dependabot/dependabot-core

helpers/javascript/package.json, helpers/javascript/yarn.lock
Reverts dependabot/dependabot-core#25
=> Revert "Bump fs-extra from 3.0.1 to 4.0.1 in /helpers/javascript"

lib/dependabot/file_fetchers/ruby/bundler.rb, lib/dependabot/file_parsers/ruby/bundler.rb, lib/dependabot/file_updaters/ruby/bundler.rb, lib/dependabot/update_checkers/ruby/bundler.rb, spec/dependabot/file_fetchers/ruby/bundler_spec.rb, spec/dependabot/file_parsers/ruby/bundler_spec.rb, spec/dependabot/file_updaters/ruby/bundler_spec.rb, spec/dependabot/update_checkers/ruby/bundler_spec.rb
=> Handle Ruby repos with just a Gemfile

dependabot-core.gemspec, lib/dependabot/dependency_file.rb, lib/dependabot/file_fetchers.rb, lib/dependabot/file_fetchers/git/submodules.rb, lib/dependabot/file_parsers.rb, lib/dependabot/file_parsers/git/submodules.rb, lib/dependabot/file_updaters.rb, lib/dependabot/file_updaters/git/submodules.rb, lib/dependabot/metadata_finders.rb, lib/dependabot/metadata_finders/git/submodules.rb, lib/dependabot/pull_request_creator.rb, lib/dependabot/pull_request_updater.rb, lib/dependabot/update_checkers.rb, lib/dependabot/update_checkers/git/submodules.rb, spec/dependabot/file_fetchers/git/submodules_spec.rb, spec/dependabot/file_parsers/git/submodules_spec.rb, spec/dependabot/file_updaters/git/submodules_spec.rb, spec/dependabot/metadata_finders/git/submodules_spec.rb, spec/dependabot/pull_request_creator_spec.rb, spec/dependabot/pull_request_updater_spec.rb, spec/dependabot/update_checkers/git/submodules_spec.rb, spec/fixtures/git/gitmodules/.gitmodules, spec/fixtures/github/gitmodules.json, spec/fixtures/github/submodule.json
Should be really straightforward...
=> Add git submodules support

helpers/php/bin/run.php, spec/dependabot/update_checkers/php/composer_spec.rb, spec/fixtures/php/composer_files/alternative_source, spec/fixtures/php/composer_files/autoload, spec/fixtures/php/lockfiles/alternative_source, spec/fixtures/php/lockfiles/autoload
Pending specs for two bugs we've seen in production.
=> [WIP] PHP bug(s)

circle.yml
=> Specify that we want PHP 7.1

helpers/python/lib/parser.py, lib/dependabot/file_parsers/python/pip.rb, lib/dependabot/file_updaters/python/pip.rb, spec/dependabot/file_parsers/python/pip_spec.rb, spec/dependabot/file_updaters/python/pip_spec.rb, spec/dependabot/update_checkers/python/pip_spec.rb
Our previous strategy was... optimistic. 🙈
=> Parse the file a python requirement comes from correctly

lib/dependabot/file_updaters/ruby/bundler.rb, lib/dependabot/git_commit_checker.rb, lib/dependabot/update_checkers/ruby/bundler.rb, lib/dependabot/update_checkers/ruby/bundler/file_preparer.rb, lib/dependabot/update_checkers/ruby/bundler/requirements_updater.rb, spec/dependabot/file_updaters/ruby/bundler_spec.rb, spec/dependabot/git_commit_checker_spec.rb, spec/dependabot/update_checkers/ruby/bundler/file_preparer_spec.rb, spec/dependabot/update_checkers/ruby/bundler/requirements_updater_spec.rb, spec/dependabot/update_checkers/ruby/bundler_spec.rb
Generate diffs such as:
```diff
-gem "business", git: "https://github.com/gocardless/business", tag: "v1.0.0"
+gem "business", git: "https://github.com/gocardless/business", tag: "v1.1.0"
```
=> Update Ruby git tags

lib/dependabot/file_updaters/README.md, lib/dependabot/file_updaters/base.rb, lib/dependabot/file_updaters/ruby/bundler.rb, lib/dependabot/update_checkers/README.md, lib/dependabot/update_checkers/base.rb, lib/dependabot/update_checkers/git/submodules.rb, lib/dependabot/update_checkers/ruby/bundler.rb, lib/dependabot/update_checkers/ruby/bundler/version_resolver.rb, spec/dependabot/file_updaters/base_spec.rb, spec/dependabot/file_updaters/docker/docker_spec.rb, spec/dependabot/file_updaters/git/submodules_spec.rb, spec/dependabot/file_updaters/java_script/yarn_spec.rb, spec/dependabot/file_updaters/php/composer_spec.rb, spec/dependabot/file_updaters/python/pip_spec.rb, spec/dependabot/file_updaters/ruby/bundler_spec.rb, spec/dependabot/update_checkers/base_spec.rb, spec/dependabot/update_checkers/docker/docker_spec.rb, spec/dependabot/update_checkers/git/submodules_spec.rb, spec/dependabot/update_checkers/java_script/yarn_spec.rb, spec/dependabot/update_checkers/php/composer_spec.rb, spec/dependabot/update_checkers/python/pip_spec.rb, spec/dependabot/update_checkers/ruby/bundler/version_resolver_spec.rb, spec/dependabot/update_checkers/ruby/bundler_spec.rb
Previously we just accepted a GitHub access token. In future, we'd like to support credentials for other services (e.g., gemfury).
Part of the solution to https://github.com/dependabot/feedback/issues/26.
=> [WIP] Accept an array of credentials in UpdateCheckers

lib/dependabot/file_fetchers/base.rb, lib/dependabot/pull_request_creator.rb, lib/dependabot/pull_request_creator/github.rb, spec/dependabot/file_fetchers/base_spec.rb, spec/dependabot/pull_request_creator_spec.rb, spec/fixtures/github/ref_my_branch.json
Backed for https://github.com/dependabot/feedback/issues/17.
=> Add support for passing a target branch to create PRs against

lib/dependabot/file_parsers/java_script/yarn.rb, lib/dependabot/file_updaters/java_script/base.rb, spec/dependabot/file_updaters/java_script/npm_spec.rb, spec/dependabot/file_updaters/java_script/yarn_spec.rb, spec/fixtures/javascript/package_files/package.json
Fixes the underlying issue in https://github.com/dependabot/feedback/issues/42.
=> JS: Sanitize any variables in a package.json before parsing/updating

lib/dependabot/file_updaters/java_script/base.rb, spec/dependabot/file_updaters/java_script/yarn_spec.rb, spec/fixtures/javascript/package_files/other_package.json, spec/fixtures/javascript/package_files/package1.json, spec/fixtures/javascript/package_files/workspaces.json, spec/fixtures/javascript/yarn_lockfiles/workspaces.lock
Updates the JavaScript `FileUpdater` to handle workspaces.
=> [WIP] Yarn Workspaces [2/2]

helpers/npm/lib/updater.js, helpers/yarn/lib/updater.js, helpers/yarn/test/updater.test.js, lib/dependabot/file_updaters/java_script/base.rb, spec/dependabot/file_updaters/java_script/yarn_spec.rb
Updates `Yarn::FileUpdater` to support workspaces.
TODO:
- More tests (particularly of generated `yarn.lock`, and in JS)
- Review from someone who actually knows how to write JS
=> [WIP] Yarn workspaces [2/2 again]

helpers/python/lib/parser.py, lib/dependabot/file_fetchers/python/pip.rb, lib/dependabot/file_parsers/python/pip.rb, lib/dependabot/file_updaters/python/pip.rb, spec/dependabot/file_fetchers/python/pip_spec.rb, spec/dependabot/file_parsers/python/pip_spec.rb, spec/fixtures/github/contents_python.json, spec/fixtures/github/contents_python_only_requirements.json, spec/fixtures/github/contents_python_only_setup.json, spec/fixtures/github/contents_python_repo.json, spec/fixtures/github/contents_requirements_folder.json
Adds FileFetcher to #135.
TODO (GB):
=> Python: support alternative names / locations for requirements.txt files

helpers/php/src/Updater.php, lib/dependabot/file_fetchers/php/composer.rb, lib/dependabot/file_parsers/php/composer.rb, lib/dependabot/file_updaters/php/composer.rb, lib/dependabot/update_checkers/java_script/npm_and_yarn/requirements_updater.rb, lib/dependabot/update_checkers/php/composer.rb, lib/dependabot/update_checkers/php/composer/requirements_updater.rb, spec/dependabot/file_fetchers/php/composer_spec.rb, spec/dependabot/file_parsers/php/composer_spec.rb, spec/dependabot/file_updaters/php/composer_spec.rb, spec/dependabot/update_checkers/php/composer/requirements_updater_spec.rb, spec/dependabot/update_checkers/php/composer_spec.rb, spec/fixtures/github/composer_json_content.json, spec/fixtures/github/composer_lock_content.json
That. Closes https://github.com/dependabot/feedback/issues/28.
TODO:
=> [WIP] Support PHP libraries

helpers/elixir/bin/run.exs, spec/dependabot/file_parsers/elixir/hex_spec.rb, spec/fixtures/elixir/lockfiles/old_elixir, spec/fixtures/elixir/mixfiles/old_elixir
Thought this was going to be a problem. Turns out not to be a problem. 🎉
=> Handle old Elixir versions

lib/dependabot/file_parsers/elixir/hex.rb
Assume Hex is always installed on the machine.
=> Remove hex install in Elixir file parser

helpers/python/lib/parser.py, helpers/python/requirements.txt
Pip 10 adds resolution logic to Pip, which is awesome. Unfortunately it's in the form of warning messages post-install, rather than resolution pre-install, but it's a step in the right direction.
=> Use pip10 beta

lib/dependabot/metadata_finders/ruby/bundler.rb, spec/dependabot/metadata_finders/ruby/bundler_spec.rb
Sometimes private gemserves haven't implemented the latest Rubygems API. In this case, if the latest version for a dependency matches the latest version listed on Rubygems, it's probably fine to take the Rubygems response instead.
=> Augment private gemserver info with Rubygems details if appropriate

helpers/elixir/bin/check_update.exs, helpers/elixir/bin/do_update.exs, helpers/elixir/bin/run.exs, lib/dependabot/file_updaters/elixir/hex.rb, lib/dependabot/shared_helpers.rb, lib/dependabot/update_checkers/elixir/hex/version_resolver.rb, spec/dependabot/update_checkers/elixir/hex/version_resolver_spec.rb, spec/dependabot/update_checkers/elixir/hex_spec.rb, spec/fixtures/elixir/lockfiles/diverging_environments, spec/fixtures/elixir/lockfiles/private_package, spec/fixtures/elixir/mixfiles/private_package
WIP for https://github.com/dependabot/feedback/issues/107.
=> Elixir: Add support for private repos

lib/dependabot/pull_request_creator/message_builder.rb, spec/dependabot/pull_request_creator/message_builder_spec.rb, spec/fixtures/github/commits_gitmoji.json
support of gitmoji commit messages : https://gitmoji.carloscuesta.me
done like https://github.com/dependabot/dependabot-core/commit/77bd3b823d740c65d3a89f1e7027a3ca4fbf09e9 to only happen when repo already use gitmoji
=> gitmoji commit messages if repo uses them

spec/dependabot/update_checkers/ruby/bundler/version_resolver_spec.rb, spec/fixtures/ruby/gemfiles/jruby, spec/fixtures/ruby/lockfiles/jruby.lock
Currently just a failing spec. Bundler issue is [here](https://github.com/bundler/bundler/issues/6350).
=> [Awaiting Bundler update] Add spec for JRuby support

helpers/elixir/bin/parse_deps.exs, spec/dependabot/file_parsers/elixir/hex_spec.rb, spec/fixtures/elixir/lockfiles/regex_version, spec/fixtures/elixir/mixfiles/regex_version
=> Elixir: Handle regex versions in FileParser

lib/dependabot/file_updaters/python/pip/pip_compile_file_updater.rb, lib/dependabot/file_updaters/python/pip/requirement_replacer.rb, lib/dependabot/update_checkers/python/pip.rb, lib/dependabot/update_checkers/python/pip/pip_compile_version_resolver.rb, lib/python_requirement_parser.rb, spec/dependabot/file_parsers/python/pip_spec.rb, spec/dependabot/file_updaters/python/pip/pip_compile_file_updater_spec.rb, spec/dependabot/file_updaters/python/pip/requirement_replacer_spec.rb, spec/dependabot/update_checkers/python/pip/pip_compile_version_resolver_spec.rb, spec/fixtures/python/requirements/pip_compile_bounded.txt, spec/fixtures/python/requirements/pip_compile_hashes.txt, spec/fixtures/python/requirements/pip_compile_unpinned.txt
=> Python: Consider ignored versions when determining updates for pip-compile setups

helpers/npm/lib/updater.js, helpers/yarn/lib/fix-duplicates.js, helpers/yarn/lib/replace-lockfile-declaration.js, helpers/yarn/lib/updater.js, lib/dependabot/file_updaters/php/composer.rb, lib/dependabot/update_checkers/java_script/npm_and_yarn.rb, lib/dependabot/update_checkers/java_script/npm_and_yarn/version_resolver.rb, spec/dependabot/file_updaters/java_script/npm_and_yarn_spec.rb, spec/dependabot/update_checkers/java_script/npm_and_yarn_spec.rb
Identical rational as https://github.com/dependabot/dependabot-core/pull/497, but for JS.
=> JS: Consider ignored versions when determining version to update to

helpers/python/requirements.txt, lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb, spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb
=> Use latest pipenv

.circleci/config.yml, Dockerfile, helpers/elixir/bin/check_update.exs, helpers/elixir/bin/do_update.exs, lib/dependabot/file_updaters/go/dep/lockfile_updater.rb, lib/dependabot/update_checkers/elixir/hex.rb, spec/dependabot/file_updaters/go/dep/lockfile_updater_spec.rb
Needs a new Dockerfile version.
=> Bump Elixir to 1.7.0

lib/dependabot/file_fetchers/terraform/terraform.rb, lib/dependabot/file_parsers/terraform/terraform.rb, lib/dependabot/file_updaters/terraform/terraform.rb, spec/dependabot/file_fetchers/terraform/terraform_spec.rb, spec/dependabot/file_parsers/terraform/terraform_spec.rb, spec/dependabot/file_updaters/terraform/terraform_spec.rb, spec/fixtures/github/contents_terragrunt_repo.json, spec/fixtures/terraform/config_files/terragrunt.tfvars
=> [WIP] Fetch Terragrunt files in terraform file fetcher

lib/dependabot/update_checkers/java/maven/property_updater.rb, spec/dependabot/update_checkers/java/maven/property_updater_spec.rb
=> Maven: Allow multi-dependency property updates where some deps can't be found

helpers/python/requirements.txt, spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb
Temporary measure until we get a new release.
=> Use git commit for pipenv

lib/dependabot/file_fetchers/python/pip.rb, lib/dependabot/file_parsers/python/pip.rb, lib/dependabot/file_parsers/python/pip/poetry_files_parser.rb, lib/dependabot/file_updaters/python/pip.rb, lib/dependabot/file_updaters/python/pip/poetry_file_updater.rb, lib/dependabot/update_checkers/python/pip.rb, lib/dependabot/update_checkers/python/pip/poetry_version_resolver.rb, spec/dependabot/file_parsers/python/pip/poetry_files_parser_spec.rb, spec/dependabot/file_updaters/python/pip/pip_compile_file_updater_spec.rb, spec/dependabot/file_updaters/python/pip/poetry_file_updater_spec.rb, spec/dependabot/update_checkers/python/pip/pip_compile_version_resolver_spec.rb, spec/dependabot/update_checkers/python/pip/poetry_version_resolver_spec.rb
See https://github.com/dependabot/feedback/issues/218 for details of Poetry's plans.
=> Support poetry.lock

lib/dependabot/clients/gitlab.rb, lib/dependabot/file_fetchers/base.rb, lib/dependabot/metadata_finders/base/changelog_finder.rb, lib/dependabot/metadata_finders/base/commits_finder.rb, lib/dependabot/metadata_finders/base/release_finder.rb, lib/dependabot/pull_request_creator/gitlab.rb, lib/dependabot/pull_request_creator/message_builder.rb
Here my proposal for factories for the gitlab api clients
=> Add factories for gitlab api clients

README.md
Fixes https://github.com/dependabot/feedback/issues/51
=> Doc to the API

lib/dependabot/file_fetchers/base.rb
So I think there was a problem with a merge conflict because some of this commit 
https://github.com/dependabot/dependabot-core/commit/872d1e1b34810919e063d2ad2af464ac2184841b#diff-a070713328dadb73fbfd7bb2bc50a912
have disappeared
=> Fix issues raised by merge conflicts

lib/dependabot/file_updaters/python/pip/pipfile_file_updater.rb, lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb
Fixes https://sentry.io/dependabot/backend/issues/583369474. Needs a test.
=> Python: Raise original error correctly depending on Python version in use

.rubocop.yml, helpers/python/lib/parser.py, helpers/python/requirements.txt, lib/dependabot/file_updaters/python/pip/pipfile_file_updater.rb, lib/dependabot/file_updaters/python/pip/setup_file_sanitizer.rb, lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb, spec/dependabot/file_parsers/python/pip/setup_file_parser_spec.rb, spec/dependabot/file_parsers/python/pip_spec.rb, spec/dependabot/file_updaters/python/pip/setup_file_sanitizer_spec.rb, spec/fixtures/python/setup_files/small.py, spec/fixtures/python/setup_files/small_needs_sanitizing.py
Fixes https://sentry.io/dependabot/backend/issues/768525518/
=> Use latest pipenv commit

helpers/python/requirements.txt
=> Bump pipenv commit

lib/dependabot/file_updaters/java_script/npm_and_yarn/yarn_lockfile_updater.rb
Currently, Dependabot will raise an internal error if it encounters a *new* scoped package that causes resolution errors.
That case can occur when a scoped package has been added as a sub-dependency and Dependabot doesn't have access to it. This is most likely to be due to a resolvability error, rather than a private repos error.
This PR updates Dependabot's error handling logic to raise a `Dependabot::DependencyFileNotResolvable` error in those cases, with details of what Dependabot was trying to update.
=> Raise a resolvability error when a scoped package can't be found

lib/dependabot/update_checkers/docker/docker.rb
=> Fix typo: replace WTIH -> WITH

helpers/php/bin/run.php
This commit changes the memory_limit logic used when resolving composer dependencies. Previously, the limit of 1900 MB was always set, even if the limit configured in php.ini was higher. With the change applied, we always respect an infinite memory limit (denoted by memory_limit=-1) as well as a limit higher than what is configured here. The COMPOSER_MEMORY_LIMIT env setting will always override any previously configured values.
The reason for the change is that the PHP helper is run with `memory_limit=-1` (see [`version_resolver.rb`](https://github.com/dependabot/dependabot-core/blob/61e79897c8c79ef0fb2e2c3c23ca8050fcf02754/lib/dependabot/update_checkers/php/composer/version_resolver.rb#L61)), but this limit is immediately overwritten by the 1900M setting in `run.php`.
// cc @ruudk
=> Improve memory limit handling in PHP helper

.circleci/config.yml
Build from PR #888 is failing due to missing environment variables.
=> Don't require docker creds for CI builds

lib/dependabot/utils/java_script/requirement.rb, spec/dependabot/utils/java_script/requirement_spec.rb
Fixes: https://github.com/dependabot/feedback/issues/297
If you supply a version requirement of `^0` or `~0` it will now satisfy
`< 1.0`.
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
If you supply a version range requirement with missing minor/patch, e.g.
`1.0.0 - 2` it will now satisfy `>= 1.0.0 && < 3.0.0.a`.
https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-
=> JS: Handle ~ and ^ with blank minor.patch version

README.md, helpers/npm/package-lock.json
Npm users have npm, its unfair to have them install yarn :).
I tried without thoroughly (?) testing, it seems to work.
=> Simplify npm usage instructions

Dockerfile
=> Use Elixir 1.8.0

cargo/lib/dependabot/cargo/file_fetcher.rb, cargo/lib/dependabot/cargo/file_parser.rb, cargo/lib/dependabot/cargo/file_updater.rb, cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb, cargo/spec/dependabot/cargo/file_fetcher_spec.rb, cargo/spec/dependabot/cargo/file_parser_spec.rb, lib/dependabot/dependency_file.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
Adds back commits lost in the great history rewriting of January 2019.
=> Old master

composer/helpers/setup.sh
Follows official recommendation: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
> Please do not redistribute the install code. [doc](https://getcomposer.org/download/)
=> Recommended Composer programmatically install

README.md
There's still plenty more detail we could include, but I think this is a step in the right direction.
=> Update README to reflect the reorg

Dockerfile
=> Add bzr to the Dockerfile

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb, go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
=> Go (modules): handle another case of module path mismatches

nuget/lib/dependabot/nuget/file_fetcher.rb, nuget/lib/dependabot/nuget/file_parser.rb, nuget/lib/dependabot/nuget/file_parser/global_json_parser.rb, nuget/lib/dependabot/nuget/file_updater.rb, nuget/spec/dependabot/nuget/file_fetcher_spec.rb, nuget/spec/dependabot/nuget/file_parser/global_json_parser_spec.rb, nuget/spec/dependabot/nuget/file_parser_spec.rb, nuget/spec/dependabot/nuget/file_updater_spec.rb, nuget/spec/fixtures/github/contents_dotnet_repo_global.json, nuget/spec/fixtures/global_jsons/global.json
=> .NET: Update NuGet packages in global.json

go_modules/lib/dependabot/go_modules/update_checker.rb
=> Retry transitory Go resolution issues

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
Adding a helpful error when private registry returns a `403 Fobidden`
error, this is not a common thing and seems only specific to a single
private registry so far.
Fixes sentry: https://sentry.io/organizations/dependabot/issues/958867122/events/d9d55b2eedeb4c0c989fad461710e154/
=> NPM: Handle private registry error '403 Fobidden'

python/lib/dependabot/python/file_updater/pipfile_file_updater.rb, python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb, python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
Fixes https://github.com/dependabot/feedback/issues/449.
=> Python: Update to a specific version when updating Pipenv subdependencies

Dockerfile
=> Upgrade to PHP 7.3

bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb, bundler/lib/dependabot/bundler/update_checker/force_updater.rb, bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb, bundler/spec/dependabot/bundler/file_updater_spec.rb, bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb, bundler/spec/fixtures/ruby/gemfiles/default_gem_specified, bundler/spec/fixtures/ruby/lockfiles/default_gem_specified.lock
Adds a minimal failing test for handling gemfiles with a default gem in them. Fix is a WIP.
=> Handle gemfiles that specify a default gem

go_modules/lib/dependabot/go_modules/file_parser.rb, go_modules/spec/dependabot/go_modules/file_parser_spec.rb
Should fix https://github.com/dependabot/dependabot-core/issues/1172.
=> Go (modules): handle local module replacements

gradle/lib/dependabot/gradle.rb, gradle/spec/dependabot/gradle_spec.rb, maven/lib/dependabot/maven.rb, maven/spec/dependabot/maven_spec.rb
Fixes https://github.com/dependabot/feedback/issues/513.
=> Maven, Gradle: Special case display name for undescriptive artifact IDs

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
Similar to https://github.com/dependabot/dependabot-core/pull/1193, but in the updater
=> Go (modules): handle replace directive in updater

common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb, common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb
Part of the fix for https://github.com/dependabot/feedback/issues/551 (rest is in Dependabot Backend).
=> Handle custom commit message prefixes for dev dependencies

Dockerfile
That. Should fix https://github.com/dependabot/feedback/issues/597.
=> Bump elixir version in Dockerfile

go_modules/helpers/go.mod, go_modules/helpers/go.sum
See:
- https://github.com/dependabot/feedback/issues/617
- https://github.com/dependabot/gomodules-extracted/issues/2
=> Bump gomodules-extracted (on branch currently)

common/lib/dependabot/pull_request_creator/github.rb, common/spec/dependabot/pull_request_creator/github_spec.rb
Sometimes we want to be able to recreate merged pull requests (if, for example, they get merged by accident and then reverted). We should therefore ignore them when searching for existing pull requests.
(Note: the same does *not* apply for closed PRs, which can just be re-opened by the user.)
=> Ignore merged PRs in PullRequestCreator::GitHub

terraform/lib/dependabot/terraform/file_parser.rb, terraform/spec/dependabot/terraform/file_parser_spec.rb, terraform/spec/fixtures/config_files/registry.tf
Fix for bug identified in https://github.com/aoggz/terraform-aws-fargate-service/issues/1.
=> Terraform: Handle registry dependencies that specify a sub-directory

bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
Fixes https://sentry.io/organizations/dependabot/issues/1144420868/?environment=default&project=1425239&referrer=alert_email.
=> Bundler: Tighter check on source being Rubygems

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb, composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/fixtures/composer_files/missing_extension, composer/spec/fixtures/composer_files/old_php_specified
=> PHP: Stricter regex for finding missing extensions and PHP versions

gradle/lib/dependabot/gradle/metadata_finder.rb, maven/lib/dependabot/maven/file_parser/property_value_finder.rb, maven/lib/dependabot/maven/metadata_finder.rb, maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb, maven/spec/fixtures/poms/multimodule_pom.xml
Fixes https://sentry.io/organizations/dependabot/issues/1145422525/?environment=default&project=1425239&referrer=alert_email.
=> Maven: Improve dot separator regex to fix XML searching bug

common/lib/dependabot/git_commit_checker.rb, common/lib/dependabot/git_metadata_fetcher.rb, common/spec/dependabot/git_metadata_fetcher_spec.rb
Refactors `GitMetadataFinder` to include logic for finding the commit SHA of a given ref. This logic will be useful in `PullRequestCreator::Github` to check whether a merged PR is up-to-date and avoid double-creating PRs shortly after they have been merged.
=> Expose GitMetadataFinder#head_commit_for_ref method

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_preparer.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb, npm_and_yarn/spec/fixtures/package_files/package.json
That. Fixes https://sentry.io/organizations/dependabot/issues/1071300139/?environment=default&project=1425239&query=is%3Aunresolved&statsPeriod=14d.
=> JS: Better sanitization of {{ variable }} text in package.json files

python/lib/dependabot/python/file_updater/pipfile_file_updater.rb, python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb, python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
=> Python: Handle arrays of Python requirements (from pyproject.toml) in PipenvVersionResolver

composer/helpers/.php_cs
=> [Composer] Enhancement: Keep rules sorted in .php_cs

.editorconfig, composer/helpers/build, composer/helpers/composer.json, composer/helpers/composer.lock, composer/helpers/phpstan.neon
This PR
💁‍♂ For reference, see https://github.com/phpstan/phpstan.
=> [Composer] Enhancement: Require and run phpstan/phpstan

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb, composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb, composer/spec/dependabot/composer/update_checker_spec.rb, composer/spec/fixtures/composer_files/git_source_conflict_at_latest, composer/spec/fixtures/lockfiles/git_source, composer/spec/fixtures/lockfiles/git_source_bad_commit, composer/spec/fixtures/lockfiles/git_source_conflict_at_latest
Fixes https://github.com/dependabot/feedback/issues/560.
=> Composer: Don't update the commit SHA for git dependencies when doing other updates

composer/lib/dependabot/composer/file_parser.rb, composer/lib/dependabot/composer/update_checker.rb, composer/spec/dependabot/composer/file_parser_spec.rb, composer/spec/dependabot/composer/update_checker_spec.rb, composer/spec/fixtures/composer_files/git_source_transitive, composer/spec/fixtures/lockfiles/git_source_transitive
Adds support for the use of stability flags in the parser and update checker when the update source is git.
Paired w/@greysteil
=> Composer: Support stability flags in parser and update checker

composer/helpers/phpstan.neon, composer/helpers/src/Hasher.php, composer/helpers/src/Updater.php
=> [Composer] Enhancement: Raise phpstan level from 5 to 6

composer/helpers/src/UpdateChecker.php
This PR
💁‍♂ Let me know if you'd prefer me to squash the commits - I've tried to make small, reviewable changes for ease of review.
=> [Composer] Enhancement: Clean up UpdateChecker

bin/docker-dev-shell
Lets you provide a custom image name, Docker network, and HTTP proxy.
=> Allow a few options to be provided to the dev shell

gradle/lib/dependabot/gradle/version.rb, gradle/spec/dependabot/gradle/version_spec.rb
Fixes https://github.com/dependabot/feedback/issues/684
=> Gradle: Support pre-release syntax 1.0.0pr

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb, npm_and_yarn/spec/fixtures/npm_lockfiles/invalid_version_requirement.json, npm_and_yarn/spec/fixtures/npm_lockfiles/subdependency_update_preserved_indentation.json
https://sentry.io/organizations/github/issues/1039714090/events/241628f309684181a704b37ae015d41d/?project=1451818&statsPeriod=14d
=> JS: handle malformed lockfile versions

bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
Reverts dependabot/dependabot-core#1409
=> Revert "Bundler: Fall back to unlocking all sub-dependencies in lockfile updater"

bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
Reverts dependabot/dependabot-core#1414
=> Revert "Revert "Bundler: Fall back to unlocking all sub-dependencies in lockfile updater""

python/lib/dependabot/python/file_fetcher.rb, python/spec/dependabot/python/file_fetcher_spec.rb
=> Python: Fetch path dependency files relative to directory they're required in

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb, common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
Sanitizing usernames that came after a code block without spaces around the code ticks, for example:
```
```@command```\nThanks to @feelepxyz
```
Refactored the code block matching to use `StringScanner` as I couldn't
make the new cases work with the existing regex.
Fixes https://github.com/dependabot/dependabot-core/issues/1421
=> Improve @mention sanitizer for compact code blocks

gradle/lib/dependabot/gradle/file_parser.rb, gradle/lib/dependabot/gradle/update_checker.rb, gradle/spec/dependabot/gradle/file_parser_spec.rb, gradle/spec/dependabot/gradle/update_checker_spec.rb, gradle/spec/fixtures/buildfiles/shortform_build.gradle
=> Support Gradle updates that use git dependencies

common/lib/dependabot/metadata_finders/base/changelog_finder.rb
Fixes https://github.com/dependabot/feedback/issues/708.
=> Add whatsnew as a CHANGELOG name

dep/spec/dependabot/dep/file_updater/lockfile_updater_spec.rb, dep/spec/dependabot/dep/update_checker/version_resolver_spec.rb, dep/spec/dependabot/dep/update_checker_spec.rb
Someone on the internet pushed to their repo so now we have to update all the dep specs with new hard coded values 🤦‍♂
We really need to fix this testing setup.
=> Update dep specs

Dockerfile, python/helpers/build, python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb, python/lib/dependabot/python/file_updater/pipfile_file_updater.rb, python/lib/dependabot/python/python_versions.rb, python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb, python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb, python/spec/dependabot/python/file_parser_spec.rb, python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb, python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb, python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb, python/spec/fixtures/lockfiles/required_python.lock, python/spec/fixtures/pipfiles/required_python
Pyenv 1.2.15, with Python 3.7.4 and 2.7.17.
Fixes #1491.
=> Upgrade Python versions

docker/lib/dependabot/docker/file_updater.rb, docker/spec/dependabot/docker/file_updater_spec.rb, docker/spec/fixtures/docker/dockerfiles/multi_stage_different_tags
PR raised to address the issue described in https://github.com/dependabot/dependabot-core/issues/1479
Test case added to reproduce the scenario.
Any feedback on a better way to solve this is appreciated!
=> Support mix of docker tags for the same image

common/lib/dependabot/pull_request_creator.rb, common/lib/dependabot/pull_request_creator/message_builder.rb, common/spec/dependabot/pull_request_creator/message_builder_spec.rb
Addresses https://github.com/dependabot/dependabot-core/issues/1525
Gives more customizability options when creating a pull request using dependabot.
=> Pull request: Add pull request message header support

Dockerfile, python/helpers/build, python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
Fixes https://github.com/dependabot/dependabot-core/issues/1542
=> Bump global Python from 3.7.5 to 3.8.0

Dockerfile, python/helpers/build, python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
Set global Python version to 3.8.1
=> Bump Python 3.8.1 & 3.7.6

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb, common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
Fixes https://github.com/dependabot/feedback/issues/871
=> Sanitize github ref links in plaintext/rdoc

Dockerfile
Fixes https://github.com/dependabot/dependabot-core/issues/1730
=> Upgrade to PHP 7.4

python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
=> Adds python 3.7.7

common/dependabot-common.gemspec, common/lib/dependabot/pull_request_updater.rb, common/lib/dependabot/pull_request_updater/gitlab.rb, common/spec/dependabot/pull_request_updater/gitlab_spec.rb, common/spec/dependabot/pull_request_updater_spec.rb
Thank you for creating dependabot! It's a nice project and so much usefull :star_struck: .
This PR will help to let dependabot rebase its branches to fix merge request conflicts.
Fixes #1603
We could then fix https://github.com/dependabot/dependabot-script/issues/306.
=> Add pull_request_updater for Gitlab

github_actions/lib/dependabot/github_actions/file_fetcher.rb
=> Fix: Use directory instead of repo

.github/workflows/ci.yml
=> Fix: Run workflow on pull requests as well

composer/helpers/composer.json, composer/helpers/composer.lock
This PR
💁‍♂️ For reference, see `Dockerfile`:
https://github.com/dependabot/dependabot-core/blob/dd510deaebce566f029adb7261d0d98fc65df49f/Dockerfile#L103.
=> [composer] Fix: Require PHP 7.4

Dockerfile
This PR
💁‍♂️ Keeping this list wrapped and sorted makes it easier to spot packages, and also easier to decide where to add additional packages if need be.
=> [composer] Fix: Wrap and sort packages in Dockerfile

composer/helpers/src/DependabotInstallationManager.php, composer/helpers/src/ExceptionIO.php
=> [composer] Enhancement: Use property type declarations where possible

composer/helpers/src/DependabotInstallationManager.php, composer/helpers/src/DependabotPluginManager.php, composer/helpers/src/ExceptionIO.php, composer/helpers/src/Hasher.php, composer/helpers/src/UpdateChecker.php, composer/helpers/src/Updater.php
This PR
💁‍♂️ There's probably no reason to extend these classes.
=> [composer] Fix: Mark classes as final

.github/workflows/ci.yml, .github/workflows/docker.yml
We should be able to restore caching now and added a new branch-ref tag so the same branch should get quicker-rebuilds.
=> Add docker caching and fix ci for forks

.github/workflows/ci.yml
We do not want other jobs to get cancelled when one of them fails.
=> Don't fail-fast in matrix

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb, nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb, nuget/spec/fixtures/nuget_responses/v2_no_base.xml
Pulled in from https://github.com/dependabot/dependabot-core/pull/1472 so I can rebase / fix up any failures and finally get this merged.
Thanks @ppejovic !
=> Nuget base fix

composer/helpers/build
dependabot-core embeds a composer project which contains helpers for updating php/composer projects.
During installation, we call [composer install](https://github.com/dependabot/dependabot-core/blob/main/composer/helpers/build#L15) on this project, leaving some cruft in the docker layer:
```
root@5641fa836168:/home/dependabot/dependabot-core# du -csh ~/.composer/cache/
71M	/root/.composer/cache/
71M	total
```
If we assume users of Dependabot follow the [example](https://github.com/dependabot/dependabot-core/blob/main/Dockerfile.development#L19-L20)/best practice of not running as the root user, this cache won't be reused at runtime.
<details>
<summary>file list</summary>
```
root@5641fa836168:/home/dependabot/dependabot-core# find ~/.composer/cache
/root/.composer/cache …
```
=> composer: remove root cache

common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
Fast-follow on https://github.com/dependabot/dependabot-core/pull/2539 to DRY out the text truncation method
=> Cleanup text quoting and truncation

common/lib/dependabot/shared_helpers.rb
Fixes https://github.com/dependabot/dependabot-core/issues/2566
=> Fix uninitialized constant error when using SharedHelpers

Dockerfile
Also verify checksum after downloading.
=> Upgrade golang to v1.15.2

CHANGELOG.md, common/lib/dependabot/version.rb
This pull request includes a proposed changelog and version bump for a 0.120.4 release.
=> Prepare CHANGELOG and version bump for 0.120.4

bundler/helpers/lib/functions.rb, bundler/helpers/lib/functions/dependency_source.rb, bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb, bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb, bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb, bundler/spec/dependabot/bundler/update_checker_spec.rb, bundler/spec/native_helpers/functions/dependency_source_spec.rb
Implements the native call-outs for the bundler version finder.
=> Extract LatestVersionFinder bundler calls to a native helper

CHANGELOG.md, common/lib/dependabot/version.rb
I liked @jasonrudolph's example of PR'ing these changes
=> Release notes for v0.120.5

CHANGELOG.md, common/lib/dependabot/version.rb
Co-authored-by: Jurre Stender <jurre@github.com>
Co-authored-by: Pete Wagner <thepwagner@github.com>
=> Release notes and version bump for v0.121.0

bin/dry-run.rb
Parse a json hash of security advisories when running bin/run.
Example:
```
export SECURITY_ADVISORIES='[{"dependency_name":"node-forge","patched_versions":[],"unaffected_versions":[],"affected_versions":["< 0.10.0"]}]'
bin/dry-run.rb npm_and_yarn "account/repo" --dir="/." --dep="node-forge" --cache=files
```
=> bin/dry-run: Parse SECURITY_ADVISORIES ENV

Dockerfile
https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#1221
=> Upgrade pyenv to v1.2.21

Dockerfile, python/helpers/build, python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
New Python version, new update PR :slightly_smiling_face:
=> Add Python 3.9

CHANGELOG.md, common/lib/dependabot/version.rb
This pull request proposes release notes for the v0.124.0 release.
=> Release notes for v0.124.0

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/dependency_files_builder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb
Originally part of
https://github.com/dependabot/dependabot-core/pull/2732, but as that PR
was getting quite big, I've moved the refactor here. We need this class
in some of the code introduced in that PR, and instead of duplicating it
further, I've opted to extract it.
=> Extract DependencyFileBuilder to remove duplication

common/lib/dependabot/clients/azure.rb, common/spec/dependabot/pull_request_creator/azure_spec.rb
Azure Devops uses a character limit of 4000 characters in UTF-16
encoding, instead of Ruby's default UTF-8 encoding. This causes issues
with special characters like Emoji, which count as 2 characters in
UTF-8, but as 4 characters in UTF-16.
=> Check Azure PR description against utf-16 encoded length

.github/workflows/ci.yml, .github/workflows/docker.yml
Attempting to fix broken actions ci runs where docker build exits with
code 137.
=> Set docker memory to 4g

bundler/helpers/lib/functions.rb, bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb, bundler/lib/dependabot/bundler/update_checker/conflicting_dependency_resolver.rb, bundler/lib/dependabot/bundler/update_checker/force_updater.rb, bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb, bundler/spec/dependabot/bundler/update_checker_spec.rb
Fixes #2657. There probably ought to be another test file, or this test added in more places, to be more complete, but I'm can't spend any more time, so this will have to do for now.
=> Bundler ignores extra nonrelevant credentials

CHANGELOG.md, common/lib/dependabot/version.rb
* https://github.com/dependabot/dependabot-core/pull/2848
=> v0.128.1 release notes

.github/workflows/ci.yml, python/helpers/lib/hasher.py, python/helpers/lib/parser.py, python/helpers/requirements.txt
@feelepxyz as recommended at https://github.com/dependabot/dependabot-core/pull/1376#issuecomment-748133905
=> GitHub Action: Add Python flake8 linting

common/lib/dependabot/clients/azure.rb, common/spec/dependabot/clients/azure_spec.rb
A typo went undetected in #2908 :(
=> [minor] Fix typo in Azure client - Availaible -> Available

common/lib/dependabot/clients/bitbucket.rb
Fixes #2917.
I'm not sure if this needs tests or how to add tests for this.
=> Add access token support for Bitbucket.

common/lib/dependabot/clients/bitbucket.rb, common/lib/dependabot/pull_request_creator.rb, common/lib/dependabot/pull_request_creator/bitbucket.rb, common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
This should fix #2919, but depends on #2918.
This gets us most of the way, but I'd appreciate some help polishing it off.
I was able to successfully create a PR with Bitbucket Cloud by modifying dependabot-script (cf. dependabot/dependabot-script#514), but I haven't added any automated tests because I don't really know where to start.
I also had a few questions as I was going through the code. I'll add review comments below.
=> Support PR creation on Bitbucket

common/lib/dependabot/utils.rb
=> Added require "set" to utils.rb

Dockerfile
* [`df596bf4c`](https://github.com/npm/cli/commit/df596bf4c10d6917672579cc38800f5e846002bc)
fix(publish): follow all configs for registry auth check
[#2602](https://github.com/npm/cli/issues/2602)
([@wraithgar](https://github.com/wraithgar))
* [`6d7afb03c`](https://github.com/npm/cli/commit/6d7afb03cd7602b60e709516711a2f94cd61ff25)
[#2613](https://github.com/npm/cli/issues/2613)
install script: pass -q to curl calls to disable user .curlrc files
([@nlf](https://github.com/nlf))
* [`3294fed6f`](https://github.com/npm/cli/commit/3294fed6f18626516978c21fac5f28ecfdb58124)
`pacote@11.2.5`
* prevent infinite recursion in git dep preparation
* [`0f7a3a87c`](https://github.com/npm/cli/commit/0f7a3a87c12e30bdd2cdab596ca6511de787c969)
`read-package-json-fast@2.0.1`
* avoid duplicating …
=> Update npm to 7.5.3 in dockerfile

npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb, npm_and_yarn/spec/fixtures/projects/npm6/etag_no_lockfile/package.json, npm_and_yarn/spec/fixtures/projects/npm6/peer_dependency_typescript_no_lockfile/package.json
Part of our ongoing effort to convert all npm specs
=> npm: Convert UpdateChecker specs to projects

bundler/helpers/v2/lib/functions.rb, bundler/helpers/v2/lib/functions/conflicting_dependency_resolver.rb, bundler/helpers/v2/spec/functions/conflicting_dependency_resolver_spec.rb, bundler/helpers/v2/spec/functions_spec.rb, bundler/spec/dependabot/bundler/update_checker/conflicting_dependency_resolver_spec.rb, bundler/spec/fixtures/projects/bundler1/subdep_blocked_by_subdep/Gemfile, bundler/spec/fixtures/projects/bundler1/subdep_blocked_by_subdep/Gemfile.lock
Adding Bundler v2 native helpers for conflicting dependency resolver.
=> Bundler [Prerelease]: Add conflicting dep resolver

npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
Looks like this array of requirements isn't ordered:
https://github.com/dependabot/dependabot-core/pull/3329/checks?check_run_id=2183109853
=> Fix flaky npm spec by checking requirements array

CONTRIBUTING.md
=> Change URL for CI

bundler/spec/dependabot/bundler/file_fetcher/child_gemfile_finder_spec.rb, bundler/spec/fixtures/projects/bundler1/eval_gemfile_absolute/Gemfile, bundler/spec/fixtures/projects/bundler1/eval_gemfile_absolute/Gemfile.lock, bundler/spec/fixtures/projects/bundler1/eval_gemfile_absolute/backend/Gemfile, bundler/spec/fixtures/projects/bundler1/eval_gemfile_nested/nested/Gemfile, bundler/spec/fixtures/projects/bundler1/eval_gemfile_nested/nested/Gemfile.lock, bundler/spec/fixtures/projects/bundler1/eval_gemfile_nested/nested/backend/Gemfile, bundler/spec/fixtures/projects/bundler1/eval_gemfile_variable/Gemfile, bundler/spec/fixtures/projects/bundler1/eval_gemfile_variable/Gemfile.lock, bundler/spec/fixtures/projects/bundler1/eval_gemfile_variable/backend/Gemfile, bundler/spec/fixtures/projects/bundler1/invalid_ruby/Gemfile
Breaks out of https://github.com/dependabot/dependabot-core/pull/3350
=> Use project fixtures for ChildGemfileFinder spec

Dockerfile
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2215-march-19-2021
=> Bump bundler to 2.2.15

.github/ISSUE_TEMPLATE/bug-report.md
When investigating a bug report, there are a handful of details that we often end up manually gathering in order to diagnose the problem. This pull request updates the template to prompt the issue author to provide these details, which gives us a better chance of being able to respond sooner.
=> 📝 Improve guidance for opening actionable bug reports

Dockerfile, python/README.md, python/helpers/build, python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
I am not sure if I also have to tweak some infra to test it 🤔
=> Adds python 3.8.9, 3.9.3 and 3.9.4, closes #3439

python/helpers/build
Workaround of https://github.com/python-poetry/poetry/issues/3010
=> Disabled poetry experimental new installer

Dockerfile.development
Looks like we need to apt-update before installing apt packages because
we deleted all the lists in Dockerfile.
=> Fix dev docker container

bin/dry-run.rb
Amends the dry-run script to accept a JSON array of "ignore conditions" as an environment variable, similar to `SECURITY_ADVISORIES`.
This is useful for rapid experimentation with ignore conditions in different ecosystems.
Like all things in the dry-run script, the parameter format is subject to change.
<details><summary>sample usage</summary>
<p>
```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb npm_and_yarn thepwagner/dependabot-test-npm --dep lodash
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> dumping fetched dependency files: ./dry-run/thepwagner/dependabot-test-npm/
=> parsing …
```
=> dry-run: ignore conditions from env

common/lib/dependabot/config/update_config.rb, common/spec/dependabot/config/update_config_spec.rb
Add wildcard dependency name filtering when finding ignore conditions
for a given dependency.
=> UpdateConfig: Match wildcards in dependency names

common/spec/dependabot/config/update_config_spec.rb
Extends https://github.com/dependabot/dependabot-core/pull/3536 with a test that exercises `Dependency.name_normaliser_for_package_manager` is applied to both dependency names and ignore condition strings.
In practice, the only registered name normaliser is for Python: https://github.com/dependabot/dependabot-core/search?q=register_name_normaliser
Since that's not available in `/common`, the test introduces a locally scoped `fake-package-manager`.
=> UpdateConfigSpec: verify name normalization

common/lib/dependabot/config/ignore_condition.rb, common/lib/dependabot/config/update_config.rb, common/spec/dependabot/config/ignore_condition_spec.rb, common/spec/dependabot/config/update_config_spec.rb
This is https://github.com/dependabot/dependabot-core/pull/3552
=> IgnoreCondition.security_updates_only

bin/dry-run.rb
dry-run: change `SECURITY_ADVISORIES` to kebab-case and find ignored
versions from `IGNORE_CONDITIONS`.
=> dry-run: change SECURITY_ADVISORIES to kebab-case

common/lib/dependabot/config/ignore_condition.rb, common/spec/dependabot/config/ignore_condition_spec.rb
I ended up shaving the yak while reviewing and getting my head around variable length semver ranges: https://github.com/dependabot/dependabot-core/pull/3588
Opening to gather some feedback on this and to check weather these test cases are actually legit and should be covered. I'm less sure about the non-numeric handling.
=> WIP: proposal to handle multi-length semver ranges

terraform/lib/dependabot/terraform/requirements_updater.rb, terraform/spec/dependabot/terraform/requirements_updater_spec.rb
I found myself having to dig a bit to figure out what this class does,
and felt some docs would have been helpful.
=> Terraform: Document and improve coverage for RequirementsUpdater

terraform/spec/dependabot/terraform/file_parser_spec.rb, terraform/spec/dependabot/terraform/file_updater_spec.rb, terraform/spec/fixtures/projects/git_tags_012/main.tf, terraform/spec/fixtures/projects/hcl2/main.tf
- Modified git_tags_012/main.tf to keep ref=tags/version formatting
- Add test for no dependency updates
=> Add HCL2 tests to file_updater

Dockerfile, bundler/spec/dependabot/bundler/file_updater_spec.rb, bundler/spec/fixtures/projects/bundler1/minor_version_specified_yanked_gem/Gemfile, bundler/spec/fixtures/projects/bundler2/minor_version_specified_yanked_gem/Gemfile
Changelog: https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2217-may-5-2021
=> Upgrade bundler to 2.2.17

composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/dependabot/composer/update_checker_spec.rb, composer/spec/fixtures/projects/invalid_manifest/composer.json
Handle schema validation errors from composer and error with a more
helpful error message with details on how to debug and fix.
=> Composer: handle invalid composer json

Dockerfile, bundler/helpers/v2/monkey_patches/definition_ruby_version_patch.rb
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2218-may-25-2021
=> Bundler: Update bundler to 2.2.18

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb, bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb, bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3/example.gemspec, bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3/example.gemspec
This includes:
- 2.5.9
- 2.6.7
- 2.7.3
- 3.0.1
=> Bump to latest ruby versions

terraform/lib/dependabot/terraform/registry_client.rb
This is a continuation of a suggestion from https://github.com/dependabot/dependabot-core/pull/3811#discussion_r641855036
and https://github.com/dependabot/dependabot-core/pull/3811#pullrequestreview-672834945.
=> Raise PrivateSourceAuthenticationFailure

python/helpers/requirements.txt, python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb, python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb, python/spec/fixtures/projects/pipenv/missing-system-library/Pipfile, python/spec/fixtures/projects/pipenv/missing-system-library/Pipfile.lock
https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#610-2021-04-14
https://pip.pypa.io/en/stable/news/#v21-1-2
=> Upgrade pip to 21.1.2 and pip-tools to 6.1.0

Dockerfile
[Rubygems CHANGELOG](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#3220--2021-06-11)
[Bundler CHANGELOG](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2220-june-11-2021)
=> Bundler: Upgrade rubygems to 3.2.20 and bundler to 2.2.20

Dockerfile
Just a couple places missed the apt lists clean up thing 😄 
cc #946
=> Add missing apt lists clean up after in Dockerfile

Dockerfile
See best practice reference:
- https://github.com/docker/docker.github.io/blob/master/develop/develop-images/dockerfile_best-practices.md#using-pipes
=> Set SHELL option in Dockerfile for shell pipe

bin/dry-run.rb
Cache the cloned repo when `--cache=files` is passed to the dry-run
script.
This also allows setting up a test repo in `tmp/repo/name` and passing
`--clone` and `--cache=files` to load it for any package manager.
The codes in the dry-run scripts are not pretty but punting on a wider
refactor as this probably means re-writing it.
=> Dry-run: cache cloned repos

Dockerfile
updates for
- Erlang deb package: 1.0 -> 2.0
- Elixir: 1.11.4 -> 1.12.2
- Erlang: 23.3.1 -> 24.0.4
=> Elixir version upgrades

Dockerfile
Reverts dependabot/dependabot-core#4089
=> Revert "Elixir version upgrades"

gradle/lib/dependabot/gradle/file_fetcher.rb, gradle/lib/dependabot/gradle/file_parser.rb, gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb, gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb, gradle/spec/dependabot/gradle/file_parser/property_value_finder_spec.rb, gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb, gradle/spec/dependabot/gradle/file_parser_spec.rb, gradle/spec/fixtures/buildfiles/with_dependency_script.gradle, gradle/spec/fixtures/buildfiles/with_dependency_script.gradle.kts, gradle/spec/fixtures/script_plugins/dependencies.gradle, gradle/spec/fixtures/script_plugins/dependencies.gradle.kts
For now work in progress, should fix https://github.com/dependabot/dependabot-core/issues/2138
I still need to add some tests etc, for now I'm just wondering if there is any interest in getting this merged as a stop-gap solution before the Gradle Tooling is integrated as proposed in https://github.com/dependabot/dependabot-core/issues/1164
=> Improved support `apply from` in gradle files

CHANGELOG.md
=> Fix minor typos in changelog

.github/workflows/docker.yml
This currently fails due to being unable to push to the repository: https://github.com/dependabot/dependabot-core/runs/4487225804?check_suite_focus=true
Let's remove it until we make the required permission changes
=> Remove the developer image docker build

Dockerfile
https://groups.google.com/g/golang-announce/c/hcmEScgc00k
=> Bump go from 1.17.4 to 1.17.5

Dockerfile, bundler/helpers/v1/spec/native_spec_helper.rb, bundler/helpers/v2/build, bundler/lib/dependabot/bundler/helpers.rb, bundler/script/ci-test, bundler/spec/dependabot/bundler/helper_spec.rb, bundler/spec/spec_helper.rb
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2233-december-7-2021
Includes a security fix around how git commands are executed
=> Bundler: update bundler to 2.2.33

Dockerfile
https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html
=> Bump cargo from 1.51.0 to 1.57.0

Dockerfile
Reverts dependabot/dependabot-core#4585
=> Revert "Bump cargo from 1.51.0 to 1.57.0"

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb, npm_and_yarn/spec/fixtures/projects/npm8/package-lock-v3/.npmrc, npm_and_yarn/spec/fixtures/projects/npm8/package-lock-v3/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/package-lock-v3/package.json, npm_and_yarn/spec/fixtures/projects/npm8/simple_lockfile_v3/.npmrc, npm_and_yarn/spec/fixtures/projects/npm8/simple_lockfile_v3/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/simple_lockfile_v3/package.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_lockfile_v3/.npmrc, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_lockfile_v3/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_lockfile_v3/package.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_lockfile_v3/packages/build/package.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_top_level_lockfile_v3/.npmrc, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_top_level_lockfile_v3/api/package.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_top_level_lockfile_v3/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/workspace_nested_package_top_level_lockfile_v3/package.json
=> Support npm lockfile v3 format

docker/lib/dependabot/docker/file_parser.rb, docker/spec/dependabot/docker/file_parser_spec.rb, docker/spec/fixtures/docker/dockerfiles/arg_from, docker/spec/fixtures/docker/dockerfiles/arg_from_curls
=> Docker: Support ARG FROM

Dockerfile, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
Node 14 is pretty old and now in maintenance mode, 16 is the new LTS version, let's use it!
https://nodejs.org/en/about/releases/
=> Update node to latest LTS version (16.x)

common/lib/dependabot/metadata_finders/base/release_finder.rb, common/spec/dependabot/metadata_finders/base/release_finder_spec.rb
Fixes #4739 
Opening PR to get input on approach and to be able to execute tests. 
Fix implements the change as described in issue #4739 and adds in test.
=> Codecommit pr release bugfix

nuget/lib/dependabot/nuget/requirement.rb, nuget/lib/dependabot/nuget/update_checker/requirements_updater.rb, nuget/lib/dependabot/nuget/update_checker/version_finder.rb, nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb, nuget/spec/dependabot/nuget/requirement_spec.rb, nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb, nuget/spec/fixtures/csproj/ranges.csproj
Fixes #3540 
This PR introduces a similar change like in https://github.com/dependabot/dependabot-core/commit/528431659e0603aebd9713c274cac50239af4e90 but also considering `*-*` wildcards. 
Tested the fix against my concrete use case and the result is as expected (see comments below).
=> Attempt to fix *-* range handling

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm8/simple_no_indentation/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/simple_no_indentation/package.json, npm_and_yarn/spec/fixtures/updated_projects/npm8/simple_no_indentation/package-lock.json, npm_and_yarn/spec/fixtures/updated_projects/npm8/simple_no_indentation/package.json
Fixes https://github.com/dependabot/dependabot-core/issues/4775
Opted to let `npm` set the indentation size of the manifest files if we cannot detect one.
=> Fix `detect_indentation` nil access error

.rubocop.yml, common/dependabot-common.gemspec, omnibus/dependabot-omnibus.gemspec
Since that's the version dependabot currently runs.
=> Require Ruby 2.7

Dockerfile, bundler/helpers/v2/build, bundler/lib/dependabot/bundler/helpers.rb, bundler/script/ci-test, bundler/spec/dependabot/bundler/helper_spec.rb, bundler/spec/spec_helper.rb
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2310-march-23-2022
=> Update bundler from 2.3.9 to 2.3.10

.github/ISSUE_TEMPLATE/bug-report.md
They have been flagged by Grammarly.
=> fix typos in GitHub issue bug report template

CHANGELOG.md, common/lib/dependabot/version.rb
Fix unsafe directory git issues during updates
=> v0.183.0 Release Notes

bundler/helpers/v2/spec/native_spec_helper.rb, bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
These can now be deleted now that Bundler 2 is supported.
=> Fix Bundler v2 related TODOs

composer/helpers/v2/composer.json, composer/helpers/v2/composer.lock
Reverts dependabot/dependabot-core#5266
May have broken CI
=> Revert "build(deps-dev): bump phpstan/phpstan from 1.6.8 to 1.7.14 in /composer/helpers/v2"

terraform/lib/dependabot/terraform/file_updater.rb
=> fix(terraform): correctly keep platform hashes when multiple providers are installed

.github/dependabot.yml
=> Re-order ecosystems lexicographically

Dockerfile
Bumping some of the erlang/elixir stuff as part of trying to resolve https://github.com/dependabot/dependabot-core/pull/5030#issuecomment-1208508201
=> Bump Elixir to `1.13.4`

.vscode/launch.json
github_actions ecosystem was missing for debugging in vscode
=> github_actions ecosystem was missing for debugging

.github/workflows/ci-release.yml
We need to add the new required checks to the ci-release workflow so that release branch builds are successful.
=> Adding required checks in ci-release.yml

.github/workflows/docker-branch-releases.yml
We're working on improving our deployment process!
=> push docker images after approval

.github/workflows/docker-branch-releases.yml
I broke the push event in #5640, this should get it working again.
=> prevent the push to main event from skipping

bin/dry-run.rb
=> Experiments not Experiment

README.md
=> Fix typo in README (promted -> prompted)

.github/workflows/smoke.yml
=> smoke test npm removed dependencies

Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.3.2
https://releases.hashicorp.com/terraform/1.3.2/
=> build(deps): bump terraform from 1.3.0 to 1.3.2

common/dependabot-common.gemspec, updater/Gemfile, updater/Gemfile.lock, updater/lib/dependabot/service.rb
Reverts dependabot/dependabot-core#5704
In some cases the shape of the data has changed with this PR, so rolling back.
=> Revert "Bump activesupport from 6.1.4.4 to 7.0.4 in /updater"

Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.3.3
https://releases.hashicorp.com/terraform/1.3.3/
=> build(deps): bump terraform from 1.3.2 to 1.3.3

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/sub_dependency_files_filterer_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb, updater/lib/dependabot/job.rb, updater/spec/dependabot/job_spec.rb
This code has passed the exam and has been fully rolled out, this removes the feature flags and makes the flagged behavior the default.
=> Graduate yarn_berry feature flagged code

docker/lib/dependabot/docker/file_parser.rb, docker/lib/dependabot/docker/update_checker.rb, docker/lib/dependabot/docker/utils/credentials_finder.rb, docker/spec/dependabot/docker/utils/credentials_finder_spec.rb
Suggestions provided by @jakecoffman to simplify few code. Thank you!
=> simplification suggestion

bundler/dependabot-bundler.gemspec, bundler/lib/dependabot/bundler/update_checker/conflicting_dependency_resolver.rb, cargo/dependabot-cargo.gemspec, composer/dependabot-composer.gemspec, docker/dependabot-docker.gemspec, elm/dependabot-elm.gemspec, git_submodules/dependabot-git_submodules.gemspec, github_actions/dependabot-github_actions.gemspec, go_modules/dependabot-go_modules.gemspec, gradle/dependabot-gradle.gemspec, hex/dependabot-hex.gemspec, maven/dependabot-maven.gemspec, npm_and_yarn/dependabot-npm_and_yarn.gemspec, nuget/dependabot-nuget.gemspec, omnibus/dependabot-omnibus.gemspec, pub/dependabot-pub.gemspec, python/dependabot-python.gemspec, terraform/dependabot-terraform.gemspec
=> Fix `dependabot-omnibus` update crashing

docker/spec/dependabot/docker/file_fetcher_spec.rb, docker/spec/fixtures/github/contents_helm_repo.json
Noticed this while debugging a related issue. We should test all variants here.
=> Add `values-other.yaml` & `other_values.yaml` to test cases

.devcontainer/core-dev/devcontainer.json, bin/docker-dev-shell
The `omnibus/spec` folder does not exist.
=> Remove unused mappings

Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.3.4
https://releases.hashicorp.com/terraform/1.3.4/
=> build(deps): bump terraform from 1.3.3 to 1.3.4

.github/workflows/docker-branch-releases.yml
I did some testing and the correct trigger type is synchronize not edit. Oops!
=> fix workflow not running on push to PR

Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.3.5
https://releases.hashicorp.com/terraform/1.3.5/
=> build(deps): bump terraform from 1.3.4 to 1.3.5

common/lib/dependabot/shared_helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb, python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb, python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
Follow up to #6272 to aggregate some more errors.
=> Aggregate more subcommand failed errors

docker/lib/dependabot/docker/file_updater.rb, docker/spec/dependabot/docker/file_updater_spec.rb, docker/spec/fixtures/helm/yaml/double-quotes.yaml, docker/spec/fixtures/helm/yaml/single-quotes.yaml
=> Allow optional single and double quotes in yaml versions/tags

common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb, common/spec/fixtures/azure/business_compare_commits.json
Tests/specs that should have accompanied #6321
Related to #6341
=> Add CommitFinder tests/specs for Azure added in #6321

Dockerfile, python/helpers/build, python/lib/dependabot/python/python_versions.rb
Follow-up to #6375 this activates those latest patch releases during runtime
=> Use latest Python patch releases for builds

.github/workflows/ci.yml
Editing `.github/workflows/ci.yml` itself could affect specific ecosystems, or all of them. So for correctness we should rebuild everything like we do when `Dockerfile` or `common/` change.
=> Rebuild all if the workflow itself changes

composer/lib/dependabot/composer/update_checker/version_resolver.rb
While working on https://github.com/dependabot/dependabot-core/pull/6434, I discovered that my prior change https://github.com/dependabot/dependabot-core/pull/6291/files#diff-82bee76077e5dbd4f3073948aa2ad29eec23333f9b4e06550fbf54c259875a24R343 was blowing up because `error.message` cannot be directly modified.
When I started to look how to change that, I realized that we _already_ sanitize all URL credentials from any message at the global level:
* https://github.com/dependabot/dependabot-core/pull/2828
So there's no need to sanitize here.
I compared the two regexes:
https://github.com/dependabot/dependabot-core/blob/9a941db3517eb407f00c5832c902a57a8762f1cb/common/lib/dependabot/errors.rb#L7 https://github.com/dependabot/dependabot-core/blob/9a941db3517eb407f00c5832c902a57a8762f1cb/compose …
=> Remove duplicate sanitization from `composer`

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb, python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb, python/spec/fixtures/pyproject_files/poetry_group_dependencies.toml
Fixes #5766
Would love some feedback on idiomatic approaches, I'm pretty unfamiliar with Ruby.
=> Support Poetry group dependencies

common/lib/dependabot/clients/azure.rb, common/spec/dependabot/clients/azure_spec.rb, common/spec/fixtures/azure/update_pull_request_details.json
This PR adds support for Azure PR autocompletion.
Azure doc: https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/update?view=azure-devops-rest-6.0
edit: fix link
=> Add Azure autocomplete_pull_request

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb, bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb, bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3/Gemfile.lock, bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_1/Gemfile.lock
Also bumped the Ruby 3.* `BUNDLED WITH` in the spec `Gemfile.lock` files.
=> Bumped RubyRequirementSetter RUBY_VERSIONS to latest versions

Rakefile
They seem unused since since 10aa3deb23b93bebd16a4aafd38af29dc2e00c64.
=> Remove unused Rakefile methods

bin/ci-test, bin/lint, script/_common, script/setup
A few more places we can run shellcheck against...
=> Run shellcheck against `./script/*`

README.md
=> Include crucial new dependabot emoji

.github/workflows/eco-branch-images.yml, .github/workflows/eco-latest-releases.yml, .github/workflows/eco-smoke.yml, .github/workflows/ecosystem-ci.yml, bundler/Dockerfile
This breaks the bundler updater out to its own image.
=> Break out bundler.

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
Fixes https://github.com/dependabot/dependabot-core/issues/6270.
=> Fix updating v3 npm lockfiles

bundler/helpers/v2/lib/functions/conflicting_dependency_resolver.rb, bundler/helpers/v2/lib/functions/force_updater.rb
=> Remove setting now ignored by Bundler

pub/Dockerfile
https://dart.dev/get-dart/archive
=> Bump Dart to `2.19.0`

.github/workflows/images-latest.yml, .github/workflows/images-updater-core.yml
Broken in #6553, I tested on this branch first, should be good now!
See https://github.com/dependabot/dependabot-core/actions/runs/4055445348 and https://github.com/dependabot/dependabot-core/actions/runs/4055445344
=> fix image push workflows

maven/lib/dependabot/maven/file_parser/property_value_finder.rb, maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb, maven/spec/fixtures/poms/property_name_starts_with_project_pom.xml
Fixes https://github.com/dependabot/dependabot-core/issues/1859.
Fixes https://github.com/dependabot/dependabot-core/issues/2025.
=> Fix updating properties with name starting with "project"

Dockerfile.development, Dockerfile.updater-core, bin/docker-dev-shell
I was working on another PR and kept getting annoyed that these lists were unordered, made it painful to track down what was already there vs what was missing.
=> Order lists in docker scripts lexicographically

bin/dry-run.rb
Before
```
=> dumping fetched dependency files: ./dry-run/dsp-testing/dependabot-core-5758/
=> updating 1 dependencies: docker/library/ruby
=== docker/library/ruby (2.7.6-buster)
=> latest available version is 2.7.6-buster
=> latest allowed version is 2.7.6-buster
=> requirements update strategy:
=> updating docker/library/ruby from 2.7.6-buster to 2.7.6-buster
± Dockerfile
~~~
1c1
< FROM public.ecr.aws/docker/library/ruby:2.7.6-buster@sha256:3ee0c8dba7051b2974ba5bead0f71db7f3f17e9302036182dfcbb401cff7ddd8 AS base
---
> FROM public.ecr.aws/docker/library/ruby:2.7.6-buster@sha256:f2ba73c31b11be325121bc5018231e21e13348c3b3bc75be44e7a6568893f5c1 AS base
~~~
🌍 Total requests …
```
=> Make dry-run.rb logging better match real behaviour

github_actions/lib/dependabot/github_actions/file_parser.rb, github_actions/spec/dependabot/github_actions/file_parser_spec.rb, github_actions/spec/fixtures/workflow_files/composite_action.yml
I think #6660 has regressed this case. I noticed it thanks to https://github.com/dependabot/dependabot-core/issues/4178#issuecomment-1432287375.
I'll try to add a spec and ship this soon.
=> Fix updating composite actions

python/lib/dependabot/python/file_updater/poetry_file_updater.rb, python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb, python/spec/fixtures/pyproject_files/table.toml, python/spec/fixtures/pyproject_files/table_version_conflicts.toml, python/spec/fixtures/pyproject_files/table_version_last.toml
=> Update Poetry dependencies specified in table format

go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
While messing with the Go fixtures on another test, the Go proxy suddenly started returning v1.2.5 as the latest version on https://github.com/dependabot-fixtures/go-modules-lib. That tag doesn't exist, so this test is failing. 
To make this less flaky, I hooked up a spy to ensure the GOPRIVATE environment variable is being set correctly rather than inferring it from the version returned.
=> Go: fix flaky test due to proxy remembering deleted tag

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
=> Properly update dependencies in new style Poetry groups

maven/lib/dependabot/maven/file_parser.rb, maven/lib/dependabot/maven/file_updater/declaration_finder.rb, maven/spec/dependabot/maven/file_parser_spec.rb, maven/spec/dependabot/maven/file_updater_spec.rb, maven/spec/fixtures/poms/annotation_processor_paths_dependencies.xml
=> Allow updating `annotationProcessorPaths > path` dependencies

python/lib/dependabot/python/update_checker/requirements_updater.rb, python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
=> Respect inclusive upper bound style in requirements.txt files

README.md
We're not actually interested in discussing licensing agreements or partnerships at this time, so removing the line that indicates as much.
=> Update README.md to clarify license

README.md
We don't explicitly ask contributors to sign a CLA anymore.
=> Tidy up license summary

elm/spec/dependabot/elm/update_checker_spec.rb
I don't think anybody has time to look into this right now, so skipping it.
=> Skip failing elm spec

python/Dockerfile, python/helpers/build, python/lib/dependabot/python/python_versions.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
=> Use latest Python 3.10.11 and 3.11.3

README.md
I had this buried in a local text file, figured it might be helpful to others.
=> Document how to test security updates

README.md
I use these options regularly when testing.
I'm not sure which are also applicable to the CLI, so I didn't document them, but if they are supported we should add mention of them either here or in the CLI readme.
Fix https://github.com/dependabot/dependabot-core/issues/6912
=> Document some other useful options for the dry-run script

.gitattributes
This helps with code highlighting in Github.com
=> chore(ee): register custom docker filenames

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/json_lock.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb, npm_and_yarn/spec/fixtures/projects/npm8/nested_node_modules_lockfile_v3/package-lock.json
=> Fix incorrect parsing of some npm lockfile V3 format dependencies

.github/labeler.yml
See https://github.com/dependabot/dependabot-core/pull/7044#issuecomment-1507804945.
=> Fix typo in labeler config

gradle/lib/dependabot/gradle/file_parser.rb, gradle/spec/dependabot/gradle/file_parser_spec.rb, gradle/spec/fixtures/buildfiles/gradle_latest_range_build.gradle
From : https://docs.gradle.org/current/userguide/single_versions.html
Closes #4276
=> fix(gradle): ignore dependencies using `latest-status` versions

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb, cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb, cargo/lib/dependabot/cargo/update_checker/version_resolver.rb, common/lib/dependabot/dependency.rb, common/lib/dependabot/file_parsers/base/dependency_set.rb, common/lib/dependabot/git_commit_checker.rb, common/lib/dependabot/metadata_finders/base/changelog_pruner.rb, common/lib/dependabot/metadata_finders/base/commits_finder.rb, common/lib/dependabot/metadata_finders/base/release_finder.rb, common/lib/dependabot/update_checkers/base.rb, composer/lib/dependabot/composer/update_checker/latest_version_finder.rb, elm/lib/dependabot/elm/update_checker/elm_19_version_resolver.rb, go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb, gradle/lib/dependabot/gradle/update_checker/version_finder.rb, hex/lib/dependabot/hex/update_checker/file_preparer.rb, hex/lib/dependabot/hex/update_checker/version_resolver.rb, maven/lib/dependabot/maven/update_checker/version_finder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb, nuget/lib/dependabot/nuget/update_checker/version_finder.rb, python/lib/dependabot/python/update_checker/latest_version_finder.rb
I extracted this from #5902, because I think that PR is probably a bit too big, and that makes it harder to review.
This is just a small refactoring PR.
=> Move some common functionality to common

composer/helpers/v1/src/UpdateChecker.php, composer/helpers/v2/src/UpdateChecker.php
Trivial aesthetic/readability improvement:
* https://www.php.net/manual/en/function.preg-replace.php
* https://www.php.net/manual/en/function.ltrim.php
=> Use `ltrim()` rather than `preg_replace()`

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
This should make it easier to plugin a feature flag for PNPM.
=> Fetch files by package manager

docker/lib/dependabot/docker/file_fetcher.rb
I think this is a leftover from c0f7545d441045ce81ce6f74608d274272841812.
=> Cleanup leftover require

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/dependency_files_builder.rb
We're in a code branch that guarantees that the condition is always false.
=> Cleanup duplicated conditions

hex/Dockerfile
Release notes https://github.com/elixir-lang/elixir/releases/tag/v1.14.4
=> build(deps): bump Elixir to 1.14.4

README.md, bin/bump-version.rb
Let's get these fixed up to match current reality. This way we have a correct baseline to use for starting to automate further.
=> Update docs with current release process

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
Extracted from #7081 as suggested by @jeffwidman!
=> Pass exception message directly to peer dependency error handler

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
Addresses https://github.com/dependabot/dependabot-core/pull/7081#discussion_r1176892944.
Took the chance to refactor the code a bit while adding the suggested comment.
=> Refactor workspace file fetching in npm

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
This should make it more clear that these lines are not part of the errors themselves.
Suggested by @jeffwidman at https://github.com/dependabot/dependabot-core/pull/7081#discussion_r1176951467.
=> Clarify comments on peer dependency error regexes

updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
We added a new Grouped Update spec which uses VCR and actually executes bundler to verify a behaviour, but the test had a mass expectation that the entire lockfile matches the fixture.
This isn't realistic as even with the fixtures pinning the target dependencies to a fixed range, downstream dependencies may shift slightly between executions.
Let's update the spec to just verify the Gemfile.lock has been updated to match the gemspec as a more stable test that still verifies the outcome.
=> [Updater] Fix brittle test for grouped updates

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
Just noticed this right after merging #7081 😅.
=> Remove dead code

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
I think this is just code I experimented with but never used, and I unintentionally left it there.
=> Remove unused code

terraform/Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.5.0
=> build(deps): bump Terraform to 1.5.0

npm_and_yarn/Dockerfile
It's already set on the base image:
https://github.com/dependabot/dependabot-core/blob/e92409d72d55c436c4a66f75b404a3924e62dd84/Dockerfile.updater-core#L46
=> Remove duplicated ENV

.github/workflows/codeql-analysis.yml
Not sure if this is worth fixing, but should address this:
=> Fix CodeQL warning

.github/dependabot.yml
See discussion here: github/dependabot-updates#4400 (comment)
=> Generate PRs on Sundays weekly

npm_and_yarn/Dockerfile
Release notes:
* https://github.com/pnpm/pnpm/releases/tag/v8.6.5
* https://github.com/pnpm/pnpm/releases/tag/v8.6.6
* https://github.com/pnpm/pnpm/releases/tag/v8.6.7
=> build(deps): bump PNPM to 8.6.7

.devcontainer/core-dev/devcontainer.json
Fixes #7652 by adding swift to core-dev/devcontainer.json
=> Update devcontainer.json to include swift

swift/lib/dependabot/swift/file_updater.rb, swift/lib/dependabot/swift/file_updater/lockfile_updater.rb, swift/lib/dependabot/swift/update_checker/version_resolver.rb, swift/spec/dependabot/swift/file_updater_spec.rb
Fixes issues discovered by @jakecoffman at https://github.com/dependabot/dependabot-core/pull/7664#issuecomment-1656231517.
=> Make sure Swift lockfile updates respect ignore conditions

terraform/Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.5.4
https://releases.hashicorp.com/terraform/1.5.4/
=> build(deps): bump terraform from 1.5.3 to 1.5.4

terraform/Dockerfile
Release notes https://github.com/hashicorp/terraform/releases/tag/v1.5.5
=> build(deps): bump terraform from 1.5.4 to 1.5.5

bin/dry-run.rb
So that dry-run matches real behavior better.
=> Copy clone logic in dry-run.rb from the updater

updater/lib/dependabot/dependency_group_engine.rb, updater/spec/dependabot/dependency_group_engine_spec.rb
=> Fix typo in no matching dependencies for group error

python/lib/dependabot/python/file_parser/subdependency_type_parser.rb, python/lib/dependabot/python/file_updater/poetry_file_updater.rb, python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
=> Refactor poetry logic to parse subdependency types

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
Found these comments about legacy code and did what I think they were telling me.
=> Python 3.6 drop follow up

docker/lib/dependabot/docker/update_checker.rb
This doesn't fix anything but I expect it to make it easier to investigate issues like https://github.com/dependabot/dependabot-core/issues/7416.
=> Debug issues with docker prereleases

python/lib/dependabot/python/file_fetcher.rb, python/lib/dependabot/python/language_version_manager.rb
=> Fix Python runtime errors when instrumenting versions

python/lib/dependabot/python/file_updater/poetry_file_updater.rb, python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
=> Fix Python version switched from exact to tilde version

.github/workflows/ci.yml, bundler/lib/dependabot/bundler/native_helpers.rb, bundler/script/ci-test, bundler/spec/spec_helper.rb, common/lib/dependabot/shared_helpers.rb, common/lib/dependabot/utils.rb, common/spec/dependabot/errors_spec.rb, common/spec/dependabot/shared_helpers_spec.rb, composer/script/ci-test, go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb, go_modules/lib/dependabot/go_modules/resolvability_errors.rb, go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb, go_modules/script/ci-test, go_modules/spec/dependabot/go_modules/file_updater_spec.rb, hex/script/ci-test, npm_and_yarn/helpers/build, npm_and_yarn/helpers/package-lock.json, npm_and_yarn/helpers/package.json, npm_and_yarn/helpers/patches/npm++pacote+9.5.12.patch, npm_and_yarn/script/ci-test, pub/lib/dependabot/pub/helpers.rb, pub/spec/dependabot/pub/file_updater_spec.rb, pub/spec/dependabot/pub/infer_sdk_versions_spec.rb, pub/spec/dependabot/pub/update_checker_spec.rb, python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb, python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/script/ci-test
This is just a WIP, but wanted to share the work since I've been intermittently working on this for the past week.
It all started while reading over git documentation looking for something else and finding about [GIT_CONFIG_GLOBAL](https://git-scm.com/docs/git-config#ENVIRONMENT). It occurred to me that we could leverage that feature to parallelize our specs.
We currently do parallelization in CI only by splitting tests and running each slice on different CI jobs.
This PR allows truly parallelizing things and easily run all tests for an ecosystem locally  by running `script/ci-test`. For the ecosystems I have tried, it shows 50% speed up over `bundle exec rspec`.
Unfortunately still needs more work and even when getting to green CI, we probably to run it fully a few times to ensure no …
=> Parallelize tests

npm_and_yarn/Dockerfile
Changelog: https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.6.3
=> build(deps): bump Yarn to 3.6.3

common/lib/dependabot/pull_request_creator/github.rb, common/spec/dependabot/pull_request_creator/github_spec.rb
I meant to have the PR number here but forgot it's a different field.
=> fix helpful error message to have PR number

.github/workflows/sorbet.yml
Uploading a coverage snapshot will allow us to generate a report[^1] to show progress.
[^1]: https://github.com/Shopify/spoom#generate-a-typing-coverage-report
=> Upload spoom coverage report data

common/lib/dependabot/utils.rb
=> Add `sig`s for `utils`

bundler/helpers/v1/lib/functions.rb, bundler/helpers/v2/lib/functions.rb, bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
=> Fix a typo

npm_and_yarn/Dockerfile
Release notes https://github.com/pnpm/pnpm/releases/tag/v8.8.0
=> build(deps): bump PNpm from 8.7.6 to 8.8.0

npm_and_yarn/Dockerfile
Release notes https://github.com/pnpm/pnpm/releases/tag/v8.9.0
=> build(deps): bump PNpm from 8.8.0 to 8.9.0

npm_and_yarn/Dockerfile
Full Changelog: https://github.com/yarnpkg/berry/compare/@yarnpkg/cli/3.6.3...@yarnpkg/cli/3.6.4
=> build(deps): bump yarn to 3.6.4

updater/lib/dependabot/sentry.rb, updater/spec/dependabot/sentry_spec.rb
This PR fixes a couple of Sentry redaction edge cases.
=> Fix sentry redaction issues

composer/lib/dependabot/composer/file_fetcher.rb, composer/spec/spec_helper.rb
It seems permanently broken right now.
=> Make composer CI pass consistently

common/lib/dependabot/pull_request_creator/message_builder.rb, common/spec/dependabot/pull_request_creator/message_builder_spec.rb
Removed unignore command feature flag as this feature has been shipped to production.
=> Removed unignore command feature flag

updater/spec/fixtures/bundler_grouped_by_types/updated_development_deps/Gemfile.lock
Need to not make actual calls to the registry during testing.
=> temporary fix for flaky test

common/lib/dependabot/shared_helpers.rb
This only brings `SharedHelpers` to `typed: true` because the changes here are different than the rest of the PRs I've been opening recently. There will be a lot more work to get `SharedHelpers` to `strict` and eventually `strong`.
=> Type `SharedHelpers`

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb, npm_and_yarn/spec/fixtures/projects/yarn/workspace_requirements_no_lockfile/package.json
=> Fix illformed requirement error on "workspace:" dependencies

npm_and_yarn/Dockerfile
Release notes 
https://github.com/pnpm/pnpm/releases/tag/v8.10.0
https://github.com/pnpm/pnpm/releases/tag/v8.10.1
https://github.com/pnpm/pnpm/releases/tag/v8.10.2
=> build(deps): bump pNPM to 8.10.2

.rubocop.yml, common/.rubocop.yml, git_submodules/.rubocop.yml, swift/.rubocop.yml
This means that any new files must have at minimum `# typed: true` in these directories going forward.
=> Enforce `# typed: true` where possible

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private/pnpm-lock.yaml
Raise user errors about being unable to reach private git PNPM dependencies.
=> Raise user errors about being unable to reach private git PNPM dependencies

npm_and_yarn/Dockerfile
Full Changelog: https://github.com/yarnpkg/berry/compare/@yarnpkg/cli/3.6.4...@yarnpkg/cli/3.7.0
=> build(deps): bump Yarn to 3.7.0

npm_and_yarn/Dockerfile
Release notes
https://github.com/pnpm/pnpm/releases/tag/v8.10.3
https://github.com/pnpm/pnpm/releases/tag/v8.10.4
https://github.com/pnpm/pnpm/releases/tag/v8.10.5
=> build(deps): bump pNPM to 8.10.5

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
I believe this error string never really matched the output. We could maybe find a more specific regex, but I think this is sufficiently specific for the use case.
=> Update error message matching

python/helpers/requirements.txt
Pick up upstream fix https://github.com/pypa/pipenv/pull/6024.
=> Use a pipenv fork for now to fix tomlkit issues in pipenv

bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb, common/lib/dependabot/pull_request_creator/branch_namer/base.rb
The last commit on main is green, but this started failing on branches. Something must not be pinned correctly in a Gemfile or gemspec somewhere.
=> fix Sorbet type error

README.md
Reminder to self: No matter what, coming back to old code/text after several months away always gives fresh eyes.
=> "re-selling" -> "reselling"

common/lib/dependabot/pull_request_creator/branch_namer/base.rb, common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb, common/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb
This can be marked as `strong` once https://github.com/sorbet/sorbet/pull/7523 is merged.
=> Strictly type `BranchNamer::Base`

.github/dependabot.yml
Seems rare that we would want to take them separately.
=> group all the actions updates together

Dockerfile.development, bin/dry-run.rb
My changes in #8670 broke this.
=> Fix building development image & running dry-run.rb script

common/lib/dependabot/workspace/git.rb
So that errors are grouped in Sentry.
=> Add fingerprint to dynamic git commands

updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
This is pretty difficult to write a test for, we need https://github.com/dependabot/dependabot-core/pull/8678 to start to be able to write dummy updaters that fail the way we want them to 😄
=> raise a specific exception when the FileUpdater doesn't produce a change

docker/lib/dependabot/docker/file_parser.rb, docker/spec/dependabot/docker/file_parser_spec.rb, docker/spec/fixtures/helm/yaml/no-tag.yaml
Fixes https://github.com/dependabot/dependabot-core/issues/8593
=> Handle non-matching tags

CONTRIBUTING.md
Removing the segments that discourage community contributions
=> We now encourage new ecosystems

npm_and_yarn/Dockerfile
https://github.com/pnpm/pnpm/releases/tag/v8.14.3
https://github.com/pnpm/pnpm/releases/tag/v8.14.2
https://github.com/pnpm/pnpm/releases/tag/v8.14.1
https://github.com/pnpm/pnpm/releases/tag/v8.14.0
https://github.com/pnpm/pnpm/releases/tag/v8.13.1
https://github.com/pnpm/pnpm/releases/tag/v8.12.1
https://github.com/pnpm/pnpm/releases/tag/v8.12.0
Note to reviewers : This is a candidate for a squash merge as the intermediate  commits are meaningless. I will try to rebase before it is merged
=> build(deps): bump pNPM to 8.14.3

nuget/lib/dependabot/nuget/file_parser.rb, nuget/lib/dependabot/nuget/file_parser/global_json_parser.rb, nuget/lib/dependabot/nuget/file_updater.rb, nuget/lib/dependabot/nuget/native_helpers.rb, nuget/lib/dependabot/nuget/nuget_client.rb, nuget/lib/dependabot/nuget/version.rb
I was working in a couple of these classes recently and having type assertions would have made my experience easier so I figured I'd do a quick cleanup for them.
=> Expand Sorbet usage

docker/README.md
[rendered](https://github.com/dependabot/dependabot-core/blob/5e46076bd22898fa6f22ff456646ab51943bf1f0/docker/README.md)
=> Add info on Docker tag support

common/lib/dependabot/pull_request_creator.rb, common/lib/dependabot/pull_request_creator/azure.rb
=> Strict type `Dependabot::PullRequestCreator::Azure`

updater/bin/fetch_files.rb, updater/bin/update_files.rb, updater/lib/dependabot/sorbet/runtime.rb
These were hold outs as they're entry points without access to Dependabot::Service. While I'm not sure how worthwhile it is to report these errors (we haven't seen them in a long time), but I want to complete the task.
=> ⏩ Send Remaining Exceptions to the Service

.github/workflows/stalebot.yml, CONTRIBUTING.md
Introducing stalebot to start getting ahead of our stale issues and PRs
=> Create stalebot.yml, update contributors to explain its existence

common/lib/dependabot/registry_client.rb, nuget/lib/dependabot/nuget/metadata_finder.rb, nuget/lib/dependabot/nuget/update_checker/version_finder.rb
Strict type `Dependabot::NuGet::MetadataFinder`
True type `Dependabot::Nuget::UpdateChecker::VersionFinder`
=> Type more of `nuget`

nuget/lib/dependabot/nuget/update_checker/version_finder.rb
=> Strict type `Dependabot::Nuget::UpdateChecker::VersionFinder`

npm_and_yarn/Dockerfile
Addresses a toolVersion bug
Fixes #9321
=> Update PNPM to 8.15.5

python/Dockerfile, python/lib/dependabot/python/language_version_manager.rb
=> chore(python): target latest python versions 3.12.2, 3.11.8

maven/lib/dependabot/maven/file_parser.rb, maven/lib/dependabot/maven/file_updater/declaration_finder.rb, maven/spec/dependabot/maven/file_parser_spec.rb, maven/spec/dependabot/maven/file_updater_spec.rb, maven/spec/fixtures/poms/plugin_dependencies_artifactItems_pom.xml
Fixes https://github.com/dependabot/dependabot-core/issues/5826
=>  fix: parse plugin artifactItem dependencies 

silent/tests/testdata/vu-group-exclude-patterns.txt
We didn't have a silent ecosystem test for exclude patterns yet, so threw one together.
=> test for exclude patterns

common/lib/dependabot/pull_request_creator/message_builder.rb, common/spec/dependabot/pull_request_creator/message_builder_spec.rb, updater/lib/dependabot/dependency_group_engine.rb, updater/spec/dependabot/dependency_group_engine_spec.rb
=> Avoid including `group` in PR titles twice

common/lib/dependabot/pull_request_creator/github.rb
This isn't allowed by the GitHub API, so we should handle it inline.
=> Handle requests for review from dependabot

npm_and_yarn/Dockerfile
https://github.com/pnpm/pnpm/releases/tag/v8.15.6
=> build(deps): bump pNPM to 8.15.6

terraform/Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.8.0
https://releases.hashicorp.com/terraform/1.8.0/
=> build(deps): bump terraform from 1.7.5 to 1.8.0

.github/dependabot.yml
Testing multi-directory config which hasn't been released to beta yet.
=> use multi-directory config

.github/dependabot.yml
=> fix the directory name in dependabot.yml

.github/dependabot.yml
Enable multi-dir grouping for the composer ecosystem
=> Add multi-dir to composer

Dockerfile.updater-core, Gemfile.lock, updater/Gemfile.lock
See https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md
=> Update bundler to 2.5.9

npm_and_yarn/lib/dependabot/npm_and_yarn/package_name.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/package_name_spec.rb
As per the logs user is trying to define a package name starting with underscore but in the code the leading underscore is restricted. So, in order to fix the issue facing by user i have removed the leading underscore restriction.
=> #5246:removing the leading underscore restriction in the package naming.

.github/workflows/scorecards.yaml
[The OpenSSF Scorecard][1] provides best practices for securing the software supply chain. This workflow runs the scorecard action and reports on the current status of the dependabot-core repository. This data is [already available][2], but this action gives us better insight and more up-to-date information.
[1]: https://scorecard.dev/
[2]: https://securityscorecards.dev/viewer/?uri=github.com%2Fdependabot%2Fdependabot-core
=> Add scorecards analysis

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb, bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb, bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_3/example.gemspec, bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_3/example.gemspec
After upgrading our rails app to ruby 3.1.1, we started to get `Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound` errors
This change updates the ruby requirement to 3.3.1
<details><summary>Stack trace</summary>
````
updater | 2024/05/06 10:33:13 INFO <job_824235775> Checking if rubocop 1.63.1 needs updating
updater | 2024/05/06 10:33:14 ERROR <job_824235775> Error processing rubocop (Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound)
updater | 2024/05/06 10:33:14 ERROR <job_824235775> Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound
updater | 2024/05/06 10:33:14 ERROR <job_824235775> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:65:in `ruby_version'
updater | …
```
=> Update bundler module to ruby 3.3.1

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs
=> allow 4 part version numbers for transitive dependencies

.rubocop_todo.yml, cargo/spec/dependabot/cargo/update_checker_spec.rb, composer/spec/dependabot/composer/update_checker_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb, nuget/spec/dependabot/nuget/update_checker/compatibility_checker_spec.rb, python/spec/dependabot/python/update_checker_spec.rb
Context block is changed to describe block.
=> #6016: Address RSpec/ContextMethod Rubocop violations

common/dependabot-common.gemspec
Address linting error in spec file
=> Fixed linting error

.rubocop_todo.yml, bundler/spec/dependabot/bundler/update_checker_spec.rb, common/spec/dependabot/file_updaters/base_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexpectchange
=> Reenable RSpec/ExpectChange

.rubocop_todo.yml, docker/spec/dependabot/docker/utils/credentials_finder_spec.rb, python/spec/dependabot/python/update_checker_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexpectinhook
=> Enable RSpec/ExpectInHook

.rubocop_todo.yml, gradle/spec/dependabot/gradle/file_parser_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecbenil
=> Enabling RSpec/BeNil

.rubocop_todo.yml, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecsubjectdeclaration
=> Enabling RSpec/SubjectDeclaration

.rubocop_todo.yml, common/spec/dependabot/pull_request_creator/message_builder_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecimplicitexpect
=> Enabling RSpec/ImplicitExpect

.rubocop_todo.yml, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspeccontainexactly
=> Enable RSpec/ContainExactly

.rubocop_todo.yml, common/spec/dependabot/file_fetchers/base_spec.rb, common/spec/dependabot/pull_request_creator/message_builder_spec.rb
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecfocus
=> Enabling RSpec/Focus

.github/workflows/add-to-core-project.yml, .github/workflows/codeql-analysis.yml, .github/workflows/codespell.yml, .github/workflows/dependency-review.yml, .github/workflows/gems-bump-version.yml, .github/workflows/gems-release-to-rubygems.yml, .github/workflows/images-branch.yml, .github/workflows/images-latest.yml, .github/workflows/images-updater-core.yml, .github/workflows/issue-labeler.yml, .github/workflows/labeler.yml, .github/workflows/smoke.yml, .github/workflows/sorbet.yml, .github/workflows/stalebot.yml
This completes the remaining work started in #9755
=> Pin remaining GitHub actions to SHA hash

.gitmodules
References:
- https://github.com/NuGet/NuGet.Client/compare/6.9.1.3...6.10.0.100
- https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.10
- https://devblogs.microsoft.com/nuget/announcing-nuget-6-10/
=> Update `NuGet.Client` from `6.9.1.3` to `6.10.0.100`

.rubocop_todo.yml, pub/spec/dependabot/pub/file_fetcher_spec.rb, pub/spec/dependabot/pub/requirements_spec.rb, pub/spec/dependabot/pub/update_checker_spec.rb
Test Improvements, Context Wording, Ecosystem pub.
=> TICtxtWrd-pub: Test Improvements, Context Wording, Ecosystem pub.

.rubocop_todo.yml, elm/spec/dependabot/elm/file_parser_spec.rb, elm/spec/dependabot/elm/requirement_spec.rb, elm/spec/dependabot/elm/update_checker/cli_parser_spec.rb, elm/spec/dependabot/elm/update_checker/elm_19_version_resolver_spec.rb, elm/spec/dependabot/elm/update_checker/requirements_updater_spec.rb, elm/spec/dependabot/elm/update_checker_spec.rb, elm/spec/dependabot/elm/version_spec.rb
TICtxtWrd-elm: Test Improvements, Context Wording, ecosystem elm
=> TICtxtWrd-elm: Test Improvements, Context Wording, ecosystem elm

.rubocop_todo.yml, updater/spec/dependabot/api_client_spec.rb, updater/spec/dependabot/job_spec.rb, updater/spec/dependabot/updater_spec.rb
TestImprovements, Context Wording, ecosystem updater
=> TICtxtWrd-updater: TestImprovements, Context Wording, ecosystem updater

.rubocop_todo.yml, terraform/spec/dependabot/terraform/file_parser_spec.rb, terraform/spec/dependabot/terraform/file_updater_spec.rb, terraform/spec/dependabot/terraform/requirements_updater_spec.rb, terraform/spec/dependabot/terraform_spec.rb
Test Improvements, Context Wording, ecosystem terraform.
=> TICtxtWrd-tf:Test Improvements, Context Wording, ecosystem terraform.

.rubocop_todo.yml, python/spec/dependabot/python/authed_url_builder_spec.rb, python/spec/dependabot/python/file_fetcher_spec.rb, python/spec/dependabot/python/file_parser/pipfile_files_parser_spec.rb, python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb, python/spec/dependabot/python/file_parser/python_requirement_parser_spec.rb, python/spec/dependabot/python/file_parser_spec.rb, python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb, python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb, python/spec/dependabot/python/file_updater/pipfile_manifest_updater_spec.rb, python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb, python/spec/dependabot/python/file_updater/requirement_file_updater_spec.rb, python/spec/dependabot/python/file_updater/requirement_replacer_spec.rb, python/spec/dependabot/python/file_updater/setup_file_sanitizer_spec.rb, python/spec/dependabot/python/file_updater_spec.rb, python/spec/dependabot/python/metadata_finder_spec.rb, python/spec/dependabot/python/requirement_parser_spec.rb, python/spec/dependabot/python/requirement_spec.rb, python/spec/dependabot/python/update_checker/index_finder_spec.rb, python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb, python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb, python/spec/dependabot/python/update_checker/pip_version_resolver_spec.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb, python/spec/dependabot/python/update_checker/requirements_updater_spec.rb, python/spec/dependabot/python/update_checker_spec.rb, python/spec/dependabot/python/version_spec.rb
Test Improvements, Context Wording, Ecosystem python.
=> TICtxtWrd-python:Test Improvements, Context Wording, Ecosystem python.

.rubocop_todo.yml, git_submodules/spec/dependabot/git_submodules/file_fetcher_spec.rb, git_submodules/spec/dependabot/git_submodules/update_checker_spec.rb
Test Improvements, Context Wording, ecosystem git submodules.
=> TICtxtWrd-gs: Test Improvements, Context Wording, ecosystem git submodules.

.rubocop_todo.yml, composer/spec/dependabot/composer/file_fetcher/path_dependency_builder_spec.rb, composer/spec/dependabot/composer/file_fetcher_spec.rb, composer/spec/dependabot/composer/file_parser_spec.rb, composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb, composer/spec/dependabot/composer/file_updater_spec.rb, composer/spec/dependabot/composer/metadata_finder_spec.rb, composer/spec/dependabot/composer/requirement_spec.rb, composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb, composer/spec/dependabot/composer/update_checker/requirements_updater_spec.rb, composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb, composer/spec/dependabot/composer/update_checker_spec.rb
Test Improvements, Context Wording, ecosystem composer.
=> TICtxtWrd-cmp: Test Improvements, Context Wording, ecosystem composer.

.rubocop_todo.yml, devcontainers/spec/dependabot/devcontainers/update_checker_spec.rb, docker/spec/dependabot/docker/file_fetcher_spec.rb, docker/spec/dependabot/docker/file_parser_spec.rb, docker/spec/dependabot/docker/requirement_spec.rb, docker/spec/dependabot/docker/update_checker_spec.rb, docker/spec/dependabot/docker/utils/credentials_finder_spec.rb
Test Improvements, Context Wording, ecosystem dev containers and docker.
=> TICtxtWrd-dcon: Test Improvements, Context Wording, ecosystem dev containers and docker.

docker/lib/dependabot/docker/version.rb
=> Strict-type `Dependabot::Docker::Version`

.github/pull_request_template.md, CONTRIBUTING.md
In order to ensure that PRs are easy to review and of high quality, let's adopt this simple PR template similar to what we use internally.
Any items we should add or remove to the checklist? Anything else you'd like to see reworded, added or removed?
New PRs include the details that are requested by this template.
=> Adopt PR template

.rubocop_todo.yml, nuget/spec/dependabot/nuget/file_fetcher_spec.rb, nuget/spec/dependabot/nuget/file_parser_spec.rb, nuget/spec/dependabot/nuget/file_updater_spec.rb, nuget/spec/dependabot/nuget/metadata_finder_spec.rb, nuget/spec/dependabot/nuget/native_helpers_spec.rb, nuget/spec/dependabot/nuget/nuget_client_spec.rb, nuget/spec/dependabot/nuget/requirement_spec.rb, nuget/spec/dependabot/nuget/update_checker/compatibility_checker_spec.rb, nuget/spec/dependabot/nuget/update_checker/dependency_finder_spec.rb, nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb, nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb, nuget/spec/dependabot/nuget/update_checker/requirements_updater_spec.rb, nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb, nuget/spec/dependabot/nuget/update_checker_spec.rb, nuget/spec/dependabot/nuget/version_spec.rb
Test Improvement, Context Wording, for the ecosystem nuget
Please ensure context wording sensible and meaningful
Ran Linter in dev environment
=> TICtxtWrd-nuget: Test Improvement, Context Wording, for the ecosystem nuget

bundler/lib/dependabot/bundler/file_updater.rb
=> True type `Dependabot::Bundler::FileUpdater`

.github/workflows/gems-bump-version.yml
Avoid "Actions Lint" annotations in PRs, like
No.
By fixing indentation.
=> Fix comment indentation

maven/lib/dependabot/maven/file_parser/repositories_finder.rb, maven/lib/dependabot/maven/metadata_finder.rb
Sorbet Implementation for Maven MetaDataFinder ruby file.
Please pay attention to the fixes in the Maven MetaDataFinder ruby file.
=> Strict type `Dependabot::Maven::MetadataFinder`

pub/lib/dependabot/pub/metadata_finder.rb
Sorbet Implementation for Pub MetaDataFinder ruby file.
Please pay attention to the fixes in the Pub MetaDataFinder ruby file.
=> Strict type `Dependabot::Pub::MetaDataFinder`

terraform/lib/dependabot/terraform/metadata_finder.rb
Sorbet Implementation for Terraform MetaDataFinder ruby file.
Please pay attention to the fixes in the Terraform MetaDataFinder ruby file.
=> Strict type `Dependabot::Terraform::MetaDataFinder`

bundler/lib/dependabot/bundler/file_updater/git_source_remover.rb
Strict type `Dependabot::Bundler::FileUpdater::GitSourceRemover`
=> True type `Dependabot::Bundler::FileUpdater::GitSourceRemover`

pub/.rubocop.yml, pub/lib/dependabot/pub/helpers.rb, pub/lib/dependabot/pub/update_checker.rb
Upgrade `Dependabot::Pub::Helpers` from `typed: false` to `typed: true` and enforce it by enabling `Sorbet/TrueSigil`.
`dependency_services_smallest_update` was migrated from `Helpers` to `UpdateChecker` as that's the only place where it was used.
=> True type `pub`

bundler/lib/dependabot/bundler/file_parser/gemspec_declaration_finder.rb
Strict type `Dependabot::Bundler::FileParser::GemspecDeclarationFinder`
=> Strict type `Dependabot::Bundler::FileParser::GemspecDeclarationFinder`

bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
Upgrade `Dependabot::Bundler::UpdateChecker::SharedBundlerHelpers` from `typed: false` to `typed: true`.
=> True type `Dependabot::Bundler::UpdateChecker::SharedBundlerHelpers`

bundler/lib/dependabot/bundler/file_parser/gemfile_declaration_finder.rb
Strict type `Dependabot::Bundler::FileParser::GemfileDeclarationFinder`
=> Strict type `Dependabot::Bundler::FileParser::GemfileDeclarationFinder`

swift/lib/dependabot/swift/metadata_finder.rb
Sorbet Implementation for Swift MetaDataFinder ruby file.
Please pay attention to the fixes in the Swift MetaDataFinder ruby file.
=> Strict type `Dependabot::Swift::MetaDataFinder`

bundler/.rubocop.yml
Enforce `true` sigil in `bundler` with the `Sorbet/TrueSigil` rubocop rule.
This change depends on:
- #9907
- #9911
- #9912
- #9914
=> Enforce `true` sigil in `bundler`

.rubocop_todo.yml, common/spec/dependabot/pull_request_creator/message_builder_spec.rb, common/spec/dependabot/pull_request_creator_spec.rb, common/spec/dependabot/registry_client_spec.rb, common/spec/dependabot/update_checkers/base_spec.rb, github_actions/spec/dependabot/github_actions/update_checker_spec.rb, nuget/spec/dependabot/nuget/update_checker_spec.rb, updater/spec/dependabot/dependency_change_spec.rb, updater/spec/dependabot/file_fetcher_command_spec.rb, updater/spec/dependabot/update_files_command_spec.rb
The RSpec rule for ReceiveMessages is disabled on some files.  This pull request enables that rubocop rule for all files
Be aware of bad autocorrect fixes that I missed in reviewing the changes.
The rubocop rule will work properly across the ecosystem.
=> enable receive messages

common/spec/spec_helper.rb
Try to make coverage information printed during tests be more accurate.
Currently each test process overwrites the previous coverage result, so we can't really know what the real coverage is. 
This PR assigns each process a unique name, so that reports are not overwritten but merged instead.
```
...............................Coverage report generated for RSpec to /home/dependabot/bundler/coverage. 107 / 112 LOC (95.54%) covered.
..............................................*.................*........................................................Coverage report generated for RSpec to /home/dependabot/bundler/coverage. 583 / 1148 LOC (50.78%) covered.
.......................................................................Coverage report generated for RSpec to …
```
=> Fix code coverage merging

updater/lib/dependabot/dependency_change.rb, updater/lib/dependabot/updater/group_update_creation.rb, updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb, updater/lib/dependabot/updater/operations/group_update_all_versions.rb, updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
Adds Sorbet types around some tricky grouped update code to ensure we don't accidentally incur NilClass errors in the future.
Nope!
The Sorbet type check passes and no new errors in production during rollout.
=> add Sorbet types to group update creation

maven/.rubocop.yml, maven/lib/dependabot/maven/file_fetcher.rb, maven/lib/dependabot/maven/file_parser.rb
Enforce `# typed: true` in `maven` ecosystem
Tests pass
=> True type `maven`

gradle/.rubocop.yml, gradle/lib/dependabot/gradle/file_fetcher.rb, gradle/lib/dependabot/gradle/file_fetcher/settings_file_parser.rb, gradle/lib/dependabot/gradle/file_parser.rb, gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb, gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb, gradle/lib/dependabot/gradle/file_updater.rb, gradle/lib/dependabot/gradle/file_updater/dependency_set_updater.rb
Enforce `# typed: true` in `gradle` ecosystem
Tests pass
=> True type `gradle`

terraform/.rubocop.yml, terraform/lib/dependabot/terraform/file_updater.rb
Enforce `# typed: true` in `terraform` ecosystem
Tests pass
=> True type `terraform`

hex/.rubocop.yml, hex/lib/dependabot/hex/update_checker/file_preparer.rb, hex/lib/dependabot/hex/version.rb
Enforce `# typed: true` in `hex` ecosystem
Tests pass
=> True type `hex`

python/lib/dependabot/python/file_fetcher.rb, python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb, python/lib/dependabot/python/file_updater/requirement_replacer.rb, python/lib/dependabot/python/metadata_finder.rb, python/lib/dependabot/python/update_checker/index_finder.rb, python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb, python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
Enforce `# typed: true` in `python` ecosystem
Tests pass
=> True type `python`

silent/lib/dependabot/silent/file_fetcher.rb
Sorbet Implementation for Silent FileFetcher ruby file.
Please pay attention to the fixes in the Silent FileFetcher ruby file.
=> Strict type `Dependabot::Silent::FileFetcher`

pub/lib/dependabot/pub/file_parser.rb
Sorbet Implementation for Pub FileParser ruby file.
Please pay attention to the fixes in the Pub FileParser ruby file.
=> Strict type `Dependabot::Pub::FileParser`

pub/lib/dependabot/pub/file_updater.rb
Sorbet Implementation for Pub FileUpdater ruby file.
Please pay attention to the fixes in the Pub FileUpdater ruby file.
=> Strict type `Dependabot::Pub::FileUpdater`

python/lib/dependabot/python/name_normaliser.rb
Sorbet Implementation for Python NameNormaliser ruby file.
Please pay attention to the fixes in the Python NameNormaliser ruby file.
=> Strict type `Dependabot::python::NameNormaliser`

silent/lib/dependabot/silent/file_parser.rb
Sorbet Implementation for Silent FileParser ruby file.
Please pay attention to the fixes in the Silent FileParser ruby file.
=> Strict type `Dependabot::Silent::FileParser`

silent/lib/dependabot/silent/file_updater.rb
Sorbet Implementation for Silent FileUpdater ruby file.
Please pay attention to the fixes in the Silent FileUpdater ruby file.
=> Strict type `Dependabot::Silent::FileUpdater`

maven/lib/dependabot/maven/file_fetcher.rb
Sorbet Implementation for Maven FileFetcher ruby file.
Please pay attention to the fixes in the Maven FileFetcher ruby file.
=> Strict type `Dependabot::Maven::FileFetcher`

composer/helpers/v2/src/UpdateChecker.php, composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb, composer/spec/dependabot/composer/update_checker_spec.rb
Reverts dependabot/dependabot-core#9967
=> Revert " Changes made for dependabot to respect ignoring minor patch updates."

hex/lib/dependabot/hex/file_updater/mixfile_sanitizer.rb
Sorbet Implementation for Hex MixFileSanitizer ruby file.
Please pay attention to the fixes in the Hex MixFileSanitizer ruby file.
=> Strict type `Dependabot::Hex::MixFileSanitizer`

hex/lib/dependabot/hex/credential_helpers.rb
Sorbet Implementation for Hex CredentialHelpers ruby file.
Please pay attention to the fixes in the Hex CredentialHelpers ruby file.
=> Strict type `Dependabot::Hex::CredentialHelpers`

maven/lib/dependabot/maven/utils/auth_headers_finder.rb
Sorbet Implementation for Maven AuthHeadersFinder ruby file.
Please pay attention to the fixes in the Maven AuthHeadersFinder ruby file.
=> Strict type `Dependabot::Maven::AuthHeadersFinder`

terraform/lib/dependabot/terraform/requirement.rb
Sorbet Implementation for Terraform Requirement ruby file.
Please pay attention to the fixes in the Terraform Requirement ruby file.
=> Strict type `Dependabot::Terraform::Requirement`

bundler/lib/dependabot/bundler/file_fetcher/gemspec_finder.rb
Sorbet Implementation for Bundler GemSpecFinder ruby file.
Please pay attention to the fixes in the Bundler GemSpecFinder ruby file.
=> Strict type `Dependabot::Bundler::GemspecFinder`

bundler/lib/dependabot/bundler/file_parser/file_preparer.rb
Sorbet Implementation for Bundler FilePreparer ruby file.
Please pay attention to the fixes in the Bundler FilePreparer ruby file.
=> Strict type `Dependabot::Bundler::FilePreparer`

bundler/lib/dependabot/bundler/file_fetcher/child_gemfile_finder.rb
Sorbet Implementation for Bundler ChildGemFileFInder ruby file.
Please pay attention to the fixes in the Bundler ChildGemFileFInder ruby file.
=> Strict type `Dependabot::Bundler::ChildGemFileFinder`

bundler/lib/dependabot/bundler/file_fetcher/path_gemspec_finder.rb
Sorbet Implementation for Bundler PathGemSpecFInder ruby file.
Please pay attention to the fixes in the Bundler PathGemSpecFInder ruby file.
=> Strict type `Dependabot::Bundler::PathGemSpecFinder`

hex/lib/dependabot/hex/file_fetcher.rb
Sorbet Implementation for Hex FileFetcher ruby file.
Please pay attention to the fixes in the Hex FileFetcher ruby file.
=> Strict type `Dependabot::Hex::FileFetcher`

Dockerfile.updater-core
Reverts dependabot/dependabot-core#9979
=> Revert "Make it easier to upgrade Bundler & RubyGems in sync "

nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
=> [NuGet] update version_finder_spec.rb

docker/lib/dependabot/docker/tag.rb
This is getting out of hand, trying to keep it a bit simpler.
=> Simplify docker regex

gradle/lib/dependabot/gradle/file_fetcher/settings_file_parser.rb
Sorbet Implementation for Gradle SettingsFileParser ruby file.
Please pay attention to the fixes in the Gradle SettingsFileParser ruby file.
=> Strict type `Dependabot::Gradle::SettingsFileParser`

python/lib/dependabot/python/file_fetcher.rb
Complete true typing of Python, and the entire Dependabot codebase. A followup from #9954 from @jurre 
`return @python_version_file if @python_version_file` ensures that `@python_version_file` is `NilClass` beyond that line, so there's no need to guard against `nil` with lazy assignment `||=`. And in fact, Sorbet errors as it considers it dead code.
Tests pass
=> True type `Dependabot::Python::FileFetcher`

common/lib/dependabot/shared_helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
Strict type `Dependabot::NpmAndYarn::FileUpdater::NpmLockfileUpdater`. This is currently the largest `true` typed file in the codebase 
Tests pass
=> Strict type `Dependabot::NpmAndYarn::FileUpdater::NpmLockfileUpdater`

.rubocop.yml, bin/bump-version.rb, bin/dry-run.rb, bundler/.rubocop.yml, cargo/.rubocop.yml, composer/.rubocop.yml, devcontainers/.rubocop.yml, docker/.rubocop.yml, elm/.rubocop.yml, github_actions/.rubocop.yml, gradle/.rubocop.yml, hex/.rubocop.yml, maven/.rubocop.yml, npm_and_yarn/.rubocop.yml, pub/.rubocop.yml, silent/.rubocop.yml, swift/.rubocop.yml, terraform/.rubocop.yml, updater/.rubocop.yml
Elevate the `true` Sorbet sigil requirement from each individual ecosystem to the root level. This ensures that existing ecosystems are consistent, but also new ecosystems start from a good state.
This depends on:
- #9929 
- #9950 
- #9954
- #10081
RuboCop and Sorbet passes
=> Enable `Sorbet/TrueSigil` at root RuboCop configuration

maven/lib/dependabot/maven/file_parser.rb, maven/lib/dependabot/maven/file_parser/property_value_finder.rb, maven/lib/dependabot/maven/update_checker.rb
Sorbet Implementation for Maven PropertyValueFinder ruby file.
Please pay attention to the fixes in the Maven PropertyValueFinder ruby file.
=> Strict type `Dependabot::Maven::PropertyValueFinder`

maven/lib/dependabot/maven/file_parser/pom_fetcher.rb
Sorbet Implementation for Maven PomFetcher ruby file.
Please pay attention to the fixes in the Maven PomFetcher ruby file.
=> Strict type `Dependabot::Maven::PomFetcher`

maven/lib/dependabot/maven/file_parser.rb, maven/lib/dependabot/maven/file_parser/property_value_finder.rb
Sorbet Implementation for Maven FileParser ruby file.
Please pay attention to the fixes in the Maven FileParser ruby file.
=> Strict type `Dependabot::Maven::FileParser`

README.md
Fix grammar.
While we're at it: could you please also fix the description of this repository from "Dependabot's core logic for creating update PR's." to "Dependabot's core logic for creating update PRs."?
Thank you!
=> Fix plural of "PR"

python/lib/dependabot/python/pip_compile_file_matcher.rb
Sorbet Implementation for Python PipCompileFileMatcher ruby file.
Please pay attention to the fixes in the Python PipCompileFileMatcher ruby file.
=> Strict type `Dependabot::Python::PipCompileFileMatcher`

pub/lib/dependabot/pub/file_fetcher.rb
Sorbet Implementation for Pub FileFetcher ruby file.
Please pay attention to the fixes in the Pub FileFetcher ruby file.
=> Strict type `Dependabot::Pub::FileFetcher`

maven/lib/dependabot/maven/file_updater/property_value_updater.rb
Sorbet Implementation for Maven PropertyValueUpdater ruby file.
Please pay attention to the fixes in the Maven PropertyValueUpdater ruby file.
=> Strict type `Dependabot::Maven::PropertyValueUpdater`

common/lib/dependabot/file_fetchers/base.rb, gradle/lib/dependabot/gradle/file_fetcher.rb, nuget/lib/dependabot/nuget/file_fetcher.rb
Sorbet Implementation for Gradle FileFetcher ruby file.
Please pay attention to the fixes in the Gradle FileFetcher ruby file.
=> Strict type `Dependabot::Gradle::FileFetcher`

bundler/lib/dependabot/bundler/file_fetcher.rb
Sorbet Implementation for Bundler FileFetcher ruby file.
Please pay attention to the fixes in the Bundler FileFetcher ruby file.
=> Strict type `Dependabot::Bundler::FileFetcher`

pub/lib/dependabot/pub/requirement.rb
Sorbet Implementation for Pub Requirement ruby file.
Please pay attention to the fixes in the Pub Requirement ruby file.
=> Strict type `Dependabot::Pub::Requirement`

devcontainers/.rubocop.yml
Enforce Sorbet strict sigil in the `devcontainers` file to ensure type safety and improve code quality.
N/A
Tests pass and the Sorbet strict sigil is enforced in the `devcontainers` file.
=> Enable `Sorbet/StrictSigil` in `devcontainers`

common/lib/dependabot/shared_helpers.rb, common/spec/dependabot/shared_helpers_spec.rb
This PR aims to enhance the error handling mechanism in the `run_helper_subprocess` method by addressing scenarios where JSON parsing fails and the standard output is empty. This improvement ensures that meaningful error messages are generated when subprocesses encounter issues, making it easier to diagnose problems and reduce unknown errors in Dependabot metrics.
The new helper function `handle_json_parse_error` centralizes the handling of JSON parsing errors. This function checks the standard output and standard error to provide a more informative error message, improving error transparency and debugging efficiency.
- The enhanced error messages will be evident in scenarios where JSON parsing fails and the standard output is empty.
- The new error handling code will pass all existing …
=> Improve Error Handling for JSON Parse Failures in Helper Subprocess

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb, npm_and_yarn/spec/fixtures/projects/npm6/npmrc_env_timeout/.npmrc, npm_and_yarn/spec/fixtures/projects/npm6/npmrc_env_timeout/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm6/npmrc_env_timeout/package.json
**Ecosystem:** NPM AND YARN
**Exception Count:** 1.5K (since April 2024)
**Preface:**  A config file .npmrc is placed in repo which controls settings such as registry, authentication, proxy config etc. It may also contain other related params such as _timeout_ while fetching registry packages. :dependabot: copies this file into temp folder which is used by native helper as configuration source. This issue is surfaced when :dependabot: makes an update in _npm and yarn_ ecosystem.
**Issue:** Some users have a key _timeout=xxxx_ (milliseconds) placed in their .npmrc file. While _timeout_ is used across as a valid key value, there is not official support for it in latest NPM version. It was observed that npm<=5 has support for the _timeout_ while npm>5 uses _fetch-timeout_ . dependabot npm …
=> Ignores timeout in .npmrc file while job update in npm_and_yarn

common/lib/dependabot/shared_helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_that_times_out/.npmrc, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_that_times_out/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_that_times_out/package.json
**Ecosystem :** NPM and YARN
**Exception Count :** 2.3k (Since April 2024)
**Preface:** Resolving issues related with Dependabot::SharedHelpers::HelperSubprocessFailed issues
**Issue:** When there is a private repo listed in config file which is not accessible to dependabot while making an update, Native helper will throw a socket hang up error after some time. Right now, the error is not captured and is thrown into _Dependabot::SharedHelpers::HelperSubprocessFailed_ _unknown_error_ . An example is as following:
`2024/07/10 04:09:02 ERROR request to https://example.com.. failed, reason: socket hang up`
```
+-------------------------------+
| Dependencies failed to update |
+---------------+---------------+
| ejs           | unknown_error |
+---------------+---------------+
```
**Fix:** To …
=> Adds socket hang up error capture

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_with_auth/.npmrc, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_with_auth/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_registry_with_auth/package.json
**Ecosystem :** NPM and YARN
**Exception Count :** 3.9k (Since April 2024)
**Preface:** Resolving issues related with Dependabot::SharedHelpers::HelperSubprocessFailed issues
**Issue:** Dependabot will throw _uknown_error_ in case a private registry is inaccessible due to missing authentication information. Right now, the error is not captured and is thrown into _Dependabot::SharedHelpers::HelperSubprocessFailed_ _unknown_error_ . Following is variation of errors that is returned from native helper:
`Unable to authenticate, need: Basic, Bearer`
`Unable to authenticate, need: Basic realm="https://exs.pkg.visualstudio.com/`
`Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/...., Basic 
realm="https://exs.app.pkg1.visualstudio.com/", TFS-Federated`
`Unable to …
=> Adds error handling for registry auth failures

updater/lib/dependabot/environment.rb
=> Sorbet for environment

common/lib/dependabot/errors.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_invalid_auth_token/.npmrc, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_invalid_auth_token/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_invalid_auth_token/package.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_no_auth_token/.npmrc, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_no_auth_token/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_github_with_no_auth_token/package.json
Ecosystem : NPM and YARN
Exception Count : 3.2k (Since April 2024)
Preface: Resolving issues related with Dependabot::SharedHelpers::HelperSubprocessFailed issues
Issue: Dependabot will throw uknown_error in case a github package registry (hosted at https://npm.pkg.github.com) is inaccessible due to missing or invalid authentication information. Right now, the error is not captured and is thrown into Dependabot::SharedHelpers::HelperSubprocessFailed unknown_error . Following is variation of errors that is returned from native helper:
`Missing or invalid authenticaton token while accessing github package https://npm.pkg.github.com/@Codertocat%2fhello-world-npm`
`401 Unauthorized - GET https://npm.pkg.github.com/@Codertocat%2fhello-world-npm - unauthenticated: User cannot be authenticated …
=> Handles GitHub package authentication errors

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm8/current_name_is_missing/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm8/current_name_is_missing/package.json, npm_and_yarn/spec/fixtures/updated_projects/npm8/current_name_is_missing/package-lock.json, npm_and_yarn/spec/fixtures/updated_projects/npm8/current_name_is_missing/package.json
`Dependabot::NpmAndYarn::FileUpdater::NpmLockfileUpdater.remove_lockfile_packages_name_attribute` takes a parameter `current_name`. Previously, I had typed this as `String`, but we're seeing warnings in production that this is passed a `nil`:
```
Parameter 'current_name': Expected type String, got type NilClass
Caller: /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:764
Definition: /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:808 (Dependabot::NpmAndYarn::FileUpdater::NpmLockfileUpdater#remove_lockfile_packages_name_attribute)
```
This change prevents `remove_lockfile_packages_name_attribute` from being called if `current_name` is `nil`
I decided to guard this function instead of change the …
=> Prevent `remove_lockfile_packages_name_attribute` from being called with `nil`

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/version.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/requirement_spec.rb
This PR adds support for a broader range of npm tags to prevent ill-formed requirement errors. Tags can be used to provide an alias instead of version numbers.
For example, a project might choose to have multiple streams of development and use a different tag for each stream, e.g., stable, beta, dev, canary.
By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.
The next tag is used by some projects to identify the upcoming version.
Ref: https://docs.npmjs.com/cli/v10/commands/npm-dist-tag
The following tags are now supported:
Note: …
=> Add support for versioning with tags for npm other then latest.

Dockerfile.updater-core, Gemfile.lock, updater/Gemfile.lock
Fix #10085.
Fix #10034.
They should be working as expected with Bundler 2.5.16. 
I haven't run tests locally, hopefully CI finds no issues 🤞.
=> Upgrade Bundler to 2.5.16 and RubyGems to 3.5.16

.github/workflows/smoke.yml
Use the official smoke-tests repo, not my fork.
Needs https://github.com/dependabot/smoke-tests/pull/216 to be merged first for CI to get green.
CI gets green and no mention of deivid-rodriguez's repo in dependabot's workflows.
=> Use main smoke-tests repo again

gradle/lib/dependabot/gradle/file_updater.rb, updater/lib/dependabot/updater/operations/update_all_versions.rb
This information was missed due to some local technical error . Adding relevant information for the exception handling and future TODO task.
https://github.com/dependabot/dependabot-core/pull/10061/files#r1667009790
=> Adds relevant information to exception handling

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_override/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_override/package.json
**Preface:** Issues related with 
```
Dependabot::Updater::SubprocessFailed
Subprocess ["corepack npm install <install_args> --force --dry-run false --ignore-scripts --package-lock-only"] failed to run. Check the job logs for error messages
```
**Ecosystem:** NPM and YARN
**Exception Count:** 60k
**Issue:**
This issue is related with native helper failure to update the dependency when an override is mentioned in package.json file as following:
```
"overrides": {
"mongoose": {
"mongodb": "^4.3.0"
}
},
```
This is issue with user did not setup the override property properly resulting in conflict with direct dependency. In this case, the native helper will throw error like following:
```
npm WARN using --force Recommended protections disabled.
npm ERR! code EOVERRIDE
npm ERR! Override for …
```
=> Adds exception handling for override failure errors

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_nested_deps/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_nested_deps/package.json
**Preface:** Related with fixing _Dependabot::SharedHelpers::HelperSubprocessFailed_ issues
**Ecosystem:** NPM and YARN
**Exception count:** 8.4k
**Issue:** This issue is surfaced when :dependabot:  is making an update and _Npm and Yarn_ native helper encounters a dependency with nested aliases. Native helper will throw an exception with following message:
`nested aliases not supported  `
**Fix:** To handle the error and raise a proper exception as following:
```
+------------------------------------------+
|      Dependencies failed to update       |
+---------+--------------------------------+
| express | dependency_file_not_resolvable |
+---------+--------------------------------+
```
=> Fixes Dependabot::SharedHelpers::HelperSubprocessFailed - nested aliases not supported

docker/lib/dependabot/docker/version.rb
Just a small typo I noticed while reading this file
=> Small typo

terraform/lib/dependabot/terraform/update_checker.rb
Strict type `Dependabot::Terraform::UpdateChecker`
Tests pass
=> Strict type `Dependabot::Terraform::UpdateChecker`

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
When an update to a transitive dependency needs to be pinned, this is accomplished by calling the command line tool `dotnet add MyProject.csproj package Some.Transitive.Dependency --version 1.2.3` but invoking this causes any `global.json` files to be processed which might specify a version of the SDK that's not installed on the machine (and might not even be possible to install.)
We already had a mechanism to temporarily rename all `global.json` files to sideline them, so this PR simply makes that code reusable and wraps the call to `dotnet add ...` in that helper.  The end result is that calling this helper tool doesn't depend on a specific version of the SDK and can just fall back to whatever is installed in the updater image.
Fixes #10304
=> temporarily sideline `global.json` when adding a transitive package

npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb, npm_and_yarn/spec/fixtures/projects/npm/simple_with_no_access_registry/.npmrc, npm_and_yarn/spec/fixtures/projects/npm/simple_with_no_access_registry/package-lock.json, npm_and_yarn/spec/fixtures/projects/npm/simple_with_no_access_registry/package.json, updater/lib/dependabot/updater/operations/update_all_versions.rb
**Preface:** fixes unhandled issues related with `Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder::RegistryError`
**Issues:** These issues are related with raised exception `RegistryError`. The example of these exceptions are as following:
`Got 503 response with body`
`Got 404 response with body`
`Got 405 response with body`
**Fix:** Handle `RegistryError` exception and raise `DependencyFileNotResolvable` with valid message passed on to user.
```
+-------------------------------------------------------------------+
|                   Dependencies failed to update                   |
+---------------------------+---------------------------------------+
| package        | dependency_file_not_resolvable        |
+---------------------------+---------------------------------------+ …
```
=> Fixes issues related with Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder::RegistryError

updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
Updated Typings to Strict Type for CreateSecurityUpdatePullRequest
I have updated the typings to be strict type for the `RefreshSecurityUpdatePullRequest ` class. This change aims to improve type safety and reliability of the code by enforcing stricter type checks.
While updating the typings, I made sure to cover all method signatures and type annotations. Please pay special attention to any edge cases that might have been affected by these changes.
By ensuring that all tests pass successfully and no type-related errors are introduced.
=> Strict type Dependabot::Updater.Operations::RefreshSecurityUpdatePullRequest

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
**Fix:** Fixes logging info so that it is only shown on server error 500
=> Fixes logger location for Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder::RegistryError 

common/lib/dependabot/errors.rb
**Preface:** Fixes issues related with Dependabot::ToolVersionNotSupported error in codebase
**Issue**: Issue related to exception handling `Dependabot::ToolVersionNotSupported` which was propagating to `unknown_errors` due to error handler missing from `errors.rb` .
**Fix:** Added error handler to `errors.rb` and handled unsanitary message.
=> Fixes Dependabot::ToolVersionNotSupported issues

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_npm/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_npm/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_npm/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_pnpm/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_pnpm/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_engine_pnpm/pnpm-lock.yaml
**Preface:** Fixes issues related with `Dependabot::SharedHelpers::HelperSubprocessFailed - ERR_PNPM_UNSUPPORTED_ENGINE` error in codebase
**Issue:** Issue raised when `pnpm` returned `ERR_PNPM_UNSUPPORTED_ENGINE` response while updating dependencies.
**Fix:** Add error handler to capture the error case and raise under `Dependabot::ToolVersionNotSupported` exception.
```
+------------------------------------------------------------------+
|                  Dependencies failed to update                   |
+-------------------------------------+----------------------------+
| @blocknote/core                     | tool_version_not_supported |
+-------------------------------------+----------------------------+
```
=> Fixes Dependabot::SharedHelpers::HelperSubprocessFailed - ERR_PNPM_UNSUPPORTED_ENGINE

nuget/Dockerfile
Updated dotnet sdk version in nuget Dockerfile.
SDK 8.0.303 contains runtime for new [.NET 8.0.7](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.7/8.0.7.md).
=> update nuget/Dockerfile, dotnet_sdk_version is now 8.0.303

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/patch_not_applied/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/patch_not_applied/patches/@nx__js@18.0.2.patch, npm_and_yarn/spec/fixtures/projects/pnpm/patch_not_applied/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/tarball_integrity/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/tarball_integrity/pnpm-lock.yaml
**Preface:** Fixes issues related with `err_pnpm_patch_not_applied` and `err_pnpm_tarball_integrity errors`
```
Progress: resolved 2916, reused 2772, downloaded 0, added 0
Progress: resolved 2990, reused 2846, downloaded 0, added 0
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: vite-plugin-node-polyfills@0.21.0
```
`ERR_PNPM_TARBALL_INTEGRITY  Got unexpected checksum
This error happened while installing the dependencies of @helloextend/local-server@3.1.2
at js-yaml@4.1.0`
**Fixes:** Handles response and raise appropriate exceptions
```
+-----------------------------------------+
|      Dependencies failed to update      |
+--------+--------------------------------+
| @nx/js | dependency_file_not_resolvable |
+--------+--------------------------------+
```
=> Fixes issues related with err_pnpm_patch_not_applied and err_pnpm_tarball_integrity errors

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_platform/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_platform/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unsupported_platform/pnpm-lock.yaml
**Preface:** Issues related with  `Dependabot::SharedHelpers::HelperSubprocessFailed`
**Issue:** Error response `ERR_PNPM_UNSUPPORTED_PLATFORM` returned from `PNPM` package manager while updating dependencies.
**Fix:** Parses the response and add exception handling
```
+------------------------------------------------------------+
|               Dependencies failed to update                |
+-------------------------------+----------------------------+
| @swc/core-win32-x64-msvc      | tool_version_not_supported |
+-------------------------------+----------------------------+
```
=> Fixes Dependabot::SharedHelpers::HelperSubprocessFailed - err_pnpm_unsupported_platform error code

common/lib/dependabot/errors.rb, npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Issue related with `out of diskspace` error 
**Issue:** :dependabot: yarn updater throwing `out of diskspace` as following:
`fatal: sha1 file '/home/dependabot/dependabot-updater/repo/.git/index.lock' write error. Out of diskspace`
**Fix:** These `out of diskspace` issues are already handled while parsing. Fix implements handler at updater stage.
=> Adds outofDisk exception handler for updater

common/lib/dependabot/errors.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/requirement_spec.rb
**Preface:** Issue related with `Gem::Requirement::BadRequirementError` exception propagation to unknown errors
**Issue:** `BadRequirementError` is raised if manifest file contains illformed requirement specs.
`"lodash":"preview~1.2"`
**Fix:** Add exception handler to stop propagation to `unknown errors`
```
+------------------------------------------------------------+
|               Dependencies failed to update                |
+------------------------------------+-----------------------+
| medusa-interfaces                  | illformed_requirement |
+------------------------------------+-----------------------+
```
=> Fixes illformed requirement error propagation to unknown errors

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Fixes issues related with Dependabot::Updater::SubprocessFailed  errors.
**Issues:** Following issues were found related to `SubprocessFailed` 
`Usage Error: Parse error when loading /home/dependabot/dependabot-updater/repo/.yarnrc.yml`
`Usage Error: Environment variable not found (AUTH_TOKEN)`
`Request Error: getaddrinfo EAI_AGAIN` 
`Internal Error: ENOENT: no such file or directory, stat '/home/dependabot/dependabot-updater/repo/.yarn/releases/yarn-4.3.1.cjs'`
**Fixes:** Handle responses and add relevant exceptions.
=> Fixes Yarn Dependabot::Updater::SubprocessFailed  issues

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Fixing issues related with Dependabot::DependabotError: [YN0001]
**Issues:** `YN0001` code YARN issues are not yarn specific but rather than application errors which are thorown by program.
**Fix:** Analyze and handle `YN0001` errors.
```
+-------------------------------------------------+
|          Dependencies failed to update          |
+----------------+--------------------------------+
| magnific-popup | dependency_file_not_resolvable |
+----------------+--------------------------------+
```
=> Fix : Dependabot::DependabotError: [YN0001] issues

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_package_manager/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_package_manager/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/meta_fetch_fail/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/meta_fetch_fail/pnpm-lock.yaml
**Preface:** Issues related with `Dependabot::SharedHelpers::HelperSubprocessFailed` pnpm errors
**Issues:** 
1. `4xx,5xx error codes `for PNPM registry response
2. `Invalid package specification` in package.json file
3. `Metadata-ERR_PNPM_META_FETCH_FAIL` inconsistency in registry response
**Fix:** Adds error handlers for above mentioned issues 
```
lodash | dependency_file_not_resolvable 
```
=> Error handlers for Dependabot::SharedHelpers::HelperSubprocessFailed PNPM errors

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Fixes Yarn issues related with `Dependabot::SharedHelpers::HelperSubprocessFailed`
**Issue:** Unhandled exception related with package version missing error
**Fix:** Handled and raise exception with correct message
```
+---------+------------------------------------------------------+
|      lodash      | inconsistent_registry_response              |
+---------+------------------------------------------------------+
```
=> Fixes unhandled couldn't find any versions for package exception

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/broken_metadata/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/broken_metadata/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/missing_workspace_dir_package/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/missing_workspace_dir_package/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/missing_workspace_package/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/missing_workspace_package/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/missing_workspace_package/pnpm-workspace.yaml
**Preface:** Resolving issues related with Dependabot::SharedHelpers::HelperSubprocessFailed 
**Issues:** 
```
err_pnpm_broken_metadata_json
err_pnpm_linked_pkg_dir_not_found
err_pnpm_workspace_pkg_not_found
```
**Fixes:** Handle and adds relevant exception handlers
```
+------------------------------------------+
|      Dependencies failed to update       |
+---------+--------------------------------+
| webpack | dependency_file_not_resolvable |
+---------+--------------------------------+
```
=> Fixes  Dependabot::SharedHelpers::HelperSubprocessFailed related issues

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
**Preface:** Issue related with `Dependabot::SharedHelpers::HelperSubprocessFailed`
**Issues:** Unhandled `Dependabot::SharedHelpers::HelperSubprocessFailed` exceptions in NPM package manager in 
**Fixes:** Adds relevant exception handling in `Dependabot::SharedHelpers::HelperSubprocessFailed`
```
+----------------------------------------------------------------------+
|                    Dependencies failed to update                     |
+-------------------------------------+--------------------------------+
| @typescript-eslint/eslint-plugin    | dependency_file_not_resolvable |
| @typescript-eslint/parser           | dependency_file_not_resolvable |
+-------------------------------------+--------------------------------+
```
=> Fixes NPM unhandled exceptions in Dependabot::SharedHelpers::HelperSubprocessFailed

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Issues related with `Dependabot::SharedHelpers::HelperSubprocessFailed`
**Issues:** Unhandled exceptions related with package discovery failures
**Fixes:** Captures and adds exception handler  `Dependabot::DependencyFileNotResolvable`
=> Fixes Yarn Dependabot::SharedHelpers::HelperSubprocessFailed issues

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb, python/lib/dependabot/python/update_checker/latest_version_finder.rb, python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb, python/spec/fixtures/requirements/custom_index_invalid_env.txt, python/spec/fixtures/requirements/custom_index_valid.txt
**Preface:** Issues related with Python ecosystem
**Issues:**
`ArgumentError: Invalid URI` exception found when user uses Env vars, illformed URLs in index  url
`Incompatible constraints in requirements of dependency`
**Fixes:** Adds relevant exceptions handlers and relay useful messages to users
=> Fixes ArgumentError: Invalid URI errors 

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
**Preface:** Unhandled exceptions related with Dependabot::SharedHelpers::HelperSubprocessFailed
**Issues:** 
`Received malformed response` Registry unreachable due to malformed response
`Command failed: git checkout` Issue while updating dependencies
`Invalid Version` Invalid version format specified in package-lock.json
**Fixes:** Adds exception handlers for the unhandled exceptions.
=> Adds exceptions for Dependabot::SharedHelpers::HelperSubprocessFailed issues

npm_and_yarn/lib/dependabot/npm_and_yarn/registry_parser.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/private_package_access/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/private_package_access/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/private_package_access/pnpm-lock.yaml
**Preface:** Fixes issues with `TypeError:Passed nil into T.must`
**Issue:**
Unhandled private registry URL format in error response resulting in `nil` format error
**Fix:** 
Modified the URL parser to allow for package name capture.
=>  Fixes issues with TypeError:Passed nil into T.must

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
**Preface:** Unhandled exceptions related with Python ecosystem 
**Issues:** Issues related to Dependabot::SharedHelpers::HelperSubprocessFailed in Python ecosystem 
`The Poetry configuration is invalid` - Invalid configuration specified in `project.toml` file
`Could not parse version constraint` - Version constraint mentioned in `project.toml` is unresolvable
`No valid distribution links found` - Python package link mentioned in  `project.toml` is invalid 
**Fixes:** Adds exception handlers to above mentioned error responses and raises valid exceptions with messages
=> Fixes issues with Dependabot::SharedHelpers::HelperSubprocessFailed - Python

.github/workflows/smoke.yml
Changing the smoke test branch back to main now that the [feature branch](https://github.com/dependabot/dependabot-core/pull/10558/files) has been merged.
It fixes build failures that are a result of the missing feature branch.
=> Revert smoke test branch back to main

terraform/lib/dependabot/terraform/requirements_updater.rb, terraform/spec/dependabot/terraform/requirements_updater_spec.rb
Strict type `Dependabot::Terraform::RequirementsUpdater`
I removed an invalid test. There is a guard for `latest_version` being `nil` in `initialize`. So it doesn't appear to be a realistic test that `latest_version` can be `nil` in `updated_requirements`
=> Strict type `Dependabot::Terraform::RequirementsUpdater`

.github/workflows/smoke.yml
=> Revert smoke test branch

composer/lib/dependabot/composer/file_fetcher.rb, composer/lib/dependabot/composer/file_parser.rb, composer/lib/dependabot/composer/helpers.rb
This PR fixes the Sorbet typings in the Composer `file_parser` and `helper`. The goal is to ensure type safety, resolve potential `nil` issues, and comply with strict Sorbet type-checking standards in these modules.
The main changes involve:
- Fixing Sorbet typings in the Composer `file_parser`.
- Applying similar fixes in the Composer `helper` to maintain consistency across the module.
This approach ensures both correct typing and enhanced code reliability without altering the core logic.
The goal will be accomplished when:
- Sorbet runs without any errors or type violations for the updated Composer modules.
- The test suite passes without any failures.
- The changes have been reviewed and confirmed to adhere to the required Sorbet strict typing standards.
=> Fix Sorbet typings for Composer file_parser and helper

.gitmodules
References:
- https://github.com/NuGet/NuGet.Client/compare/6.10.0.100...6.11.1.2
- https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.11
=> Upgrade `NuGet.Client` from `6.10.0.100` to `6.11.1.2`

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
Strict type `Dependabot::NpmAndYarn::FileUpdater`
=> Strict type `Dependabot::NpmAndYarn::FileUpdater`

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
This update sets both the default and fallback npm versions to npm 8, running behind the `npm_fallback_version_above_v6` feature flag. This change aligns with our support policy, which includes npm versions 7, 8, and 9, while deprecating npm 6. Defaulting to npm 8 improves compatibility for projects without explicit npm versioning in their lockfiles, providing more reliable dependency resolution under this flag.
Related Feature Flag PR: 
- https://github.com/github/dependabot-api/pull/5799
- Resolves compatibility issues for projects that previously defaulted to unsupported npm 6 by using npm 8 as the standard fallback.
- Ensures npm 8 is consistently applied as the fallback when no lockfile or lockfile version is specified, under the `npm_fallback_version_above_v6` feature flag.
- The …
=> Update NPM Default and Fallback Versions to NPM 8

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
**Preface:** Issues related with python exception handling
**Issues:**
Unhandled exceptions related with client and server error codes (4xx, 5xx)
```
NetworkConnectionError('404 Client Error: Not Found for url: https://example.com/apache/'
common/lib/dependabot/shared_helpers.rb:191:in `run_helper_subprocess'
```
`HTTP error 404 Client Error:  for url: https://github.com/compute-cloud/[FILTERED_REPO]/archive/a39bf83b6fbfe25be5400cfb3a4070c923246dd4.zip for URL https://****@github.com/compute-cloud/[FILTERED_REPO]/archive/a39bf83b6fbfe25be5400cfb3a4070c923246dd4.zip`
**Fix:** Adds exception handlers related to the error codes
=> Fixes : exception handling for client and server codes (4xx, 5xx)

maven/lib/dependabot/maven/update_checker/requirements_updater.rb
Add sorbet typing to maven requirements updater
=> Add sorbet typing to maven requirements updater

bin/docker-dev-shell, maven_osv/Dockerfile
Bringing in some changes that include the osv-scanner tool in the maven_osv ecosystem docker image.  I'm going to start integrating the tool into the ruby codebase as part of this POC.
I haven't done most of these, this is targeting a non-main branch and is part of a POC.  This is not yet intended for production use.
=> Adding osv scanner to maven_osv docker image

updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
**Preface:** This PR is related with https://github.com/dependabot/dependabot-core/pull/10727
**Task:** Adds additional logs statement for telemetry data collection in case there is a difference between security-advisory and first-dependency
=> Adds additional log for wrong dependency rebase (dependency_changed) issue

bundler/lib/dependabot/bundler/file_parser.rb, bundler/lib/dependabot/bundler/helpers.rb, bundler/lib/dependabot/bundler/package_manager.rb, bundler/spec/dependabot/bundler/file_parser_spec.rb, bundler/spec/dependabot/bundler/helper_spec.rb, bundler/spec/dependabot/bundler/package_manager_spec.rb, common/lib/dependabot/ecosystem.rb, common/lib/dependabot/requirement.rb, common/spec/dependabot/ecosystem_spec.rb, common/spec/dependabot/requirement_spec.rb
This PR expands the centralized ecosystem format by adding requirements information for the Bundler package manager. This enhancement allows for improved management and tracking of Bundler version constraints directly within the package manager's configuration.
This approach keeps the requirements information organized within the package manager’s context, simplifying the addition of similar support for other ecosystems in the future.
- The added requirements information should be verifiable by examining Bundler’s version constraints in the dependency resolution output.
- Tests have been updated to validate various Bundler requirements scenarios, ensuring correct functionality.
=> Expand Centralized Ecosystem Format with Requirements Information for Bundler Package Manager

common/lib/dependabot/pull_request_creator/github.rb
Adds additional logging information for Github PR  creator, This is to validate the changes for existing_branches issue https://github.com/dependabot/dependabot-core/pull/10878
=> Adds additional logs for Github PR creator 

bundler/lib/dependabot/bundler/file_parser.rb, bundler/lib/dependabot/bundler/helpers.rb, bundler/lib/dependabot/bundler/language.rb, bundler/spec/dependabot/bundler/helper_spec.rb, bundler/spec/dependabot/bundler/language_spec.rb
This PR introduces the collection of Ruby language requirements for the Bundler ecosystem, implementing metrics for language requirements. This enhancement provides greater visibility into language compatibility requirements specified by Bundler, helping ensure accurate dependency updates and ecosystem compatibility insights.
This implementation processes Ruby language requirements across supported files, leveraging existing `requirement` and `version` logic to maintain consistency. 
- **Reproduction**: Metrics accurately reflect defined Ruby constraints in test cases.
- **Feature Demonstration**: The added metrics can be validated through enhanced test cases requirement constraint and max, min versions.
=> Add Ruby Language Requirement Collection for Bundler Ecosystem Metrics

terraform/helpers/build, terraform/spec/dependabot/terraform/file_parser_spec.rb
Fix the issue #10315 by using the latest version of hcl2json
=> Update hcl2json to version `0.6.4`

composer/lib/dependabot/composer.rb, composer/lib/dependabot/composer/file_fetcher.rb, composer/lib/dependabot/composer/file_fetcher/path_dependency_builder.rb, composer/lib/dependabot/composer/file_parser.rb, composer/lib/dependabot/composer/file_updater.rb, composer/lib/dependabot/composer/file_updater/lockfile_updater.rb, composer/lib/dependabot/composer/helpers.rb, composer/lib/dependabot/composer/language.rb, composer/lib/dependabot/composer/package_manager.rb, composer/lib/dependabot/composer/update_checker.rb, composer/lib/dependabot/composer/update_checker/latest_version_finder.rb, composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/dependabot/composer/package_manager_spec.rb
This PR refactors the Composer-related codebase to improve maintainability and readability. Key changes include:
- Code cleanup to remove redundancies and improve clarity.
- Moving common strings into constants for better reusability and central management.
- Moving common version and platform helper functions into dedicated helper modules.
**Why:**  
This ensures a more modular and maintainable structure, reduces duplication, and aligns with best practices.
N/A
- Constants and helper functions were moved to centralized locations. Please review to ensure this approach aligns with project standards.
- Additional cleanup was done in the Composer code; please verify no unintended changes were introduced.
- All tests and linters pass successfully.
- Code functionality remains the same while …
=> Refactor Composer: Code Cleanup, Constants, and Helper Functions

pub/lib/dependabot/pub/file_parser.rb, pub/lib/dependabot/pub/language.rb, pub/lib/dependabot/pub/package_manager.rb, pub/spec/dependabot/pub/pub_package_manager_spec.rb
Adds metric collection for Dart language ecosystem along with pub package manager
=> Metric collection for Dart ecosystem

nuget/lib/dependabot/nuget/file_parser.rb, nuget/lib/dependabot/nuget/language.rb, nuget/lib/dependabot/nuget/package_manager.rb, nuget/spec/dependabot/nuget/file_parser_spec.rb, nuget/spec/dependabot/nuget/language_spec.rb, nuget/spec/dependabot/nuget/nuget_package_manager_spec.rb
Dotnet ecosystem metric collection
Collects following:
Nuget package manager version information 
Dotnet languages C#, F#, VB metric along with targeted framework version
Ecosystem metric
=> Dotnet ecosystem metric collection

npm_and_yarn/Dockerfile
I'm debugging a `pnpm`-related issue and noticed we're a few versions behind... let's get caught up to pickup any upstream bugfixes.
=> Bump pnpm to 9.15.0

CODEOWNERS
Enforce ownership of the `dotnet_sdk` updater
=> Add `@dependabot/azure-dev-ops` as owners of `dotnet_sdk`

dotnet_sdk/lib/dependabot/dotnet_sdk/file_parser.rb, dotnet_sdk/lib/dependabot/dotnet_sdk/language.rb, dotnet_sdk/lib/dependabot/dotnet_sdk/package_manager.rb, dotnet_sdk/spec/dependabot/dotnet_sdk/file_parser_spec.rb
Implements _DotnetSDK_ metric collection. 
DotnetSdk metric collection will start appearing in ecosystems metric collection.
=> Metric collection for Dotnet SDK

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_json/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_json/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_yaml/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/invalid_yaml/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/unmet_peer_deps/.npmrc, npm_and_yarn/spec/fixtures/projects/pnpm/unmet_peer_deps/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unmet_peer_deps/pnpm-lock.yaml
Enhancements to error handling:
1. un-parsable dependency in _package.json_ (dependency name format issue)
2. Malformed _pnpm-lock.yaml_ file (out of date lockfile, unexpected content)
3. Configuration missing error while upgrading peer deps (auto-install-peers false)
=> Fixes [1.2k weekly errors] [JS] SubprocessHelperFailure issues

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
Adds error handlers for poetry unhandled exceptions
=> Fixes [4k weekly] [pip] unhandled poetry exceptions

npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb
Adds exception handler for malformed package manager version.
=> Fixes [1.2k weekly errors] [JS] exception handler for malformed package manager version

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/unexpected_store/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/unexpected_store/pnpm-lock.yaml
Fixes SharedHelpers::HelperSubprocessFailed errors in the JavaScript ecosystem.
=> Fixes [1.2k weekly errors] [JS] SharedHelpers::HelperSubprocessFailed errors

bundler/lib/dependabot/bundler/file_updater/gemfile_updater.rb, bundler/lib/dependabot/bundler/file_updater/gemspec_dependency_name_finder.rb
We are adding sorbet typing to all files in `dependabot-core`.
This PR adds typing for:
- `bundler/lib/dependabot/bundler/file_updater/gemfile_updater.rb`
- `bundler/lib/dependabot/bundler/file_updater/gemspec_dependency_name_finder.rb`
Linters and specs pass.
=> Sorbet: add strict typing for GemfileUpdater and GemspecDependencyNameFinder

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
Reverts dependabot/dependabot-core#11299
=> Revert "Removing corepack usage from else clause"

bundler/lib/dependabot/bundler/file_updater/gemspec_updater.rb
Add Sorbet type checking: bundler/lib/dependabot/bundler/file_updater/gemspec_updater.rb
Add Sorbet type checking: bundler/lib/dependabot/bundler/file_updater/gemspec_updater.rb
Ensured all the CI jobs of this PR is passing
=> Add Sorbet Type Checking for file: bundler/lib/dependabot/bundler/file_updater/gemspec_updater.rb

swift/lib/dependabot/swift/file_parser/manifest_parser.rb
Add Sorbet type checking for swift/lib/dependabot/swift/file_parser/manifest_parser.rb
All CI checks should pass and there shouldn't be any new errors in Sentry.
=> Add sorbet type checking for swift/file_parser/manifest_parser.rb

python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb, python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb
Adds exception handler for _Dependabot::SharedHelpers::HelperSubprocessFailed_ errors.
=> Fixes [3.2k weekly errors] [pip] exception handlers for Python ecosystem

npm_and_yarn/lib/dependabot/npm_and_yarn/version.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/version_spec.rb
Fixes https://github.com/dependabot/dependabot-core/issues/11293 where a version extract returns some additional information that forces job failures
=> Fixes argument error when corepack return verbose information along with version.

composer/lib/dependabot/composer/file_updater.rb
Adding type check for composer/file_updater.rb
As part of updating type check whole dependency-core source code, I have added type check for composer/file_updater.rb
Ran 
```
% bundle exec srb tc -a
No errors! Great job.
```
=> Adding type check for composer/file_updater.rb

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
This also adds a new error message pattern:
```
Unable to resolve dependencies. 'Some.Package 1.2.3' is not compatible with ...
```
=> consolidate exception error creation

bundler/lib/dependabot/bundler/update_checker/force_updater.rb, bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb, bundler/spec/fixtures/projects/bundler2/invalid_gem_information_in_gemfile/Gemfile, bundler/spec/fixtures/projects/bundler2/invalid_gem_information_in_gemfile/Gemfile.lock
```
Parameter 'version': Expected type Gem::Version, got type String with value ""
Caller: /home/dependabot/bundler/lib/dependabot/bundler/update_checker/force_updater.rb:55
Definition: /home/dependabot/bundler/lib/dependabot/bundler/requirement.rb:15 (Dependabot::Bundler::Requirement.satisfied_by?)
```
=> Fixes [part of][weekly 8.3k] [bundler] "Expected type Gem::Version" in bundler 

npm_and_yarn/Dockerfile
https://github.com/pnpm/pnpm/releases/tag/v9.15.4
=> Bump pnpm to 9.15.4

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
Adds error handler for YN0001 class errors
=> Adds error handler for YN0001 class errors

elm/lib/dependabot/elm/update_checker/elm_19_version_resolver.rb
Add sorbet types to: `elm/lib/dependabot/elm/update_checker/elm_19_version_resolver.rb`
All tests should continue to pass as before and there shouldn't be any new sorbet runtime errors in Sentry
=> Add sorbet types to elm_19_version_resolver.rb

npm_and_yarn/Dockerfile
This PR bumps pnpm to 9.15.5 which includes fix for pnpm/pnpm#6530 which is downstream issue for the following issues:
- #7258
- #7851 
- #10124
Closes #7258 
Closes #7851
Closes #10124
This PR also upgrades corepack to 31.0 to support npm signature key update (https://github.com/nodejs/corepack/pull/614
Release note for each package here
- https://github.com/pnpm/pnpm/releases/tag/v9.15.5
- https://github.com/nodejs/corepack/releases/tag/v0.31.0
N/A. simple pnpm and corepack update.
the only breaking changes in corepack was dropping node 21.x (according to release note), and still supports node 20.x.
From changelog of pnpm.
=> chore: bump pnpm to 9.15.5 and corepack to 0.31.0

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_workspace_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb, npm_and_yarn/spec/fixtures/projects/pnpm/catalog_prettier/package.json, npm_and_yarn/spec/fixtures/projects/pnpm/catalog_prettier/pnpm-lock.yaml, npm_and_yarn/spec/fixtures/projects/pnpm/catalog_prettier/pnpm-workspace.yaml
Adding catalog check to `pnpm_lock_changed` to ensure that `pnpm` is not run for catalog dependencies
We do not remove catalogs from lock file for pnpm
=> Add catalog check to pnpm_lock_changed

npm_and_yarn/lib/dependabot/npm_and_yarn/constraint_helper.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/constraint_helper_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb
This PR introduces a constraints check to ensure that if no valid constraints exist, the function returns no requirement. This prevents incorrect requirement values from being returned when constraints are missing or invalid.  
The key change here is the addition of a validation step to check for constraints before returning a requirement. If no valid constraints are found, it now correctly returns no requirement.  
- The issue where requirements were incorrectly determined in the absence of constraints should no longer occur.  
- The tests have been updated to verify that no requirement is returned when constraints are missing or invalid.  
- Running the complete test suite ensures that existing functionality remains unaffected while this fix is correctly applied.
=> Return No Requirement if No Valid Constraints Exist

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb
Adds a prelim check for patch and local dependencies to prevent unnecessary updates
=> Fixes [part of] [npm and yarn] NoFilesChanged error

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
Removing the `:enable_pnpm_workspace_catalog` feature flag and allowing all users to update pnpm catalogs
PNPM catalog will be rolled out for all users
=> Remove `:enable_pnpm_workspace_catalog` feature flag

docker/lib/dependabot/docker/update_checker.rb, docker/spec/dependabot/docker/update_checker_spec.rb
Adds error handlers for bad response while accessing private registries
=> Fixes [ part of weekly 1.3k] [docker] RestClient::ServerBrokeConnection and related errors

docker/lib/dependabot/docker/update_checker.rb, docker/spec/dependabot/docker/update_checker_spec.rb
Adds RestClient exceptions to Docker Transient errors
=> Adds RestClient exceptions to Docker Transient errors

docker/lib/dependabot/docker/update_checker.rb, docker/spec/dependabot/docker/update_checker_spec.rb
Adds handler for bad response returned from RestClient
=> Adds handler for bad response returned from RestClient

docker/.rubocop.yml, docker/lib/dependabot/docker/update_checker.rb, docker/lib/dependabot/docker/utils/credentials_finder.rb
Strict type Dependabot::Docker::UpdateChecker
Also enabled Sorbet/StrictSigil to prevent regressions
Tests pass
=> Strict type `Dependabot::Docker::UpdateChecker`

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb, go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
Handle Sentry errors like the following:
```
go mod download github.com/vmware/[FILTERED_REPO]
go: github.com/osbuild/[FILTERED_REPO]/internal/boot/vmwaretest imports
github.com/vmware/[FILTERED_REPO]/govc/importx: github.com/vmware/[FILTERED_REPO]@v0.38.0: missing go.sum entry for go.mod file; to add it:
go mod download github.com/vmware/[FILTERED_REPO]
go: downloading github.com/bandprotocol/[FILTERED_REPO] v0.0.1
go: module github.com/bandprotocol/[FILTERED_REPO]@v0.0.1 found, but does not contain package 
github.com/bandprotocol/[FILTERED_REPO]/[FILTERED_REPO]-api/client/go-client
```
=> Handle `module does not contain package` & `missing go.sum entry` errors

bundler/helpers/spec_helpers/gem_net_http_adapter.rb
Sorbet type checking for gem_net_http_adapter
N/A
=> Sorbet type checking for gem_net_http_adapter

terraform/lib/dependabot/terraform/registry_client.rb, terraform/spec/dependabot/terraform/registry_client_spec.rb
Adds handler to private registries timeout and socket errors
=> Adds handler to private registries timeout and socket errors

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
Adds handlers for miscellaneous Poetry error handlers
=> Fixes [part of 1.9k] [Python] Poetry errors

npm_and_yarn/lib/dependabot/npm_and_yarn.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
Adds handlers for Yarn001 class errors
=> Adds handlers for yarn001 errors

terraform/lib/dependabot/terraform/file_updater.rb, terraform/spec/dependabot/terraform/file_updater_spec.rb
Adds handlers for terraform exceptions.
=> Fixes [1.9k weekly] [terraform] exceptions

python/lib/dependabot/python/file_updater/pipfile_preparer.rb, python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb, python/spec/fixtures/pipfile_files/malformed_pipfile_source_missing, python/spec/fixtures/pipfile_files/malformed_pipfile_source_missing.lock
raise dependency_file_not_resolvable error on malformed pipfile contents
```
+------------------------------------------+
|      Dependencies failed to update       |
+---------+--------------------------------+
| certifi | dependency_file_not_resolvable |
+---------+--------------------------------+
```
=> Fixes [Pipfile] [Python] raise error on malformed pipfile contents

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb, terraform/lib/dependabot/terraform/file_updater.rb, terraform/spec/dependabot/terraform/file_updater_spec.rb
=> Adds various fixes for terraform and python exceptions

docker/lib/dependabot/docker/update_checker.rb, docker/spec/dependabot/docker/update_checker_spec.rb
Fixes issue when docker registry image tag returns empty response
=> Fixes docker image fetch empty response issue

Dockerfile.updater-core
Fixing a typo in the updater-core dockerfile
We will be able to create the dependabot folder for docker_compose
=> Renaming docker-compose to docker_compose

updater/lib/dependabot/setup.rb
Adding docker compose to set up
We will be able to register docker compose during the set up
=> Adding Docker Compose to setup

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
If a security update job was started but that specific dependency wasn't found or wasn't vulnerable, report `security_update_not_needed` to align with common Ruby code.
=> report `security_update_not_needed` when security update can't be performed

python/helpers/requirements.txt, python/spec/dependabot/python/file_parser/setup_file_parser_spec.rb, python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb
Reverts dependabot/dependabot-core#11596
=> Revert "Bump pip from 24.0 to 25.0.1 in /python/helpers in the pip group across 1 directory"

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.PackagesConfig.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
Some legacy project files import targets that only ship with Visual Studio.  Previously these specific files were sidelined during an update process because they interfere with the MSBuild evaluation.  With direct dependency discovery now turned on by default, MSBuild again fails to parse these files.
The fix is to simply reuse our magic file patcher and wrap the discovery calls with it.
I recommend turning off whitespace when looking at the diff, but the only change was to wrap the body of the main discovery method with `using (new WebApplicationTargetsConditionPatcher(actualProjectPath)) { ... }`; literally nothing else changed.
=> manually sideline `Microsoft.WebApplication.targets` during direct dependency discovery

go_modules/Dockerfile, go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb, go_modules/spec/dependabot/go_modules/file_updater_spec.rb
This update involves upgrading the Go version used in the Dockerfile for the Go module from version 1.20 to version 1.24. The new version brings improvements in performance, security, and support for newer Go features. This change ensures that the toolchain leverages the latest features and optimizations available in Go 1.24, while maintaining compatibility with the rest of the application dependencies.
Ran Dependabot CLI and ensured that all the dependencies are compatible with the new Go version.
=> Update Go Version in Toolchain from 1.20 to 1.24 in Dockerfile

bun/Dockerfile, npm_and_yarn/Dockerfile
https://bun.sh/blog/bun-v1.2.2
https://bun.sh/blog/bun-v1.2.3
https://bun.sh/blog/bun-v1.2.4
https://bun.sh/blog/bun-v1.2.5
=> Bump Bun to 1.2.5

uv/Dockerfile, uv/lib/dependabot/uv/file_updater/lock_file_updater.rb, uv/spec/dependabot/uv/file_updater/lock_file_updater_spec.rb, uv/spec/fixtures/uv_locks/minimal.lock, uv/spec/fixtures/uv_locks/minimal_updated.lock
GA unearthed some `uv.lock` file handling issues and this PR aims to simplify the `LockFileUpdater`.
We have removed the implementation that attempted to parse the lock file and extract relevant sections and we are instead leaning on the built in single dependency update using `--update-package`.
We have also updated python version detection for the lock file taking into account any `.python-version` file in the same folder and handle this using the `LanguageVersionManager`.
Follows https://github.com/dependabot/dependabot-core/issues/10478
Dry ran against the `dependabot-uv` test repo without error.
`./bin/dry-run.rb uv dsp-testing/dependabot-uv`
We tried a dry run against a repo that did have issues, but all dependencies were reported as up to date now:
`./bin/dry-run.rb uv …
=> Update and simplify uv.lock file handling

python/Dockerfile, python/lib/dependabot/python/file_fetcher.rb, python/lib/dependabot/python/language.rb, python/lib/dependabot/python/language_version_manager.rb, python/lib/dependabot/python/requirement.rb, python/spec/dependabot/python/file_fetcher_spec.rb, python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb, python/spec/dependabot/python/requirement_spec.rb, python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
This PR fixes the Python ecosystem language support check. The previous implementation had problems in checking the supported language through the detected version when detected, which is causing raising language not supported error for supported versions.
- Fix python language not supported through pre installed versions. 
- Combine deptecation/unsupported mechanism with pre installed python version to provide accurate language support check. 
- The fix should correctly identify and use the best-matching Python version.
- Existing tests pass, confirming no regressions in functionality.
=> Fix Python Ecosystem Language Support Check

.devcontainer/post-create.sh, nuget/Dockerfile
Context: https://github.com/dotnet/core/issues/9799
The dot.net redirector has issues currently, using the CDN URL directly is more reliable.
NuGet tests pass and container images are built successfully.
=> Use CDN URL for dotnet-install script

elm/.rubocop.yml, elm/lib/dependabot/elm/file_parser.rb, elm/lib/dependabot/elm/file_updater.rb, elm/lib/dependabot/elm/metadata_finder.rb
=> Strict type `elm`

pub/.rubocop.yml, pub/lib/dependabot/pub/file_parser.rb, pub/lib/dependabot/pub/file_updater.rb, pub/lib/dependabot/pub/helpers.rb, pub/lib/dependabot/pub/update_checker.rb, pub/lib/dependabot/pub/version.rb
=> Strict type `pub`

bun/lib/dependabot/bun/metadata_finder.rb, bun/spec/dependabot/bun/metadata_finder_spec.rb
Strict type `Dependabot::Bun::MetadataFinder`
This class didn't have any unit tests or Sorbet types, and I think some of the types were incorrect. Specifically `all_version_listings` and anythig that called it.
Tests pass
=> Strict type `Dependabot::Bun::MetadataFinder`

go_modules/Dockerfile, go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb, go_modules/spec/dependabot/go_modules/file_updater_spec.rb
Reverts dependabot/dependabot-core#11826
=> Revert "Update Go Version in Toolchain from 1.20 to 1.24 in Dockerfile"

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
**What are you trying to accomplish?**
This pull request aims to revert the recent changes related to Sorbet typing in the `npm_and_yarn/version.rb` file that were introduced in [[PR #11903](https://github.com/dependabot/dependabot-core/pull/11903/files#diff-90eca29ed297dba81a7ce1bc74ff4d3293e109bfa4e4183f4170d7322a9cbf27L79)](https://github.com/dependabot/dependabot-core/pull/11903/files#diff-90eca29ed297dba81a7ce1bc74ff4d3293e109bfa4e4183f4170d7322a9cbf27L79). The changes have caused a `TypeError` to be raised, specifically when `nil` values are passed into `T.must`, causing the application to fail.
**Why this change?**
The error traceback shows the following:
```
TypeError: Passed `nil` into T.must
from dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/_types. …
```
=> Revert Sorbet Typing Changes to Fix TypeError for `nil` in `T.must`

sorbet/config
RSpec tests aren't possible to typecheck with Sorbet. This is just reducing our overall Sorbet coverage level for no reason.
N/A
=> Ignore `docker_compose` spec typechecking

.rubocop.yml, bun/.rubocop.yml, bundler/.rubocop.yml, cargo/.rubocop.yml, common/.rubocop.yml, composer/.rubocop.yml, devcontainers/.rubocop.yml, docker/.rubocop.yml, docker_compose/.rubocop.yml, dotnet_sdk/.rubocop.yml, elm/.rubocop.yml, git_submodules/.rubocop.yml, github_actions/.rubocop.yml, go_modules/.rubocop.yml, gradle/.rubocop.yml, helm/.rubocop.yml, hex/.rubocop.yml, maven/.rubocop.yml, npm_and_yarn/.rubocop.yml, nuget/.rubocop.yml, omnibus/.rubocop.yml, pub/.rubocop.yml, python/.rubocop.yml, silent/.rubocop.yml, swift/.rubocop.yml, updater/.rubocop.yml, uv/.rubocop.yml
Make Sorbet `# typed: strict` opt-out instead of opt-in.
This change switches `Sorbet/StrictSigil` from default off to default on at the root directory, and disables it explicitly in the ecosystems which currently do not conform.
Rubocop tests pass
=> Make Sorbet strict type opt-out instead of opt-in

docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb
Since the release of https://github.com/dependabot/dependabot-core/pull/11942 our `docker_compose` tests have started failing. This PR updates the digest tests to better reflect real world scenarios after the changes from docker image component comparison change
`docker_compose` tests will pass
=> Update the digest tests to better reflect real world scenarios

nuget/helpers/lib/NuGetUpdater/Directory.Packages.props, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/AnalyzeCommand.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/CloneCommand.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/DiscoverCommand.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/RunCommand.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestBase.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/LoggerTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/NuGetUpdater.Core.csproj, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/OpenTelemetryLogger.cs
Instrument open telemetry for the nuget updater C# code, which will significantly improve log visibility.
Added a unit test to confirm compatibility with existing logger.
=> Instrument OTel for the Nuget Updater C# Code

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatePermittedAndMessageTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
Allows a job to run when we're explicitly updating an existing pull request.
=> allow update for existing pr if specifically requested

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
When doing direct dependency discovery, the `obj/` directory gets populated with some generated files that can get picked up later and reported as an editable file.  This doesn't cause any issues, but it can make the logging messy.
=> exclude generated files during build file discovery

README.md
I saw this in the Readme and didn't understand what it meant by "checking" until I `git blame`'d the context from https://github.com/dependabot/dependabot-core/pull/7407.
So reword to make it more clear.
=> Slight reword for clarity

npm_and_yarn/Dockerfile
Reverts dependabot/dependabot-core#10750
=> Revert "bump node version to 22"

bun/lib/dependabot/bun/update_checker/version_resolver.rb
Refine the `VersionResolver` class for the Bun package manager to simplify logic and remove unnecessary comments.
This refinement was intended to simplify the code and removing unnecessary comments. 
- The existing functionality is preserved.
- The code is simpler and easier to maintain.
- The refactored code passes all existing tests, and no new issues are introduced.
=> Refine VersionResolver for Bun

uv/lib/dependabot/uv/file_updater/pyproject_preparer.rb, uv/spec/dependabot/uv/file_updater/pyproject_preparer_spec.rb
We are fixing how extras are handled when parsing the `pyproject.toml` file.
When parsing the `pyproject.toml` file, the extras are not being preserved correctly. In the example in the issue below the `google` extras were being parsed out, resulting in the related extras being dropped from the `uv.lock` file.
```
[project]
name = "dependabot-uv-bug-11896"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
"django>=5.1.7",
"django-storages[google]>=1.14.5",
"whitenoise>=6.8.2",
]
[dependency-groups]
dev = [
"pytest>=8.3.5",
]
```
Was parsed to:
```
[project]
name = "dependabot-uv-bug-11896"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [ …
```
=> Fix pyproject.toml parsing extras

bin/dry-run.rb
Properly convert
--requirements-update-strateg
y value to Enum
=> Properly convert --requirements-update-strategy value to Enum

maven/lib/dependabot/maven/package/package_details_fetcher.rb, maven/lib/dependabot/maven/update_checker/property_updater.rb, maven/lib/dependabot/maven/update_checker/version_finder.rb, maven/spec/dependabot/maven/package/package_details_fetcher_spec.rb, maven/spec/dependabot/maven/update_checker/version_finder_spec.rb, maven/spec/fixtures/maven_central_metadata/with_release.html
The goal of this pull request is to standardize the Maven package fetcher to support generic package release details. This change will make the Maven package fetcher more flexible, allowing it to support a broader range of use cases and package types. This will improve the maintainability and extensibility of the package fetching logic across different ecosystems.
The key areas for attention are:
- The refactoring of the existing Maven package fetcher to align with the generic structure for fetching package release details.
- Ensuring that the changes don’t break any existing functionality, especially in terms of compatibility with the current Maven ecosystem.
The changes were made to support a more unified and flexible structure for fetching package details, allowing for future …
=> Standardize Maven Package Fetcher to Support Generic Package Release Details

composer/lib/dependabot/composer/file_fetcher/path_dependency_builder.rb, composer/lib/dependabot/composer/metadata_finder.rb, composer/lib/dependabot/composer/native_helpers.rb, composer/lib/dependabot/composer/requirement.rb, composer/lib/dependabot/composer/update_checker.rb
Increase Sorbet type coverage
N/A
Tests pass
=> Strict type some more of `composer`

maven/.rubocop.yml, maven/lib/dependabot/maven/file_parser.rb, maven/lib/dependabot/maven/file_parser/property_value_finder.rb, maven/lib/dependabot/maven/file_parser/repositories_finder.rb, maven/lib/dependabot/maven/file_updater.rb, maven/lib/dependabot/maven/file_updater/declaration_finder.rb, maven/lib/dependabot/maven/file_updater/property_value_updater.rb, maven/lib/dependabot/maven/metadata_finder.rb, maven/lib/dependabot/maven/package/package_details_fetcher.rb, maven/lib/dependabot/maven/requirement.rb, maven/lib/dependabot/maven/update_checker.rb, maven/lib/dependabot/maven/update_checker/property_updater.rb, maven/spec/dependabot/maven/token_bucket_spec.rb, maven/spec/dependabot/maven/version_parser_spec.rb, maven/spec/spec_helper.rb
=> Strict type remaining files in `maven` ecosystem

.github/workflows/check-sorbet-typing-mode.yml
I am adding a GitHub Actions workflow to automatically enforce the presence of Sorbet typings (`# typed: strict` or `# typed: strong`) at the top of any changed Ruby files. This will help ensure that all Ruby files in the repository maintain proper Sorbet type checking.
**Why?**  
This change will prevent the growth of untyped code in the project and ensure that new Ruby files or changes to existing Ruby files have Sorbet typings added consistently. This is important for keeping the codebase maintainable and ensuring that type errors are caught early in the development process.
Please review the logic for checking Sorbet typings at the top of Ruby files and confirm that the error messages are clear and helpful for contributors. Let me know if you think there’s a better way to handle …
=> Enforce Sorbet Typings in Changed Ruby Files

swift/.rubocop.yml, swift/lib/dependabot/swift/file_fetcher.rb, swift/lib/dependabot/swift/file_parser.rb, swift/lib/dependabot/swift/file_parser/dependency_parser.rb, swift/lib/dependabot/swift/file_parser/manifest_parser.rb, swift/lib/dependabot/swift/file_updater.rb, swift/lib/dependabot/swift/file_updater/lockfile_updater.rb, swift/lib/dependabot/swift/file_updater/manifest_updater.rb, swift/lib/dependabot/swift/file_updater/requirement_replacer.rb, swift/lib/dependabot/swift/native_requirement.rb, swift/lib/dependabot/swift/requirement.rb, swift/lib/dependabot/swift/update_checker.rb, swift/lib/dependabot/swift/update_checker/requirements_updater.rb, swift/lib/dependabot/swift/update_checker/version_resolver.rb
Strict Sorbet type the remainder of the `swift` ecosystem, and enable the `Sorbet/StrictSigil` cop.
N/A
Tests pass
=> Strict type the `swift` ecosystem

maven/spec/dependabot/maven/package/package_details_fetcher_spec.rb
This PR adds more test cases to improve coverage for the construction of Maven dependency file URLs. It ensures that the logic handles various scenarios, such as URLs with special characters, classifiers, and different versions.
The added test cases focus on edge cases for URL construction, particularly handling special characters (like `_`, `-`). This ensures that the URL is correctly formed and encoded when needed.
- The goal will be accomplished if all tests pass and cover the necessary edge cases, confirming the correctness of the URL construction logic for Maven dependencies.
- Any issues with URL construction, especially related to special characters in classifiers, should be caught by the tests.
=> Add more specs for Maven dependency files URL construction

bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb, common/lib/dependabot/package/package_latest_version_finder.rb
Fixes related to https://github.com/dependabot/dependabot-core/issues/12033 where dependency version is malformed.
=> Fixes issue when a malformed dependency version is specified

helm/lib/dependabot/helm/file_fetcher.rb, helm/spec/dependabot/helm/file_fetcher_spec.rb
Remove feature flag `allow_beta_ecosystems` from helm
closes: https://github.com/dependabot/dependabot-core/issues/12121
Feature flag will no long be needed for helm
=> Remove helm beta feature flag

common/lib/dependabot/shared_helpers.rb, npm_and_yarn/.rubocop.yml, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/yarn_lock.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/bun_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_preparer.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/package/registry_finder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/dependency_files_builder.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/library_detector.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/requirements_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
Improve Sorbet type coverage
This gets us to 65% coverage
Tests pass
=> Strict type most of `npm_and_yarn`

common/lib/dependabot/shared_helpers.rb, npm_and_yarn/.rubocop.yml, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
Finish strict typing of `npm_and_yarn`
I made `run_helper_subprocess` return `T.untyped` as the number of return types was becoming unweildy. I'd like to properly resolve this by using a generic return type, but this escape hatch will do for now. 
Tests pass
=> Complete Sorbet strict typing of `npm_and_yarn` ecosystem

common/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb, common/spec/dependabot/pull_request_creator/branch_namer/solo_strategy_spec.rb, common/spec/dependabot/pull_request_creator/branch_namer_spec.rb, docker/spec/dependabot/docker/update_checker_spec.rb
Reverts dependabot/dependabot-core#12137
=> Revert "Refactor branch naming strategy for docker dependencies with digests."

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/json_lock.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb, npm_and_yarn/spec/fixtures/updated_projects/npm6/subdependency_update_tab_indentation/package-lock.json
The goal of this pull request is to implement the following changes:
1. Support updating lockfileVersion `v1` (npm <=6) to lockfileVersion `v3` (npm >=7).
2. Clean up and remove the obsolete `npm_fallback_version_above_v6` feature flag.
This change ensures compatibility between npm 6 (lockfile v1) and newer npm versions (npm 7 and above, lockfile v3), while also reducing complexity in the codebase by eliminating the outdated feature flag.
- This PR resolves issues related to maintaining compatibility between npm 6 and newer npm versions (npm 7 and above).
- It also addresses the problem of managing obsolete feature flags in the codebase, making the code cleaner and easier to maintain.
- Please verify that the logic for handling npm 6 (lockfile v1) and npm 7+ (lockfile v3) updates is …
=> Support Update from npm 6 (lockfile v1) to npm 8, 10 (lockfile v3) and Cleanup `npm_fallback_version_above_v6` Feature Flag

docker/lib/dependabot/docker/file_parser.rb, docker/lib/dependabot/docker/update_checker.rb, docker/lib/dependabot/shared/shared_file_parser.rb, docker/lib/dependabot/shared/shared_file_updater.rb, docker/spec/dependabot/docker/common/shared_examples_for_docker_update_checkers.rb, docker/spec/dependabot/docker/file_parser_spec.rb, docker/spec/dependabot/docker/file_updater_spec.rb, docker/spec/dependabot/docker/update_checker_spec.rb
This reverts commit c3799f690f22f113dd5cef485d0f9b86653a15a1
We are noticing some errors coming up due to [this PR](https://github.com/dependabot/dependabot-core/pull/11977) , So we are reverting it.
=> Revert "Merge pull request #11977 from jpinz/docker-version-digest-fix"

go_modules/lib/dependabot/go_modules/package/package_details_fetcher.rb, go_modules/lib/dependabot/go_modules/update_checker.rb, go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb, go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb, go_modules/spec/dependabot/go_modules/update_checker_spec.rb
Part of adding cooldown options to go_modules
=> Adds cooldown options for go_modules

nuget/Dockerfile, nuget/helpers/lib/NuGetUpdater/global.json
Updating to the latest April releases.
=> update installed sdks to 8.0.408 and 9.0.203

docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb, docker_compose/spec/dependabot/docker_compose/file_updater_spec.rb
This reverts commit 882cc6dcf2d0e3b44a7cac3519dfb7bca638e622.
It is necessary as it was missed as part of #12086 , and `docker_compose` specs are currently failing on `main`.
=> Revert "Fix Docker Compose Specs Related to Requirements Digest with Sha256 (#12086)"

go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb, go_modules/spec/dependabot/go_modules/path_converter_spec.rb, go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
1. Fixes issue where release date fetch fails and throws an error.
2. Disables a test which was still running despite being skipped.
=> Adds exception handler for release dates fetch

helm/Dockerfile, helm/lib/dependabot/helm.rb, helm/lib/dependabot/helm/helpers.rb, helm/lib/dependabot/helm/package_manager.rb, helm/lib/dependabot/helm/update_checker.rb, helm/lib/dependabot/helm/version.rb, helm/spec/dependabot/helm/update_checker_spec.rb, helm/spec/dependabot/helm/version_spec.rb
Improve support for Helm OCI repositories without index.yaml files in Dependabot. Currently, we convert OCI URLs to HTTPS to look for index.yaml files, but this fails for OCI repos that don't provide them. This change leverages our existing ORAS integration to properly interact with the OCI Registry API, allowing us to find and update dependencies regardless of index.yaml availability
closes: https://github.com/dependabot/dependabot-core/issues/12126
This is more robust than the index.yaml approach since it works with all OCI repositories by communicating directly with the OCI Registry API
Note that with certain complex versioning schemes in OCI image names, we won't be able to differentiate between similar versions that use extended identifiers (e.g., between …
=> Improve support for OCI registries in Helm

nuget/helpers/lib/NuGetUpdater/Directory.Packages.props, nuget/helpers/lib/NuGetUpdater/DotNetPackageCorrelation.Test/DotNetPackageCorrelation.Test.csproj, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/NuGetUpdater.Cli.Test.csproj, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/NuGetUpdater.Core.Test.csproj, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/LoggerTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/PathHelperTests.cs
Upgrade to the latest major version of xunit
Followed https://xunit.net/docs/getting-started/v3/migration
This introduces a lot of new analyzer warnings, which are not addressed in this PR.
NuGet tests pass
=> Upgrade from `xunit` to `xunit.v3`

composer/.rubocop.yml, composer/lib/dependabot/composer/file_fetcher.rb, composer/lib/dependabot/composer/file_updater.rb, composer/lib/dependabot/composer/file_updater/lockfile_updater.rb, composer/lib/dependabot/composer/file_updater/manifest_updater.rb, composer/lib/dependabot/composer/metadata_finder.rb, composer/lib/dependabot/composer/version.rb
Complete strict Sorbet typing of `composer`
Tests pass
=> Strict type some more `composer`

composer/.rubocop.yml, composer/lib/dependabot/composer/update_checker.rb, composer/lib/dependabot/composer/update_checker/latest_version_finder.rb, composer/lib/dependabot/composer/update_checker/requirements_updater.rb, composer/lib/dependabot/composer/update_checker/version_resolver.rb
=> Complete strict typing `composer` ecosystem

cargo/.rubocop.yml, cargo/lib/dependabot/cargo/file_fetcher.rb, cargo/lib/dependabot/cargo/file_updater.rb, cargo/lib/dependabot/cargo/registry_fetcher.rb, cargo/lib/dependabot/cargo/requirement.rb
Complete strict Sorbet typing of `dependabot-core`
N/A
Tests pass
=> Strict type some of `cargo`

updater/lib/dependabot/api_client.rb, updater/lib/dependabot/service.rb, updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb, updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb, updater/lib/dependabot/updater/operations/update_all_versions.rb, updater/spec/dependabot/api_client_spec.rb, updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb, updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb, updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb, updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb, updater/spec/dependabot/updater/operations/refresh_version_update_pull_request_spec.rb, updater/spec/dependabot/updater/operations/update_all_versions_spec.rb, updater/spec/dependabot/updater_spec.rb
Related to sending cooldata metadata for metric collection
=> [Part of] [Cooldown] send cooldown meta to service request

.github/workflows/smoke.yml
Follow up to #12219 to reset the smoke test branch.
=> reset smoke test branch to `main`

gradle/lib/dependabot/gradle/package/package_details_fetcher.rb, gradle/lib/dependabot/gradle/update_checker/version_finder.rb, gradle/spec/dependabot/gradle/package/package_details_fetcher_spec.rb
Part of cooldown feature for gradle
Implements cooldown for gradle and fetches release dates info for use in cooldown feature
=> [cooldown] [gradle] Uses generic PackageDetailsFetcher

gradle/lib/dependabot/gradle/update_checker.rb, gradle/lib/dependabot/gradle/update_checker/version_finder.rb, gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb, gradle/spec/dependabot/gradle/update_checker_spec.rb
Part of adding cooldown to ecosystems, This PR adds cooldown options to Gradle ecosystem for release date filtering
=> [cooldown] [gradle] Adds cooldown options for Gradle ecosystem

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
Found during a manual scan of the logs.
=> expand pattern for unpossible updates

pub/lib/dependabot/pub/helpers.rb, pub/lib/dependabot/pub/package/package_details_fetcher.rb, pub/lib/dependabot/pub/update_checker.rb, pub/lib/dependabot/pub/update_checker/latest_version_finder.rb, pub/spec/dependabot/pub/package/package_details_fetcher_spec.rb, pub/spec/dependabot/pub/update_checker/latest_version_finder_spec.rb, pub/spec/dependabot/pub/update_checker_spec.rb
part of cooldown implementation and standardizing package metadata fetching.
1. Adds new module to standardize package metadata fetching.
2. refactors the latest version finder to separate to new file `latest_version_finder` .
3. adds cooldown option for version updates
=> Standardize pub package manager package fetcher and implements cooldown feature 

.github/workflows/ci.yml, .github/workflows/gems-bump-version.yml, .github/workflows/gems-release-to-rubygems.yml, .github/workflows/sorbet.yml
Split out #11681 into smaller, less risky, changes.
This version of `ruby/setup-ruby` includes support for the latest Ruby 3.4 release
=> Bump `ruby/setup-ruby` from `1.226.0` to `1.244.0`

swift/lib/dependabot/swift/package/package_details_fetcher.rb, swift/spec/dependabot/swift/package/package_details_fetcher_spec.rb
Truncate URl to fix cooldown issue under swift module.
=> Truncate URl to fix cooldown issue under swift.

bun/Dockerfile, npm_and_yarn/Dockerfile
https://github.com/nodejs/corepack/releases/tag/v0.33.0
=> Bump corepack to 0.33.0

common/lib/dependabot/package/package_release.rb, git_submodules/lib/dependabot/git_submodules/package/package_details_fetcher.rb, git_submodules/lib/dependabot/git_submodules/update_checker.rb, git_submodules/lib/dependabot/git_submodules/update_checker/latest_version_finder.rb, git_submodules/spec/dependabot/git_submodules/package/package_details_fetcher_spec.rb, git_submodules/spec/dependabot/git_submodules/update_checker/latest_version_finder_spec.rb
part of cooldown and refactoring work: 
Updates git submodule package fetcher to fetch metadata from git api.
Should be able to see package metadata in logs and no job fails
=> Adds package fetcher for git submodule

dotnet_sdk/lib/dependabot/dotnet_sdk/file_parser.rb
`JSON.parse` can throw `JSON::ParserError`, which was not caught prior to this change.
I also performed some cleanup and optimizations in `FileParser`
=> handle `JSON::ParserError` when `global.json` invalid

swift/lib/dependabot/swift/update_checker/latest_version_resolver.rb, swift/spec/dependabot/swift/update_checker/latest_version_resolver_spec.rb
Fixed issue related to pulling latest version in Swift. [Issue No](https://github.com/github/dependabot-updates/issues/8993)
To fix cooldown issue under Swift module.
=> Fixed issue related to pulling latest version in Swift.

python/Dockerfile, python/lib/dependabot/python/language.rb
Fix unsupported error for Python 3.12.10.
> updater | 2025/05/29 01:33:56 ERROR <job_1023675660> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '>=3.12.10, <3.13'.
> Currently, the following Python versions are supported in Dependabot: 3.9., 3.10., 3.11., 3.12., 3.13.*.
https://github.com/dependabot/dependabot-core/issues/12237
This PR updates each minor version to the latest patch version as of today for a workaround.
I know that the changes in this PR are very ad-hoc.
However, the following code comments are the justification.
https://github.com/dependabot/dependabot-core/blob/261436243d0fa5dc56e5010484ad6ba481dae098/python/lib/dependabot/python/language_version_manager.rb#L102
Sorry but I'm not familiar with the …
=> Fix Unsupported version error for latest Python.

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/SpecialFilePatcherTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SpecialImportsConditionPatcher.cs
We already have code to detect and maintain a file's byte order mark status, but project files are passed through an extra layer of patching to remove certain `<Import>` statements during the update process and this does not maintain the byte order mark.  The result is that the byte order mark was stripped from all project files before submitting to `create_pull_request`.  Non-project files are not affected by this because they don't get the extra condition patching.
The fix was to simply track and restore that in the condition patcher code.
=> maintain byte order mark during project file patching

python/lib/dependabot/python/package/package_details_fetcher.rb, python/spec/dependabot/python/package/package_details_fetcher_spec.rb
Related to [issue](https://github.com/github/dependabot-updates/issues/9701) where package fetching was failing due to dependency names with optional data. This PR fixes this so that data can be fetched successfully.
=> Fix issue with package details fetching while package with optional dependencies

bundler/lib/dependabot/bundler/package/package_details_fetcher.rb, bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
The existing cooldown implementation did not support private registries.
I’ve updated the source code to add support for private repositories.
This implementation assumes that private and public registries should be supported similarly, with the main difference being the need to pass appropriate credentials—such as host, username, and password—for private access.
I tested the updated CLI against the previously failing workflow and confirmed that it now correctly identifies the latest version as expected:
🔗 [Failing workflow](https://github.com/dsp-testing/bundler-private-registry-multidirectory-grouping-test/actions/runs/15562443403/job/43817970255)
Additionally, I verified through a local CLI run that it's successfully detecting the latest version and grouping the content as intended. …
=> Update cooldown implementation to support private registry

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackageReferenceUpdaterTests.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs, nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
When using the dependency solver, we analyze the initial package set and the resolved package set to determine what actually happened.
In the instance where no update could be performed on a transitive dependency, we mistakenly said that we _did_ perform an update because we found the parent package in the top-level dependencies.
What we needed was to add another check to see if that top-level dependency got assigned a newer version and it wasn't a wildcard.  Only then do we report the parent package update, otherwise nothing.
=> report no change if parent package didn't update

devcontainers/lib/dependabot/devcontainers/package/package_details_fetcher.rb, devcontainers/lib/dependabot/devcontainers/update_checker/latest_version_finder.rb, devcontainers/spec/dependabot/devcontainers/update_checker_spec.rb, devcontainers/spec/fixtures/projects/cooldown/package_metadata.json, devcontainers/spec/fixtures/projects/cooldown/token.json
This is part of implementing cooldown features for the Devcontainers ecosystem.
=> Implements cooldown for Devcontainers ecosystem

terraform/lib/dependabot/terraform/package/package_details_fetcher.rb, terraform/spec/dependabot/terraform/package/package_details_fetcher_spec.rb
To fix issue while parsing response from registry.
Issue while parsing module and provider
=> Terraform cooldown feature fix

NEW_ECOSYSTEMS.md
We are trying to encourage our community to contribute to the ecosystem by providing clear and concise documentation. This documentation will help new contributors understand the ecosystem and our expectations for contributions.
=> Creating new ecosystem documentation

python/lib/dependabot/python/language.rb, uv/Dockerfile, uv/lib/dependabot/uv/language.rb
Run dependabot of uv ecosystem with `3.11.12` in my pyproject.toml
AFAIK, there is never any reason for the python and uv python versions to be difference since they use the same base python docker container. Hopefully the additional comment will help going forward, even better would be a lint to ensure all three files, `Dockerfile`, `uv/language.rb`, `python/language.rb` match.
When specifying `3.11.12` in a pyproject.toml in a uv project and using the uv package ecosystem, dependabot completes instead of producing this error
```
+----------------------------------------------------------------------------------------------+
|                                            Errors                                            |
+----------------------------+--------------------------------------- …
```
=> Fix uv python versions to match python ecosystem

git_submodules/spec/dependabot/git_submodules/update_checker/latest_version_finder_spec.rb
Due to a Time component was not passed along with test cases, some test cases started failing incrementally, this PR fixes it.
=> Fixes failing git_submodules ecosystem cooldown test cases

hex/Dockerfile, hex/spec/dependabot/hex/file_parser_spec.rb
Updates the Hex package manager to version '2.2.1' as part of the ongoing package manager update epic.
link https://github.com/hexpm/hex/releases/tag/v2.2.1
=> Updates Hex package manager to version '2.2.1'

vcpkg/lib/dependabot/vcpkg.rb, vcpkg/lib/dependabot/vcpkg/file_parser.rb
Part of #7644 
Missed in #12491, but caught by smoke tests
=> Add missing `require` in `vcpkg`

npm_and_yarn/Dockerfile
As part of ecosystem latest version updates, we are updating Yarn to latest version 4.9.2
Smoke test fails are unrelated to this PR work
=> Upgrades Yarn to latest version 4.9.2

Rakefile
In order to unblock the weekly gem release we [skipped](https://github.com/dependabot/dependabot-core/pull/12603/commits/07c2ae2d44bc7373533d6bddc3736a18bdf84e5d) publishing the new gems `dependabot-rust_toolchain` and `dependabot-vcpkg`.
This PR is re-adding them so we can try signing them once more.
n/a
`dependabot-rust_toolchain` and `dependabot-vcpkg` will publish correctly with the next gem release.
=> Add rust_toolchain and vcpkg gemspecs to the GEMSPECS list

.github/workflows/codespell.yml
Fixes issue where codespell is scanning lock files for spelling errors
=> Adds lock files to actions-codespell ignore list

dotnet_sdk/lib/dependabot/dotnet_sdk/update_checker/latest_version_finder.rb
Removing feature flag for dotnet_sdk ecosystem
=> Cooldown feature flag removal for Dotnet SDK

cargo/lib/dependabot/cargo/helpers.rb
Sorbet type check added to the cargo helper class.
N/A
All CLI got passed
=> Sorbet type check added to cargo helper class.

python/helpers/requirements.txt, python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb, python/spec/dependabot/python/file_parser/setup_file_parser_spec.rb, python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb
As part of ecosystems upgrade, we are updating PIP to 25.0.1 
Fixes test cases as per upgrade.
=> Upgrade PIP to 25.0.1

uv/helpers/requirements.txt, uv/spec/dependabot/uv/file_parser_spec.rb
As per process to upgrade ecosystem versions, we are upgrading UV to version 0.7.20
https://pypi.org/project/uv/#history
=> UV update to version 0.7.20

rust_toolchain/lib/dependabot/rust_toolchain/update_checker/latest_version_finder.rb, vcpkg/lib/dependabot/vcpkg/update_checker/latest_version_finder.rb, vcpkg/spec/dependabot/vcpkg/update_checker/latest_version_finder_spec.rb
Now that the cooldown feature has been made generally available, these feature flags can be removed.
Tests pass
=> Remove cooldown feature flag for `vcpkg` and `rust_toolchain`

python/helpers/requirements.txt
We are receiving some concerns due to PIP>25 [malfunctioning](https://github.com/dependabot/dependabot-core/issues/12632) with dependabot . 
A [fix](https://github.com/jazzband/pip-tools/pull/2195) is already in place, however it is not available in latest release. We are downgrading PIP to 24.2 to mitigate new issues. We will upgrade once pip fix is released.
=> Downgrade pip to 24.2 due to issue in >25

.github/labeler.yml
The standard format for issue labels in this repository seems to be of the form `L: <language>:<tool>`. This changes a few labels to try and better match that form:
- `L: dotnet-sdk` becomes `L: dotnet:dotnet-sdk`
- This is to match the existing `L: dotnet:nuget`
- `L: rust-toolchain` becomes `L: rust:rust-toolchain`
- This is to match the existing `L: rust:cargo`
- `L: vcpkg` becomes `L: cpp:vcpkg`
- Where `cpp` is a common abbreviation for `C++` 
Once this is merged, I'll update the actual issue labels in this repository
=> Update labels for `dotnet-sdk`, `rust-toolchain`, and `vcpkg`

composer/Dockerfile
Updates the `composer/Dockerfile` to make the PHP version configurable via a build argument, improving flexibility and maintainability.
=> Use common variable for PHP version

silent/lib/dependabot/silent/metadata_finder.rb
Tests have been timing out, it seems they're hitting example.com and it has been slow lately. The tests aren't meant to make any network calls at all, not sure when that changed, but hopefully setting these values will fix it.
Integration tests will pass on the branch.
=> fix integration test timeouts

vcpkg/Dockerfile
To run certain VCPKG commands, VCPKG expects a complete checkout to be available. We previously only checked out a single commit to minimize the checkout size.
=> Complete checkout of vcpkg repository

uv/Dockerfile, uv/helpers/requirements.txt, uv/spec/dependabot/uv/file_parser_spec.rb
Just upgrading UV to the latest 0.8.0 - https://github.com/astral-sh/uv/releases/tag/0.8.0
=> Upgrade uv to the latest 0.8.0

python/Dockerfile, python/lib/dependabot/python/language.rb, uv/Dockerfile, uv/lib/dependabot/uv/language.rb
Fix the `tool_version_not_supported` error for Python 3.13.5 and other latest minor version releases.
```
updater | 2025/07/07 01:35:44 ERROR <job_<filtered>> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '>=3.13.5'.
Currently, the following Python versions are supported in Dependabot: 3.9.*, 3.10.*, 3.11.*, 3.12.*, 3.13.*.
proxy | 2025/07/07 01:35:44 [008] POST /update_jobs/<filtered>/record_update_job_error
proxy | 2025/07/07 01:35:44 [008] 204 /update_jobs/<filtered>/record_update_job_error
proxy | 2025/07/07 01:35:44 [010] PATCH /update_jobs/<filtered>/mark_as_processed
proxy | 2025/07/07 01:35:44 [010] 204 /update_jobs/<filtered>/mark_as_processed
updater | 2025/07/07 01:35:44 INFO <job_<filtered>> Finished job processing …
```
=> Target latest Python versions

composer/lib/dependabot/composer/update_checker/version_resolver.rb, composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb, composer/spec/fixtures/projects/check_original_requirements_resolvable/composer.json
This provided a fix for the following Sentry error in Composer package manager.
```
Return value: Expected type String, got type NilClass
```
[Sentry link](https://github.sentry.io/issues/6657632404/?project=1451818&query=is%3Aunresolved%20stack.filename%3Acomposer%2Flib%2Fdependabot%2Fcomposer%2Fupdate_checker%2Fversion_resolver.rb&referrer=issue-stream) for the issue.
=> Fix Sorbet Runtime Error due to Nil return value in Composer ecosystem

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/FileWriters/XmlFileWriter.cs
When computing the line number from a node's offset, manually walk the syntax tree.  This removes a bunch of unnecessary string allocations.
=> use trivia to compute newline offset locations

uv/Dockerfile, uv/helpers/requirements.txt, uv/spec/dependabot/uv/file_parser_spec.rb
uv 0.8.3 includes the ability to [target Python 3.14.0rc1](https://github.com/astral-sh/uv/releases/tag/0.8.3).
This PR is basically the same as #12674
=> Upgrade uv to the latest 0.8.4

NEW_ECOSYSTEMS.md
Adding `Rakefile` to support new ecosystem documentation
=> Adding `Rakefile` to omnibus section

cargo/lib/dependabot/cargo/file_parser.rb, cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
Adding sorbet types to cargo `file_parser.rb` in order to unblock @rvagg pr: https://github.com/dependabot/dependabot-core/pull/12780
- File parser will have sorbet types
- We will raise no additional errors due to typing
- Tests will pass without the need of modification
=> Adding sorbet typing for cargo file parser

terraform/lib/dependabot/terraform/update_checker.rb, terraform/lib/dependabot/terraform/update_checker/latest_version_resolver.rb
Since terraform does not support semver version so removed check for that. Additionally added check to restrict cooldown related code scan by adding flag. If user does not add cooldown option in dependabot.yml then it will not run cooldown and it will save overall scan time.
All specs should pass.
=> Terraform Cooldown related Code Cleanup and added Flag to Restrict Cooldown Scan if not requested.

.github/issue-labeler.yml
=> Add `dotnet-sdk`, `vcpkg`, and `rust-toolchain` to issue labeler

swift/lib/dependabot/swift/update_checker/latest_version_resolver.rb, swift/spec/dependabot/swift/update_checker/latest_version_resolver_spec.rb
Current logic is to find the max cooldown period and based on that filter the versions, new logic or fix is to give priority to the semver major then semver minor then semver patch then default.
Additionally added check to not to execute cooldown related code if user does not want to. This will save scan time.
One of the issue mentioned in this [ticket](https://github.com/github/dependabot-updates/issues/10415).
All existing tests should pass.
=> Fixed issue related to calculate cooldown period by providing semver major version as highest priority.

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
[Earlier logs accessing public registry](https://github.com/dsp-testing/npm-private-registry-issue-dw-v1/actions/runs/16942568062/job/48015251367)
```
updater | 2025/08/13 15:57:35 INFO <job_1074894042> Started process PID: 1477 with command: {} corepack npm install lodash@4.17.2 --package-lock-only --dry-run\=true --ignore-scripts {}
proxy | 2025/08/13 15:57:35 [021] GET [https://registry.npmjs.org:443/lodash](https://registry.npmjs.org/lodash)
proxy | 2025/08/13 15:57:35 [021] 200 [https://registry.npmjs.org:443/lodash](https://registry.npmjs.org/lodash)
```
After this fix (What ever the registry marked as `replaces-base:true`)
```
updater | 2025/08/18 15:44:06 INFO Started process PID: 1257 with command: {"npm_config_registry" => …
```
=> Adding registry env variable to corepack command.

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/EndToEndTests.cs
This is a supported high-level scenario that was only verified through unit tests.  Adding and end-to-end test to ensure the scenario is covered.
=> add end-to-end test for updating json files

docker/Dockerfile
https://github.com/regclient/regclient/releases/tag/v0.9.1
=> Bump regclient to 0.9.1

Rakefile
Add a more helpful error message to the `tag <tag> does not exist` error we sometimes see when releasing Gems 
Tried to add it somewhere helpful
We know what to do next time we run into this error
N/A
=> More descriptive error message for `tag <tag> does not exist`

vcpkg/Dockerfile, vcpkg/lib/dependabot/vcpkg/file_parser.rb, vcpkg/lib/dependabot/vcpkg/file_updater.rb, vcpkg/lib/dependabot/vcpkg/package/package_details_fetcher.rb, vcpkg/lib/dependabot/vcpkg/update_checker.rb, vcpkg/lib/dependabot/vcpkg/update_checker/latest_version_finder.rb, vcpkg/lib/dependabot/vcpkg/version.rb, vcpkg/spec/dependabot/vcpkg/file_parser_spec.rb, vcpkg/spec/dependabot/vcpkg/file_updater_spec.rb, vcpkg/spec/dependabot/vcpkg/package/package_details_fetcher_spec.rb, vcpkg/spec/dependabot/vcpkg/update_checker/latest_version_finder_spec.rb, vcpkg/spec/dependabot/vcpkg/update_checker_spec.rb
Add support for updating `vcpkg` version constraints. See #12871
=> Add support for `vcpkg` dependency constraints

.github/workflows/scorecards.yaml
This workflow does not add value in the context of forks and it just increases the runner usage
=> Do not run Scorecard analysis from forks

Dockerfile.updater-core
Improve the build speed using the Azure mirrors for Ubuntu
I noticed various build failures due to the default's mirror flakiness while working on #13022 both locally and in the CI environment
Example failure: 
> #12 129.5   Connection failed [IP: 185.125.190.83 80]
> #12 130.2 Ign:20 http://security.ubuntu.com/ubuntu noble-security InRelease
> #12 130.4 Err:21 http://archive.ubuntu.com/ubuntu noble-updates InRelease
> #12 130.4   Could not connect to archive.ubuntu.com:80 (91.189.91.81), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.83), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.82), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.83), connection timed out Could not connect to archive.ubuntu.com:80 …
=> Prefer Azure mirror for Ubuntu

bun/.rubocop.yml, bun/lib/dependabot/bun/file_updater.rb, bun/lib/dependabot/bun/file_updater/bun_lockfile_updater.rb, bun/lib/dependabot/bun/file_updater/package_json_preparer.rb, bun/lib/dependabot/bun/native_helpers.rb, bun/lib/dependabot/bun/requirement.rb, bun/lib/dependabot/bun/update_checker/conflicting_dependency_resolver.rb, bun/lib/dependabot/bun/update_checker/dependency_files_builder.rb, bun/lib/dependabot/bun/update_checker/library_detector.rb, bun/lib/dependabot/bun/update_checker/requirements_updater.rb, bun/lib/dependabot/bun/update_checker/subdependency_version_resolver.rb, bun/lib/dependabot/bun/update_checker/vulnerability_auditor.rb, bun/spec/dependabot/bun/file_updater_spec.rb, bun/spec/dependabot/bun/update_checker/package_latest_version_finder_spec.rb, bun/spec/spec_helper.rb
=> Finish Sorbet strict types in `bun`

CONTRIBUTING.md
Adding link to new ecosystems in the contribution guide
=> Link to new ecosystems guide in CONTRIBUTING.md

.rubocop.yml, bun/.rubocop.yml, common/.rubocop.yml, composer/.rubocop.yml, git_submodules/.rubocop.yml, go_modules/.rubocop.yml, npm_and_yarn/.rubocop.yml, pub/.rubocop.yml, python/.rubocop.yml, updater/.rubocop.yml, uv/.rubocop.yml
`T.Unsafe` is an [escape hatch][1] from Sorbet's type system.
[1]: https://sorbet.org/docs/troubleshooting#tunsafe
=> Enable `Sorbet/ForbidTUnsafe` cop from `rubocop-sorbet`

bundler/.rubocop.yml, bundler/lib/dependabot/bundler/file_updater.rb, bundler/lib/dependabot/bundler/file_updater/git_pin_replacer.rb, bundler/lib/dependabot/bundler/file_updater/git_source_remover.rb, bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb, bundler/lib/dependabot/bundler/file_updater/requirement_replacer.rb, bundler/lib/dependabot/bundler/metadata_finder.rb, bundler/lib/dependabot/bundler/requirement.rb, bundler/lib/dependabot/bundler/update_checker.rb, bundler/lib/dependabot/bundler/update_checker/file_preparer.rb, bundler/lib/dependabot/bundler/update_checker/force_updater.rb, bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb, bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb, bundler/spec/dependabot/bundler/update_checker/latest_version_finder/dependency_source_spec.rb
=> Complete Sorbet strict typing of `bundler`

.rubocop.yml
This simplifies our `.rubocop.yml` configuration by:
- Removing explicitly enabled cops that are enabled or pending by default
- Removing explicitly disabled cops that are disabled by default
- Removing explicitly disabled cops which do not result in warnings
=> Simplify Rubocop configuration

npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb
```
Parameter 'details': Expected type T.nilable(T.any(String, T::Hash[String, T.untyped])), got type Array with value [{"type" => "git", "url" =>...thub.com/Ranks/emojione.git"}]
Caller: /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb:95
Definition: /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb:119 (Dependabot::NpmAndYarn::MetadataFinder#get_source)
```
=> Fix Sorbet error in NpmAndYarn::MetadataFinder

NEW_ECOSYSTEMS.md
Closes https://github.com/github/dependabot-updates/issues/10268
Improve the available documentation for adding new ecosystems.
The additions are mainly around local dry-run testing.
A new contributor can understand and run local dry run test without confusion 😄
=> local dryrun testing instructions

.git-blame-ignore-revs, .rubocop.yml, bun/lib/dependabot/bun/update_checker/version_resolver.rb, common/spec/dependabot/pull_request_updater/github_spec.rb, github_actions/lib/dependabot/github_actions/requirement.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_workspace_updater.rb, npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb, npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb, pub/lib/dependabot/pub/update_checker.rb, python/lib/dependabot/python/update_checker/poetry_version_resolver.rb, python/spec/dependabot/python/authed_url_builder_spec.rb, updater/spec/dependabot/sentry/exception_sanitizer_processor_spec.rb, uv/spec/dependabot/uv/authed_url_builder_spec.rb
See https://docs.rubocop.org/rubocop/cops_layout.html#layoutspacearoundmethodcalloperator
=> Enable Layout/SpaceAroundMethodCallOperator

.git-blame-ignore-revs, .rubocop.yml, common/lib/dependabot/clients/codecommit.rb, common/lib/dependabot/pull_request_creator/codecommit.rb, helm/lib/dependabot/helm/package/package_details_fetcher.rb, pub/lib/dependabot/pub/update_checker/latest_version_finder.rb, python/lib/dependabot/python/package/package_details_fetcher.rb, uv/lib/dependabot/uv/package/package_details_fetcher.rb
https://docs.rubocop.org/rubocop/cops_layout.html#layoutrescueensurealignment
=> Enable RuboCop Layout/RescueEnsureAlignment

.github/dependabot.yml, docker/Dockerfile
* Reduces the manual effort required to upgrade the version of regctl
* Validates the binary using the cosign method recommended by the regctl team
Once this is merged, manual updates like #12937 should no longer be necessary as we'll delegate the work to Dependabot
Demo: https://github.com/yeikel/dependabot-core/pull/87
=> Automate regclient version upgrades

Gemfile.lock, maven/dependabot-maven.gemspec, updater/Gemfile.lock
A new reference to this dependency was added, but we were just relying on upstream gems (updater) including it.  This prevented this gem from being used standalone.
=> Add explicit dependency for maven on rexml
