dependabot/dependabot-core

lib/dependabot/file_fetchers/python/pip.rb
lib/dependabot/file_parsers/python/pip.rb
lib/dependabot/file_updaters/python/pip.rb
spec/dependabot/file_fetchers/python/pip_spec.rb
spec/dependabot/file_parsers/python/pip_spec.rb
spec/dependabot/file_updaters/python/pip_spec.rb
spec/fixtures/github/requirements_with_cascade.json
spec/fixtures/python/requirements/cascading.txt

Support for cascading requirement files in Python. See [heroku's advice](https://devcenter.heroku.com/articles/python-pip#cascading-requirements-files) on them, for example.
With this added, I'm happy to move Python to beta (from alpha).

Cascading python requirements

---

lib/dependabot/errors.rb
lib/dependabot/update_checkers/ruby/bundler.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb

That. If a private source tells us we aren't authenticated, there's not much we can do except serve the error back to the user.
Example Gemfile this came from is:
```
source 'https://gems.graphql.pro/' do
gem 'graphql-pro'
end
```

Raise helpful message for Ruby private sources without auth details

---

lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/update_checkers/ruby/bundler.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb
spec/fixtures/ruby/gemspecs/with_require

A little hacky, but this will considerably improve our support for path-based Ruby dependencies.

Sanitize path-based gemspecs to remove fine requirements

---

lib/bundler_git_source_patch.rb
lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/update_checkers/ruby/bundler.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb
spec/fixtures/ruby/gemfiles/private_git_source
spec/fixtures/ruby/lockfiles/private_git_source.lock

Fixes a `Gemfile.lock` reordering bug.
Frustratingly, this is extremely hard to spec - ideally we want to have an actual private repo on GitHub, and a corresponding access token stored in the spec suite, but that just not going to happen.

Patch Bundler to use HTTPS instead of SSH for git sources hosted on GitHub

---

lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/update_checkers/ruby/bundler/requirements_updater.rb
spec/dependabot/file_parsers/ruby/bundler_spec.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler/requirements_updater_spec.rb
spec/fixtures/ruby/gemfiles/version_between_bounds

Previously, Dependabot was ignoring Ruby dependencies whose requirement had multiple components (e.g., `gem "business", "~> 1.0", ">= 1.0.3"`).
This PR updates the Ruby parsing, update checking and file-updating code to fix that. 🎉

Handle Ruby Gemfile requirements with multiple components

---

lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/shared_helpers.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/shared_helpers_spec.rb

When the Bundler root is not set to the working directory, it attempts to
add the fully expanded path to the `Gemfile` for gems that are path based.
This resulted in an erroneous path being added to the updated `Gemfile.lock`
due to the temporary working directory not being on the original
repository.
That means that if my gem had a path of:
```YAML
PATH
remote: path/to/my_library
```
it would output:
```YAML
PATH
remote: tmp/dependabot_20170907-3-5asdast/path/to/my_library
```

Manually set Bundler root

---

helpers/php/src/Updater.php
lib/dependabot/file_parsers/php/composer.rb
spec/dependabot/file_parsers/php/composer_spec.rb
spec/dependabot/file_updaters/php/composer_spec.rb

Previously we were ignoring development dependencies for PHP. Including them needs a change to the parser and to the file updater.

[WIP] Include development dependencies in FileParsers::Php::Composer

---

lib/dependabot/file_parsers/python/pip.rb

It's more specific, and dependabot-core doesn't work with python2.

Use python3.6 rather than python

---

lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/pull_request_creator.rb
lib/dependabot/update_checkers/base.rb
lib/dependabot/update_checkers/git/submodules.rb
spec/dependabot/file_parsers/ruby/bundler_spec.rb
spec/dependabot/pull_request_creator_spec.rb
spec/dependabot/update_checkers/git/submodules_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb

- Get SHA-1 hash as version for Ruby git dependencies
- Update `UpdateCheckers::Base` and `PullRequestCreator` to handle SHA-1 versions (and remove the special-casing we were previously using for Git submodule versions).
Lays the foundation for the Ruby update checker to update git dependencies to the latest commit. Currently, this won't cause any additional updates, since the `UpdaterCheckers::Ruby::Bundler` class will always return `nil` for the updated version of Ruby git dependencies.

Get SHA-1 hash as version for Ruby git dependencies

---

helpers/python/lib/parser.py

Paths with spaces work properly now, and using `os.path.relpath` is preferred over using `re.sub` for reletavising the path.

Improve how we extract filenames in the Python parser

---

.rubocop.yml
dependabot-core.gemspec
lib/dependabot/update_checkers/ruby/bundler/file_preparer.rb
spec/dependabot/update_checkers/ruby/bundler/file_preparer_spec.rb

We'll need to use an AST parser when we start doing clever mandate file manipulation (e.g., in https://github.com/dependabot/dependabot-core/pull/84). Let's introduce it now, gradually.

Switch to AST parser for updating Ruby requirements in UpdateChecker

---

lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/file_parsers/ruby/bundler/dependency_set.rb
lib/dependabot/file_parsers/ruby/bundler/file_preparer.rb
lib/dependabot/file_parsers/ruby/bundler/gemfile_checker.rb
spec/dependabot/file_parsers/ruby/bundler/dependency_set_spec.rb

Ruby FileParser was becoming a big class, and difficult to test. This PR splits out the logic for file preparation, dependency set concatenation, and checking whether a declaration occurs in a given Gemfile.

Split Ruby FileParser logic out into smaller classes

---

lib/dependabot/file_fetchers/ruby/bundler.rb
lib/dependabot/file_fetchers/ruby/bundler/child_gemfile_finder.rb
lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/file_parsers/ruby/bundler/file_preparer.rb
lib/dependabot/file_parsers/ruby/bundler/gemfile_checker.rb
lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/update_checkers/ruby/bundler/file_preparer.rb
lib/dependabot/update_checkers/ruby/bundler/requirements_updater.rb
spec/dependabot/file_fetchers/ruby/bundler/child_gemfile_finder_spec.rb
spec/dependabot/file_fetchers/ruby/bundler_spec.rb
spec/dependabot/file_parsers/ruby/bundler_spec.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler/file_preparer_spec.rb
spec/dependabot/update_checkers/ruby/bundler/requirements_updater_spec.rb
spec/fixtures/github/gemfile_with_circular.json
spec/fixtures/github/gemfile_with_eval_content.json
spec/fixtures/ruby/gemfiles/eval_gemfile
spec/fixtures/ruby/gemfiles/only_statesman

Adds support for Ruby gemfiles that use `eval_gemfile`. Relatively uncommon, but the equivalent in Python (`-r some/requirements.txt`) is widely used, so applying the same logic for other languages seems sensible.
Closes https://github.com/dependabot/feedback/issues/18.
**TODO**

[WIP] Add support for `eval_gemfile` in Ruby gemfiles

---

dependabot-core.gemspec
lib/dependabot/metadata_finders/ruby/bundler.rb
lib/dependabot/update_checkers/ruby/bundler/version_resolver.rb

The `gems` gem is unmaintained, and doesn't make automatically retrying requests easy. We only use it for a couple of simple idempotent requests anyway, so can just swap it out for `excon`.
Using `excon`'s idempotent argument means timeouts will automatically be retried, making our use of the Rubygems API more robust. 🎉

Remove Gems dependency (replace with Excon calls)

---

lib/dependabot/file_parsers/docker/docker.rb
lib/dependabot/file_updaters/docker/docker.rb
lib/dependabot/update_checkers/docker/docker.rb
spec/dependabot/file_parsers/docker/docker_spec.rb
spec/dependabot/file_updaters/docker/docker_spec.rb
spec/dependabot/update_checkers/docker/docker_spec.rb
spec/fixtures/docker/dockerfiles/private_tag

If details for a private Docker registry are provided as a credential, there's no reason we shouldn't be able to bump the version of the base image in the Dockerfile.

Private docker registries

---

circle.yml

That. We run Node 8 in the updater, so should be testing against it.

Test against latest version of node

---

.editorconfig

The valid option for `indent_style` is `space` not `spaces` per the [documentation](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style) :-)

EditorConfig should use 'space' not 'spaces'

---

helpers/python/lib/parser.py
spec/dependabot/file_parsers/python/pip_spec.rb
spec/fixtures/python/setup_files/setup.py

This pull-requests intends to add support to the standard
`setup_requires` and `extras_require` sections in setup.py.
`setup_requires` allows one to declare packages required at installation
time wheras `extras_require` is to declare additional dependencies when
an optional feature is activated, for instance: `pip install foo[API]`

python: extract dependencies from `setup_requires` and `extras_require`

---

helpers/npm/test/fixtures/updater/original/package.json
helpers/npm/test/fixtures/updater/updated/package.json
helpers/yarn/lib/updater.js

We're seeing quite a lot of these errors now, since Dependabot currently run Node 8. Ignoring the node engine specification of packages is *probably* the right thing to do here (and would mean errors show up for our integrators in CI, rather than hidden away here.

Ignore node manifest engine constraints

---

lib/dependabot/file_updaters/java_script/base.rb
lib/dependabot/metadata_finders/java_script/yarn.rb
lib/dependabot/update_checkers/java_script/yarn.rb
spec/dependabot/metadata_finders/java_script/yarn_spec.rb
spec/dependabot/update_checkers/java_script/yarn_spec.rb

That. Uses npm credentials passed to it.
The solution here is temporary - we'll want to accept a users's `.npmrc` at some point in the future so we support registries other than `registry.npmjs.org`. We can cross that bridge when we come to it, though - no reason not to get private packages working in the meantime.

JS: Add basic support for private npm packages

---

helpers/npm/lib/updater.js
helpers/npm/test/fixtures/updater/original/package.json
helpers/npm/test/fixtures/updater/updated/package.json
helpers/npm/test/updater.test.js
helpers/yarn/lib/updater.js
helpers/yarn/test/fixtures/updater/original/package.json
helpers/yarn/test/fixtures/updater/updated/package.json
helpers/yarn/test/fixtures/updater/with-version-comments/package.json
helpers/yarn/test/updater.test.js
lib/dependabot/file_updaters/base.rb
lib/dependabot/file_updaters/java_script/base.rb
lib/dependabot/file_updaters/ruby/bundler.rb
spec/dependabot/file_updaters/java_script/npm_spec.rb
spec/dependabot/file_updaters/java_script/yarn_spec.rb
spec/dependabot/update_checkers/java_script/yarn_spec.rb
spec/fixtures/javascript/package_files/non_standard_whitespace.json

Previously we were updating the `package.json` file by calling `yarn add` or by manually altering it in the npm `updater.js` file.
There's no need not to do this update in Ruby, and doing so will speed things up if/when we allow JS repos without a lockfile. It also makes it easier to debug, and to use regexes to do the update (and therefore preserve file formatting).

Perform package.json update in Ruby (and avoid changing package.json format)

---

helpers/npm/package.json
helpers/npm/yarn.lock

That.
Looks like there are a lot of changes in there, and that we might be able to piggy-back off of the new `--package-lock-only` option.
Release blog post: http://blog.npmjs.org/post/167963735925/v560-2017-11-27

Bump npm to 5.6.0

---

helpers/php/src/UpdateChecker.php
helpers/php/src/Updater.php
lib/dependabot/update_checkers/php/composer.rb
spec/dependabot/file_updaters/php/composer_spec.rb
spec/dependabot/update_checkers/php/composer_spec.rb
spec/fixtures/php/composer_files/old_php_specified
spec/fixtures/php/lockfiles/old_php_specified

Fixes #156.
This might cause us to create updates we shouldn't (i.e., ones that require a higher PHP version than the `composer.json` specifies. We can fix that if/when it occurs, though - it's a better problem to have than not creating updates at all if our PHP install is missing *any* PHP extensions.

PHP: Don't check platform requirements during updates

---

.gitignore
circle.yml
helpers/php/.php_cs
helpers/php/bin/run.php
helpers/php/composer.json
helpers/php/composer.lock
helpers/php/src/DependabotInstallationManager.php
helpers/php/src/UpdateChecker.php
helpers/php/src/Updater.php

This does the following:
* Uses php-cs-fixer to automatically fix / verify style issues
* Keeps with the 1 class per file for PSR-4.
* Uses composer autoloading in run.php instead of the update classes themselves.
* Moves the setting of the timezone to run.php so it is centralized
* Uses PSR-2 & additional style standards including renaming the snake_case method to camelCase
The only thing that isn't done here is to introduce tests. That would be another great thing to add in which I can look into.
Not sure if this PR is wanted or not, but I didn't spend a lot of time on it anyways.

Refactored and cleaned up PHP code

---

lib/dependabot/file_parsers/java/maven.rb
lib/dependabot/file_updaters/java/maven.rb
spec/dependabot/file_parsers/java/maven_spec.rb
spec/dependabot/file_updaters/java/maven_spec.rb
spec/fixtures/java/poms/pom_with_parent.xml

This add support for projects that inherit from a parent POM. These POMs can manage dependencies, plugins etc. Often used for getting started with Spring Boot projects, e.g. [here in the docs](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-first-application.html#getting-started-first-application-pom) or in the official [getting started tutorial](https://spring.io/guides/gs/spring-boot/).
A [project of mine](https://github.com/evenh/coffeebot/blob/master/pom.xml) uses this technique.

Java: Add support for projects that inherit from parent POM

---

helpers/elixir/bin/check_update.exs
helpers/elixir/bin/parse_deps.exs
helpers/elixir/bin/run.exs
lib/dependabot/update_checkers/elixir/hex.rb
spec/dependabot/file_parsers/elixir/hex_spec.rb
spec/dependabot/update_checkers/elixir/hex_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb
spec/fixtures/elixir/mixfiles/bad_spec

This needs a change to our Elixir code so that it bubbles errors up to Ruby.
This can likely be done by using:
- The [arguments to System](https://hexdocs.pm/elixir/System.html#cmd/3)
- A conditional in `run.exs` to return an `"error"` (just needs to have the text of the error) to Ruby if the exit code of the command was non-zero

Add (failing) spec for Elixir update checking with a bad version requirement

---

helpers/elixir/bin/do_update.exs

Replaced the call to the Erlang `:file` module by a call to the Elixir `File` module. Also used pipes to make the code a bit cleaner.

Use Elixir standard library instead of Erlang

---

lib/dependabot/pull_request_creator/message_builder.rb
spec/dependabot/pull_request_creator_spec.rb

Angular changed their semantic commit message prefixes in January 2017 ([PR](https://github.com/angular/angular/pull/13991)). This PR updates Dependabot to use the relevant new prefix (`build`).

Use `build` prefix if semantic commits are in use

---

helpers/python/lib/pipfile_updater.py
lib/dependabot/file_updaters/python/pipfile.rb
spec/dependabot/file_updaters/python/pipfile_spec.rb

Python: Use Pipenv's new --keep-outdated option instead of freezing Pipfile

---

helpers/elixir/bin/check_update.exs
lib/dependabot/update_checkers/elixir/hex.rb
spec/dependabot/file_updaters/elixir/hex_spec.rb
spec/dependabot/update_checkers/elixir/hex_spec.rb
spec/fixtures/elixir/lockfiles/git_source_no_tag
spec/fixtures/elixir/lockfiles/git_source_no_tag_blocked
spec/fixtures/elixir/mixfiles/git_source_no_tag
spec/fixtures/elixir/mixfiles/git_source_no_tag_blocked

First cut of support for git-based dependencies in Elixir. This will allow Dependabot to keep dependencies that point at a branch up-to-date.

Elixir: Add support for git-source dependencies

---

lib/dependabot/file_fetchers/ruby/bundler.rb
lib/dependabot/file_fetchers/ruby/bundler/path_gemspec_finder.rb
spec/dependabot/file_fetchers/ruby/bundler/path_gemspec_finder_spec.rb
spec/dependabot/file_fetchers/ruby/bundler_spec.rb
spec/fixtures/github/contents_ruby_nested_path_directory.json
spec/fixtures/github/contents_ruby_path_directory.json

Handle path dependencies when the `gemspec` is in a nested one level deep. For example, `gem 'my_gem', path: 'vendored_gems'` with the gemspec at `vendored_gems/my_gem/my_gem.gemspec`.
TODO: Add a spec for this case.

Handle nested Ruby path dependencies

---

lib/dependabot/utils/java/requirement.rb
lib/dependabot/utils/java/version.rb
spec/dependabot/update_checkers/java/maven/version_finder_spec.rb
spec/dependabot/update_checkers/java/maven_spec.rb
spec/dependabot/utils/java/requirement_spec.rb
spec/dependabot/utils/java/version_spec.rb
spec/fixtures/java/maven_central_metadata/with_release.xml

Java's implementation of version comparison is a little different to other languages. This PR implements it in full, and will ensure we don't accidentally downgrade versions.

Implement Java version comparison

---

lib/dependabot/file_fetchers/java/maven.rb
lib/dependabot/file_parsers/java/maven.rb
lib/dependabot/file_parsers/java/maven/property_value_finder.rb
lib/dependabot/file_parsers/java/maven/repositories_finder.rb
lib/dependabot/file_updaters/java/maven.rb
lib/dependabot/update_checkers/java/maven.rb
spec/dependabot/file_fetchers/java/maven_spec.rb
spec/dependabot/file_parsers/java/maven_spec.rb
spec/dependabot/update_checkers/java/maven_spec.rb

Work in progress. Idea is to always download a POM's parents, if they're stored in the same repo, so that we can always do property resolution.
TODO:

Java: Preemptively download parent POMs, when present, to allow property evaluation

---

.circleci/config.yml
.gitignore
Dockerfile
helpers/python/lib/pipfile_updater.py
helpers/python/requirements.txt
lib/dependabot/file_parsers/python/pip.rb
lib/dependabot/file_updaters/python/pip.rb
lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb

The idea here is to piggy-back off of pipenv's automatic use of pyenv to install the right Python version. The install typically takes < 3 minutes, and will only happen once per update run, and only if the user specifies a Python version that we don't have (currently we only have 3.6.5).
More details in https://github.com/skylines-project/skylines/pull/734.

Use pyenv to manage Python version

---

lib/dependabot/file_updaters/rust/cargo.rb
lib/dependabot/update_checkers/rust/cargo.rb
lib/dependabot/update_checkers/rust/cargo/requirements_updater.rb
spec/dependabot/file_updaters/rust/cargo_spec.rb
spec/dependabot/update_checkers/rust/cargo/requirements_updater_spec.rb
spec/dependabot/update_checkers/rust/cargo_spec.rb

If a Rust dependency is specified with a git source and a tag, and the tag looks like a version, check whether there is a later tag we can update to.

Update git tags for Rust dependencies

---

helpers/php/bin/run.php
helpers/php/src/Hasher.php
lib/dependabot/file_updaters/php/composer.rb
lib/dependabot/update_checkers/java_script/npm_and_yarn/version_resolver.rb
lib/dependabot/update_checkers/php/composer.rb
lib/dependabot/update_checkers/php/composer/version_resolver.rb
lib/dependabot/update_checkers/python/pip/pip_compile_version_resolver.rb
lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb
lib/dependabot/update_checkers/ruby/bundler/version_resolver.rb
spec/dependabot/file_updaters/php/composer_spec.rb
spec/dependabot/update_checkers/php/composer/version_resolver_spec.rb
spec/dependabot/update_checkers/php/composer_spec.rb
spec/fixtures/php/lockfiles/subdependency_update_required
spec/fixtures/php/packagist_responses/dependabot:dummy-pkg-a.json
spec/fixtures/php/packagist_responses/doctrine:dbal.json
spec/fixtures/php/packagist_responses/longman:telegram-bot.json
spec/fixtures/php/packagist_responses/monolog:monolog.json
spec/fixtures/php/packagist_responses/neos:flow.json
spec/fixtures/php/packagist_responses/path_dep:path_dep.json
spec/fixtures/php/packagist_responses/pear-pear.horde.org:horde_date.json
spec/fixtures/php/packagist_responses/phpdocumentor:reflection-docblock.json
spec/fixtures/php/packagist_responses/symfony:polyfill-mbstring.json
spec/fixtures/php/packagist_responses/wpackagist-plugin:acf-to-rest-api.json
spec/fixtures/php/wpackagist_response.json

Previously, the PHP UpdateChecker knew nothing about versions the user had chosen to ignore. It always suggested updating to the latest resolvable version, and a separate process (in the Dependabot webapp) would ignore the generated update if the user had asked it to ignore that range.
This PR makes the PHP UpdateChecker aware of ignored versions. It will now only generate an update if one is possible that isn't being ignored, and will consider those ignores when determining the latest resolvable version that the user might want. As a result, if you're ignoring v2 of a dependency, Dependabot will still be able to generate updates for you if they're available on the v1 branch.
The same functionality is already being used in our Java and Python updaters, and is working well.

Consider ignored versions when generating PHP update PRs

---

helpers/php/src/ExceptionIO.php
helpers/php/src/UpdateChecker.php
helpers/php/src/Updater.php
lib/dependabot/update_checkers/php/composer/version_resolver.rb
spec/dependabot/file_updaters/php/composer_spec.rb
spec/dependabot/update_checkers/php/composer_spec.rb
spec/fixtures/php/composer_files/bad_php
spec/fixtures/php/composer_files/missing_extension
spec/fixtures/php/composer_files/old_php_platform
spec/fixtures/php/lockfiles/old_php_platform

Fixes #394
When a user sets the platform requirements we should respect them. Else
proposed new versions might not run on their target platform.
If no platform is set we ignore it all so that the current platform
isn't taken into account.
Todo:
* Just took them from https://github.com/dependabot/dependabot-core/pull/209

Respect platform requirements if they are set

---

lib/dependabot/update_checkers/rust/cargo.rb
lib/dependabot/update_checkers/rust/cargo/file_preparer.rb
spec/dependabot/update_checkers/rust/cargo/file_preparer_spec.rb
spec/dependabot/update_checkers/rust/cargo_spec.rb
spec/fixtures/rust/crates_io_responses/regex.json

Improve Rust support for ignored major versions (as described in [this blog post](https://dependabot.com/blog/updating-older-versions)).
TODO:

Improve Rust support for ignored major versions

---

lib/dependabot/file_fetchers/base.rb
lib/dependabot/pull_request_creator/gitlab.rb
lib/dependabot/pull_request_creator/message_builder.rb

Hello @greysteil,
As we already discussed, we are very interested by your project. 
But we use gitlab selfhosted, so we were waiting for the implementation of gitlab.
I discovered your project dependabot\dependabot-script and we tried to use it. 
We got a lot of snafu but we got it at the end. 
But to be able to make it work, we add to make some little changes. Here they are. Maybe it can be of some help.
You will maybe see that we didn't leave from master. There is a very good reason for that ! :smile: 
We working on php/composer projects and we add a fatal yesterday due to this very recent commit on master : https://github.com/dependabot/dependabot-core/commit/319b92a99ecb0ff94a73dc1598b35a6bf3577215
Since we are on gitlab, we got no username to use for these credentials.
Maybe we can …

Use source api endpoint in gitlab client for using self host gitlab

---

lib/dependabot/pull_request_creator/message_builder.rb
spec/dependabot/pull_request_creator/message_builder_spec.rb

Implements the fix in https://github.com/dependabot/dependabot-core/issues/560, by changing the semantic-release commit message scope for development dependencies from `"devDeps"` scope to `"deps-dev"`.

Update semantic-release commit messages to be compliant with @commitlint/config-conventional

---

helpers/python/lib/hasher.py
helpers/python/requirements.txt
helpers/python/run.py
lib/dependabot/file_fetchers/python/pip.rb
lib/dependabot/file_parsers/python/pip.rb
lib/dependabot/file_parsers/python/pip/pipfile_files_parser.rb
lib/dependabot/file_parsers/python/pip/poetry_files_parser.rb
lib/dependabot/file_updaters/python/pip.rb
lib/dependabot/file_updaters/python/pip/poetry_file_updater.rb
lib/dependabot/file_updaters/python/pip/pyproject_preparer.rb
lib/dependabot/update_checkers/python/pip.rb
lib/dependabot/update_checkers/python/pip/poetry_version_resolver.rb
spec/dependabot/file_fetchers/python/pip_spec.rb
spec/dependabot/file_parsers/python/pip/poetry_files_parser_spec.rb
spec/dependabot/file_parsers/python/pip_spec.rb
spec/dependabot/file_updaters/python/pip/poetry_file_updater_spec.rb
spec/dependabot/file_updaters/python/pip/pyproject_preparer_spec.rb
spec/dependabot/file_updaters/python/pip_spec.rb
spec/dependabot/update_checkers/python/pip/poetry_version_resolver_spec.rb
spec/dependabot/update_checkers/python/pip_spec.rb
spec/fixtures/github/contents_python_only_pyproject.json
spec/fixtures/python/pyproject_files/conflict_at_latest.toml
spec/fixtures/python/pyproject_files/exact_version.toml
spec/fixtures/python/pyproject_files/pyproject.toml
spec/fixtures/python/pyproject_files/version_not_specified.toml
spec/fixtures/python/pyproject_locks/conflict_at_latest.lock
spec/fixtures/python/pyproject_locks/exact_version.lock
spec/fixtures/python/pyproject_locks/pyproject.lock
spec/fixtures/python/pyproject_locks/version_not_specified.lock

Support for [Poetry](https://github.com/sdispater/poetry), a Python dependency management tool that has a build in resolver.
~~Note: currently the `content-hash` generated will be wrong. Needs some Python code to get it right (or some painstaking matching of Ruby and Python JSON generation).~~ Fixed!
Closes https://github.com/dependabot/feedback/issues/57.

Add poetry support

---

spec/dependabot/update_checkers/elixir/hex/version_resolver_spec.rb
spec/fixtures/elixir/mixfiles/coxir

Can I get your eye on `spec/dependabot/update_checkers/elixir/hex/version_resolver_spec.rb:137` please @stevedomin?
Would also be hugely grateful if you could take a look at the deprecation warnings when running `bundle exec rspec spec/dependabot/file_parsers/elixir/hex_spec.rb`.

Failing spec for Elixir UpdateChecker

---

lib/dependabot/pull_request_creator/labeler.rb

Hello there! :wave:
We're using [gitlab-update-script.rb](https://github.com/dependabot/dependabot-script/blob/master/gitlab-update-script.rb) for our private GitLab instance and found out issues when the script was trying to check the labels endpoint.
Our configuration:
```
source = Dependabot::Source.new(
provider: "gitlab",
api_endpoint: "https://git.example.com/api/v4",
hostname: "git.example.com",
repo: repo_name,
directory: directory,
branch: "master"
)
```
Error message:
```
Gitlab::Error::Unauthorized (Server responded with code 401, message: 401 Unauthorized. Request URI: https://gitlab.com/api/v4/projects/dev%2Ffoobar%2Dapp/labels)
```
Here I changed the hardcoded line to `source.api_endpoint`

Be GitLab API agnostic

---

helpers/npm/lib/updater.js
helpers/npm/test/updater.test.js
lib/dependabot/file_fetchers/java_script/npm_and_yarn.rb
lib/dependabot/file_parsers/java_script/npm_and_yarn.rb
lib/dependabot/file_updaters/java_script/npm_and_yarn.rb
lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb
spec/dependabot/file_fetchers/java_script/npm_and_yarn_spec.rb
spec/dependabot/file_parsers/java_script/npm_and_yarn_spec.rb
spec/dependabot/file_updaters/java_script/npm_and_yarn_spec.rb
spec/fixtures/github/contents_js_shrinkwrap.json
spec/fixtures/javascript/shrinkwraps/npm-shrinkwrap.json

File format for `npm-shrinkwrap.json` is identical to `package-lock.json`, so it should be relatively straightforward to update.
TODO:

WIP: Add support for npm-shrinkwrap.json

---

helpers/npm/package.json
helpers/yarn/package.json

I am using yarn workspaces to manage dependencies of helpers.
Without a version parameter, `yarn install` ignores the dependencies of this package.json when using workspaces. 
https://yarnpkg.com/lang/en/docs/workspaces/
Additionally, add private property to avoid accidentally publishing this package.

Add version and private keys to helper package.json files

---

helpers/python/requirements.txt
lib/dependabot/file_updaters/python/pip/pipfile_file_updater.rb
lib/dependabot/file_updaters/python/pip/pipfile_preparer.rb
lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb
lib/toml_converter.rb
spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb
spec/toml_converter_spec.rb

Should fix many Python bugs 🎉.

Update Pipenv to 2018.10.9

---

spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb
spec/fixtures/python/pipfiles/required_python_implicit

This was failing before Pipenv 2018.10.9. It now passes. 🎉

Add failing test for Python install

---

helpers/npm/lib/updater.js

- Remove `var` declarations. `var` is obsolete and `let` and `const` are more intuitive and safe.
- Reduce unnecessary `if` statements.

Remove 'var' declarations and reduce 'if' statements in updater.js

---

lib/dependabot/file_updaters/go/modules/go_mod_updater.rb
spec/dependabot/file_updaters/go/modules/go_mod_updater_spec.rb

`go get` rewrites the `go.sum`, but only includes the `go.mod` entry if there module is not imported.

go: fix go.sum updating by writing a dummy main.go

---

helpers/yarn/lib/peer-dependency-checker.js
spec/fixtures/javascript/npm_lockfiles/peer_dependency_multiple.json
spec/fixtures/javascript/package_files/peer_dependency_multiple.json
spec/fixtures/javascript/yarn_lockfiles/peer_dependency_multiple.lock

Fixes a bug where no peer dependency errors where output if the
dependencies had been added with a fixed version e.g. yarn add
react@0.14.9.
This meant that the lockfile had an entry that exactly matched running
yarn add react@0.14.9 again from `checkPeerDependencies()` which made
yarn skip fetching the manifest for that package and just relying on the
lockfile information (which has no peer dependency info).
We then bailed from the install command before fetching the manifests
for all dependencies, meaning we never got the peer dependency
information in these cases.
Fixed by letting the install command do all the work (skipping the
package and lockfile updates).
This delegates peer dependency resolution to the pacakge-linker which is
called from the install command after the manifests …

Fix bug in peer dependency checks for yarn

---

lib/dependabot/file_fetchers/ruby/bundler.rb
lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/file_parsers/ruby/bundler/file_preparer.rb
lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/file_updaters/ruby/bundler/gemfile_updater.rb
lib/dependabot/file_updaters/ruby/bundler/lockfile_updater.rb
lib/dependabot/update_checkers/ruby/bundler/file_preparer.rb
lib/dependabot/update_checkers/ruby/bundler/force_updater.rb
lib/dependabot/update_checkers/ruby/bundler/latest_version_finder.rb
lib/dependabot/update_checkers/ruby/bundler/shared_bundler_helpers.rb
lib/dependabot/update_checkers/ruby/bundler/version_resolver.rb
spec/dependabot/file_fetchers/ruby/bundler_spec.rb
spec/dependabot/file_parsers/ruby/bundler_spec.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb
spec/fixtures/github/contents_ruby_bundler_2.json

That. Optional setup under Bundler 1.17.0, so time we supported it.

Add support for gems.rb and gems.locked setup

---

helpers/yarn/lib/peer-dependency-checker.js
lib/dependabot/update_checkers/java_script/npm_and_yarn/version_resolver.rb

Also don't need to pass down the top levels deps now that we fetch all manifests.

Stop downloading node_modules when checking yarn peer deps

---

helpers/npm/bin/run.js
helpers/npm/lib/helpers.js
helpers/npm/lib/subdependency-updater.js
helpers/npm/lib/updater.js
helpers/yarn/lib/subdependency-updater.js
lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb
lib/dependabot/file_updaters/java_script/npm_and_yarn/yarn_lockfile_updater.rb
lib/dependabot/update_checkers/java_script/npm_and_yarn/subdependency_version_resolver.rb
spec/dependabot/file_updaters/java_script/npm_and_yarn_spec.rb
spec/dependabot/update_checkers/java_script/npm_and_yarn/subdependency_version_resolver_spec.rb
spec/fixtures/javascript/npm_lockfiles/subdependency_update.json

Updating npm subdependencies would be awesome because it would allow us to patch security vulnerabilities in sub-dependencies.

JS: Add failing test for npm subdependency updates

---

helpers/python/requirements.txt
lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb
spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb

Whilst we wait for a release this should fix the extras bug some users are seeing.

Pin to latest pipenv commit

---

helpers/npm/lib/subdependency-updater.js
spec/dependabot/update_checkers/java_script/npm_and_yarn/subdependency_version_resolver_spec.rb
spec/fixtures/javascript/npm_lockfiles/subdependency_update_npm5.json

When using both npm5 and yarn lockfiles we failed to update the npm5
lockfile and managed to update the yarn lockfile leaving the npm
lockfile in a broken state.
Fixing this by always running npm6 installer on the lockfile which can
deal with the missing entries and will add them back in.
When the lockfile is in an npm5 format npm6 can't update the
subdependency without doing a full install because the lockfile
requirements are exact versions (allowed range in npm6).
TODO:
Example:
https://github.com/hmarr/bump-test/pull/44

Fix bug when using both npm5 and yarn lockfiles

---

.circleci/config.yml
dependabot-core.gemspec

This enables Circle's "Insights" section, which gives reports on the slowest and flakiest tests.

Collect test metadata in CI

---

lib/dependabot/update_checkers/java_script/npm_and_yarn/subdependency_version_resolver.rb
spec/dependabot/update_checkers/java_script/npm_and_yarn/subdependency_version_resolver_spec.rb

Temp fix until we've moved error logic from file updater to the version resolver.

Mute sub-dependency version resolve errors

---

lib/dependabot/file_updaters/java_script/npm_and_yarn/npmrc_builder.rb
spec/dependabot/file_updaters/java_script/npm_and_yarn/npmrc_builder_spec.rb
spec/fixtures/javascript/npmrc/env_registry

Previously, we only stripped *some* environment variables out of the `.npmrc`. We'll now strip all of them, and use the same logic for adding global registries as we do if a `.npmrc` isn't present.

JS: Handle environment variables in npmrc in unexpected places

---

lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb
lib/dependabot/shared_helpers.rb
spec/dependabot/file_updaters/java_script/npm_and_yarn_spec.rb
spec/fixtures/javascript/npm_lockfiles/github_dependency_private.json
spec/fixtures/javascript/package_files/github_dependency_private.json

Relying on SharedHelpers.with_git_configured.. to rewrite ssh://git@..
to https:// so don't need to guard against ssh:// when raising error
about unreachable git repo.

NPM: Raise git not reachable for ssh://git

---

helpers/npm/lib/updater.js
spec/dependabot/file_updaters/java_script/npm_and_yarn_spec.rb
spec/fixtures/javascript/npm_lockfiles/os_mismatch.json
spec/fixtures/javascript/package_files/os_mismatch.json

Use npm force config to ignore engines and platform check when updating
the lockfile.
Fixes: https://sentry.io/dependabot/backend/issues/473215575

npm: Fix dependency updates with os requirements

---

.rubocop.yml
helpers/utils/git-credential-store-immutable
lib/dependabot/shared_helpers.rb

Two changes to the git credentials configuration:
1. Instead of adding lines into an existing global git config (then removing them afterwards), we take a backup of the pre-existing git config and start from scratch. This is important because CircleCI runs `git config --global url."ssh://git@github.com".insteadOf "https://github.com"` at the start of a test run, which means we end up using git over SSH rather than HTTPS.
2. The git credential store is now wrapped in an executable that filters out commands that would mutate the store. Previously, the credential store was getting nuked when credentials were invalid, causing an authentication prompt to appear and wait for user input.

Use clean git config and don't let git erase credentials

---

helpers/npm/lib/peer-dependency-checker.js
helpers/npm/lib/subdependency-updater.js

Ignore "os", "engine" and "cpu" checks when updating peer/sub
dependencies (we already do this for top level deps).

npm: ingore platform and engine checks on install

---

bin/dry-run.rb
lib/dependabot/file_updaters/go/dep/lockfile_updater.rb
lib/dependabot/update_checkers/go/dep/file_preparer.rb
spec/dependabot/file_updaters/go/dep/lockfile_updater_spec.rb
spec/dependabot/update_checkers/go/dep_spec.rb
spec/fixtures/go/gopkg_locks/fsnotify_trans_dep.lock
spec/fixtures/go/gopkg_tomls/fsnotify_trans_dep.toml

It was still occurring for transitive dependencies. Always adding an override for fsnotify seems to fix it in all cases, and doesn't appear to do anything to the lockfile when fsnotify isn't used.

Dep: fix fsnotify-related panic

---

lib/dependabot/update_checkers/python/pip/pipfile_version_resolver.rb
spec/dependabot/update_checkers/python/pip/pipfile_version_resolver_spec.rb
spec/fixtures/python/lockfiles/unsupported_dep.lock
spec/fixtures/python/pipfiles/unsupported_dep

Some Python dependencies can only be built on a mac. Nothing we can do to resolve dependency files with that setup.

Python: Raise a resolvability error for unsupported dependencies

---

lib/dependabot/file_parsers/java_script/npm_and_yarn.rb
lib/dependabot/update_checkers/java_script/npm_and_yarn.rb
lib/dependabot/update_checkers/java_script/npm_and_yarn/version_resolver.rb
spec/dependabot/update_checkers/java_script/npm_and_yarn/version_resolver_spec.rb
spec/fixtures/javascript/npm_responses/react-modal.json

Currently only for the `UpdateChecker` - need to handle updating multiple dependencies in the `FileUpdater` before this can be deployed.
Freeform notes on considerations as I was writing this:
- Requirement comes from another dependency
- Likely that it would be fine if we updated that other dependency (unusual
for a dependency to have a peer dependency which itself has peer
dependencies)
- Need to check whether it's a sub-dependency we're updating
- Also, that other dependency could have other peer dependencies
- In theory we should do a resolvability check
- Requirement comes from this dependency
- NOT likely that it would be fine if we update the other dependency, as there
may be other dependencies that use it as a peed dep (e.g., many packages
declare react as a peed dependency)
- …

[WIP] JS: Implement full unlock for resolving JS peer dependencies

---

python/.gitignore
python/lib/dependabot/python/file_parser.rb
python/spec/dependabot/python/file_parser_spec.rb
python/spec/fixtures/requirements/invalid_value.txt

Fix for https://sentry.io/dependabot/backend/issues/798713617/?environment=default&referrer=alert_email. Needs to wait for Python refactor.

Python: Catch ValueError and treat as a FileNotEvaluatable error

---

README.md

Tiny changes in the README to suggest using only needed dependencies for helpers in a "production" environment.
Adding these arguments reduce run time and disk usage.

Promote runs without helpers dev dependencies

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
elm/lib/dependabot/elm/update_checker/elm_18_version_resolver.rb
elm/lib/dependabot/elm/update_checker/elm_19_version_resolver.rb
helpers/test/run.rb
hex/.gitignore
hex/lib/dependabot/hex/file_parser.rb
hex/lib/dependabot/hex/update_checker/version_resolver.rb
lib/dependabot/file_updaters/go/dep/lockfile_updater.rb
lib/dependabot/shared_helpers.rb
lib/dependabot/update_checkers/go/dep/version_resolver.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
python/lib/dependabot/python/update_checker/pipfile_version_resolver.rb
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
spec/dependabot/shared_helpers_spec.rb
terraform/.gitignore
terraform/lib/dependabot/terraform/file_parser.rb

Switch from `IO.popen` to `Open3.capture3` to get separate stdout and
stderr, adding stderr to Sentry error context.
Adding error context to debug these Sentries with no useful information:
https://sentry.io/dependabot/backend/issues/831291825/events/41548068139/

Add error context when helper subprocesses fail

---

lib/dependabot/file_fetchers/ruby/bundler.rb
lib/dependabot/file_fetchers/ruby/bundler/gemspec_finder.rb
lib/dependabot/file_parsers/ruby/bundler.rb
lib/dependabot/file_parsers/ruby/bundler/file_preparer.rb
lib/dependabot/file_updaters/ruby/bundler.rb
lib/dependabot/file_updaters/ruby/bundler/lockfile_updater.rb
lib/dependabot/pull_request_creator.rb
lib/dependabot/pull_request_creator/branch_namer.rb
lib/dependabot/pull_request_creator/message_builder.rb
lib/dependabot/update_checkers/ruby/bundler/file_preparer.rb
spec/dependabot/file_fetchers/ruby/bundler/gemspec_finder_spec.rb
spec/dependabot/file_fetchers/ruby/bundler_spec.rb
spec/dependabot/file_parsers/ruby/bundler_spec.rb
spec/dependabot/file_updaters/ruby/bundler_spec.rb
spec/dependabot/update_checkers/ruby/bundler/file_preparer_spec.rb
spec/dependabot/update_checkers/ruby/bundler_spec.rb
spec/fixtures/github/gemfile_with_path_gemspec_content.json
spec/fixtures/ruby/gemfiles/imports_gemspec_from_path
spec/fixtures/ruby/lockfiles/imports_gemspec_from_path.lock

We were seeing an error for one of [our Gemfiles](https://github.com/UKGovernmentBEIS/beis-mspsds/blob/master/shared-web/Gemfile#L5):
```
Bundler::Dsl::DSLError with message: 
[!] There was an error parsing `Gemfile`: There are no gemspecs at /home/dependabot/dependabot-updater/dependabot_tmp_dir/shared-web/dev. Bundler cannot continue.
>  gemspec path: "./dev"
```
We're using the `path` option [as described here](https://bundler.io/v1.17/rubygems.html) but the [parsing code only supports gemspecs at the top level](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_parsers/ruby/bundler.rb#L281).
I've made a naive change to correct this but it seems like it breaks another test relating to path based `gem` dependencies. The correct solution might involve checking …

[WIP] Add support for gemspec path option

---

lib/dependabot/file_updaters/java_script/npm_and_yarn.rb
lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb

Remove redundant guard in npm lockfile updater, raised in
`FileUpdaters::JavaScript::NpmAndYarn`

JS: Add error context when no files where updated

---

npm_and_yarn/lib/dependabot/npm_and_yarn/dependency_files_filterer.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/dependency_files_filterer_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb

Omit package files and lockfiles that are not related to the dependencies being checked/updated.
The aim is to speed up large repos like this one (has 100 dependency files): https://github.com/AxaGuilDEv/react-toolkit
From testing on a few dependencies that needed to be updated the number of dependency files went from 100 to ~10.
Also removed a few duplicate calls to lockfile updates.

NPM/Yarn: Filter dependency files

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/git_sub_dep_invalid_from.json
npm_and_yarn/spec/fixtures/package_files/git_sub_dep_invalid_from.json

NPM 6.6.0 has started failing when a sub-dependency has a "from"
field that includes the dependency name.
Example invalid from: "from": "bignumber.js@git+https://gi... (shuld not
include `bignumber.js@`).
Should be able to delete this in the future once this is fixed in npm.

NPM: Fix invalid from for git sub-dependencies

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

That. Fixes https://github.com/dependabot/feedback/issues/344.

JS: Parse the semver version, rather than the git SHA, for git reqs with a semver specification

---

bundler/lib/dependabot/bundler/file_fetcher.rb
bundler/spec/dependabot/bundler/file_fetcher_spec.rb
cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb
composer/lib/dependabot/composer/file_fetcher.rb
composer/spec/dependabot/composer/file_fetcher_spec.rb
git_submodules/lib/dependabot/git_submodules/file_fetcher.rb
lib/dependabot/file_fetchers/base.rb
maven/lib/dependabot/maven/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_fetcher_spec.rb
spec/dependabot/file_fetchers/base_spec.rb

Previously, Dependabot would fetch files at the top-level of submodules, if required. That was a little half-arsed.
Now, the FileFetcher can be told whether you want to fetch files from submodules (for support files this will be true, for files we might want to update it will be false). If it is asked to fetch files from submodules it will dive deep into those submodules to find the file.

Better submodule fetching

---

dependabot-core.gemspec
lib/dependabot/pull_request_creator.rb
lib/dependabot/pull_request_creator/gitlab.rb
spec/dependabot/pull_request_creator/gitlab_spec.rb
spec/dependabot/pull_request_creator_spec.rb

This PR add the following options to the GitLab PR creator:
* `milestone` same as GitHub `milestone`
* `approvers` same as GitHub `reviewers`

Align GitLab PR creator with generic options

---

go_modules/helpers/go.mod
go_modules/helpers/go.sum
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/path_converter_spec.rb

Switches us to fork of vcs.
Once https://github.com/Masterminds/vcs/pull/92 is merged we can switch
back.

go_modules: handle vanity urls that return non-200 responses

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Serve a better error message when a dependency can't be cloned.

go_modules: detect missing/invalid dependency with pseudo version

---

npm_and_yarn/helpers/npm/lib/peer-dependency-checker.js
npm_and_yarn/helpers/npm/lib/subdependency-updater.js
npm_and_yarn/helpers/npm/lib/updater.js

Sadly this will probably not have the desired effect. I've not managed to get reliable run times locally so want to get this out and test on a live run.
- Enable `prefer-offline` setting in npm which sets 'force-cache' in the npm fork of fetch (using the local cache folder `~/.npm`)
- Turn off audit for npm helpers
- Removed redundant cleanup installer from peer dep checker (only want peer dependency warnings)

Force local cache for npm installs

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

For unresolvable dependencies due to git errors, and for go.sum checksum mismatches.

Go (modules): more detailed and specific error messages

---

common/lib/dependabot/file_fetchers/base.rb
common/spec/dependabot/file_fetchers/base_spec.rb
common/spec/fixtures/github/symlinked_file_content.json
common/spec/fixtures/github/symlinked_repo.json

When fetching support files, there's no reason we shouldn't fetch them from symlinked directories. This isn't the last word on fetching symlinked files (it only applies for directories) but it's a step in the right direction and will fix https://github.com/minimum2scp/dependabot-example-02/issues/23.

Fetch files from symlinked directories if fetching submodules

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/git_ref_dependencies.json
npm_and_yarn/spec/fixtures/npm_lockfiles/git_tag_dependencies.json
npm_and_yarn/spec/fixtures/package_files/git_ref_dependencies.json
npm_and_yarn/spec/fixtures/package_files/git_tag_dependencies.json

Fixes the logic to restore locked git dependencies in npm lockfiles using tags/refs.
When updating a npm dependency we need to lock git dependencies specified in `package.json` to a commit so npm doesn't unintentionally update them.
We handle this by updating the `package.json` version with the resolved git commit from the lockfile and restore this after update.
After a `npm install` this commit sha is set in the lockfile so we need to restore it to the original value (plain git url or with tags/refs).

NPM: Fix lockfile for git dependencies using tags

---

composer/helpers/bin/run

Without using the global variable, a new local variable is created.
https://3v4l.org/4TbmN vs https://3v4l.org/06HcL

PHP: Use the global variable $memory when freeing it

---

cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
common/lib/dependabot/shared_helpers.rb

Cargo (well, git2-rs) doesn't accept the 'command with args' form of specifying a git credential helper. It does, however, accept the shell snippet form, which is prefixed with a !.
I still need to confirm that this doesn't break regular git (all other languages).

Cargo: fix git credential helper issue

---

bundler/lib/dependabot/bundler/file_parser.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/fixtures/ruby/gemfiles/git_source_unparseable
bundler/spec/fixtures/ruby/lockfiles/git_source_unparseable.lock

That. Fixes an error we're seeing, and I don't  *think* there's any downside to this. Will merge and deploy tomorrow when I can watch it out.

Allow gemspec dependencies to have a source (in case it's git)

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb

Seems to handle the case when we auth against artifactory and get
"Unable to authenticate, need: Basic realm="Artifactory Realm""
This seems to be caused by a trailing slash in the registry host as set
in config variables. When we write this out in npmrc we add another
trailing slash and this seems to cause the above error. Changing to a
single trailing slash returns a 403 Forbidden error.

NPM: Handle 403 Forbidden when updating lockfiles

---

npm_and_yarn/README.md

Looks like a copy paste error :)
`npm` is written in all lowercase on purpose.

Fix copy paste error in npm and Yarn README.md

---

bin/dry-run.rb

Add `--cache=step` option to the `dry-run.rb` script.
Step can be one of: `files`, `dependencies`, `updates`
Example:
```
bin/dry-run.rb npm_and_yarn "repo-path" --cache=files,dependencies,updates
```
This marshalls the output of `files`, `dependencies` and `updated_deps`
to `tmp/github-logi@repo-name/cache/step.bin`
Also writing out all dependency files to `tmp` making debugging easier.
Next step is to use real dependency files as the cache so you could edit
these or add your own files to test against.

Add option to cache dry-run script steps

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Another resolvability error that we should surface to our users.

Go (modules): handle missing sub-dependency error

---

.rubocop.yml
bundler/.rubocop.yml
cargo/.rubocop.yml
common/.rubocop.yml
composer/.rubocop.yml
dep/.rubocop.yml
docker/.rubocop.yml
elm/.rubocop.yml
git_submodules/.rubocop.yml
go_modules/.rubocop.yml
gradle/.rubocop.yml
hex/.rubocop.yml
maven/.rubocop.yml
npm_and_yarn/.rubocop.yml
nuget/.rubocop.yml
omnibus/.rubocop.yml
python/.rubocop.yml
terraform/.rubocop.yml

This change is aesthetic but may also help IDEs to handle Rubocop validation much better (both for perf and for overall coverage).
Except if you have specific usage?

Reduce rubocop config spread and cover root files

---

common/lib/dependabot/errors.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Caused by the module path specified in a `go.mod` requirement differing from the module path declared in the dependency's `go.mod` `module ...` line.

Go (modules): Handle module path mismatch errors

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

Fixing locked peer dependency updates for libraries that don't have
lockfiles (and therefore don't have a current version).
Removing logic to raise when there are identical peer dependency warnings. Turns out there are a bunch of cases where there are legitimately identical errors (e.g. when the same dep is shared across multiple sub packages).

JS: Fix peer dependency updates for libraries

---

npm_and_yarn/helpers/npm/lib/updater.js
npm_and_yarn/helpers/yarn/lib/updater.js
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/github_dependency_semver_modern.json

Fixes lockfile updates for dependencies installed with a semver range,
for example: `yarn add graphql@graphql/graphql-js#semver:^v14.0.0`
When a semver git dependency was updated Dependabot dropped the semver
part and updated the lockfile with the new absolute version instead.
Also cleaned up the yarn updater to match the npm updater taking the
version requirement from the pacakge.json instead of constructing it
from skratch when using git shorthand syntax.

NPM: Fix lockfile for git deps with semver version

---

go_modules/helpers/updatechecker/main.go
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

We do want to support this in the future, but it needs more thought - we should do it well or not at all.

Go (modules): prevent all pseudo version updates

---

bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/fixtures/ruby/gemfiles/git_source_circular
bundler/spec/fixtures/ruby/lockfiles/git_source_circular.lock

That. Doesn't happen often, but we should quietly not update to bad versions if/when it does.

Ruby: Handle circular dependencies at the latest version

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/config_files/git_tags.tf

Terraform handles a module source prefixed by `git@github.com:` as a
type of Git repo pointing to GitHub automatically[1][2]. This commit adds
parsing of these GitHub SSH sources to match the existing parsing for
GitHub HTTP sources.
[1]https://www.terraform.io/docs/modules/sources.html#github
[2]https://github.com/hashicorp/terraform/blob/6fe2703/vendor/github.com/hashicorp/go-getter/detect_github.go#L20-L21
---
Example repo: https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/blob/master/consul/main.tf#L28

Parse `git@github.com:` Terraform module sources

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb

Fixes https://sentry.io/organizations/dependabot/issues/906729855/?project=160754&referrer=RegressionActivityEmail&statsPeriod=14d

JS: Ignore URL-style versions in npm lockfiles in NpmAndYarn::FileParser::LockfileParser

---

Dockerfile

`ext-gmp` seems to be reported missing so trying to install the gmp for php 7.2:
```
erorus/db2 dev-master requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
```

Install php7.2-gmp

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb

Adding a better error message when the lockfile is corrupt with
instructions to re-generating the lockfile.
Previously when a version was missing from some entries in package-lock
or npm-shrinkwrap you get a pretty unhelpful error saying:
`Cannot read property 'match' of undefined`

NPM: Raise helpful error when lockfile is corrupt

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
cargo/spec/fixtures/lockfiles/git_dependency_ssh
cargo/spec/fixtures/manifests/git_dependency_ssh

~~Needs a test.~~
Because we switch git URLs from SSH to HTTPS, we can sometimes get duplicates in the lockfile. The only way to remove them is to regex through.

Cargo: Remove lockfile duplicates

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

That. See https://github.blog/changelog/2019-03-15-creating-a-commit-on-behalf-of-an-organization/.

Sign commits on behalf of an org

---

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb

That. There's no user input to sanitize here, and we don't want the `memory_limit =-1` to get escaped.
I did a sweep of the codebase and there are no other places where we have this problem.

PHP: Remove overzealous use of shellwords

---

npm_and_yarn/helpers/lib/npm/peer-dependency-checker.js
npm_and_yarn/helpers/lib/npm/subdependency-updater.js
npm_and_yarn/helpers/lib/npm/updater.js

When installing a package from git npm will run the scripts `prepare`
and `prepack` if defined in pacakge.json scripts.
This fails on aws and we shouldn't need to run any prepare/prepack
scripts to build a lockfile. These scripts are commonly used to babel
transpile the src.

NPM: ignore lifecycle scripts when installing@git

---

npm_and_yarn/helpers/lib/npm/updater.js
npm_and_yarn/spec/fixtures/npm_lockfiles/git_sub_dep_invalid_from.json

Sanitise the lockfile before first install removing any invalid `from`
and `requries` for git dependencies.

NPM: Fix git dependencies with invalid requires

---

Dockerfile

This error is caused by package prepare/prepack scripts that fail to
execute.
Setting `dry-run` globally is the only way to get npm to pick up the
config setting when installing git dependencies. When installing git
dependencies npm will shell out out to the cli and loosing
all config passed to the installer from `npm/updater.js`.
Code calling `npm install` from npm:
https://github.com/npm/cli/blob/latest/lib/pack.js#L293:L312

NPM: Fix "premature close" for git dependencies

---

maven/lib/dependabot/maven/update_checker.rb
maven/lib/dependabot/maven/update_checker/property_updater.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb
maven/spec/dependabot/maven/update_checker_spec.rb

That. This is pretty simple, since we don't consider resolvability for Maven. Hooks into the logic added to common [here](https://github.com/dependabot/dependabot-core/commit/0549ebab2530b8287654da00ee382e72f4814c54).
Idea is that users would prefer minimal changes when fixing a security vulnerability. We'll roll this out across all languages over time (some are harder than others!).

Maven: Upgrade to lowest fixed version if a dependency is vulnerable

---

nuget/lib/dependabot/nuget/update_checker.rb
nuget/lib/dependabot/nuget/update_checker/property_updater.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

Same as https://github.com/dependabot/dependabot-core/pull/1107, but for .NET.

.NET: Upgrade to lowest fixed version if a dependency is vulnerable

---

gradle/lib/dependabot/gradle/update_checker.rb
gradle/lib/dependabot/gradle/update_checker/multi_dependency_updater.rb
gradle/lib/dependabot/gradle/update_checker/version_finder.rb
gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb
gradle/spec/dependabot/gradle/update_checker_spec.rb

Same as #1107, but for Gradle.

Gradle: Upgrade to lowest fixed version if a dependency is vulnerable

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
npm_and_yarn/spec/fixtures/npm_responses/etag_deprecated.json
npm_and_yarn/spec/fixtures/npm_responses/peer_dependency_deprecated.json

When getting possible versions from npm registry we filter out deprecated versions which meant that deprecated packages with peer requirements returned a nil latest resolvable version which got converted into a empty version string in the updater checker causing the exception: "blank strings must not be provided as versions".

NPM: Fix update checker for deprecated deps

---

nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb
nuget/spec/dependabot/nuget/file_updater/project_file_declaration_finder_spec.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb
nuget/spec/fixtures/csproj/basic.csproj

Nuget supports case-insensitive version attributes (e.g. `Version` and
`Version`) for `PackageReference` entries.
Tested this with nuget and it will install the specific version. The
rest of the PackageReference attributes seem to be case-sensitive, e.g.
`Include`.

Nuget: support lowercase version attributes

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb

Sad fix for https://sentry.io/organizations/dependabot/issues/959275980/?project=1425239&referrer=RegressionActivityEmail.
We can't update aliased dependencies at the moment. We ignore them at the top-level, but if someone configures JS to update sub-dependencies then we'll try to update them as parsed from the lockfile.
This PR excludes them from the lockfile. We can do better than that, and fully support aliased dependencies in future, but not yet.

JS: Ignore aliased dependencies in lockfile parser

---

cargo/lib/dependabot/cargo/file_parser.rb
cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/lib/dependabot/cargo/update_checker/file_preparer.rb
cargo/spec/dependabot/cargo/file_parser_spec.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
cargo/spec/dependabot/cargo/file_updater/manifest_updater_spec.rb
cargo/spec/dependabot/cargo/update_checker/file_preparer_spec.rb
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
cargo/spec/fixtures/lockfiles/target_dependency
cargo/spec/fixtures/manifests/target_dependency

See https://github.com/dependabot/feedback/issues/448 for details.
TODO:
- `FilePreparer` needs to handle target-specific dependencies
- `FileUpdater` needs to handle target-specific dependencies when pinning

[WIP] Rust: Update target-specific dependencies

---

python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
python/spec/fixtures/pyproject_files/latest_subdep_blocked.toml
python/spec/fixtures/pyproject_locks/latest_subdep_blocked.lock

Previously, when updating a Poetry sub-dependency, we always updated it to the latest (resolvable) version. This meant the `PoetryVersionResolver#resolvable?` method was broken for sub-dependencies, and the ignore conditions weren't considered when updating Poetry sub-dependencies.
This PR fixes both of the above by temporarily creating top-level requirements for Poetry sub-dependencies when assessing version resolvability and updating lockfiles.

Python: Update poetry sub-dependencies to a specific version

---

npm_and_yarn/helpers/lib/npm/remove-dependencies-from-lockfile.js
npm_and_yarn/helpers/lib/npm/subdependency-updater.js
npm_and_yarn/helpers/lib/npm/updater.js
npm_and_yarn/helpers/package.json
npm_and_yarn/helpers/test/npm/updater.test.js
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/package-lock.json
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/package_lock_preserved_indentation.json
npm_and_yarn/spec/fixtures/npm_lockfiles/subdependency_update_preserved_indentation.json

Npm do this so we should do the same ✌️
When updating npm lockfiles we used to always update it to use 2 spaces.
Setting indentation in Ruby isn't possible so moved the logic of
removing sub deps to JS.

NPM: Preserve indentation of lockfiles

---

npm_and_yarn/helpers/lib/npm/updater.js

This was introduced in a bad rebase conflict.

NPM: Remove extraneous git url fix

---

Dockerfile
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
python/helpers/build
python/lib/dependabot/python/python_versions.rb
python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb

That. We stayed on 3.6 for a while as we want to have the most commonly used version in the Dockerfile. That's hopefully shifted to 3.7 by now.
Supporting stats: https://www.jetbrains.com/research/python-developers-survey-2018/

Use Python 3.7.3

---

common/lib/dependabot/git_metadata_fetcher.rb
common/lib/dependabot/pull_request_creator/github.rb
common/spec/dependabot/git_metadata_fetcher_spec.rb
common/spec/dependabot/pull_request_creator/github_spec.rb

We've seen a few errors from GitHub when requesting the `git/refs/heads/<branch_name>` endpoint, and can replace it with fetching the upload pack for the repo. That's likely to be quicker, so we should give it a try.

Use service pack to determine existing branches

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb

When packages have a slash in them (e.g. `@private/package`) the
registry escapes it to `%2f` in the error response.
We now sanitize this in the final error detail presented in issues
making it slightly less cryptic.
Previously:
`404 Not Found - GET https://registry.npmjs.org/@private%2fpackage - Not found`
Now:
`404 Not Found - GET https://registry.npmjs.org/@private/package - Not found`

JS: Sanitize / from package names from errors

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb
docker/spec/fixtures/docker/registry_tags/gcr_io.json
docker/spec/fixtures/docker/registry_tags/kube_state_metrics.json

Suggesting least invasive change to the regex to support the tags like 'v1.5.0'

#1194 fix docker tag regex to support common tag format with 'v' prefix

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

If we use a package name other than `main`, we don't build anything during `go get -d`, which means we don't have to worry about a whole class of errors which previously caused us problems (such as depending on a Go module without a top-level package, as the import path can't be figured out from the go.mod alone).

Don't invoke builder during `go get -d`

---

bin/dry-run.rb
common/dependabot-common.gemspec

Ops didn't realise byebug was already a dev dependency.

Use byebug instead of pry

---

common/.gitignore
common/lib/dependabot/dependency.rb
common/lib/dependabot/file_parsers/base/dependency_set.rb
common/spec/dependabot/dependency_spec.rb
common/spec/dependabot/file_parsers/base/dependency_set_spec.rb
npm_and_yarn/.gitignore
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/bundled_sub_dependency.json
npm_and_yarn/spec/fixtures/package_files/bundled_sub_dependency.json

Thinking that we shouldn't update bundled sub-dependencies as they have
been bundled into the release at an exact version by a parent using
`bundledDependencies`.
For example, fsevents < 2 bundles node-pre-gyp meaning all it's
sub-dependnecies get bundled into the release tarball at publish time so
you always get the same sub-dependency versions if you re-install a
specific version of fsevents.
Updating the sub-dependency (by deleting the entry) does seem to work
but it gets removed from the bundled set of dependencies and moved top
level resulting in a bunch of package duplication which is pretty
confusing.
To fix this properly we would need to try and update the parent but
this gets a bit crazy if we need to go up several levels which is the
case when updating `tar` here: `chokidar > …

Npm: Ignore bundled sub-dependencies

---

go_modules/helpers/updatechecker/gomodfile.go
go_modules/helpers/updatechecker/main.go
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

The replace directive can be used to pin dependencies to a specific version. Don't update the dependency in that case.
Related: https://github.com/dependabot/feedback/issues/538
See: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

Go (modules): don't update replace-pinned dependencies

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/message_builder.rb
common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb

Allows a hash of commit message options to be passed to the pull request creator. The allowed options are:
- `signoff_details` which works as currently used
- `prefix` which allows a prefix to be specified
- `include_scope` which takes a boolean to determine with the dependency's scope should be included in the prefix
The intention is for `prefix` and `include_scope` to be allowed keys under `commit_message` in Dependabot's config files, and for this to provide a robust way for folks to specify that they want to use a particular commit style. A config file might look like:
```yaml
version: 1
update_configs:
- package_manager: "ruby:bundler"
directory: "/"
update_schedule: "live"
commit_message:
- prefix: "chore"
- include_scope: true
```
One deficiency here is that the same prefix will be …

Allow commit_message_options to be passed to pull request creator

---

common/lib/dependabot/pull_request_creator/branch_namer.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb

Despite "@" character is perfectly fine as a part of a Git branch name,
it is not allowed inside a Docker tag. It can break some workflows when
branch name is used as a Docker tag for corresponding Docker image.
Replacing it with something safer like "at-" string solves the problem.
UPD: It's been decided to strip the `@` character from branch name altogether.

Strip @ character from branch name

---

python/lib/dependabot/python/file_parser/python_requirement_parser.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb

Removes a bunch of duplication, and creates a single place for us to make improvements to our Python version detection (including, for example., parsing the `setup.py` and getting the `python_requires` out of it, or adding imputed requirements based on the Django version being used).

Python: Move Python version requirement detection into its own class

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
npm_and_yarn/spec/fixtures/github/package_json_with_yarn_resolution_file_content.json

This fixes yarn lockfile resolution with file paths coming from a
resolutions declaration, for example:
```json
"resolutions": {
"js-yaml/**/sprintf-js": "file:./mocks/sprintf-js"
}
```
Yarn supports selective version "resolutions" to override the version of
sub-dependencies. Usually this is used to force a sub-dependency to a
patched/working version when the parent isn't being updated but you can
also set a file path.

Fetch yarn file path resolutions from manifest

---

.dependabot/config.yml

Slightly embarrassing that we didn't already have this switched on!

Enable Dependabot for go_modules helpers

---

go_modules/helpers/go.mod
go_modules/helpers/go.sum

The previous version was using the BitBucket v1 API, which was recently turned off. This meant that dependabot-core would blow up when trying to resolve modules hosted on BitBucket. masterminds/vcs v1.13.1 includes https://github.com/Masterminds/vcs/pull/101, which switches it over to the BitBucket v2 API.
Should fix #1248.

Bump masterminds/vcs to v1.13.1 to fix Go bitbucket support

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher/path_dependency_builder_spec.rb

Yarn supports "link:." paths for local file paths and they are
interchangeable with "file:" so treating them the same and building
unfetchable dependencies for them (for example when link dependency is
missing package.json).

Yarn: Add support for missing link: path deps

---

bin/dry-run.rb

After pulling dependabot-core image and building dependabot-core-development, I tried `bin/dry-run.rb` with several projects and found out that `pip` support was missing:
```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb pip UPC/mailtoticket
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Traceback (most recent call last):
1: from bin/dry-run.rb:187:in `<main>'
/home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers.rb:11:in `for_package_manager': Unsupported package_manager pip (RuntimeError)
```
Hope this helps!

Missing pip support in dry-run

---

composer/README.md
composer/helpers/bin/run
composer/helpers/composer.json
composer/helpers/src/DependabotInstallationManager.php
composer/helpers/src/DependabotPluginManager.php
composer/helpers/src/ExceptionIO.php
composer/helpers/src/Hasher.php
composer/helpers/src/UpdateChecker.php
composer/helpers/src/Updater.php

This PR
💁‍♂ There are other package managers for PHP, so renaming the namespace makes room for those.

[Composer] Enhancement: Rename namespace

---

bundler/lib/dependabot/bundler/file_fetcher.rb
bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/file_parser/file_preparer.rb
bundler/lib/dependabot/bundler/file_updater.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb
bundler/spec/dependabot/bundler/file_fetcher_spec.rb
bundler/spec/dependabot/bundler/file_parser/file_preparer_spec.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb
bundler/spec/fixtures/github/contents_ruby_with_specification.json
bundler/spec/fixtures/ruby/gemfiles/path_source_statesman
bundler/spec/fixtures/ruby/lockfiles/path_source_statesman.lock
bundler/spec/fixtures/ruby/specifications/statesman

That. `.specification` files are a thing, and are documented (a little) [here](https://gist.github.com/jordelver/4352220).

Bundler: Handle path dependencies that use a .specification file

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/github.rb
common/spec/dependabot/pull_request_creator/github_spec.rb
common/spec/dependabot/pull_request_creator_spec.rb

Currently, there is a danger that Dependabot creates many PRs for the same update if it kicks off several update jobs during which a PR gets merged. That sucks - see [these PRs](https://github.com/reload/acdc/pulls?q=is%3Apr+is%3Aclosed) for an example of things going wrong.
This PR adds a `require_up_to_date_base` option to `PullRequestCreator`. When passed, Dependabot will check whether the commit SHA it's using is up-to-date, and bail out if it's not. That will allow us to prevent races like the above.
Builds on https://github.com/dependabot/dependabot-core/pull/1308.

Merged pr filtering

---

composer/lib/dependabot/composer/requirement.rb
composer/spec/dependabot/composer/requirement_spec.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/composer_files/dev_branch

Ranges like `>= 1.x` are invalid in PHP (check out [this site](https://semver.mwl.be/#!?package=madewithlove%2Felasticsearcher&version=*&minimum-stability=stable) for validation). We should therefore raise if we encounter them.
Fixes https://github.com/AmazeeLabs/silverback/issues/85.

Composer: Parse ranges with a wildcard as invalid

---

.gitignore
bin/dry-run.rb

Dumping cached dependency files individually with file extensions making it possoble to edit the cache and re-run the script. This is helpful when trying to narrow down a reproduction case.
When running the dry run script it will always dump the dependency files in: `dry-run/account/repo/branch/directory/*` (omitting branch and directory unless they are set)
To read from the cache pass `--cache=files` to the script: `bin/dry-run.rb npm_and_yarn "dependabot/website" --cache=files`
You can edit the contents of this folder (make sure it's in sync with the `cache-manifest.json` file) and re-run against the edited cache.
If you run the dry run with `bin/dry-run.rb npm_and_yarn "test/test" --cache=files` you'll need a `cache-manifest.json` in `./dry-run/test/test` with the file metadata and …

Update dry run to cache editable dependency files

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

We recently added support for GitHub Actions to Dependabot. Woo! Yay!
Because GitHub actions are generally specified using a git tag, but don't have a lockfile we often end up in the PR creator with an update that switches git tags but which doesn't know what the commit SHA of the previous tag was. That means we get a slightly sad PR message, as seen [here](https://github.com/greysteil/berry/pull/1).
> Updates the requirements on [actions/setup-node](https://github.com/actions/setup-node) to permit the latest version.
We do not need to live with this sadness! By tweaking the `MessageBuilder`'s definition of `previous_version` we can use the old tag as the version in these cases and get commit messages like:
> Bumps [actions/setup-node](https://github.com/actions/setup-node) from v1.0.0 to …

Better commit messages when updating a git tag without a lockfile

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker_spec.rb

Previously we were wussing out of creating these errors in all cases, because we couldn't distinguish between cases where the error happened on install and cases where it happened on update.
This improves the situation slightly - we don't have to distinguish between those cases for setups without a lockfile.

PHP: Raise a Dependabot::DependencyFileNotResolvable error in some VersionResolver cases

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker_spec.rb
composer/spec/fixtures/composer_files/version_conflict_library

If we get a resolution error on a library when trying to update its version we should check whether it is due to our PHP version. If it is we should relax it.

PHP: Handle loosely specified PHP versions for libraries better

---

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker_spec.rb
composer/spec/fixtures/composer_files/odd_php_specified

Extends our MissingExtension logic to cover `php-64bit` requirements. See https://sentry.io/organizations/dependabot/issues/1103546162/events/4678a36e0b4f4a73b1ec849036b2bf7a/?environment=default&project=1425239&statsPeriod=14d (private) for error report.

Composer: Handle php-64bit requirements

---

composer/helpers/composer.json
composer/helpers/composer.lock

This PR
💁‍♂ I ran
```
$ composer config sort-packages true
```
followed by
```
$ composer require php:^7.1
```
to trigger sorting.
For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.

[Composer] Enhancement: Keep packages sorted in composer.json

---

composer/helpers/composer.json

This PR
💁‍♂ The former shows a diff, the latter shows progress and is generally more verbose.
~~❓ Couldn't find this being run anywhere in CI, should it be?~~ Never mind, spotted it in https://github.com/dependabot/dependabot-core/blob/c621705e067c067082ed9b2d8afa224e35a858bb/composer/helpers/build#L14.

[Composer] Enhancement: Run php-cs-fixer with --diff and --verbose options

---

composer/helpers/build

This PR
💁‍♂ This ensures that `composer.json` is valid, and that `composer.lock` is in sync. The `--no-check-publish` option can be used to ignore requirements for publication on https://packagist.org.
For reference, see https://getcomposer.org/doc/03-cli.md#validate.

[Composer] Enhancement: Validate composer.json and composer.lock

---

composer/helpers/src/Hasher.php

This PR
💁‍♂ Probably best reviewed commit by commit.

[Composer] Fix: Fetch content of composer.json in specified working directory when calculating hash

---

bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/dependabot/bundler/file_updater/gemspec_sanitizer_spec.rb
bundler/spec/fixtures/ruby/gemspecs/version_as_float

The normal syntax in a Gemfile indicates versions as a string, i.e. `s.version     = '1.0.0'`.  However, bundler will recognize and accept a version number entered as a float.  This PR updates dependabot-core to handle these cases.
Paired w/@feelepxyz

Handle gemspec with a float version number

---

python/spec/fixtures/setup_files/with_open.py
python/spec/fixtures/setup_files/with_pbr.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/dependabot/dependabot-core on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./python/spec/fixtures/setup_files/with_open.py:10:9: F821 undefined name 'io'
file3 = io.open("some_file", "r")
^
./python/spec/fixtures/setup_files/with_open.py:16:17: F821 undefined name 'os'
return open(os.path.join(os.path.dirname(__file__), fname)).read()
^
./python/spec/fixtures/setup_files/with_open.py:16:30: F821 undefined name 'os'
return open(os.path.join(os.path.dirname(__file__), fname)).read()
^
./python/spec/fixtures/setup_files/with_parse_reqs.py:3:29: F821 undefined name 'parse_requirements'
reqs = [str(r.req) for r in parse_requirements('requirements.txt', session=PipSession()) if r.req is …
```

Undefined names: Add missing imports

---

.gitignore
bin/dry-run.rb

Porting logging and logic from dependabot-updater and adding a few
options to customise the updater:
- `--write`: will write the updated files into the dry-run cache folder
(initilizes a git repo to help with diffing 👌)
- `--lockfile_only`: only update the lockfile
- `--requirements_update_strategy`: chaneg how to update manifest
requirements

Update dry-run to be more like dependabot-updater

---

bin/dry-run.rb
common/lib/dependabot/file_fetchers/base.rb
common/lib/dependabot/source.rb
common/spec/dependabot/file_fetchers/base_spec.rb

Add the option to fetch manifest files from a specific commit instead of the branch head commit.
This is useful when debugging a past update that has already been fixed and merged into master.
Example:
```
bin/dry-run.rb bundler "dependabot/dependabot-core" --commit=e0c9035898dd52fc65c41454cec9c4d2611bfb37
```

dry-run: add --commit option to fetch from

---

common/dependabot-common.gemspec
common/lib/dependabot/pull_request_creator/commit_signer.rb

It's _really_ slow to install, and mostly not needed now that app commits are automatically signed (https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps/).

Make gpgme an optional dependency

---

common/lib/dependabot/update_checkers/base.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

Handle cases where the latest resolvable previous version is the latest
version. This often happens if you don't have lockfiles and have
requirements update strategy set to bump_versions, where an update might
go from ^1.1.1 to ^1.1.2 (both resolve to 1.1.2).

JS: Fix cases where previous version the latest

---

bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb

In complicated resolution cases, Bundler's `VersionConflict` error class may not have all of the details required to determine which sub-dependencies to unlock. This is rare, but it can happen.
In such cases, the update will make it through the version resolver (which unlocks all sub-dependencies to check resolvability speedily) but fail during the FileUpdater's lockfile generation. That sucks.
This PR adds a fallback to lockfile generation:  if the above happens, attempt to unlock all sub-dependencies, like we do in the UpdateChecker.  This will result in a PR with a lot of sub-dependencies unlocked, but that's not so bad (top-level dependencies *won't* be unlocked, and this case is rare anyway).

Bundler: Fall back to unlocking all sub-dependencies in lockfile updater

---

python/lib/dependabot/python/file_parser.rb
python/spec/dependabot/python/file_parser_spec.rb
python/spec/fixtures/requirements/cascading_nested.txt

That. @rebelagentm we were going wrong with the test because the path dependency requirement line needed to come in a nested file.

Python: Handle nested path dependencies during parsing

---

python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_fetcher_spec.rb

Alternative to https://github.com/dependabot/dependabot-core/pull/1419.
Looking at https://github.com/aio-libs/aiohttp/issues/4122, I think we got this one wrong. Pip itself *doesn't* take into account the directory that nested requirement files are in - it  concatenates the cascading requirements into a single file and treats all of the lines as if they were written at that  level.

Revert Python file fetching change

---

npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/metadata_finder_spec.rb
npm_and_yarn/spec/fixtures/npm_response_string_shorthand.json

Documented [here](https://docs.npmjs.com/files/package.json#repository).
As reported by a user on Twitter.

JS: Handle GitHub shorthand links in MetadataFinder

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/file_updater.rb

While working on https://github.com/dependabot/dependabot-core/issues/390 (Support for docker-compose.yml files), I noticed that some regex expressions in the docker directory could be simplified.

Simplify regex expressions in docker parser/updater

---

Dockerfile
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

It's the current stable version, so we should be using it.

Upgrade to Go 1.13

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/update_checker.rb

It's causing issues with private dependencies, so let's switch it off for now and we can re-enable once we have a good strategy for setting the `GOPRIVATE` environment variable.
We don't need the `GO111MODULE` setting any longer, as it's on by default now.

Disable the Go module proxy

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb

This PR improves `LinkAndMentionSanitizer` so that it understands code fences with verbatim backticks which would normally derail the matching logic. Basically, the rule behind backtick code fences seems to be that the outermost delimiter is the one with most backticks, so we need to find the next occurrence with the same number of backticks in order to find the end of the code fence (see [spec](https://daringfireball.net/projects/markdown/syntax#precode), confirmed in GitHub comment editor preview).
Example:
````
``` => Verbatim backticks
````
Related to #1421 
cc @feelepxyz

Improve @mention sanitizer for for verbatim backticks in code blocks

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

Fix missing previous version when the dependency already has a git sha
version. This was being cleared out because of an unecessary semver
version class check.
Changing the return value of the resolved previous version to always be
a string which is the default behaviour when a previous version exists
without needing to be resolved from the requirements.

JS: Fix missing previous version when git sha

---

.devcontainer/devcontainer.json
.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
Dockerfile.development
README.md
bin/docker-dev-shell
bin/dry-run.rb
omnibus/Gemfile

This PR adds support in Dependabot for [Visual Studio Remote Development feature](https://code.visualstudio.com/docs/remote/containers), allowing devs to debug the app within the Docker development image. When starting a dry run debugging session, VS Code prompts for the package manager and a repo name.
See the [updated README](https://github.com/dependabot/dependabot-core/pull/1442/files#diff-04c6e90faac2675aa89e2176d2eec7d8) for usage instructions.
Debugging gems were added to `omnibus/Gemfile` in the `:development` group, which are then leveraged by the config in the new `.devcontainer/devcontainer.json` and `.vscode/launch.json` files.
The new `.vscode/extensions.json` file takes care of recommending the correct plugins for debugging with Ruby and supporting Remote Development.
The …

Add support for VS Code Remote Development on Docker

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/fixtures/changelogs/sentry.md

This PR fixes the failing test added by @greysteil in https://github.com/dependabot/dependabot-core/pull/1469. That PR can be closed once this one gets merged.
It improves the detection of [fenced code blocks](https://github.github.com/gfm/#fenced-code-block) by ensuring they start in a line boundary, and also improves detection of [code spans](https://github.github.com/gfm/#code-span) to not acknowledge ones that include empty lines.

Fix mismatched code span issue when sanitizing mentions

---

common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/fixtures/changelogs/sentry.md

Codeblock sanitization is hard. This PR adds another (currently failing) spec for it.
Connected to #1427.

Add failing spec for codeblock sanitization

---

.devcontainer/devcontainer.json
Dockerfile.development

This PR fixes a syntax error introduced in a7dafb5b5a75dc6d011eca93146176023967cac2, causing `LOCAL_GITHUB_ACCESS_TOKEN` to be initialized with a bogus value, instead of empty. It looks like the empty quotes are ignored by Docker, causing `LOCAL_CONFIG_VARIABLES` to become the value of `LOCAL_GITHUB_ACCESS_TOKEN`.
Note: for some reason, [this context](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb#L1838-L1856) seems to be failing, even on `master` and older releases. Most likely something in the CI is non-deterministic, since a7dafb5b5a75dc6d011eca93146176023967cac2 recently passed in [CI](https://circleci.com/gh/dependabot/dependabot-core/12615).

Fix Dockerfile.development syntax error

---

Dockerfile

Adding php7.3-cli explicitly seems to not trigger any 7.4 package installs.

Add php7.3-imagick dep to prevent 7.4 being installed

---

common/lib/dependabot/pull_request_creator/gitlab.rb

Gitlab api doesn't allow passing empty array for `approver_ids` or `approver_group_ids`. This leads to situation, when passing in approvers hash without `approver_group_ids`, request will fail with invalid approver_group_ids error.
Instead, if one of the 2 is not passed, it should be left as `nil`.

Don't pass empty array to update approvers gitlab method

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/fixtures/changelogs/jsdom.md

It seems that this commit introduced a regex pattern that would hang
indefinitely on some changelogs:
https://github.com/dependabot/dependabot-core/commit/ddf6a3ed55fda4a4247338a4ed95d2304726607b
Temporarily rollback the changes until we have a better fix in place. We
should probably switch to a legit markdown parser instead of rolling our
own.

Fix hanging regex in LinkAndMentionSanitizer

---

common/lib/dependabot/shared_helpers.rb

Seems we don't decompress gzipped responses in dependabot-core but we do
in the proxy which blocks debugging using the dry run script.

Decompress gzipped http responses

---

gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb
gradle/spec/dependabot/gradle/file_parser/property_value_finder_spec.rb
gradle/spec/fixtures/buildfiles/duplicate_property_name.gradle

In this [issue](https://github.com/dependabot/feedback/issues/698), the user had some variable names in code that matched the property name of the dependency.  When Dependabot parsed the `gradle.build` file, it would pick up the variable name, replacing the version value of the property with the variable name.  This caused Dependabot to skip over the dependency, as it didn't see it as valid.

Gradle: Skip name property if already present

---

common/lib/dependabot/file_fetchers/base.rb

In #1484  was reported a bug when trying to update `docker` dependencies using Gitlab.
At least with Gitlab 12, when a submodule is present the type returned is "commit".
Due to my practically nonexistent skills in Ruby I could't create any tests. I think there is no coverage for the `_gitlab_repo_contents` method and couldn't find any example to work with.

Fix Gitlab api types to match GitHub

---

maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb
maven/spec/dependabot/maven/update_checker_spec.rb

Previously, we parsed an HTML page looking for the name of a dependency to be present.  This was causing failures with Nexus repositories that were returning a non-browsable page.  This PR changes the logic to instead check the headers to see if the dependency exists.
Fixes https://github.com/dependabot/feedback/issues/746

Maven: Change logic to check if a version is released

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
npm_and_yarn/spec/fixtures/github/blob_js_tarball.json
npm_and_yarn/spec/fixtures/github/contents_js_tarball.json
npm_and_yarn/spec/fixtures/github/file_too_large.json
npm_and_yarn/spec/fixtures/github/package_json_with_tarball_path.json

Fetch tarballed path dependencies in the file fetcher.
https://docs.npmjs.com/cli/pack.html
Fixes: https://github.com/dependabot/feedback/issues/757

NPM and Yarn: Fetch tarball path dependencies

---

python/helpers/lib/parser.py
python/spec/dependabot/python/file_parser_spec.rb
python/spec/dependabot/python/requirement_parser_spec.rb
python/spec/fixtures/requirements/jinja_requirements.txt

Closes https://github.com/dependabot/feedback/issues/769.
When parsing python requirements files, ignore Jinja delimiters (e.g. `{{ }}`, `{% %}`, etc.). This provides the ability to update dependencies that are part of a [cookiecutter](https://github.com/cookiecutter/cookiecutter) project.

Support Jina templates in requirements files

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
cargo/spec/dependabot/cargo/file_parser_spec.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
cargo/spec/fixtures/manifests/virtual_workspace_root

Add a check to only write dummy target files if the manifest isn't a
virtual manifest (without `[package]` table).
When writing temporary manifest files we add a dummy `src/lib.rs` and
`src/main.rs` to satisfy Cargo's checks for a target src file.
If the top-level manifest is a virtual manifest (which doesn't require a
target lib/main file) and it has a workspace glob set to `src/*` Cargo
will attempt to read the dummy file as a directory failing to find
`src/lib.rs/Cargo.toml` as a result.

Cargo: Handle virtual manifests /w workspace glob

---

common/lib/dependabot/clients/codecommit.rb
common/spec/dependabot/clients/codecommit_spec.rb

Create `Aws::CodeCommit::Client` without any credentials if no
`git_source` credentials are provided. The client will default to using
AWS environment variables.
Fixes: https://github.com/dependabot/dependabot-core/pull/1399

Codecommit: Create client without credentials

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Fixes a regression introduced by
https://github.com/dependabot/dependabot-core/commit/6fa27f79834e2ed7a84e7d2565492115854b13f8
When a path dependency is a tarball it shouldn't be fetched as a
package (appending/package.json to the end assuming it's a directory).
Commit #6fa27f79834e2ed7a84e7d2565492115854b13f8 only handled the
initial fetch but not the retry which caused an infinite retry loop as
the path dependency was re-fetched with path.tgz/package.json after each
time it wasn't found as path.tgz.

JS: Fix unfetchable tarball path deps ∞ loop

---

python/helpers/lib/parser.py
python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/file_parser/setup_file_parser.rb
python/lib/dependabot/python/file_updater/requirement_replacer.rb
python/lib/dependabot/python/name_normaliser.rb
python/spec/dependabot/python/file_parser_spec.rb
python/spec/dependabot/python/file_updater/requirement_file_updater_spec.rb
python/spec/dependabot/python/file_updater/setup_file_sanitizer_spec.rb
python/spec/fixtures/requirements/version_specified.txt

This fixes an issue with a setup.py + requirements.txt setup where extras (defined in square brackets as part of a dependency name) are ignored and therefore lost in the parsing stage (i.e. https://github.com/dependabot/dependabot-core/issues/1517). Now we keep the information with the dependency for as long as we can and switch between including it in the name and not as appropriate.

Python extras fix

---

common/dependabot-common.gemspec
common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/gitlab.rb
common/spec/dependabot/pull_request_creator/gitlab_spec.rb
common/spec/dependabot/pull_request_creator_spec.rb

Gitlab API supports creating merge requests with multiple assignees for a while now.
* Pass all the assignees to merge request creator
* Bump ruby gitlab gem version

Pass all the assignees to gitlab merge request creator

---

common/dependabot-common.gemspec
common/lib/dependabot/pull_request_creator/message_builder.rb
common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
common/spec/fixtures/changelogs/jsdom.html

We had a bug reported where we weren't sanitizing the markdown footer in changelogs.  As @feelepxyz and I dove into fixing this, we realized a refactor of the `sanitize_links` method was in order.  Not only does it fix the bug, but it makes for a cleaner and more resilient method.

Refactor `sanitize_links` method

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/metadata_finder_spec.rb

This discrepancy caused the `SecurityAdvisory` class to fail when
comparing a `dep` version with a `go_modules` version:
https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/security_advisory.rb#L22
We have some code paths that fetch the version class from the dependencies
package manager and some fetch it from the [job package manager](https://github.com/dependabot/dependabot-updater/blob/master/lib/dependabot/updater.rb#L351).

Fix go modules package manager (was set to dep)

---

python/lib/dependabot/python/update_checker/latest_version_finder.rb
python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb

When a dependency includes extras (dep[extra]) in the name we should
strip these out when building a valid name regex.

Fix Python version finder with name extras

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

We don't yet support updating indirect dependencies for Go Modules.
Currently we attempt to update the indirect dependency but raise in the
file updater because no files where changed.
To update indirect dependencies we'll need to promote the indirect
dependency to the go.mod file forcing the resolver to pick this version.

Go Modules: Stop trying to update indirect deps

---

common/lib/dependabot/git_metadata_fetcher.rb
common/spec/dependabot/git_metadata_fetcher_spec.rb

Even in these modern ages I do have this gem in a git repository that
does not support HTTPS (yet). Currently the uri_with_auth always adds
"https://", which makes the service pack URI invalid. This change makes
sure it uses `http` if and only if the original scheme is HTTP.

Respect HTTP scheme for git dependencies

---

maven/lib/dependabot/maven/file_updater/property_value_updater.rb
maven/spec/dependabot/maven/file_updater_spec.rb
maven/spec/fixtures/poms/property_pom_single_attribute.xml

Because we update the properties via string substitution instead of editing the dom with nokogiri we can fail to update valid POMs that don't don't match what we expect, for example POMs where properties have attributes.
This will result in no substitution being performed, which then triggers an assertion:
```
uri@MacBook-Pro-108 ~/g/d/dependabot-core> bin/dry-run.rb maven canva/canva --dir parent
=> dumping fetched dependency files: ./dry-run/canva/canva/parent
=> updating 192 dependencies
=== com.google.googlejavaformat:google-java-format (1.5)
=> checking for updates
=> latest version from registry is 1.7
=> latest resolvable version is 1.7
=> requirements update strategy: 
=> updating …
```

Support attributes in maven properties.

---

maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/version_spec.rb

[Semver allows for build identifiers prefixed with a `+`](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions).  Currently, dependabot does not supports this.  This PR adds support.
Example: `1.0.0+100` or `1.0.0+build1`

[feature]Add Support for Semver Build Identifier in Maven

---

bin/dry-run.rb
common/lib/dependabot/update_checkers/base.rb

Currently unused. Will be used to only update vulnerable dependencies to
non-vulnerable versions and prevent updating currently non-vulnerable
versions.

Add security updates only to the update checker

---

common/lib/dependabot/pull_request_creator/branch_namer.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb

Looks like we're trying to put `[` characters in branch names, which are being rejected. Git's ref [validation logic](https://github.com/libgit2/libgit2/blob/559751714b23f63ead726e9a773be8b07e3551ae/src/refs.c#L898-L956) is quite complex so I didn't go all the way, but this should get us closer to fully-normalising the branch names we generate.

Cleaner branch names

---

hex/README.md
hex/helpers/build
hex/helpers/lib/parse_deps.exs
hex/spec/dependabot/hex/file_parser_spec.rb
hex/spec/fixtures/lockfiles/hex_version_0_20_2

Hello,
Recently hex was updated and new mix.lock file format is not supported by Dependabot. I prepared a fix for that. It also fixes #1675

Fix Elixir support for new mix.lock format

---

hex/helpers/lib/parse_deps.exs
hex/spec/fixtures/lockfiles/hex_version_0_20_2

Hex may add more lock entries in the future, make sure to only parse the
ones we know about now.
From https://github.com/dependabot/dependabot-core/pull/1680/files#r376408834.

Future proof Hex lock parsing

---

common/lib/dependabot/pull_request_creator/codecommit.rb

Currently, dependabot will happily open a PR against a codecommit repo that requires updates, but fails to actually include the updated file and associated commit in the PR.. this should fix that.

Ensures codecommit client actually creates a commit before opening a PR

---

bin/dry-run.rb
common/spec/dependabot/clients/github_with_retries_spec.rb
common/spec/dependabot/clients/gitlab_with_retries_spec.rb
hex/lib/dependabot/hex/update_checker/requirements_updater.rb
maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/version_spec.rb

The version comparison logic was broken in the Maven Version.rb file.  The `PREFIXED_TOKEN_HIERARCHY` did not list `+` as a valid key.  The Maven documentation site listed did not provide any guidance on how to handle `+` so I chose some sane values for `qualifier` and `number`.
I added some tests to test comparison with plus signs.  Please let me know if additional testing is needed.

Fix Semver Build Identifier Support

---

common/lib/dependabot/update_checkers/base.rb
common/spec/dependabot/update_checkers/base_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
npm_and_yarn/spec/fixtures/package_files/peer_dependency_typescript.json

Previously when we knew that a newer version was available in the
registry, we didn't correctly mark the dependency as out of date.
`UpdateChecker#requirements_up_to_date?` was first checking if any
dependencies were actually updated, but this check is already happening
in `#can_update_requirements?`, and this was causing us to miss cases
when a new version was _available_ but not possible to update.
Concretely this means that we show a better error when these updates
fail, previously we would mark them as no update needed and now we mark
them as no update possible.

Correctly mark requirements as not up to date

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

We do not need to sanitize github links when creating PR's outside of
GitHub.
Some providers don't support HTML rendering, this change correctly
respects that.
Fixes https://github.com/dependabot/dependabot-core/pull/1715

Improve PR descriptions for non-github PR's

---

bin/docker-dev-shell

This makes it easier to run the dry-run script in docker and make
changes to the dependencies etc we're running the script against.

Mount dry-run folder in docker dev shell

---

maven/lib/dependabot/maven/requirement.rb
maven/spec/dependabot/maven/requirement_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb

* Add support for semver 2.0 build meta data.
* Update logic in determining wildcard versions to key off of ending in `+`

Update Maven Requirement

---

bin/docker-dev-shell
python/helpers/lib/hasher.py
python/helpers/requirements.txt
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb

Upgrades Dependabot to using Poetry v1. This is backwards compatible with existing lockfiles, while supporting the new lockfile features introduced in v1.
This is based on #1710, but also:
- upgrades `python/helpers` test fixtures
- changes tests fixed by the upgrade from `pending -> it`

python: upgrade to poetry ^1.0.0

---

go_modules/helpers/updatechecker/main.go

In the `go_modules` helper `UpdateChecker`, dependabot fetches the available remote versions  before interrogating the target version with a regular expression.
Doing the regular expression check before fetching versions has the same postcondition with less (wasted?) network overhead.

go_module: early exit UpdateChecker

---

common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_updater/github_spec.rb
common/spec/fixtures/github/unauthorized_push_protected_branch.json

When you restrict who can push to protected branches a different error
message is returned compared to pushing to a branch that only disables
force-pushes.

Handle unauthorized pushes to protected branches

---

nuget/lib/dependabot/nuget/update_checker/requirements_updater.rb
nuget/spec/dependabot/nuget/update_checker/requirements_updater_spec.rb

Changed `gsub` to `sub`. I don't think it makes sense to `gsub` as there
shouldn't be multiple of the same version in the requirement.
Fixes https://github.com/dependabot/feedback/issues/906

Nuget: Handle version requirements with prefix

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
README.md

Unfortunately we're not able to respond as quickly to feedback as we'd
like, let's inform users of this.

Add notices about slow response times to README and Issue templates

---

bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/fixtures/ruby/gemfiles/git_source_with_version

https://github.com/gocardless/business/releases/tag/v1.18.0
This breaks a bundler test that expects the latest version.
This is a blind patch w/o much consideration for what the test is doing.

business-1.18.0

---

bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb
bundler/spec/dependabot/bundler/file_updater/gemspec_sanitizer_spec.rb

Gems generated by `bundle gem` dynamically generate their `spec.files` by shelling out to `git ls-files`, inside a `Dir.chdir` block ([see here](
https://github.com/rubygems/rubygems/blob/9cfc95d9d9eeede71884a25ade8851b7ab722011/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L25-L27)).
Dependabot was unable to update our dependencies because of this call.
```
There was an error while loading `our-private-project.gemspec`: No such file or directory @ dir_chdir
```
Currently, gemspec sanitization replaces dynamic `files` assignment with an empty array by searching for an AST node that looks like this:
```
s(:send,
s(:lvar, :spec), :files=,
s(:send, ...))
```
However, because `Dir.chdir` receives a [literal block](https://github.com/whitequark/parser/blob/68c21e247fde370fae7640fdc3bb6 …

Sanitize Dir.chdir calls in gemspecs

---

gradle/lib/dependabot/gradle/update_checker/version_finder.rb
gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb
gradle/spec/fixtures/maven_central_metadata/with_version_type_releases.xml
gradle/spec/fixtures/poms/with_version_type_releases.xml

Fixes a bug in Gradle that would not match version types when additional context is provided.
For example: com.thoughtworks.xtream:xstream:1.4.11-java7
Now, the system will obey the version type that the user provides, maintaining the correct version types for future upgrades.

fix: Fix version types in gradle to allow matching postfixed version types

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/go_mods/upgraded_indirect_dependency.mod

Fixes an issue in our Go modules support where we'd fail to remove lines from the go.mod that because unnecessary due to a Dependabot version update.
Reviewer notes:
- To understand the problem this solves, it may be beneficial to start with the first commit, which adds a failing test.
- Reorganizes a bit of code (class constants, attr_reader), which creates some visual noise in the diff. Sorry about that.
Previously, we'd:
1. Add the new dependency versions to the go.mod
2. If a go.sum was present, run `go get` to update the go.sum
Sometimes the new dependency requirement should change other entries in the go.mod. For instance, say we use dependency x@v1, which depends on y@v1. We upgrade y to v2 manually in the go.mod, which promotes y@v2 to the go.mod. Dependabot kicks in and then …

go modules: remove unnecessary requirements

---

common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_updater/github_spec.rb
common/spec/fixtures/github/linear_history_protected_branch.json

You can enforce linear history for a protected branch preventing any
merge commits to be pushed to the branch, this currently prevents the
pull request from being updated. I'm not entirely sure where we're
creating a merge commit but might be because we're creating a new commit
and force pushing and this is the first rule that gets tripped up in
github.
`BranchProtected` is rescued in dependabot api resulting in a comment on
the pull request explaining why the update failed.

Handle protected branches enforcing linear history

---

bin/docker-dev-shell

I expected `git pull && bin/docker-dev-shell --rebuild` to provide me with a suitable sandbox for development.
Since `Dockerfile.development` references `dependabot/dependabot-core:latest`, changes to helpers aren't included unless I manually rebuild.
This PR updates `bin/docker-dev-shell` to rebuild `dependabot/dependabot-core:latest` whenever the developer shell image is being rebuilt.
Thanks to docker's layer cache, this costs `<1s` if there's no work to be done. Worth it to trivialize synchronizing the dev sandbox.

docker-dev-shell: rebuild core

---

common/lib/dependabot/pull_request_creator/labeler.rb
common/spec/dependabot/pull_request_creator/labeler_spec.rb
common/spec/fixtures/github/labels_with_custom_and_default.json

Fixes https://github.com/dependabot/feedback/issues/846
This change makes sure an existing label named `dependencies` is always
used as the default over one that matches `*dependenc.`.
When a repo label exists that matches `*dependenc.` Dependabot will pick
and use that as the default label (unless you specifcy default/custom
labels).

Always use exact dependencies label if one exists

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/fixtures/go_mods/parent_module.mod

This PR updates the regular expressions used to parse `go` command output to handle errors encountered processing transitive dependencies.
When go encounters an error resolving a direct dependency, it outputs an error like:
```
go: github.com/hmarr/404@v1.4.0: reading github.com/hmarr/404/go.mod at revision v1.4.0: unknown revision v1.4.0
```
When go resolves a direct dependency, then fails resolving a transitive dependency-of-a-dependency, it outputs an error like:
```
go: github.com/dependabot/vgotest@v1.0.0 requires
github.com/hmarr/404@v1.0.0: reading github.com/hmarr/404/go.mod at revision v1.0.0: unknown revision v1.0.0
```
That `\n\t` breaks dependabot's regexp, which is used to detect and retry on ephemeral errors (e.g. a 502 from a remote).
This results in a …

go_modules: multiline `go` output matching

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb

This PR adds an extra condition to parsing output from the `composer` helper.
If the output begins with "Out of memory", raise as a `Dependabot::OutOfMemory`.

composer: reraise OutOfMemory

---

hex/spec/dependabot/hex/file_parser_spec.rb

It seems like we can no longer pass an `exception` as a plug /
dependency, hex will raise an `ArumentError`, which kind of makes sense.

Fix failing hex file parser spec

---

bundler/spec/dependabot/bundler/file_updater/gemfile_updater_spec.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker/file_preparer_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb
bundler/spec/fixtures/git/upload_packs/dependabot-test-ruby-package
bundler/spec/fixtures/ruby/gemfiles/git_source_with_version
bundler/spec/fixtures/ruby/lockfiles/git_source_with_version.lock

We rely on the `business` gem for these tests, which recently got a [2.0
upgrade], which breaks these tests.
This is the simplest thing we can do to fix those tests, but I would
recommend that we swap out these public gems for dummy / cloned versions
that we can pin to a specific version.
[2.0 upgrade]: https://github.com/gocardless/business/blob/master/CHANGELOG.md#200---may-4-2020

Update tests to account for business 2.0 update

---

bin/docker-dev-shell

This PR updates the `docker-dev-shell` script to fix a misconfiguration that specifies the `--rebuild` accepts an argument.
The `getopt` baked into OSX doesn't mind this, but `util-linux-2.33.1.0.1` fails.
Per https://linux.die.net/man/1/getopt
```
Each long option name in longopts may be followed by one colon to indicate it has a required argument, and by two colons to indicate it has an optional argument.
Each short option character in shortopts may be followed by one colon to indicate it has a required argument, and by two colons to indicate it has an optional argument.
```

docker-dev-shell --rebuild no args

---

common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb
common/spec/fixtures/azure/commits_no_author_email.json

Azure deploy user and Collection Build Service can commit to repository without having an email address. `last_azure_dependabot_commit_message` and `recent_azure_commit_messages` methods are failing with key not found error if repository has one of those commits. This commit fixes the issue

Fix failing non-existing author email

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
cargo/spec/fixtures/manifests/linked_dependency

Previously, when specifying a native dependency using `links =
"dependency"`, we would fail as we do not copy over the build.rs file,
which is needed to actually link to the binary. However, to run `cargo
update` we don't actually need to link the dependency, we just need
cargo not to fail. So adding a dummy build.rs file, like we do for
src/main.rs fixes the issue.
Fixes: https://github.com/dependabot/feedback/issues/943

Handle cargo native dependencies

---

.gitignore
bin/docker-dev-shell

This adjusts the `bin/docker-dev-shell` helper script to provide a persistent `~/.bash_history`, allowing the history to persist across invocations.
I opted for a `.gitignore`-ed file in the working directory; a docker volume might have been cleaner - but more work for whats just a papercut.

docker-dev-shell: mount .bash_history

---

gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb
gradle/spec/dependabot/gradle/file_parser/property_value_finder_spec.rb
gradle/spec/fixtures/buildfiles/properties.gradle
gradle/spec/fixtures/buildfiles/properties_namespaced.gradle

Extract properties set as defaults, supports both the findProperty and hasProperty syntax styles:
```
findPropertyVersion = project.findProperty('findPropertyVersion') ?: '1.0.0'
hasPropertyVersion = project.hasProperty('hasPropertyVersion') ? project.getProperty('hasPropertyVersion') :'1.0.0'
```

Gradle: Add support for properties set as defaults

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb

Many moons later, after quite some investigation and unfortunately after @keirlawson left the team, we managed to find out what the issue was and add a fix.
Basically what is/was happening is that in the absence of a `.npmrc` file (our default case in most repositories) dependabot creates a temporary one at runtime but it always creates it in the root folder of the project rather than in the working directory where the `package.json` is located and where the `npm:update` command is run which, in some cases, like in our setup, could be in subfolders.
I hope it helps.

#1231: Create .npmrc file in the current working directory

---

common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_updater/github_spec.rb
common/spec/fixtures/github/force_push_this_protected_branch.json

Relaxing the error message check to raise a `BranchProtected` error when
the API error includes the words `protected branch`.
When force pushing to a protected branch the error can have two forms:
- Cannot force-push to this protected branch
- Cannot force-push to a protected branch

Updating PR: Handle new protected branch error

---

common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb

Fixes https://github.com/github/dsp-dependabot/issues/280
Looks like the repo can be removed by the time we try to create the PR.
This is currently raising preventing the PR creation from gracefully
handling the missing repo.

Handle missing repo when fetching recent commits

---

.vscode/settings.json
nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/file_parser/property_value_finder.rb
nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
nuget/spec/dependabot/nuget/file_parser/property_value_finder_spec.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/fixtures/csproj/directory.packages.props
nuget/spec/fixtures/property_files/directory.packages.props

This adds in support for the new `<PackageVersion />` element added for the nuget implementation of [Centrally managing NuGet package-versions](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions)
The latest dotnet sdk (3.1.300) includes support for the new `Directory.Packages.props` file from the command line, it follows very similarly to the `<PackageReference Update="" />` syntax, just using `<PackageVersion Include="" />` instead.

Added support for <PackageVersion> elements for MSBuild projects

---

python/lib/dependabot/python/requirement_parser.rb
python/spec/dependabot/python/file_updater/requirement_file_updater_spec.rb
python/spec/dependabot/python/requirement_parser_spec.rb
python/spec/fixtures/requirements/markers_and_hashes_multiline.txt

Hashes are ignored when environment markers are present because the regex used for parsing doesn't take into account environment markers.
Adding them to the regex allow proper parsing of hashes when environment markers are present.
RegExp inspired from https://www.python.org/dev/peps/pep-0508
Fix #1587

[Python] Add parsing of environment markers

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb

When configured as UNSAFE, CommonMarker will leave in any HTML tags
present in the text, which can cause our markdown to break when rendered
by GitHub.
This change ensures that no unsafe attributes are included in the
output, but things like `<code>` blocks for usernames etc still continue
to work.

Safely output markdown from link_and_mention_sanitizer

---

github_actions/.gitattributes
github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb
github_actions/spec/fixtures/vcr_cassettes/Dependabot_GithubActions_UpdateChecker/_latest_version/given_a_dependency_with_multiple_git_refs/1_3_4_1.yml
github_actions/spec/fixtures/vcr_cassettes/Dependabot_GithubActions_UpdateChecker/_updated_requirements/with_multiple_requirement_sources/1_5_4_1.yml
github_actions/spec/fixtures/workflow_files/multiple_sources_matching_major.yml

Fixes the regex matching the old actions declaration to only match the
declaration if it's proceded by a space or EOL.
Previously if the same action was used with multiple tags where the
major version matched both, e.g.
```yml
actions/cache@v1
actions/cache@v1.1.1
```
The first `step` update would replace both, meaning the second `step` update would no
longer match the old declaration (v1.1.1):
```yml
actions/cache@v1
actions/cache@v2.1.1
```
Future note: Would be nice to refactor the Actions file updater to
manipulate the YAML structure instead but will be tricky to maintain the
formatting.
Fixes https://github.com/dependabot/feedback/issues/965

Actions: Fix multiple sources matching major vers

---

gradle/lib/dependabot/gradle/update_checker/version_finder.rb
gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb

Despite the [docs](https://dependabot.com/docs/config-file/#ignored_updates), which say that ignored updates should match the package manager, it looks like Maven & Gradle ranges have always been implemented using Gem’s pattern.
I’m not 100% confident that this will fix the actual issue with `config.yml`, since the implementation that parses that file into a Dependabot run doesn’t seem to be open source.
fixes #1845

Use Maven version ranges for ignored_versions in Maven and Gradle

---

nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb

Fix `NoMethodError` when a NuGet package defined in a `Directory.Packages.props` file needs updating.
It looks like the support added in #1880 missed updating the `get_element_from_node` function to expect the `PackageVersion` node.
I noticed this in my dependabot logs after updating some of my repositories to use central NuGet package management (https://github.com/martincostello/alexa-london-travel/pull/256 is one example).
I did try trying to write an integration test for this by updating the `property_value_updater_spec` to include a `.csproj` that defined a `<PackageReference Include="Foo" />` element (note that there's no `Version` attribute because it's centrally defined) to replicate the error before applying what I think is the fix, but I'm not very familiar with Ruby and …

Fix NoMethodError when updating NuGet packages from Directory.Packages.props

---

cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb

The layout of the error seems to have changed slightly in the latest
version of Cargo.

Fix cargo requirement message in specs

---

composer/helpers/composer.json

Fix: Do not bother using array

---

composer/helpers/composer.json
composer/helpers/phpstan.neon

This PR
Slightly related to #2338.

Fix: Configure phpstan level via phpstan.neon

---

python/spec/fixtures/setup_files/with_parse_reqs.py

`PipSession()` and `parse_requirements()` are both used on line 5 but they are not defined or imported which may raise a `NameError` at runtime.
* https://github.com/pypa/pip/blob/master/src/pip/_internal/network/session.py#L228
* https://github.com/pypa/pip/blob/master/src/pip/_internal/req/req_file.py#L127

Undefined names: import PipSession and parse_requirements

---

python/lib/dependabot/python/file_updater/pyproject_preparer.rb
python/spec/dependabot/python/file_updater/pyproject_preparer_spec.rb
python/spec/fixtures/pyproject_files/path_dependency.toml
python/spec/fixtures/pyproject_locks/path_dependency.lock

This fix was proposed by @jtbeach in in https://github.com/dependabot/dependabot-core/pull/1788 and fixes https://github.com/dependabot/dependabot-core/issues/1771.
When specifying a path dependency in Poetry, we should not try to lock the version of the dependency.

Don't freeze poetry path dependency version

---

github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb
github_actions/spec/fixtures/workflow_files/workflow.yml

[github_actions] Fix: Update references to actions when they are single- or double-quoted strings

---

.github/workflows/ci.yml

This PR adds the matrix that @localheinz added in #2372 and also uses the github package registry of whatever repository the PR comes from in order to share the docker file between different CI jobs.

CI: Build matrix and use package registry for CI image

---

.github/workflows/ci.yml

This PR
🙈 I missed this in e32df23ef, sorry!

Fix: Add github_actions to job matrix

---

composer/helpers/composer.json
composer/helpers/composer.lock

[composer] Fix: Explicitly require latest stable version of composer/composer

---

.github/workflows/ci.yml
Rakefile

Cleaning up the actions workflow file. Removing the rakefile ci tasks and using a matrix build instead to make it concurrent.

Run rubocop in matrix and stop fetching docker ci image

---

.github/workflows/ci.yml

When running in ci also build `Dockerfile` to re-build native helpers.

Build main dockerfile in ci

---

python/lib/dependabot/python/authed_url_builder.rb
python/spec/dependabot/python/authed_url_builder_spec.rb

If a password contains an `@` sign, when we construct a URL with it, it
will result in an invalid URL, since we now have multiple `@` signs,
resulting in the URL parser not being able to determine where the
password stops and the address begins.

Encode '@' in python HTTP basic auth passwords

---

.github/workflows/ci.yml

Push a `latest` tag to the ci image and build ci from that cache.
[Existing build time](https://github.com/dependabot/dependabot-core/runs/945555472):
- fetch cache: 1m 30s
- core: 12s
- ci: 9m 23s
[New build time](https://github.com/dependabot/dependabot-core/pull/2415/checks?check_run_id=945981526)  (when everything is already cached):
- fetch cache: 1m 53s
- core: 13s
- ci: 1s 🎉 🙌

Build docker with cache

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

When dealing with an indirect gomodules dependency, we were retuning a
string value that came from the Dependency object. We use this version
to compare with a Dependency object in
common/lib/dependabot/update_checkers/base.rb:216, which resulted in an
ArgumentError. We already return a Version object when the dependency is
top_level.

Always return a Version object for indirect gomodule dependencies

---

common/lib/dependabot/shared_helpers.rb

This PR increases the read timeout used for HTTP connections.
This is a specific problem for `npm_and_yarn` ecosystem + GitHub Package Registry. It could be scoped tighter.
It doesn't seems a crazy default? The connect timeout seems more important (to avoid waiting for private/LAN registries that we can't reach).

common: increase default http client read timeout

---

.github/workflows/ci.yml
.github/workflows/docker.yml
Dockerfile.ci
bin/docker-dev-shell

Fix caching for the ci image build using buildkit. This was previously failing because docker build seemed to just hang when building the ci image with `DOCKER_BUILDKIT=1`. Not sure why yet, thought it might have something to do with this bug: https://github.com/moby/buildkit/issues/1123 but doesn't seem like it, my current theory is that the previous Dockerfile.ci had too many layers and exporting the cache timed out.
Previously we where just using `--cache-from image` without the inline buildkit cache which seemed to result in super fast builds that didn't rebuild when stuff changed. Builds would only take 1s even though some helper manifests had changed.
Verified the build cache seems to be working by upgrading pip here (which includes a breaking change) …

CI: fix docker cache

---

Dockerfile
Dockerfile.ci
Dockerfile.development

This PR
💁‍♂️ There currently is no specific rule for `Dockerfile`s to be indented with anything other than 2 spaces, see [`editorconfig`](https://github.com/dependabot/dependabot-core/blob/6b5a42e35ef400f63544ed8d26030af6bd1b3fba/.editorconfig).

Fix: Consistently indent Dockerfiles with 2 spaces

---

python/lib/dependabot/python/authed_url_builder.rb
python/spec/dependabot/python/authed_url_builder_spec.rb

Both the username and password may contain characters that are not valid
in HTTP basic auth, we want to escape both, and will assume that the
first colon is what should be split on.

Properly escape both username and password in auth url

---

.github/workflows/docker.yml

This appends the `docker.yaml` workflow to:
- be triggered when a tag is pushed
- if triggered from a tag, push `dependabot/dependabot-core:$VERSION` after `dependabot/dependabot-core:latest`
For reference, the release process pushes a commit to the default branch and a tag in rapid succession: https://github.com/dependabot/dependabot-core/blob/main/bin/bump-version.rb#L50-L54
We _could_ have just pushed `:$VERSION` on every build, but this approach keeps tagged images ~immutable.

actions docker.yaml: publish tag ontag

---

.github/workflows/docker.yml

This fixes a regression introduced by #2431 that blocks _all_ docker publishing.
The YAML editor didn't mind, and Actions apparently doesn't validate syntax until the workflow is _triggered_  (e.g. when the previous PR was merged to main, it [didn't work](https://github.com/dependabot/dependabot-core/actions/runs/199385282) ).
To verify this syntax, I forced this YAML to be evaluated and verified the runner interprets the workflow as expected: https://github.com/dependabot/dependabot-core/actions/runs/199413936
- Continues #2431

docker.yaml syntax fix

---

.github/workflows/docker.yml
.github/workflows/gems.yml

AFAICT `create` events aren't filtered like `push|pull_requests` events are.
We can see this as the `Release gems` triggering more frequently than expected: https://github.com/dependabot/dependabot-core/actions?query=workflow%3A%22Release+gems%22 
- special snowflake: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
- same assumption: https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/22

on: create: tags filtering does not work

---

common/lib/dependabot/dependency_file.rb
common/spec/dependabot/dependency_file_spec.rb

A very minimal change to `DependencyFile` to allow us to specify wether files are binary and/or deleted.

Add binary and deleted properties to dependency_file

---

common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_updater/github_spec.rb

Same changes as for the Creator. A bunch of this code should be pulled
out and shared so we wouldn't have to duplicate the logic like this.

Support binary and deleted files in PR Updater

---

common/lib/dependabot/pull_request_creator/github.rb
common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_creator/github_spec.rb
common/spec/dependabot/pull_request_updater/github_spec.rb

Always check if the file was deleted before checking if it was binary,
so we delete files either way.

Handle deleting binary files

---

common/lib/dependabot/file_fetchers/base.rb
common/lib/dependabot/file_parsers/base.rb
common/lib/dependabot/file_updaters/base.rb
common/lib/dependabot/update_checkers/base.rb

Adding a unused attribute to be able to test multiple versions of core
from the updater.

Add repo_contents_path attribute

---

cargo/lib/dependabot/cargo/file_updater/manifest_updater.rb
cargo/spec/dependabot/cargo/file_updater/manifest_updater_spec.rb
cargo/spec/fixtures/manifests/version_in_name

We do a rather straight-forward regex replace on Cargo versions,
however, we did not take into account that the dependency name can
include the the version string. In order to avoid this, we only change
the part of the string after the `=` mark.

Only replace version part of cargo line

---

python/helpers/requirements.txt
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb

A change in poetry 1.0.10 has changed how the `git clone` operation is performed. It now includes the `--recurse-submodules` option which wasn't there previously. This PR should superseed #2407.

Update to poetry to 1.0.10

---

.rubocop.yml
bundler/.gitignore
bundler/lib/dependabot/bundler/file_updater.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/fixtures/projects/vendored_git/Gemfile
bundler/spec/fixtures/projects/vendored_git/Gemfile.lock
bundler/spec/fixtures/projects/vendored_git/vendor/cache/dependabot-test-ruby-package-81073f9462f2/README.md
bundler/spec/fixtures/projects/vendored_git/vendor/cache/dependabot-test-ruby-package-81073f9462f2/test-ruby-package.gemspec

This extends https://github.com/dependabot/dependabot-core/pull/2476 with a test case demonstrating updating a vendored git dependency.

bundler vendoring: git sources

---

bundler/dependabot-bundler.gemspec
bundler/lib/dependabot/bundler/file_updater.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb

This extends #2476 to avoid base64 encoding files that are probably not binary.
This is important because of how the `PullRequestCreator::GitHub` [creates PRs](https://github.com/dependabot/dependabot-core/blob/f9ee541691b91f76308a972bb535d40443bce33f/common/lib/dependabot/pull_request_creator/github.rb#L173-L182). Since binary files are created as blobs, a PR that updates many files (e.g. a vendored git dependency #2479 ) would have a slow sequential upload process.
We'd prefer to batch content as much as possible within the `POST /repos/:owner/:repo/git/trees` call.
The trade-off of this approach is the growing size of that API call, I couldn't find any documented limits just some [reports](https://github.community/t/creating-new-tree-with-git-data-api-returns-502/1320/5) of potential …

bundler vendoring: detect non-binary extensions

---

Dockerfile.development

Since #2476 , docker dev tests have required a git author be set.
This PR copies the `Dockerfile.ci` setup so developers don't have to configure this manually.

Dockerfile.dev: set git author

---

cargo/lib/dependabot/cargo/update_checker/version_resolver.rb

In cargo 1.45.0 the message we were matching against was:
```
Updating crates.io index
Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 (/home/dependabot/dependabot-core/cargo/tmp/dependabot_20200902-3407-1pi6vdm)`
Caused by:
failed to load source for dependency `utf8-ranges`
Caused by:
Unable to update https://github.com/BurntSushi/utf8-ranges#11111b37
Caused by:
revspec '11111b376b93484341c68fbca3ca110ae5cd2708' not found; class=Reference (4); code=NotFound (-3)
```
In cargo 1.46.0 this has been changed to:
```
Updating crates.io index
Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 …
```

Support cargo 1.46.0 ref not found message

---

github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

If an action is pinned to a commit, this is most likely as a security precaution, so always update pinned commits to the commit hash corresponding to the latest tag.
Fixes https://github.com/dependabot/dependabot-core/issues/2470.

Don't downgrade a pinned commit to a tag.

---

Dockerfile

https://elixir-lang.org/blog/2020/01/27/elixir-v1-10-0-released/

Upgrade elixir/mix to 1.10.0

---

common/lib/dependabot/clients/azure.rb
common/spec/dependabot/clients/azure_spec.rb

**Issue**
Currently, `azure_client` supports only `basic authentication` using `username` and `password`. For our service, which we have built on top of dependabot-core, we require support for `OAuth` tokens in `azure_client`. We found this as something which we could contribute back to dependabot-core hence creating this PR.
**Solution**
For enabling authentication using tokens, it will be expecting a separate field named `'token'` in the `credentials` hash instead of `username` and `password`. Using the token, it will decide on the `authorization headers` for the `Excon` request in the same manner as it is done for connecting to registries in dependabot-core. For e.g 
https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_ …

Add OAuth support in azure client

---

common/lib/dependabot/clients/azure.rb

**Issue**
While running dependabot-core on a `AzureDevOps repo`, it failed to create PR for dependency update with error **`PR description limit exceeded (Description limit cannot be more than 4000 characters)`**. However, to avoid this error, `create_pull_request` function in `azure_client` checks whether the `pr_description length` is greater than the `permissible limit ( i.e currently 4000 characters)` and accordingly trims the description.
https://github.com/dependabot/dependabot-core/blob/f4cf8cfdcc44fa4f309af2df264a3dabe7ee5b7b/common/lib/dependabot/clients/azure.rb#L160
**Cause**
The error was caused due to a `special unicode character` i.e 🎉 which occured multiple times in the PR description. In `UTF-8 encoding`( used in dependabot-core) this character has length `1` whereas in …

Fix for PR description limit issue for AzureDevOps(ADO)

---

Dockerfile

Bumps the bundled version of elixir from `v1.10.0` to `v1.10.4`.
https://github.com/elixir-lang/elixir/blob/v1.10/CHANGELOG.md#v1104-2020-07-04

Elixir 1.10.4

---

common/spec/spec_helper.rb
python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_fetcher_spec.rb
python/spec/fixtures/github/requirements_with_path_dependencies.json

This should fix https://github.com/dependabot/dependabot-core/issues/1977
This PR updates the regex in Dependabot::Python::FileFetcher.parse_path_setup_paths to ignore if there is a `file:` at the beginning of the requirement path.

Fix python path dependencies with file

---

nuget/lib/dependabot/nuget/metadata_finder.rb

Windows has a history of using UTF-16, recent versions of windows
default to UTF-8, but we sometimes encounter files that are encoded as
UTF-16. When trying to regex match on such a string, we get an error:
```
incompatible encoding regexp match (US-ASCII regexp with UTF-16 string)
```
By enforcing the encoding we should be able to prevent this.

Force encode nuspec files to utf-8 for regex matching

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
common/spec/dependabot/pull_request_creator/message_builder/metadata_presenter_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

We've encountered PRs where the Change Log notes have been truncated without any indication there is more content, leading to some confusion.
On investigation, we discovered that in an attempt to fix any table structures we have broken by truncating by line number we add a closing table table as part of the truncation line.
We rely on a later sanitisation set to remove this tag it if is not required, i.e. malformed, but this sanitisation currently removes the entire line including the truncation notice.
The fix itself is trivial, [we just insert a new line after the closing table tag](https://github.com/dependabot/dependabot-core/commit/7d1b1a7beb8d833c4baa0ca4ad3872cb19ca1fb1) and the sanitisation process works as intended.
The challenge of this PR was extracting a testable surface as …

Fix missing truncation notice on GitHub PRs

---

.rubocop.yml
common/lib/dependabot/clients/azure.rb
common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/azure.rb
common/spec/dependabot/pull_request_creator/azure_spec.rb
common/spec/dependabot/pull_request_creator_spec.rb

This PR adds the ability to link work items when create a pull request in Azure DevOps.
The API is pretty forgiving, and allows the JSON `"workItemRefs": [{"id": null}]`
API docs: https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/create?view=azure-devops-rest-5.0

Allow Azure client to set linked work item

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/github.rb
common/spec/dependabot/pull_request_creator/github_spec.rb

PullRequestCreators like `GitHub` separate the creation of PRs from
labelling, assigning reviewers, etc.
Since creating a pull request is a very noticeable side-effect for
customers, we'd prefer to throw an exception that attaches the 
half-completed PR, giving callers a hook for recovery.
An alternative would be _deleting_ the "failed" PR if annotation fails. Assuming PR creation is retried, I avoided that to squelch the `opened->closed->opened` noise.

PullRequestCreator::AnnotationError

---

python/lib/dependabot/python/update_checker.rb
python/spec/dependabot/python/update_checker_spec.rb

This PR continues https://github.com/dependabot/dependabot-core/pull/2557 , resolving another extra redirect and removing some pressure from Dependabot operating against `pypi.org.`

Add trailing slash to pypi index request

---

common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb

Fix `SharedHelpers.excon_defaults` when merging extra headers.
Extra `headers` passed in as an argument would always override the
default `excon_headers` that sets the `User-agent`, e.g.:
```
SharedHelpers.excon_defaults(
headers: { "Accept": "text/html" }
)
{
...,
headers: { "Accept": "text/html" }
}
```
It will now return:
```
{
...,
headers: { "Accept": "text/html", "User-Agent": "dependabot/..." }
}
```

Fix excon_defaults extra headers

---

python/lib/dependabot/python/file_parser/pipfile_files_parser.rb
python/spec/dependabot/python/file_parser/pipfile_files_parser_spec.rb
python/spec/fixtures/pipfiles/empty_requirement

Dependabot doesn't allow the `Dependabot::Dependency`
requirements.requirement string to be a blank string.
Pip treats `""` equal to `"*"` so we can set this when building the
`Dependabot::Dependency` object.

Handle empty pipfile requirement string

---

bin/docker-dev-shell

Modifies `bin/docker-dev-shell` helper to use a fixed container name, and reuse the container when it's already running.
This is a papercut: I'm usually `docker exec`-ing in to check out a tempdir while sitting in a breakpoint.

re-entrant docker-dev-shell

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb

This branch extracts a preamble refactor for https://github.com/dependabot/dependabot-core/pull/2552 that drops all the points where we call out to Bundler in `LatestVersionFinder` into a subclass.
This leaves `LatestVersionFinder` responsible for filtering versions returned from the `DependencySource` according to `ignored_versions` and `security_advisories` and creates a seam that will allow us to swap out the DependencySource implementation with one that shells out and ultimately returns the same output.
I've left tests as-is apart from adding some to document existing behaviour, I may extract some more specs on the `DependencySource` as a follow-up PR.

[Bundler] Extract a DependencySource class from LatestVersionFinder

---

bin/docker-dev-shell
bin/dry-run.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
common/lib/dependabot/file_fetchers/base.rb
common/spec/dependabot/file_fetchers/base_spec.rb
go_modules/lib/dependabot/go_modules/file_fetcher.rb
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

This is an idea to {have,eat} 🍰  in #2551 . Per discussion there, we think that cloning full repositories is our long term direction for `go_modules` updates.
This PR provides a migration path by bootstrapping a temporary git repository from `DependencyFiles[]` if the instantiator of `GoModules::FileUpdater` hasn't provided `repo_contents_path`.
This keeps our internal implementation forward-facing, but provides a migration path during transition.

go_modules: stub repo_contents_path

---

common/lib/dependabot/file_updaters/base.rb
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

This PR targets #2551 
This allows us to pass configuration options to Updater classes,
starting with `tidy` for gomod. Current plans are for go mod tidy
support to be default and not configurable, but in order to roll these
changes out gradually we temporarily allow passing it as an option.
These options can be used to conditionally enable features in the
future, like for instance vendoring.

Allow passing tidy as option to go_modules updater

---

python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_fetcher_spec.rb
python/spec/fixtures/github/contents_python_large_requirements_txt.json

We have a limit on the size of .txt files that we fetch for Python
repositories, most likely because we try to fetch _all_ files with that
extension, and the GitHub contents API only allows fetching files up to
1mb.
Some users are now running into the 100kb size limit that we've set, and
are getting back a pretty opaque `DependencyFileNotFound` error.
In order to resolve the issue for the cases that have been reported,
increasing to 200kb seems like a reasonable first step.
@greysteil you added the original 100kb size limit: https://github.com/dependabot/dependabot-core/commit/86c769c096b57ca41b5c93f939f43ca0ca3b0db8. Do you happen to remember if what I've typed up here is indeed the reason, or is there another reason we cap at 100kb?

Allow requirements.txt files of up to 200kb

---

go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

In production we do not have git configured, so when creating a temp
repo we need to do that. It was passing on CI and locally because we set
it in the docker container there, so the tests now explicitly unset
this.

Configure git when creating a temp repo for gomod updates

---

.github/workflows/ci.yml
.gitignore
common/dependabot-common.gemspec
common/spec/spec_helper.rb
go_modules/spec/spec_helper.rb
nuget/spec/spec_helper.rb
terraform/spec/spec_helper.rb

We are working on some refactors of Dependabot Core and after I introduced  a bug into the 0.19.5 release in https://github.com/dependabot/dependabot-core/pull/2539, I realised the root cause was a test stub bypassing the affected code https://github.com/dependabot/dependabot-core/pull/2543#discussion_r492243627
This PR introduces [simplecov](https://github.com/simplecov-ruby/simplecov) to generate HTML coverage reports locally
Along with a summary in CI:
It adds a few safety rails for work in progress:
- CI will fail if any builds drop below 80% line coverage / 70% branch coverage
- When working locally, CI will fail if any changes made between test runs drop the coverage
At time of writing, this does not implement a per-file coverage minimum and some specific test suites have their …

Add test coverage reports

---

.gitignore
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb
go_modules/spec/fixtures/projects/vendor/go.mod
go_modules/spec/fixtures/projects/vendor/go.sum
go_modules/spec/fixtures/projects/vendor/main.go
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/.gitignore
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/.travis.yml
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/LICENSE
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/README.md
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/appveyor.yml
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/errors.go
go_modules/spec/fixtures/projects/vendor/vendor/github.com/pkg/errors/stack.go
go_modules/spec/fixtures/projects/vendor/vendor/modules.txt

This builds on the work we've done for go mod tidy, and adds support
for running `go mod vendor` and committing the results.
We now also expose a `vendor` flag in the `FileUpdater`, in the bundler
implementation this is not yet used, as we implicitly rely on the
`repo_contents_path` being available there. We should start using that
flag there as well, but leaving it as is for now to make upgrading
easier.
This relies on changes in:
- https://github.com/dependabot/dependabot-core/pull/2551
- https://github.com/dependabot/dependabot-core/pull/2598
And needs to be rebased once those changes land.

Add vendoring support for go_modules

---

bin/dry-run.rb

This accepts a comma separated list representing the keys in the `options` hash passed to `FileUpdater`s.
It's good enough while that's a bitmap, but won't play nicely if options accept values.
We can use this to toggle all the cool features masked behind `options` in the updater, without needing to turn each into a command line flag.
Maybe we should still accept the list via option instead of yanking it from environment?
- Continues https://github.com/dependabot/dependabot-core/pull/2597
- Formalized hack from testing https://github.com/dependabot/dependabot-core/pull/2596 + https://github.com/dependabot/dependabot-core/pull/2551

dry-run --updater-options=

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/renamed_package/go.mod
go_modules/spec/fixtures/projects/renamed_package/go.sum
go_modules/spec/fixtures/projects/renamed_package/main.go

When a module exists, but it (no longer) defines the package of a given
name, we get an error like such:
```
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
github.com/dependabot/vgotest imports
github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```
In this case, we should not treat that as a failed update, but rather as
a DependencyFileNotResolvable.

Gracefully handle gomod package import that has changed

---

CHANGELOG.md
common/lib/dependabot/version.rb

- Bump phpstan/phpstan from 0.12.48 to 0.12.49 in /composer/helpers
- Gracefully handle gomod package import that has changed
- Treat .bundlecache files as binary
- Check if files are binary using the `file` util
- Bump jest from 26.5.2 to 26.5.3 in /npm_and_yarn/helpers
- Bump eslint from 7.10.0 to 7.11.0 in /npm_and_yarn/helpers
- Update tests and fixtures for new Cargo.lock format
- Explicitly install version of rust toolchain
- Rust toolchain has been upgraded to 1.47.0. This means PRs will now try to
upgrade the lockfile to cargo's v2 format.
- Update rubocop requirement from ~> 0.92.0 to ~> 0.93.0 in /common
- Add a fingerprint to generated gitconfigs
- If there isn't a backup gitconfig, remove the generated one
- dry-run: updater-opts via option

Release notes for v0.122.1

---

CHANGELOG.md
common/lib/dependabot/version.rb

- Bundler: Refactored Dependabot's use of Bundler commands to shell out instead
of running in a subprocess.
- This aligns Bundler with other package managers and will enable us to
support other Bundler versions in future.

Release notes for v0.123.0

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

When we vendor a bundler project we often end up with an updated `.gemspec` files in the vendor folder but we don't care about these when creating the PR branch or message as this incorrectly identifies the dependency as a library and attempts to generate a updated requirement.
The requirement sometimes doesn't change when only bumping the version in the lockfile.
This is a quick fix to keep the existing logic but we should refactor this to get it in line with the existing logic to determine if a project is a library as this varies between package manager.

Ignore changed  .gemspec from vendor/cache folder

---

CHANGELOG.md
common/lib/dependabot/version.rb

- Go mod: Handle `cannot find module` during go mod tidy
- Python: Add 3.9.0 and upgrade pyenv to v1.2.21 (@ulgens)
- Bundler: Ignore changed .gemspec from vendor/cache folder

Release notes for v0.123.1

---

.gitignore
bin/dry-run.rb
bundler/lib/dependabot/bundler/update_checker.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb
cargo/lib/dependabot/cargo/update_checker.rb
cargo/spec/dependabot/cargo/update_checker_spec.rb
common/lib/dependabot/update_checkers/base.rb
composer/lib/dependabot/composer/update_checker.rb
composer/spec/dependabot/composer/update_checker_spec.rb
gradle/lib/dependabot/gradle/update_checker.rb
gradle/spec/dependabot/gradle/update_checker_spec.rb
maven/lib/dependabot/maven/update_checker.rb
maven/spec/dependabot/maven/update_checker_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
nuget/lib/dependabot/nuget/update_checker.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb
python/lib/dependabot/python/update_checker.rb
python/spec/dependabot/python/update_checker_spec.rb

In order to better explain why a security update is not possible, we're exposing the  `lowest_security_fix_version` which returns the lowest available non-vulnerable version from the package registry not taking resolvability into account. We'll use this alongside the existing method `lowest_resolvable_security_fix_version` to explain which version is the latest possible version that can be installed and which version is the earliest non-vulnerable/fixed version.
Planned "update not possible" error message:
`Dependabot cannot update #{dependency_name} to a non-vulnerable version`
```
The latest possible version that can be installed is #{lowest_resolvable_security_fix_version},
another dependency is locking  #{dependency_name} to a vulnerable version range.
The earliest fixed version is …
```

Explain update not possible

---

common/lib/dependabot/security_advisory.rb
common/spec/dependabot/security_advisory_spec.rb

Going to use this to figure out if an update is a security fix:
```ruby
security_advisories.select do |advisory|
advisory.fixes_advisory?(updated_dependency)
end.any?
```

Add fixes_advisory/affects_version to security adv

---

bin/dry-run.rb
common/lib/dependabot/security_advisory.rb
common/spec/dependabot/security_advisory_spec.rb

Handle mixed case dependency name when checking if updated dependency fixes security advisory.
- Add option to only do a security update and check if the updated dependency fixes any vulnerabilities
- Security only updates won't attempt to update any non-vulnerable versions

Handle mixed case advisory dependency name & sec only dry-run

---

bin/docker-dev-shell
bundler/helpers/run.rb
common/lib/dependabot/shared_helpers.rb

This forwards the backtrace from any native bundler helper, which makes it easier to figure out what happened in the native helper when ran from core.
I named this `trace` as to not clash with `StandardError#backtrace`, but open to alternatives.

Include backtrace in bundler native errors

---

bin/dry-run.rb
common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

Handle missing directory in cloned repo by creating an empty one and
relying on file fetcher to raise because it can't find a manifest file.
Fixed up some issues around dry-run cloning and the go mod clone stub
(which might not be needed anymore?).

Handle missing directory in cloned repo

---

common/lib/dependabot/file_updaters/vendor_updater.rb

Get the relative vendor dir from the repo_contents_path which is what we
used to construct the vendor_dir.
When creating a tmp dir in mac it returns the directory as `/var/tmp`
but if you run `pwd` in the folder it's suddently in `/private/var/tmp`.

Fix relative dir on mac where tmp is in /private

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/fixtures/projects/unknown_vcs/go.mod
go_modules/spec/fixtures/projects/unknown_vcs/main.go

Copied from go dep implementation:
https://github.com/dependabot/dependabot-core/blob/main/dep/lib/dependabot/dep/file_parser.rb#L142

Handle missing VCS when converting git_source path

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb
go_modules/spec/fixtures/projects/missing_meta_tag/go.mod

Raise DependencyFileNotResolvable error when checking for latest version
for a package that doesn't have any valid meta tags.

Go mod: handle missing package url meta tags

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

Bumping gomodules-extracted (https://github.com/dependabot/dependabot-core/pull/2619) caused the raised error to change for import paths that 404/don't include valid meta tags.

Fix error handling for packages that 404

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb
go_modules/spec/fixtures/projects/missing_meta_tag/go.mod
go_modules/spec/fixtures/projects/missing_package/go.mod

Add a spec for handling package url that don't include meta tags.
Both 404 and missing meta tag errors raised a error message starting
with `unrecognized import path`. I've split these out with two different
test cases.

Go mod: Add/fix specs for missing meta tag and 404

---

cargo/lib/dependabot/cargo/file_updater/manifest_updater.rb
cargo/spec/dependabot/cargo/file_updater/manifest_updater_spec.rb
cargo/spec/fixtures/manifests/version_requirement

Handle `^` version requirements by escaping the previous requirement.
The old requirement (e.g. `^1.0.0`) was interpolated unescaped inside a
regex match so the caret `^` broke the match.

Cargo: handle caret version requirements

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/module_major_version_mismatch/go.mod
go_modules/spec/fixtures/projects/module_major_version_mismatch/go.sum
go_modules/spec/fixtures/projects/module_major_version_mismatch/main.go

When updating a dependency to a v1 tag which includes a v2 module go mod
will complain that the major version doesn't match:
```
go: github.com/dependabot-fixtures/go-major-mismatch@v1.0.1:
go.mod has post-v1 module path "github.com/dependabot-fixtures/go-major-mismatch/v2" at revision v1.0.1
```

Go mod: handle major version mismatch

---

bin/dry-run.rb

Handle comman separated list of dependency names in dry-run, e.g.
```
bin/dry-run.rb cargo "acc/repo" --dep=env_logger,actix-cors
```

dry-run: handle comman separated list of deps

---

common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/helpers/test/run.rb
composer/helpers/bin/run
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb

This aims to improve the behaviour of the `composer` updater while under memory pressure:
Composer updates shell to a helper process implemented in PHP, depending on the project this helper process might end up using several GB of memory.
Previously, there was some code to [enforce memory limits](https://github.com/dependabot/dependabot-core/blob/main/composer/helpers/bin/run#L45-L46) in PHP, that I don't think is used as we always run without specifying the [limit](https://github.com/dependabot/dependabot-core/search?q=memory_limit).
In practice, we're at the whims of the Linux Out of Memory (OOM) Killer, whose algorithm is roughly described [here](https://github.com/torvalds/linux/blob/7c2a69f610e64c8dec6a06a66e721f4ce1dd783a/Documentation/filesystems/proc.rst#31-procpidoom_adj--procpido …

composer: increase Dependabot::OutOfMemory

---

.github/workflows/ci.yml

I noticed that there were some github action warnings on the ci build of my previous PRs. I've made another PR to fix these warnings, as it appears they will break your CI on Monday.
the warnings (https://github.com/dependabot/dependabot-core/actions/runs/357182402): 
```The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/```

update ci jobs env variable assignment

---

hex/lib/dependabot/hex/file_fetcher.rb
hex/spec/dependabot/hex/file_fetcher_spec.rb
hex/spec/fixtures/github/contents_elixir_mixfile_with_eval_file_without_relative_dir.json

Currently there is a bug where if you use `Code.eval_file` in your mix.exs, then dependabot will error out because the second argument is nil. A simple compact solves this issue by removing any nils that the regex catches. I have added a test as well.

Bugfix for Elixir Code.eval_file

---

hex/lib/dependabot/hex/file_fetcher.rb
hex/spec/dependabot/hex/file_fetcher_spec.rb
hex/spec/fixtures/github/contents_elixir_mixfile_with_require_file.json
hex/spec/fixtures/github/contents_elixir_mixfile_with_require_file_without_relative_dir.json

I have a project that requires another file as part of our mix.exs, and dependabot fails due to it not being able to find the required file when upgrading dependencies. This PR adds this functionality by adding another regex similar to how `Code.eval_file` is handled. I have also included tests fo this as well.

Support Elixir Code.require_file

---

npm_and_yarn/helpers/test/npm/conflicting-dependency-parser.test.js
npm_and_yarn/helpers/test/npm/fixtures/conflicting-dependency-parser/package-lock.json
npm_and_yarn/helpers/test/npm/fixtures/conflicting-dependency-parser/package.json
npm_and_yarn/helpers/test/npm/helpers.js
npm_and_yarn/helpers/test/npm/updater.test.js

By writing tests for this helper in the native language, it makes it a lot easier to iterate on the code.

Add native javascript test for npm helper

---

hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/fixtures/mixfiles/diverging_environments

I came across this spec that was setting the wrong let variables, and thus wasn't being run properly.
The mixfile was syntactically invalid, so I fixed it.

fix incorrect spec and mixfile fixture

---

hex/lib/dependabot/hex/file_parser.rb
hex/lib/dependabot/hex/file_updater/lockfile_updater.rb
hex/lib/dependabot/hex/update_checker/version_resolver.rb
hex/spec/dependabot/hex/file_parser_spec.rb
hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/dependabot/hex/update_checker/version_resolver_spec.rb
hex/spec/fixtures/mixfiles/loads_file_with_require
hex/spec/fixtures/support_files/module_version

Currently you get an error if you try and read say a version file in a supporting file in an Elixir project. This is handled in the mixfile proper by stubbing out the call to read a file with just a standard string. This PR extends this behavior to supporting files as well. I have also added a test for this as well.

Support reading files in Elixir supporting files like in mixfiles

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver.rb

Prefer the npm conflicting dependency parser when there's both a yarn.lock and a package-lock.json file.
The npm parser handles edge cases where the package.json is out of sync with the lockfile, something the yarn parser doesn't deal with at the moment.

JS: Prefer the npm conflicting dependency parser

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb

Sharing snapshot to discuss the approach:
When Dependabot encounters a Go module backed by a Git repository, especially one on `github.com`, it should raise `Dependabot::GitDependenciesNotReachable` with `dependency-urls` details describing the missing repository. This matters as the rich exception provides more detail about what went wrong and potential recovery options.
This PR accomplishes this by intercepting the error thrown from the "UpdateChecker", and detecting `github.com/.*` urls. If we detect the failed dependency was on `github.com`, we assume it's a "git dependency" and raise accordingly.

Go modules: raise GitDependenciesNotReachable

---

go_modules/helpers/build

Invoke the [go clean](https://golang.org/pkg/cmd/go/internal/clean/) command after building modules, to remove the helper's dependency sources from the tree.
This frees 11MB from the final docker image, and reduces the files any subsequent [`chown`](https://github.com/dependabot/dependabot-core/blob/main/Dockerfile.development#L23) steps have to update.
<details><summary>pre-disk usage</summary>
<p>
```
[dependabot-core-dev] /opt/go/gopath $ du pkg/
12	pkg/mod/golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898/internal
116	pkg/mod/golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898
32	pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/hkdf
148	pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/ed25519/internal/edwards25519
156 …
```

go_modules: clean build cache

---

bin/dry-run.rb
bundler/helpers/lib/functions/force_updater.rb

Add dependency names and count to dry run:
```
=> updating 4 dependencies: aws-sdk, vcr, webdrivers, webmock
=== aws-sdk (2.1.0)
=> checking for updates 1/4
...
```
Renamed a variable in the bundler force updater to clarify intent.

Add dependency names and count to dry run

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb

When checking if a package is private dependabot makes a request to the
package url, e.g. https://www.npmjs.com/package/express and if this
redirects to the login page it is assumed it is private so we show a
custom PrivateSourceAuthenticationFailure. This request can become rate
limited in which case it returns a 429.

JS: Handle rate limited npm package requests

---

go_modules/spec/dependabot/go_modules/file_parser_spec.rb

No functional changes, but it may be worth verifying this behaviour with versioned modules?

go: verify GitDependenciesNotReachable from versioned modules

---

.github/workflows/ci.yml
.github/workflows/docker.yml
Dockerfile.ci

Running docker build for the dependabot-core-ci image was hanging at the
"exporting layers" step after running all the steps in the Dockerfile.
This seems to indicate that docker buildkit is doing a bunch of heavy
lifting/diffing/hashing of the content (lots of bundle files) which is
too memory intensive and causes the docker build command to exit 137
(probably OOM).

Fix dependabot-core-ci build by removing buildkit

---

.github/workflows/ci.yml
bundler/.rubocop.yml
cargo/.rubocop.yml
common/.rubocop.yml
composer/.rubocop.yml
dep/.rubocop.yml
docker/.rubocop.yml
elm/.rubocop.yml
git_submodules/.rubocop.yml
github_actions/.rubocop.yml
go_modules/.rubocop.yml
gradle/.rubocop.yml
hex/.rubocop.yml
maven/.rubocop.yml
npm_and_yarn/.rubocop.yml
nuget/.rubocop.yml
omnibus/.rubocop.yml
python/.rubocop.yml
terraform/.rubocop.yml

At some point rubocop removed support for finding configs in parent
directories and only loads the .rubocop.yml defined in the current
folder so we used to run CI lint with `-c ../.rubocop.yml` but this
breaks editors (e.g. vscode) support as it needs to run rubocop in the
package manager folder.

Add rubocop config for each language

---

python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
python/spec/fixtures/projects/pipenv/missing-system-library/Pipfile
python/spec/fixtures/projects/pipenv/missing-system-library/Pipfile.lock

Raise a `DependencyFileNotResolvable` error when pipenv fails to install
dependencies require missing system level dependenceis.
The error message parsing is pretty gnarly as the only reference of the
offending dependency is in a tmp build path in the error message.
In the test case pipenv failed to install `rtree` because it requires a
system level dependency: `libspatialindex`.
We don't want to install this in our ever growning dockerfile so attempt
to explain the error to users.
The underlying cause might be obscured by this open issue in pipenv:
https://github.com/pypa/pipenv/issues/2791
Similarly, there's an open issue to fix the system requirement in rtree:
https://github.com/Toblerity/rtree/issues/147
This is the error pipenv raises:
``` …
```

pipenv: handle installs with missing system deps

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/file_updater.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/dependabot/docker/file_updater_spec.rb
docker/spec/fixtures/docker/dockerfiles/platform

Dockerfiles can specify the platform in the from line. This change adds support for parsing and updating FROM lines with the platform flag specified.
```Dockerfile
FROM [--platform=<platform>] <image> [AS <name>]
```
https://docs.docker.com/engine/reference/builder/#from

fix(docker): support platform option in from line

---

Dockerfile.development

The default branch of https://github.com/hmarr/dotfiles was renamed, follow it.
This is only for development, where `.vimrc` is loaded.
<details><summary>fails like</summary>
<p>
```
E492: Not an editor command:               You can always update your selection by clicking <span class="text-bold">Cookie Preferences</span> at the bottom of the page.
line  730:
E492: Not an editor command:               For more information, see our <a href="https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-privacy-statement">Privacy Statement</a>.
line  731:
```
770 total errors!
</p>
</details>

hmarr dotfiles branch rename

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

`go mod tidy` makes sure that go.mod matches the source code in a Go
module. This also means that `dependabot` is doing a quassi linting on
the code, which prevents updating versions in a go.mod if the source
code doesn't got build. One particular use case is when a project is
missing generated files. Sometimes people don't submit and commit the
generated files of a code generator (i.e: `protobuf`) and do it in
pre-script in the CI. Because `dependabot` is not aware of this
pre-script, it'll run `go mod tidy` and fail for the user.
We should silently continue if `go mod tidy` fails and not raise an
error. This will allow dependabot still to run `go mod tidy`, but will
not block users for these kind of edge cases.

go_modules: don't raise error for go mod tidy

---

common/lib/dependabot/errors.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Similar to the introduction of the `OutOfMemory` error type in 61e79897c8c79ef0fb2e2c3c23ca8050fcf02754, this pull request introduces an `OutOfDisk` error type.
Incorporating new error types typically requires teaching each ecosystem to make use of the error type. Instead of one long-running pull request to update every ecosystem, this pull request incorporates the `OutOfDisk` error type into the go_modules ecosystem, and paves the way for future pull requests to add it to other ecosystems.
To date, I've seen two stack traces for out of disk errors in the go_modules ecosystem. One includes STDERR content like this:
rsc.io/sampler imports
write /opt/go/gopath/pkg/mod/cache/vcs/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef/info/attributes: no space left on device
And the …

Add OutOfDisk error and use it in go_modules ecosystem

---

CHANGELOG.md
common/lib/dependabot/version.rb

- Gradle: Support kotlin manifest files (thanks, @shakhar!)

V0.128.0 release notes

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/monorepo/cmd/go.mod
go_modules/spec/fixtures/projects/monorepo/cmd/go.sum
go_modules/spec/fixtures/projects/monorepo/cmd/main.go
go_modules/spec/fixtures/projects/monorepo/common/go.mod
go_modules/spec/fixtures/projects/monorepo/common/go.sum
go_modules/spec/fixtures/projects/monorepo/common/lib.go

Some users have multiple go modules within a single repository, and use `replace` directives to reference local modules on disk. [sample](https://github.com/thepwagner/dependagot/blob/master/go/modules/go.mod#L5).
Previous to this PR, Dependabot would replace all local `replace` directives with stubbed modules, under the assumption that they weren't available.
This assumption changed when Dependabot started cloning full Go repositories (a requirement for `go mod vendor` and `go mod tidy` support)! This PR adjusts the logic to only stub modules that are:
* absolute paths
* relative paths that escape the current checkout (e.g. `../foo` from the root)
* relative paths that do not exist
cc https://github.com/dependabot/dependabot-core/pull/2551#discussion_r494289784

go_modules: only stub modules outside the current checkout

---

bundler/spec/dependabot/bundler/file_updater_spec.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/spec_helper.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb

This corrects the assumption that `repo_contents_path` is an instance of `Pathname`, which it only ever is when instantiated by the `build_tmp_repo` helper.
Since that helper already claims to return a`[String]`, correct it.
- #2848

common/spec_helper: tmp_repo return string

---

go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Don't `expect().not_to raise_error(SpecificError)`, since that masks all other potential errors.

go_modules: fix test warning 🩹 

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb

In https://github.com/dependabot/dependabot-core/pull/2791 we added a test for unreachable dependencies that aren't located at the repository root. 
At the time it was assumed that since the user wrote `github.com/thepwagner/my-awesome-repo/v2` that was the best "dependency URL" to return with errors. Since introducing [updates from private GitHub repositories](https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/) it has become clear that recording the problematic repository is a better solution than the exact path.
This PR adjusts the behaviour so only the base repository URL (e.g. `github.com/${owner}/${repo}`) is raised in the error for unreachable git dependencies.

go_modules: GitDependenciesNotReachable.urls are repos, not module paths

---

CONTRIBUTING.md
README.md

Unfortunately, we are not accepting new ecosystems into core at the moment. We are currently focused on making some improvements into how we handle extensibility before we add any more ecosystems. We will still be improving and upgrading support for existing ecosystems.

Update README and CONTRIBUTING guidelines

---

bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
cargo/spec/dependabot/cargo/file_updater_spec.rb
common/lib/dependabot/errors.rb
common/lib/dependabot/shared_helpers.rb
common/lib/dependabot/utils.rb
common/spec/dependabot/errors_spec.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/helpers/test/run.rb
common/spec/spec_helper.rb
composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb
composer/spec/dependabot/composer/file_updater_spec.rb
dep/spec/dependabot/dep/file_updater_spec.rb
elm/spec/dependabot/elm/file_updater_spec.rb
hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/dependabot/hex/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb
python/spec/dependabot/python/file_updater_spec.rb

All errors now inherit from `DependabotError` and sanitize the message from http basic creds in urls.

Sanitize creds from DependabotError

---

.github/workflows/ci.yml

Composer is runnig into rate limits fetching packages from github which
is failing on ci.
Adding a github token with no special permissions to get a higher api
rate limit fetching public repos.

Add composer github token for public repo read

---

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/helpers.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/v1/invalid_v2_name/composer.json

Composer v2 introduced a check on package names, and when no lockfile is
present to validate the plugin-api-version this causes us to attempt the
update with v2, which will fail because of this invalid name.
This includes an extra check to make sure the name is compatible with
the constraints of composer v2.

Verify if composer name is compatible with v2

---

CHANGELOG.md
common/lib/dependabot/version.rb

- Bump phpstan/phpstan from 0.12.62 to 0.12.63 in /composer/helpers/v2
- Bump friendsofphp/php-cs-fixer in /composer/helpers/v2
- Composer: Verify if composer name is compatible with v2
- Python: Upgrade Python version to 3.9.1 (@ulgens)
- Bump npm from 6.14.9 to 6.14.10 in /npm_and_yarn/helpers
- Bump eslint from 7.15.0 to 7.16.0 in /npm_and_yarn/helpers
- Bump friendsofphp/php-cs-fixer in /composer/helpers/v1
- Sanitize creds from DependabotError
- Bump composer/composer from 1.10.16 to 1.10.19 in /composer/helpers/v1
- Bump phpstan/phpstan from 0.12.62 to 0.12.63 in /composer/helpers/v1
- Bump pip from 20.3.1 to 20.3.3 in /python/helpers
- Bump @npmcli/arborist from 2.0.1 to 2.0.2 in /npm_and_yarn/helpers
- go_modules: limit GitDeps to repo
- go_modules: fix test warning
- Bump …

v0.129.1 release notes

---

bundler/dependabot-bundler.gemspec

When we moved this code out into native helpers, those were not included
in the gem that we build.
This has historically not really been an issue for us, since we run
Dependabot in the Docker environment where these helpers are manually
copied over. But for people using the gem as a standalone, this means it
no longer works.
Fixes #2885

Include native helpers in bundler gem

---

.github/workflows/ci.yml
composer/spec/dependabot/composer/file_updater_spec.rb
composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb

Fixes flaky test failures where composer runs into gh rate limits:
`Could not authenticate against github.com`
Requires `DEPENDABOT_TEST_ACCESS_TOKEN` to be set in CI.
Flattened the git specs as they where pretty hard to reason about with
lots of nested lets.

Composer: use github token in test env 

---

.github/workflows/ci.yml

It's used to authenticate composer github requests to get around api rate limits

Use GITHUB_TOKEN as a test token to fix fork specs

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb

Previously we would run `go list -m -json all` to generate a list of
dependencies to attempt to update.
The way that this is implemented, it causes _every_ transitive
dependency to be listed, even if they are not required by this project.
This can happen when a module defines several packages, but only a
subset of those packages is used by the current repository.
It will also verify that each of those transitive dependencies is
available, and this causes issues when we rely on a dependency with
private transitive dependencies. We run into the scenario where we have
access to any of the transitive dependencies that are used, but since we
do not have access to an _unused_ transitive dependency, we run into a
`dependency_file_not_resolvable` error.
This is especially unfortunate, since we …

gomod: Do not attempt to parse transitive dependencies

---

common/lib/dependabot/clients/azure.rb
common/spec/dependabot/clients/azure_spec.rb

Azure client today doesn't implement any retries. When working with bigger repos, we see (transient) ServiceUnavailable often. This PR adds retries for the standard 500, 502 and 503 errors.

[azure] Add retries for Azure client

---

common/dependabot-common.gemspec

Per https://github.com/octokit/octokit.rb/issues/1315
[faraday-1.2.0](https://github.com/lostisland/faraday/releases/tag/v1.2.0) released recently, breaking Dependabot CI.
Specifically, errors are being returned as resources instead of raised as exceptions like `Octokit::NotFound`.
🩹 CI by pinning faraday to the previous version.
- discovered https://github.com/dependabot/dependabot-core/pull/2911
- discovered https://github.com/dependabot/dependabot-core/pull/2912

pin faraday for octokit

---

gradle/lib/dependabot/gradle/file_fetcher/settings_file_parser.rb
gradle/spec/dependabot/gradle/file_fetcher/settings_file_parser_spec.rb
gradle/spec/fixtures/settings_files/call_style_settings.gradle

I had a `settings.gradle.kts` where includes with a space in front of the opening parenthesis were not discovered.
This PR should fix that issue.

[Gradle] Fix not matched spaces in settings

---

bin/dry-run.rb

This modifies the `bin/dry-run.rb` testing script to accept a `--provider PROVIDER` argument, which can be used to select from [any available source providers](https://github.com/dependabot/dependabot-core/blob/f66290a0e341e656784fd1dae0d7e80ea913ebac/common/lib/dependabot/file_fetchers/base.rb#L200-L212).
This makes functionally testing authentication changes like #2918 easier.
To verify this change use a public repository. I searched `package.json site:bitbucket.org` and found [atlassian/atlasboard](https://bitbucket.org/atlassian/atlasboard/src/master/package.json):
```
bin/dry-run.rb --provider bitbucket npm_and_yarn atlassian/atlasboard
```

dry-run: configurable source provider

---

.dockerignore

These directories are created by the setup in [`bin/docker-dev-shell`](https://github.com/dependabot/dependabot-core/blob/f66290a0e341e656784fd1dae0d7e80ea913ebac/bin/docker-dev-shell#L164-L165),
and [cache-bust the docker build](https://github.com/dependabot/dependabot-core/blob/f66290a0e341e656784fd1dae0d7e80ea913ebac/Dockerfile#L182).
They're already `.gitignore`-ed, by `.dockerignore`-ing we can have docker 
cache hits for `bin/docker-dev-shell --rebuild` 🩹 🎉 .
This has no affect outside local development experience.

dockerignore helpers/helpers

---

common/dependabot-common.gemspec

This reverts https://github.com/dependabot/dependabot-core/pull/2913 , as https://github.com/octokit/octokit.rb/releases/tag/v4.20.0 was released to address the underlying issue, https://github.com/octokit/octokit.rb/issues/1315
- Reverts https://github.com/dependabot/dependabot-core/pull/2913
- Closes https://github.com/dependabot/dependabot-core/pull/2914

revert faraday restriction

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/go_1.11/go.mod
go_modules/spec/fixtures/projects/go_1.11/main.go
go_modules/spec/fixtures/projects/monorepo/go.mod
go_modules/spec/fixtures/projects/monorepo/go.sum
go_modules/spec/fixtures/projects/monorepo/main.go
go_modules/spec/fixtures/projects/substituted/go.mod
go_modules/spec/fixtures/projects/substituted/go.sum
go_modules/spec/fixtures/projects/substituted/main.go

Previously Dependabot would extract the changes detected in `go.mod`, then use `go mod edit -{drop,}require` to re-apply the updated paths on to the original `go.mod`.
This PR asserts that since Dependabot supports `go mod tidy`, customers expect `go.mod` to be tidied. That allows us to skip this additional complexity+compute of reapplying updates by returning the tidied contents directly.
Extra care is taken to ensure Dependabot won't inject a go language version (the `go` directive, e.g. `go 1.15`), to avoid regression. AFAICT this will be added by all versions since `go1.12 (released 2019/02/25)`. Meaning the potential for injection only affects modules that immediately upgrade to vgo when it became available, `go1.11 (released 2018/08/24)`, and haven't updated since. Likely rare.

GoModUpdater: return updated go.mod directly

---

github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

When dependabot updates an Actions workflow file, it prefers to replace versions with full length commit SHAs.
This is a great practice, reinforced by [Actions's best practices](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions).
This has an unfortunate side effect when the Action is already pinned to the short version of the SHA: Dependabot will propose an "upgrade" to the full SHA.
That's _is_ a good idea from a security standpoint, but not an expected feature of Dependabot. Customers only expect PRs for dependency updates.
This PR adjusts the `Actions` comparison so that short refs are considered equal to full refs when considering upgrades.
That means customers will be upgraded (to full SHAs) as …

actions: accept shortref hashes

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/resolvability_errors.rb
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

This PR restores the functionality introduced by https://github.com/dependabot/dependabot-core/pull/2780 , which was reverted by https://github.com/dependabot/dependabot-core/pull/2880 .
If Dependabot encounters a go module on `github.com` that can not be accessed, it should raise a `GitDependenciesNotReachable` error with details about the requested repositories.
Raising a `GitDependenciesNotReachable` is important as this is used by GitHub.com to recover from the error - https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/
Since we no longer `go get` in the `FileParser`, there are two possible places this might be raised:
* In the `UpdateChecker`, if the private repository is a direct dependency
* In the `FlleUpdater`, if the private …

go_modules raise GitDependenciesNotReachable

---

common/dependabot-common.gemspec
git_submodules/dependabot-git_submodules.gemspec

[parseconfig](https://rubygems.org/gems/parseconfig/versions/1.1.0) released `v1.1.0` on `2021-01-06` (today).
Per its [changelog](https://github.com/datafolklabs/ruby-parseconfig/blob/master/Changelog), this release changes the behaviour of value parsing to introduce additional features.
This change causes a regression in the `git_submodules` tests: when an invalid `.gitmodules` file is parsed, the returned value is different.
* Modify gemspec to not upgrade `parseconfig` past `1.1.0`
* As `parseconfig` is used exclusively by the `git_submodules` plugin, only declare it there
- Discovered/blocked https://github.com/dependabot/dependabot-core/pull/2951
- Blocks https://github.com/dependabot/dependabot-core/pull/2952

fix CI: pin parseconfig <1.1.0

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/fixtures/projects/no_dependencies/go.mod
go_modules/spec/fixtures/projects/no_dependencies/main.go

It's valid to declare a `go.mod` file that doesn't define any dependencies; when that happens `go mod edit -json` will return:
```
dependabot-core/go_modules/spec/fixtures/projects/no_dependencies $ go mod edit -json
{
"Module": {
"Path": "github.com/dependabot/vgotest"
},
"Go": "1.12",
"Require": null,
"Exclude": null,
"Replace": null
}
```
This PR modifies the `FileParser` to return an empty array in this case, instead of the nil value.
- https://github.com/dependabot/dependabot-core/pull/2880

go_modules: FileParser accept go.mod without dependencies

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb
bundler/spec/fixtures/ruby/gemspecs/require_ruby_3
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb

Support gemspecs with `required_ruby_version` requirements matching 2.7
and 3.0. Also updated the other major versions to the latest available
version to match stricter requirements.
I'm not sure why we actually do this re-write from a requirement `>=
2.7.2` to `2.7.2`. Removing this logic seems to still work for some
updates that previously failed but fail with others so I don't yet feel
confident in re-writing this.
AFAICT we don't actually rely on these versions being installed, it only seems to be done for resolution where updates fail with exceptions about no compatible ruby version being found if removing the re-write.
Tested that this fix works for projects that require ruby 2.7+ but don't
rely on bundler 2 gems:
`bin/dry-run.rb bundler "HerbCSO/carstens-butler" --dir="/." …

Bundler: support ruby 2.7 and 3.0 in gemspecs

---

bin/docker-dev-shell

Don't persist the `dry-run/` path across container restarts.
This might be a performance regression for some workflows, but avoids the potential for private manifests used in testing (e.g. with [`LOCAL_GITHUB_ACCESS_TOKEN`](https://github.com/dependabot/dependabot-core/blob/0c3f58f3a33c93036a7e346f2ff42bb629d99e8e/bin/dry-run.rb#L109-L116)) to stick around on the host system.
Note that ecosystems that clone by default (e.g. `go_modules`) do not use the `dry-run/` path for clones: they use `/tmp`, which is already not persisted.

docker-dev-shell: exclude dry-run files

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/private_source.json
npm_and_yarn/spec/fixtures/package_files/private_source.json
npm_and_yarn/spec/fixtures/yarn_lockfiles/private_source.lock

Currently it will try to call `/api/v4/projects/229/packages/npm/@prefix%2Fpackage-name`
Which will return: HTTP/1.1 404 Not Found
The correct api endpoint for the package meta data is located at: `/api/v4/packages/npm/@prefix%2Fpackage-name`
While the endpoint for the tar.gz is `api/v4/projects/229/packages/npm/@prefix/package-name/-/@prefix/package-name-0.4.0.tgz`

Support GitLab format npm registry

---

Dockerfile

pyenv released a new version with Python 3.9.1 https://github.com/pyenv/pyenv/releases/tag/v1.2.22

Use release version of pyenv

---

composer/lib/dependabot/composer/helpers.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/v1/invalid_v2_requirement/composer.json

Composer v2 has added some restrictions on package names. We already
validate that name for the package name itself, but v2 will _also_ raise
an error when any of the names listed in the require map are invalid.
We particularly notice this happens for invalid casing (v2 requires the
full name to be downcased), so that's what we're testing for here.

Use composer v1 when any of the requirements are invalid on v2

---

python/helpers/requirements.txt
python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb

As of pip-tools 5.5, the output format changed to always put `via` comments on separate lines, and no longer include a trailing `\` when using `--generate-hashes`.
so it changed from this output:
```
#
#
#
apipkg==1.4               # via execnet
attrs==18.1.0             # via -r requirements/test.in, pytest
execnet==1.5.0            # via pytest-xdist
flaky==3.4.0              # via -r requirements/test.in
mock==2.0.0               # via -r requirements/test.in
more-itertools==4.1.0     # via pytest
pbr==4.0.2                # via mock
pluggy==0.6.0             # via pytest
py==1.5.3                 # via pytest
pytest-forked==0.2        # via pytest-xdist
pytest-xdist==1.22.2      # via -r requirements/test.in
pytest==3.5.1             # via -r requirements/test.in, pytest-forked, …
```

Bump pip-tools from 5.4.0 to 5.5.0 in /python/helpers and update test spec

---

Dockerfile

This upgrades node from v12.x (contrary to what the comment said) to v14.x, which is the latest long-term supported version.

Upgrade node to v14.15.4

---

npm_and_yarn/helpers/package.json
npm_and_yarn/helpers/yarn.lock

We plan to use npm v7 in a future update. This adds that, just to make
sure that having them side by side doesn't introduce any problems.

Install npm 6 and npm 7 side by side

---

bin/dry-run.rb
common/lib/dependabot/logger.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/conflicting_dependency_resolver.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb

WIP: detect npm 7 lockfiles and log the result without using it.

npm: detect npm 7 lockfiles

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

The current sanitization works well when directly creating PRs, however,
when a user replies to an email notification containing that content, some
of the markup of the original message will be stripped out (either by
GitHub, or by email providers), which can result in a link like 
`<a href="https://github.com/jurre>@jurre</a>` being turned into just
`@jurre`, which will consequently mention theuser when that email reply 
is rendered.
This wraps the inner mention in a codeblock, which should prevent this
from happening. It looks _slightly_ funny:
<a href="https://github.com/jurre"><code>@jurre</code></a>
But I think this is worth it, getting unexpected mentions by Dependabot
is a source of frustration for users, and by showing that the mention is
wrapped in a codeblock, this should make …

Sanitize mentions more aggressively

---

gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb
gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb
gradle/spec/fixtures/buildfiles/custom_repos_build_assignment.gradle

This pull request modifies the `Dependabot::Gradle::FileParser::RepositoriesFinder` to accept maven repositories where the URL field is assigned.
Includes a failing test case rooted on a valid project.
<details><summary>$ gradle classpath</summary>
<p>
```
$ gradle dependencies
&gt; Task :dependencies
------------------------------------------------------------
Root project 'gradle-foo'
------------------------------------------------------------
annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies
apiElements - API elements for main. (n)
No dependencies
archives - Configuration for archive artifacts. (n)
No dependencies
compileClasspath - Compile classpath for source set 'main'.
\--- org.spigotmc:spigot-api:1.16.4-R0.1-SNAPSHOT
+--- …
```

gradle: repository url by assignment

---

python/helpers/requirements.txt
python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb

Restore the pull request updating pip-tools. This was reverted because
there was a delay getting the changelog posted.
This reverts commit 88bd296eae0d127c15a7b00578c9de7842cb525f.

Bump pip-tools from 5.4.0 to 5.5.0

---

.vscode/launch.json
.vscode/settings.json
bin/dry-run.rb
npm_and_yarn/helpers/.eslintrc
npm_and_yarn/helpers/build
npm_and_yarn/helpers/jest.config.js
npm_and_yarn/helpers/package.json
npm_and_yarn/helpers/yarn.lock

This adds a couple launch scripts to debug npm and yarn tests when
running then using jest.
The launch scripts complained about a missing config file so added this
and changed the default env from jsdom to node as this is what we use.
Changed `eslint-plugin-prettier` to `eslint-config-prettier` as this
seems like the recommended extension now when using prettier with
eslint: https://prettier.io/docs/en/integrating-with-linters.html
This extracts these changes from the npm 7 branch:
#3011

Fix JS debugging in vscode

---

composer/lib/dependabot/composer/helpers.rb
composer/spec/dependabot/composer/file_updater_spec.rb
composer/spec/dependabot/composer/helpers_spec.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/platform_package/composer.json
composer/spec/fixtures/projects/platform_package/composer.lock

Hi,
after https://github.com/dependabot/dependabot-core/pull/2970 Dependabot PRs reverted to using composer v1 in my repo. The reason is that I have `"ext-zip": "*"`and similar in the `require` section.
I tested this by checking the value returned by `composer_version`.

composer: fix check for platform deps in composer version detection

---

gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb
gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb
gradle/spec/fixtures/buildfiles/root_build.gradle.kts

In Kotlin, a function call can have named parameters and Strings are only allowed to begin with `"`.
````kotlin
repositories {
maven("foo.com")
maven(url = "bar.com") // equals to maven("bar.com")
maven('baz.com') // invalid, does not compile
}
````
This PR adds the optional `url = ` String to the regex as well as removing `'` as String delimiter, which is not allowed in Kotlin.

Gradle Kotlin DSL: Add Support for Named URL Parameter in Maven Repository

---

nuget/lib/dependabot/nuget/file_fetcher/import_paths_finder.rb
nuget/spec/dependabot/nuget/file_fetcher/import_paths_finder_spec.rb
nuget/spec/fixtures/csproj/project_reference_remove.csproj

Nuget allows us to reference nested projects using the
`<ProjectReference Include="some\project.csproc">` notation. You can
also explicitly remove references as shown in the fixture added in this
PR.
In that case we used to error, now we just ignore that reference
instead.

Nuget: Ignore `Remove` ProjectReferences

---

nuget/lib/dependabot/nuget/requirement.rb
nuget/spec/dependabot/nuget/requirement_spec.rb

Typically you’d define a Nuget range as `[2.0, 3.0)` which translates to: "higher than
or equal to 2.0 but lower than 3.0". You can also say `2.0.*` which means any
patch version of 2.0.
However, it's valid to combine these like `[2.1.*,3.0.0)`.
The floating notation (`*`) seems like it’s redundant in this case,
as the `3.0.0)` bit would allow 2.2 to be installed.
I could not find any documentation on this, so I made a best guess
effort to do what seems right, previously a notation like this would
fail and cause the update to error. I've verified that this resolves
those errors when dry-running.

Nuget: Parse floating notation when used in range

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/unreachable_path_vcs_source/composer.json

When a Composer repository is specified as a local path source which is
not available we should raise a DependencyFileNotResolvable error.

Composer: handle unreachable path vcs source

---

composer/lib/dependabot/composer/requirement.rb
composer/spec/dependabot/composer/requirement_spec.rb

The `.x-dev` postfix is a way to tell composer to check out a branch
instead of a tag. For the purpose of defining the version range, we can
ignore this notation and replace it with a `0` to ensure we match the
right range.

Composer: Handle version constraints with both caret and dev postfix

---

docker/lib/dependabot/docker/update_checker.rb

Previously, Dependabot would use the [Docker registry manifest
endpoint](https://docs.docker.com/registry/spec/api/#manifest) with the
`application/vnd.docker.distribution.manifest.v2+json` Media Type:
```
dt=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/python:pull" | jq -r .access_token)
curl curl --get -v https://registry.hub.docker.com:443/v2/library/python/manifests/slim --header "Authorization: Bearer $dt" --header "Accept: application/vnd.docker.distribution.manifest.v2+json"
< HTTP/1.1 200 OK
< Content-Length: 1370
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Docker-Content-Digest: sha256:af2d64e6de9f891bd5958a498bd2394389143749b3c57ffcc8c2aec054b28ad5
```
However, the digest that is returned in the header here, …

Use the correct Docker digest when checking for updates

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/unaddable_platform_req/composer.json

It's not clear to me why we need to raise in this scenario, those errors
are not handled. It seems better to attempt the update without adding
the extensions, for some cases that I've tried locally that seems to
update dependencies just fine.
Maybe this behavior was improved with composer 2?

Don't raise when adding temp platform extensions

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/invalid_version_string/composer.json

This would previously bubble up as an unknown error, but we should
inform the user their manifest file is not resolvable.
We handle a slightly different variant of this error already.

Composer: handle invalid version string

---

maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb
maven/spec/fixtures/projects/invalid_repository_url/pom.xml

Previously an invalid URI would result in an unhandled error. When one
is specified, we cannot resolve any of the dependencies, so we should
raise an error indicating such.

Maven: Raise DependencyFileNotResolvable when invalid repo is specified

---

maven/lib/dependabot/maven/file_parser/property_value_finder.rb
maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb
maven/spec/fixtures/projects/invalid_version_ref/pom.xml

When a version ref is invalid, we should raise a
DependencyFileNotEvaluatable. This can potentially be handled in the
`FileParser` if other dependencies _can_ be found.

Maven: handle invalid pom references

---

nuget/lib/dependabot/nuget/update_checker/version_finder.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
nuget/spec/fixtures/projects/version_range/my.csproj

Previously, a version specified as a range would result in a `undefined
method `any?' for "[5.1.0, 6.0.0)":String` error. This prevents that
from happening.

Nuget: handle version ranges in VersionFinder

---

bin/dry-run.rb
bundler/lib/dependabot/bundler/file_parser.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
common/lib/dependabot/errors.rb
common/lib/dependabot/file_parsers/base.rb

This introduces `Dependabot::UnexpectedExternalCode` as a new error, to be raised when Dependabot
determines it may need to evaluate external code to update a dependency.
This exception will be part of an **opt-in** hardening, to
be used in conjunction with features that extend the resources
accessible to Dependabot (e.g. private packages and sources).
The included sample and test cases centre around the Bundler ecosystem,
where Git sources which may result in a evaluating the Ruby code contained in the the dependency's
`.gemspec`, e.g. https://github.com/dependabot/dependabot-core/blob/main/common/dependabot-common.gemspec

Dependabot::UnexpectedExternalCode

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package/package.json
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package/packages/build/package.json

Previously, when using npm 7 workspaces, when a dependency was installed
from a workspaces' `package.lock` but a _different_ version of that
dependency was installed via the top-level `package.json`, we would grab
the top-levels version, resulting in incorrect behavior.
This changes the implementation to look in the lockfiles' `packages`
object for the actual dependency from that workspace, and grab the we
need there.

Npm7: correctly parse version from package dependencies

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/npm_lockfiles/npm7_subdependency_update_preserved_indentation.json
npm_and_yarn/spec/fixtures/projects/npm7/packages_name_missing/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/packages_name_missing/package.json
npm_and_yarn/spec/fixtures/projects/npm7/packages_name_outdated/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/packages_name_outdated/package.json
npm_and_yarn/spec/fixtures/projects/npm7/simple/package.json
npm_and_yarn/spec/fixtures/projects/npm7/subdependency_update/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/subdependency_update_tab_indentation/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/workspaces_incorrect_version/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/workspaces_incorrect_version/package.json
npm_and_yarn/spec/fixtures/projects/npm7/workspaces_incorrect_version/package/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/packages_name_missing/package-lock.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/packages_name_missing/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/packages_name_outdated/package-lock.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/packages_name_outdated/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/simple/package-lock.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/simple/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/workspaces_dev/other_package/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/workspaces_dev/package-lock.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/workspaces_dev/package.json
npm_and_yarn/spec/fixtures/updated_projects/npm7/workspaces_dev/packages/package1/package.json

Fixes one of the bugs discovered in this update:
https://github.com/AviVahl/ts-tools/pull/152
This particular update no raises when dry-running: `bin/dry-run.rb npm_and_yarn AviVahl/ts-tools --cache files --dep yargs` - we'll need to do some further work in the file parser and update checker to not attempt this update in the first place.
Dependabot will no longer attempt to add the nested dependency to the root level lockfile when doing updates to npm workspace projects.
This is done by checking if the dependency being updated is defined in a `package.json` in the same folder as the lockfile being updated. If it's a nested package we run `npm install` without any package@version arguments letting npm update the nested package references which have already been updated in the package.json …

npm: fix npm workspace bug

---

docker/lib/dependabot/docker/update_checker.rb

https://github.com/dependabot/dependabot-core/issues/2962 reported an problem with the pull requests that Dependabot was opening for the `python:slim` Docker image. The `python:slim` Docker image is a multi-architecture image and publishes a manifest _list_ (also known as a ["fat manifest"](https://docs.docker.com/registry/spec/manifest-v2-2/#image-manifest-version-2-schema-2)). With an image that uses a manifest _list_, the manifest list has a digest, and each architecture-specific image in the list has a digest as well. In https://github.com/dependabot/dependabot-core/issues/2962 we saw that when a Dockerfile depended on `python:slim` (which again is a multi-architecture image), Dependabot wrongly created a pull request to update the Dockerfile to use the `linux/amd64` version of the …

Fix media types in Accept header for Docker Registry

---

common/lib/dependabot/file_updaters/vendor_updater.rb
common/spec/dependabot/file_updaters/vendor_updater_spec.rb

Previously Dependabot included a list of binary mime types and encoded
only binary files.
Invert to include a list of acceptable text mime types to leave
un-encoded.
Per the included test, the edge case here is `iso-8859-1` strings, which
aren't binary but also aren't valid `utf-8`.
- Closes https://github.com/dependabot/dependabot-core/issues/3074

common: assume vendored resources are binary

---

npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/yanked_version/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm6/yanked_version/package.json
npm_and_yarn/spec/fixtures/projects/npm7/yanked_version/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/yanked_version/package.json

This was previously not working for npm 7 using arborist so we removed
the spec but seems to be working as expected using the cli.

Restore npm6/7 yanked version spec

---

go_modules/spec/dependabot/go_modules/update_checker_spec.rb
go_modules/spec/fixtures/projects/missing_meta_tag/go.mod

Spotted this spec has been flaking: https://github.com/dependabot/dependabot-core/pull/3138/checks?check_run_id=1903505156
Looks like archive.org is intermittently failing to serve the request.

Fix go_modules flaky spec accessing archive.org

---

.github/workflows/ci.yml
README.md
bin/docker-dev-shell
bin/dry-run.rb
common/dependabot-common.gemspec

This makes it easy to figure out performance bottlenecks by analyzing
where time is spent in a run. The trace can be visualized by running
`stackprof --d3-flamegraph tmp/stackprof-2021-02-15-13:00.dump > tmp/flamegraph.html`
and viewing that in a browser. For some reason the built in viewer did
not work on my machine, but the d3-generated flamegraph has been clear
enough for me.

Add option to profile dry-run using Stackprof

---

common/lib/dependabot/clients/azure.rb
common/spec/dependabot/clients/azure_spec.rb

Currently for fetch_commit function in azure_client, if the given branch does not exist, then dependabot-core raises error KeyError: Key not found 'commit' instead of Azure::NotFound error.
The ADO api used to fetch branch details returns a status code of 400(Bad Request) instead of 404 because of which it does not raise a Azure::NotFound error.
Added logic in fetch_commit method in Azure client class to raise Azure::NotFound whenever the incoming response is missing commit details.
Tested this locally. Added unit test to verify this behaviour

Raise Azure::NotFound error when branch does not exist

---

npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm7/dev_and_peer_dependency/package.json
npm_and_yarn/spec/fixtures/projects/npm7/duplicate_identical/package.json
npm_and_yarn/spec/fixtures/projects/npm7/minor_version_specified/package.json
npm_and_yarn/spec/fixtures/projects/npm7/non_standard_whitespace/package.json

Updating the `PackageJsonUpdater` specs to use project based spec
fixtures.

PackageJsonUpdater: use project based fixtures

---

hex/helpers/build
hex/spec/dependabot/hex/file_parser_spec.rb
hex/spec/fixtures/mixfiles/nerves

Nerves provides tooling for using Elixir in embedded systems. Using
Dependabot on these projects currently fails with the following error
message:
```
Dependabot can't evaluate your Elixir dependency files.
As a result, Dependabot couldn't check whether any of your dependencies
are out-of-date.
The error Dependabot encountered was:
** (Mix) Archive "nerves_bootstrap" could not be found. Please make sure the archive is installed locally.
```
Adding the `nerves_bootstrap.archive` fixes this issue. This does not
affect projects that do not use the Nerves tooling since the code in the
archive is not called in those cases.

elixir: support projects using Nerves extensions

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

Insert zero-width space in @mentions to prevent sending notifications to
users tagged in changelogs and release notes when email-replying to pull
requests from dependabot.
When sending an email reply to a pull request from dependabot the
contents of the pull request description including changelogs can be
included in the body of the email causing notifications to be sent to
the @mentioned users.
We've previously attempted to fix this by changing @mentions into code
blocks but it seems like the email content is treated as plain text
removing any formatting before detecting usernames.
Ref: https://github.com/dependabot/dependabot-core/pull/2982

Insert zero-width space in @mentions

---

hex/lib/dependabot/hex/file_parser.rb
hex/spec/dependabot/hex/file_parser_spec.rb
python/lib/dependabot/python/file_parser.rb
python/spec/dependabot/python/file_parser_spec.rb

This PR propagates the `reject_external_code` setting and `UnexpectedExternalCode` exceptions to other ecosystems that may execute external/third party code as part of the update process:
* `python`, due to `setup.py` being evaluated
* `hex`, due to `mix.exs` being evaluated from git-sourced dependencies
Unlike `bundler`, there is no attempt at verifying these ecosystems will not execute external code: the exception is always raised if the flag is set.
We intend to improve this on a per-ecosystem basis in follow-up PRs.

python+hex reject_untrusted_code

---

common/dependabot-common.gemspec
common/lib/dependabot/clients/azure.rb
common/lib/dependabot/pull_request_updater.rb
common/lib/dependabot/pull_request_updater/azure.rb
common/spec/dependabot/clients/azure_spec.rb
common/spec/dependabot/pull_request_updater/azure_spec.rb
common/spec/fixtures/azure/create_new_branch.json
common/spec/fixtures/azure/pull_request_details.json
common/spec/fixtures/azure/pull_request_source_branch_details.json
common/spec/fixtures/azure/repo_contents.json
common/spec/fixtures/azure/repo_contents_treeroot.json

Added support for updating pull requests for `azure client (AzureDevOps)`. For updating pull requests (i.e pushing new file changes) implemented the following logic - 
- Check if the `PR & PR source branch` exists. If no, return nil else continue
- Push the new file changes onto the PR source branch.
`Caveat` - Currently the AzureDevOps PR files diff UI shows the diff in commits instead of the actual diff in the file content. Hence, there is a temporary workaround to push file changes to the source branch to ensure the reviewer sees the exact files changes. The workaround is as follows - 
- Create a new temp branch from the PR target branch and push the new file changes in that branch.
- Update the PR source branch head commit to this newly created branch head commit(hence preserving the …

Pull request updater for azure client

---

bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb

To unblock merging work into the default branch.
By updating the expected bundler version in the assertions
related to the failing tests.

test: update assertions to pass

---

bin/docker-dev-shell

When mounting the development environment via `./bin/docker-dev-shell`
the `bundler/helpers` folder is not mounted to the `$CODE_DIR` so
the line `native_spec_helper` that attempts to load one of the files
in that directory will fail.
I add a volume mount point to include the `bundler/helpers` directory
in the `$CODE_DIR`.
Before:
```bash
[dependabot-core-dev] ~/dependabot-core $ cd bundler && bundle exec rspec
An error occurred while loading ./spec/native_helpers/functions/conflicting_dependency_resolver_spec.rb.
Hint: Install the `did_you_mean` gem in order to provide suggestions for similarly named files.
Failure/Error: require "definition_ruby_version_patch"
LoadError:
cannot load such file -- definition_ruby_version_patch
An error occurred while loading …
```

chore: mount bundler/helpers in docker dev container

---

Dockerfile

Attempting to docker build failure seen on CI by forcing http1.1:
https://github.com/dependabot/dependabot-core/pull/3219/checks?check_run_id=2057169372
Specifically this error: `curl: (16) Error in the HTTP2 framing layer`
Ref: https://github.com/CircleCI-Public/circleci-cli/issues/382#issuecomment-688989139

Use --http1.1 when fetching go version

---

bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb

These tests run bundler to check the latest version, but any time this
is updated the test would start to fail
(https://github.com/dependabot/dependabot-core/pull/3235). This change
makes sure that we only check that the version was unlocked by checking
the major version only. If a v3 is ever released this will fail again,
but at least it buys us a bit more time.

bundler: Fix flaky specs by checking major version unlock only

---

Dockerfile

Install bundler 2 and update gem from 3.0.3 to 3.2.14
Bundler 2 is only used to install core's gems when building the image, bundler 1 is still used for all updates.
Once we ship this we can enable bundler v2 support here https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/helpers.rb#L10

Install bundler 2.2.11 and update gem

---

bundler/lib/dependabot/bundler/native_helpers.rb

This fixes a permissions error when vendoring gems, when `GEM_HOME` was
unset it defaulted to `/var/lib` which isn't writeable.
Attempting to fix the discrepancy between ci and updater here:
https://github.com/dependabot/dependabot-core/pull/3279

Bundler: Fix permission error when vendoring gems

---

bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/helpers.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
common/dependabot-common.gemspec
common/lib/dependabot/file_parsers/base.rb
common/lib/dependabot/notifications.rb

Instrument the version of bundler that a package has specified.
This way we can collect metrics about usage of these gems.
This PR implements just a single ecosystem, but we've tried to take into account changes that might be required for other ecosystems. For python, for example, it is possible to have multiple package managers configured, so we instrument a hash of package manager => version.
Planning to have the consumer side of this set up and reporting actual data before adding more ecosystems to the mix.

Instrument bundler version

---

Dockerfile.ci
Dockerfile.development

Updating the dev and ci Dockerfile to match the user permissions set by the updater image.
This reproduces the error seen production when updating a vendored bundler project.
The [failing bundler specs](https://github.com/dependabot/dependabot-core/runs/2122196759) are expected and fixed here https://github.com/dependabot/dependabot-core/pull/3280

Update dev and ci Dockerfile to match updater

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
nuget/spec/fixtures/configs/disabled_sources.config

This prevents disabled package sources, such as those used for doing deploys to private package registries, from being used.
Will read, and disable, any repositories specified in `disabledPackageSources` in `NuGet.Config`, for example, the following `github` package source will not be used:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
<add key="github" value="https://nuget.pkg.github.com/AshleighAdams/index.json" />
</packageSources>
<disabledPackageSources>
<add key="github" value="true" />
</disabledPackageSources>
</configuration>
```
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#disabledpackagesources
~~Though I haven't tested, I strongly suspect that without this change, if a disabled source has a newer dependency version, that …

Add support for disablePackageSources in NuGet.Config

---

.github/workflows/ci.yml
bundler/helpers/v2/.bundle/config
bundler/helpers/v2/.gitignore
bundler/helpers/v2/build
bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/lib/functions/file_parser.rb
bundler/helpers/v2/monkey_patches/definition_bundler_version_patch.rb
bundler/helpers/v2/monkey_patches/definition_ruby_version_patch.rb
bundler/helpers/v2/monkey_patches/git_source_patch.rb
bundler/helpers/v2/spec/functions/file_parser_spec.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/helpers/v2/spec/native_spec_helper.rb
bundler/helpers/v2/spec/shared_contexts.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/spec_helper.rb

Add native helpers for bundler 2 file parsing with testing setup to run bundler specs with both bundler 1 and 2.
The current setup runs all bundler tests twice, sequentially which will add around ~4 mins to the bundler test suite run time.
We could split and run these in parallel or make the bundler 2 tests optional somehow but this also complicates the test setup.

Bundler 2: [Prerelease] Add native helpers for file parsing

---

.github/workflows/ci.yml

Looks like most builds on main are now running out of disk space when
`chown`ing: https://github.com/dependabot/dependabot-core/runs/2168114315
This is a quick fix to try and get builds green. We should look into
removing the need to chown files.

Attempt to fix builds running out of disk space

---

Dockerfile.ci
Dockerfile.development

This reverts https://github.com/dependabot/dependabot-core/pull/3279
It looks like this change has broken ci builds on `main`:
https://github.com/dependabot/dependabot-core/runs/2168623534
Reverting this change until we've figured out a fix for it.

Revert Update dev and ci Dockerfile to match updater #3279

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/private_source_lower/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm6/private_source_lower/package.json

This PR modifies the pattern used by `NpmRcBuilder` to accept `/` characters escaped as lowercase hex. They're the same thing, e.g. `decodeURIComponent('%2F') === decodeURIComponent('%2f')`.
There's a full project harness introduced to exercise this case, which may be overkill:
```
$ diff npm_and_yarn/spec/fixtures/projects/npm6/private_source{,_lower}
diff npm_and_yarn/spec/fixtures/projects/npm6/private_source/package-lock.json npm_and_yarn/spec/fixtures/projects/npm6/private_source_lower/package-lock.json
32c32
<           "resolved": "https://npm.fury.io/dependabot/~/d/%40dependabot%2Fetag/%40dependabot%2Fetag-1.8.1",
---
>           "resolved": "https://npm.fury.io/dependabot/~/d/%40dependabot%2fetag/%40dependabot%2fetag-1.8.1",
```
- Identified …

NpmRcBuilder accept lowercase escaped slash

---

bundler/helpers/v1/run.rb
bundler/helpers/v2/run.rb

I've ran into a few subtle bugs running tests where my environment wasn't set up properly and my native helpers were actually failing over to an unexpected bundler version.
Since a native helper running with the wrong bundler version is likely to fail in subtle ways that might be hard to diagnose, let's force a clear failure if/when it happens.

Avoid subtle runtime failures by raising if a native helper is invoked with the wrong bundler version

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb

This change works toward resolving #3173 with an alternate approach to https://github.com/dependabot/dependabot-core/pull/3251. It maintains grouping of updates so that we can update `php:8.0.1-apache` and `php:8.0.1-cli` in a single PR instead of two as suggested in https://github.com/dependabot/dependabot-core/pull/3251#pullrequestreview-612037713.
Prior to this change if there were multiple tags with different prefixes/suffixes we'd only resolve the latest version for one of them and would end up updating all of the tags to a common version:
```
=== php (8.0.1-apache)
=> latest available version is 8.0.3-apache
=> latest allowed version is 8.0.3-apache
=> requirements update strategy: 
=> updating php from 8.0.1-apache to …
```

docker: consider each requirement when updating dependencies

---

bundler/helpers/v1/build
bundler/helpers/v2/build

Fixes this warning in the build output:
```
[DEPRECATED] The `--without` flag is deprecated because it relies on
being remembered across bundler invocations, which bundler will no
longer do in future versions. Instead please use `bundle config set
--local without 'test'`, and stop using this flag
```

Bundler: fix deprecated --without flag in build

---

bundler/helpers/v1/run.rb
bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/lib/functions/lockfile_updater.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/fixtures/projects/bundler2/git_source_with_multiple_deps/Gemfile
bundler/spec/fixtures/projects/bundler2/git_source_with_multiple_deps/Gemfile.lock

Add native helpers for bundler 2 lockfile updater.

Bundler 2: Add native helpers for LockfileUpdater

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/message_builder.rb

Follows up on: https://github.com/dependabot/dependabot-core/issues/3276
The root cause of the Dependabot service starting to create lots of mentions on downstream GitHub repositories was due to a change to how we used the MessageBuilder class. Let's avoid allowing a nil value for the `github_redirection_service` and promote it to a constant with some explanation for posterity.
It is worth noting, this is a breaking API change for anyone using this class directly, it should be called out in the ChangeLog.

The PR MessageBuilder requires a github_redirection_service to be specified

---

bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/lib/functions/force_updater.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb
bundler/spec/fixtures/projects/bundler1/version_conflict/Gemfile
bundler/spec/fixtures/projects/bundler1/version_conflict/Gemfile.lock
bundler/spec/fixtures/projects/bundler1/version_conflict_mutual_sub/Gemfile
bundler/spec/fixtures/projects/bundler1/version_conflict_mutual_sub/Gemfile.lock

Adding Bundler v2 native helpers for the ForceUpdater.

Bundler [Prerelease]: Add force updater helpers

---

npm_and_yarn/helpers/build

Looks like npm installing the npm_and_yarn helpers is timing out a fair
bit on ci:
https://github.com/dependabot/dependabot-core/pull/3329/checks?check_run_id=2183869598
Seeing errors like:
```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://registry.npmjs.org/@jest/reporters/-/reporters-26.6.2.tgz failed, reason: Socket timeout
```
I also disabled `npm audit` when isntalling which we never look at from
the build output.

Attempt to fix npm install timing out ci builds

---

common/spec/spec_helper.rb
go_modules/spec/spec_helper.rb
nuget/spec/spec_helper.rb
terraform/spec/spec_helper.rb

Calculating code coverage reports isn't free and our CI builds are quite long running as-is.
Let's turn this off for now to save some time as we are not actively pushing coverage right now - individual developers can still generate these reports via:
`COVERAGE=true bundle exec rspec spec`
We can review the status of coverage reporting after making some optimisation passes on builds.

Make code coverage optional via an envvar

---

bundler/lib/dependabot/bundler/file_updater/requirement_replacer.rb
bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb
bundler/spec/dependabot/bundler/file_updater/requirement_replacer_spec.rb

This adjusts the `Dependabot::Bundler::FileUpdater::RequirementReplacer` to adequately ignore `!=` operators within requirements.
Previously the implementation would produce invalid requirements (e.g. for the included test case: `~> 2.0.1, ! 2.0.3, ! 2.0.4`).
This also addresses a nit in the  `Dependabot::Bundler::FileUpdater::RequirementUpdater`: settling on `twiddle` instead of a mix of `twidle`/`twiddle`.

Bundler req replacer not equal

---

bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb
bundler/spec/fixtures/projects/bundler2/bad_ref/Gemfile
bundler/spec/fixtures/projects/bundler2/bad_ref/Gemfile.lock
bundler/spec/fixtures/projects/bundler2/private_git_source/Gemfile
bundler/spec/fixtures/projects/bundler2/private_git_source/Gemfile.lock
bundler/spec/fixtures/ruby/lockfiles/specified_source.lock

Implements remaining native helpers to get the UpdateChecker to work on v2

Bundler 2 [pre-release]: Add UpdateChecker

---

Dockerfile

BUG FIXES
200bee74b #2951 fix(config): accept explicit production=false (@wraithgar)
7b45e9df6 #2950 warn if using workspaces config options in npm config (@ruyadorno)
BUG FIXES
c76f04ac2 #2925 fix(set-script): add completion (@yash-singh1)
0379eab69 #2929 fix(install): ignore auditLevel (@wraithgar)
98efadeb4 #2923 fix(audit-level): add info audit level (@wraithgar)
e8d2adcf4 #2945 config should not error when workspaces are configured (@nlf)
aba2bc623 #2944 fix(progress): re-add progress bar to reify (@wraithgar)
877b4ed29 #2946 fix(flatOptions): re-add _auth (@wraithgar)
BUG FIXES
a4df2b98d #2942 Restore --dev flag, unify --omit flatteners (@isaacs)
DEPENDENCIES
2cbfaac0e hosted-git-info@4.0.2
#83 Do not parse urls for gitlab (@nlf)
FEATURES
33c4189f9 #2864 add npm run-script …

Update npm from 7.6.1 to 7.7.4

---

docker/lib/dependabot/docker/update_checker.rb

Remove an errant `"` included in a string array constant used to derive the `Accept` headers for querying docker registries. Oh Ruby.
```
irb(main):001:0] %w(
irb(main):002:0]           application/vnd.docker.distribution.manifest.v2+json
irb(main):003:0]           application/vnd.docker.distribution.manifest.list.v2+json
irb(main):004:0]           application/json"
irb(main):005:0]         ).join(",")
=> "application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/json\""
```
Many registries don't mind, but this manifests as a `400` response from Artifactory Pro:
```
[dependabot-core-dev] ~/dependabot-core $ curl -H'Accept: application/vnd.docker.distribution.manifest.v2+json, …
```

docker: valid Accept header

---

.github/workflows/ci.yml
bundler/helpers/v2/build

I pushed some breaking changes to the bundler2 implementation in a [WIP branch](https://github.com/dependabot/dependabot-core/pull/3350) in https://github.com/dependabot/dependabot-core/pull/3350/commits/fd3d377c95e3597c42174e1ffe33660cf8b1fa7b but all checks passed unexpectedly.
It seems CI isn't actually setting the `SUITE_NAME` properly at present, so I've cherry picked a fix from my WIP to fix that asap.

Fix bundler2 CI build

---

bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/spec/fixtures/projects/bundler1/jfrog_source/Gemfile

Adds a basic test for the jfrog_source method. I tried to test this from
the core codebase where it's used as well, but due to the current setup
it's currently very hard to do that without connecting to an actual
jfrog server. Since we had no coverage for this before, I'm calling it
an improvement.

Bundler v2 [pre-release]: Add and test jfrog source helper

---

Dockerfile
cargo/spec/dependabot/cargo/file_parser_spec.rb
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
cargo/spec/fixtures/manifests/disabled_feature
cargo/spec/fixtures/manifests/resolver2

With Rust 1.51.0 cargo now supports resolver = "2", which dependabot currently fails to parse.
https://github.com/LiveSplit/livesplit-core/issues/417
```
error: failed to parse manifest at `/home/dependabot/dependabot-updater/dependabot_tmp_dir/Cargo.toml`
Caused by:
feature `resolver` is required
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["resolver"]` to enable this feature
````

Update Rust to 1.51.0

---

common/lib/dependabot/pull_request_updater.rb

`Dependabot::PullRequestUpdater` class was missing the require statement for the azure client implementation for the PR updater which in turn raises a `missing module` error when trying to run pull request updater for azure client
@feelepxyz @jurre FYI

Adding missing azure PR updater reference in Dependabot::PullRequestUpdater

---

gradle/lib/dependabot/gradle/version.rb
gradle/spec/dependabot/gradle/version_spec.rb
maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/version_spec.rb

Add `dev` as a pre-release token for gradle and maven.
Also added `pr` as a pre-release token to maven to align with gradle.
Reported here https://github.com/dependabot/dependabot-core/issues/3255

Treat dev and pr as pre-releases for gradle/maven

---

bin/bump-version.rb

I typically remove those manually as they don't add value to the changelog, but we may as well let the script do it for us

Bump version: Remove merge commits

---

bin/docker-dev-shell

This exports the `LOCAL_GITHUB_ACCESS_TOKEN` from the host machine to the
development container. So that it is easier to export the token into
the shell environment without needing to copy and paste it into the docker
container environment.

export LOCAL_GITHUB_ACCESS_TOKEN to docker dev container

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/invalid_pseudo_version/go.mod
go_modules/spec/fixtures/projects/invalid_pseudo_version/main.go

This helps to raise awareness when a specific resolvability error occurs.
This allows code owners to take corrective action on their go module projects.
It raises an error and discloses the nature of the incompatible pseudo version
detected in a `go.mod` file.

Raise resolvability errors when incompatible pseudo version is detected

---

bundler/spec/dependabot/bundler/file_fetcher/gemspec_finder_spec.rb
bundler/spec/fixtures/projects/bundler1/imports_gemspec_from_nested_path/nested/Gemfile
bundler/spec/fixtures/projects/bundler1/imports_gemspec_from_nested_path/nested/Gemfile.lock
bundler/spec/fixtures/projects/bundler1/imports_gemspec_from_nested_path/nested/subdir/example.gemspec

Breaks out from https://github.com/dependabot/dependabot-core/pull/3350
Follows on from https://github.com/dependabot/dependabot-core/pull/3381

Use project fixtures for GemspecFinder spec

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/unknown_revision_version/go.mod
go_modules/spec/fixtures/projects/unknown_revision_version/main.go

Changes the go mod updater error handling to fall back to matching the
whole string if no lines where matched against the regex.
Some errors where surfacing with an empty error message as we initially
match on the whole string but filter per line.

Go mod: Handle multi-line error messages

---

bundler/spec/dependabot/bundler/update_checker/conflicting_dependency_resolver_spec.rb
bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb

Update the ForceUpdater and ConflictingDependencyResolver specs to use
the `bundler_project_dependency_files` helpers paving the way for
multiple bundler versions.

Bundler: Use project fixture helpers in specs

---

Dockerfile

This moves `software-properties-common`  to earlier in the `Dockerfile`.
This package provides the `apt-add-repository` used by setup PPAs used by several ecosystems: `ruby`, `php`. Since the package is part of baseline ubuntu, we can install it in the first layer to avoid a duplicate `apt-get update`.
I opted to place it before `make`, so the preceding "things after `make` are for python" comment was still valid.

Dockerfile: promote software-properties-common

---

bundler/helpers/v2/run.rb
bundler/lib/dependabot/bundler/helpers.rb
bundler/spec/dependabot/bundler/helper_spec.rb

Depends on https://github.com/dependabot/dependabot-core/pull/3406
This modifies the `bundler_2_available` option so it no longer forces use of the bundler 2 native helpers but rather decides based on the lockfile if present.
The primary change is to expand and test the `Dependabot::Bundler::Helper` to clearly specify scenarios such as defaulting to the newest when no Lockfile is present and failing over to v1 if a file is present but appears to pre-date the `BUNDLED_WITH` notation.
This also clarifies how Dependabot will behave if a new/malformed Gemfile.lock version were to appear.

Bundler 2 [pre-release]: Detect bundler version to use when bundler 2 is available

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

When we pull in changelogs and commits etc we sanitize user mentions
(`@jurre`), by wrapping them in a codeblock and inserting a zero-width
space between the `@` and the username, and wrapping that in a link to
the profile, to prevent users from getting notifications from Dependabot PRs.
Something that we didn't cover before yet were team-mentions, e.q:
@dependabot/reviewers. These are slightly tricky in the sense that there
are ecosystems (npm for example) that have package names that follow the
same pattern. There is no way to distinguish between a package name and
a team mention, so we treat them the same and sanitize them but do not
attempt to link, as this is expected to lead to a lot of false
positives.
Fixes https://github.com/dependabot/dependabot-core/issues/3378

Pull Requests: Sanitize team mentions

---

bundler/spec/spec_helper.rb

This branch inverts our current default testing behaviour to use bundler2 by default since it is the latest release.
This mostly impacts developer workflows where it is anticipated they won't set the SUITE_NAME flag unless specifically testing a bunder 1-specific change.
This will have no affect on CI but just sets the expectation that in future, the builder1 CI build is a regression test and all new work will focus the latest release.

If SUITE_NAME is not specified, default to bundler2

---

.github/workflows/ci.yml
Dockerfile.ci
bundler/script/ci-test
cargo/script/ci-test
common/script/ci-test
composer/script/ci-test
dep/script/ci-test
docker/script/ci-test
elm/script/ci-test
git_submodules/script/ci-test
github_actions/script/ci-test
go_modules/script/ci-test
gradle/script/ci-test
hex/script/ci-test
maven/script/ci-test
npm_and_yarn/script/ci-test
nuget/script/ci-test
omnibus/script/ci-test
python/script/ci-test
terraform/script/ci-test

Currently in the CI container we bundle install for _every_ package,
this ends up taking 4 to 5 minutes on every build for every ecosystem.
Since the tests are split up per ecosystem, we only need to install the
gems for the package that is being tested in this matrix step.
This also introduces a `script/ci-test` per ecosystem, it currently runs
both rubocop and rspec for all ecosystems, but the expectation is that
these scripts might diverge per ecosystem.
Running both rspec and rubocop in the same script is done to prevent us
from having to `bundle install` for each of those steps.
We could take this approach a step further and split out a CI container
per ecosystem, and that would let us run rubocop and rspec as separate
steps, but I don't think this is currently worth it.
This should …

CI: Only bundle install for ecosystem under test

---

.github/workflows/ci.yml

This was only added because of the changes here
https://github.com/dependabot/dependabot-core/pull/3279 which where
reverted here https://github.com/dependabot/dependabot-core/pull/3320
This step sometimes takes over a minute.

CI: Remove step freeing up disk space

---

.github/workflows/ci.yml
bundler/script/ci-test
npm_and_yarn/script/ci-test
python/script/ci-test

We were setting up a bunch of conditional tests/linting in the workflow
file, but now that we have test scripts I think it's cleaner to run
those inline in the `script/ci-test` script

CI: Simplify workflow by moving suite specific tests into test script

---

Dockerfile.ci

I hacked together a little script to figure out which python versions
we're actually installing in our test suite, turns out it's not that
many:
https://github.com/dependabot/dependabot-core/pull/3425/commits/9f7251b423dccd474077da9227c3dbfb14f3535f
But this leads to almost 10 minutes of time spent _every python run_.
This change runs the install steps in the CI Dockerfile so they can be
cached.
It does nothing to prevent newer versions from python being added in new
tests, but it's a fairly safe way to shave 10 minutes of the build.

CI: Pre-install python versions used in tests

---

bin/dry-run.rb

Modifies the dry-run script so that when the `--pull-request` argument is passed, the GitHub pull request message is rendered to stdout.
This is a regression from #3301 , that only affected an infrequent path for development.

dry-run: redirection-service

---

.github/workflows/ci.yml
.github/workflows/docker.yml
Dockerfile.ci
bin/docker-dev-shell

Leverage Docker's buildkit caching when building `Dockerfile.ci`.
Using docker volumes instead of copying all the files over to the ci image as the buildkit cache was previously hanging when building the ci image.
The caching change was previously [reverted in this commit](a89aca9#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f).

CI: Use buildkit caching when building Dockerfile.ci

---

maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/version_spec.rb

When comparing a string version with one that can be coerced to an
integer, we would call `<=>` on two different types, resulting in `nil`
values that would raise errors further up the call stack.
This introduces a change to only coerce these values to ints if we can
do this on both, and perform a string comparison otherwise.
Fixes: https://github.com/dependabot/dependabot-core/issues/2992

Maven: fix error when comparing string and integer versions

---

.github/workflows/ci.yml
.github/workflows/docker.yml

When building images with the buildkit inline cache and using
`--cache-from` when building docker should be smart enough to only pull
the layers it needs so we don't need to do a full docker pull up front.

CI: Rely on cache-from instead of pulling

---

cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb
cargo/lib/dependabot/cargo/version.rb
cargo/spec/dependabot/cargo/update_checker/requirements_updater_spec.rb
cargo/spec/dependabot/cargo/version_spec.rb

This PR amends the cargo updater to handle target versions with a build annotation, such as `1.5.0+build.1`.
First: there are several calls to `Cargo::Version#correct?` that probably expect to be validated against the regexp in `Cargo::Version`, but are actually evaluated against `Gem::Version`. The biggest implication of this bug is that the `RequirementsUpdater` will silently ignore the upgrade - so `Cargo.lock` will be updated but `Cargo.toml` will be unaffected:
* https://github.com/dependabot/dependabot-core/blob/2e5dd943912f005208ea1b43a5e4ad164029d96e/cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb#L31
* https://github.com/dependabot/dependabot-core/blob/2e5dd943912f005208ea1b43a5e4ad164029d96e/cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb#L42 …

cargo: support build annotations

---

Dockerfile.ci

In https://github.com/dependabot/dependabot-core/pull/3431 we introduced
some pre-installed versions of Python in an effort to speed up our test.
@brrygrdn rightfully pointed out it'd be good to add a note as to why
this is here. This is said note.

[ci skip] Explain pre-installed pythons in Dockerfile.ci

---

bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/file_updater.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/helpers.rb
bundler/lib/dependabot/bundler/update_checker/conflicting_dependency_resolver.rb
bundler/lib/dependabot/bundler/update_checker/force_updater.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/dependabot/bundler/file_updater_spec.rb
bundler/spec/dependabot/bundler/helper_spec.rb
bundler/spec/dependabot/bundler/update_checker/conflicting_dependency_resolver_spec.rb
bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb

Update dependabot-bundler to support V2 by default

Clean up feature flag protecting use of Bundler v2

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

To handle job failures due to network issues causing errors like `fatal: The remote end hung up unexpectedly`.
Example jobs:
* 109068953
* 109064542
* 109050277
* 109043842
* 109043677
E.g.
```plaintext
Error processing k8s.io/cri-api (Dependabot::DependabotError)
go: github.com/containers/podman/v3@v3.1.0 requires
gopkg.in/check.v1@v1.0.0-20200227125254-8fa46927fb4f: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in <snip> exit status 128:
fatal: The remote end hung up unexpectedly
```
```plaintext
Error processing k8s.io/cli-runtime (Dependabot::DependabotError)
go: github.com/spf13/viper@v1.7.1 requires
github.com/grpc-ecosystem/grpc-gateway@v1.9.0 requires
gopkg.in/yaml.v2@v2.0.0-20170812160011-eb3733d160e7: invalid version: git fetch …
```

fix(Go mod): detect when remote end hangs up

---

common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb

To detect out of disk errors and fail gracefully.
It rescues `Errno::ENOSPC` and converts it to a `Dependabot::OutofDisk` error.
Example:
From job id `109063142`.
```plaintext
ERROR <job_109063142> Error processing github.com/sirupsen/logrus (Errno::ENOSPC)
ERROR <job_109063142> No space left on device @ fptr_finalize_flush - /home/dependabot/.gitconfig
ERROR <job_109063142> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.2/lib/dependabot/shared_helpers.rb:171:in `close'
ERROR <job_109063142> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.2/lib/dependabot/shared_helpers.rb:171:in `open'
ERROR <job_109063142> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.2/lib/dependabot/shared_helper …
```

fix: detect No Space errors

---

gradle/dependabot-gradle.gemspec

In https://github.com/dependabot/dependabot-core/pull/3403 we added a dependency on `dependabot-maven` from the `dependabot-gradle` gem.
To ensure that the `dependabot-maven` gem is installed when we install the `dependabot-gradle` gem we need to declare `dependabot-maven` as a runtime dependency.

Add dependency to dependabot-maven from dependabot-gradle

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

To detect module mismatch errors when resolving dependencies with `go mod`.
E.g. Job id: 109392653
```bash
Error processing github.com/aws/amazon-ecs-agent (Dependabot::DependabotError)
go: downloading github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/awslabs/go-config-generator-for-fluentd-and-fluentbit v0.0.0-20210308162251-8959c62cb8f9
go: downloading github.com/containernetworking/plugins v0.9.1
go: downloading github.com/etcd-io/bbolt v1.3.5
go: downloading github.com/vishvananda/netlink v1.1.0
go get: github.com/etcd-io/bbolt@none updating to
github.com/etcd-io/bbolt@v1.3.5: parsing go.mod:
module declares its path as: go.etcd.io/bbolt
but was required as: …
```

fix(go mod): capture module mismatch error

---

Dockerfile

Continuing Dockerfile cleanup, let's do a shallow clone of `pyenv`.
That means instead of fetching the repository and checking out the branch we'd like to use, we'll fetch only the branch we'd like to use.
<details><summary>this only trims 4MB, but is trivial</summary>
<p>
</p>
</details>

pyenv: shallow clone

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/package_json_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/metadata_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/peer_dependency/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm6/peer_dependency_multiple/package-lock.json

Previously there was some logic in place to determine if a package came
from a public package repo or not, and if it came from a registry
considered central/public, we would not parse its source.
However, in the case of private packages that specify yarnpkg.com as
their source, this resulted in some calls expecting that package to
exist on npmjs.org, which it technically is (yarnpkg.com is a proxy for
it), but we would have no credentials configured for npmjs.org, so those
requests will fail.
This PR changes that behavior to always parse a package's source and add
it to the requirement if it exists. We previously only did this for
registries we considered "private", hence the name `private_registry`,
but since we cannot reliably determine if a package hosted on
`yarnpkg.com` or …

npm/yarn: Always use registry source when available

---

Dockerfile

Running composer update to warm the cache which was previously done in
an upstream image along with installing ca-certificates explitly.

Cache composer installs & install ca-certificates

---

Dockerfile

Seems like https://github.com/dependabot/dependabot-core/pull/3398 ended up breaking some scripts that were using the dependabot-core image (such as https://github.com/wemake-services/kira-dependencies and https://github.com/dependabot/dependabot-script). Seems like someone just forgot to set the `WORKDIR` which causes `pwd` to be `/`, which causes dependabot to fail to bundle install, since it doesn't have permission to write to `/`. This just sets the `WORKDIR` to the dependabot's home directory so that all of the bundler stuff ends up in a place that dependabot owns.
~~Note that now the bundler env variables are no longer needed, since they will just go into dependabots home directory.~~ They are still needed, but I moved the directories to be in dependabot's home directory.
I tested …

set Dockerfile WORKDIR to /home/dependabot to avoid permission errors when consumers of the dependabot-core image run bundle install

---

common/lib/dependabot/clients/azure.rb
common/lib/dependabot/errors.rb
common/lib/dependabot/pull_request_updater/azure.rb
common/spec/dependabot/clients/azure_spec.rb
common/spec/dependabot/pull_request_updater/azure_spec.rb
common/spec/fixtures/azure/update_ref.json
common/spec/fixtures/azure/update_ref_failed.json

Added logic in the azure PR updater to raise an error of type `Dependabot::PullRequestUpdateFailed` when the update ref call to update the source branch is unsuccessful. Currently the update_ref API in azure returns a 200 response code even when the update operation is unsuccessful hence need to check the response body to verify if the update operation is successful
@feelepxyz @jurre Does this way of error handling makes sense? Apologies for creating a separate PR for this small change

Add error handling for failure while updating Pull request in azure

---

Dockerfile

Changes since 7.7.4: https://github.com/npm/cli/blob/latest/CHANGELOG.md
* [`f9b639eb6`](https://github.com/npm/cli/commit/f9b639eb6c504ded6cdd59e83e26a392bfe81e5d)
[#3052](https://github.com/npm/cli/issues/3052)
feat(bugs): fall back to email if provided
([@Yash-Singh1](https://github.com/Yash-Singh1))
* [`8c9e24778`](https://github.com/npm/cli/commit/8c9e24778db867cb3148bc247c7e321639aa9f58)
[#3055](https://github.com/npm/cli/issues/3055)
feat(version): add workspace support
([@wraithgar](https://github.com/wraithgar))
* [`f1e6743a6`](https://github.com/npm/cli/commit/f1e6743a6e8e32ddad6d1964eb05d17e6c50a456)
`libnpmversion@1.2.0`
* feat(retrieve-tag): retrieve unannotated git tags
* fix(retrieve-tag): use semver to look for semver
* …

Update npm from 7.7.4 to 7.10.0

---

bundler/helpers/v1/lib/functions.rb
bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/update_checker/conflicting_dependency_resolver.rb
bundler/lib/dependabot/bundler/update_checker/force_updater.rb
bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb

Removing the bundler 2 config changes that we prevously did in the v1
helpers. This codepath should no longer be hit as we invoke the v2
helpers if the lockfile uses bunder 2.
I've also changed the native helper args to take a hash making it less brittle when removing attributes and you run a different version of the gem to the docker image, which was reported in the past https://github.com/dependabot/dependabot-core/issues/2879

Remove unused bundler v2 codepath 

---

common/lib/dependabot/pull_request_creator/branch_namer.rb

Added a separate method name `branch_version_suffix` which basically gets the version related suffix for the branch name. We need to use this function in our own service hence created a separate method for this. @feelepxyz @jurre Does adding this refactoring in dependabot-core make sense?

Refactoring new_branch_name function in branch_namer

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb

Go 1.16 added an option to instruct `go mod tidy` to make a best effort
to update the `go.sum` file in spite of errors for specific packages as
described in the commit the old comment pointed to:  https://github.com/golang/go/commit/3aa09489ab3aa13a3ac78b1ff012b148ffffe367
This adds said flag, now that we're on go 1.16
Edit: should we add a test that demonstates the new behavior?

Gomod: Run `go mod tidy` with flag to allow errors

---

common/lib/dependabot/pull_request_creator/branch_namer.rb

This is an automated `rubocop -A` addressing a no longer necessary lint disabling.
I thought it was just a hiccup in my environment, but https://github.com/dependabot/dependabot-core/pull/3521/files#diff-cb18ce6ed14510cf237cf0615d847f2f84564cd4b13c438dbffbb6a2702eb1e1 does this too. It's not just me!

branch_namer PerceivedComplexity

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/gems.yml

Following this change: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
We only need to clone repos in `ci.yml` tests so `contents: read` should
be enough.

Restrict permissions for actions workflows

---

bin/dry-run.rb
common/lib/dependabot/config/file.rb
common/lib/dependabot/config/update_config.rb
common/spec/dependabot/config/file_spec.rb
common/spec/dependabot/config/update_config_spec.rb
common/spec/fixtures/configfile/npm-weekly.yml

This shifts the `Dependabot::Config::UpdateConfig` class introduced by https://github.com/dependabot/dependabot-core/pull/3512 from being a shallow facade over an entry in the `updates:` configuration, to a plain old ruby object.
Parsing is migrated to the `Dependabot::Config::File` class, which makes sense as the owner of parsing+translation.
I also removed `Dependabot::Config::UpdateConfig#interval`. As discussed in the earlier PR, it only existed to provide a unique attribute on `.updates[]` parsed from the config file. By using the `#commit_message_options` this can be accomplished with less cruft.
- Continues https://github.com/dependabot/dependabot-core/pull/3512
- Discussed https://github.com/dependabot/dependabot-core/pull/3521
- Conflicts …

UpdateConfig ruby-er model

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
gradle/lib/dependabot/gradle/requirement.rb
gradle/lib/dependabot/gradle/version.rb
gradle/spec/dependabot/gradle/requirement_spec.rb
gradle/spec/dependabot/gradle/version_spec.rb
maven/lib/dependabot/maven/requirement.rb
maven/spec/dependabot/maven/requirement_spec.rb
maven/spec/dependabot/maven/version_spec.rb

Fixes a few bugs discovered from https://github.com/dependabot/dependabot-core/pull/3368
For reasons I don't yet understand, the bundler latest version finder doesn't declare `requirement_class` but passes specs testing ignored versions but if I `byebug` inside the method during the test it explodes with an exception saying it's undefined.
I also discovered we didn't properly handle for the case where a maven/gradle version requirement is created from a pull request ignore with ruby style requirements but with a maven style version, e.g. `>= Finchley.a, < Finchley.999999`.

Fix regressions from ignore version refactor

---

go_modules/lib/dependabot/go_modules/update_checker.rb

There's clearly a typo here, but I'm less clear on what the intended wording was:
* we either use the commit sha or the tag name
* we use the commit sha of the tag name
These have very different meanings... I picked one, but I may be wrong, as I've never written Ruby, so kinda spitballin' here.
Let me know if I should reword different.

Fix typo to clarify meaning

---

.github/ISSUE_TEMPLATE/migration-issue.md

Template to point folks to for any issues that may arise when migrating from Preview to GitHub-native Dependabot (e.g. via clicking "Update config file" on https://app.dependabot.com).
Captures general information about the ecosystem/manifest/etc. as well as Preview and GitHub-native behavior.

Add a preview-migration issue template

---

common/lib/dependabot/config/file.rb
common/lib/dependabot/config/ignore_condition.rb
common/spec/dependabot/config/file_spec.rb
common/spec/dependabot/config/ignore_condition_spec.rb
common/spec/dependabot/config/update_config_spec.rb

Moving the update_types transform from the config file parser to the
ignore condition making it easier to initialize IgnoreCondition without
fetching a config file.
Working towards being able to do this:
```ruby
ignore_conditions = ignore_conditions.map do |ic|
Dependabot::Config::IgnoreCondition.new(
dependency_name: ic["dependency-name"],
versions: [ic["version-requirement"]],
update_types: ic["update-types"],
)
end
Dependabot::Config::UpdateConfig.
new(ignore_conditions: ignore_conditions).
ignored_versions_for(dependency)
```

Transform update_types in IgnoreCondition

---

go_modules/helpers/go.mod
go_modules/helpers/go.sum
go_modules/helpers/updater/go.mod
go_modules/helpers/updater/go.sum

Since `go.mod` in the root of helpers declares itself as:
```
module github.com/dependabot/dependabot-core/go_modules/helpers
```
then my understanding is there's no need to have custom replace
directives... `go` is smart enough to realize that these are local pkgs
and should be imported locally.
As a result, we also no longer need a custom `go.mod` file within the
subpackage.
Which makes life easier as this subpackage declared an older version of
the extracted go modules repo... which works, but can be confusing since
there are two `go.mod` files with slightly different minimum supported
versions. Avoid all that by treating this as a package of the parent
modules rather than a standalone module.

Cleanup go.mod handling of helpers

---

go_modules/helpers/Makefile
go_modules/helpers/build

`go` `1.16` flipped the default for `GO111MODULE` to `on`. So now that
ci targets `go` `1.16`, this is no longer needed.
Similar cleanup could be done for `dep`, but that is deprecated and will
soon be deleted, so I skipped it.

Drop GO111MODULE env var now that it defaults to `on`

---

go_modules/helpers/updater/helpers.go

`git blame` looks like the only change was https://github.com/golang/mod/commit/788aebd06792f833c387fcee8647edac94108a98
Added a "sync date/commit sha" so that it's easier to see when these were last updated.

Sync copy/pasted private methods with upstream

---

go_modules/helpers/go.mod
go_modules/helpers/go.sum
go_modules/helpers/updater/go.mod
go_modules/helpers/updater/go.sum

This isn't strictly required, but it makes life simpler in some edge
cases... and also later someone is considering updating, it's easier if
this has been kept up to date all along so the delta is smaller down the
road. I ran `go mod tidy` and it didn't update the `go.sum` file here
(sometimes it does when you bump this directive).
Note: This depends on https://github.com/dependabot/dependabot-core/pull/3576, as that reduced the number of `go.mod` files that needed this update. 
If that is rejected, then this change should be applied to the other `go.mod` files that weren't removed.

Bump the go directive to 1.16

---

gradle/lib/dependabot/gradle/file_parser.rb
gradle/spec/dependabot/gradle/file_parser_spec.rb

In `Dependabot::Gradle::FileParser`, there's an assumption that any package that begins with `com.github.*` is backed by a git repository.
This has implications in `Dependabot::Gradle::UpdateChecker`, where it means Dependabot will prefer to [check the git repository's commit history](https://github.com/dependabot/dependabot-core/blob/cd9fb4106bf9176304fe549532edc1249d57abcc/gradle/lib/dependabot/gradle/update_checker.rb#L147-L150) in place of querying the maven repository for the latest version.
This was intended to integrate with https://jitpack.io/ , a service that builds Java artifacts directly from commits. This can be confirmed by inspecting the repository in the test case: https://github.com/heremaps/oksse suggests Jitpack to consume artifacts.
Using the `GitCommitChecker` makes …

gradle: only commit versions are git sourced

---

go_modules/helpers/updater/main.go

Looking at the source of `AddRequire`, it looks like it never actually returns a non-`nil` error: https://github.com/golang/mod/blob/858fdbee9c245c8109c359106e89c6b8d321f19c/modfile/rule.go#L828-L846
However, they wrote the func signature to return an `err` to give themselves future flexibility.
So we should respect that and check for any unexpected errors. This way future updates that
suddenly start returning errors will be caught rather than insidiously slipping by and causing
difficult-to-debug issues elsewhere.

Check the err returned by AddRequire

---

README.md

I'd completely overlooked that the `## Local Development` section of the Readme documents how to run tests.
So enhance the discoverability of this slightly.
Fix #3601.

Document how to run tests within the dev docker container

---

go_modules/helpers/main.go

idiomatic `go` generally prefers uncapitalized error strings:
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Make error output more idiomatic

---

common/lib/dependabot/config/ignore_condition.rb
common/spec/dependabot/config/ignore_condition_spec.rb

When handling the relative `version-update:semver-patch` ignore condition we were generating an ignored version range that included the current version. This was causing the latest allowed version to resolve to a prior version when running an update:
```
=== ssri (8.0.0)
=> latest available version is 7.1.0
=> latest allowed version is 7.1.0
```
This tweaks the starting range of the ignore condition so that the current version is excluded:
```
=== ssri (8.0.0)
=> latest available version is 8.0.0
=> latest allowed version is 8.0.0
```
I also added some tests to verify we didn't exclude the current version when ignoring minor or major ranges.

IgnoreCondition: don't ignore current version when ignoring patches and handle multi-length semver ranges

---

python/helpers/lib/parser.py
python/spec/dependabot/python/file_parser/setup_file_parser_spec.rb
python/spec/fixtures/setup_files/with_comments.cfg

Currently any comments in a setup.cfg file will raise an error in
Dependabot. Pip handles this fine, so let's make sure Dependabot does as
well.
Fixes https://github.com/dependabot/dependabot-core/issues/3619

Python: allow comments when parsing setup.cfg

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/replace_stubber.rb
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/replace_stubber_spec.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb
go_modules/spec/fixtures/projects/unknown_vcs/go.mod
go_modules/spec/fixtures/projects/unknown_vcs/main.go
go_modules/spec/fixtures/projects/unrecognized_import/go.mod
go_modules/spec/fixtures/projects/unrecognized_import/go.sum
go_modules/spec/fixtures/projects/unrecognized_import/main.go

This PR makes two adjustments to the handling of `go_modules` updates.
1. Introduce `Dependabot::GoModules::ReplacementStubber` as shared logic for how local paths outside of the current checkout should be stubbed. This wasn't _too_ bad, until https://github.com/dependabot/dependabot-core/pull/2848 upgraded the `GoModUpdater` implementation without updating the `FileParser`. Bring them back in sync.
2. Ignore any dependencies in `go.mod` that aren't valid hosts, since they'll be [rejected by the go SDK](https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/cmd/go/internal/vcs/vcs.go#L931-L933).
This fixes projects like [cloudfoundry-incubator/backup-and-restore-sdk-release/src/s3-blobstore-backup-restore](https://github.com/cloudfoundry-incubator/backup-and-restore …

go_modules: stub consistently and ignore invalid modules

---

common/lib/dependabot/config/ignore_condition.rb
common/lib/dependabot/config/update_config.rb
common/spec/dependabot/config/ignore_condition_spec.rb
common/spec/dependabot/config/update_config_spec.rb

Handle a `nil` dependency version when computing ignored versions from
ignored update types.
When we can't reliably figure out the exact version of a dependency
(e.g. it doesn't have a lockfile), we just leave the
`dependency.version` as nil.

Ignored update types: handle nil dep version

---

common/lib/dependabot/pull_request_creator/github.rb

This is a workaround to the proposed upstream fix, https://github.com/octokit/octokit.rb/pull/1336.
Consider a dependency named `github.com/football-refs/league-rules`.
As part of an upgrade, Dependabot might attempt a branch like `dependabot/go_modules/github.com/football-refs/league-rules/2.0.0`.
Since that matches `refs/`, it won't automatically have `refs/` prepended, ultimately resulting in a `Octokit::UnprocessableEntity`.

GitHub PullRequestCreator: prepend refs/

---

go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

This fixes a change in behavior introduced in https://github.com/dependabot/dependabot-core/pull/3631.
The previous behavior filtered lower versions but did not filter out the current version of the dependency. This adjusts the ruby implementation of the filter to allow the current version.

go_modules: don't filter the current version

---

.rubocop.yml

To respect line widths, ensure consistent indentation and help those who
need to use a bigger font to read code.
It enforces a `consistent` indentation setting via RuboCop.

style: use consistent indentation for first element

---

python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb

I believe I have stumbled across a bug in check_original_requirements_resolvable in the pip-compile version resolver.
I think the error is that the pip-compile command runs here without the relevant options that it runs with in all other contexts. This can mean, for example, that this command can fail when requirements contain libraries that are present only in a private repository and not on the public PyPi.
I can see three ways to resolve this:
1. Add the call to the relevant function when running pip-compile. This is the simplest and what I've opened initially, for discussion.
2. Make a function that returns the full pip-compile-with-options command that should be used everywhere, so you don't have to remember to add the option
3. Write a local pip.conf file and ensure it's picked up …

Run all pip-compile commands with options

---

.github/workflows/ci.yml
terraform/helpers/build
terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/projects/hcl2/main.tf
terraform/spec/spec_helper.rb

To gradually introduce tooling and changes needed to support HCL v2.0.
This change will let us run the old codepath in production, while we merge in small portions of tests and functionality for HCL2 support, keeping those PRs small and  focussed to make them easier to review.
We currently do not plan to toggle/feature flag between the codepaths in production, but once hcl2 support is ready, we'll flip the option to default to the new binary and code, and once we verify that runs successfully in production we can clean out the old code.
This inserts a test suite and feature toggles that can be used to toggle between
which parsing tools to use.
/xref: https://github.com/github/dependabot-updates/issues/1422
HCL1:
```bash
[dependabot-core-dev] ~/dependabot-core/terraform $ …
```

Run terraform specs against both old and new HCL2 compatible binaries

---

terraform/spec/dependabot/terraform/file_updater_spec.rb

The multiline strings where a little hard to read, this changes them
into heredocs, which keeps the original indentation etc intact, making
it easier to figure out what we expect the content to be.
Co-authored-by: nishnha <nishnha@github.com>

Terraform: Clarify FileParser expectations in specs

---

.github/dependabot.yml

Dependabot version updates [supports updating GitHub Actions workflow files](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#package-ecosystem).
Dependabot-core [has GitHub Actions workflow files](https://github.com/dependabot/dependabot-core/tree/main/.github/workflows).
We should use Dependabot version updates to maintain dependabot-core's workflow files!
This feels good, but shouldn't have any immediate impact (as all actions use major-level tags).
```
.github/workflows/gems.yml:        uses: actions/checkout@v2
.github/workflows/gems.yml:      - uses: actions/setup-ruby@v1
.github/workflows/docker.yml:        uses: actions/checkout@v2
.github/workflows/ci.yml:        uses: actions/checkout@v2
```
- Discovered …

dependabot.yml: enable github_actions ecosystem

---

github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

This corrects a regression in the `github_actions` ecosystem, where a change to extend semver support had an unintended effect:
In Actions, it's common to maintain a mutable tag, like [actions/setup-node@v2](https://github.com/actions/setup-node/releases/tag/v2), in addition to full semver tags like [v2.1.5](https://github.com/actions/setup-node/releases/tag/v2.1.5).
By more aggressively interpreting refs as semver, Dependabot began proposing those mutable semver tags be upgraded to the "latest" version, since `v2 == v2.0.0`, which is `< v2.1.5`.
To resolve this, there's an added check in `Dependabot::GithubActions::UpdateChecker`, such that if the specified version is a shortened but equivalent semver tag,  any potential upgrade is ignored.
Corrected case, `actions/setup-node@v2`
```
=== …
```

GitHub actions: skip equivalent shorter semver tags

---

bin/dry-run.rb
terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/spec_helper.rb

Switches the feature flag for HCL to use HCL2 as the default in Terraform's `FileParser`.
- The HCL1 parser can be enabled by setting the LEGACY_TERRAFORM environment variable to 'true'.

Switch HCL2 parser to be the default

---

hex/lib/dependabot/hex/update_checker/version_resolver.rb

Fixes broken hex specs: https://github.com/dependabot/dependabot-core/pull/3719/checks?check_run_id=2581264410
Handle hex errors that return valid json, e.g. `{"error":"Dependency resolution failed: Can't continue due to errors on dependencies"}`
Previously we only checked if the sub-process output was parseable and tried to get the `result` key, but this will just return nil if the json is valid.
For context, valid results look like `{"result":"1.3.6"}`

Hex: Fix version resolver specs

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb

I ran across this comment on an old PR while researching https://github.com/dependabot/dependabot-core/pull/3590/.
The comment seems very useful/easy to overlook, so thought I should add it here.

Add helpful comment

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package_top_level/api/package.json
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package_top_level/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm7/workspace_nested_package_top_level/package.json

Handle nested workspace dependencies that have been installed in the
top-level `node_modules` folder instead of the nested
`workspace/node_modules` folder.
While this case returned `nil` previously, we still ended up extracting
lockfile details for the dependency by checking all instances of the
same dependency and picking the lowest version, meaning the `from`
version in updates was incorrect.
It seems this happens when the package is only installed once, so
doesn't end up having several versions across different pacakges.

npm: Handle workspace deps installed top-level

---

terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/registry_provider/main.tf

Previously we would match for any `version` string, and this would end
up matching on `required_version`, and we'd fail to update these
configs.

Terraform: Improve updating provider requirements

---

Dockerfile

This allows for better caching and also gives us more information when
one of these build steps fails.

Dockerfile: split up native helper build steps

---

terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/registry_provider/main.tf

Previously, the regex we used to figure out which part of the codebase
to run the replace on was too broad, and would include the entire
`required_providers` block, which results in the replace only working on
the first provider in the file.
This adds a new regex to use for provider updates, which will find the
specific provider within the `required_providers` block.
Fixes https://github.com/dependabot/dependabot-core/issues/3760

Terraform: Fix updating multiple providers

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
cargo/spec/dependabot/cargo/update_checker/latest_version_finder_spec.rb
composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb
elm/lib/dependabot/elm/update_checker.rb
elm/spec/dependabot/elm/update_checker_spec.rb
gradle/lib/dependabot/gradle/update_checker/version_finder.rb
gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb
python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb

Handle the `dependency.version` being nil, which it might be when the
version isn't known because there's now lockfile.

Handle nil version when raising AllVersionsIgnored

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

Handle multiple sources in the update checker, following on from https://github.com/dependabot/dependabot-core/pull/3718 where we started doing this.

npm: Handle multiple sources in the update checker

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/v1/vcs_source_unreachable/composer.json
composer/spec/fixtures/projects/v1/vcs_source_unreachable/composer.lock
composer/spec/fixtures/projects/vcs_source_unreachable/composer.json
composer/spec/fixtures/projects/vcs_source_unreachable/composer.lock

Relax the error message matching when a git source is unreachable as
it's subtly different when speciyfing the source under `repositories`
with `type: git` (erroring with `... --mirror 'url..'`) and `type: vcs`
(erroring with `... --mirror -- 'url..'`).

Composer: handle unreachable git vcs source

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/provider_implicit_source/main.tf

When leaving out a `source = ..` declaration for a Terraform provider,
it falls back to assuming the default `hashicorp` namespace and the
declared local name as the package name.
This is unrecommended, but we do come across it.
Previously Dependabot would fail, with this change it parses + updates
these cases correctly.

Terraform: handle implicit (v0.12 style) provider sources

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/projects/pessimistic_constraint_lock_file/.terraform.lock.hcl
terraform/spec/fixtures/projects/pessimistic_constraint_lock_file/main.tf
terraform/spec/fixtures/projects/private_registry/main.tf
terraform/spec/fixtures/projects/private_registry_pessimistic_constraint/main.tf

To parse the version from the [terraform lock file][lock_file] so that
the correct version is compared against the eligible versions.
fixes:
```bash
updater | INFO <job_139154747> Starting job processing
updater | INFO <job_139154747> Starting update job for dsp-testing/dependabot-updates-1480
updater | INFO <job_139154747> Checking if hashicorp/aws ~> 3.0 needs updating
proxy | 2021/05/25 19:31:39 [012] GET https://registry.terraform.io:443/v1/providers/hashicorp/aws/versions
proxy | 2021/05/25 19:31:39 [012] 200 https://registry.terraform.io:443/v1/providers/hashicorp/aws/versions
updater | INFO <job_139154747> Latest version is 3.42.0
updater | I, [2021-05-25T19:31:39.299128 #7]  INFO -- sentry: ** [Raven] Sending event 2930bd6eaf7e4716bbf3ed064fb224f7 to Sentry
proxy | 2021/05/25 …
```

Parse version from terraform lock file

---

npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/requirement_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
npm_and_yarn/spec/fixtures/projects/npm7/latest_requirement/package.json

Handle `latest` version requirements which are valid in npm:
```
"dependencies": {
"etag" : "latest"
}
```

npm: handle latest version requirement

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb

When a dependency specifies a version range, we do not want to set the
dependency objects version, as we cannot reliably determine it. Instead,
we need to rely on the _requirement_. For example, `~> 2.0` is not a
valid _version_, so when parsing it, we should set the `version`
attribute to nil.
This was already handled by #3756, this adds a test to verify setting
to nil when no lockfile is present.

Terraform: Do not set dependency.version for version ranges

---

terraform/lib/dependabot/terraform/metadata_finder.rb
terraform/lib/dependabot/terraform/registry_client.rb
terraform/lib/dependabot/terraform/update_checker.rb
terraform/spec/dependabot/terraform/registry_client_spec.rb
terraform/spec/dependabot/terraform/update_checker_spec.rb
terraform/spec/fixtures/vcr_cassettes/Dependabot_Terraform_RegistryClient/fetches_the_source_for_a_provider_from_a_custom_registry.yml

We need this to be able to connect to private terraform registries that are
secured with a bearer token.
This change searches for credentials that match the provided host and injects
that as an [Authorization header](https://www.terraform.io/docs/cloud/api/index.html#authentication).

feat(Terraform): Inject authorization header

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/fixtures/projects/module_path_and_version_changed_during_update/go.mod
go_modules/spec/fixtures/projects/module_path_and_version_changed_during_update/main.go

This handles a slight variation in error message when using `go get <module>@<version>` and the module path doesn't match in the new version. This can happen when you were previously on a version that didn't support go modules.
```
% go get gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.0
go: downloading gopkg.in/DATA-DOG/go-sqlmock.v1 v1.3.0
% go get -d gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.3
go get: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.3: invalid version: go.mod has non-....v1 module path "github.com/DATA-DOG/go-sqlmock" at revision v1.3.3
```

gomod: UpdateChecker - handle invalid module path error on update

---

Dockerfile

Bumps the bundled version of elixir from `v1.10.4` to `v1.11.4`.
https://github.com/elixir-lang/elixir/blob/v1.11/CHANGELOG.md

bump elixir version from 1.10.4 -> 1.11.4

---

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb

Fix error matching for `GitDependenciesNotReachable` in the lockfile
updater.
We're still seeing the error I tried to fix in the version resolver:
https://github.com/dependabot/dependabot-core/pull/3779
It looks like we need to match the same error in the lockfile updater as
it might raise for a dependency we're not trying to update.
Sharing the constant doesn't feel ideal. It would be better to extract
the error handling to something we can share between the lockfile
updater and version resolver but wanted to get this fix in to improve
our error rate.

Composer: fix git clone error in lockfile updater

---

go_modules/spec/dependabot/go_modules/file_parser_spec.rb

Tests: Rename non-existent go package name to domain we own

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_range/Gemfile
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_range/example.gemspec
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_range_array/Gemfile
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_range_array/example.gemspec
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_requirement_class/Gemfile
bundler/spec/fixtures/projects/bundler1/gemspec_required_ruby_version_requirement_class/example.gemspec
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_range/Gemfile
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_range/example.gemspec
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_range_array/Gemfile
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_range_array/example.gemspec
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_requirement_class/Gemfile
bundler/spec/fixtures/projects/bundler2/gemspec_required_ruby_version_requirement_class/example.gemspec

Handle `required_ruby_version` ranges in gemspecs:
`required_ruby_version = ">= 2.2, < 4.0"` and
`required_ruby_version = Gem::Requirement.new(">= 2.1.8", "< 4.0.0")`
This would previously raise a `Gem::Requirement::BadRequirementError`.
Note: The `Bundler::Requirement` class splits requirements by `,`.
I've done an audit of other uses of `Gem::Requirement` but these seem ok
as we control the range we create so shouldn't run into similar bugs
there.
Fixes https://github.com/dependabot/dependabot-core/issues/2963

Bundler: handle gemspec required ruby version ranges

---

python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/fixtures/pyproject_files/indented.toml

Some projects indent the `tool.poetry.dependencies` section of the `pyproject.toml`. The regex for updating `pyproject.toml` requirements didn't account for this which results in a "Content did not change!" error when indentation is used.
This adjusts the regex to handle indentation.

poetry: support pyproject.toml indentation

---

terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/private_module/main.tf
terraform/spec/fixtures/projects/private_provider/main.tf

To fix a bug that prevents the update of a Terraform module/provider versions that include the optional hostname in the source address. 
* https://www.terraform.io/docs/language/modules/sources.html#terraform-registry
* https://www.terraform.io/docs/language/providers/requirements.html#source-addresses
It adds a test that reproduces the defect and updates the regex to look for an optional hostname.
```bash
[dependabot-core-dev] ~/dependabot-core/terraform $ export LOCAL_CONFIG_VARIABLES="[{\"type\":\"terraform_registry\",\"host\":\"app.terraform.io\",\"token\":\"snip\"}]"
[dependabot-core-dev] ~/dependabot-core $ ./bin/dry-run.rb terraform dsp-testing/dependabot-updates-1480
Resolving dependencies...
=> dumping fetched dependency files: …
```

Detect optional hostname in module/provider source declaration

---

.github/workflows/dependabot-automerge.yml

Enable automerge on dependabot pull requests if the PR. This won't actually merge the PR, it will still require an approval from a team member.

Enable automerge on dependabot pull requests

---

hex/spec/dependabot/hex/file_parser_spec.rb
hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/dependabot/hex/file_updater/mixfile_git_pin_updater_spec.rb
hex/spec/dependabot/hex/file_updater/mixfile_updater_spec.rb
hex/spec/dependabot/hex/update_checker/file_preparer_spec.rb
hex/spec/dependabot/hex/update_checker/requirements_updater_spec.rb
hex/spec/dependabot/hex/update_checker_spec.rb
hex/spec/fixtures/lockfiles/git_source
hex/spec/fixtures/lockfiles/git_source_no_tag
hex/spec/fixtures/lockfiles/git_source_no_tag_blocked
hex/spec/fixtures/lockfiles/git_source_tag_can_update
hex/spec/fixtures/lockfiles/git_source_with_charlist
hex/spec/fixtures/mixfiles/git_source
hex/spec/fixtures/mixfiles/git_source_multiple_lines
hex/spec/fixtures/mixfiles/git_source_no_tag
hex/spec/fixtures/mixfiles/git_source_no_tag_blocked
hex/spec/fixtures/mixfiles/git_source_tag_can_update
hex/spec/fixtures/mixfiles/git_source_with_charlist

To prevent these repositories from being squatted or from otherwise changing
under our feet in unexpected ways, prefer using repositories that we own
as git dependencies in our tests.

Hex tests: Use git dependencies of repositories we own

---

Dockerfile

This pins the `esl-erlang` package to a version that uses OTP 23 instead of the latest which is using OTP 24. OTP 24 introduced some new warning output which is causing mix updates to fail.
https://elixirforum.com/t/mix-local-hex-warning/39665
I took this version from the last core release which was successfully processing mix updates:
```
% docker run -it dependabot/dependabot-core:0.147.0
dependabot@95d004bd8c6d:~$ apt list esl-erlang
Listing... Done
esl-erlang/now 1:23.3.1-1 amd64 [installed,local]
```
The next version contained the update causing the failures:
```
% docker run -it dependabot/dependabot-core:0.147.1
dependabot@a084b38baba1:~$ apt list esl-erlang
Listing... Done
esl-erlang/now 1:24.0-1 amd64 [installed,local]
```
Fixes: …

Pin erlang to OTP 23 until we can resolve OTP 24 warning issues

---

npm_and_yarn/helpers/lib/npm6/updater.js
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/ghpr_no_hash_pinning/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm6/ghpr_no_hash_pinning/package.json

To make sure that Dependabot does not pin to a specific git hash when the `package.json` has not pinned to one.
It updates the npm helper to check for a pinned hash in git based version constraints.
Fixes https://github.com/dependabot/dependabot-core/issues/3813
Before:
```bash
[dependabot-core-dev] ~/dependabot-core $ ./bin/dry-run.rb npm_and_yarn xlgmokha/hypixel-translators-bot --dep discord.js --branch core-3813
Resolving dependencies...
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> dumping fetched dependency files: ./dry-run/xlgmokha/hypixel-translators-bot/core-3813/
=> parsing …
```

fix(npm): Prevent unnecessary hash pinning in lock file constraint

---

terraform/lib/dependabot/terraform/file_fetcher.rb
terraform/spec/dependabot/terraform/file_fetcher_spec.rb
terraform/spec/fixtures/github/contents_lockfile_repo.json

Fixes a bug where `lock_file` would fail when appended `fetched_files` array. Introduced in https://github.com/dependabot/dependabot-core/pull/3766/commits/b3c774247f3ff1ec38e1dfbb8fd6851b51f02150
This fix wraps the `lock_file` in an array before appending it to `fetched_files`. It also adds a test to ensure the lockfile is correctly added in `FileFetcher`

Fix Terraform lockfile bug introduced in #3766

---

README.md
common/spec/spec_helper.rb

This adds the ability to tag a spec with `:profile`:
```ruby
it "profiles with rspec", :profile do
end
```
And will then generate a stackprof dump in the `tmp` directory.
This is useful when debugging performance issues.

Tests: Allow profiling tests with stackprof when tagged

---

bin/bump-version.rb

This PR adds a `git checkout` instruction before creating a PR in `bin/bump-version`.

Add instruction to checkout new branch

---

Dockerfile
python/helpers/build
python/lib/dependabot/python/python_versions.rb
python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb

- Also adds support for 3.8.10
Fixes https://github.com/dependabot/dependabot-core/issues/3889

Python: Upgrade pyenv to 2.0.1 to add support for Python 3.9.5

---

Dockerfile

The clean up of `~/.npm` should be in the same layer with `npm install`
cc #946 #3638

Fix npm cache clean up in Dockerfile

---

Dockerfile

Should always use `-y` with `apt-get install` in Dockerfile to prevent manual input interrupt the image build. (This is the only on missing in the Dockerfile)

Add missing `-y` for apt-get install in Dockerfile

---

Dockerfile
bundler/helpers/v1/build
bundler/helpers/v2/build
bundler/helpers/v2/lib/functions/lockfile_updater.rb
bundler/lib/dependabot/bundler/native_helpers.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
python/spec/dependabot/python/requirement_spec.rb

Updates Ruby from 2.6 to 2.7.
Ruby 2.7 ships a version of rubygems where the `Gem::Requirement` class is sorted. I don't think we rely on sort order in dependabot-core, we loop over requirements in turn to check if they match.
I had to change how we run the native helpers, to use `bundle exec` to make it pick up the `BUNDLER_VERSION` env var. Ruby 2.7 started falling back to bundler 2.1.4 for both bundler v1 and v2 without `bundle exec`.

Update Ruby from 2.6 to 2.7

---

.rubocop.yml
bundler/helpers/v1/lib/functions.rb
bundler/helpers/v1/lib/functions/dependency_source.rb
bundler/helpers/v1/lib/functions/file_parser.rb
bundler/helpers/v1/lib/functions/force_updater.rb
bundler/helpers/v1/lib/functions/lockfile_updater.rb
bundler/helpers/v1/lib/functions/version_resolver.rb
bundler/helpers/v1/monkey_patches/git_source_patch.rb
bundler/helpers/v1/run.rb
bundler/helpers/v1/spec/functions/dependency_source_spec.rb
bundler/helpers/v1/spec/native_spec_helper.rb
bundler/helpers/v2/lib/functions.rb
bundler/helpers/v2/lib/functions/dependency_source.rb
bundler/helpers/v2/lib/functions/file_parser.rb
bundler/helpers/v2/lib/functions/force_updater.rb
bundler/helpers/v2/lib/functions/lockfile_updater.rb
bundler/helpers/v2/lib/functions/version_resolver.rb
bundler/helpers/v2/monkey_patches/git_source_patch.rb
bundler/helpers/v2/run.rb
bundler/helpers/v2/spec/functions/dependency_source_spec.rb
bundler/helpers/v2/spec/functions/file_parser_spec.rb
bundler/helpers/v2/spec/functions_spec.rb
bundler/helpers/v2/spec/native_spec_helper.rb

Dependabot's logic for the bundler ecosystem is split between "normal" dependabot-core, and helpers specific to bundler1 and bundler2.
I'm not sure why the ruby code in the helpers was being excluded from rubocop, so this PR enables it and fixes all outstanding issues that have accumulated. This maintains styling across dependabot-core's ruby codebase.

enable rubocop on bundler/helpers

---

Dockerfile
common/lib/dependabot/shared_helpers.rb
go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb

Disable the outdated system rubygems installation and use the updated
3.2.20 version.
The default brightbox ppa for ruby 2.7 installs rubygems 3.1.2 which
can't be updated with `gem update --system` and prints the following
deprecation warnings when loaded from bundler:
```
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
```

Ruby: Fix 2.7 deprecation warnings in rubygems

---

bundler/helpers/v1/lib/functions/lockfile_updater.rb
bundler/helpers/v1/spec/functions/file_parser_spec.rb
bundler/helpers/v2/lib/functions/lockfile_updater.rb
bundler/helpers/v2/spec/functions/file_parser_spec.rb
bundler/script/ci-test
cargo/script/ci-test
common/script/ci-test
common/spec/helpers/test/error_bash
common/spec/helpers/test/run_bash
composer/script/ci-test
dep/script/ci-test
docker/script/ci-test
elm/script/ci-test
git_submodules/script/ci-test
github_actions/script/ci-test
go_modules/script/ci-test
gradle/script/ci-test
hex/script/ci-test
maven/script/ci-test
npm_and_yarn/script/ci-test
nuget/script/ci-test
omnibus/script/ci-test
python/script/ci-test
terraform/script/ci-test

Fix bundler `script/ci-test` bash codes and conform scripts to use
`bin/bash`.
Native helper specs are not being run as the script/ci-test currently
bails out with:
```
./script/ci-test: 7: [: bundler1: unexpected operator
./script/ci-test: 14: [: bundler1: unexpected operator
```

Bundler: Run native helper specs

---

.github/workflows/ci.yml
common/lib/dependabot/clients/bitbucket_with_retries.rb
common/spec/dependabot/dependency_spec.rb
common/spec/dependabot/security_advisory_spec.rb
common/spec/dependabot/source_spec.rb
common/spec/spec_helper.rb
common/spec/warning_monkey_patch.rb
gradle/spec/dependabot/gradle_spec.rb
maven/spec/dependabot/maven_spec.rb

Break tests if we introduce any ruby 2.7 deprecation warnings.

Raise on ruby 2.7 deprecation warnings

---

Dockerfile

This option will prevent not needed package being installed, make the
image smaller.
```
$ docker images
REPOSITORY                    TAG                 IMAGE ID       CREATED          SIZE
after                         latest              302fbe1d94dc   16 minutes ago   4.06GB
before                        latest              e59fb0274b02   17 minutes ago   4.17GB
```

Add `--no-install-recommends` to all `apt-get install` in Dockerfile

---

dep/helpers/build
go_modules/helpers/build
hex/helpers/build

This will help prevent globbing and word splitting. Most of them are
already quoted, just few of them are missed.

Double quote variables in shellscript

---

terraform/lib/dependabot/terraform/registry_client.rb
terraform/spec/dependabot/terraform/registry_client_spec.rb

Raise a `PrivateSourceAuthenticationFailure` with the provided hostname
if the registry responds with a `401`.

Terraform: Handle 401 registry responses

---

Dockerfile

Double quote variables in Dockerfile's shellscript

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/projects/provider_no_namespace/main.tf

Default providers without a namespace to `hashicorp`.

Terraform: handle dependencies without a namespace

---

github_actions/spec/fixtures/vcr_cassettes/Dependabot_GithubActions_UpdateChecker/_updated_requirements/with_multiple_requirement_sources/1_5_4_1.yml

To remove non-essential data from test fixtures.
To remove headers that aren't needed.

Remove headers from HTTP fixture recordings

---

.github/workflows/ci.yml
bin/docker-dev-shell
bin/lint
hex/helpers/build

To ensure that we follow the best practices for shell scripting described in
the Shellcheck wiki. e.g. [SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006).
It adds a `./bin/lint` script that can be used to run the shellcheck linter
on your machine. It also adds a job to the CI workflow to ensure that the
linter checks are passing.
xref: https://github.com/dependabot/dependabot-core/pull/3917#issuecomment-862823068
Before:
```bash
モ ./bin/lint
In ./bin/docker-dev-shell line 14:
OPTS=`getopt -o hr --long help,rebuild -n 'parse-options' -- "$@"`
^--^ SC2034: OPTS appears unused. Verify use (or export if used externally).
^-- SC2006: Use $(...) notation instead of legacy backticked `...`.
Did you mean:
OPTS=$(getopt -o hr --long help,rebuild -n 'parse-options' -- "$@")
In …
```

Run linter against shell scripts

---

.rubocop.yml
Rakefile
bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
common/lib/dependabot/dependency.rb
common/lib/dependabot/file_updaters/vendor_updater.rb
common/lib/dependabot/git_metadata_fetcher.rb
common/lib/dependabot/metadata_finders/base/release_finder.rb
common/lib/dependabot/pull_request_creator/github.rb
common/lib/dependabot/pull_request_creator/gitlab.rb
common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/file_fetchers/base_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb
gradle/spec/dependabot/gradle/version_spec.rb
hex/lib/dependabot/hex/file_parser.rb
maven/spec/dependabot/maven/version_spec.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
terraform/spec/dependabot/terraform/registry_client_spec.rb

This is an idle hands PR: I upgraded my system and wanted to verify this toolchain wasn't broken.
The changeset begins by adding a `rake rubocop:sort` task, which does a recursive sort of `.rubocop.yml` for 💄 .
From there, new but not enabled cops are enabled in 3 phases with autofix+sort applied at each round.
When an autofix wasn't available, the rule was disabled (I didn't write any code):
* [`Lint/NoReturnInBeginEndBlocks`](https://rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/NoReturnInBeginEndBlocks)
* [`Lint/DuplicateBranch`](https://rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/DuplicateBranch)

Enable available rubocops

---

Dockerfile
terraform/helpers/build

Use single tool for the same purpose, simplify the dependency, and
also make the Docker image a little bit more smaller.

Replace `wget` with `curl` to minimiz dependency

---

Dockerfile.development

To ensure that the dev container has `shellcheck` installed so that the
`./bin/lint` script can be used.
It installs the `shellcheck` package in the dev docker image.
/xref: https://github.com/dependabot/dependabot-core/pull/3932#discussion_r654200778

chore: install shellcheck in the dev container

---

common/lib/dependabot/git_metadata_fetcher.rb
common/spec/dependabot/git_commit_checker_spec.rb
common/spec/dependabot/git_metadata_fetcher_spec.rb
common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb
common/spec/dependabot/pull_request_creator/github_spec.rb

Some formats for git remotes require extra git configuration to be able to authenticate to the remote. Falling back to `git ls-remote` allows the metadata fetcher to use any authentication mechanism implemented in the user's gitconfig. Particularly troublesome are codecommit formats using the [awscli credential helper](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html) or the [git-remote-codecommit plugin](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-git-remote-codecommit.html).

Fetches metadata upload-pack using git if http/s fails

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md

We tend to get a lot of questions here about the Dependabot service that
we operate at GitHub. Many of those questions are much easier to resolve
when going through Support, as they have much better tooling and
processes to follow up on those sorts of questions.
This attempts to clarify that in the README and issue template.

Clarify support policies in README and Issue template

---

common/lib/dependabot/file_fetchers/base.rb

Previously, the `name` and `path` attributes were both the absolute
path for all files retrieved from CodeCommit sources. This caused
problems in `fetch_file_from_host`, which joins the `directory`
from the config with the `filename`. When `filename` is the absolute
path, this essentially duplicated the directory in the result, e.g.
`directory/directory/relative path`.
This change returns the basename and relative path instead, matching
the implemenation for azure devops, and allowing the join in `fetch_file_from_host`
to return `directory/relative path.

Returns basename and relative path in CodeCommit file fetcher

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/projects/private_module_proxy/main.tf

Raise a `PrivateSourceAuthenticationFailure` when a private module proxy
can't be reached.

Terraform: handle unreachable private module proxy

---

terraform/lib/dependabot/terraform/registry_client.rb
terraform/spec/dependabot/terraform/registry_client_spec.rb
terraform/spec/fixtures/vcr_cassettes/Dependabot_Terraform_RegistryClient/fetches_the_source_for_a_provider_dependency.yml
terraform/spec/fixtures/vcr_cassettes/Dependabot_Terraform_RegistryClient/handles_sources_that_can_t_be_found.yml

Silently ignore failing source requests to not block PR creation.
Returning nil here will cause the PR creator to not include any
changelogs/release notes.

Terraform: handle missing source

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
common/lib/dependabot/update_checkers/version_filters.rb
composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
gradle/lib/dependabot/gradle/update_checker/version_finder.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb

Creates a new `version_filter` module and removes the `filter_vulnerable_version` method from ecosystems' `update_checker`.

Add version_filter method to common, remove filter_vulnerable_version from ecosystems' update_checker

---

terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/nested_modules/main.tf

Relax the regex that matches module sources to include nested modules.
Nested modules mentioned in docs here: https://www.terraform.io/docs/language/modules/develop/structure.html

Terraform: handle nested module sources

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
gradle/lib/dependabot/gradle/update_checker/version_finder.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb

Addresses https://github.com/dependabot/dependabot-core/pull/3905#discussion_r655682644 where the #filter_ignored_version executing before #filter_vulnerable_versions could cause tests to flake.
A refactor to remove the order-dependence of version filters is a WIP https://github.com/dependabot/dependabot-core/pull/3960

Revert order of filters in #fetch_lowest_security_fix_version across ecosystems

---

terraform/lib/dependabot/terraform/file_updater.rb
terraform/spec/dependabot/terraform/file_updater_spec.rb
terraform/spec/fixtures/projects/lockfile_with_modules/.terraform.lock.hcl
terraform/spec/fixtures/projects/lockfile_with_modules/caf_module.tf
terraform/spec/fixtures/projects/lockfile_with_modules/versions.tf

Terraform requires modules to be installed with `terraform init` when
updating the lockfile. Opted to only run `terraform init` if the call to
`terraform providers lock` bails out and retry.
We could opt to always run `terraform init` if there are any modules
defined but would mean parsing the dependency files and checking if any
of the dependencies are modules as we only have access to the current
dependency, which in this case is provider.

Terraform: install modules when updating lockfile

---

go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

Currently tested against manual security advisories. 
Uses [github.com/dependabot-fixtures/go-modules-lib][test-fixture] as a test fixture and passes a dry-run.
Based off of https://github.com/dependabot/dependabot-core/pull/3905
TODO:
[test-fixture]: https://github.com/dependabot-fixtures/go-modules-lib

Security advisories for Go
