- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
This is the other side of https://github.com/dependabot/dependabot-core/pull/3968
This fixes module updates when there's a lockfile present. Modules are
not included in the lockfile so adding a guard to only attempt lockfile
updates for providers.
Fixed some test setup to match what the parsed files would look like.
> Terraform: fix module updates with a lockfile

- nuget/lib/dependabot/nuget/update_checker/version_finder.rb
- nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
- nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
- nuget/spec/fixtures/nuget_responses/artifactory_base.json
When interacting with Nuget repositories, Dependabot will look for a [Package Content](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource) resource, specifically [`PackageBaseVersion/3.0.0`](https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb#L84). Unfortunately not every server supports this feature, Artifactory Pro does not seem to.
This PR captures the repository details from a test instance of Artifactory Pro, and verifies the registries lacking `PackageBaseVersion/3.0.0` are supported. Previously the `.fetch(:versions_url)` step would raise a `KeyError`.
The downstream concern from this change: what happens now that `nuspec_url` might be nil? The only usage I …
> nuget: allow registries without PackageBaseAddress

- bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb
- bundler/spec/dependabot/bundler/file_updater/gemspec_sanitizer_spec.rb
The previous impl only replaced the components of the interpolated
string that looked like versions.
When this is called with a `replacement_version` read from
`Gemfile.lock`, the replacement value is based on the interpolated string. That means replacing the entire string is more correct than swapping individual components.
> GemspecSanitizer: replace interpolated strings

- terraform/lib/dependabot/terraform.rb
- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/.terraform.lock.hcl
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/main.tf
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/modules/repeat_that/main.tf
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/modules/repeat_this/main.tf
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/providers.tf
Terraform projects can include local path modules that are currently not
fetched in the file fetching step so any lockfile update will fail
because these files are missing.
The easiest fix seemed to be to always start cloning terraform projects
as this is what we want to end up doing for all ecosystems.
The file fetcher will still hit the gh api when getting the [repo contents](https://github.com/dependabot/dependabot-core/blob/40baefd1e812feca9712daa1e359583a29b5fdc1/common/lib/dependabot/file_fetchers/base.rb#L171-L178)
but this would require changes in common so keen to make that change
separately as it currently works.
> Terraform: always clone repository contents

- bin/bump-version.rb
Build the changelog entries from merge commit PR details instead of the individual commits, automating attribution to non-team members and including a link to the PR.
Example:
```
- fix(Go mod): detect when remote end hangs up [#3469](https://github.com/dependabot/dependabot-core/pull/3469)
- Final pass on bundler1 test cruft [#3466](https://github.com/dependabot/dependabot-core/pull/3466)
- Handle repo not found errors for go modules [#3456](https://github.com/dependabot/dependabot-core/pull/3456)
- Disabled poetry experimental new installer (@honnix) [#3459](https://github.com/dependabot/dependabot-core/pull/3459)
- Implement delete/create action in GitLab Client (@jerbob92) [#3414](https://github.com/dependabot/dependabot-core/pull/3414)
```
> Create changelog from merge commits

- CHANGELOG.md
- common/lib/dependabot/version.rb
Merged too quickly https://github.com/dependabot/dependabot-core/pull/3979
Makes sense to bump minor for the terraform cloning change.
> Bump minor for change to cloning

- bin/bump-version.rb
Exclude release note merges in generated changelog.
For example: https://github.com/dependabot/dependabot-core/pull/3977
> Exclude release note merges in changelog

- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/lockfile_unreachable_module/.terraform.lock.hcl
- terraform/spec/fixtures/projects/lockfile_unreachable_module/main.tf
When attempting to `terraform init` when there are private module
sources present, currently we raise a `HelperSubprocessFailed`.
Terraform will attempt to use any git credentials that are configured,
so passing these along should help in some cases when Dependabot is
configured to access these, and when it isn't we should raise a
PrivateSourceAuthenticationFailure to communicate more clearly that we
cannot reach a certain source.
It's a little unfortunate that we even need to do this, because this
happens when we attempt to update a lockfile, and these don't support
modules. However, `terraform providers lock` will still complain about
modules needing to be installed, and this should do a better job of
that.
> Terraform: Configure git for `terraform init` and capture errors

- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_with_backend/.terraform.lock.hcl
- terraform/spec/fixtures/projects/provider_with_backend/providers.tf
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/.terraform.lock.hcl
- terraform/spec/fixtures/projects/provider_with_local_path_moudules/providers.tf
Some terraform setups have backend (where the state is stored) configurations present in the code. When this is the case the `terraform init` command will fail trying to initialize the backend. Most backend types can't be initialized by dependabot as where they are pointing should be well protected or require user input to continue. Example of error message: https://github.com/dependabot/dependabot-core/issues/3909#issuecomment-866239727
I have added the following options to the `terraform init` command:
- `-backend=false` to ignore any backend configuration
- `-input=false` to immediately fail if it needs user input
- `-no-color` to prevent color characters from printing, which means `strip_terminal_colors` could be removed
Hopefully I have gotten things correct set up here. First time …
> Terraform: Prevent `terraform init` from initializing backends

- python/lib/dependabot/python/file_fetcher.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/file_updater/pyproject_preparer.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
The array `%w(dependencies dev-dependencies)` is duplicated in several places to describe [the scopes available to the poetry package manager](https://python-poetry.org/docs/basic-usage/#installing-dependencies).
This PR updates duplicated references to prefer an existing shared constant.
- Discovered https://github.com/dependabot/dependabot-core/pull/3987
> Nit: prefer POETRY_DEPENDENCY_TYPES

- python/lib/dependabot/python/file_parser/poetry_files_parser.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
- python/spec/dependabot/python/file_parser/poetry_files_parser_spec.rb
- python/spec/dependabot/python/file_parser_spec.rb
- python/spec/fixtures/pyproject_files/url_dependency.toml
- python/spec/fixtures/pyproject_locks/url_dependency.lock
This PR updates the python `FileParser` to ignore dependencies specified as a poetry [path dependency](https://python-poetry.org/docs/dependency-specification/#path-dependencies) or [url dependency](https://python-poetry.org/docs/dependency-specification/#url-dependencies), by following the existing pattern for ignoring `git` dependencies.
This is an alternative to https://github.com/dependabot/dependabot-core/pull/3987 , which would allow these dependencies to be parsed but not updated. Since they'll never be updated, it's easier just to skip them in the parse. It addresses the same concerns:
* When querying for the latest versions, available indexes were queried. This is a privacy concern: customers with monorepos will leak every submodule's name to PyPI. (In my test setup, my internal …
> poetry: skip path and url dependencies

- common/lib/dependabot/pull_request_updater/github.rb
- common/spec/dependabot/pull_request_updater/github_spec.rb
- common/spec/fixtures/github/required_status_checks_protected_branch.json
As per [the docs][docs] when branch protection rules are enabled, force
pushing to them is disabled.
This handles errors when this happens and raises a `BranchProtected`
error, which will allow us to handle this gracefully and inform the user
of this.
[docs]: https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#about-branch-protection-rules
> PR Updater: Handle required status checks

- maven/lib/dependabot/maven/file_fetcher.rb
- maven/lib/dependabot/maven/file_parser.rb
- maven/lib/dependabot/maven/file_updater.rb
- maven/spec/dependabot/maven/file_fetcher_spec.rb
- maven/spec/dependabot/maven/file_parser_spec.rb
- maven/spec/dependabot/maven/file_updater_spec.rb
- maven/spec/fixtures/extensions/extensions.xml
- maven/spec/fixtures/github/contents_java_extensions_xml.json
- maven/spec/fixtures/github/contents_mvn_directory.json
- maven/spec/fixtures/vcr_cassettes/Dependabot_Maven_FileFetcher/with_a_multimodule_pom/with_a_nested_multimodule_pom/when_asked_to_fetch_only_a_subdirectory/fetches_the_relevant_poms.yml
These files contain dependency coordinates for Maven extensions that
want to receive the Maven afterSessionStart event. The file is always
located in the .mvn folder in the project root and is optional.
See also
- https://maven.apache.org/guides/mini/guide-using-extensions.html
- https://maven.apache.org/examples/maven-3-lifecycle-extensions.html
> Add support for updating Maven extensions.xml files

- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/lockfile_with_modules/versions.tf
This fixes a test that started to fail because a new version of a Terraform
dependency was released.
Before:
```bash
Failures:
1) Dependabot::Terraform::FileUpdater#updated_dependency_files with a lockfile and modules that need to be installed updates the version in the lockfile
Failure/Error:
expect(lockfile.content).to include(
<<~DEP
provider "registry.terraform.io/integrations/github" {
version     = "4.12.0"
constraints = "~> 4.4"
DEP
)
expected "# This file is maintained automatically by \"terraform init\".\n# Manual edits may be lost in future...64511702\",\n    \"zh:e2b1f5133d53e640fc7048c70f813530204e2c6d4941a7433c60cac5a3354778\",\n  ]\n}\n" to include "provider \"registry.terraform.io/integrations/github\" {\n  version     = \"4.12.0\"\n  constraints = \"~> 4.4\"\n"
Diff:
@@ …
```
> test: place upper bound on version constraint

- common/lib/dependabot/clients/azure.rb
- common/spec/dependabot/clients/azure_spec.rb
Currently azure.rb does not have any logic to catch 401 error codes and will attempt to parse the response if one is encountered, causing auth exceptions for this client to be surfaced to the user as a JSON::ParserError.
This fix adds an Unauthorized exception to azure.rb and raises it when calls to Excon.get and Excon.post return a 401 status.
> Fix for Azure client trying to parse 401 responses

- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
- go_modules/spec/fixtures/projects/nonexisting_proxy/go.mod
- go_modules/spec/fixtures/projects/nonexisting_proxy/main.go
When referencing a go proxy that 404s, we see this error. Previously
this would not be handled, but it should result in a
DependencyFileNotResolvable error, so users have a sense of what's
wrong.
> Gomod: Handle unrecognized import path error

- common/lib/dependabot/clients/azure.rb
- common/spec/dependabot/clients/azure_spec.rb
Adds a Forbidden error type to Dependabot:Clients:Azure to raise when a request returns 403
This fixes an issue where Dependabot:PullRequestCreator:Azure.create returns a 400 status to the caller when the root issue is a 403 being returned by Dependabot:PullRequestCreator:Azure.create_commit (since Azure.create creates both the commit and pull request it only ever returns the response code for the latter).
> Add Forbidden error type to Azure client

- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_with_mixed_case/.terraform.lock.hcl
- terraform/spec/fixtures/projects/provider_with_mixed_case/providers.tf
Provider names can include uppercase characters but the resulting
lockfile downcases the name in the provider url.
> Terraform: handle mixed case providers

- common/lib/dependabot/file_fetchers/base.rb
- terraform/lib/dependabot/terraform/file_fetcher.rb
- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_fetcher_spec.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/.terraform.lock.hcl
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/loader.tf
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/loader/project/providers.tf
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/loader/projects.tf
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/loader/providers.tf
- terraform/spec/fixtures/projects/provider_with_multiple_local_path_modules/providers.tf
Add support for fetching and updating local path modules:
```
module "project" {
source = "./project"
}
```
Terraform will resolve all local path modules when updating the
lockfile, so we need to make sure all requirements for the same
dependency have been updated, and written to the temporary directory
before we run `terraform providers lock _provider_`.
This also updates the file fetcher to not make an api request when
checking folder contents.
Fixes: https://github.com/dependabot/dependabot-core/issues/4043
> Terraform: support updating local path modules

- Dockerfile
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
* [`013f0262d`](https://github.com/npm/cli/commit/013f0262db3e16605820f6117749fd3ebc70f6d1)
[#3469](https://github.com/npm/cli/issues/3469)
fix(exitHandler): write code to logfile
([@wraithgar](https://github.com/wraithgar))
* [`0dd0341ac`](https://github.com/npm/cli/commit/0dd0341ac9a65a2df8fc262ad9a56b7351f99d66)
[#3474](https://github.com/npm/cli/issues/3474)
fix(ping): make "npm ping" echo a right time
([@aluneed](https://github.com/aluneed))
* [`d2e298f3c`](https://github.com/npm/cli/commit/d2e298f3cbab278071480f94ff7d916d42cbf43b)
[#3484](https://github.com/npm/cli/issues/3484)
fix(deprecate): add undeprecate support
([@wraithgar](https://github.com/wraithgar))
* [`9dd32d08e`](https://github.com/npm/cli/commit/9dd32d08e09c21c9a4517161abfc7eed6518faf2) …
> Bump npm from 7.10.0 to 7.19.1

- common/lib/dependabot/file_fetchers/base.rb
- terraform/spec/dependabot/terraform/file_fetcher_spec.rb
Fix a bug with symlinks being fetched in the file fetcher, resulting in
attempted updates to these files, which fail when creating a pull
request.
> Terraform: ignore symlinks in file fetcher

- Dockerfile
This was previously done here: https://github.com/dependabot/dependabot-core/pull/4089
But that was reverted after being released due to an issue with the
erlang upgrade in that PR. This bumps only the elixir version, which
should be safe.
> Upgrade elixir to v1.12.2

- Dockerfile
We pinned erlang to OTP 23 due to an issue with our proxy in production,
however this is easy to miss. I've added some inline documentation to
make that clear.
> Document pinned OTP version

- terraform/lib/dependabot/terraform/update_checker.rb
- terraform/spec/dependabot/terraform/update_checker_spec.rb
To skip performing update checks on Terraform dependencies that have a source
type of 'path'.
This adds an allow list of eligible source types that can be used for update
checks.
xref: https://github.com/github/dependabot-updates/issues/1668
Before:
```bash
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb terraform "plus3it/terraform-aws-ldap-maintainer" --dir="/." --commit=151a9b745a7e0eec3888e26886e214e174e71f68 --cache=files
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.4-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> reading cloned repo from /home/dependabot/dependabot-core/tmp/plus3it/terraform-aws-ldap-maintainer
=> checking out commit …
```
> fix(terraform): exclude path source types in update check

- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_with_mixed_case/providers.tf
This test was currently set up in a way that caused new releases of
Mongey/confluentcloud to make our tests fail. Now we pin it to a range,
in line with other tests
> Terraform: Pin fixture to range to prevent tests failing

- common/lib/dependabot/git_metadata_fetcher.rb
- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
More consistent use of `SharedHelpers.escape_command` on args.
> Improve argument sanitation

- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
- go_modules/spec/dependabot/go_modules/file_updater_spec.rb
Recently GitHub changed its response to requests that appeared to be using user/pass authentication. Our use of `token`  in default credentials was triggering this new response and causing an unexpected [test failure](https://github.com/dependabot/dependabot-core/runs/3343021425):
https://github.com/dependabot/dependabot-core/blob/23049ea9d768bccbaf79da2b6d9a21822fdc10d1/go_modules/spec/dependabot/go_modules/file_updater_spec.rb#L26-L33
```
go: k8s.io/kubernetes@v1.15.9 requires
github.com/mholt/caddy@v0.0.0-20180213163048-2de495001514: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/dependabot/go/pkg/mod/cache/vcs/4d13fcc7852c2edc10fd0bb49b723561904719db812ccb21ab70a690362645eb: exit status 128:
remote: Support for password authentication …
```
> Fix failing go modules tests

- go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
- go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
Previously we improved handling of unreachable go module dependencies when performing an update in https://github.com/dependabot/dependabot-core/pull/4130
This updates the `LatestVersionFinder` to detect unreachable dependency errors as well. Previously we'd return an `UnknownError` in this case where Dependabot checks if an unreachable dependency needs an update.
I've also continued replacing the default credentials used in the test with empty credentials. This is a more realistic use case since using made up credentials can result in other unexpected errors: https://github.com/dependabot/dependabot-core/pull/4141
> Handle unreachable go module dependencies in LatestVersionFinder

- Dockerfile
Go 1.17.0 is [out](https://blog.golang.org/go1.17)! This gets us to the [latest 1.16.x release](https://golang.org/dl/) first.
> Bump go from 1.16.3 to 1.16.7

- Dockerfile
- bundler/helpers/v1/build
- bundler/helpers/v2/build
- bundler/helpers/v2/lib/functions/force_updater.rb
- bundler/helpers/v2/lib/functions/version_resolver.rb
- bundler/lib/dependabot/bundler/helpers.rb
- bundler/lib/dependabot/bundler/native_helpers.rb
- bundler/script/ci-test
- bundler/spec/dependabot/bundler/file_parser_spec.rb
- bundler/spec/dependabot/bundler/helper_spec.rb
- bundler/spec/spec_helper.rb
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2225-july-30-2021
Something we _might_ get some support questions on is:
https://github.com/rubygems/rubygems/pull/4647 but overall I think
that's a very good change! The GEM sources not being split has bitten
our users in the past, so happy to see that change.
In a recent version of bundler, passing a major version like
`BUNDLER_VERSION=2 bundle --version` no longer works.
I suspect this may have happened here: https://github.com/rubygems/rubygems/pull/4750/files
We now need to pass the exact version of bundler we're using, which is a
bit cumbersome as you can see from the diff, and it also means we'll
have to change a few more lines every time we update a version of
bundler.
I don't think the current behavior we were …
> Bump bundler from 2.2.20 to 2.2.25

- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
- go_modules/spec/fixtures/projects/go_1.17/go.mod
- go_modules/spec/fixtures/projects/go_1.17/go.sum
- go_modules/spec/fixtures/projects/go_1.17/main.go
This loosely covers the issue reported in https://github.com/dependabot/dependabot-core/issues/4148 where the new indirect requirement section of the `go.mod` file was removed.
> Add a minimal test for go 1.17 module handling

- README.md
- common/dependabot-common.gemspec
- go_modules/spec/dependabot/go_modules/path_converter_spec.rb
Pinning to an older version of faraday appears to improve the condition of the builds. A new version of faraday was released yesterday. 
* https://rubygems.org/gems/faraday/versions
* https://github.com/lostisland/faraday/releases/tag/v1.7.1
* https://github.com/lostisland/faraday/pull/1306
A golang test is failing and I was able to reproduce it with:
```bash
~/src/github.com/dependabot/dependabot-core/go_modules/helpers [fix-build]
モ echo "{\"function\":\"getVcsRemoteForImport\",\"args\":{\"import\":\"code.cloudfoundry.org/bytefmt\"}}" | go run main.go
{"error":"Cannot detect VCS"}exit status 1
```
I was able to resolve this by falling back to http after attempting https resolution for paths that do not have a scheme specified.
> Fix failing builds

- Dockerfile
This resolves some panics that we observed in production updates for
users.
> Bump terraform CLI from 1.0.0 to 1.0.6

- python/lib/dependabot/python/file_parser/poetry_files_parser.rb
- python/spec/dependabot/python/file_parser_spec.rb
- python/spec/fixtures/projects/poetry/multiple_requirements/poetry.lock
- python/spec/fixtures/projects/poetry/multiple_requirements/pyproject.toml
Poetry projects can specify multiple requirements for a dependency.
e.g.
```toml
numpy = [
{ version = "^1.19", python = "^3.6,<3.7" },
{ version  = "^1.20", python = "^3.7" }]
scipy = [
{ version = "^1.5", python = "^3.6,<3.7" },
{ version = "^1.6.0", python = "^3.7" }
]
```
This change is needed to allow the parser to parse dependencies with multiple
requirements.
This change handles poetry dependencies with multiple requirements by looping
through each requirement specified for a dependency.
> fix: Parse multiple requirements from a poetry dependency

- .github/workflows/ci.yml
A recent release of a [project dependency was released](https://github.com/lostisland/faraday/releases/tag/v1.7.1) that caused most of our
builds to fail. We didn't detect this until the [first unrelated PR](https://github.com/dependabot/dependabot-core/pull/4179) was submitted
to fix a different defect. That PR was held up because the default builds were
failing.
This change introduces a cron job to run the builds on a daily basis to try to
detect these types of errors sooner.
> chore: run builds on a regular basis to detect anomolies

- common/lib/dependabot/file_updaters/vendor_updater.rb
Paths in packages could be constructed to perform command, when not
properly escaped those could be executed.
```
(byebug) `file -b --mime-encoding t&&curl$IFS@0.0.0.0&&.go`
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 0.0.0.0 port 80: Connection refused
"cannot open `t' (No such file or directory)\n"
```
```
(byebug) `#{Dependabot::SharedHelpers.escape_command("file -b --mime-encoding t&&curl$IFS@0.0.0.0&&.go")}`
"cannot open `t&&curl$IFS@0.0.0.0&&.go' (No such file or directory)\n"
```
> Escape paths passed to VendorUpdater

- Dockerfile
From https://golang.org/dl/
go1.17.1.linux-amd64.tar.gz | Archive | Linux | x86-64 | 129MB | dab7d9c34361dc21ec237d584590d72500652e7c909bf082758fb63064fca0ef
-- | -- | -- | -- | -- | --
Also related: https://github.com/dependabot/gomodules-extracted/pull/14
> Bump golang from 1.17 to 1.17.1

- gradle/lib/dependabot/gradle/version.rb
- gradle/spec/dependabot/gradle/version_spec.rb
Fixes #1636
Treat `-` and `_` the same in Gradle version names. Since `1.0.0-10` > `1.0.0-9`, it makes sense to also have `1.0.0_10` > `1.0.0_9`.
> Treat tokens after underscore as numeric if possible

- go_modules/lib/dependabot/go_modules/file_parser.rb
- go_modules/spec/dependabot/go_modules/file_parser_spec.rb
This pull request makes sure that replaced modules are not being updated. I saw this behavior with one of my own projects where Dependabot updated the original import directive, but since the dependency itself was replaced by another directive, the actual update had no effect. 
Basically the go.mod looked like this:
```
require (
github.com/dghubble/oauth1 v0.6.0
)
replace github.com/dghubble/oauth1 => github.com/klippa-app/oauth1 v0.0.0-20190731095211-0d6b37cb52ba
```
And the PR that Dependabot created resulted in this:
```
-	github.com/dghubble/oauth1 v0.6.0
+	github.com/dghubble/oauth1 v0.7.0
```	
While technically correct, since that is the latest version of `github.com/dghubble/oauth1`, this PR doesn't do anything, since the import is replaced. I updated the `FileParser` to be aware …
> Ignore replaced dependencies

- common/lib/dependabot/shared_helpers.rb
- common/spec/dependabot/shared_helpers_spec.rb
In very long-running jobs with a lot of dependencies, it is feasible we can loop through the `in_a_temporary_directory` step hundreds of times.
This change ensures we clean up these directories after use in an effort to reclaim disk space in all cases and to avoid problems in persistent run environments such as the `bin/docker-dev-shell` environment.
> Ensure we cleanup tmp directories after use

- bin/bump-version.rb
The script only needs to auth to github.com, not any GHES instances you have configuration for.
> Only check auth for github.com when running `bump-version`

- bundler/helpers/v1/run.rb
- bundler/helpers/v2/run.rb
- bundler/lib/dependabot/bundler/file_parser.rb
- bundler/lib/dependabot/bundler/file_updater.rb
- bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
- bundler/lib/dependabot/bundler/native_helpers.rb
- bundler/lib/dependabot/bundler/update_checker/conflicting_dependency_resolver.rb
- bundler/lib/dependabot/bundler/update_checker/force_updater.rb
- bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
- bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
- bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
- bundler/spec/dependabot/bundler/native_helpers_spec.rb
- bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
- bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
- bundler/spec/dependabot/bundler/update_checker_spec.rb
This change introduces an experiment that allows configuring a timeout per
operation to prevent spawned processes from running indefinitely.
> Add timeout per operation

- composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
- composer/spec/fixtures/projects/private_registry_not_found/composer.json
dependabot.com now redirects to github.com which was causing our 404 test case to fail. I've chosen a new 404'ing url which is under the dependabot org on github to resist squatting attempts.
> Move composer-not-found fixture from decommissioned dependabot.com

- Dockerfile
There were some minor fixes to the `go` command in `1.17.2`/`1.17.3`... 
I don't think any of them directly affect dependabot, but it
doesn't hurt to bump this and makes it so the next person has a smaller
diff to look at when they consider updating.
I also ran the `script/extract` in `gomodules-extracted` against `1.17.3` locally, and didn't see any changes other than a very minor build file change which I suspect is simply due to building on my Mac, so that should keep working as-is. It's important to keep the code in `gomodules-extracted`  in-sync with the version of `go` used here.
> Bump to go 1.17.3

- common/lib/dependabot/source.rb
- common/spec/dependabot/source_spec.rb
We check if a potential Source is GitHub enterprise by making a request
to a `/status` endpoint against the root URL and checking some headers.
We've observed this check failing in some cases when the source is not
enterprise, and we get rate limited, or otherwise the request fails with
an error.
In this case we do not want to block creating a PR, but instead we
should assume the source is not Enterprise.
This also adds a list of known hosts that we come across often that
definitely are not GitHub Enterprise instances, and we ignore those and
don't bother making a request to them.
> Ignore errors from Source enterprise check and ignore known failures

- common/lib/dependabot/source.rb
We've observed some failures when trying to establish if this might be
an GHES host, since we can be confident it's not, let's not bother
making a request to check.
> Explicitly ignore metadata detection for fuchsia.googlesource.com

- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/lib/dependabot/terraform/registry_client.rb
This PR addresses two issues:
Dependabot sometimes comes across terraform modules that need to be installed, where terraform will hint at this with a message like: `This module is not yet installed. Run "terraform init" to install all modules`. We will then dutifully run that command and retry, and typically the `terraform providers lock` command will succeed at that point.
However, when that command fails we would previously try to run `terraform providers lock` again, and spit out the full error to users, which on our end would be handled as an unknown error.
The change introduced here is to report any failures for `terraform init` as resolvability failures, and the same goes if the command exits successfully, but the next run of `terraform providers lock` gives us the same `This module …
> Terraform: Improve file updater and registry request error handling

- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
A new version of [pandoc-ruby](https://rubygems.org/gems/pandoc-ruby/versions/2.1.5) was recently released that changes the behaviour of how the `pandoc` executable is invoked. [source](https://github.com/xwmx/pandoc-ruby/compare/2.1.4...2.1.5). This caused one of the tests in the default branch to start failing.
The change introduced in this PR makes the minimal change necessary to fix the failing test while preserving the desired behaviour to unblock merging into the main branch.
/cc https://github.com/dependabot/dependabot-core/pull/2849
> fix: remove fixed error message check

- maven/lib/dependabot/maven/file_updater/declaration_finder.rb
- maven/lib/dependabot/maven/update_checker/property_updater.rb
- maven/spec/dependabot/maven/file_updater/declaration_finder_spec.rb
- maven/spec/fixtures/poms/nested_plugin.xml
We've observed errors around pom files that have a nested `plugin`
section inside an outer plugin declaration.
Previously we used a regex to recursively scan the XML document, which
caused the inner `plugin` declarations closing tag to match the regex,
resulting in an incomplete XML section.
To demonstrate, given the following XML:
```xml
<plugins>
<plugin>
<configuration>
<jvmTarget>11</jvmTarget>
<compilerPlugins>
<plugin>spring</plugin>
</compilerPlugins>
</configuration>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-maven-plugin</artifactId>
<version>${kotlin.version}</version>
</plugin>
</plugin>
```
The `<plugin>spring</plugin>` declaration would cause a regex match,
resulting in the required information (the `version` in this case) to be
omitted from the XML snippet. …
> Maven: Correctly handle nested declarations

- gradle/lib/dependabot/gradle/file_fetcher.rb
- gradle/lib/dependabot/gradle/file_parser.rb
- gradle/spec/dependabot/gradle/file_fetcher_spec.rb
- gradle/spec/dependabot/gradle/file_parser_spec.rb
- gradle/spec/fixtures/settings_files/buildscript_dependencies_settings.gradle
- gradle/spec/fixtures/settings_files/buildscript_dependencies_settings.gradle.kts
Implements & Closes #4299
The syntax of settings files about dependencies is mostly same as build files.
settings files support plugins block, `classpath "group:name:version"` syntax in `buildscript { dependencies { here } }`, and `group: 'group', name: 'name', version: 'name'`.
> Support updating dependencies on settings file

- common/lib/dependabot/pull_request_creator/message_builder.rb
- common/spec/dependabot/pull_request_creator/message_builder_spec.rb
Some platforms like Gitlab use git trailers to generate changelog entries from commit messages.
This PR adds option to pass in custom git trailer via `commit_message_options` hash in a completely backwards compatible way.
> Add support for custom commit message trailers

- common/dependabot-common.gemspec
- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
- common/spec/dependabot/metadata_finders/base/changelog_finder_spec.rb
PandocRuby has been used to convert RestructuredText (rst), a
markdown-like format widely used in the Python ecosystem, to markdown.
We recently noticed new errors surfacing around Pandoc and started to
investigate.  This led to the discovery that Pandoc was not installed in
the Docker container GitHub is using to run Dependabot against
repositories.
I'm opting to remove this dependency as PandocRuby is effectively
unused.
Note: There is the possibility that some users rely on this
functionality. As has been noted in a recent PR-review, non-Docker usage
of dependabot-core is poorly supported, so this seems unlikely.
> Remove reliance on `PandocRuby`

- npm_and_yarn/helpers/lib/yarn/updater.js
Issue: https://github.com/dependabot/dependabot-core/issues/4288
Currently, For a mono repo, when [UpdateDependencyFiles ](https://github.com/dependabot/dependabot-core/blob/d734dc6e4fe0f7903ee97e0079ac9f5362e408c1/npm_and_yarn/helpers/lib/yarn/updater.js#L103)is called for generating the lock file content, dependencies param is passed to it. Dependencies param contains the dep that needs to be updated in all required workspaces in the repo. 
As far as observed, the multiple package.json (multiple requirements) for a dependency are getting passed for a mono repo., where it does have only a single yarn.lock file. 
In this case, it's not necessary to run `yarn update` for each and every package.json or requirement if all are referring to same version.
For a single version, if run once, …
> Run YarnUpdate only once for a version requirement

- python/helpers/requirements.txt
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
This patch contains #4345 plus a fix for the failing test.
Closes #4345.
> python: Upgrade to pip 21.3.1

- go_modules/helpers/go.mod
This isn't strictly necessary, but since the rest of the infra bumped to 1.17,
might as well bump it here too. Esp since the `go.mod` behavior changed
a bit in `1.17`... so if more libs get added ever, this makes it so `go.mod`/`go.sum`
will follow the new behavior...
> Bump minimum to 1.17

- .github/dependabot.yml
These helpers exist to support npm 6, so we require that specific major version and should not update it.
> Dependabot config: ignore npm lib major version updates

- LICENSE
Dependabot was acquired back in 2019 and is now a part of GitHub. This is a small change to reflect GitHub as the contributor in the license.
> Update contributor from Dependabot Ltd to GitHub Inc

- .devcontainer/devcontainer.json
Fixes #4465 Added the bundler/helpers directory to the run args in devcontainer.json
> Add bundler/helpers directory to devcontainer.json for VSCode

- .github/ISSUE_TEMPLATE/tech-debt.md
Create a issue template for the new `T: tech-debt` label 
added as part of https://github.com/dependabot/dependabot-core/issues/3611.
> Add tech-debt issue template

- maven/lib/dependabot/maven/file_updater/declaration_finder.rb
- maven/spec/dependabot/maven/file_updater/declaration_finder_spec.rb
- maven/spec/fixtures/poms/nested_plugin.xml
This was originally resolved in
https://github.com/dependabot/dependabot-core/pull/4417 but later
reverted, because that changed introduced a regression due to parsing
the XML using Nokogiri, which caused formatting of the XML to be lost.
We've observed errors around pom files that have a nested plugin
section inside an outer plugin declaration.
Given the following XML:
```xml
<plugins>
<plugin>
<configuration>
<jvmTarget>11</jvmTarget>
<compilerPlugins>
<plugin>spring</plugin>
</compilerPlugins>
</configuration>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-maven-plugin</artifactId>
<version>${kotlin.version}</version>
</plugin>
</plugin>
```
The <plugin>spring</plugin> declaration would cause a regex match,
resulting in the required information (the version in this case) to …
> Maven: Handle nested plugin declarations

- Dockerfile
Release notes:
https://go.dev/doc/devel/release#go1.17.minor
> Bump to go 1.17.4

- terraform/lib/dependabot/terraform/file_parser.rb
- terraform/spec/dependabot/terraform/file_parser_spec.rb
- terraform/spec/fixtures/projects/git_protocol/main.tf
Now it will be possible to also pass the source_type(source_string) call 
with a terraform valid git@... source property being set.
The function [git_source_details_from(source_string)](https://github.com/dependabot/dependabot-core/blob/main/terraform/lib/dependabot/terraform/file_parser.rb#L225-L234) is already prepared 
to handle this type.
> feat(:git): do not decline valid git@... source

- .github/workflows/docker.yml
We currently build this container on the fly in `bin/docker-dev-shell` which means it can take ~10 minutes to boot up a development container.
The reason we have historically done this is to ensure we set the UID/GID of the `dependabot` user matches those of current user on linux hosts, e.g.
```bash
build_image() {
export BUILT_IMAGE=true
echo "$(tput setaf 2)=> building image from Dockerfile.development$(tput sgr0)"
docker build \
--build-arg BUILDKIT_INLINE_CACHE=1 \
--build-arg "USER_UID=$(id -u)" \
--build-arg "USER_GID=$(id -g)" \
--cache-from "dependabot/dependabot-core-development:latest" \
-t dependabot/dependabot-core-development Dockerfile.development
}
```
Internally, we primarily use this image in two environments that do not require these build arguments:
- MacOS developer …
> Prebuild and publish the dependabot/dependabot-core-development container

- cargo/spec/fixtures/projects/version_conflict/Cargo.toml
[The test](https://github.com/dependabot/dependabot-core/blob/a5efcdaba81d5d4e1034e773f565b248f0346df8/cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb#L537-L546) made sure no update occurred if there is a transitive dependency conflict. The transitive dependency used in this test, `nom`, was [updated in the direct dependency askama](https://github.com/djc/askama/pull/530), so we pin `askama` to a commit SHA prior to that update.
> Fix failing Cargo test

- python/lib/dependabot/python/update_checker/latest_version_finder.rb
- python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb
- python/spec/fixtures/requirements/custom_index_invalid.txt
This PR rescues a InvalidURIError in Dependabot that was previously uncaught.
> Python invalid url

- .github/workflows/docker.yml
Follows up on #4511, #4513 
This reinstates the matrix build to push the development image of core, using GHCR as a target instead of docker.io.
Since this image is a development tool, it makes less sense to have it on `docker.io` for general consumption, GHCR is a better home for this - and likely our CI image which I will migrate in a follow up.
> Reinstate the dev container build, pushing to GHCR

- .github/workflows/docker.yml
Related to #4524 
When a fork of `dependabot-core` pushes a new commit, it triggers the ["Push docker images"](https://github.com/dependabot/dependabot-core/blob/main/.github/workflows/docker.yml) workflow. However, that workflow fails unless `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets are configured, which will be the case for pretty much everyone.
This PR conditionalizes the `push-core-image` step to run only in the `dependabot/dependabot-core` repository.
> Disable `docker` workflow on forks

- .github/workflows/docker.yml
Fixes regression introduced by #4525.
Double quotes (`"`) aren't valid in expressions, so this PR changes them to use single quotes (`'`). This also wraps the expression in `${{ }}`; the documentation mentions that single-line expressions don't need to be escaped like this, but I'd rather follow [the examples in the docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-contexts).
> Fix conditional in `docker` workflow

- terraform/lib/dependabot/terraform.rb
- terraform/spec/dependabot/terraform_spec.rb
Closes #4519  - returns name unless it contains git dependency name notation/
> Return name unless contains git dependency name notation

- cargo/lib/dependabot/cargo/file_updater/manifest_updater.rb
- cargo/spec/dependabot/cargo/file_updater/manifest_updater_spec.rb
- cargo/spec/fixtures/manifests/whitespace_names
Allows `cargo.toml` manifest files to have arbitrary whitespace at the beginning of dependency declarations.
Includes a new fixture file that contains dependencies with tabs or spaces at the start of their declaration.
> Allow whitespace at beginning of Cargo dependency declarations

- bin/docker-dev-shell
Passing in `HTTP_PROXY` and `HTTPS_PROXY` to `bin/docker-dev-shell` means that they are picked up as envvars by any other processes that aware of them within the script.
Let's use `DOCKER_PROXY` as a relay value so we exclusively inject them into the `docker run` command and avoid any side effects.
When checking if there is a container runner with `$CONTAINER_NAME`, we will currently match any container with _starts_ with this value, e.g. `$CONTAINER_NAME=foo` will also match `foo-sidecar`.
> Avoid setting HTTP_PROXY for docker in the dev shell

- common/dependabot-common.gemspec
We rely on some code that seems to be incompatible with activesupport 7,
which was just released. We'll want to dig into that and see if we can't
make our code play nice with the new version, but for now, since this is
breaking our builds etc let's ensure that we stay on major version 6.
> Common: Constrain activesupport to < 7

- common/lib/dependabot/source.rb
We've observed some failures when making requests to the `/status`
endpoint for some git hosts that end up not being reported as a
`Excon::Error`.
We make this request to check if the host is a GHES instance so we can
pull in relevant metadata from the host. However, when that request
fails, we should prefer opening the PR without that metadata, as we
likely wouldn't be able to source it any way.
Fixes https://github.com/dependabot/dependabot-core/issues/4538
> Common: Consider all failed requests to check enterprise source as false

- bundler/helpers/v1/build
- bundler/helpers/v2/build
The syntax in our native bundler helpers is unintentionally modifying a config variable called `set`:
```bash
dependabot@4891a24fb822:/opt/bundler/v1$ BUNDLER_VERSION=1.17.3 bundle config set --local path ".bundle"
dependabot@4891a24fb822:/opt/bundler/v1$ BUNDLER_VERSION=1.17.3 bundle config set --local without "test" 
You are replacing the current global value of set, which is currently "--local without test"
dependabot@4891a24fb822:/opt/bundler/v1$ bundle config --local
Settings are listed in order of priority. The top value will be used.
set
Set for the current user (/home/dependabot/.bundle/config): "--local without test"
path
Set via BUNDLE_PATH: ".bundle"
silence_root_warning
Set via BUNDLE_SILENCE_ROOT_WARNING: true
bin
Set via BUNDLE_BIN: ".bundle/bin"
gemfile
Set via …
```
> Fix syntax for setting bundle config

- .github/workflows/ci.yml
This PR follows on from #4523 to increase our use of GHPR.
The high level intent of this change is to move our development images out of dockerhub as they aren't relevant to downstream consumers of Dependabot.
Rather than a breaking change where everyone's builds are suddenly much slower, this is a gradual switch over that just mirrors the CI image to GHPR for now, we'll follow up with a change to consume from this image in a few days once it has an opportunity to propagate on a few WIP PRs.
One major change is that we _immediately_ start pushing and consuming the branch-specific build of `dependabot-core` to and from GHPR instead of the main `dependabot/dependabot-core` image.
This is due to a decision the team has made that these branch builds should live in a separate project to avoid …
> Update the CI workflow to use GHPR for branch images and as a mirror for CI images

- .github/workflows/ci.yml
- python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb
- python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb
- python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb
- python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
- python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
- python/spec/spec_helper.rb
These tests have not been wearing masks, and to avoid them infecting the
other tests we need to quarantine them.
Jokes aside, splitting these slow tests off into their own CI run should
reduce the overall time we have to wait on CI to pass, and it gives us
some indication on which tests we might want to try to speed up going
forward.
So far I've split off the ~10 slowest tests, which according to rspec
take 40% of the total time to run these tests!
We can move more things into the slow suite, but I'd like to avoid
having the majority of the tests live there, because then we'd still end
up with one very slow suite.
> Python: Quarantine slow tests into their own CI run

- .github/workflows/ci.yml
As of #4524, we are pushing our CI image to a mirror in GHCR.
This PR follows up to swap over from Dockerhub to GHCR as the canonical source for these images.
> Use GHCR as the canonical source for CI images

- python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb
- python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
- python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
After noticing the regular python suite still takes ~20 minutes on CI
and the python_slow suite roughly half that, I moved another bunch of
the now top 10 slowest tests in the regular suite to the slow one.
I expect this to bring the total test suite down to ~15 minutes.
> Python: Move some more tests to the slow suite

- bin/dry-run.rb
- bundler/helpers/v1/Gemfile
- bundler/helpers/v1/spec/native_spec_helper.rb
- bundler/helpers/v2/Gemfile
- bundler/helpers/v2/spec/native_spec_helper.rb
- common/dependabot-common.gemspec
- common/lib/dependabot/notifications.rb
- common/lib/dependabot/shared_helpers.rb
- common/spec/spec_helper.rb
We encountered an issue recently where upgrading to ActiveSupport 7 caused our builds to fail. Upon investigation, I found that `byebug` was no longer a dependency of ActiveSupport. The library now depends on `debug`, which is a gem now but will ship with Ruby 3.1.
> Enable support for ActiveSupport 7

- .dockerignore
- .gitignore
- common/.gitignore
- common/lib/dependabot/shared_helpers.rb
- npm_and_yarn/.gitignore
These artifacts are remnants of a [recently removed gem](https://github.com/dependabot/dependabot-core/pull/4559). Now that we're
using `debug`, we no longer need to ignore `.byebug_history`.
I wasn't aware that the major Ruby debuggers implement `debugger` as an
alias to their `binding` calls in source code. While I don't see this as
a necessary or important change, I think it's worth making.
> Cleanup after byebug removal

- .github/workflows/ci.yml
Our CI workflow currently fails on PRs opened from forks or Dependabot. Workflows for those PRs run with a read-only access token and no secrets so the push to ghcr fails.
Previously we avoided this failure by [checking](https://github.com/dependabot/dependabot-core/commit/c9314d37da7ca29c94fa63b28ed7cab9fa2e91f3#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL91) if the docker credentials were available to the workflow and skipping the push step if not. I've recreated that mechanism by adding a dummy secret, `ACCESS_CANARY`, that the workflow can check for before pushing. It's currently set to a random guid. The secret won't be available to fork PRs or Dependabot PRs so it should cause them to skip the push step.
> Check for access before ghcr push

- Dockerfile
`USER root` was set already on above, just few lines before, and there's no need to use two `mkdir` together, just use it once, just like like Dockerfile.development: https://github.com/dependabot/dependabot-core/blob/84367a4ee86fe17bc22e7cfa1b0b4a1abbe9e156/Dockerfile.development#L56
> Simplify Dockerfile a little bit

- bin/dry-run.rb
- go_modules/lib/dependabot/go_modules/file_parser.rb
- go_modules/lib/dependabot/go_modules/file_updater.rb
- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
- go_modules/lib/dependabot/go_modules/resolvability_errors.rb
- go_modules/lib/dependabot/go_modules/update_checker.rb
- go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
- go_modules/spec/dependabot/go_modules/file_updater_spec.rb
- go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
Previously we've hardcoded setting `GOPRIVATE=*` to prevent failures if private go modules are validated against the public sumdb. That works but incurs a performance penalty when public go modules are updated. This change allows a custom `GOPRIVATE` to be specified. This could be leveraged in the future to:
- Use an unrestricted `GOPRIVATE=` when checking updates for a public repo
- Use a more specific `GOPRIVATE=github.com/owner/*` when checking updates for a private repo
- Use a more customized `GOPRIVATE` when private registries are defined
Those changes would allow updates to perform more efficiently (less time and less disk usage).
In the first 2 commits I made some minor cleanup to the `FileParser`. In the past `FileParser` ran `go get` and required `GOPRIVATE` and resolvability …
> Allow configuration of GOPRIVATE

- .github/workflows/ci.yml
We tag a branch specific image when preparing for CI to run, but then reference the generic `CORE_CI_IMAGE`. This seems to cause race conditions when multiple branches build and push to the `CORE_CI_IMAGE:latest` ref.
> Ensure CI uses the latest image built on that branch

- python/helpers/requirements.txt
Manually reverts https://github.com/dependabot/dependabot-core/pull/4610
CI failed on master and PRs subsequent to this merging, which is unexpected as the branch itself _did_ pass.
I built a base image of the previous [SHA on main](https://github.com/dependabot/dependabot-core/commit/4a33928a9c13fe665f24556c52f3a9033049f90e) locally and confirmed the failing python spec now passes:
```bash
$ bundle exec rspec spec/dependabot/python/file_updater/requirement_file_updater_spec.rb:177
Run options: include {:locations=>{"./spec/dependabot/python/file_updater/requirement_file_updater_spec.rb"=>[177]}}
Randomized with seed 4982
.
Finished in 2.41 seconds (files took 2.22 seconds to load)
1 example, 0 failures
Randomized with seed 4982
```
I want to see if CI agrees with me but there are two …
> Revert hashin upgrade for python native helper

- .github/workflows/ci.yml
See: https://github.com/dependabot/dependabot-core/pull/4617
We've determined we have a green + green problem in CI where changes are made to native helpers are not fully tested on branches.
It turns out this was a result of my refactor of this file in https://github.com/dependabot/dependabot-core/pull/4524, where I removed `-t "$CORE_IMAGE:latest"` from the `docker build` that generated the 'branch image'.
Without this branch image tagged as `dependabot/dependabot-core:latest`, the `Dockerfile.ci` will pick up the base image pulled in, which is effectively `main`.
This results in us running Dependabot Core using the `native helpers` installed on `main` absent any changes made on branch.
> [CI] Ensure CI builds pick up native helper changes

- Dockerfile
- composer/helpers/v1/build
- composer/helpers/v2/build
- composer/lib/dependabot/composer/native_helpers.rb
As part of streamlining how we mount the native helpers into the development shell, I noticed that the composer native helper install path is inconsistent with our other native helpers.
In all other cases we follow the pattern of:
```Dockerfile
COPY --chown=dependabot:dependabot $ECOSYSTEM/helpers /opt/$ECOSYSTEM/helpers
RUN bash /opt/$ECOSYSTEM/helpers/build /opt/$ECOSYSTEM/
```
Which results in the relevant contents of the `helpers/` folder being copied up a level in the directory structure.
In the case of Bundler, this results in a directory with `helpers, v1, v2` folders.
My expectation is that the composer helpers should be in the same paths as bundler, but in reality we are using them in-situ without copying any files or actually using the `$install_dir` argument in the script.
My …
> Consistency pass on composer native helper build

- CHANGELOG.md
- common/lib/dependabot/version.rb
- build(deps): bump pipenv from 2021.11.23 to 2022.1.8 in /python/helpers [#4609](https://github.com/dependabot/dependabot-core/pull/4609)
This is a minor patch to release any changes on main prior to https://github.com/dependabot/dependabot-core/pull/4554, which is a breaking change for anyone who is not using the same version of the dependabot-omnibus/dependabot-composer gems and the docker image.
It will ship in isolation as v0.171.0 to minimise churn.
> v0.170.2-release-notes

- CHANGELOG.md
- common/lib/dependabot/version.rb
- Consistency pass on composer native helper build [#4554](https://github.com/dependabot/dependabot-core/pull/4554)
- NOTE: If you are using the `dependabot-composer` gem in your Dependabot scripts, you must ensure you upgrade
both the gem and the `dependabot/dependabot-core` image to v0.171.0 at the same time as this change modifies the
install path for composer's native helpers in both.
#4620 must merge first.
> v0.171.0-release-notes

- .gitignore
- Dockerfile
- README.md
- bin/docker-dev-shell
- bundler/README.md
- bundler/helpers/v1/build
- bundler/helpers/v2/build
- composer/README.md
- composer/helpers/v1/build
- composer/helpers/v2/build
- go_modules/README.md
- go_modules/helpers/build
- hex/README.md
- hex/helpers/build
- npm_and_yarn/README.md
- npm_and_yarn/helpers/build
- python/README.md
- python/helpers/build
- terraform/README.md
- terraform/helpers/build
Follow on from https://github.com/dependabot/dependabot-core/pull/4554, which should merge first
Our `docker-dev-shell` script currently uses volume mounting to ensure that changes made to core's code on the host machine are reflected in the container without rebuilding, and vice versa.
As part of this volume mounting strategy we are inconsistent on how we handle the 'native helpers' used by some languages.
These helpers are installed into `/opt/` in the base `dependabot/dependabot-core` image via `build` scripts which ensure they have any dependencies available in a path _outside_ the working directory.
For bundler and python, we currently volume mount the native helpers from the host machine into `/opt/` like so:
```bash
-v "$(pwd)/bundler/helpers:/opt/bundler" \
-v …
```
> Refresh the workflow for native helpers within the docker dev shell, Consistency pass on native dev

- common/lib/dependabot/pull_request_creator.rb
- common/spec/dependabot/pull_request_creator_spec.rb
Labeler does not support bitbucket. So don't pass labeler to the pull_request_creator in case Bitbucket is involved.
```
vendor/ruby/2.7.0/gems/dependabot-common-0.154.0/lib/dependabot/pull_request_creator/labeler.rb:241:in `labels': Unsupported provider bitbucket (RuntimeError)
from vendor/ruby/2.7.0/gems/dependabot-common-0.154.0/lib/dependabot/pull_request_creator/labeler.rb:186:in `default_dependencies_label'
from vendor/ruby/2.7.0/gems/dependabot-common-0.154.0/lib/dependabot/pull_request_creator/labeler.rb:178:in `default_labels_for_pr'
from vendor/ruby/2.7.0/gems/dependabot-common-0.154.0/lib/dependabot/pull_request_creator/labeler.rb:49:in `labels_for_pr'
from vendor/ruby/2.7.0/gems/dependabot-common-0.154.0/lib/dependabot/pull_request_creator/bitbucket.rb:85:in …
```
> Bitbucket: creating pull-request-creator fails on labeler not supporting bitbucket

- README.md
Documenting the `DEBUG_HELPERS` and `DEBUG_FUNCTION` env vars used to debug native helpers.
> Add section to debug native helper scripts

- bin/docker-dev-shell
- bin/dry-run.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
Fixes the npm 7 subdependency version resolver by doing an update using
the npm cli, similar to how we do subdependency updates in the lockfile
updater.
Dependabot currently says no update is possible for npm 7 subdependency
updates.
I ran into a few issues testing npm 8 so leaving this out of this PR.
> npm7: Fix subdependency versoion resolver 

- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
For example, this project puts their changelog in Releases.md
https://github.com/denoland/deno/blob/main/Releases.md
I think it is spiritually similar to "release" which is already on
the list.
> Add releases to list of changelog file strings

- nuget/lib/dependabot/nuget/file_parser/packages_config_parser.rb
- nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
- nuget/spec/dependabot/nuget/file_parser/packages_config_parser_spec.rb
- nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
- nuget/spec/dependabot/nuget/file_parser_spec.rb
- nuget/spec/dependabot/nuget/file_updater/packages_config_declaration_finder_spec.rb
- nuget/spec/dependabot/nuget/file_updater/project_file_declaration_finder_spec.rb
- nuget/spec/dependabot/nuget/file_updater_spec.rb
- nuget/spec/dependabot/nuget/metadata_finder_spec.rb
- nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
- nuget/spec/dependabot/nuget/update_checker/requirements_updater_spec.rb
- nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
- nuget/spec/dependabot/nuget/update_checker_spec.rb
- nuget/spec/fixtures/csproj/basic.nuproj
- nuget/spec/fixtures/packages_configs/packages.config
- Addresses issue #4659
- Supports `ItemGroup > DevelopmentDependency` groups in `.csproj` files
- Supports `developmentDependency="true"` in `packages.config`
- Does **not** support development dependencies specified using the `Condition=` property in `<Import />`, etc.
> Adding "devDependencies" support for nuget projects.

- Dockerfile
- cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
- cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
- cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb
- cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
Reverts dependabot/dependabot-core#4588 and bumps to one version higher. The behavior for blank versions seems to have changed in this release of cargo, but the old behavior was not documented, so the tests have been updated to match cargo's new behavior
> Bump cargo from 1.51.0 to 1.58.0

- bin/dry-run.rb
A part of me considered leaving as-is, as it's one of the most context-appropriate typos I've encountered.
> Fix typo: `developerment` -> `development`

- Dockerfile
This makes 2 optimizations to the rust installation process to reduce of the size of the docker image from 4.3GB to 2.8GB.
- Use the [minimal profile](https://rust-lang.github.io/rustup/concepts/profiles.html) which takes less space.
- Specify the desired version at install so we don't additionally install the latest stable version by default.
Pre optimization:
```
[dependabot-core-dev] ~/dependabot-core $ du -sk /opt/rust/toolchains/*
1067576 /opt/rust/toolchains/1.58.0-x86_64-unknown-linux-gnu
1067648 /opt/rust/toolchains/stable-x86_64-unknown-linux-gnu # installed by rustup-init
```
Post optimization:
```
[dependabot-core-dev] ~/dependabot-core $ du -sk /opt/rust/toolchains/*
431624  /opt/rust/toolchains/1.58.0-x86_64-unknown-linux-gnu
```
rustup-init docs:
```
[dependabot-core-dev] …
```
> Optimize rust toolchain installation

- README.md
When I tried running this, i got the following:
```
dependabot-core git:(main) bin/docker-dev-shell
> image dependabot/dependabot-core-development doesn't exist
```
There are two ways I was able to solve this:
```
$ docker pull ghcr.io/dependabot/dependabot-core-development:latest
$ docker tag ghcr.io/dependabot/dependabot-core-development dependabot/dependabot-core-development
$ bin/docker-dev-shell
```
AND
```
$ docker pull ghcr.io/dependabot/dependabot-core-development:latest
$ IMAGE_NAME=ghcr.io/dependabot/dependabot-core-development bin/docker-dev-shell
```
Maybe the dev shell also looks for the ghcr.io version too? Lots of solutions for this. I'm OK with just about any.
> Fix Running with Docker section to find the image that was just pulled

- README.md
We now have a Dependabot category in the GitHub feedback discussions repo: https://github.com/github/feedback/discussions/categories/dependabot-feedback. Let the people know about this!
> Link to GitHub feedback discussion for Dependabot

- Dockerfile
The version has already been updated in the composer.lock of the helper,
but the actual binary was still lagging behind.
> Bump composer v1 binary from 1.10.24 to 1.10.25

- composer/spec/dependabot/composer_spec.rb
Composer versions in the native helpers and dockerfile need to match up. Currently they don't, but there's also no way for us to know right now, so let's add a simple test for it to remind ourselves
> Verify the right version of composer is installed in helper and docker

- docker/lib/dependabot/docker/file_parser.rb
- docker/spec/dependabot/docker/file_parser_spec.rb
- docker/spec/fixtures/docker/dockerfiles/arg_from_no_default
In https://github.com/dependabot/dependabot-core/pull/4598 we added
support for ARG FROM. However, this assumed that a default value is
always specified, when it isn't the code would crash.
This is not that common, however:
Due to how we parse Dockerfiles, this actually also happened for regular
`ARG`s in a Dockerfile, even if it didn't belong to the `FROM`, meaning
that any ARG without a default would cause our update to fail.
> Docker: Ignore ARGs without default values

- bin/bump-version.rb
I often find myself not really knowing if I should be doing a patch or
minor bump for dependabot-core, and what I end up doing is just running
the update with either, looking at the changelog, discarding the changes
and running it again with the right flag.
This adds a `--dry-run` option to the script instead, that allows you to
peek at what would be generated, which can help inform if we should be
doing a patch or minor release.
> Add `--dry-run` flag to `bump-version` script

- cargo/lib/dependabot/cargo/file_updater/manifest_updater.rb
- cargo/spec/dependabot/cargo/file_updater/manifest_updater_spec.rb
- cargo/spec/fixtures/manifests/dotted_key_version
With cargo, it's possible to define a dependency using this syntax:
```
sentry.version = "1.2.3"
sentry.features = ["a", "b", "c"]
```
This PR adds support for this in dependabot-core's manifest updater.
> Support depname.version = "1.2.3" syntax in TOML

- Dockerfile
- terraform/lib/dependabot/terraform/file_updater.rb
This is a minor release from our last version and includes some new features.
https://github.com/hashicorp/terraform/blob/v1.1/CHANGELOG.md#116-february-16-2022
This update triggered a test failure:
```
1) Dependabot::Terraform::FileUpdater#updated_dependency_files when using a lockfile that requires access to an unreachable module raises a helpful error
Failure/Error:
expect { subject }.to raise_error(Dependabot::PrivateSourceAuthenticationFailure) do |error|
expect(error.source).to eq("github.com/dependabot-fixtures/private-terraform-module")
end
expected: "github.com/dependabot-fixtures/private-terraform-module"
got: "git::https://github.com/dependabot-fixtures/private-terraform-module.git"
(compared using ==)
```
I've addressed this by stripping the `git::https://` and `.git` from …
> Bump Terraform from 1.0.11 to 1.1.6

- docker/lib/dependabot/docker/file_parser.rb
- docker/spec/dependabot/docker/file_parser_spec.rb
- docker/spec/fixtures/docker/dockerfiles/arg_from
- docker/spec/fixtures/docker/dockerfiles/arg_from_curls
- docker/spec/fixtures/docker/dockerfiles/arg_from_no_default
This reverts the `ARG FROM` support that was previously added in https://github.com/dependabot/dependabot-core/pull/4598. It was discovered that the implementation was incomplete (https://github.com/dependabot/dependabot-core/issues/4725) as support needs to be extended to the `FileUpdater`. Currently we can detect versions specified as ARGs but we aren't able to create a PR to update them.
I think this is a great feature that would be great to finish but in the meantime the missing `FileUpdater` support is causing an increase in error reports. Reverting this will clear up the errors and give us more time to understand what `FileUpdater` changes will be needed to complete this.
> Temporarily revert Docker arg from support

- Dockerfile
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
- npm_and_yarn/spec/fixtures/projects/npm7/subdependency_update_tab_indentation/package.json
This updates npm to version 8, which is mostly backwards compatible with v7, but drops support for an old version of node.
We've left the references to `npm7` in the codebase (test fixtures and npm version that we reference) as is, because it would become a fairly noisy change and functionally it doesn't change anything. We do plan to follow this up with a PR to update all of those references to `npm8`.
~There is currently one issue that we're digging into which is that the formatting of lockfiles is not respected between updates, and this seems to be caused by a change in npm where in version 8 it bases the formatting (indentation) on the `package.json` instead. When Dependabot performs updates to the `package-lock.json` we strip formatting, so in our case this always results in a large …
> Update to npm 8

- bundler/spec/dependabot/bundler/update_checker_spec.rb
This test intermittently fails, which often trips up external
contributors and ends up wasting CI cycles when we have to retry the
whole thing. We also consistently ignore this failing test, so it seems
better to disable it altogether for now.
> Disable flaky bundler1 test

- pub/lib/dependabot/pub/helpers.rb
By default Dart uses it's own certificate store. This is problematic for
us in production where we send traffic through a proxy to add
authentication headers to requests being made, which uses a randomly
generated certificate that we add to the systems cert store, which will
then be ignored by dart.
This instructs dart to use the system certificates instead.
cc @jonasfj, did I explain that correctly?
> Pub: use system root certificates

- README.md
When I tried to run `dry-run.rb` against a repo where the
dependency files were in a subdirectory, I got a very confusing error.
It took me _way_ too long to realize that parsing `.github/dependabot.yml`
wasn't part of `dependabot-core` therefore I needed to manually pass in
the subdirectory. So document this better for folks doing drive-by PRs.
Temporarily addresses https://github.com/dependabot/dependabot-core/issues/4811, at least until a better runtime error can be emitted.
> Note that the `--dir` flag is required for subdirs

- bundler/script/ci-test
I think it was unintentionally left out from the recent update to Bundler 2.3.8.
> Update ci-test script to use bundler 2.3.8

- bundler/helpers/v2/lib/functions/dependency_source.rb
While investigating a [flaky bundler 2 test](https://github.com/dependabot/dependabot-core/blob/248d927865e172c380992af0f815458ca4026f63/bundler/helpers/v2/spec/functions/dependency_source_spec.rb#L107) I found with the latest bundler update the retries are not idempotent and can lead to an incorrect result. This works around the issue for now by not retrying.
We could add a manual retry to this but in our current test cases of 40x errors a retry is actually not helpful. I think it would be better to observe if not doing a retry leads to a noticeable number of recoverable errors before adding any additional complexity here. We could also end up restoring the built in retries in a future bundler update although I've found it's lacking features like backoff and detecting 400 errors as not …
> Disable spec fetching retries which are not functioning properly

- nuget/lib/dependabot/nuget/version.rb
- nuget/spec/dependabot/nuget/version_spec.rb
Fixes #1972
The pre-release section of the version string was being compared as a single string. Now it is correctly breaking up the dot-separated pre-release identifier and comparing those parts numerically when possible per the semver spec.
Verified this was the issue by running `bin/dry-run.rb nuget "ecoAPM/SrcSet" --dir="/." --commit=d2ec33dd1ea80b40a4f163780281cd4678d5db12 --cache=files` and seeing it no longer bumps Statiq.Web from 1.0.0-beta.33 to 1.0.0-beta.9, instead it chooses 1.0.0-beta.46.
> fixes comparison between prerelease identifiers for NuGet

- bundler/spec/dependabot/bundler/native_helpers_spec.rb
When running specs outside of a Docker context, the `DEPENDABOT_NATIVE_HELPERS_PATH` might not be set, and most likely not to "/opt" if set.
This commit makes the related specs independent of this.
With this patch I only have three spec failures when running `CI=true RAISE_ON_WARNINGS=true SUITE_NAME=bundler1 script/ci-test` outside of a Docker context.
> Fix some specs to pass outside of Docker

- common/lib/dependabot/shared_helpers.rb
When debugging the result of subcommands, I think it's very useful to know which command failed to run, and the environment that it used.
At least this was helpful for me for figuring out some spec failures I was getting.
> Improve `DEBUG_HELPERS` output

- docker/lib/dependabot/docker/file_parser.rb
- docker/spec/dependabot/docker/file_parser_spec.rb
- docker/spec/fixtures/docker/dockerfiles/multiple_args
First PR of fixing Docker ARG support...
https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
`
An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. 
To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage:
`
> Docker: ARG Support: Only replace args outside build stage

- bundler/helpers/v1/Gemfile
- bundler/helpers/v2/Gemfile
I was running the `bundler/script/ci-test` script (well, actually each command separately since I assume it would fail), and I was getting hundreds of errors when running the `bundle exec rspec spec` command after running `bundle install` on the bundler subfolder of the repository.
Errors looked like this:
```
$ DEBUG_HELPERS=true bundle exec rspec ./spec/dependabot/bundler/file_parser_spec.rb:400
Run options: include {:locations=>{"./spec/dependabot/bundler/file_parser_spec.rb"=>[400]}}
Randomized with seed 18517
{"BUNDLER_VERSION"=>"2.3.8", "BUNDLE_GEMFILE"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/lib/dependabot/bundler/../../../helpers/v2/Gemfile", "GEM_HOME"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/lib/dependabot/bundler/../../../helpers/v2/.bundle"} …
```
> Fix webmock requirement in helpers Gemfiles to match dependabot-common

- bundler/helpers/v1/Gemfile
- bundler/helpers/v2/Gemfile
I run into a similar issue as #4838, because `bundle install` had installed RSpec versions compatible with `Dependabot-common` dependencies (RSpec 3.11), but these didn't match the specification in these Gemfiles (RSpec 3.10.2).
This PR proposes the same solution as in #4838. Now all development dependencies are consistent.
> Unify RSpec requirements in helpers Gemfiles to match dependabot-common

- bundler/helpers/v1/monkey_patches/resolver_spec_group_sane_eql.rb
- bundler/helpers/v1/run.rb
- bundler/helpers/v1/spec/native_spec_helper.rb
Sometimes specs run into the following issue:
```
1) Dependabot::Bundler::UpdateChecker::VersionResolver#latest_resolvable_version_details with a rubygems source with no update possible due to a version conflict [:version]
Failure/Error:
SharedHelpers.run_helper_subprocess(
command: command,
function: function,
args: args,
env: {
"BUNDLER_VERSION" => bundler_version,
"BUNDLE_GEMFILE" => File.join(helpers_path, "Gemfile"),
"GEM_HOME" => File.join(helpers_path, ".bundle")
Dependabot::SharedHelpers::HelperSubprocessFailed:
undefined method `name' for "Gemfile":String
```
We never found the real culprit of this, but ruby-core run into the same
issue when testing Bundler, and it was fixed by
https://github.com/rubygems/bundler/commit/30a690edbdf5ee64ea54afc7d0c91d910ff2b80e.
This commit …
> Fix flaky spec failure on Bundler 1 suite

- bundler/lib/dependabot/bundler/native_helpers.rb
- bundler/spec/dependabot/bundler/native_helpers_spec.rb
This makes the `DEBUG_HELPERS` output a bit easier to read.
Before you got something like
```
{"BUNDLER_VERSION"=>"2.3.8", "BUNDLE_GEMFILE"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/lib/dependabot/bundler/../../../helpers/v2/Gemfile", "GEM_HOME"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/lib/dependabot/bundler/../../../helpers/v2/.bundle"}
bundle exec ruby /Users/deivid/Code/dependabot/dependabot-core/bundler/lib/dependabot/bundler/../../../helpers/v2/run.rb
```
Now you get something like:
```
{"BUNDLER_VERSION"=>"2.3.8", "BUNDLE_GEMFILE"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/helpers/v2/Gemfile", "GEM_HOME"=>"/Users/deivid/Code/dependabot/dependabot-core/bundler/helpers/v2/.bundle"}
bundle exec ruby …
```
> Use expanded path when DEPENDABOT_NATIVE_HELPERS_PATH not set

- Dockerfile
`18.04` is getting a bit long in the tooth... `20.04` is the most recent LTS, and `22.04` isn't too far in the future.
I'm sure this will break a bunch of things, so let's try it and see what the tests say...
> Bump Ubuntu to 20.04

- bundler/helpers/v1/Gemfile
- bundler/helpers/v1/monkey_patches/fileutils_keyword_splat_patch.rb
- bundler/helpers/v1/run.rb
- bundler/helpers/v1/spec/native_spec_helper.rb
- bundler/helpers/v2/Gemfile
- common/dependabot-common.gemspec
I was getting 3 spec failures when running dependabot bundler specs on my system.
I debugged it, and the cause turned out to be that I'm using Ruby 3.1.
This PR makes bundler specs fully pass on Ruby 3.1.
Only the first commit is necessary, the second one only fixes some annoying VCR warnings.
> Get bundler specs green when run on Ruby 3.1

- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
When the `get` is not part of the error message, the space won't
appear either, so this regex won't match a genuine error such as:
```
"go: github.com/jenkins-x/jx-api@v0.0.25: invalid version: go.mod has post-v0 module path \"github.com/jenkins-x/jx-api/v3\" at revision v0.0.25\n"
```
This is a bug from https://github.com/dependabot/dependabot-core/commit/b6fa7eecf7dfaaf1dbd30c80c1838a9e27484e79#diff-491ccbbf0ae3cfe37dca8fba172104cc5466631d946daf9639deac37b014692eR21.
I also double-checked the other regexes, and they already correctly include the extra space:
https://github.com/dependabot/dependabot-core/blob/0fd174fd3b49d308030cf57373f106b4fc3aed9f/go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb#L40-L42
The error is only thrown by the tests when upgrading to `go …
> Bugfix: Include space in regex capturing group

- nuget/lib/dependabot/nuget/version.rb
- nuget/spec/dependabot/nuget/version_spec.rb
The [NuGet docs](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200) specify they use SemVer 2.0 [which says](https://semver.org/#spec-item-10):
> Build metadata MUST be ignored when determining version precedence.
Also the NuGet docs say [a little further down](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#where-nugetversion-diverges-from-semantic-versioning) that they depart from SemVer 2.0 in a few ways:
> 1. NuGetVersion supports a 4th version segment, Revision, to be compatible with, or a superset of, [System.Version](https://docs.microsoft.com/en-us/dotnet/api/system.version). Therefore, excluding prerelease and metadata labels, a version string is Major.Minor.Patch.Revision. As per version normalization described above, …
> NuGet versioning does not consider the "build part" in comparisons

- Dockerfile
- go_modules/helpers/go.mod
- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
- go_modules/spec/dependabot/go_modules/file_updater_spec.rb
From https://golang.org/dl/:
* go1.18.linux-amd64.tar.gz
* `e85278e98f57cdb150fe8409e6e5df5343ecb13cebf03a5d5ff12bd55a80264f`
> Bump to `go` `1.18`

- bundler/spec/dependabot/bundler/native_helpers_spec.rb
This is a follow up to #4835.
Right now, if one of these specs start failing, we'll get a very confusing error like the following:
```
Failures:
1) Dependabot::Bundler::NativeHelpers.run_bundler_subprocess with DEPENDABOT_NATIVE_HELPERS_PATH not set uses the full path to the uninstalled run.rb command
Failure/Error:
expect(Dependabot::SharedHelpers).
to have_received(:run_helper_subprocess).
with(
command: "bundle exec ruby #{File.expand_path('../../../v2/run.rb', __dir__)}",
function: "noop",
args: [],
env: anything
)
{"SHELL"=>"/bin/zsh", (... rest of the env...), "GEM_HOME"=>"/Users/deivid/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0"} received :[] with unexpected arguments
expected: ("DEPENDABOT_NATIVE_HELPERS_PATH")
got: ("COLUMNS")
Please stub a default value first if message might be …
```
> Modify ENV in a friendlier way during specs

- github_actions/lib/dependabot/github_actions/file_fetcher.rb
- github_actions/spec/dependabot/github_actions/file_fetcher_spec.rb
- github_actions/spec/fixtures/github/contents_githubaction_repo_base_subdir.json
In an earlier [commit][1] we introduced the feature where dependabot
also looked for "action.ya?ml" files in the root directory in addition
to what could be found in the ".github/workflows/" folder. However,
what was not known at the time was that the action.yml files do not
need to reside directly in the root directory, but may be nested in
subdirectories.
While the code (unintentionally) worked with subdirectories it has now
been updated to be a bit more clear in what it will look for.
[1]: https://github.com/dependabot/dependabot-core/commit/c4f3e6eae592c5c42332719b9e597c8bd47a2db9
> Improve file_fetcher for GitHub Actions

- bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
The specs are still failing, but I think it's better to explicit mark them as pending than to keep them commented out.
> Reenable commented out failing specs

- bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
- bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
- bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
Hello!
I'm having some issues running specs locally, and I won't be able to finish this work (and possibly write some specs) today, but I want to open a WIP PR if that's ok, so that I don't lose the context and that I can check whether the current version of my patch is ok with your CI.
On some of my repositories I'm getting mysterious Ruby version conflict errors that make dependabot updates fail. See for example: https://github.com/activeadmin/arbre/security/dependabot/9, which shows this error:
```
Bundler::VersionConflict with message: Bundler found conflicting requirements for the Ruby version:
In Gemfile:
Ruby (~> 2.6.7.0)
rails (~> 7.0.2) was resolved to 7.0.2.2, which depends on
actionpack (= 7.0.2.2) was resolved to 7.0.2.2, which depends on
Ruby (>= 2.7.0)
```
However, my …
> Fix Ruby version conflict error detection for new Bundler versions

- github_actions/spec/dependabot/github_actions/version_spec.rb
- nuget/lib/dependabot/nuget/version.rb
- nuget/spec/dependabot/nuget/version_spec.rb
I found the NuGet version spec too verbose and hard to read, so I tried switching to a table-driven approach. I find this to be much more readable and maintainable for this particular test.
Also while implementing this, I found another bug in the comparisons!
The bug was due to `zip` returning a shorter array in this case `[1].zip([1, 2])`. I thought it would pad out with nils as in this case `[1, 2].zip([1])` but it does not.
Let me know any Ruby tips to make the style better or if you spot a test that I might have missed.
> fixed a bug and improved testing around NuGet version compare

- Dockerfile
```
> git log --format="%C(auto) %h %s" fbc9732eeeed2c219a84c155f05f5b6222dccd9c..3082796f8ba9b3f509265ac3a223312fb5033988
3082796f dependency_services: Don't download archives on apply (#3352)
48d0ffaf dependency_services: Use ^ constraints for widened intervals when possible (#3349)
826e2086 Remove obsolete test (#3347)
35e5140b Bump analyzer from 2.8.0 to 3.3.1 (#3341)
52f2bdc2 Enable dependabot (#3340)
1e70c0c7 Remove `uploader` command (#3335)
3174a264 Warn if git version is not high enough for supporting all features (#3332)
3f7a3cb7 Don't analyze ignored directories in directory-validator (#3331)
e8f36614 Allow use of token for talking to pub.dev (#3330)
b93bf88f Upgrade `package:tar` to version `0.5.4`. (#3313)
```
The relevant new commits are: 3082796f and 48d0ffaf fixing:
* …
> Update pub dependency_service

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
Dependabot has support for loading file dependencies for npm, and when
these files are larger than 1mb, we have some logic in place to retry
using the Git Data API.
We ran into a case where this would surface a `Blob too large` error,
indicating that the retry via the Git Data API wasn't working as expected,
and it turns out it's because we did not support the `.tar.gz` extension
in our code.
Previously this would cause us to assume this was a nested package.json,
(see [here][npm path dependency ref]) so we'd tack `package.json` onto the
filename, which in turn would cause a 404, which in turn would cause us to
retry without `package.json` attached, only this time using
`_github_repo_contents` instead of `_fetch_file_content_from_github`,
which does not have logic to retry using the Git …
> Npm: Handle `.tar.gz` extensions for path dependencies

- npm_and_yarn/helpers/run.js
I noticed that our helper script currently accesses `process` as an implicit global, rather than an explicit import.
From the [Node.js docs](https://nodejs.org/api/process.html#process):
> The process object provides information about, and control over, the current Node.js process. While it is available as a global, it is recommended to explicitly access it via require or import. 
Not a big deal right now, but this is the kind of thing I could see being deprecated / removed in future releases.
> Explicitly import process in npm_and_yarn helper

- Dockerfile
An early tester pinning to the latest version of the flutter sdk was running into issues. I think this will help.
cc: @jonassf, @sigurdm
> Bump Dart and Flutter to latest stable versions

- pub/lib/dependabot/pub/update_checker.rb
- pub/spec/dependabot/pub/update_checker_spec.rb
When running on GitHub, Dependabot sets `raise_on_ignore` to true in order to determine when a version update is not possible because the user has ignored all possible updates. It's expected that calling the updater's `latest_version` method will raise `AllVersionsIgnored` when that is the case.
cc: @sigurdm, @jonasfj
> Add raise_on_ignore support to Pub

- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
When `go get github.com/org/repo@v1.2.3` starts with an empty module
cache, it appears to prepend an additional status string (copied from https://github.com/dependabot/dependabot-core/issues/4625#issuecomment-1067578732):
[dependabot-core-dev] ~/dependabot-core/tmp/<redacted-org>/repo1 $ GOPRIVATE=* go get -d github.com/<redacted-org>/repo2@v0.39.0
go: downloading github.com/<redacted-org>/repo2 v0.39.0
go get: reading google.golang.org/grpc/go.mod at revision v1.33.0: unknown revision
[dependabot-core-dev] ~/dependabot-core/tmp/<redacted-org>/repo1 $ GOPRIVATE=* go get -d github.com/<redacted-org>/repo2@v0.39.0
go get: reading google.golang.org/grpc/go.mod at revision v1.33.0: unknown revision v1.33.0
[dependabot-core-dev] ~/dependabot-core/tmp/<redacted-org>/repo1 $ go clean -modcache …
> Handle when `go: downloading` is emitted before an unknown revision error

- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
- common/lib/dependabot/metadata_finders/base/commits_finder.rb
- common/spec/dependabot/metadata_finders/base/changelog_finder_spec.rb
- common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb
This pull request Fixes #4897 by replacing the hard-coded `master` with the default branch of the repository
> Metadetafinders: Use the default branch instead of master for gitlab

- Dockerfile
It was released on Feb 25th: https://github.com/rust-lang/rust/releases/tag/1.59.0
> Cargo: Update rust toolchain to 1.59.0

- python/lib/dependabot/python/version.rb
This was added in https://github.com/dependabot/dependabot-core/commit/cdb346e6653e217e6726e44eaefb92b1a8c6c126 as a temporary workaround
until https://github.com/rubygems/rubygems/pull/2651 shipped.
It looks like that shipped in Ruby Gems `3.1.0`, and Dependabot is currently on 
Ruby Gems `3.2.20`: https://github.com/dependabot/dependabot-core/blob/9c090f6fe573aa3b6b05d20920c7c48f5f00403f/Dockerfile#L77
So this should be safe to remove.
Note that I removed the code workaround from the original commit, but
not the test cases... so they should catch any regressions.
> Remove workaround for broken ruby gems compare

- Dockerfile
- bin/update-bundler.rb
- bundler/helpers/v2/build
- bundler/lib/dependabot/bundler/helpers.rb
- bundler/script/ci-test
- bundler/spec/dependabot/bundler/helper_spec.rb
- bundler/spec/spec_helper.rb
This bumps the bundler version to the latest release, and adds a quick
'n dirty script to do it for us going forward.
This solution isn't ideal as places where we reference the version might
change, but I think it's an improvement over manually going through the
files. Also, if we happen to reference the same value as the bundler version
to mean something else in the same file, it'll get updated.
> Bump bundler from 2.3.8 to 2.3.9 and automate it

- Dockerfile
- bin/docker-dev-shell
- bin/dry-run.rb
This PR amends the `Dockerfile` and `bin/docker-dev-shell` commands to support native builds on arm64, as provided by an M1 Mac.
* Initial commits walk the Dockerfile and provide arm64-native alternatives when binaries are fetched.
* There is no Elm, sorry.
* There are no Terraform Debian packages, so I switched to fetching zips.
* In places where the digest of downloaded files is verified, you have two digests to maintain now.
* No attempt is made to build `arm64` in CI, or publish `arm64` releases.
The resulting build stands up OK to light testing: I could dry-run a golang, node and gradle repository.
I hit an error in the bundler that I didn't try to debug:
```
1: from /home/dependabot/dependabot-core/bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:54:in `block …
```
> Dockerfile: arm64 support

- npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb
- The underlying DefinitelyTyped issue was resolved in https://github.com/microsoft/types-publisher/commit/910368a4f23336b0245d9abfe654ac577f36d90c
- The underlying Gatsby issue was resolved in https://github.com/gatsbyjs/gatsby/commit/d6d18e29c0d16d6b5f6030157381584dfb85d4a9
> Remove unnecessary get_directory special cases for npm_and_yarn

- bundler/lib/dependabot/bundler/file_updater/requirement_replacer.rb
- bundler/spec/dependabot/bundler/file_updater/requirement_replacer_spec.rb
Users with case statements in their Gemfile such as this:
```ruby
gem "activemodel", case activemodel_version
when "default"
">= 6.1"
else
"~> #{activemodel_version}"
end
```
Are seeing an error like this:
```
NoMethodError:
undefined method `begin' for #<Parser::Source::Map:0x000000010f824140 @expression=#<Parser::Source::Range (gemfile_content) 22...26>, @node=s(:true)>
requirement_nodes.first.children.first.loc.begin.source,
^^^^^^
```
While rewriting the Gemfile, the code skips over certain AST nodes that would be difficult to handle. 
Adding the case statement to the skip list fixes the error.
> fix error due to not handling case statements in Gemfile

- python/lib/dependabot/python/requirement_parser.rb
- python/lib/dependabot/python/version.rb
- python/spec/dependabot/python/requirement_parser_spec.rb
- python/spec/dependabot/python/version_spec.rb
@kohder thanks for PR #4891!
While I was reviewing that PR I noticed we would also need to add epoch support to the `requirement_parser`, so I went ahead and did that in this branch on top of your changes. I also made a few simplifications to the code and brought in more thorough tests like those in the nuget spec.
Let me know what you think, and I will also get another @dependabot/reviewers to take a look at these changes as well!
Fixes #3165
> Add support for Python packages with epoch version

- Dockerfile
New commits: 
```
> git log --format="%C(auto) %h %s" 3082796f8ba9b3f509265ac3a223312fb5033988...62bb244059415cf0c78b24151472efd46ad7569a
62bb2440 Fix `dependency_services apply` for packages with relative imports (#3374)
a949b329 Fix handling of 'git@github.com:dart-lang/pub.git' style urls in git source (#3381)
c6cd3758 Always use forward slash for relative paths in lockfile (#3379)
7d48f902 Remove unused function (#3370)
b1373d4c Fix import prefix (#3369)
a3a102a5 Fix equality and hashcode for the sdk descriptors (#3367)
94ae66a6 Refine what a relative uri means in a git path (#3212)
cc4c1292 Only call Package.listFiles once per publish. (#3346)
f4484073 Fix test/global/activate/git_package_test test on windows (#3361)
610ce7f2 Refactor descriptors (#3305)
953b6097 Substitute …
```
> Update pub dependency service

- go_modules/lib/dependabot/go_modules/file_fetcher.rb
- go_modules/lib/dependabot/go_modules/update_checker.rb
- go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
While looking at #4954 I noticed the code was gathering main files for some reason, so I pulled the thread and it wasn't attached to anything!
I assume this code was from the days of `dep`. Go modules don't give main files any special treatment, so removing this code.
> code is unsused: main packages have no particular effect on dependencies

- common/lib/dependabot/clients/github_with_retries.rb
- common/spec/dependabot/clients/github_with_retries_spec.rb
We want this value to be configurable so that it can vary by
environment. For example, GHES customers might run Dependabot in a
higher latency network. In these cases, the previous timeout of two
seconds is not enough.
Note: I had wanted to get some tests on these, but relying on constants
to store the values makes the scope of this change larger than I would
like. I'm open to re-architecting if needed. Verification of this change
would also be somewhat sticky as we'd need to reach into the Octokit
client and inspect its values. While I've done that in a debugger, doing
so in a test seems less than ideal.
> Allow open_timeout to be configured by ENV var

- Dockerfile
Before
```bash
dependabot@d0e8d7a84fce:~$ php -i | grep mcrypt
dependabot@d0e8d7a84fce:~$
```
After
```bash
dependabot@102a62523fb5:~# php -i | grep mcrypt
/etc/php/7.4/cli/conf.d/20-mcrypt.ini,
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*, mcrypt.*, mdecrypt.*
mcrypt
mcrypt support => enabled
mcrypt_filter support => enabled
mcrypt.algorithms_dir => no value => no value
mcrypt.modes_dir => no value => no value
```
> added php mcrypt extension 

- python/lib/dependabot/python/requirement.rb
- python/spec/dependabot/python/requirement_spec.rb
When encountering a Python requirement containing parentheses, dependabot-core would throw `Illformed requirement`. 
This fixes that error by unwrapping simple parenthesis patterns. 
I tried looking in the [packaging](https://github.com/pypa/packaging/blob/main/tests/test_requirements.py) and [poetry](https://github.com/python-poetry/poetry-core/blob/master/tests/version/test_requirements.py) tests for more complex examples but could only find simple ones. Hopefully that means this will catch most of the use cases for parentheses inside of a requirement string!
> Python: unwrap arbitrary parentheses from requirement string

- nuget/lib/dependabot/nuget/metadata_finder.rb
- nuget/spec/dependabot/nuget/metadata_finder_spec.rb
- nuget/spec/fixtures/nuspecs/index.json
- nuget/spec/fixtures/nuspecs/microsoft.extensions.depdencymodel-results.json
Dependabot PRs are missing the release notes and commits sections that we expect them to have when using a private NuGet registry like nuget.pkg.github.com.
This is because the GitHub NuGet registry doesn't support downloading `.nuspec` files currently, and [this is the way we're finding the source repo of the project](https://github.com/dependabot/dependabot-core/blob/bdbf87a1f64594997092fc74f3998b17b75d8ec4/nuget/lib/dependabot/nuget/metadata_finder.rb#L58-L77).
The `.nuspec` URL is part of the [NuGet Server spec](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-manifest-nuspec).
This PR adds a fallback to try to find the `projectUrl` or `licenseUrl` in the search data, which ***might*** contain the repo. The search URL is supported by GitHub …
> nuget: fix PR missing commits in message when using private registry

- bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
- bundler/spec/dependabot/bundler/file_updater_spec.rb
- bundler/spec/fixtures/projects/bundler1/unsatisfied_required_ruby_version/Gemfile
- bundler/spec/fixtures/projects/bundler1/unsatisfied_required_ruby_version/Gemfile.lock
- bundler/spec/fixtures/projects/bundler1/unsatisfied_required_ruby_version/example.gemspec
- bundler/spec/fixtures/projects/bundler2/unsatisfied_required_ruby_version/Gemfile
- bundler/spec/fixtures/projects/bundler2/unsatisfied_required_ruby_version/Gemfile.lock
- bundler/spec/fixtures/projects/bundler2/unsatisfied_required_ruby_version/example.gemspec
To ensure that no Ruby resolution conflicts are generated.
This PR fixes the issue mentioned in [this comment](https://github.com/dependabot/dependabot-core/issues/4987#issuecomment-1098804316).
> Use a temporary Ruby requirement for updating lockfile

- Dockerfile
- bundler/helpers/v2/build
- bundler/helpers/v2/monkey_patches/definition_ruby_version_patch.rb
- bundler/lib/dependabot/bundler/helpers.rb
- bundler/script/ci-test
- bundler/spec/dependabot/bundler/helper_spec.rb
- bundler/spec/spec_helper.rb
Includes a small change in monkeypatches to catch up with
https://github.com/rubygems/rubygems/commit/21c145cb232c5266b330d4f6df2c8c635930e23c.
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2311-april-7-2022
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2312-april-20-2022
Dependabot should give slightly better errors on Ruby version conflicts with this version.
> Update Bundler from 2.3.10 to 2.3.12

- npm_and_yarn/lib/dependabot/npm_and_yarn/package_name.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/package_name_spec.rb
Now that we can translate from library to types package (e.g. `jquery` -> `@types/jquery`), we need to be able to translate in the other direction (e.g. `@types/jquery` -> `jquery`).
> Translate from `@types` package to library name

- Dockerfile
The RubyGems version had fallen a bit behind. I didn't update all the way to the latest 3.3.12 because there's a bug in 3.3.12 that might affect Dependabot (I don't think so, but just in case). Also I think it makes sense to use `--no-document` for updating it because it's faster.
> Update RubyGems and use `--no-document` for updating it

- CHANGELOG.md
- common/lib/dependabot/version.rb
- Prevent KeyError when checking search results (@brrygrdn) [#5038](https://github.com/dependabot/dependabot-core/pull/5038)
- Update RubyGems and use `--no-document` for updating it (@deivid-rodriguez) [#5035](https://github.com/dependabot/dependabot-core/pull/5035)
- Translate from `@types` package to library name (@landongrindheim) [#5025](https://github.com/dependabot/dependabot-core/pull/5025)
- Add ecosystem-specific code owners (@mattt) [#4614](https://github.com/dependabot/dependabot-core/pull/4614)
- fix typos in GitHub issue bug report template (@tyrann0us) [#5015](https://github.com/dependabot/dependabot-core/pull/5015)
- Update Bundler from 2.3.10 to 2.3.12 (@deivid-rodriguez) [#5018](https://github.com/dependabot/dependabot-core/pull/5018)
- build(deps): bump @npmcli/arborist …
> v0.182.1 Release notes

- bundler/lib/dependabot/bundler/native_helpers.rb
We've encountered an issue in the move forward to bundler 2.3.12 where our approach to setting the `BUNDLER_VERSION` in native helpers now behaves differently.
Using `v0.182.0`, you can observe the behaviour like so:
```
$ cd bundler/helpers/v1
$ bundle install
$ BUNDLER_VERSION=1.14.6 bundler -v
> Bundler version 1.17.3
```
On main the behaviour is like so:
```
$ cd bundler/helpers/v1
$ bundle install
$ BUNDLER_VERSION=1.14.6 bundler -v
> Bundler version 2.3.12
```
We updated this behaviour in https://github.com/dependabot/dependabot-core/pull/4132 when we noted that passing in just the major version, i.e. `BUNDLER_VERSION=1` no longer worked and we started using the _detected_ version instead, which bundler would previously 'guess' at a near match.
This modifies our `native_helper` …
> Set BUNDLER_VERSION to the specific installed version in native helpers

- Dockerfile
We attempted to resolve an issue around Bundler version detection for projects using Bundler 1.x in https://github.com/dependabot/dependabot-core/pull/5044, but this wasn't sufficient to fix the issue.
We've verified that the issue is resolved by reverting our recent RubyGems update so we're reverting #5035 to unblock releasing forward and we will reintroduce the RubyGems upgrade once we have determined root cause.
> Rollback RubyGems from 3.3.11 to 3.2.20

- CHANGELOG.md
- common/lib/dependabot/version.rb
- Rollback RubyGems from 3.3.11 to 3.2.20 (@mctofu) [#5048](https://github.com/dependabot/dependabot-core/pull/5048)
> v0.182.4 Release Notes

- .vscode/launch.json
- common/dependabot-common.gemspec
Reverts #4971
@pavera Unfortunately debase started failing to build in Codespaces. 
I noticed this on my machine a couple weeks ago as well and managed to work around it by changing debase versions and ruby versions. It seems others are having this issue as well: https://github.com/ruby-debug/debase/issues/98
I tried a couple different versions of debase and they all failed, so I guess we should roll this back for now? Any ideas we can try before we do this?
> fix debase build errors

- cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
- common/lib/dependabot/clients/bitbucket.rb
- common/lib/dependabot/git_metadata_fetcher.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
Excon has a builtin retry of 4 when using idempotent: true. The retries removed by this PR were multiplying the total retries done. So for NPM, with 2 retries a total of 12 retries are made.
We think 4 retries are probably enough! This will probably make some jobs succeed that were hitting the maximum wait limit since doing 12 retries can take quite a while. 
*Implementation note:*
BitBucketWIthRetries delegates to BitBucket and it seems like the intent was to not retry using BitBucket, so there I set idempotent to false with a note as to why. The other option is to remove BitBucketWithRetries entirely which I am not opposed to. Any opinions there?
> remove multiplicative retries to improve system health

- .github/workflows/codeql-analysis.yml
Related to #5108 
14 of the 30 code scanning alerts triggered for test fixtures with "Dependency download using unencrypted communication channel". This behavior is intentional, and should be ignored. For example:
https://github.com/dependabot/dependabot-core/blob/bef818879143045aec43af0c46b9c6019dba3358/bundler/spec/fixtures/projects/bundler2/includes_requires_gemfile/Gemfile#L1-L1
This PR updates our CodeQL workflow to ignore anything in a spec/fixture subdirectory from future analysis.
> Add fixtures to `paths-ignore` for CodeQL workflow

- common/spec/warning_monkey_patch.rb
The current version of the warning:
```
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```
So I removed the TODO comment because it's outdated. 
But I left the actual exclusion in because it will be a recurring issue from time to time because https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu can be a little slow to update...
for example see various discussions on the mailing list that sometimes get no response from
the maintainers: https://groups.google.com/g/brightbox-ruby-ubuntu-packaging
> Clarify comment and remove TODO

- npm_and_yarn/lib/dependabot/npm_and_yarn/package_name.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/package_name_spec.rb
The current logic for determining whether a package has the Definitely Typed `@types` scope uses an unanchored regular expression, causing false positives on packages like `@typescript-eslint/parser`.
This PR replaces the check with the [`casecmp?`](https://apidock.com/ruby/v2_6_3/String/casecmp%3F) method, which performs a case-insensitive string equality check.
> Fix implementation of `PackageName#library_name`

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
The current implementation of `original_package_update_available?` and `types_update_available?` in `Dependabot::NpmAndYarn::UpdateChecker::VersionResolver` calls `Version.new` without first validating, which raises an exception.
This PR adds missing calls to `Version.correct?` and returns from these methods early.
> Validate before creating version objects in `Dependabot::NpmAndYarn::UpdateChecker::VersionResolver`

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_and_npm/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_and_npm/package.json
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_only/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_only/package.json
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_with_ports/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/private_registry_ghpr_with_ports/package.json
Assuming a project has the following config:
**dependabot.yml**
```yml
version: 2
registries:
private-npm:
type: npm-registry
url: example.com/artifactory/api/npm/example
username: ${{secrets.USER}}
password: ${{secrets.PASS}}
updates:
- package-ecosystem: "npm"
registries:
- private-npm
schedule:
interval: "daily"
```
In their package.json they have a dependency from their private registry, which has a `resolved` URL in the form:
```
https://example.com:443/artifactory/api/npm/example/@example/example-client/-/@example-corp/example-client-1.0.0.tgz
```
This will result in confusing behaviour where we will correctly find the latest version in the private registry but fail to actually update the package with a `private_source_authentication_failure`.
The …
> Fix Dependabot ignoring scoped registries if the lockfile resolved uri contains a port number

- common/lib/dependabot/shared_helpers.rb
- common/spec/dependabot/shared_helpers_spec.rb
- maven/lib/dependabot/maven/file_parser/repositories_finder.rb
Excon has a default retry strategy of `4` requests.
As part of Maven updates, we attempt to find a list of repository URLs to lookup in "parent" pom files, but generally treat a non-200 response as a nil return. In the case a parent URL points to a host that is unreachable, we can spend up to 100 seconds attempting a single this with the current configuration.
We should tolerate network weather, but 5 attempts is fairly excessive, so let's drop to a single retry for 2 attempts overall.
> [Maven] Avoid retrying requests to repos excessively

- maven/lib/dependabot/maven/update_checker/property_updater.rb
- maven/lib/dependabot/maven/update_checker/version_finder.rb
This PR collects up a pass on any methods that make `Excon.get` calls which attempt to memoize the outcome of requests.
I found a couple of cases where the pattern used wouldn't correctly memoize falsy values and fall through to making the request a second time.
From walking through the code I don't think these will have any performance implications unfortunately, I don't believe these methods are called more than once in any of our runtimes, but it could catch us out in future.
> [Maven] Fix some malformed memoizations

- bin/dry-run.rb
- common/lib/dependabot/shared_helpers.rb
- common/spec/dependabot/shared_helpers_spec.rb
We are currently investigating some slow running jobs and one thing that is noticeable is that some ecosystem implementations tend to make excessive network calls within core's code.
This change does two things:
- Adds `ActiveSupport::Notification` as a generic instrumentor for `Excon`, per the [docs](https://github.com/excon/excon#instrumentation)
- Adds a `--network-trace` argument to the dry-run script that optionally prints out every request made during the run along with a total count at the end of the job
Example:
```log
$ bin/dry-run.rb maven "apache/avro" --dir="/lang/java" --cache=files --dep "org.eclipse.jetty:jetty-server" --network-tracing
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see …
```
> Add --network-trace to dry-run

- CHANGELOG.md
- common/lib/dependabot/version.rb
- Fix Bundler v2 related TODOs (@deivid-rodriguez) [#5034](https://github.com/dependabot/dependabot-core/pull/5034)
- Add network tracing to dry-run (@brrygrdn) [#5131](https://github.com/dependabot/dependabot-core/pull/5131)
- [Maven] Fix some malformed memoizations (@brrygrdn) [#5132](https://github.com/dependabot/dependabot-core/pull/5132)
- bundler: upgrade to 2.3.13 for rubygems/rubygems#5492 (@jakecoffman) [#5134](https://github.com/dependabot/dependabot-core/pull/5134)
- [Maven] Avoid retrying requests to repos excessively (@brrygrdn) [#5130](https://github.com/dependabot/dependabot-core/pull/5130)
- [Npm][Yarn] Fix Dependabot ignoring scoped registries if the lockfile resolved uri contains a port number (@brrygrdn) [#5124](https://github.com/dependabot/dependabot-core/pull/5124)
> v0.187.0 Release notes

- common/lib/dependabot/dependency_file.rb
- common/spec/dependabot/dependency_file_spec.rb
- docker/spec/dependabot/docker/file_parser_spec.rb
- docker/spec/fixtures/docker/dockerfiles/bom
Resolves #5118
From the [Unicode FAQ about BOM](https://www.unicode.org/faq/utf_bom.html#BOM) (emphasis added):
> Q: What is a BOM?
> A: A byte order mark (BOM) consists of the character code U+FEFF at the beginning of a data stream, where it can be used as a signature defining the byte order and encoding form, primarily of unmarked plaintext files. Under some higher level protocols, use of a BOM may be mandatory (or prohibited) in the Unicode data stream defined in that protocol.
> Q: Can a UTF-8 data stream contain the BOM character (in UTF-8 form)? If yes, then can I still assume the remaining UTF-8 bytes are in big-endian order?
> A: Yes, UTF-8 can contain a BOM. However, it makes no difference as to the endianness of the byte stream. UTF-8 always has the same byte order. An initial …
> Strip UTF-8 BOM from file contents

- .github/workflows/ci.yml
The release process is already pretty lengthy, so this allows us to skip the CI step when cutting release notes. We could use admin powers to merge before CI is complete but that is a bad habit.
> skip CI workflow when creating release notes

- CHANGELOG.md
- common/lib/dependabot/version.rb
- [Maven] Cache client-side timeouts when a remote host is unreachable (@brrygrdn) [#5142](https://github.com/dependabot/dependabot-core/pull/5142)
- build(deps): bump @npmcli/arborist from 5.1.0 to 5.2.0 in /npm_and_yarn/helpers [#5133](https://github.com/dependabot/dependabot-core/pull/5133)
EDIT: Updated to include a fix for v0.188
- Revert "Strip UTF-8 BOM from file contents" (@mattt) [#5145](https://github.com/dependabot/dependabot-core/pull/5145)
> v0.189.0 Release Notes

- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
We have "required checks" configured for the CI, and so if the CI never runs then the build will never pass. So this creates a workflow which runs during a release with identical names to the real CI workflow, but doesn't run the real tests.
We also thought it would be a good idea to skip the CodeQL step during a release since it probably won't detect any issues. The CodeQL isn't currently required so no codeql-analysis-release.yml required yet!
See https://github.com/dependabot/dependabot-core/pull/5143
> fix required checks not run during a release

- Dockerfile
There's no need for the comments to specify the versions when
the code with the actual version pin is just a couple of lines below.
Removing the version from the comment removes the chance that the comment diverges from the code.
It also makes future PR's simpler because they have one less thing to remember to update.
> Remove versions from comments

- nuget/lib/dependabot/nuget/update_checker/version_finder.rb
Fixes #5166
Some Nuget repositories, such as JFrog's Artifactory, URL encode the "next" href link in the paged results. If the href is not URL decoded, the paging parameters are ignored and the first page is always returned. This change URL decodes the href before fetching the next page of version results.
> URL decode Nuget API v2 "next" link when paging version results

- nuget/lib/dependabot/nuget/update_checker/version_finder.rb
Since this link will always work on GitHub regardless of whether escaped or not,
I added an inline code comment with the commit message from 62366e46fea1b0c9e56d55a9aca8b1bbeb86b43b.
That way someone doesn't accidentally pull this out and think they're okay just
because everything continues to work on GitHub.
I meant to tag this onto #5174 but then forgot before I clicked the merge button.
> Document why the link needs to be unescaped

- npm_and_yarn/helpers/test/npm6/fixtures/updater/updated/package-lock.json
- npm_and_yarn/helpers/test/yarn/fixtures/updater/updated/yarn.lock
- npm_and_yarn/spec/fixtures/updated_projects/npm6/simple/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm6/subdependency_update_tab_indentation/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/packages_name_missing/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/packages_name_outdated/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/simple/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/simple_no_indentation/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/subdependency_update_tab_indentation/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/workspaces_dev/package-lock.json
We are getting some [npm ci failures](https://github.com/dependabot/dependabot-core/runs/6665124687?check_suite_focus=true) from tests that run against the actual npm registry. Some dependencies have been returning sha512 hashes instead of sha1. This updates the failing test cases to expect the sha512 hashes.
> Update test cases with new hashes returned from npm registry

- Dockerfile
This pulls in a fix of https://github.com/dependabot/dependabot-core/issues/5199
New commits:
```
> git -C ~/projects/pub log --format="%C(auto) %h %s" 1e3c17ea871e6a80c720aa998f37cbd3913bc287..6f20a94b074a1c2dc82d429fa04d365b4bcf65b6
6f20a94b Handle missing pubspec.lock in dependency_services list (#3439)
0ad17e84 Handle broken response from userinfo_endpoint (#3427)
153ef061 `pub add` create top-level attribute in block-style if possible. (#3423)
3b96f910 Handle error code 183 on windows (#3426)
9eb6428c Ignore `pubspec_overrides.yaml` for `publish` command (#3419)
51435efc Reland "Add flag controlling creation of `.packages` file." (#3413)
```
For dependabot the only one relevant is
```
6f20a94b Handle missing pubspec.lock in dependency_services list (#3439)
```
> Update pub revision

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
Instruments the package manager version for npm and yarn similar to [how we instrument bundler versions](https://github.com/dependabot/dependabot-core/blob/e96b546e8d6bbe723732ba9657f9008c75c0424a/bundler/lib/dependabot/bundler/file_parser.rb#L46-L55)
Note: 
This PR instruments in the FileFetcher step so it should only run once.
The dry-runner shows this too
```shell
[dependabot-core-dev] ~/dependabot-core $ SECURITY_ADVISORIES='[{"dependency-name":"node-forge","patched-versions":[],"unaffected-versions":[],"affected-versions":["< 0.10.0"]},{"dependency-name":"node-forge","patched-versions":[],"unaffected-versions":[],"affected-versions":["< 1.0.0"]},{"dependency-name":"node-forge","patched-versions":[],"unaffected-versions":[],"affected-versions":["< 1.3.0"]}]' bin/dry-run.rb …
```
> Instrument npm version

- bin/dry-run.rb
Follow up to https://github.com/dependabot/dependabot-core/pull/5187
Prints package manager version instrumentation events in the dry runner
Previously in this PR, the dry runner would print out the package manager version log when the notification event occurred, but really it should only be logged once per ecosystem. 
Since the additional logging was polluting, I modified the dry runner to instead print out the logging event(s) at the end of the run.
The dry runner will still show all the package manager version log events in case it really is logged more than once per ecosystem
```
🌍 Total requests made: '7'
🎈 Package manager version log: {:ecosystem=>"npm", :package_managers=>{"npm"=>8, "yarn"=>1}}
```
> Print package manager version instrumentation events in the dry runner

- bin/dry-run.rb
I extracted this commit from https://github.com/dependabot/dependabot-core/pull/5221, because it's also useful for me to (fix) #4867.
If I understand correctly, both https://github.com/rubygems/rubygems/pull/5520 and #5221 are fixing the same issue but for different ecosystems, and we both run into the same issue where the dependency is properly updated but `bin/dry-run.rb` still reports conflicts.
> Only report conflicting dependencies when update is not possible

- pub/helpers/pubspec.lock
- pub/helpers/pubspec.yaml
Based on @sigurdm's [suggestion](https://github.com/dependabot/dependabot-core/issues/5199#issuecomment-1154825560) this bumps the revision of Pub used to match the previous version used in https://github.com/dependabot/dependabot-core/pull/5203. This fixed an [issue](https://github.com/dependabot/dependabot-core/issues/5199) with projects without lockfiles failing to update. 
In https://github.com/dependabot/dependabot-core/pull/5207 the method of pinning to the Pub revision changed and we accidentally pinned to an older version of Pub without the fix.
> Bump pub revision to fix error without lockfile

- cargo/lib/dependabot/cargo/file_fetcher.rb
- cargo/spec/dependabot/cargo/file_fetcher_spec.rb
- cargo/spec/fixtures/github/contents_cargo_submodule.json
In Cargo.toml a user can add this to override a dependency:
```
[patch.crates-io]
uuid = { path = './path/to/uuid' }
```
This doesn't work in Dependabot if `path/to/uuid` is a submodule since the file doesn't exist in this repository. So I've added the "fetch_submodules: true" flag which handles this case.
> cargo: handle patch with path that is a submodule

- Dockerfile
Updates TERRAFORM_VERSION in Dockerfile to 1.2.3
Fixes an important bug fixed in 1.2.1 also referred to here: https://github.com/hashicorp/terraform/pull/31091
Release notes for version 1.2.3:
https://github.com/hashicorp/terraform/releases/tag/v1.2.3
> Updates TERRAFORM_VERSION in Dockerfile to version 1.2.3

- .github/workflows/ci.yml
With our changes in #5295, we inadvertently removed a step that rebuilds `dependabot/dependabot-core` before using it as a base image in `Dockerfile.ci`. This would cause any changes to system libraries or native helpers in a branch to be missing from CI runs for PRs for that branch.
This PR adds a step to the CI workflow to rebuild `dependabot/dependabot-core`.
> Rebuild dependabot-core image in CI Workflow

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
When responding to rebase requests Dependabot will re-run the job using the first dependency in the PR. Since we aren't enforcing the target dependency is at the front of the list the rebase could run against a different dependency and produce a different result.
I only wanted to re-order the results with https://github.com/dependabot/dependabot-core/commit/7c2c02ae85762d8b7463feae5c098a34dd2c0374 but had to do a little bit more to satisfy Rubocop's complexity requirements.
> Prioritize target dependency in transitive dependency updates

- .rubocop.yml
Rubocop for the omnibus started failing today. This does what it asks in an attempt to fix it.
```
Error: The `Gemspec/DateAssignment` cop has been removed. Please use `Gemspec/DeprecatedAttributeAssignment` instead.
(obsolete configuration found in /home/dependabot/dependabot-core/.rubocop.yml, please update it)
```
> Fix rubocop configuration error

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
- npm_and_yarn/spec/fixtures/github/package_json_with_nested_glob_workspaces.json
- npm_and_yarn/spec/fixtures/github/packages_files_nested3.json
So now it can successfully expand a glob like `packages/*/*`.
Resolves https://github.com/dependabot/dependabot-core/issues/1777
~~**NOTE**: this PR is based on top of https://github.com/dependabot/dependabot-core/pull/5220~~
**UPDATE**: the previously mentioned PR is already merged, so this one is rebased now.
> Yarn: support recursive paths expansion

- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
To support dependencies in private registries we need to forward the credentials we've passed to npm along to arborist.
I was able to extract registry scopes from the existing npm config we parse from the `npm config list --json` command. Unfortunately that doesn't return credentials so I needed to do a second pass to read them directly from the project's `.npmrc` file.
In the future we hope to be able to replace this with a npm maintained library to load the configuration.
> Configure arborist registries from npm config

- npm_and_yarn/helpers/lib/npm/conflicting-dependency-parser.js
- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
When executing updates via the npm clis we pass the `--ignore-scripts` flag to prevent dependencies from running untrusted code during dependency updates.
ex: https://github.com/dependabot/dependabot-core/blob/5574067c44c06042a352dbedd9b2b8b34a89eb77/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb#L177-L192
We should do the same for our usage of Arborist. This wasn't a documented option but I found this flag is honored in https://github.com/npm/cli/blob/5a50762faa37ae5964ae6f12595b20b367056c0a/workspaces/arborist/lib/arborist/rebuild.js#L50-L68
> Disable potential script execution in arborist

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
The underlying JavaScript helper invoked by the vulnerability auditor consistently returns a JSON object with predictable fields, including a `fix_updates` JSON array. If the vulnerability auditor reaches an exceptional code path, or if the helper raises an exception, it should also similarly return a hash with the same fields, including `fix_updates`, so that downstream code can safely rely on this.
> [npm] Ensure 'fix_updates' field in `VulnerabilityAuditor#audit` response

- go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
We've seen flakiness with this particular test. It's stubbing out a response to execution of `go get` but only captures our [2nd call](https://github.com/dependabot/dependabot-core/blob/e44578d99d6c925de2823ea52712dc78149f83cb/go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb#L96-L99) to it. Our initial call to `go get github.com/spf13/viper@v1.7.1` is unstubbed so can fail if there's issues resolving the update for that external dependency. I've adjusted the test to stub the initial usage of `go get` instead. The failure that it returns will prevent the 2nd call to `go get`.
> [go_mod] Stub failed response for initial go get call

- bin/bump-version.rb
Historically we've not attributed the core team in release notes, as the
mentions can be a bit noisy and I guess because it's our job to
contribute to Dependabot :smile:
To do so, we used to pull the `reviewers` team, but that team is no
more, and is now called `maintainers`, so I've updated our
`bump-version` script to pull in that team instead.
> Do not attribute `maintainers` in release notes

- Dockerfile
Following up on #5356, this PR uses `ruby-install` to install [Ruby 2.7.6](https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/), which is the most up-to-date 2.7 release.
> Update Ruby to version 2.7.6

- python/lib/dependabot/python/file_fetcher.rb
- python/spec/dependabot/python/file_fetcher_spec.rb
- python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb
- python/spec/fixtures/github/contents_python_pyproject_and_requirements_without_setup_py.json
- python/spec/fixtures/github/contents_python_pyproject_and_setup_cfg.json
Previously, Dependabot would assume that for every requirements.txt with
a self-reference (`-e .`), we should expect a `setup.py` to be present. The
self-reference is considered a path dependency that needs a setup.py.
However, nowadays it's valid to have a requirements.txt without a
setup.py. This change accounts for that by still attempting to pull in a
setup.py if it exists, but to not raise and error when it doesn't.
Closes https://github.com/dependabot/dependabot-core/pull/5324
Resolves https://github.com/dependabot/dependabot-core/issues/4483
> Pip: Do not raise PathDependenciesNotReachable for missing setup.py

- python/lib/dependabot/python/metadata_finder.rb
- python/lib/dependabot/python/update_checker.rb
- python/lib/dependabot/python/update_checker/latest_version_finder.rb
See: https://github.com/dependabot/dependabot-core/pull/5373
This PR modifies the timeout caching strategy we used for Maven into a generic 'Dependabot::RegistryClient' and then applies it to the `python` gem to ship this strategy for another ecosystem.
Python is currently in the two three ecosystems experiencing this issue, but it's a little lower frequency than NPM so it might be worth shipping this first.
> [Python] Cache client-side timeouts when a remote host is unreachable

- composer/lib/dependabot/composer/metadata_finder.rb
- composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
This PR switches Composer over to use the `Dependabot::RegistryClient` so it benefits from caching of unreachable hosts.
> [Composer] Cache client-side timeouts when a remote host is unreachable

- bin/bump-version.rb
Small nitpick, it makes me nervous to use `git push --tags` in the event I've accidentally created all release-like tags locally and accidentally push something to RubyGems, etc
> Tweak bump-version script to just push the newly-created tag

- nuget/lib/dependabot/nuget/metadata_finder.rb
- nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
- nuget/lib/dependabot/nuget/update_checker/version_finder.rb
This PR switches Nuget over to use the `Dependabot::RegistryClient` so it benefits from caching of unreachable hosts.
> [Nuget] Cache client-side timeouts when a remote host is unreachable

- cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
- cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb
- cargo/spec/fixtures/manifests/bare_version_specified_as_optional
- cargo/spec/fixtures/manifests/cargo-registry-s3-ssl-optional
- cargo/spec/fixtures/manifests/path_dependency_feature_enabled
This change fixes an unexpected nil error when a project has a path dependency which includes one or more optional sub-dependencies that are not included by default.
I believe this behaviour is the most correct as we rely on Cargo to generate a lockfile from which to determine the latest version; for a disabled optional sub-dependency it won't be present in the generated lockfile, so we should treat it as unused and return nil.
> [Cargo] Correctly handle unused subdependencies of path dependencies

- common/lib/dependabot/source.rb
- common/spec/dependabot/source_spec.rb
> fix: regex to support Gitlab subgroups

- go_modules/lib/dependabot/go_modules/path_converter.rb
This PR switches gomod over to use the Dependabot::RegistryClient so it benefits from caching of unreachable hosts.
> [gomod] Cache client-side timeouts when a remote host is unreachable

- .github/dependabot.yml
I was surprised I had to manually open #5030 until I realized
that the docker ecosystem was never enabled for Dependabot.
So this fixes that.
> Add dependabot updates for Dockerfiles

- Dockerfile
Previously, it was easy to lose track of this comment because it's
located quite a ways from the code. Moving it makes it less likely that
packages will listed in the wrong category.
Although I'd happily bet an ice cream cone that the comment is
partially incorrect and some of the listed packages are not just for
python.
> Move comment to relevant section of code

- .github/dependabot.yml
We tend to take a while before we're able to review and merge these PRs
anyway, so to cut through some of the noise I think we can live with a
weekly cadence for updates.
If there are any high priority updates we can always kick off a manual
run.
> Switch to weekly updates for Dependabot

- elm/lib/dependabot/elm/update_checker.rb
- gradle/lib/dependabot/gradle/metadata_finder.rb
- gradle/lib/dependabot/gradle/update_checker/version_finder.rb
- hex/lib/dependabot/hex/metadata_finder.rb
- hex/lib/dependabot/hex/update_checker.rb
- pub/lib/dependabot/pub/metadata_finder.rb
This PR collects up the final swap over from using `Excon` directly to using `Dependabot::RegistryClient` to cache unreachable hosts and provide an interface to start adding more logging/caching behaviour in future.
> Cache client-side timeouts when a remote host is unreachable for remaining ecosystems

- .github/workflows/docker.yml
We've been running on `20.04` since https://github.com/dependabot/dependabot-core/pull/4394, I just didn't realize this actions workflow also pinned the version. So this bumps to our current base image.
Unfortunately, this will likely be outdated in the future again, once #5030 lands... and likely to be an ongoing issue of drift whenever we bump Ubuntu versions.
I wish there was an easy way to extract this value from the Dockerfile, but everything I come up with seems quite hacky/brittle.
> Bump base image in docker push workflow to `20.04`

- docker/lib/dependabot/docker/file_parser.rb
- docker/lib/dependabot/docker/utils/credentials_finder.rb
The unescaped '.' before 'amazonaws.com' could match more hosts than
expected.
Discovered via CodeQL.
Fix https://github.com/dependabot/dependabot-core/security/code-scanning/6
Fix https://github.com/dependabot/dependabot-core/security/code-scanning/7
> Fix incomplete regular expression for hostnames

- .github/dependabot.yml
Previously Dependabot watched the top-level gemspec, but not the
per-ecosystem gemspecs.
Historically we haven't had much (any?) per-ecosystem gem requirements,
so this hasn't been a problem before.
But it's probably wiser if we start watching these. Especially because
for the Ruby 3.1 upgrade we will likely need to add a specific dependency
on `webrick` to `pub/dependabot-pub.gemspec`.
> Make Dependabot watch the per-ecosystem gemspecs

- github_actions/lib/dependabot/github_actions/file_parser.rb
- github_actions/spec/dependabot/github_actions/file_parser_spec.rb
- github_actions/spec/fixtures/workflow_files/non_github_source.yml
I don't think we realized that we lacked the ability to fetch Actions
from non-GitHub.com sources. With this change, we're now able to fetch
Actions from GitHub Enterprise Server instances.
> Allow Actions to be fetched from non-GitHub source

- Dockerfile
The `--no-document` flag [skips installing documentation](https://guides.rubygems.org/command-reference/#installupdate-options), so is faster.
This was originally proposed by @deivid-rodriguez as part of
https://github.com/dependabot/dependabot-core/pull/5035, but was lost when https://github.com/dependabot/dependabot-core/pull/5048 reverted the version bump.
So this adds back only the `--no-document` flag, but doesn't touch the
version.
> Update ruby gems using the `--no-document` flag

- Dockerfile
I noticed the [following logs during the docker build](https://github.com/dependabot/dependabot-core/runs/7646741836?check_suite_focus=true#step:3:5062):
```
0.906 You are in 'detached HEAD' state. You can look around, make experimental
0.906 changes and commit them, and you can discard any commits you make in this
0.906 state without impacting any branches by switching back to a branch.
0.906
0.906 If you want to create a new branch to retain commits you create, you may
0.906 do so (now or later) by using -c with the switch command. Example:
0.906
0.906   git switch -c <new-branch-name>
0.906
0.906 Or undo this operation with:
0.906
0.906   git switch -
0.906
0.906 Turn off this advice by setting config variable advice.detachedHead to false
```
Passing the config this way sets it _only_ …
> Suppress "detached head" advice during `git clone`

- Dockerfile
I noticed that our Ruby installs included generating docs, which takes
~30 seconds:
https://github.com/dependabot/dependabot-core/runs/7646741836?check_suite_focus=true#step:3:5996
But we don't need docs in our docker images--humans can always look them
up online.
So skip installing docs and cut 30s off our CI times.
Thanks to @deivid-rodriguez for the tip on [how to pass the arg through
`ruby-install` to the underlying `ruby`](https://github.com/dependabot/dependabot-core/issues/5475#issuecomment-1204742884).
Fix #5475
> Skip installing docs when installing Ruby

- composer/lib/dependabot/composer/file_fetcher.rb
- composer/spec/dependabot/composer/file_fetcher_spec.rb
- composer/spec/fixtures/github/composer_json_with_nested_path_deps.json
- composer/spec/fixtures/github/contents_ruby_nested_path_directory_one.json
- composer/spec/fixtures/github/contents_ruby_nested_path_directory_two.json
- composer/spec/fixtures/github/contents_ruby_nested_path_top_level.json
A customer reported that nested wildcard resolution fails in Dependabot.  Given a composer.json repository like:
```{
"repositories": [
{
"type": "path", 
"url": "components/*/*", 
"options": {"symlink": false}
}
], 
"require": {
"monolog/monolog": "1.0.*", 
"symfony/polyfill-mbstring": "1.0.*"
}
}
```
We would fail to properly handle both `*` and would attempt to retrieve `components/*` from the source repository.  When this attempt returns an error we fail the update job.
This PR adds support to traverse the path and expand the directory list at each level of the path which is represented by a wildcard.  It also adds a test for this added path traversal support.
> Add support for multi-level wildcard paths in composer

- .github/workflows/gems.yml
The `actions/setup-ruby` action [was deprecated in favor of `ruby/setup-ruby`](https://github.com/actions/setup-ruby/commit/e932e7af67fc4a8fc77bd86b744acd4e42fe3543#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R9).
So this switches to that.
Reading the docs for `ruby/setup-ruby`, all the examples include the
following params:
```
with:
ruby-version: '3.0' # Not needed with a .ruby-version file
bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```
However, the `ruby-version` looked like it needed to be specified for
`actions/setup-ruby` as well, and it wasn't, so maybe there's a default
that suffices?
And I suspect the `bundler-cache` arg is only relevant for repeated calls to ruby/bundler
within a single CI run... whereas we only …
> Migrate from `actions/setup-ruby` to `ruby/setup-ruby`

- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
The `npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js` script leverages the library code that powers `npm audit` in order to determine if a vulnerable transitive dependency can be fixed and, if it can, the updates necessary to fix it.
The audit report is essentially a map of packages affected by the vulnerable transitive dependency. Each entry in the map has an array of effects, which are the names of other packages—keys in the same map—affected by it.
Originally the script would start at the vulnerable transitive dependency and walk up the "tree of effects" until it encountered entries with no effects, signaling the earliest ancestors of the vulnerable transitive dependency that have known fixability. A problem arose when we realized that the effects tree may contain cycles, which …
> [npm] Refactor with top-down traversal

- python/helpers/build
This python helper is being run during the build of `Dependabot-core`
docker image, triggering the following warning:
```
You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/.pyenv/versions/3.10.5/bin/python3.10 -m pip install --upgrade pip' command.
```
Beyond the annoyance of the warning message, this means that `pip` is
making an unnecessary call to a remote server to check the version.
This won't be a huge savings, a blogger [benchmarked this as costing ~0.2s](https://pythonspeed.com/articles/faster-pip-installs/), but still might as well disable it.
This option can also be set globally using a config file or env var:
* https://stackoverflow.com/a/46288945
* https://stackoverflow.com/a/60270281
However, we have a …
> Disable `pip` latest version check when building `python` native helper

- python/lib/dependabot/python/update_checker.rb
`pip` has a [new resolver that's enabled by default](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html).
So let's update this comment to reduce the confusion.
I copied the text from other ecosystems where we use this exact wording:
* [`hex`](https://github.com/dependabot/dependabot-core/blob/c2adf22e99192547ee5cd597b9c572ccd3419972/hex/lib/dependabot/hex/update_checker.rb#L56)
* [`go`](https://github.com/dependabot/dependabot-core/blob/c2adf22e99192547ee5cd597b9c572ccd3419972/go_modules/lib/dependabot/go_modules/update_checker.rb#L80)
> Tweak comment now that `pip` has a resolver

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
This will make it easier to see why an update wasn't possible by viewing the job logs. Ideally we'd surface these in update error message but until then this is better than needing to reproduce the failure with the debugger.
> Log reasons why npm audit can't succeed

- bundler/helpers/v2/lib/functions.rb
- bundler/helpers/v2/monkey_patches/endpoint_specification_patch.rb
- bundler/helpers/v2/run.rb
We have had a number of customer escalations reporting timeouts and excessive requests to private gem servers.
This is a known performance regression in bundler documented here: https://github.com/rubygems/rubygems/issues/5385
Through discussions with @deivid-rodriguez he is working on an upstream fix, but in the meantime we can patch the EndpointSpecification class so that it no longer retrieves gemspec.rz files from private servers.
I've confirmed through manual tests against a private gem server and a repo that consumes said registry that this patch greatly improves performance (~10 minutes to run dry-run.rb down to 30-45s)
> Monkey patch bundler EndpointSpecification

- Dockerfile
I don't think we need the sources for anything, so we can remove them to make the image thinner.
> Cleanup Ruby sources after installing Ruby

- bin/dry-run.rb
- common/lib/dependabot/file_fetchers/base.rb
Originally introduced by @brendandburns in
https://github.com/dependabot/dependabot-core/pull/5348,
This allows our FileFetcher to accept an optional `options` hash, that
we can use for feature-flagging, like we do in the
FileUpdater/UpdateChecker etc.
This does not make use of the functionality yet, but it will enable us
to start passing the argument in our internal systems.
No tests are added or changed, because right now the behavior is not
altered, as long as the existing tests keep working, we're good!
> Optional options arg for FileFetcher

- bundler/helpers/v1/Gemfile
- bundler/helpers/v1/spec/native_spec_helper.rb
- bundler/script/ci-test
This is a fun one.
Consider the following script
```bash
#!/bin/bash
set -e
true
if [[ "$SUITE_NAME" == "bundler1" ]]; then
cd helpers/v1 \
&& false \
&& cd -
fi
if [[ "$SUITE_NAME" == "bundler2" ]]; then
cd helpers/v2 \
&& false \
&& cd -
fi
```
Believe or not, this is what you get when you run it
```
$ SUITE_NAME=bundler1 ./script/ci-test-dummy; echo $?
=> 0
$ SUITE_NAME=bundler2 ./script/ci-test-dummy; echo $?
=> 1
```
You can read more about here here:
http://mywiki.wooledge.org/BashFAQ/105, but the conclusion is that `set
-e` is brittle.
Yet I think adding `|| exit 1` to all commands is painful.
As an alternative, I added a full if-else construct that works as expected, with a note on top. I'm not fully sold on this solution, but it's simple and it also lets the script default to …
> Make failures in Bundler 1 native helper specs actually fail CI

- python/helpers/requirements.txt
As per the discussion on this [abandoned PR](https://github.com/dependabot/dependabot-core/pull/5506) this documents our intention to review python 3.6 support once Ubuntu 18.04 is EoL in April 2023.
> Adds a TODO and more detailed comment about python 3.6 support

- bin/lint
- bundler/helpers/v1/build
- bundler/helpers/v2/build
- composer/helpers/v1/build
- composer/helpers/v2/build
It was not being run for Bundler and Composer due to having a slightly different structure.
> Run shellcheck on all native helper build scripts

- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
Fixes #5405
Adding error handling and a retry if the pip-compile is not new enough to have the --resolver argument.
> The new pip resolver is not backwards compatible

- github_actions/lib/dependabot/github_actions/update_checker.rb
- github_actions/spec/dependabot/github_actions/update_checker_spec.rb
The established wisdom for versioning actions is to syn major version
tags to the most recent corresponding release/tag (eg. v2 == v2.2.3).
However, there doesn't seem to be any recommendations for versioning via
commit SHA.
This commit makes the assumption that we should look up the _version_ of
diverged commits and make the update based on the version rather than
the commit. Until now, we've been bailing when commits have diverged
(aka no longer exist as part of a branch's lineage).
> Allow diverged-commit pinned Actions to be updated

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/lockfile_with_newline/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/lockfile_with_newline/package.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/lockfile_with_newline/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/lockfile_with_newline/package.json
Recently it was reported that Dependabot had changed the indentation for
an entire package-lock.json from two spaces to one. Upon investigation,
it was determined that a newline had been added to the end of that file
(by the user), and Dependabot had considered the newline a single space.
By using `[[:blank:]]`, we get the benefits of `\s`, but with a little
less aggressiveness.
> Ignore newlines when determining indentation

- docker/lib/dependabot/docker/file_updater.rb
- docker/spec/dependabot/docker/file_updater_spec.rb
- docker/spec/fixtures/kubernetes/yaml/hyphen.yaml
The previous checked in code didn't handle:
```yaml
...
- image: foo
...
```
Add a unit test and fix the updater code.
See https://github.com/brendandburns/arc-prometheus/runs/7919856883?check_suite_focus=true for an example of the bug
> Add a fix for when the image tag is the first entry in the array.

- common/dependabot-common.gemspec
The latest version of docker_registry2 has the fix for #3989.
> Bump docker_registry2 to fix #3989

- common/lib/dependabot/pull_request_updater/azure.rb
- common/spec/dependabot/pull_request_updater/azure_spec.rb
Add a new parameter to set the author details when updating an Azure pull request.
Like in [PullRequestCreator](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/azure.rb) set the author details when creating a commit.
Otherwise azure API returns an error when [commit author email validation](https://docs.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops&tabs=browser#commit-author-email) is enabled.
> Set the author details when updating an Azure pull request.

- .github/workflows/ci.yml
Some of these still included the ci_node_total and index when they didn't need them.
> Fix CI matrices

- README.md
Dependabot was acquired back in 2019 and is now a part of GitHub.
See also: https://github.com/dependabot/dependabot-core/pull/4463
> Dependabot Ltd -> GitHub Inc

- .github/ISSUE_TEMPLATE/tech-debt.yml
- Use correct label for tech debt form
The tech debt label uses an ⚙️ emoji, which was missing from the `labels` string.
> Use correct label for tech debt form

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
This PR adds a new method, `#explain_fix_unavailable`, which adds an `explanation` key to the `fix_unavailable` object when the UpdateChecker returns an `update_not_possible` error.
This `explanation` key is also used in the ConflictingDependencies check which is printed out after a failed job run and also shows up in the Dependabot security alert view.
The UpdateChecker should always raise with an `:update_not_possible` by this point since the call from [`#latest_version_resolvable_with_full_unlock?`](https://github.com/dependabot/dependabot-core/blob/7d717862f7c441f3fafd265e516e9f5a26e1c90f/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb#L121) will not have any [`viable audit results`](https://github.com/dependabot/dependabot-core/blob/7d717862f7c441f3fafd265e516e9f5a26e1c90f/ …
> Add more helpful error messaging when a vulnerable dependency cannot be upgraded

- Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.2.8
https://releases.hashicorp.com/terraform/1.2.8/
> build(deps): bump terraform from 1.2.3 to 1.2.8

- .github/workflows/docker-branch-releases.yml
- .github/workflows/docker.yml
This should publish a tagged image for commits on main too. This way we can deploy a SHA from a main merge commit.
> publish main branch images

- .gitignore
- common/spec/spec_helper.rb
When I make changes and break stuff, I like running `rspec --only-failures` to focus on fixing what I broke. This allows RSpec to keep track of what's currently failing, so that this flag can actually be used.
What do you think?
> Configure RSpec to allow running `rspec --only-failures`

- .github/workflows/docker-branch-releases.yml
We created two ways to deploy Dependabot Updater internally: 
1. Push the Updater to GHCR
1. Export an image of the Updater and save it as an artifact for more processing later
Due to layer caching and the size of the image, saving it as an artifact takes a significant amount of time compared to just using GHCR. So we're going to remove it and just use GHCR.
> only use GHCR for deploys

- .github/workflows/smoke.yml
same as #5620 but for the smoke tests
> skip smoke test if no change was made in ecosystem

- .github/workflows/ci.yml
- .github/workflows/smoke.yml
Dependabot rebases PRs and kicks off every CI job so we're running out of Actions runners. This reduces the amount of CI jobs run by only running ones that are applicable to the change.
> skip CI if no changes effect the ecosystem

- Dockerfile
I was working on improving #5617, and while changing the `pub` native helper script, I noticed that rebuilding would rebuild native helpers for all ecosystems.
I think reordering things this way should make things a bit more efficient.
> Speedup rebuilding native helper changes

- .github/workflows/ci.yml
- .github/workflows/smoke.yml
Thanks to @jurre for pointing this out. I checked the other ecosystems and couldn't find another case of this.
> gradle depends on maven gem, so run gradle tests when maven changes

- common/lib/dependabot/git_commit_checker.rb
- common/spec/dependabot/git_commit_checker_spec.rb
- github_actions/lib/dependabot/github_actions.rb
- github_actions/lib/dependabot/github_actions/update_checker.rb
- github_actions/spec/dependabot/github_actions/update_checker_spec.rb
If the pinned commit sha is not the tip of any repo branch, we would "update" to the commit sha of the latest version, which might be actually a parent of the current sha.
The problem is that so far we were not cloning the repository, so all we can access is sha's discoverable through http `/info/refs` endpoint, or through `git ls-remotes`.
To properly update this kind of references, we need to clone the repository.
This is not ready at all, it _at least_ needs some tests, but I wanted to share it.
Fixes #5556.
```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
=> dumping fetched dependency files: ./dry-run/sigprof/nur-packages/
🌍 https//github.com:443/cachix/install-nix-action.git/info/refs
=> updating 1 …
```
> Properly upgrade github actions pinned to specific commits

- python/lib/dependabot/python/native_helpers.rb
While working on python native helpers, I was running `python/helpers/build` after making changes to install native helpers to the proper location. However, my changes were not being picked up.
Turns out Dependabot was using `/opt/python/helpers`, the path were helpers are originally copied:
https://github.com/dependabot/dependabot-core/blob/70805187fb63ff1f012446bd32a3d22a6220cc43/Dockerfile#L271
Not the path were helpers are originally installed:
https://github.com/dependabot/dependabot-core/blob/70805187fb63ff1f012446bd32a3d22a6220cc43/python/helpers/build#L10
Initially I just fixed the path but thinking about it more, this file tree duplication seems unnecessary and confusing, specifically for interpreted language (where installed files are exactly the same as copied files).
Should we …
> Fix path to python native helpers

- .devcontainer/core-dev/devcontainer.json
Now that updater is in core, there's no way to use Codespaces to run the updater tests since the devcontainer.json we specified drops us in docker-dev-shell where updater doesn't exist. 
So I've moved devcontainer.json to a subdirectory which gives us the ability to choose between the devcontainer.json we specified and the default one Codespaces uses:
Bonus: I noticed there was no cacheFrom specified, so I've added one and it seems to be using it when building. This should save some time!
> move devcontainer to allow debugging updater with the default devcontainer

- .vscode/launch.json
- common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
- common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
Attempting to improve our link sanitation to prevent `<org>/<repo>#<pr number>` text strings from being hydrated into full github.com links by PR creation machinery.
I found that a number of our tests produce redirect links, however the link text itself is in the format above, and adding those links to a PR comment or description results in a valid github.com link and creates a mention on the targeted PR timeline.
This should also break up any text string in the above format to prevent flood of mentions experienced in the below issue:
Closes https://github.com/dependabot/dependabot-core/issues/5639
I also added common tests to the test debug dropdown in vscode and fixed a path issue with the vscode debugger.
~~This is still a WIP as there is 1 failing test which I need to fix, and the …
> Adding code tags around any nwo#number text string

- .github/workflows/docker-branch-releases.yml
A downside to #5640 was commits pushed after approval aren't deployed.
So to fix that, I've restored the pull_request trigger, but use `gh` to get the review state. Thus if a commit comes in after approval it will still be able to see if was approved. Commits before an approval should be skipped.
> deploy commits made after approval

- .github/workflows/docker.yml
I noticed that [in GHCR](https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-core/versions) we're tagging the latest tagged version 0.212.0 repeatedly,  I think this is because this if statement is a string:
```workflow
if: "contains(github.ref, 'refs/tags')"
```
I also changed the updater push to not push latest since that's being done in `docker-branch-releases.yml` now. I moved the if statement up on that job so it only runs to tag if the version changes.
> fix tagged push overwriting previous tags

- updater/spec/dependabot/integration_spec.rb
- updater/spec/fixtures/bundler_git/original/Gemfile.lock
- updater/spec/fixtures/bundler_git/updated/Gemfile.lock
I had not been able to get all updater specs passing on my laptop. I was getting two spec failures, which I describe in each commit message, together with how I got them passing.
> Fix updater specs on M1

- python/spec/spec_helper.rb
This flag prints the slowest 10 specs and their run times after each rspec run.
Because our Python test suite is so slow, It just occurred to me that maybe using it by default in Python would raise awareness on the areas that need more love with regards to test speed.
> Run `rspec` with `--profile` flag by default in Python

- python/lib/dependabot/python/requirement.rb
- python/spec/dependabot/python/requirement_spec.rb
In 45f5b77a776cf8bada4c262af9e39ff492ab6ba9, we started handling odd python requirements, with multiple constraints not separated by colons.
Native behavior is to ignore anything after the first requirement, yet we were only ignoring the first one.
> Fix incomplete clean up of odd python requirements

- common/lib/dependabot/git_commit_checker.rb
While working on a spec failure, I observed the failing spec was also soooooo slow:
```
Top 1 slowest examples (48.37 seconds, 100.0% of total time):
Dependabot::EndToEndJob bundler git dependencies updates dependencies correctly
48.37 seconds ./spec/dependabot/integration_spec.rb:296
```
Further investigation revealed that this spec was trying to do the following up to 76 times, on a non-existing github repository:
* Try fetch `https://github.com/dependabot/dummy-git-dependency.git/info/refs?service=git-upload-pack`.
* Since the previous fetch failed, try run `git ls-remote https://github.com/dependabot/dummy-git-dependency.git` locally.
This is done every time the update checker needs to fetch remote git tags, and if this fails, the checker considers that there are no remote tags, but …
> Speed up dealing with non-reachable git repos

- .github/workflows/smoke.yml
Our smoke tests were broken for forks since PATs aren't available there. So I've moved the tests, caches, and CLI binary to public places so we can use GITHUB_TOKEN which is available as a read-only source.
> fix smoke tests from forks by using public sources

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
Adds additional logging to `VulnerabilityAuditor#audit` to support metrics tracking.
> [npm] Add additional logging to VulnerabilityAuditor

- updater/spec/dependabot/file_fetcher_job_spec.rb
- updater/spec/dependabot/integration_spec.rb
Up to now, running updater specs prints a lot of server logs with a lot of "E" letters that can be confused with spec failures, and it's hard to process.
This commit adds some bare assertions on the output instead of printing it, so that it's clean.
As a side effect, it also avoids using `expect { foo }.not_to raise_error`. This is not considered a great testing practice because an empty implementation of `foo` passes it, so it's not testing much 😅.
Sample output here (not everything because it's so verbose that exceeds maximum PR size 😆)
```
Randomized with seed 17332
..............................E, [2022-09-08T18:56:26.044927 #1] ERROR -- : <job_123123> Error during file fetching; aborting
...E, [2022-09-08T18:56:27.451602 #1] ERROR -- : <job_123123> Error during file fetching; …
```
> Cleanup updater specs output

- Dockerfile
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
By installing yarn via corepack we can take advantage of built in version detection based on the `packageManager` key in package.json.
This also enables a repo with a `.yarnrc.yml` file which specifies a `yarnPath` key pointing to a checked in version of yarn to work.  This assumes we get the `.yarnrc.yml` and corresponding `.yarn/releases/<yarn-release>.cjs` files into the tmp directory.  This capability is another argument in favor of clone the repo for yarn berry.
> Install yarn via corepack

- npm_and_yarn/lib/dependabot/npm_and_yarn.rb
In order for us to update yarn berry's cache, we need that folder to be available. The easiest way to do that is to just check out the full repo. No other changes are required, the file fetcher should use functionality available in the base class in order to grab files from the repo on disk instead of making API calls.
If we were to roll this out, we should put it behind a feature flag and roll it out incrementally though, but for the purpose of a PoC for yarn berry, this should suffice, and I was able to perform a dry-run update that updates the cache correctly with this change:
```
=== @braintree/sanitize-url (5.0.2)
🌍 https//registry.npmjs.org:443/@braintree%2Fsanitize-url
🌍 https//registry.npmjs.org:443/@braintree%2Fsanitize-url/6.0.0
=> latest available …
```
> Clone full repo so yarn cache is available

- updater/lib/dependabot/api_client.rb
- updater/spec/dependabot/api_client_spec.rb
This is required to support removed transitive dependencies.
> Include removed dependency flag when creating a pull request

- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_by_parent/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_by_parent/package.json
- npm_and_yarn/spec/fixtures/vcr_cassettes/Dependabot_NpmAndYarn_UpdateChecker/_conflicting_dependencies/with_a_locking_parent_dependency_and_an_unsatisfiable_vulnerablity/delegates_to_the_ConflictingDependencyResolver_and_VulnerabilityAuditor_and_explains_the_conflict.yml
This PR adds a new test to `UpdateChecker#conflicting_dependencies` which uses locking parent fixture so the vulnerable transtitive dependency can't be upgraded.
I created and published [npm-parent-dependency-5](https://github.com/dependabot-fixtures/npm-parent-dependency-5) which has only 1 version `v1.0.0` and requires exactly `npm-intermediate-dependency@0.0.1`. In turn, this version of `npm-intermediate-dependency` requires exactly `npm-transitive-dependency@v1.0.0`, locking it from upgrading to the non vulnerable `v1.0.1`.
This test is subltly different from the "with a conflicting dependency and an unsatisfiable vulnerablity" test that already exists because it uses a valid vulnerable version range for `npm-transitive-dependency` of `< 1.0.0` which could be satisfied by upgrading to …
> Test #conficting_dependencies with a locking parent dependabot fixture

- Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.2.9
https://releases.hashicorp.com/terraform/1.2.9/
> build(deps): bump terraform from 1.2.8 to 1.2.9

- python/lib/dependabot/python/file_fetcher.rb
Hi there,
This PR is a result from a discussion in https://github.com/dependabot/dependabot-core/pull/5580 where @jeffwidman asked to split up the original PR into two.
The purpose of this PR is to increase the file size of `requirements.txt` files to 500 kilobytes.
Especially in large projects, `pip-tools`-compiled `requirement.txt` files can get pretty big.
As @dws mentioned [here](https://github.com/dependabot/dependabot-core/pull/5580#issuecomment-1226148657) the ideal solution would be to have the file size as a configurable parameter.
If this change requires any unit tests please point me to existing examples.
Thanks!
> Update file size to 500 kilobytes

- python/helpers/build
The `pipfile` package doesn't have published wheels, so pip has to build it from source. By default, it tries to do that in the current environment, but it lacks the `wheel` package, so pip falls back to the legacy `setup.py install` method, which generates a build warning. The `--use-pep517` option lets pip do the build in an isolated environment, automatically downloading the necessary dependencies.
Fixes #5478.
> python/helpers/build: fix a pip warning related to pipfile installation

- .github/workflows/docker-fork-releases.yml
Since fork PRs can only get read access from GITHUB_TOKEN, we can't use the `docker-branch-releases.yml` workflow to deploy a fork to GHCR before merging it.
This works around that with a manually dispatched workflow that pulls in the PR code, builds, and deploys it. Since it was kicked off by the team it _should_ have the correct permissions.
> **Note**
> While implementing this, I tried to simply `git merge main` after the `gh pr checkout` but git errors with `fatal: refusing  to merge unrelated histories`. So I assume the `gh` command is pulling in the PR as a different tree. To work around that, I squashed the changes and cherry picked them over to main. If anyone has a better or easier solution to that let me know!
> deploy from a fork using a workflow

- docker/lib/dependabot/docker/update_checker.rb
DockerRegistry2 has a default read timeout of 5s.  We have seen issues where loading the list of docker tags times out if that list is very large.  This increases the timeout to 10s which in my testing locally is sufficient to load hexpm/elixir with > 150k tags.
> Increase docker registry client timeout

- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
fixes #5655
Poetry recently released 1.2.0 which uses [dulwich](https://github.com/jelmer/dulwich), a pure Python implementation of Git. Like other ecosystems, we actually want to use the system Git with Dependabot so the Git shim will rewrite URLs to be HTTPS. 
But also, in #5655 we are probably seeing a bug in dulwich that doesn't honor proxy authentication settings in the `http_proxy` environment variables. I tested this change locally and it fixed my reproduction repo.
> fix Poetry not using system git

- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/updater_spec.rb
This should be the last step before enabling removed dependencies. An update is provided a list of existing open PRs that are matched against when attempting an update. If we determine there's already a PR for our target state we'll exit early with an error. The existing PR data is getting updated to indicate removed dependencies via the `dependency-removed` flag and this change is to accommodate that new field and properly match against it.
> Handle removed dependencies in existing PRs

- .github/dependabot.yml
Now that we've merged `updater` into `core`, 
we should also have Dependabot watch its `Gemfile`.
> Watch the new `updater/Gemfile`

- .github/workflows/docker-branch-releases.yml
Reverts dependabot/dependabot-core#5709
This didn't work, it also breaks deploys for everyone else.
> Revert "disable branch release workflow for forks"

- composer/helpers/v1/.php-cs-fixer.dist.php
Fix the following warnings:
```
15.95 > php-cs-fixer fix --diff --verbose '--dry-run'
16.10 You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
16.10 You may find an UPGRADE guide at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.3.0/UPGRADE-v3.md .
16.10 If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
16.10
16.10 PHP CS Fixer 2.19.3 Testament by Fabien Potencier and Dariusz Ruminski
16.10 Runtime: PHP 7.4.30
16.10 Loaded config default from "/opt/composer/v1/.php_cs".
16.14 ......
16.26 Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
16.26
16.26 Checked all files in 0.134 seconds, 14.000 MB memory used
16.26
16.26 Detected …
```
> Fix `PHP-CS-Fixer` deprecation warnings

- composer/helpers/v1/composer.json
- composer/helpers/v1/composer.lock
The previous pin technically allowed any version of composer >= 1.10.9, < 2.0... but because it included the full version pin, it was easy to overlook the `^` and think it was pulling in that older version of composer.
Over in the `v2/composer.json` file, we only pin to `"^2", so I made this pin less explicit for both improved consistency and less confusion.
There is no functional change to `composer.lock`, so this shouldn't have any impact beyond clearer documentation.
> Relax the composer pin to make it less confusing

- python/lib/dependabot/python/file_fetcher.rb
- python/spec/dependabot/python/file_fetcher_spec.rb
- python/spec/fixtures/github/contents_python_only_requirements_in.json
- python/spec/fixtures/github/requirements_in_content.json
Hi there,
There seems to be a bug in the [file_fetcher.rb](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/file_fetcher.rb) class when trying to fetch `requirements.in` files:
If there's also a `requirements.txt` file in the repository, the download works.
If not, Dependabot doesn't continue to look for `requirements.in` files and raises a `DependencyFileNotFound` exception [here](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/file_fetcher.rb#L87).
When I add `requirements_in_files.any?` to the list of checks the download works just fine. Maybe, there's a better fix for this, didn't investigate the issue any further.
Thanks.
> Fix fetching bug for requirements.in files

- common/lib/dependabot/pull_request_creator.rb
- common/lib/dependabot/pull_request_creator/branch_namer.rb
- common/spec/dependabot/pull_request_creator/branch_namer_spec.rb
This PR adds a max length option to the BranchNamer and addresses https://github.com/dependabot/dependabot-core/issues/3107. Also relevant for the "... and may contain a maximum of 128 characters" part of https://github.com/dependabot/dependabot-core/issues/396.
This is a backwards compatible change and requires no configuration: when no option is passed, no truncating is performed on the branch name.
As this is my first contribution here, let me know if I missed some conventions, or if there are additional changes expected!
> Add max length option to BranchNamer

- composer/helpers/v1/composer.json
- composer/helpers/v1/composer.lock
- composer/helpers/v2/composer.json
- composer/helpers/v2/composer.lock
Addresses the following warnings:
```
16.51 > phpstan analyse
16.82 Note: Using configuration file /opt/composer/v1/phpstan.neon.
18.22  0/6 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% 6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
18.31
18.31
18.31  [OK] No errors
18.31
18.73 ./composer.json is valid for simple usage with Composer but has
18.73 strict errors that make it unable to be published as a package
18.73 See https://getcomposer.org/doc/04-schema.md for details on the schema
18.73 # General warnings
18.73 - No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
18.73 # Publish warnings
18.73 - name : The property name is required
18.73 - description : The property description is required
```
As noted, these are not strictly needed given …
> Add composer fields to silence PHPStan

- bin/dry-run.rb
On the one hand, it was missing ":" after the colon. On the other hand, including the port makes the url not browsable, which I think it's the point of logging this.
Please trust me and don't even try to visit `https//pypi.org`, which is how I got here 🤣.
> Fix URIs logged by dry-run

- npm_and_yarn/helpers/.eslintrc
Previously we were at 9, which is from back in 2018...
You can see the map of node versions to Ecma versions here: https://node.green/ Currently we're shipping `node` `16`, which has solid support through ES2021.
We could just bump the pin to a version, but then we have to remember to manually keep bumping it (Dependabot doesn't _yet_ support bumping this option).
Instead, by switching to [`"latest"`](https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-parser-options) we don't have to continue to maintain the pin.
Admittedly, this is a little YOLO'ish, since it will default to Ecma 2023 soon, but OTOH we will probably bump to Node 18 at the end of next month [when it goes to `Active` status[(https://nodejs.org/en/about/releases/). And Node 18 currently has …
> Use `"latest"` for ESLint `ecmaVersion`

- script/dependabot
Not sure if this makes sense to you, but today I wanted to use a full CLI run, with my development copy of dependabot-core code, but without a debugging shell. And the current `script/debug` script doesn't let you do that.
I thought about removing the hardcoded `--debug` flag, and if you want a debugger console, you can pass the `--debug` flag explicitly. Of course, that's more typing, so alternatively we could, for example:
* Use `dep` for the script name.
* Keep `script/debug` and do what I'm doing here in a separate script.
Does this make sense?
> Make `script/debug` a simple wrapper over the CLI

- .github/workflows/docker-branch-releases.yml
This will add a date based version tag to the docker image published on main. 
This fixes some downstream projects relying on a comparable version tag.
> add a date tag to the docker image when merged

- common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
- common/spec/dependabot/pull_request_creator/message_builder_spec.rb
I have encountered an issue that quite often handles in gitlab will be the same as on github. This creates an issue where PR descriptions in various projects can send notifications to people mentioned in release notes.
I'm not entirely sure if same issue could exist on bitbucket as well and maybe this check should be removed all together. For now it seemed safer to explicitly just add gitlab to conditional.
> Sanitize mentions for merge requests in Gitlab

- python/lib/dependabot/python/update_checker/requirements_updater.rb
- python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
I still want to add some specs, but this is just a quick patch to get this started.
Fixes #3212.
Fixes #4435.
Fixes #5537.
> Support `increase-if-necessary` versioning strategy in python

- docker/lib/dependabot/docker/update_checker.rb
- docker/lib/dependabot/docker/version.rb
- docker/spec/dependabot/docker/update_checker_spec.rb
- docker/spec/fixtures/docker/registry_tags/eclipse-temurin.json
As per
https://www.oracle.com/java/technologies/javase/versioning-naming.html, an underscore is used for "update release" segments.
This PR fixes #5728 and supersedes #4801.
I added attribution to @RodrigoPetter since I used his tests!
Diffferences from his PR are the implementation, which is simpler here, and the scope which limits only to segments followed by numbers, but does not deal with other cases since I have not seen those in real life.
Thanks so much Rodrigo!!
> Allow updating Java images with "update releases"

- python/lib/dependabot/python/requirement.rb
- python/spec/dependabot/python/requirement_spec.rb
Standard Python does not support this, but Poetry does, so when they appear on Poetry dependency files, they make dependabot crash.
Fixes https://github.com/dependabot/dependabot-core/issues/5363.
> Fix multiple Python requirements separated by whitespace

- .github/workflows/ci.yml
- .github/workflows/smoke.yml
We noticed the CI and Smoke tests weren't running on stacked PRs so this should fix that. Tested in https://github.com/dependabot/dependabot-core/pull/5753.
> fix #5751 run CI and smoke tests on stacked PRs

- pub/helpers/bin/infer_sdk_versions.dart
- pub/lib/dependabot/pub/helpers.rb
Fix of https://github.com/dependabot/dependabot-core/issues/5396
> [pub] Log the Dart / Flutter SDK version selected

- bin/dry-run.rb
- common/lib/dependabot/experiments.rb
- common/spec/dependabot/experiments_spec.rb
- common/spec/spec_helper.rb
- docker/lib/dependabot/docker/file_fetcher.rb
- docker/spec/dependabot/docker/file_fetcher_spec.rb
- updater/lib/dependabot/updater.rb
Currently experiments are required to be passed in as an optional
`options` flag to the individual classes like the FileFetcher and
FileUpdater. This is fine, but it becomes a bit cumbersome when more
deeply nested objects need to access this flag, as we need to pass it
down to all of them.
This introduces a global `Dependabot::Experiments` interface that we can
use to register experiments and access them where needed.
The idea is that these are set in the Updater before running an update,
and will be available for the duration of the job.
Right now most of the existing experiments are left as is, using the `options` flags,
but I've ported the `kubernetes_enabled` feature flag for the Docker ecosystem to
demonstrate how this would work.
There is more functionality we could add to this …
> Add new interface to register experiments

- bin/dry-run.rb
- updater/lib/dependabot/updater.rb
With a dependency chain of A -> B -> C a vulnerability on C could require an update to B but not A so the resulting update would be for B & C. This fixes a few issues in that scenario.
- When C is removed an error occurs when attempting to update B. This was because I missed applying this [filter](https://github.com/dependabot/dependabot-core/blob/e11608fd17da3275cefca5e22eb01d01eb62fe09/bin/dry-run.rb#L740-L742) from the dry-run script to the updater after the merge.
- When we create the PR for B & C then B was being filtered out resulting in a single dependency PR instead of a multi dependency PR. When C is removed this was causing an error because we don't support removal in single dependency PRs.
These aren't things that are easily tested in the updater spec but I'm planning on adding …
> Fixes for transitive dependency vulnerabilities without a top level dependency update

- common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
As pointed out in https://github.com/dependabot/dependabot-core/issues/5729, we should be using the "source" of the metadata for deciding how to sanitize, not the "place where Dependabot is hosted".
This hack was annoying the folks who use GitLab to the point that [they monkey-patched this code to also run the sanitizer on GitLab](https://github.com/dependabot/dependabot-core/pull/3437#issuecomment-816582168), and then contributed that back in #3437.
If it's true on GitLab, it's even more true on other platforms as well for the reasons explained in https://github.com/dependabot/dependabot-core/pull/3437#issuecomment-1247597678.
So remove this guard altogether.
> Sanitize metadata links on all platforms

- .github/workflows/docker-branch-releases.yml
Another attempt to prevent forks from trying to deploy, which will fail. Previous attempt reverted in #5711.
I found a fork boolean in the payload so this seems to be the way to go. If the run is found to be a fork, it sets DECISION to FORK which is not APPROVED and so it skips the rest of the steps. 
Dependabot PRs are not considered forks.
> prevent forks from trying and failing to deploy to GHCR

- npm_and_yarn/lib/dependabot/npm_and_yarn.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/sub_dependency_files_filterer.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/yarn_lockfile_parser_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/sub_dependency_files_filterer_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
- updater/lib/dependabot/updater.rb
In order to merge these changes into main without disrupting existing behavior, gate the changes behind a feature flag, so we can gradually roll them out and iron out issues without building up a huge set of changes.
I've opted to explicitly _enable_ the feature in our tests, so they run against the new situation, we can add a few tests that ensure the new behavior doesn't run _without_ the flag present, but I'm a little concerned about how invasive this feature-flag change is to be honest, needing to pass the feature flag around etc. and would like to possibly rethink the approach first.
This also still includes the changes to always clone the full repo, which we should flag in updater/api instead.
> Gate yarn berry changes behind feature-flag

- common/lib/dependabot/pull_request_creator/message_builder.rb
- common/spec/dependabot/pull_request_creator/message_builder_spec.rb
This builds on the message improvements in https://github.com/dependabot/dependabot-core/pull/5595 to also support cases where a dependency is removed.
Bumps [xmldom](https://github.com/xmldom/xmldom) and [read-excel-file](https://gitlab.com/catamphetamine/read-excel-file). These dependencies needed to be updated together.
Removes `xmldom`
Updates `read-excel-file` from 4.1.0 to 5.4.7
Removes [xmldom](https://github.com/xmldom/xmldom). It's no longer used after updating ancestor dependency [read-excel-file](https://gitlab.com/catamphetamine/read-excel-file). These dependencies need to be updated together.
Removes `xmldom`
Updates `read-excel-file` from 4.1.0 to 5.4.7
> Improve PR message for removed dependencies

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/sub_dependency_files_filterer.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
This config option ensures that we don't run postinstall scripts that ship with npm packages.
This is something we already do for all ecosystems including npm and yarn classic.
> Run yarn commands without running scripts

- bundler/lib/dependabot/bundler/file_parser.rb
- bundler/lib/dependabot/bundler/file_parser/gemfile_declaration_finder.rb
- bundler/spec/dependabot/bundler/file_parser/gemfile_declaration_finder_spec.rb
After profiling `FileParser#parse` for bundler, I found that the ruby
Parser was extremely hot. The same Gemfile was being parsed twice for
each dependency, when it only needed to be parsed a single time per
file.
The performance improvement depends on the size of the Gemfile being
parsed, but the following example shows the speedup for the
[discourse/discourse](https://github.com/discourse/discourse) repo.
Before:
```
Warming up --------------------------------------
parse     1.000  i/100ms
Calculating -------------------------------------
parse      0.121  (± 0.0%) i/s -   1.000  in   8.262804s
```
After:
```
Warming up --------------------------------------
parse     1.000  i/100ms
Calculating -------------------------------------
parse      6.319  (±15.8%) i/s -  32.000  in …
```
> bundler: optimize gemfile parsing

- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/locked_transitive_dependency_plus_fixed/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/locked_transitive_dependency_plus_fixed/package.json
Without this check we can surface already fixed versions of the dependency as needing to be updated which confuses Dependabot.
> [npm] Only return a chain if a node matches a vulnerable version

- .github/workflows/codeql-analysis.yml
We run CI via actions on `main` on a daily cron to catch any unexpected regressions, or if CodeQL adds a new check that suddenly flags something.
However, this can result in some unexpected notification noise:
1. I merged a PR from an external contributor: https://github.com/dependabot/dependabot-core/pull/5580
2. That PR was opened from the fork's `main` branch
3. Before merging, I clicked the "Update by rebase". So a commit from me landed on the fork's `main` branch.
4. I'm now receiving daily emails about failing CI runs from the fork. These are pure noise, since I don't care about the state of an external contributor's forked repo.
This hasn't happened for any other PR's that I've merged from external contributors, so I suspect it's related to the rebase so I'm now seen as a committer …
> Skip cron run of CodeQL in forks

- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
There can be other deps marked as vulnerable that aren't the advisory dep (locking parents) and we can't be sure that a non-vulnerable version of those deps doesn't still have a vulnerable version of the advisory dep as a child.
For ex for an advisory on C:
```
A -> B (vuln) -> C (vuln)
| -> D -> B(not vuln) -> C (vuln)
```
I haven't found real examples of this occurring yet but this is worth fixing since it could lead to PRs that don't fully fix an alert.
> [npm] Only shortcut search when non-vuln version of advisory dep is found

- .github/workflows/codeql-analysis.yml
Moves the if condition to the job.
> Fix syntax error in Actions workflow file

- bin/dry-run.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_but_updateable/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_but_updateable/package.json
- npm_and_yarn/spec/fixtures/vcr_cassettes/Dependabot_NpmAndYarn_UpdateChecker/_can_update_/given_an_up-to-date_dependency/when_a_transitive_dependency_is_able_to_update_without_unlocking_its_parent_but_is_still_vulnerable/allows_full_unlocking.yml
- npm_and_yarn/spec/fixtures/vcr_cassettes/Dependabot_NpmAndYarn_UpdateChecker/_can_update_/given_an_up-to-date_dependency/when_a_transitive_dependency_is_able_to_update_without_unlocking_its_parent_but_is_still_vulnerable/can_t_update_without_unlocking.yml
This fixes an issue that prevents Dependabot from trying to update a parent dependency when updating a vulnerable transitive dependency.
Ex: A vulnerability is reported in dependency B for all versions `< 2.0.0`
We start with:
```
A (1.0.0, allows B ^1.0.0) -> B (1.0.0, vuln)
```
To successfully fix this vulnerability we need to update A:
```
A (1.0.1, allows B ^2.0.0) -> B (2.0.0, fixed)
```
However, if Dependabot found there was a version B was allowed to update to it would propose that instead:
```
A (1.0.0, allows B ^1.0.0) -> B (1.0.1, still vuln)
```
The end result would be the job fails as not possible because it fails the vuln fix check at https://github.com/dependabot/dependabot-core/blob/8ab4d78efe7cf9a75bef76dd883d7ee3fffffb40/updater/lib/dependabot/updater.rb#L274-L282
This …
> [npm] fix failure to attempt parent update if unfixed transitive update is available

- Dockerfile.updater
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
In order for yarn berry to pick up our custom CA file path, we can set an environment variable instead of a custom config file.
See https://yarnpkg.com/configuration/yarnrc#caFilePath:
> Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: YARN_CACHE_FOLDER will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).
> Set custom CA file path for yarn berry

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/on-create.sh
- .devcontainer/post-create.sh
This allows us to quickly launch a Codespace and execute `script/dependabot` without having to figure out how to download the CLI.
> add dependabot CLI dev container

- updater/lib/dependabot/job.rb
- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/job_spec.rb
Previously we set the `always_clone` flag in the updater, but in prod we run file fetching as a separate step, and as a result the flag was not set at that point.
This change sets all the experiments on Dependabot::Experiment whenever we initialize a job. That way we can ensure that all the experiments are globally available during all steps.
> Ensure always_clone is enabled for yarn_berry during file_fetching

- common/lib/dependabot/file_updaters/base.rb
- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/private_modules_with_different_versions/main.tf
Hello,
I noticed that dependabot running for one our repositories had issues with updating one dependency.
```
updater | ERROR <job_468187453> No files changed!
updater | ERROR <job_468187453> /home/dependabot/terraform/lib/dependabot/terraform/file_updater.rb:44:in `updated_dependency_files'
updater | ERROR <job_468187453> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:746:in `generate_dependency_files_for'
updater | ERROR <job_468187453> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:311:in `check_and_create_pull_request'
updater | ERROR <job_468187453> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_468187453> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80: …
```
> Update all versions of the same private module in single terraform file

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/locked_transitive_dependency_outdated/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/locked_transitive_dependency_outdated/package.json
I've seen this occurring when the `package-lock.json` is not in sync with the `package.json`. In these cases the result contains `fix_available: true` but the `fix_updates` property is empty or contains dependencies with missing target versions.
> [npm] Reject audits which don't have a fix we can apply

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
Yarn Berry commands related to performing updates can run in a mode called `update-lockfile`, which was purpose-built for exactly what Dependabot does:
```
- `update-lockfile` will skip the link step altogether, and only fetch packages
that are missing from the lockfile (or that have no associated checksums).
This mode is typically used by tools like Renovate or Dependabot to keep a
lockfile up-to-date without incurring the full install cost.
```
This makes yarn berry updates _significantly_ more performant, but it has the downside that when the yarn cache is committed to the repo, old entries in there are not cleaned up. Everything still works as expected when this happens, but over time it could lead to that cache folder getting larger than is necessary.
I've opened an issue about this …
> Yarn Berry: Run commands in `update-lockfile` mode

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm6/transitive_dependency_locked_by_intermediate_top_and_sub/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm6/transitive_dependency_locked_by_intermediate_top_and_sub/package.json
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_by_intermediate_top_and_sub/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_locked_by_intermediate_top_and_sub/package.json
- npm_and_yarn/spec/fixtures/updated_projects/npm6/transitive_dependency_locked_by_intermediate_top_and_sub/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm6/transitive_dependency_locked_by_intermediate_top_and_sub/package.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/transitive_dependency_locked_by_intermediate_top_and_sub/package-lock.json
- npm_and_yarn/spec/fixtures/updated_projects/npm8/transitive_dependency_locked_by_intermediate_top_and_sub/package.json
Previously we wouldn't update sub dependencies if a top level dependency was also in the update list. With our new ability to update locking parents of a vulnerable transitive dependency it's now possible for an update to require updating both. This is resulting in incomplete PRs that include fixes for top level dependencies (and their child dependencies) but not fixes for separate sub dependencies that need updates.
> [npm] Allow updates with both top level and sub dependencies

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
We had been setting the source of transitive parent dependencies to nil but this caused the FileUpdater to think the requirement was always changing. This might not be the case for a library with a requirement range that already allows the fixed version. We should prefer to preserve the existing source when an updated source is not provided.
Example:
```
#<Dependabot::Dependency:0x0000558c3bf7fc48
@name="serverless-offline",
@package_manager="npm_and_yarn",
@previous_requirements=
[{:requirement=>"8",
:file=>"package.json",
:groups=>["devDependencies"],
:source=>{:type=>"registry", :url=>"https://registry.npmjs.org"}}],
@previous_version="8.8.0",
@removed=false,
@requirements=[{:requirement=>"8", :file=>"package.json", :groups=>["devDependencies"], :source=>nil}],
@version="8.8.1">
``` …
> [npm] Preserve requirement source when updating transtive dep parents

- Dockerfile
- python/helpers/build
- python/lib/dependabot/python/python_versions.rb
- python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
Bump pyenv from v2.3.2 to v2.3.4. Python 3.10.7, 3.9.14, 3.8.14, and 3.7.14 have all been released, but are not yet supported by a released version of pyenv.
> Add support for Python 3.10.6

- bin/lint
- bundler/helpers/v1/build
- bundler/helpers/v2/build
- bundler/script/ci-test
When upgrading RubyGems to 3.3+, RubyGems gets confused about which Bundler version to use when shelling out to native helpers.
There's two different instances of Bundler during a dependabot run/update. There's the version that runs Dependabot itself and that activates the different `dependabot-*` gems, and there's the version of Bundler that runs native helpers.
The version of Bundler that runs dependabot itself can be anything really. It defaults to the highest version globally installed, but may be restricted by manifest files (`Gemfile` and `Gemfile.lock`) present when Dependabot is run.
The version of Bundler that runs native helpers is more tricky, because it needs to respect (up to a certain point) the version of Bundler the manifest files being updated work best with.
With …
> Decouple Bundler versions

- composer/helpers/v1/composer.lock
Used `composer1 update` to update the `v1/composer.lock` file:
```
[dependabot-core-dev] ~/dependabot-core/composer/helpers/v1 $ composer1 update
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Nothing to install or update
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
28 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
I …
> Update `v1/composer.lock` using `composer1 update`

- docker/lib/dependabot/docker/file_fetcher.rb
- docker/lib/dependabot/docker/file_parser.rb
- docker/lib/dependabot/docker/file_updater.rb
- docker/spec/dependabot/docker/file_fetcher_spec.rb
- docker/spec/dependabot/docker/file_parser_spec.rb
- docker/spec/dependabot/docker/file_updater_spec.rb
- docker/spec/fixtures/github/contents_helm_repo.json
- docker/spec/fixtures/github/contents_other_yaml.json
- docker/spec/fixtures/github/contents_values_yaml.json
- docker/spec/fixtures/helm/yaml/empty.yaml
- docker/spec/fixtures/helm/yaml/multi-image.yaml
- docker/spec/fixtures/helm/yaml/no-registry.yaml
- docker/spec/fixtures/helm/yaml/values.yaml
This PR extends the recent Kubernetes support for Docker containers to common Helm chart formats:
```yaml
foo:
image:
repository: sql/sql
tag: 1.2.3
registry: docker.io
```
or alternatively:
```yaml
foo:
image:
repository: sql/sql
version: 1.2.3
```
> Add support for helm files.

- common/lib/dependabot/dependency.rb
- common/spec/dependabot/dependency_spec.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- updater/lib/dependabot/job.rb
- updater/spec/dependabot/job_spec.rb
In testing https://github.com/dependabot/dependabot-core/pull/5801 via the updater we found there's an additional spot we need to consider all versions of a dependency when doing a vulnerability check. This is to prevent Dependabot from returning a confusing error message that all versions have been ignored.
This code path is invoked from the updater at https://github.com/dependabot/dependabot-core/blob/97ae98c8f7fbb308ff317be20f644d700f612258/updater/lib/dependabot/updater.rb#L231
Part of the allowed update check is to see if the dependency is actually still vulnerable:
https://github.com/dependabot/dependabot-core/blob/97ae98c8f7fbb308ff317be20f644d700f612258/updater/lib/dependabot/job.rb#L77-L78
I considered removing this check as it's a duplicate of this check in the create pr flow: …
> Consider all dependency versions in Job.vulnerable?

- python/helpers/build
This was added in https://github.com/dependabot/dependabot-core/pull/3459/ to workaround the underlying issue of https://github.com/python-poetry/poetry/issues/3010.
However, `poetry` `1.2` fixed the underlying issue, and we are now on `poetry` `1.2.1` so we can remove this workaround.
See also:
* https://github.com/python-poetry/poetry/issues/3010#issuecomment-1207683271
* https://github.com/python-poetry/poetry/issues/3010#issuecomment-1076518050
* https://github.com/python-poetry/poetry/issues/3010#issuecomment-1122209272
* https://github.com/dependabot/dependabot-core/pull/5492
> Stop disabling new `poetry` installer

- maven/lib/dependabot/maven/file_updater.rb
- maven/spec/dependabot/maven/file_updater_spec.rb
- maven/spec/fixtures/poms/plugin_with_double_backslashes.xml
Dependabot removes backslashes in maven pom.
This PR will fix it.
Example PR: https://github.com/mallowlabs/dependabot-maven-double-backslashes-test/pull/1
`String#gsub` escapes double backslashes.
Using block prevents this problem.
```
irb(main):001:0> "\\\\".gsub("\\\\","\\\\")
=> "\\"
irb(main):001:0> "\\\\".gsub("\\\\") { "\\\\" }
=> "\\\\"
```
I use spotless-maven-plugin.
The `importOrder` configuration contains `\\#`.
https://github.com/diffplug/spotless/blob/7667a849d377b546d45350b77b65e0793e3d17dc/plugin-maven/README.md?plain=1#L184
> Fix Dependabot removes double backslashes in maven plugin configurations

- common/lib/dependabot/file_fetchers/base.rb
We can use [Dependabot CLI](https://github.com/dependabot/cli) to test specific commits of a repository with an input file like this:
```
job:
package-manager: go_modules
allowed-updates:
- dependency-type: direct
source:
provider: github
repo: dependabot/smoke-tests
directory: "/."
commit: 147f31acdcaf088f1ecfefeb8ef33f603a944420
```
This is useful in smoke testing so there's no fear of breaking all of the tests when making a new commit to the repo, the tests are essentially pinned. This is also useful for testing customer issues since the customer may have made new commits that changed the situation since the job ran.
Ecosystems that use the clone method to fetch code are not honoring the commit since they only call clone with a branch, or use the default branch. That makes it …
> allow updating at a commit, for testing

- updater/bin/fetch_files.rb
- updater/bin/update_files.rb
When running in the CLI with `script/dependabot`, this allows us to add `debugger` in the code and then invoke `bin/run fetch_files --debug` to start a debugging session once that line is hit.
> allow interactive debugging in the CLI

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_multiple_versions/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/transitive_dependency_multiple_versions/package.json
Minor follow up to https://github.com/dependabot/dependabot-core/pull/5801
In testing I saw that https://github.com/dsp-testing/npm-multiple-versions/ was still reporting the dependency was no longer vulnerable. It seems that in some cases when a dependency exists in both `package.json` and `package-lock.json` we weren't preserving all the versions. This turned out to be because when parsing dependencies from `package-lock.json` we converted the `DependencySet` to a list of dependencies and back to a `DependencySet` which loses a bit of the version tracking state. Rather than try to preserve everything in the conversion I found it easier to just skip the unnecessary conversion.
> [npm] fix to preserve all_versions metadata from the lockfile

- .gitignore
`byebug` was replaced with the new `debug` gem as part of the `ruby` `3.1` upgrade.
So swap out the history file locations in `.gitignore` to the new one... see `RUBY_DEBUG_HISTORY_FILE` default value [here](https://github.com/ruby/debug#configuration-list).
This was originally removed in https://github.com/dependabot/dependabot-core/pull/4567/files#diff-2f754321d62f08ba8392b9b168b83e24ea2852bb5d815d63e767f6c3d23c6ac5L19, then put back in  https://github.com/dependabot/dependabot-core/commit/847d111805b78c64c9883e31b421734cb74637fa#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R20.
However, the last trace of `byebug` was removed from `Gemfile.lock` in https://github.com/dependabot/dependabot-core/pull/5849/files#diff-0c7825d57fc79377b294d76c04d7bf63931bba3e9cd7946e19 …
> swap history file from `byebug` to new `debug` gem

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
Adding a yarn global or scoped registry can be done via the yarn CLI with `yarn config add <key> <value>`.
For some reason, yarn will remove any quotes around the value when writing to `.yarnrc`, so this change teaches Dependabot to parse values not encased in quotation marks.
> Make quotes around Yarn private registry sources optional

- npm_and_yarn/helpers/lib/npm/vulnerability-auditor.js
🤞 This fixes test failures seen when the tests are run in a particular order. Details of the advisories are being cached in the npm cache and shared across test runs. This can lead to faulty analysis of vulnerabilities in the tests because we were using the same advisory ids in each evaluation.
I didn't track down exactly where it goes wrong in the arborist code but I found that once I reproduced the failures locally with a particular test seed I could then reliably reproduce the failure on an individual test. After observing that the audit report didn't completely match up with the advisory I tried changing the advisory id and the test passed.
> [npm] Randomize advisory id to avoid cache collisions across tests

- common/lib/dependabot/dependency.rb
- hex/spec/dependabot/hex/update_checker_spec.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
- updater/lib/dependabot/updater.rb
When we need to update a parent dependency to fix an alert on a transitive child dependency we currently return both the parent & child as dependencies to update. Only the parent actually needs to be directly updated as its child dependencies will be automatically updated as part of that process. Still, we include the child dependency in the updated dependency list so it will be included in the PR title/description for context.
Since introducing https://github.com/dependabot/dependabot-core/pull/5822 that means we'll attempt to do a sub-dependency update of the child which has no effect.
This adds a flag to indicate dependencies returned by the updater that don't need to be directly updated and then filters them out before sending them to the FileUpdater. This also works for removed …
> [npm] Flag indirect transitive updates to be ignored by the FileUpdater

- maven/lib/dependabot/maven/file_parser/repositories_finder.rb
- maven/spec/dependabot/maven/file_parser/repositories_finder_spec.rb
- maven/spec/fixtures/poms/overwrite_central_pom.xml
In Maven, it is possible to overwrite repository URLs defined elsewhere by defining a repository with the same ID, as long as the file has precedence according to the [order defined in the docs](https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-order).
This is often used to define a different central repository to replace the default one inherited from the Super POM:
```xml
<repositories>
<repository>
<id>central</id>
<url>https://example.com</url>
<snapshots>
<enabled>false</enabled>
</snapshots>
</repository>
</repositories>
```
In this PR, I've tried to honor that behavior by gathering the IDs along with the URL and deduplicate by ID according to that precedence.
One caveat is that Maven differentiates between repository and pluginRepository. Our code …
> Fix Maven inability to overwrite repository urls by ID

- bin/dry-run.rb
- bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb
- bundler/spec/dependabot/bundler/update_checker/requirements_updater_spec.rb
- cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb
- cargo/spec/dependabot/cargo/update_checker/requirements_updater_spec.rb
- composer/lib/dependabot/composer/update_checker/requirements_updater.rb
- composer/spec/dependabot/composer/update_checker/requirements_updater_spec.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/requirements_updater.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb
- python/lib/dependabot/python/update_checker/requirements_updater.rb
- python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
- updater/lib/dependabot/job.rb
- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/job_spec.rb
- updater/spec/dependabot/updater_spec.rb
The `lockfile-only` versioning strategy is currently handled by only allowing the dependency itself to be unlocked, but not other dependencies that might depend on it.
This is incorrect, because it could perfectly happen that updating a dependency needs other dependencies to be unlocked too to succeed, yet the end result does not involve anything other than lockfile changes. See #5569 for an example.
This PR reimplements the `lockfile-only` versioning strategy by passing it to `UpdateCheckers` as an update strategy and avoid updating any manifest requirements in that case.
I also think this is a good move, because it makes the `lockfile-only` versioning strategy actually testable! I will add tests later.
Fixes #5569.
> Fix `lockfile-only` versioning strategy not creating some updates that are expected

- script/dependabot
Without this change I get
```
$ script/dependabot --help
Error: unknown command "/Users/deivid/Code/dependabot/dependabot-core/.core-bash_history:/home/dependabot/.bash_history" for "dependabot"
Run 'dependabot --help' for usage.
```
With this change
```
$ script/dependabot --help
Run Dependabot jobs from the command line.
Usage:
dependabot [command]
Examples:
$ dependabot update go_modules rsc/quote --dry-run
$ dependabot test -f input.yml
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
test        Test scenarios
update      Perform update job
Flags:
-h, --help                   help for dependabot
--proxy-image string     container image to use for the proxy (default …
```
> Make `script/dependabot --help` actually work

- gradle/lib/dependabot/gradle/file_fetcher.rb
- gradle/lib/dependabot/gradle/file_fetcher/settings_file_parser.rb
- gradle/spec/dependabot/gradle/file_fetcher/settings_file_parser_spec.rb
- gradle/spec/dependabot/gradle/file_fetcher_spec.rb
- gradle/spec/fixtures/github/contents_java_settings_1_included_build.json
- gradle/spec/fixtures/github/contents_java_settings_2_included_builds.json
- gradle/spec/fixtures/github/contents_java_settings_explicit_buildsrc.json
- gradle/spec/fixtures/github/contents_java_with_buildsrc.json
- gradle/spec/fixtures/github/contents_java_with_buildsrc_and_settings.json
- gradle/spec/fixtures/settings_files/call_style_settings.gradle
- gradle/spec/fixtures/settings_files/comment_settings.gradle
- gradle/spec/fixtures/settings_files/composite_build_settings.gradle
- gradle/spec/fixtures/settings_files/composite_build_simple_settings.gradle
- gradle/spec/fixtures/settings_files/settings.gradle.kts
Detect **already supported** Gradle dependency files inside included builds and `buildSrc`.
Dependabot currently supports dependencies in `build.gradle` and other buildscripts in the _main build_. However, these files can be present in the same format in other builds part of the main one: included builds. They can be easily supported by the current file parsing and updating implementation, since they're in the same format, most changes being in fetching files in the additional folders.
- [Usual project `build.gradle`][1]
- [Similar `build.gradle` in an included build][2] (currently not fetched by Dependabot)
Closes #4375
In Gradle, a single build is composed of one root project with zero or more subprojects. A single build can also include other independent builds, each with its own …
> Detect dependencies in Gradle included builds

- bin/dry-run.rb
- bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb
- bundler/spec/dependabot/bundler/update_checker/requirements_updater_spec.rb
- cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb
- cargo/spec/dependabot/cargo/update_checker/requirements_updater_spec.rb
- composer/lib/dependabot/composer/update_checker/requirements_updater.rb
- composer/spec/dependabot/composer/update_checker/requirements_updater_spec.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/requirements_updater.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb
- python/lib/dependabot/python/update_checker/requirements_updater.rb
- python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
- updater/lib/dependabot/job.rb
- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/job_spec.rb
- updater/spec/dependabot/updater_spec.rb
Revert "Merge pull request #5581 from dependabot/deivid-rodriguez/lockfile-only-bug"
This reverts commit 2f14e446f1cccb6e6d3983413ef07f6e96b0829b, reversing changes made to 5ae1a8c240a1cdc45545672200ac8f0f80323094.
This has caused some regressions, which are actually worse than the bug originally fixed.
I'm working on fixing those regressions right now, but I'd rather work on them without the pressure of those regressions hitting more people.
Closes #5892.
Tentatively closes #5890 .
Reopens #5569.
> Revert lockfile-only changes

- maven/lib/dependabot/maven/file_parser/property_value_finder.rb
- maven/lib/dependabot/maven/file_parser/repositories_finder.rb
- maven/spec/dependabot/maven/file_parser/repositories_finder_spec.rb
Currently Dependabot uses any repository or pluginRepository URL it finds in the POM to search for parent POM files. However, there is no reason a child POM needs to have any repositories defined at all. It's fairly common for private/custom registries to only be defined in the parent which is published to the registry. 
The reason why this works locally for Maven users is they often have a `settings.xml` which defines what registry to use, but that file isn't typically checked in to git.
Dependabot users commonly try to put the registry in `dependabot.yml` as a hint to where it can find the parent POM.
This PR takes that hint and puts Maven registries defined in `dependabot.yml` at the front of the list of registries to check.
> add Maven credential metadata to the URLs it searches for POM files

- docker/lib/dependabot/docker/requirement.rb
- docker/lib/dependabot/docker/version.rb
- docker/spec/dependabot/docker/update_checker_spec.rb
- docker/spec/dependabot/docker/version_spec.rb
- docker/spec/fixtures/docker/registry_tags/eclipse-temurin.json
In the edge case of Java versions, which include an extra "update_release" separated by `_`, and that can also include a variable number of segments, Dependabot would interpret something like `11.0.16_8-jdk` as higher than `11.0.16.1_1-jdk`.
This is because up until now Dependabot considers all components equally for sorting, and the 4th component in the first version (8) is higher than the 4th component in the second (1), while previous components are equal.
The correct way to do this is to compare the "release segment" first, in this case, 11.0.16 vs 11.0.16.1, and only if those are equal compare the "update segment".
With that logic in place, things sort as they should.
> Fix dependabot incorrectly downgrading docker versions

- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/metadata_finder.rb
- python/lib/dependabot/python/update_checker.rb
- python/lib/dependabot/python/update_checker/index_finder.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
- python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
There are many ways to specify an alternate pypi index in Python depending on the package manager, for the most part we attempt to parse these settings from pyproject.toml, pip.conf, and requirements.txt settings.  If the project specifies an alternate index url we shouldn't call the public pypi.org index.
There are a number of calls we make to pypi.org to retrieve data that is only available there (primarily the `<package name>/json` metadata endpoint).  These calls currently cause PR creation to fail if pypi.org is unavailable or otherwise blocked/firewalled.  We should be able to generate a PR given a private index even if pypi.org is unavailable.
There are 3 classes of issues I found in attempting to run updates without pypi.org access:
1) Failures to get metadata from pypi.org …
> Fixing PR failures if pypi.org unavailable

- common/lib/dependabot/config/file.rb
- common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
- common/spec/dependabot/pull_request_creator/message_builder_spec.rb
- common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb
- common/spec/fixtures/github/commits_angular_sentence_case.json
We should not try to be too smart since there's too many different commitlint setups. Instead, it seems more sound to use the style of previous commits.
Also, I think commit message should default to use the configured prefix for development dependencies if `prefix` is configured, but `prefix-development` is not.
This is just a naive approach that works with `bin/dry-run.rb` but probably specs need fixing, etc.
Fixes #1666.
> Fix commitlint message style detection

- nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
- nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
- nuget/spec/fixtures/configs/clears_default.config
- nuget/spec/fixtures/configs/disabled_default_sources.config
- nuget/spec/fixtures/configs/excludes_default.config
- nuget/spec/fixtures/configs/include_default_disable_ext_sources.config
- nuget/spec/fixtures/configs/nuget.config
- nuget/spec/fixtures/configs/override_def_source_with_same_key.config
- nuget/spec/fixtures/configs/override_def_source_with_same_key_default.config
In the nuget.config, adding the default public Nuget registry to `disabledPackageSources` section was not disabling it. Dependabot was still able to access the default public registry (nuget.org). 
With this modification, the dependabot won't contact the default public registry if a user disable the public nuget registry in the `disabledPackageSources` section even without using the `<clear />` tag in the nuget.config. [[ref](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#example-nugetdefaultsconfig-and-application)]
> Fixed disabledPackageSources for nuget.org

- Dockerfile
I observed that many times buildkit cache is not being hit, triggering a rebuild of the whole dependabot-core image, in situations where it would not seem necessary.
One hypothesis is that this is due to the `COPY --from` usage when installing composer, since I recall issues with that not playing well with buildkit cache.
I want to try a different way of installing composer, in order to verify whether this is the culprit and this speeds up our CI.
> Install composer in a way that does not use `COPY --from`

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
Version resolution for security updates was broken for yarn berry if there were any packages sourced from private registries, even if the private registry was correctly configured. Previously we were not performing version resolution with yarn berry for security updates, this still worked as long as yarn 1 could talk to all of the necessary registries.
This PR adds specific version resolution calls for yarn berry to the subdependency version resolver so that it doesn't attempt to use yarn 1 when performing this resolution.
This still requires that any package mentioned in yarn.lock or package.json is reachable by Dependabot. This means if there are packages sourced from private registries and Dependabot does not have access to those registries due to lack of configuration or incorrect …
> Yarn Berry: Fixes subdependency security updates

- maven/lib/dependabot/maven/file_parser/repositories_finder.rb
- maven/spec/dependabot/maven/file_parser/repositories_finder_spec.rb
In project where POMs have grandparents (the POM's parent has a parent) we're seeing Dependabot forget about repositories it has seen in previous POMs. So it will start off well querying for a parent in a custom repository, but then forget about that and try to get the grandparent from Maven Central where it doesn't exist.
This PR adds tracking for URLs seen in POM files so that Dependabot can find the grandparent.
I was careful to keep the central repo URL out of the list of known URLs because if we have `[custom1, central]` in the first POM and `[custom2, central]` in the second, that would add up to `[custom1, central, custom2]` which is not the ideal order.
I tested this locally and it fixes #4168 and #5543. It also makes Dependabot "just work" in more cases now!
> Maven: fix forgetting repositories seen in earlier POMs

- python/lib/dependabot/python/update_checker.rb
- python/spec/dependabot/python/update_checker_spec.rb
I discovered this issue while wrapping up #5661. However, the issue is already there so I think it makes sense to extract it to its own PR.
If a library has both a pyproject.toml file and a standard requirements.txt file, we'd end up using the `:widen` strategy for the dependencies in the `requirements.txt` file if the project is a library, and eventually crashing with an error like the following:
```
/home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:266:in `block in preferred_version_resolvable_with_unlock?': undefined method `[]' for nil:NilClass (NoMethodError)
updated_requirements.none? { |r| r[:requirement] == :unfixable }
^^^^^^^^^^^^^^
from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:266:in `none?'
from …
```
> Fix crash when updating Python libraries with multiple manifest types

- common/lib/dependabot/source.rb
- common/spec/dependabot/source_spec.rb
This bug was causing Dependabot to not be able to create PRs to bump the oauth2 ruby gem.
This is a fairly popular Ruby gem. It's hosted a gitlab.com, and uses gemspec metadata to declare how to find it's changelog.
The URL it uses is `https://gitlab.com/oauth-xx/oauth2/-/tree/v2.0.9/CHANGELOG.md`, which Dependabot was not parsing properly, causing runtime errors.
This is a regression from 49d1a13fca921000b8f9a76612a67d9098431ebd.
Before, when trying to create a PR bump the oauth2 rubygem, you would get:
```
🌍 https://rubygems.org/api/v1/gems/oauth2.json
🌍 https://gitlab.com/oauth-xx/oauth2/-/tree/v2.0.9.git/info/refs
/home/dependabot/dependabot-core/common/lib/dependabot/git_metadata_fetcher.rb:68:in `fetch_upload_pack_for': Server error at …
```
> Fix error when parsing Gitlab changelogs

- bundler/lib/dependabot/bundler/file_updater/gemfile_updater.rb
- bundler/spec/dependabot/bundler/file_updater/gemfile_updater_spec.rb
If there's an evaled gemfile that also includes git dependencies, it would result in a crash like the following:
```
Failure/Error:
dependency.requirements.
find { |f| f[:file] == file.name }.
fetch(:source).fetch(:ref)
NoMethodError:
undefined method `fetch' for nil:NilClass
fetch(:source).fetch(:ref)
```
We need to check the Gemfile name being updated, not generic names when figuring out if we should update any git pins.
> Fix crash when updating git dependencies

- github_actions/lib/dependabot/github_actions/update_checker.rb
- github_actions/spec/dependabot/github_actions/update_checker_spec.rb
Never changing the existing version precision is our default behavior, however there's one edge case where Dependabot may actually propose a PR changing the precision.
This is only in the interim between the time where a new major version of the action has been released, but the action's author has not yet created a new major version tag pointing to the new release.
If Dependabot happens to run between the above two events, it will create a PR changing the precision from vX to vX.Y.Z, just because it's unable to find any versions with the same precision.
I think this in never what users expect, and it introduces inconsistent behavior in Dependabot, not dependent of the state of the manifest files, but on external circumstances which is confusing. On top of that, the issue will be …
> Never change version precision of actions chosen by users

- nuget/lib/dependabot/nuget/metadata_finder.rb
- nuget/spec/dependabot/nuget/metadata_finder_spec.rb
When pubic registry is disabled in the Nuget, it still tries to make a call to public registry url (`https://api.nuget.org/v3-flatcontainer/nuget.versioning/6.2.1/nuget.versioning.nuspec`) to get the nuspec file if no nuspec file url is provided.
Earlier, in the `dependency_nuspec_url` function of the metadata finder, a default public nuspec url was added if the source was missing or if the source was present but had no nuspec file. I have removed the injection of the default public nuspec url when there is either no source or no nuspec url specified in the source.
Even without my change from this PR, when nuspec url was nil in source, the metadata finder was calling the default nuspec url and returning 404.
Nuspec file: A .nuspec file is an XML manifest that contains package metadata. …
> No public url call when public registry is disabled

- bin/dry-run.rb
Check whether up to date after figuring latest version.
Before, on a standard Python update:
```
$ time bin/dry-run.rb pip LeeeeT/valtypes --cache files
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
=> reading dependency files from cache manifest: ./dry-run/LeeeeT/valtypes/cache-manifest-pip.json
=> updating 11 dependencies: pre-commit, isort, sort-all, black, pyproject-flake8, mypy, pyright, pytest, pytest-cov, mkdocs-material, jinja2
=== pre-commit ()
=> checking for updates 1/11
🌍 https://pypi.org/simple/pre-commit/
=> latest available version is 2.20.0
=> latest allowed version is 2.20.0
(no update needed as it's already up-to-date)
(...)
=== jinja2 (3.1.0)
=> checking for updates 11/11
🌍 https://pypi.org/simple/jinja2/
=> latest …
```
> Make dry-run script twice as fast

- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
Avoid unnecessary `pip-compile` processes, and explain why we need to run an extra one sometimes.
Closes #5903.
> Only call pip compile once

- common/lib/dependabot/pull_request_creator/message_builder.rb
- common/spec/dependabot/pull_request_creator/message_builder_spec.rb
This improves the PR title to only mention a dependency once if it's being updated to multiple versions.
ex: https://github.com/dependabot/dependabot-core/issues/5880
Fix https://github.com/dependabot/dependabot-core/issues/5888
> Don't repeat dependency names in PR title

- python/lib/dependabot/python/update_checker.rb
- python/spec/dependabot/python/update_checker_spec.rb
If a library keeps a requirement duplicated in
pyproject.toml/poetry.lock and a requirements.txt file, Dependabot updates will crash because we will try to widen requirements in the requirements file, which is not supported.
Honestly, I don't know what users of this kind of setup expect so I opted for fixing the crash without changing the current behavior, namely, no updates.
> Fix crashes on Python libraries using multiple manifests

- Dockerfile.updater
- updater/Gemfile.lock
This is not a big problem, specially now that we're not pushing new gems to rubygems.org. But the lock file could still get out of sync unintentionally and this should prevent that.
This should clear #5858 from any changes other than the Bundler upgrade.
> Keep updater lockfile in sync with subgem changes

- Dockerfile
- updater/Gemfile.lock
I noticed the following log lines in [the output of building the `updater`](https://github.com/dependabot/dependabot-core/actions/runs/3212248230/jobs/5250946524) Docker image:
```
32 sha256:563a023320753425444761bd82772c641463b33ea716db65998c70bdc931dd95
32 1.167 Bundler 2.3.22 is running, but your lockfile was generated with 2.2.20. Installing Bundler 2.2.20 and restarting using that version.
32 2.192 Fetching gem metadata from https://rubygems.org/.
32 2.217 Fetching bundler 2.2.20
32 2.297 Installing bundler 2.2.20
32 2.511 Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
32 3.308 Fetching gem metadata from https://rubygems.org/.........
```
That's probably because …
> Regenerate `updater/Gemfile.lock`

- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/helpers.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
- python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
As part of the work to allow Dependabot to work reliably when isolated from the internet some code cleanup has been identified.  This is the beginning of the work to limit the places where we make attempts to talk to the public internet
I've added a new `helpers.rb` for python which will contain various methods which are currently copy/pasted between the various python package manager implementations.  The first method I've moved over is the method that installs new python versions via `pyenv install`.
I am pretty sure the `python_version` and the methods it calls in the various implementations can also be moved to the new `helpers.rb` and I will be working on that next.
> Centralize pyenv install logic

- common/lib/dependabot/file_fetchers/base.rb
- common/spec/dependabot/file_fetchers/base_spec.rb
- go_modules/lib/dependabot/go_modules/file_fetcher.rb
- go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
Closes https://github.com/dependabot/dependabot-core/issues/5975
Repos are always git-cloned with `--no-recurse-submodules`. This can be problematic if a dependency lives in a git submodule and dependency resolution requires reading from it. For my use case, this is showing up when using go modules.
This PR adds `#recurse_submodules_when_cloning?` to `Dependabot::FileFetchers::Base`. If it returns a truthy value, repos are git-cloned with [`--recurse-submodules`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---recurse-submodulesltpathspecgt) and [`--shallow-submodules`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---no-shallow-submodules); if it returns a falsy value, `--no-recurse-submodules` is used (the current behavior).
The default implementation of …
> Allow file fetchers to opt into loading git submodules

- .github/ISSUE_TEMPLATE/bug-report.yml
- Bump from Node.js `14.1` to `16.18`
`16.18` is the latest Node.16 maintenance release.
You use Node `16` in your Dockerfile, so it seems good to match that in the bug report description.
https://github.com/dependabot/dependabot-core/blob/6da4eadd68fea6c0c9f4975ea17be2e957514576/Dockerfile#L114-L121
> Bump Node.js in bug report description field

- common/lib/dependabot/git_commit_checker.rb
- github_actions/lib/dependabot/github_actions/file_updater.rb
- github_actions/spec/dependabot/github_actions/file_updater_spec.rb
- github_actions/spec/fixtures/workflow_files/pinned_sources_version_comments.yml
GitHub encourages pinning third-party GitHub Actions to a full length commit SHA. It's common for actions pinned by commit SHA to include a comment specifying the version associated with the commit. For example:
- uses: actions/checkout@01aecc # v2.1.0
This change updates the GitHub Actions manager to bump versions in comments that follow SHA-pinned actions, so the comment stays up-to-date with the SHA being updated.
The file_updater now searches the comment string for all references to the previous version and replaces them with the new version. To avoid changing unrelated comments, the comment updater only updates dependencies that pin SHA refs.
---
> **Note**
> I'm not an experienced Ruby developer and I welcome any suggestions to improve the code. My main goal was to make a minimal …
> Update version comments for SHA-pinned GitHub Actions

- Dockerfile
Our native helpers reference Hex.Version.InvalidRequirementError which comes from Hex itself, and since 2.0.0 was released it seems that struct is gone causing a compiler error. So I've pinned Dependabot to 1.0.1 until we can fix the issue and upgrade.
> fix hex native helpers: v2.0.0 removed Hex.Version.InvalidRequirementError

- Dockerfile
The `1.13.x` `elixir` releases have a single precompiled file. But it's not clear which OTP release they're compiled against.
The `1.14.x` `elixir` releases have multiple precompiled binaries for OTP 23, 24, and 25. So we can specify which binary to pull to guarantee it aligns with the Erlang version we're using.
> Bump Elixir so we can specify the OTP version

- Dockerfile
- common/dependabot-common.gemspec
We use `dependabot-core` as a library in a few internal projects. After the bump to `3.3.22`, they started complaining with the following error:
```
dependabot-common-0.213.0 requires rubygems version >= 3.3.22, which is
incompatible with the current version, 3.3.7
```
RubyGems `3.3.7` is the version shipped with `ruby:3.1.2`.
While we could patch all those places to update their system RubyGems, it's a bit of a game of whack-a-mole, and adds minimal value.
So instead, relax the constraint slightly so that those versions work. I don't mind forcing folks to upgrade to the newest Ruby, but as long as they do that, then there's no need for us to be forcing them to futz around further.
Downgrading the version used in the Dockerfile was optional, but I thought better to keep that in sync with …
> Downgrade RubyGems to 3.3.7 to match Ruby 3.1.2

- Dockerfile
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
cc @jurre  @defunctzombie
Run `git lfs pull --include .yarn` before using yarn for dependency updating. Yarn plugins stored with LFS can now be used.
Resolves LFS issues described in https://github.com/dependabot/dependabot-core/issues/1297, see example Dependabot PR at https://github.com/foxglove/studio/pull/4528
Tested with `bin/dry-run.rb npm_and_yarn foxglove/studio --clone --dep rc-tree`, which now updates yarn.lock instead of failing with an error.
Ran unit test with `cd npm_and_yarn && bundle exec rspec spec/dependabot/npm_and_yarn/file_fetcher_spec.rb -e "with .yarn data stored in git-lfs"`
> Yarn Berry: run git lfs pull before running yarn

- hex/helpers/lib/check_update.exs
As noted in https://github.com/dependabot/dependabot-core/issues/6009, Hex has no public API, so we should be using `elixir`'s built-in [`Version.InvalidRequirementError`](https://hexdocs.pm/elixir/Version.InvalidRequirementError.html) instead of `Hex.Version.InvalidRequirementError`.
Despite Hex not having a public API, we're still calling into it all over the place in this script, but that can't really be helped.
But this particular call can be updated, which will unblock bumping to Hex 2.0
Co-authored-by: @sorentwo
Co-authored-by: @tiagoefmoraes
> Use `elixir`'s `InvalidRequirementError`

- Dockerfile
- bundler/helpers/v1/monkey_patches/definition_ruby_version_patch.rb
- bundler/helpers/v2/monkey_patches/definition_ruby_version_patch.rb
Dependabot monkeypatches Bundler to allow resolving for arbitrary rubies, not just for the running Ruby. However, when no Ruby information is provided via either `gemspec` files or `ruby` Gemfile directive, Dependabot was only allowing to resolve either to Ruby 2.5, or to the running Ruby 3.1.
In some situations, it can happen that resolving on Ruby 3.1 is not possible, while resolving on Ruby 2.5 is possible but requires downgrading some lock file dependencies.
To avoid this problem, let's add the missing rubies to our list of rubies Dependabot can resolve to.
NOTE: I spent some time trying to write specs for this, but it turned out pretty tricky. In the end, I added a note in the Dockerfile to avoid falling out of sync again here. Also, I will look into porting this functionality to …
> Fix accidental downgrades in Bundler PRs

- nuget/lib/dependabot/nuget/version.rb
- nuget/spec/dependabot/nuget/update_checker/requirements_updater_spec.rb
- nuget/spec/dependabot/nuget/version_spec.rb
fixes #2310
We already don't consider NuGet build info when comparing versions. The next step is to not add the build info to versions bumped in the manifests which is what users expect, and how the native tooling behaves. 
By removing it immediately when parsing the version we ensure it won't appear when `to_s` is called.
> nuget: keep version build identifiers out of manifests

- Dockerfile
- hex/helpers/build
Moves the location of the `hex` version pin to a more intuitive location.
This also centralizes the install logic within the helper builder script so that we don't call `mix local.hex` twice.
We could do it externally, but Hex requires being installed as the Dependabot user, and so we end up with the Hex install commands sitting right next to the build script... so rather than scattering the logic across the Dockerfile and build script, I opted to keep it all in the build script. This way if a developer is using the build script for local development w/o rebuilding the docker image, it's a repeatable experience.
> Move location of `hex` version pin

- cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
Context: https://github.com/dependabot/dependabot-core/pull/5332#discussion_r936888624
Now with `git-fetch-with-cli = true` it's using Git CLI's error message so no need to catch the old HTTP variant.
> Stop catching 200 error

- Dockerfile
- python/helpers/build
- python/lib/dependabot/python/python_versions.rb
- python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
It was just released on Oct. 24, 2022:
https://www.python.org/downloads/release/python-3110/
pyenv is providing 3.11 support was released today:
- https://github.com/pyenv/pyenv/releases/tag/v2.3.6
- https://github.com/Homebrew/homebrew-core/commit/c6ab2f5caf80d8558a1d76a88a5352aa4d318936
> Add support for Python 3.11.0

- Dockerfile
- bundler/helpers/v2/monkey_patches/definition_bundler_version_patch.rb
- updater/Gemfile.lock
Recently I've been experiencing an issue where Dependabot has stopped working and always [times out](https://github.com/Homebrew/brew/network/updates/499334214).
I've looked into why that was happening and it's a Bundler bug that was [fixed](https://github.com/rubygems/rubygems/pull/5698) in 2.3.24. Dependabot is however still using 2.3.22.
I've tested this change locally and it fixed the issue for me. `dependabot update` always hung before but now succeeeds.
The fix upstream changed some methods a bit, so I've updated a monkey-patch accordingly.
> Upgrade Bundler to 2.3.25

- go_modules/lib/dependabot/go_modules/file_parser.rb
- go_modules/spec/dependabot/go_modules/file_parser_spec.rb
- go_modules/spec/fixtures/projects/unknown_vcs_local_replacement/go.mod
- go_modules/spec/fixtures/projects/unknown_vcs_local_replacement/main.go
Fixes #5949, so that if a project is using a module namespace that does not have an accessible version control system, and is using local replacements like a monorepo, dependabot will not fail to update the dependencies it can. Example:
```go
module company.com/vcs/service
go 1.12
require (
company.com/vcs/gotool v0.0.0-00010101000000-000000000000
)
replace (
company.com/vcs/gotool => ../monorepo/common
)
```
Updates the `go_modules` `file_parser` implementation such that: if dependabot encounters a `DependencyFileNotResolvable` error but the dependency has a local replacement available, it will not fail to update the remaining dependencies.
This case can occur in monorepos whose module paths are not a mapping to their version control system.
I've added the test scenario, and ran the …
> Don't fail if dependency with unknown vcs has local replacement

- bundler/lib/dependabot/bundler/metadata_finder.rb
- bundler/spec/dependabot/bundler/metadata_finder_spec.rb
When looking up metadata for Bundler, Dependabot would fall back to using rubygems.org even if the user had a private registry defined. 
This PR allows the user to define a host that replaces that with a private registry of their own by using the "replaces-base" setting in dependabot.yml.
> Bundler: use the replaces-base credential for metadata lookup

- docker/lib/dependabot/docker/update_checker.rb
This was detected by CodeQL in #6075 as inefficient Regexp.
I extracted it from that PR since it's an unrelated fix.
I had a look and yeah, I believe the Regexp was too unspecific and can be made more specific and thus easier to process.
> Fix docker version regexp matching too much

- docker/spec/dependabot/docker/file_fetcher_spec.rb
I'm going to be adding more test cases, so DRY this up so I don't have to copy/paste the stubbed requests.
Doing as a separate PR from the PR adding test cases because I need external feedback on the list of new test cases.
> DRY up the matching filename list

- docker/lib/dependabot/docker/file_fetcher.rb
- docker/spec/dependabot/docker/file_fetcher_spec.rb
- docker/spec/fixtures/github/contents_helm_repo.json
- docker/spec/fixtures/github/contents_values_yaml.json
While pairing with `@bdragon`, he noticed this check is only looking for `*.yaml` files. However, we suspect Helm also supports `.yml` files.
I found mention of `values.yml` in their documentation: https://v2.helm.sh/docs/developing_charts/#chart-development-tips-and-tricks
So we should support it as well.
Co-authored-by: Bryan Dragon <bdragon@github.com>
> Helm supports both `.yml` and `.yaml`

- docker/lib/dependabot/docker/file_fetcher.rb
- docker/lib/dependabot/docker/file_updater.rb
- docker/lib/dependabot/docker/utils/helpers.rb
The docker updater for helm charts was hardcoded to `"values.yaml"`.
But we should support the full range of filenames supported in the file fetcher... for example, in the wild we saw this failing to update `"arc-values.yaml"` because of this hardcoding.
> Update helm charts beyond `values.yaml`

- docker/spec/dependabot/docker/file_updater_spec.rb
These tests were originally written by copy/pasting the `"docker"` ecosystem into an entirely new ecosystem called `"kubernetes"`. However, given the amount of duplication between them, we worked with the original contributor to instead extend the `"docker"` ecosystem itself.
It looks like these tests were never updated from the original `"kubernetes"` package manager name back to `"docker"`, so this fixes that.
> Use correct package manager name

- python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
This is a fix focused on #6090, but we may want to consider unifying and reviewing all helpers that shell out, because this same thing is likely to be happening in other places.
I guess we could also log warnings somewhere, not sure.
I thought of a adding a spec but it was a bit tricky.
Fixes #6090.
> Don't leak pipenv warnings into manifest files

- python/lib/dependabot/python/file_updater/pyproject_preparer.rb
- python/spec/dependabot/python/file_updater/pyproject_preparer_spec.rb
- python/spec/fixtures/pyproject_files/multiple_constraint_dependency.toml
- python/spec/fixtures/pyproject_locks/multiple_constraint_dependency.lock
Before trying to generate a lockfile with an upgraded dependency, Dependabot first explicitly updates the pyproject.toml file like the following:
* It pins the dependency to be upgraded to the resolved versions.
* It pins all other dependencies to the locked version.
In this particular case, the numpy dependency is getting locked to 1.21.6, but this is incorrect, because it's a multiple constraint dependency, so locking it explicitly will cause some versions to be removed from the lock file.
In general, the second step does not seem necessary to me. The command we run to update the lock file, `poetry update <dependency> --lock` should deal with it fine and keep the locked dependencies not being upgraded untouched.
However, when removing all that logic, some specs fail since they let other …
> Fix multiple constraint Poetry dependencies getting bad updates

- nuget/lib/dependabot/nuget/file_updater/packages_config_declaration_finder.rb
- nuget/spec/dependabot/nuget/file_updater/packages_config_declaration_finder_spec.rb
- nuget/spec/fixtures/packages_configs/packages.config
Since pattern whitespace is being ignored via the `x` flag, the string `<packages>` incorrectly matches the second part of the regex (`<package\s[^>]*?[^/]>.*?</package>`) when "package" isn't a self-closing element.
For example:
```xml
<packages>
<package id="mypackage" version="0.0.0"></package>
</packages>
```
will match:
```
<packages>
<package id="mypackage" version="0.0.0"></package>
```
This commit makes the space explicit so that `<packages>` no longer matches.
> Fix NuGet packages.config parsing

- bin/dry-run.rb
I actually run `dry-run.rb` without `docker-dev-shell` quite often, specifically in those ecosystem where I know I have everything I need, or when I'm confident I can troubleshoot any issues.
With the current situation I have to keep stashing and unstashing a patch to remove this whole block when I need to. Instead I could live with a warning every time I run this, but that allows me to avoid all this dance.
I also think this is less important now that our main entry point to reproduce issues is the [CLI](https://github.com/dependabot/cli).
Thoughts?
> Tolerate running `dry-run.rb` without `docker-dev-shell`

- common/lib/dependabot/clients/azure.rb
- common/lib/dependabot/pull_request_creator.rb
- common/lib/dependabot/pull_request_creator/azure.rb
- common/spec/dependabot/pull_request_creator/azure_spec.rb
- common/spec/dependabot/pull_request_creator_spec.rb
Allows [creating a PR ](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-rest-6.0&tabs=HTTP) for Azure DevOps and assigning directly a 
- required reviewer (reviewer)
- optional reviewer (assignee)
by providing the ids of the identities to be assigned.
just for completeness, the identity Id can be retrieved in scripts:
- Azure DevOps Services using the [Graph API](https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/subject-query/query?view=azure-devops-rest-6.1), [Stackoverflow](https://stackoverflow.com/a/70268220)
- Azure DevOps Server using the [Identities API](https://learn.microsoft.com/en-us/rest/api/azure/devops/ims/identities/read-identities?view=azure-devops-server-rest-6.0&tabs=HTTP) using a `searchFilter` for e.g. a …
> Add Azure DevOps support for creating a PR with assigned reviewers

- script/_common
These args appear unused. `git blame` shows they landed as part of the merge of updater-into-core, so possibly they're a relic from that.
> Remove unused `appdir` arg

- updater/lib/dependabot/file_fetcher_job.rb
- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/file_fetcher_job_spec.rb
- updater/spec/dependabot/updater_spec.rb
As the comment notes in the code below, originally this was added because of file permission issues when cleaning up after a job since the Dependabot Action runs as root. The other reason this is needed is the container runs fetch_files in one container, then update_files in another. Since the clone happens in fetch_files, the repo directory had to be mounted to avoid cloning twice.
So in https://github.com/github/dependabot-action/pull/319 I removed the need to mount the directory, so this code is no longer needed because the repo only exists inside the container which is removed on completion.
> local clone deletion not required due to action change

- common/spec/dependabot/pull_request_creator/github_spec.rb
- common/spec/dependabot/pull_request_updater/github_spec.rb
I was being a bad boy and running `common/` specs outside of the development container and got a couple of failures.
Failures were due to my specific timezone.
This PR makes specs timezone independent.
> Make specs time zone independent

- docker/lib/dependabot/docker/file_fetcher.rb
`DependencyFileNotFound` is treated by our internal monitoring as a user configuration error, and not something we need to act on. Additionally, we surface a nice clean error banner to the user.
`DependabotError` is treated as an unknown error that requires further investigation, so it's causing our internal alerts to flap when users don't have a manifest file... for example, users sometimes assume the `docker` check is recursive so they specify it as `"/"`, but it's not so it raises this error.
This is a super quick PR that we can get deployed to stop our alerts flapping. I'm working on a larger refactor of this section of code that also removes the feature flag and adds a unit test to ensure the proper exception is raised.
> Raise `DependencyFileNotFound` for missing files

- docker/lib/dependabot/docker/file_fetcher.rb
- docker/spec/dependabot/docker/file_fetcher_spec.rb
This has been rolled out 100%, so safe to remove.
> Remove the `kubernetes_updates` feature flag

- docker/spec/dependabot/docker/file_fetcher_spec.rb
- docker/spec/fixtures/github/contents_no_docker_repo.json
Add a unit test to guard against regressions resulting in bugs like https://github.com/dependabot/dependabot-core/pull/6142.
I didn't include this with the original PR because I was uncertain if it'd be affected by the removal of the `kubernetes_updates` feature flag in https://github.com/dependabot/dependabot-core/pull/6144.
> Add unit test for `docker` `DependencyFileNotFound`

- Dockerfile
Bump to the latest release. I started to add the SHA256 validation, but it'll require refactoring how the unzipping works, so leaving that for later as the version bump is a step in the right direction for now.
Fix #6126
> Bump `Dart` to `2.18.4`

- .rubocop.yml
- Dockerfile.development
- Gemfile
For the same reasons this is useful in the development container, I'd like to also have it outside of the development container.
My use case is to quickly run RuboCop over the whole repo when making global changes across ecosystems.
> Create a permanent root Gemfile

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
Previous to this PR we were still running yarn classic to check for peer dependency issues created by a proposed version update. This was slow and probably could result in incorrect answers.
I've added a yarn berry specific checker based on the output I could see after adding a dependency at a version that breaks a peer dependency request. This may be naive, and almost certainly does not catch all cases so I'd appreciate feedback around how to make this check more accurate. One specific shortcoming is that without making additional calls to `yarn explain` the versions of the the peer dependency mismatch are not available. In the short term this may cause us to fail to create a possible PR if we could have resolved an update to an earlier version.
> Yarn Berry: Adding a peer dependency checker

- .github/workflows/docker-branch-releases.yml
- .github/workflows/docker-fork-releases.yml
- .github/workflows/docker-main-releases.yml
#6155 removed the pull_request trigger, but we need it since it triggers when we update a branch from master, for instance, or push a small change. That way we don't need to ask for reapproval in those cases. 
I **think** types: edited is the correct thing to put. We don't need the workflow to run when the PR opens, or closes, etc.
I also fixed the names of the latest release workflow being the same as the branch release workflow, which then got me carried away to make all the names shorter and more accurate.
> need pull_request trigger for branch updates

- bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
- cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
- common/lib/dependabot/dependency.rb
- common/lib/dependabot/git_commit_checker.rb
- common/lib/dependabot/update_checkers/base.rb
- composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
- elm/lib/dependabot/elm/update_checker.rb
- github_actions/lib/dependabot/github_actions/update_checker.rb
- go_modules/lib/dependabot/go_modules/update_checker.rb
- go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
- gradle/lib/dependabot/gradle/update_checker/version_finder.rb
- hex/lib/dependabot/hex/update_checker.rb
- maven/lib/dependabot/maven/update_checker/version_finder.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
- nuget/lib/dependabot/nuget/update_checker/version_finder.rb
- python/lib/dependabot/python/update_checker/latest_version_finder.rb
- terraform/lib/dependabot/terraform/update_checker.rb
While working on #6071 I noticed some common logic across ecosystem that I think makes sense to be moved to common.
There's a lot of more that can be done here, but I didn't want to deviate too much from my original goal, so I stopped here which I believe is already an improvement.
> Refactor some common logic across ecosystems

- cargo/lib/dependabot/cargo/version.rb
- cargo/spec/dependabot/cargo/version_spec.rb
Cargo implements standard semantic versions as per https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field.
And standard semantic versioning allows hyphens in build identifiers as per https://semver.org/#spec-item-10.
> Allow cargo versions with hypens in build identifiers

- github_actions/lib/dependabot/github_actions/file_fetcher.rb
While testing security updates for actions, I noticed that manual security update jobs are created with an explicit `directory` option passed with the `/.github/workflows` value.
But our updater currently does not support this.
Apparently, it used to, but that broke at some point.
Fixes https://github.com/dependabot/dependabot-core/issues/5047.
> Respect custom directory for actions updates

- docker/lib/dependabot/docker/update_checker.rb
- docker/lib/dependabot/docker/version.rb
- docker/spec/dependabot/docker/update_checker_spec.rb
I'm not adding any specs because the spec that my changes broke illustrates perfectly the desired behavior.
Fixes #3929.
Fixes #4535.
Fixes #6169.
> Fix inconsistent docker updates with `-` suffixed images

- common/lib/dependabot/clients/bitbucket.rb
- common/spec/dependabot/clients/bitbucket_spec.rb
- common/spec/fixtures/bitbucket/pull_requests_no_match.json
- common/spec/fixtures/bitbucket/pull_requests_with_match.json
This way the code can also be used to fetch more than one pull request and the state of the pull requests to fetch can be specified.
With this function it's possible to decline a pull request with a provided comment (a default comment is provided as fallback).
> Bitbucket improvements

- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
Bugfix for pre-compiled python. I originally missed a couple places where we set the full version instead of just `major.minor`
> Use only python major.minor version

- python/lib/dependabot/python/python_versions.rb
Add note about why `3.9.3` excluded
> Add note about why `3.9.3` omitted

- github_actions/lib/dependabot/github_actions/file_fetcher.rb
In #6189 I changed Actions logic to respect explicit directories being configured to fetch files from.
This PR changes the error message to follow the new logic.
> Honor new dir selection logic in Github Actions error messages

- bundler/dependabot-bundler.gemspec
- cargo/dependabot-cargo.gemspec
- common/dependabot-common.gemspec
- composer/dependabot-composer.gemspec
- docker/dependabot-docker.gemspec
- elm/dependabot-elm.gemspec
- git_submodules/dependabot-git_submodules.gemspec
- github_actions/dependabot-github_actions.gemspec
- go_modules/dependabot-go_modules.gemspec
- gradle/dependabot-gradle.gemspec
- hex/dependabot-hex.gemspec
- maven/dependabot-maven.gemspec
- npm_and_yarn/dependabot-npm_and_yarn.gemspec
- omnibus/dependabot-omnibus.gemspec
- pub/dependabot-pub.gemspec
- python/dependabot-python.gemspec
- terraform/dependabot-terraform.gemspec
This is the result of running `time bundle exec rubocop --version` on my machine with the code in main:
```
$ time bundle exec rubocop --version
1.39.0
bundle exec rubocop --version  9,92s user 0,73s system 96% cpu 11,075 total
```
10 seconds, wait, what??
This is the result with this branch:
```
$ time bundle exec rubocop --version
1.39.0
bundle exec rubocop --version  0,56s user 0,30s system 94% cpu 0,909 total
```
Half a second seems more sensitive 😅.
To figure out why this is, we can add a `puts` statement in one of the gemspecs:
```diff
diff --git a/bundler/dependabot-bundler.gemspec b/bundler/dependabot-bundler.gemspec
index d8fa4822e..147ec9e55 100644
--- a/bundler/dependabot-bundler.gemspec
+++ b/bundler/dependabot-bundler.gemspec
@@ -42,4 +42,7 @@ Gem::Specification.new do |spec| …
```
> Use git to fill in gemspec files

- .github/dependabot.yml
- bundler/lib/dependabot/bundler/file_parser.rb
- bundler/lib/dependabot/bundler/file_parser/gemspec_declaration_finder.rb
- bundler/spec/dependabot/bundler/file_parser/gemspec_declaration_finder_spec.rb
- bundler/spec/dependabot/bundler/file_parser_spec.rb
- bundler/spec/fixtures/projects/bundler1/gemspec_loads_another/another.gemspec
- bundler/spec/fixtures/projects/bundler1/gemspec_loads_another/example.gemspec
- bundler/spec/fixtures/projects/bundler2/gemspec_loads_another/another.gemspec
- bundler/spec/fixtures/projects/bundler2/gemspec_loads_another/example.gemspec
This is my WIP work to fix the issue I mentioned at https://github.com/dependabot/dependabot-core/pull/6179#issuecomment-1322489357.
Currently dependabot can't handle things like what we do here:
https://github.com/dependabot/dependabot-core/blob/52226f5d298cbc66a331bc5b64b67300515b7697/omnibus/dependabot-omnibus.gemspec#L42-L44
When checking whether the requirements of a dependency can be unlocked, Dependabot checks whether modifying all requirements of the dependency always results in a changed manifest. However, in the case of these dynamically loaded gemspecs, this replacement does not change the manifest, and as a consequence, Dependabot interprets that the requirement cannot be unlocked and is unable to update the dependency.
As a solution, when deciding whether to add gemspec …
> Fix dependabot not updating gemspec dependencies loaded dynamically from other gemspecs

- Dockerfile
- Dockerfile.development
When developing Bundler native helpers, I sometimes edit one helper and then run `helpers/v2/build` in the development container and then rerun specs affected by the change.
This currently doesn't work and results in something like:
```
[dependabot-core-dev] ~/dependabot-core/bundler $ helpers/v2/build
Successfully installed bundler-2.3.25
1 gem installed
Setting `path` to nil, since path and path.system are mutually exclusive
Fetching gem metadata from https://rubygems.org/......
Using rake 13.0.6
Fetching concurrent-ruby 1.1.10
Fetching minitest 5.16.3
Fetching ansi 1.5.0
Fetching public_suffix 5.0.0
Installing ansi 1.5.0
Installing minitest 5.16.3
Installing public_suffix 5.0.0
(...)
[dependabot-core-dev] ~/dependabot-core/bundler $ bundle exec rspec …
```
> Improve Bundler configuration

- terraform/spec/dependabot/terraform/file_parser_spec.rb
- terraform/spec/fixtures/projects/private_module_with_dir_suffix/main.tf
I am suspecting that module sources containing a dir suffix is not properly handled. Unable to test locally due to the size of the Docker developer image.
> test: add test for private registry module with dir suffix

- Dockerfile
While working on the pub security update I happened to notice that `2.18.5` dropped yesterday.
> Bump Dart to 2.18.5

- pub/lib/dependabot/pub/requirement.rb
Rubocop was complaining about this in an unrelated PR, so split it out to make future `git blame` simpler.
> Remove redundant freeze

- common/lib/dependabot/file_fetchers/base.rb
- common/spec/dependabot/file_fetchers/base_spec.rb
In #5982 we enabled submodule cloning by default. However, sometimes a repo has a submodule that is inaccessible to Dependabot that is unrelated to dependencies.
We talked about adding a flag to disable it, but it's nice when Dependabot just works. 
So for this PR I took the approach to just ignore the submodule clone errors and continue with the update. That way if it was  not important, it will succeed in doing the update.
If it was important it will fail later, but I added an error log that says the nature of the failure during the fetch as a hint as to what might be wrong.
> submodule cloning may not be important to the job, ignore errors

- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
Co-authored-by: David Rodríguez <deivid.rodriguez@riseup.net>
> Prevent `NoMethodError` when captures are missing

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
- npm_and_yarn/spec/fixtures/projects/npm8/path_dependency_blank_file/another/package.json
- npm_and_yarn/spec/fixtures/projects/npm8/path_dependency_blank_file/package-lock.json
- npm_and_yarn/spec/fixtures/projects/npm8/path_dependency_blank_file/package.json
In NPM when you add a path dependency it can result in a blank `"file:"` entry in the package-lock. The code here was taking that and calling `File.join` resulting in `/package.json` which later creates an EACCES error when it tries to write the package.json to the root directory.
It seems these blank `file:` sections are just for the parent dependency, so we can safely skip over them.
> NPM: skip blank "file:" references in path dependencies

- pub/README.md
- pub/lib/dependabot/pub/update_checker.rb
- pub/spec/dependabot/pub/update_checker_spec.rb
This implements basic security update support for Pub.
For now, it's a naive implementation that bumps to the latest available version, and then filters it out if it's vulnerable.
In other ecosystems, we only bump to the minimum version required to get a non-vulnerable version.
We're currently discussing with the `Pub` team how best to do that over in `https://github.com/dependabot/dependabot-core/issues/5391`, but that will come later.
> Add Security Update Support for Pub

- common/lib/dependabot/clients/bitbucket.rb
Closes #6216
Before my change: [ceb626f5bab804b96798bd558bdb41d07f69bfe3
](https://bitbucket.org/james-lucas/dependabot-core-reproduction/commits/ceb626f5bab804b96798bd558bdb41d07f69bfe3)
After my change: [f54e4c0ad71ccbbf9a3859c53fb81a24648a0892](https://bitbucket.org/james-lucas/dependabot-core-reproduction/commits/f54e4c0ad71ccbbf9a3859c53fb81a24648a0892)
As it says in the issue bitbucket expects the path to file in the post request (docs [here](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#application-x-www-form-urlencoded)) `file.name` does not include the path, so simply swapped to use `file.path` instead and dropped the `.start_with?("/")` as `file.path` returned the path prefixed with `/`
> fix(bitbucket): Fixed file path not correct when creating commit

- Dockerfile
https://github.com/postmodern/ruby-install/tags
This may (or may not, I'm not sure) be helpful when bumping `ruby` to `3.1.3` / upcoming `3.2`...
I figured might as well bump it.
> Bump `RUBY_INSTALL_VERSION` to `0.8.5`

- python/lib/dependabot/python/file_updater/pyproject_preparer.rb
Reported https://github.com/dependabot/dependabot-core/issues/6226 we are inadvertently updating the python project and causing the poetry resolver to change behavior based on the python version specified in `pyproject.toml`.
This change checks the existing python version specification against the python version we're going to use to see that the existing requirement is satisfied by the python version under which we're running. If the python requirement is satisfied by this version, we do not change `pyproject.toml`. This preserves the earlier behavior introduced in #6191 to widen this requirement if the repository specifies a specific python version eg. `3.10.6`. In this case we need to widen the python requirement to `~3.10` so that poetry will not error out when we try to run under …
> Check if existing python requirement is satisfied before modifying

- Dockerfile
https://github.com/hashicorp/terraform/releases/tag/v1.3.6
https://releases.hashicorp.com/terraform/1.3.6/
> build(deps): bump terraform from 1.3.5 to 1.3.6

- Dockerfile
I'm about to tackle https://github.com/dependabot/dependabot-core/issues/6046, so might as well start from the latest version of Elixir:
https://github.com/elixir-lang/elixir/releases/tag/v1.14.2
> Bump Elixir to `1.14.2`

- hex/helpers/build
Prior to Elixir `1.14.0`, we couldn't specify the `hex` version during the initial install, causing two problems:
1. Brittle code, because if the latest `hex` version was broken, we couldn't workaround it.
2. Duplicated install, wasting space and time.
We're now able to specify the version during install, so let's do that instead. Many thanks to @sorentwo for clarifying in  https://github.com/hexpm/hex/issues/962.
Additionally, when I was first looking at this code, I was very confused thinking that the line:
```shell
mix archive.install hex nerves_bootstrap --force
```
resulted in installing both `hex` and `nerves_bootstrap`, ie, we were installing it a third time. 
But after reading `mix help archive.install` I realized that the `hex` arg is simply indicating that `nerves_bootstrap` is …
> Install hex only once, the specific version we want

- bin/dry-run.rb
In https://github.com/dependabot/dependabot-core/pull/5950/, this short-circuit was moved up to skip checking for the latest version if we already know we're on the latest version. (Which is awesome! It's a great speedup)
During review, it was moved below the case for a security update, when a dep is already up-to-date but also _not_ vulnerable.
However, there's yet another case, which is where a dep is up-to-date and _also_ vulnerable. I was surprised in
https://github.com/dependabot/dependabot-core/pull/6230#discussion_r1035078282 to see that it spits out `no update needed as it's already up-to-date` when I had explicitly passed in a security advisor marking the latest version as vulnerable. It wasn't clear to me if the `dry-run` was prematurely bailing before checking for vulnerable …
> Delay short-circuit in `dry-run.rb` if `vulnerable`

- updater/lib/dependabot/file_fetcher_job.rb
We're noticing some PRs are failing to be created and have "unknown" set as the base_commit.
One way that could be happening is the `file_fetcher.commit` could be returning `nil`, which then gets set to "unknown". Then the update carries that values through the entire update posting PRs which will fail with a base commit of "unknown." We originally added the "unknown" in a few places in #5981 to fix an exception in the exception handler.
So I've removed the `|| "unknown"` and added a sanity check which will take us into the rescue. 
It seems like the only place `commit` could return `nil` is here: https://github.com/dependabot/dependabot-core/blob/db729c15d578e441825b8481ff2aa5973a5fa449/common/lib/dependabot/file_fetchers/base.rb#L88
I'm unsure why we would not want to throw in that …
> prevent "unknown" base_commit SHA from failing PR creation

- Dockerfile
Let us use whatever version comes with our Ruby.
> No need to install RubyGems explicitly

- python/lib/dependabot/python/update_checker.rb
We need to handle socket errors as well as timeouts to allow poetry updates to continue if pypi.org is unavailable.
> Rescue socket errors for poetry library detection

- common/lib/dependabot/shared_helpers.rb
- updater/lib/dependabot/updater.rb
So that we get proper differentiation of exceptions according to the subprocess that failed to run.
Sentry-raven will look into `#raven_context` of the passed exception and deep merge it into the passed context. However, the passed exception here is `SubprocessFailed` which does not define any `raven_context`. It's `HelperSubprocessFailed` defining it, so we should pass over that information to `SubprocessFailed`.
This is what I meant at https://github.com/dependabot/dependabot-core/pull/6253#discussion_r1040094395.
Completely untested.
> Pass `raven_context` to Sentry on failed subprocess exceptions

- cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
- cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
- common/lib/dependabot/shared_helpers.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
For dynamic commands including things like the name of a dependency, we want to make sure we aggregate all errors together, no matter what the name of the dependency is.
> Improve subprocess failed error aggregation

- common/lib/dependabot/clients/github_with_retries.rb
- common/spec/dependabot/clients/github_with_retries_spec.rb
Same as #4964 but for the read timeout.
We'd like to bump the read timeout up a bit to fix some timeout issues, so making it configurable with an environment variable.
> make Octokit read_timeout configurable

- cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
- cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
- common/lib/dependabot/file_updaters/vendor_updater.rb
- common/lib/dependabot/shared_helpers.rb
- github_actions/lib/dependabot/github_actions/update_checker.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
- terraform/lib/dependabot/terraform/file_updater.rb
- updater/lib/dependabot/updater.rb
This PR removes most of my recent changes 😆
Sentry groups events by stacktrace, and now we have a stacktrace for subprocess failed errors, so I believe Sentry should be able to group properly by default?
Also, I believe this is more correct because the same command may end up being run in different code locations, and those would be different errors.
> Remove no longer needed custom fingerprints

- github_actions/lib/dependabot/github_actions/file_parser.rb
- github_actions/spec/dependabot/github_actions/file_parser_spec.rb
- github_actions/spec/fixtures/workflow_files/docker_reference.yml
Dependabot currently supports version updates for Actions that are referenced as a GitHub repository. There is a [feature request](https://github.com/dependabot/dependabot-core/issues/5819) to support image/container URLs in GitHub Actions, which will require checking which versions of the Action are available on the registry.
In the mean time, Dependabot should stop trying to parse these URLs as a reference to a GitHub repo and ignore them.
This PR accomplishes this by anchoring the `GITHUB_REPO_REFERENCE` regex to the start of the line.
> Ignore URLs in Actions

- composer/lib/dependabot/composer/metadata_finder.rb
- composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
- composer/spec/dependabot/composer/metadata_finder_spec.rb
- composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb
- composer/spec/dependabot/composer/update_checker_spec.rb
Per https://github.com/dependabot/dependabot-core/issues/3010:
> Note that you currently use the packagist.org domain rather than the
> repo.packagist.org domain, which forbids you from using the official
> metadata mirrors. If dependabot runs in a US-based datacenter, using
> the repo.packagist.org domain would allow you to hit the mirror in
> Montreal instead of hitting a server in Europe, improving latency.
> Doing that switch is unrelated to the v1 vs v2 metadata change though
> (both are mirrored by packagist).
So this switches the two places we call out to `packagist.org` to use the new domain.
> Switch to `repo.packagist.org` to allow mirrors

- composer/lib/dependabot/composer/update_checker/version_resolver.rb
These error messages should have their URL creds stripped before reporting them.
Also, from a GitHub security perspective, these creds never even make it to `dependabot-core` since we use a separate proxy for handling credentials... so this only affects users running `dependabot-core` on their own.
> Strip out URL credentials when reporting composer errors

- common/lib/dependabot/clients/bitbucket.rb
- common/spec/dependabot/clients/bitbucket_spec.rb
- common/spec/fixtures/bitbucket/current_user_no_access.json
If an access token is used that does not have access to the current_user endpoint, the default_reviewers method fails.
This PR prevents this failure.
See https://github.com/dependabot/dependabot-core/pull/6166#issuecomment-1338643047
> [Bitbucket] Handle Unauthorized error on current user endpoint

- bundler/lib/dependabot/bundler/metadata_finder.rb
- bundler/spec/dependabot/bundler/metadata_finder_spec.rb
- composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
- composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
More fixes like #6304. 
We want to do exact matches on hostname rather than substring match to avoid security issues.
> fix hostname matching to be exact to avoid security issues

- Dockerfile
dependabot-action runs as root because it has to run `update-ca-certificates` which requires root access. By granting the `dependabot` user access to install certificates we can stop running as the root user, improving security of the container.
The `dependabot` user having write access to the certificates is not a problem since anyone able to execute commands on the container would be able to ignore certificate errors anyway.
I've tested this with the CLI and it works https://github.com/dependabot/cli/pull/46
> fix running as root in dependabot-action

- Dockerfile.updater
As part of bringing `updater` into `core`, we stopped running as `root`.
Now:
1. base core Dockerfile flips to [`USER dependabot`](https://github.com/dependabot/dependabot-core/blob/6d1c083a7e1d244096b024f255cea5eb9c232358/Dockerfile#L266) near the end 
2. Updater Dockerfle has [`FROM dependabot/dependabot-core:$OMNIBUS_VERSION`](https://github.com/dependabot/dependabot-core/blob/6d1c083a7e1d244096b024f255cea5eb9c232358/Dockerfile.updater#L2)... buildkit inherits the user from the previous dockerfile.
So now that `git` is running as the `dependabot` user it can access the folder `/home/dependabot/dependabot-updater/repo` owned by user `dependabot` w/o needing us to specify a `safe.directory` exclusion.
> Remove `git` workaround since no longer run as `root`

- composer/spec/fixtures/packagist_response.json
Historical context:
In https://github.com/dependabot/dependabot-core/commit/77406d5d220ce7c61c7d68d1bacb8b8fadf59277, support was added for version numbers that included a `"v"` prefix. At the time, the only packagist test fixture was this single file: https://github.com/dependabot/dependabot-core/tree/77406d5d220ce7c61c7d68d1bacb8b8fadf59277/spec/fixtures/php So to test this, Grey added a customization to force a `"v"` prefix on a version.
However, we now have a whole folder of packagist responses: https://github.com/dependabot/dependabot-core/tree/dc6584174b027b7313e1ccc92adae209417c8910/composer/spec/fixtures/packagist_responses
And several of those include `"v"` prefixes:
* https://github.com/dependabot/dependabot-core/blob/dc6584174b027b7313e1ccc92adae209417c8910/composer/spec/fixture …
> Remove superfluous `v` customization in test fixture

- composer/spec/dependabot/composer/update_checker_spec.rb
- composer/spec/fixtures/packagist_responses/monolog--monolog.json
For a few upcoming PR's, it'll be helpful if the `monolog/monolog` packagist fixture is current to match what's _actually_ returned by https://repo.packagist.org/p/monolog/monolog.json.
Initially I updated all the other fixtures as well, but the `illuminate/*` fixtures ballooned to 43+ MB... and then when I switched them to the `v2` metadata endpoint (https://github.com/dependabot/dependabot-core/issues/3010) they shrank back down due to the new minifications... so no point in adding that much cruft to our git history when I'm going to almost immediately drop it.
But the `monolog/monolog` change is necessary because I'll be updating all the tests that point at the generic `packagist_response.json` to point at this fixture... and since it already has a newer version than is in …
> Update `monolog/monolog` fixture to latest packagist response

- composer/spec/dependabot/composer/update_checker_spec.rb
- composer/spec/fixtures/packagist_responses/pear-pear.horde.org--horde_date.json
It took me a while to understand this unit test, because this package _is_ actually present on packagist: https://repo.packagist.org/p/pear-pear.horde.org/horde_date.json
However, from the associated `composer.json` fixture plus the existing fixture, it's clear that this test is checking what happens when a PEAR dependency is _not_ present on packagist.
So remove the fixture from the `packagist_responses` directory which is supposed to match what Packagist actually returns and instead hardcode the response for this single unit test to avoid confusion of future devs thinking they need to update it to match the actual packagist response.
This will make the https://github.com/dependabot/dependabot-core/pull/6315 a bit more straightforward because composer v1 doesn't know about the v2 …
> Clarify `composer` `v1` `PEAR` unit test

- common/lib/dependabot/clients/azure.rb
- common/lib/dependabot/metadata_finders/base/commits_finder.rb
Handle generation of compare path and fetching commits for Azure sources in the metadata finder for commits.
These were previously marked as `TODO`.
Fixes: #6341
> Generate compare path and fetch commits for Azure sources

- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
- common/spec/dependabot/metadata_finders/base/changelog_finder_spec.rb
- common/spec/fixtures/azure/business_files.json
Adds support for pulling files containing changelog, release notes, and upgrade notes for dependencies hosted on Azure. 
These were previously marked as `TODO`.
Fixes: #6342
> Support pulling changelog and related files from Azure based repos

- bin/dry-run.rb
I was helping a friend repro a bug, and he was using the dry-run script... when we initially grep'd for "metadata", we didn't find this `--pull-request` option, so adding it here for easier grep'ability.
> Mention `"metadata"` in `--pull-request` description

- common/lib/dependabot/metadata_finders/base/changelog_finder.rb
- common/lib/dependabot/metadata_finders/base/commits_finder.rb
- common/lib/dependabot/metadata_finders/base/release_finder.rb
We weren't providing the source here so we'd inadvertently load the metadata from github.com instead. The source provides the hostname & api endpoint to use when making requests.
codeql is flagging an issue in the changelog finder but since it's not related to this change I think we should address it in a separate PR.
> Use source for GitHub client to support fetching metadata from GHES instances

- go_modules/lib/dependabot/go_modules/file_parser.rb
- go_modules/lib/dependabot/go_modules/file_updater.rb
- go_modules/lib/dependabot/go_modules/update_checker.rb
- go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
- go_modules/spec/dependabot/go_modules/file_parser_spec.rb
- go_modules/spec/dependabot/go_modules/file_updater_spec.rb
- go_modules/spec/dependabot/go_modules/update_checker_spec.rb
This is an improved take on an [earlier spike](https://github.com/dependabot/dependabot-core/pull/5555) I did to support updating indirect dependencies in a security update. This allows updating indirect dependencies that are listed in the `go.mod` file in either version or security updates. Dependencies that are only included in the `go.sum` and not the `go.mod` still can't be updated but using the go 1.17+ `go.mod` file any used indirect dependencies should be contained in the `go.mod`.
For version updates, the default allow filter is to only update direct dependencies so indirect dependencies will only be updated if a user configures their `dependabot.yml` to do so.
A benefit over my previous attempt is that this approach maintains the indirect dependency distinction so using the …
> [gomod] Support updating indirect dependencies

- README.md
Updated to match that in the current repository's About section.
> Fix discussions feedback URL in README

- common/lib/dependabot/clients/bitbucket.rb
This should fix requests failing for URLs composed of parts where spaces might be possible
fix: #6381
> fix: make sure to escape requests

- python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
These are flagged in a newer version of Rubocop.
Splitting them out separate because I think the other Rubocop flags are false-positives and causing CI to fail, but want to isolate to only those changes, so splitting these out separate.
> Minor rubocop lints

- Dockerfile
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1660-2022-12-15
The new `cargo remove` command may be something we could leverage at some point, but for now let's just bump the version.
> Bump `rust` to `1.66.0`

- .devcontainer/devcontainer.json
This was coming up as `3.2.0`, which was inconvenient when I was trying to regenerate the `Gemfile.lock` etc... life is simpler if we pin this to match the ruby version we use in the rest of `dependabot-core` and then update it in lockstep.
> Pin codespace ruby version to match the rest of the repo

- .github/workflows/ci.yml
- Dockerfile.ci
Reverts dependabot/dependabot-core#6418
The CI only passed because it skipped everything and now I've got it running them there are some linter failures that might be due to rubocop config being in the wrong place perhaps.
Either way this will get our CI working again.
> Revert "remove Dockerfile.ci as it is redundant"

- common/spec/spec_helper.rb
In #6424 I moved the git config into the tests, but didn't realize there are some tests that run `git commit` directly like this one:
https://github.com/dependabot/dependabot-core/blob/c2b0cf8cd7d58f01565128ac68c72c4818d7edf3/common/spec/dependabot/file_fetchers/base_spec.rb#L1338-L1343
This is resulting in racy failures in CI where the git config hasn't been set globally yet.
By moving this out of the function it will run as soon as it's required which should fix that problem. It's a bit of a naive solution though so I am not opposed to other ideas.
> fix git config not present for certain tests

- Dockerfile.go_modules
- Dockerfile.updater-core
> **Note** This is a WIP, not merging into main, note the base branch above ⬆️ . 
Doing this less as a space savings (it does save some space) but more from a cache invalidation perspective. For example, when you change code in the Go ecosystem and rebuild the container it won't invalidate the base container, just the ecosystem container.
Unless of course you touch the Gemfile or gemspec which is fairly rare.
> avoid copying all code for every ecosystem into every image

- .github/workflows/ecosystem-ci.yml
- Dockerfile.updater-core
- Remove apt dependencies that are not needed for the ruby-install build
- Pass the `-j` flag to ruby-install which will build with multiple cores (I set to 4 but we might need to use 2 to match the number of cores in the Actions runner)
Also a couple of minor clean-ups.
> ecosystem-images: speed up base build

- common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
- common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
- common/spec/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer_spec.rb
Recently something changed in formatting the PR description, resulting in a mess of HTML where a nice description should be in bitbucket.
This PR changes the PR description from:
to:
> Do not convert the markdown PR description to HTML for bitbucket

- bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
- bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb
- bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_2/Gemfile
- bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_2/Gemfile.lock
- bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_2/example.gemspec
- bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_2/Gemfile
- bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_2/Gemfile.lock
- bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_2/example.gemspec
Similar to https://github.com/dependabot/dependabot-core/pull/4912 I am getting `Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound` in a Rails engine project that uses `spec.required_ruby_version = ">= 3.1"` in the `.gemspec`.
This is the specs output from running them with the included "when requiring ruby 3.2".
> Added Ruby 3.2.0 to RubyRequirementSetter version requirements

- python/lib/dependabot/python/file_updater/pipfile_preparer.rb
- python/spec/dependabot/python/file_updater/pipfile_preparer_spec.rb
- python/spec/fixtures/pipfiles/private_source_auth
Instead of filtering out private pipenv sources completely, and inserting the urls from the Dependabot credentials configuration (which removes other parts of the pipenv source configuration, e.g. the source name), only replace the url with the new authed url.
This should fix https://github.com/dependabot/dependabot-core/issues/6157
> only replace url for private pipenv source

- updater/spec/bin_run_spec.rb
Authenticate updater spec to by-pass rate limiting, otherwise it may fail randomly. For example: https://github.com/dependabot/dependabot-core/actions/runs/3949825265/jobs/6761544223.
```
Failures:
1) bin/run fetch_files completes the job successfully and persists the files
Failure/Error: expect(result).to include("Finished job processing")
expected "I, [2023-01-18T14:31:25.371276 #292]  INFO -- sentry: ** [Raven] Raven 3.1.2 configured not to captu...s:\nDependabot encountered '2' error(s) during execution, please check the logs for more details.\n" to include "Finished job processing"
Diff:
@@ -1,26 +1,51 @@
-Finished job processing
+I, [2023-01-18T14:31:25.371276 #292]  INFO -- sentry: ** [Raven] Raven 3.1.2 configured not to capture errors: DSN not set
+INFO <job_1> Starting job …
```
> Fix flaky spec failure in updater

- .github/workflows/docker.yml
Reverts dependabot/dependabot-core#6464
This didn't work, so I'll make a new workflow in a new branch to test with a temporary trigger.
> Revert "publish updater-core image"

- .github/dependabot.yml
Watch:
* https://github.com/dependabot/dependabot-core/blob/700751a4f53098b94f690564d574e65fd6a15f70/bundler/helpers/v1/Gemfile
* https://github.com/dependabot/dependabot-core/blob/700751a4f53098b94f690564d574e65fd6a15f70/bundler/helpers/v2/Gemfile
> Add Bundler native helper Gemfiles to Dependabot

- .github/workflows/ci.yml
- .github/workflows/ecosystem-ci.yml
- bin/lint
- bundler/script/ci-test
- cargo/script/ci-test
- common/script/ci-test
- composer/script/ci-test
- docker/script/ci-test
- elm/script/ci-test
- git_submodules/script/ci-test
- github_actions/script/ci-test
- go_modules/script/ci-test
- gradle/script/ci-test
- hex/script/ci-test
- maven/script/ci-test
- npm_and_yarn/script/ci-test
- nuget/script/ci-test
- omnibus/.rubocop.yml
- omnibus/script/ci-test
- pub/script/ci-test
- python/script/ci-test
- script/lint
- terraform/script/ci-test
Currently, if you introduce a style issue in one ecosystem, you'll get the same failure for all jobs of that ecosystem. I think it's better to get the failure in the lint job instead.
This PR also removes omnibus jobs, since `omnibus` has no tests and changes very rarely, so I think (even with Docker caching), they're just overhead. Instead, those few times when it does changes, run everything.
> Run RuboCop as a monorepo

- .github/workflows/docker-updater-core.yml
This deploys updater-core:latest mostly for caching purposes. It's the base for all the ecosystem images.
> workflow to deploy updater-core:latest

- updater/spec/bin_run_spec.rb
- updater/spec/fixtures/get_job.json
- updater/spec/fixtures/jobs/job_with_credentials.json
- updater/spec/fixtures/jobs/job_with_vendor_dependencies.json
In https://github.com/dependabot/dependabot-core/pull/6461, I attempted to inject environment credentials in the fixture file that `bin_run_spec.rb` uses so that the spec's requests don't get rate limited.
However, turns out credentials were not being properly picked up by the fetcher.
I think the reason is that "credentials" were located at the wrong position in the fixture file, so were getting ignored. I also corrected other fixtures with the same problem.
> Fix flaky spec failure in updater (take 2)

- updater/lib/dependabot/setup.rb
Trying out an alternative to #6282.
> Try fix in-app vs outside-app frame classification in Sentry

- .github/workflows/docker-updater-core.yml
The cache-from should come from the image in GHCR for it to work.
Also removed the `--cache-from "$BASE_IMAGE"` as it should have no effect.
> fix updater-core caching not working

- bin/ci-test
- script/_common
Per the Docker [docs](https://docs.docker.com/engine/reference/commandline/run/#-set-environment-variables--e---env---env-file):
> When running the command, the Docker CLI client checks the value the variable has in your local environment and passes it to the container. If no `=` is provided and that variable is not exported in your local environment, the variable won’t be set in the container.
So there's no need to check if an env var is set in the environment before passing it to the `docker`  command.
Conveniently, this removes some of the code throwing `shellcheck` warnings over in:
* https://github.com/dependabot/dependabot-core/pull/5820
> No need to check if env var set

- .github/workflows/eco-latest-releases.yml
Trying to track down why the ecosystem image builds aren't cached. This OMNIBUS_VERSION build arg seems like a good candidate since it would be set to the `github.sha` which changes each build, thus never able to be utilized for caching.
> fix build-arg busting the Docker cache

- bin/docker-dev-shell
If these folders are not yet created when running `bin/docker-dev-shell`, and Docker is not configured in rootless mode, then they will be created by the container with root ownership.
Make sure they are created before running the container so that permissions from the host system are inherited.
Closes #6452.
> Fix dry-run and tmp permissions

- python/lib/dependabot/python/update_checker/requirements_updater.rb
- python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
This PR adds support for the "increase-if-necessary" update strategy for Python projects following PEP621.
Fixes #6371.
> Support "increase-if-necessary" strategy on PEP621 projects

- common/dependabot-common.gemspec
- updater/Gemfile
Just curious to see what breaks if we unify our development dependencies.
> Unify development dependencies

- maven/lib/dependabot/maven/file_fetcher.rb
- maven/lib/dependabot/maven/file_parser.rb
- maven/lib/dependabot/maven/file_updater.rb
- maven/lib/dependabot/maven/update_checker.rb
- maven/spec/dependabot/maven/file_fetcher_spec.rb
- maven/spec/dependabot/maven/file_parser_spec.rb
- maven/spec/dependabot/maven/update_checker_spec.rb
During review of #6248, we noticed that Dependabot special cases the `pom_parent.xml` name as some trick to fetch parent poms. #6248 tries to preserve that, resulting in that with that PR, Dependabot can now update any pom names, except for `pom_parent.xml`.
We concluded that this "magic name" is not necessary. So this PR removes the magic and instead adds the `pom_parent.xml` to the list of "allowed names", so repositories like https://github.com/filip26/titanium-json-ld can now get updates.
I'm hesitant to add any specs over manual testing because those specs would be exercising a special case that should completely go way after we merge #6248, since that will allow any names.
> Allow updating pom's named `pom_parent.xml`

- .devcontainer/post-create.sh
I must have messed this up! Putting quotes around the asterisks prevents the globbing I was going for. Removing them fixes dependabot CLI not being installed properly in the dev container.
> fix CLI installation in devcontainer

- Dockerfile
Since https://github.com/dependabot/dependabot-core/pull/5513 I think it's no longer needed.
For running updater, Bundler 1 is not used anyways, and for running native helpers, the Bundler 1 native helper installer installs Bundler 1 to an isolated location already.
Just opening a PR so that CI can prove me wrong.
> We no longer need to install Bundler 1 globally

- common/lib/dependabot/pull_request_creator/labeler.rb
- common/spec/dependabot/pull_request_creator/labeler_spec.rb
Azure does not have centralized labels, as such none are fetched. Filtering labels in the `Labeler` results in no labels if `custom_labels` is not null. This PR removes the filtering if `source.provider == "azure"`.
Fix: #6231 
Related to: 
- https://github.com/tinglesoftware/dependabot-azure-devops/pull/348
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/317
> Remove label filter for azure

- .github/workflows/eco-branch-images.yml
- .github/workflows/eco-latest-releases.yml
- .github/workflows/eco-smoke.yml
- .github/workflows/ecosystem-ci.yml
- Dockerfile.updater-core
- bundler/Dockerfile
- cargo/Dockerfile
- composer/Dockerfile
- elm/Dockerfile
- go_modules/Dockerfile
- hex/Dockerfile
- npm_and_yarn/Dockerfile
- pub/Dockerfile
- python/Dockerfile
- terraform/Dockerfile
This breaks out:
- composer
- elm
- hex
- pub
- terraform
It also pulls a couple commonly used dependencies into updater-core.
> Breakout the remaining "helper" based ecosystems

- .github/workflows/eco-latest-releases.yml
We didn't notice this was broken because updater-core was in GHCR and was being downloaded each time. In https://github.com/dependabot/dependabot-core/pull/6495 curl was removed and moved into updater-core, so it broke the deploy when it pulled the version that didn't have curl. 
By removing the tag, it builds "latest" which gets picked up by the ecosystem image build in the next step.
> fix latest ecosystem push broken due to errant tag

- .github/workflows/eco-branch-images.yml
- .github/workflows/eco-latest-releases.yml
We're using the documented YAML values as the GHCR image names since they are the official names in dependabot.yml. This one was mistakingly named "hex" so renaming to "mix."
> rename hex image to match YAML value

- composer/helpers/v2/src/UpdateChecker.php
- composer/helpers/v2/src/Updater.php
When running the dependabot-script with `DEBUG_HELPERS=true` I saw this error:
```
PHP Deprecated:  Installer::setIgnorePlatformRequirements is deprecated since Composer 2.2, use setPlatformRequirementFilter instead. in /opt/composer/v2/vendor/composer/composer/src/Composer/Installer.php on line 1289
```
In this PR I work around the deprecations (there was one more, which was not verbose) and also added a forward compatible change to [disable the audit](https://github.com/dependabot/dependabot-core/pull/6385#issuecomment-1372922640).
Applied changes:
- Use `eventDispatcher::setRunScripts` instead of [deprecated `Installer::setRunScripts`](https://github.com/composer/composer/blob/2.5.1/src/Composer/Installer.php#L1241)
- Use `Installer::setPlatformRequirementFilter` instead of [deprecated …
> Add compatibility with composer v2.4+

- bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
Per the discussion in https://github.com/dependabot/dependabot-core/pull/3319#discussion_r599482825,
these only temporarily needed to be marked `pending` until
https://github.com/dependabot/dependabot-core/pull/3327 was merged.
From the first thread it looks like the intent was to remove the
`pending` marker, but that accidentally got overlooked.
So this removes the `pending` marker, and then fixes the failures:
1. The first was a straightforward change from method to hash value.
2. The second wasn't raising the expected error... However, this has
been true since [this code was originally committed](https://github.com/dependabot/dependabot-core/pull/3319/files#r600526250)
(once #3327 was merged to make the test work). So I deleted the test
as it added no value.
> Re-enable two pending tests

- bundler/helpers/v1/lib/functions/file_parser.rb
- bundler/helpers/v2/lib/functions/file_parser.rb
- bundler/spec/dependabot/bundler/file_parser_spec.rb
Since by definition they're at the latest version.
There were actually specs positively checking for this, but I believe they may have been an oversight. They were introduced when adding support for updating subdpendencies at
b8010392313fa97dbbdb74792e3fafc7deb35d67, and I don't think this change regresses there.
I'm not sure if this could have any bad side effect, just opening it as a draft.
Fixes #5989.
> Don't try to update path dependencies

- github_actions/lib/dependabot/github_actions/file_parser.rb
There have been a few reported issues where Dependabot is attempting to source actions incorrectly from non-github.com sources. 
Following @mctofu's advice, this implements a check and fallback so non-github sources will work, but will default to github.com if the non-github source is incorrect/inaccessible.
> Fallback to github.com for actions source

- .github/workflows/eco-fork-images.yml
This mirrors the functionality of `docker-fork-releases.yml` but for the ecosystem images. It's a workflow that we use to manually deploy fork PRs to GHCR.
> add manual workflow for deploying fork images

- python/lib/dependabot/python/update_checker.rb
- python/spec/dependabot/python/update_checker_spec.rb
This is what's normally done when updating a direct dependency through pip-compile:
* Say we have `mkdocs-material==9.0.3` in the requirements.in file.
* We'll first unlock the requirement to allow the latest version, like this: `mkdocs-material>=9.0.3,<=9.0.4`.
* Then we'll run something like `pip-compile -v --build-isolation --allow-unsafe --resolver backtracking --output-file=requirements.txt -P mkdocs-material requirements.in`.
* Then we'll look at the version of `mkdocs-material` in the new requirements.txt and we'll consider that version as the latest resolvable version.
However, if updating to 9.0.4 requires an indirect dependency to also be updated, the above `pip-compile` command won't update anything in the lockfile, since it finds an existing `requirement.txt` and is happy with …
> Let `pip-compile` unlock sub-dependencies when necessary

- bundler/spec/dependabot/bundler/update_checker_spec.rb
- bundler/spec/spec_helper.rb
This is a weird one.
Up until now, running the spec being changed here in isolation fails:
```
$ bundle exec rspec spec/dependabot/bundler/update_checker_spec.rb:1183 --order defined --format documentation
Run options: include {:locations=>{"./spec/dependabot/bundler/update_checker_spec.rb"=>[1183]}}
Dependabot::Bundler::UpdateChecker
#latest_resolvable_version
given a gem with a git source
that is not the gem we're checking
that is private
bundler v2
updates the dependency (FAILED - 1)
Failures:
1) Dependabot::Bundler::UpdateChecker#latest_resolvable_version given a gem with a git source that is not the gem we're checking that is private bundler v2 updates the dependency
Failure/Error: raise Dependabot::GitDependenciesNotReachable, bad_uris.uniq
Dependabot::GitDependenciesNotReachable: …
```
> Fix order-dependent Bundler spec failures

- gradle/lib/dependabot/gradle.rb
- gradle/spec/dependabot/gradle_spec.rb
> make gradle display_name property use full dependency name

- composer/spec/fixtures/projects/invalid_version_string/composer.json
The previous string `"^3.0|4.1.x-dev as 3.0.0"` isn't actually an invalid version... because `4.1.x-dev` can technically be an exact version number.
However, this passed unit tests just fine due to an upstream bug in `composer` which was fixed in https://github.com/composer/composer/issues/11086 / https://github.com/composer/composer/commit/8618f004f791144dc33a196a5e5346ab56f77f7b. So when we upgrade to a newer version of `composer` that includes this fix, the test will start failing.
On composer `2.4.1`, the version string `"^3.0|4.1.x-dev as 3.0.0"` throws:
```
{"error":"Invalid version string \"^3.0|4.1.x-dev\" in \"^3.0|4.1.x-dev as 3.0.0\", the alias source must be an exact version, if it is a branch name you should prefix it with dev-"}
```
Compare with `2.5.1`, where it parses that …
> Use an actually invalid version for test

- .github/workflows/eco-latest-releases.yml
I noticed in https://github.com/dependabot/dependabot-core/actions/runs/4034930902/attempts/1 that the docker image names are missing the ecosystem name. Having this correct makes it easier to update smoke tests, for example I had to copy the full image name when doing https://github.com/dependabot/smoke-tests/pull/27.
So I added it, by copying the format from the step above where we're building the `dependabot-updater image`:
https://github.com/dependabot/dependabot-core/blob/5eff30823a1eb0aba02f2267d14427a8bb547414/.github/workflows/eco-latest-releases.yml#L90-L91
I double-checked, and the summaries for `eco-branch-images.yml` and the similar action for forks already include this in their job summary: https://github.com/dependabot/dependabot-core/blob/5eff30823a1eb0aba02f2267d14427a8bb54 …
> Include ecosystem name in job summary

- Dockerfile.updater-core
During the recent Dockerfile refactoring to split into per-ecosystem, the ruby version regressed from `3.1.3` to `3.1.2`... probably because some of the changes from https://github.com/dependabot/dependabot-core/pull/6257 weren't pulled in.
So this re-applies them. I checked the other files change in that PR and they all still looked correct, this was the only file from that PR that regressed.
> Re-bump Ruby to `3.1.3` to fix regression

- Dockerfile.development
- Dockerfile.updater-core
I run into similar issues to #6534.
I investigated and found the culprit to be that `BUNDLE_PATH` is no longer set in the devcontainer so gems get installed globally, not at the path they got previously installed. So `bundle exec rspec` no longer works.
The reason is that the base Dockerfile is now multistage, and the `ENV BUNDLE_PATH` line was left behind in the builder stage, but it's no longer present in the final image.
This PR fixes the issue plus other little things I found while investigating. More details in commit messages.
Fixes #6534.
> Fix running tests in devcontainer

- maven/lib/dependabot/maven/file_fetcher.rb
- maven/lib/dependabot/maven/file_parser.rb
- maven/lib/dependabot/maven/file_updater.rb
- maven/spec/dependabot/maven/file_fetcher_spec.rb
- maven/spec/dependabot/maven/file_parser_spec.rb
- maven/spec/dependabot/maven/file_updater_spec.rb
- maven/spec/fixtures/github/contents_java_multimodule_different_pom_names.json
- maven/spec/fixtures/github/contents_java_parent_pom_custom_name.json
- maven/spec/fixtures/poms/inheritance_custom_named_parent_pom.xml
- maven/spec/fixtures/poms/inheritance_custom_named_pom.xml
- maven/spec/fixtures/poms/inheritance_pom_no_parent_with_namespace_present.xml
- maven/spec/fixtures/poms/multimodule_custom_modules.xml
- maven/spec/fixtures/poms/multimodule_custom_modules_submodule_one_pom.xml
- maven/spec/fixtures/poms/multimodule_custom_modules_submodule_three_pom.xml
- maven/spec/fixtures/poms/multimodule_custom_modules_submodule_two_pom.xml
Extended on the multi-module review support, allowing for the custom pom.xml names be used for the pom-s in child modules. With that PR they would be able to have various names, with the only limitation being that they must end with .xml. 
This PR should, hopefully, address a part of the https://github.com/dependabot/dependabot-core/issues/4425 issue.
> Add support for custom pom.xml names for the child maven modules

- .github/workflows/ci.yml
- .github/workflows/images-branch.yml
- .github/workflows/images-fork.yml
- .github/workflows/images-latest.yml
- .github/workflows/images-updater-core.yml
- .github/workflows/smoke.yml
- script/_common
- script/ci-test-updater
- script/test
Also other enhancements:
- renamed workflows to be more consistent
- added `pull=never` to run commands to ensure the tests are testing what was built
- fixed some incorrect ecosystems in workflows
> use the build scripts in the workflows

- bin/docker-dev-shell
I built the python dev container with
```
bin/docker-dev-shell python --rebuild
```
Then I built the golang one with
```
bin/docker-dev-shell golang --rebuild
```
The I wanted to use the python one again, so I run
```
bin/docker-dev-shell python
```
No rebuild because I had already built it.
But I got "no pyenv in path" error.
I figure it was because rebuilding for golang overwrote the image.
Should we built dev separate dev containers for each ecosystem? That's what I did here. I think could've passed the `IMAGE_NAME` and `CONTAINER_NAME` variables, but we probably want this to be the default and no need to make it configurable.
> Build per ecosystem dev containers

- maven/lib/dependabot/maven/file_fetcher.rb
- maven/spec/dependabot/maven/file_fetcher_spec.rb
When Dependabot needs some files to perform an update, but those files should not be updated, we normally use the `#support_file` dependency attribute. However, in this case, I think users normally configure directories for completely disjoint maven apps, so we can avoid fetching files outside of directory altogether.
> Don't fetch poms outside of configured dir

- bin/docker-dev-shell
This way we can run those unit tests as well from within the dev shell.
They'll need to be run from within the `bundler` ecosystem.
> Mount `/updater` files into `docker-dev-shell`

- Dockerfile.development
1. list packages on separate lines for easier `git blame` spelunking
2. Default to not installing recommended packages
I audited all the Dockerfiles, and this was the only one that was missing these things.
> Cleanup Dockerfile's `apt-get install` lines

- python/lib/dependabot/python/requirement_parser.rb
- python/spec/dependabot/python/file_updater/requirement_file_updater_spec.rb
- python/spec/fixtures/requirements/hashes_multiline_no_space.txt
If the hashes used line continuation right after the hash (without a space in the middle), Dependabot would generate an invalid requirements file.
Fixes #2689.
> Fix updating requirement files with multiline hashes

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
This was extracted from #6516 because this fix alone is enough to fix #6565.
I also added a spec so this one should be ready!
Closes #6565.
> Fix yarn parsing of locked dependencies with multiple requirements

- terraform/lib/dependabot/terraform/file_updater.rb
- terraform/spec/dependabot/terraform/file_updater_spec.rb
- terraform/spec/fixtures/projects/provider_version_preceed/providers.tf
The current terraform provider regex doesn't work correctly if `version` is preceeding the `source` which leads to the Runtime error mentioned in https://github.com/dependabot/dependabot-core/issues/5361.
Current regex: `((source\s*=\s*["'](registry\.terraform\.io\/)?hashicorp\/azurerm["']|\s*hashicorp\/azurerm\s*=\s*\{.*)
(?:(?!^\}).)+)`
Updated regex: `((\s*version\s=\s*["'].*["'])|(\s*source\s*=\s*["'](registry\.terraform\.io\/)?hashicorp\/azurerm["']|\s*hashicorp\/azurerm\s*=\s*\{.*)){2}`
~~At the moment this is just a first approach. I didn't take a closer look at test cases yet. I think there should be added one that covers this case at least.~~
Fix #5361
> Fix terraform runtime error if `version` preceeds `source` in `required_providers` block

- docker/lib/dependabot/docker/file_updater.rb
A helm `values.yaml` can be a complex file with nested structures, ex:
```yaml
---
service_a:
image: foo/bar:v1.2.3
````
However, a very simple values files could also contain `image` as a top level tag, ex:
```yaml
---
image: foo/bar:v1.2.3
```
Dependabot assumes there will be whitespace `\s+` before the `image:` tag, but this is not always true.
> Don't require whitespace before image tag in helm charts

- common/lib/dependabot/git_metadata_fetcher.rb
- common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb
- git_submodules/lib/dependabot/git_submodules/file_fetcher.rb
- git_submodules/spec/dependabot/git_submodules/metadata_finder_spec.rb
Support `git_submodules` from Azure DevOps. All the code was present but not set up.
Changes in #6304 and #6306 helped a great deal too in handling submodule URLs for Azure DevOps:
```bash
[submodule "another-repo"]
path = another-repo
url = https://contoso@dev.azure.com/contoso/MyProject/_git/another-repo
```
The suffix `.git` does not in Azure DevOps. For GitHub and GitLab, it works with and without the suffix hence removed it just when getting the `git-upload-pack` in `service_pack_uri(...)`. For `dev.azure.com` and `*.visualstudio.com`, this suffix is skipped.
Fixes: #6340 
Fixes: #5756
> Added support for Azure in git_submodules

- CONTRIBUTING.md
Not mentioning `bin/dry-run.rb` or the CLI yet, just focusing on removing out of date information and replacing it with how you get setup to run specs for a specific ecosystem.
> Pass on setup docs for contributing

- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
Fixes https://github.com/dependabot/dependabot-core/issues/4445
> Log when `go mod tidy` fails

- composer/spec/dependabot/composer/update_checker_spec.rb
`monolog/monolog` released a new `2.9.x` version which broke these unit
tests: https://github.com/Seldaek/monolog/releases/tag/2.9.1
A couple of things going on here:
- the native helper calls out to Packagist, and since it's not Ruby,
it can't be easily stubbed, so that's why it suddenly started picking
up the 2.9.1 release.
- However, this illustrated that I actually introduced a bug in the
tests back in https://github.com/dependabot/dependabot-core/pull/6334 / 34216d42d099c60d9d999664e4dcb956721e1c89
because anything above `1.22.0.a` should have been ignored.
- The tests were still broken because there's been a 3.0 release that
isn't resolvable because it requires PHP 8, but we're still running
PHP 7, so it exposed the bug described in: …
> Fix broken `composer` unit tests

- go_modules/helpers/go.mod
This should have been included as part of:
* https://github.com/dependabot/dependabot-core/pull/6576
Not a big deal since no functional changes, but makes it easier for us to grep/replace if it stays in sync on versions.
> Bump go.mod to 1.20

- .github/workflows/ci.yml
- python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
- python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
- python/lib/dependabot/python/file_updater/poetry_file_updater.rb
- python/lib/dependabot/python/helpers.rb
- python/lib/dependabot/python/language_version_manager.rb
- python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
- python/lib/dependabot/python/update_checker/pip_version_resolver.rb
- python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
- python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
The 4 python package managers had very nearly copy/pasted code to detect the project python version and install the correct python version. This copy/pasted code had drifted over time in some package managers (pipenv and poetry had gained some additional error handling around unsupported python versions among others). This aims to clean up the copy/pasted code and provide a new mixin module that can hold cross package manager methods to increase code reuse going forward
I implemented a new mixin module in `python/helpers.rb` and attempted to unify the behavior of detecting a project python version, verifying support for said python version in Dependabot, and getting that python version installed. Going forward this will hopefully simplify the task of changing our python installation …
> Refactor python version detection

- maven/lib/dependabot/maven/file_fetcher.rb
- maven/spec/dependabot/maven/file_fetcher_spec.rb
- maven/spec/fixtures/github/contents_java_parent_pom_custom_name_parent.json
- maven/spec/fixtures/github/parent_modules_different_artifact_pom.json
- maven/spec/fixtures/github/parent_modules_different_group_pom.json
- maven/spec/fixtures/github/parent_modules_different_version_pom.json
- maven/spec/fixtures/github/parent_modules_implicit_parent_pom.json
- maven/spec/fixtures/github/parent_modules_no_parent_pom.json
- maven/spec/fixtures/github/parent_modules_parent_of_pom_with_parent.json
- maven/spec/fixtures/github/parent_modules_pom_with_parent.json
- maven/spec/fixtures/github/parent_modules_root_pom.json
Reverted the fix in #6557 
Updated the parent fetching logic:
- added a check that we only try to fetch parent `pom.xml` when the `parent` node is defined in the file
- added additional checks when we fetch parent file to validate its `groupId`, `artifactId` and `versionId` against the ones provided in its "child" `pom.xml`
- additionally added the cases for the empty `groupId` in case the `groupId` of the parent `pom.xml` is inherited from its own parent
- covered the logic with tests and amended the old tests which have demonstrated incorrect behavior but worked fine before the logic adjustment
> Adjust parent pom fetching logic

- python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
This already happens as part of `install_required_python`: https://github.com/dependabot/dependabot-core/blob/26e670a2bdc6833efe9421979aa121b6a3f139d1/python/lib/dependabot/python/file_updater/pipfile_file_updater.rb#L306-L311
Which is called right above the deleted code:
https://github.com/dependabot/dependabot-core/blob/26e670a2bdc6833efe9421979aa121b6a3f139d1/python/lib/dependabot/python/file_updater/pipfile_file_updater.rb#L200
This probably was a simple oversight of the refactoring in https://github.com/dependabot/dependabot-core/pull/6609.
> Remove duplicate `git init` call

- composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb
The upstream issue was just closed:
* https://github.com/cweagans/composer-patches/issues/338#issuecomment-1421336293
Effectively it's a "wontfix" because patch data isn't going to be re-applied to `composer.lock`:
* https://github.com/composer/composer/discussions/11295#discussioncomment-4869345
Instead, `composer-patches` will add a new lockfile called `patches.lock`. Supporting that might make sense as a feature request down the road, but for now let's remove the `pending` test since that behavior is never coming back.
> Remove spec for composer patches due to change upstream behavior

- npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
- npm_and_yarn/spec/fixtures/github/package_json_with_path_content_file_relative_outside_repo.json
Otherwise we hang infinitely.
Fixes https://github.com/dependabot/dependabot-core/issues/5945.
Needs tests and I haven't even run npm CI locally either, so just opening a WIP for now.
> Detect path dependencies falling outside of repository and error out

- bin/docker-dev-shell
- docker/lib/dependabot/docker/utils/credentials_finder.rb
- docker/spec/dependabot/docker/utils/credentials_finder_spec.rb
This enables the AWS ECR client to look for creds in default fallback locations if they are not explicitly provided.
NOTE: This will _only_ affect folks running `dependabot-core` by themselves outside of the Dependabot Service offered by GitHub.
According to the [AWS ECR SDK Client docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECR/Client.html#initialize-instance_method):
> When `:credentials` are not configured directly, the following locations will be searched for credentials:
> * `Aws.config[:credentials]`
> * The `:access_key_id`, `:secret_access_key`, and `:session_token` options.
> * `ENV['AWS_ACCESS_KEY_ID']`, `ENV['AWS_SECRET_ACCESS_KEY']`
> * `~/.aws/credentials`
> * `~/.aws/config`
The flow here of picking what creds to prioritize is important to get correct. We have …
> Enable AWS ECR client to look for creds in default fallback locations

- docker/lib/dependabot/docker/update_checker.rb
- docker/spec/dependabot/docker/update_checker_spec.rb
User may have all three ignores `["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]` configured, but will still want digest updates if pinned to specific digests.
This PR fixes that.
Closes #1971.
> Don't raise all versions ignored error if digest can be updated

- bin/docker-dev-shell
As _deivid-rodriguez pointed out in https://github.com/dependabot/dependabot-core/pull/6622#discussion_r1102041336, `bin/docker-dev-shell` is intended for dev work, including running tests. Plumbing AWS creds through from outside the dev container reduces the reproducability.
So removing this.
For entrypoints intended for prod (such as `dependabot-script`), IMO we _should_ plumb AWS creds through for a sane default, but anyone using `bin/docker-dev-shell` in prod is doing it wrong...
> Don't plumb AWS creds through dev environment

- python/lib/dependabot/python/update_checker.rb
- python/lib/dependabot/python/update_checker/requirements_updater.rb
- python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
- python/spec/dependabot/python/update_checker_spec.rb
```
$ bin/dry-run.rb pip sanderr/inmanta-module-factory
=> dumping fetched dependency files: ./dry-run/sanderr/inmanta-module-factory/
=> updating 1 dependencies: more-itertools
=== more-itertools (8.14.0)
🌍 --> GET https://pypi.org/simple/more-itertools/
🌍 <-- 200 https://pypi.org/simple/more-itertools/
=> latest available version is 9.0.0
🌍 --> GET https://pypi.org/simple/more-itertools/
🌍 <-- 200 https://pypi.org/simple/more-itertools/
=> latest allowed version is 9.0.0
🌍 --> GET https://pypi.org/pypi/lorem/json/
🌍 --> GET https://pypi.org/pypi/lorem/json
🌍 <-- 200 https://pypi.org/pypi/lorem/json
🌍 <-- 301 https://pypi.org/pypi/lorem/json/
=> requirements to unlock: update_not_possible
🌍 --> GET …
```
> Implement `widen` strategy for Python libraries with a requirements file

- gradle/lib/dependabot/gradle/file_updater.rb
- gradle/spec/dependabot/gradle/file_updater_spec.rb
- gradle/spec/fixtures/buildfiles/multiple_configurations.gradle
When multiple configurations include the same dependency, only one would be updated.
Fixes #6598.
> Fix build.gradle files missing some updates

- updater/lib/dependabot/updater.rb
This PR removes one use of `shuffle` on the dependencies list.
EDIT: Thanks to some detective work from @deivid-rodriguez and @mctofu, we've verified the original duplication was unintentional, so we can clean this up with confidence.
----
In addition to the top-level call when we actually execute the check-and-create, we also shuffle within the `Updater#dependencies` method itself here:
https://github.com/dependabot/dependabot-core/blob/afbc9fb35e40961ffd7cf17f2891608f49310b9c/updater/lib/dependabot/updater.rb#L626-L630
Immediately after this, we then attempt to pull vulnerable dependencies to the top of the list:
https://github.com/dependabot/dependabot-core/blob/afbc9fb35e40961ffd7cf17f2891608f49310b9c/updater/lib/dependabot/updater.rb#L637-L640
The second shuffle will undo this but it …
> The updater shuffles dependencies once

- README.md
We've broken the large updater image out into smaller images and thus some of the scripts have changed. 
Here's a first pass at updating the README to capture those changes.
> update readme to include new ecosystem image info

- .github/workflows/smoke.yml
- npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
If a dependency has a bad checksum, we fail to `yarn install --mode=skip-build` even when yarn cache is not necessary because of not being on any situation needing the cache.
We can fix this by explicitly configuring a global cache the first time we detect we won't need it because otherwise yarn runs may generate a cache and result in further commands running in `--mode=skip-build`.
Closes #6432.
~Closes #6565.~ Already closed by #6587.
Closes #6003.
> Fix update to lockfile on yarn berry projects with workspaces

- bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
- bundler/spec/dependabot/bundler/file_updater/lockfile_updater_spec.rb
- bundler/spec/fixtures/projects/bundler1/multiple_path_gems/Gemfile
- bundler/spec/fixtures/projects/bundler1/multiple_path_gems/Gemfile.lock
- bundler/spec/fixtures/projects/bundler1/multiple_path_gems/vendor/couchrb/couchrb.gemspec
- bundler/spec/fixtures/projects/bundler1/multiple_path_gems/vendor/net-imap/net-imap.gemspec
- bundler/spec/fixtures/projects/bundler2/multiple_path_gems/Gemfile
- bundler/spec/fixtures/projects/bundler2/multiple_path_gems/Gemfile.lock
- bundler/spec/fixtures/projects/bundler2/multiple_path_gems/vendor/couchrb/couchrb.gemspec
- bundler/spec/fixtures/projects/bundler2/multiple_path_gems/vendor/net-imap/net-imap.gemspec
If Bundler was unable to infer the name of a gemspec, it would use the version of the first parsed path gemspec, which... is not correct.
This change makes Bundler try harder to find the gem name by also considering the name of the gemspec file, which in most cases matches the gem name.
Fixes #6627.
> Fix lockfile incorrectly updated with unrelated path gem version

- composer/spec/fixtures/projects/provided_dependency/composer.json
The failure seems to be due to this change: https://github.com/php-http/discovery/pull/208
Before, discovery was not providing php-http/client-implementation, but now that it is it's taking precedence in our [native helper](https://github.com/dependabot/dependabot-core/blob/e3875084e8787f7ec1c854128ef0b6b9078c877f/composer/helpers/v2/src/UpdateChecker.php#L120), returning a version of * which is invalid to our Version parser, causing the test to fail.
So I've switched to use `guzzle6-adapter` which doesn't seem to pull in `discovery`.
> fix Composer CI due to "discovery" dependency change

- Dockerfile.updater-core
The Bundler ecosystem is evading the smoke test cache after a while, causing failures. This is probably due to how Bundler caches dependency data. When we run `bundle install` during a build, it stores a cache of the versions it fetched under `~/.bundle`. After a day or so this is out of date and Bundler attempts to get new data, probably sending new headers to do so, avoiding the cache.
So by removing the Bundler cache during image build, our tests should always make the same call to get fresh data instead of starting with a snapshot at the time of build.
An outstanding question is whether this is a good idea outside of testing. With this change, updates become more deterministic, so I think it's worth the extra download cost it incurs. Also we don't need to make a special case in tests …
> remove bundler cache after installing

- common/lib/dependabot/shared_helpers.rb
When debugging a crash, you can normally figure it out from the backtrace, but this makes it easier. And you may not always be debugging a crash, in which case a command like `ruby run.rb` is pretty contextless without the function to be run.
> Log function too when debugging native helpers

- .github/workflows/smoke.yml
I noticed some smoke tests were skipping incorrectly due to their name not matching up with the filter name. This brings it in-line with `ci.yml`.
> fix some smoke tests skipping due to filters

- github_actions/lib/dependabot/github_actions/file_fetcher.rb
- github_actions/lib/dependabot/github_actions/file_parser.rb
- github_actions/spec/dependabot/github_actions/file_parser_spec.rb
- github_actions/spec/fixtures/workflow_files/workflow_reusable.yml
- github_actions/spec/fixtures/workflow_files/workflow_semver_reusable.yml
This PR fixes #4327
It changes how the "uses" key is searched for and found.  Reusable workflows do not have the "steps" key, this fix no longer make the assumption that a "steps" key exists, however it still processes the "steps" key if it does exist.  
The fix also allows for a mix of reusable or standard workflows to exist in the same directory.
New logic to find and update "uses":
Check for "jobs" key and provide that section to the search.
Recursively search for "uses" key.
If it is a hash and has "uses" key, then add the "uses" value to the `found_uses` array.
If it is a hash and has "steps" key, then send the "steps" value recursive search function.
If neither "steps" or "uses" are found, then send each item in the current hash/array into the recursive search function.
Once the …
> Allow updating GitHub reusable workflows

- Dockerfile.development
- bin/docker-dev-shell
- updater/README.md
Supersedes https://github.com/dependabot/dependabot-core/pull/6626
This updates the `Dockerfile.development` with the additional requirements needed to bundle and test the `updater/` project inside the `bin/docker-dev-shell` and aligns the README with this workflow.
> Properly support the Updater project in the dev shell

- docker/lib/dependabot/docker/version.rb
- docker/spec/dependabot/docker/version_spec.rb
We need to be able to see if an update was a major bump for a feature we're working on. So I wanted to use `segments` to do that. Something like `if before.segments.first == after.segments.first` would tell us it was not a major bump.
The Docker Version class segment method had a NilClass error due to the special handling of Java versions. I've hooked it up simply to return the `@release_part`'s segments since that's the part we care about at the moment.
> fix segments not working for Docker ecosystem

- go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
- go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
- go_modules/spec/dependabot/go_modules/version_spec.rb
Currently Dependabot doesn't touch Go pseudo-versions, they're handled as if they were pinned on a revision like other ecosystems.
However, the Go tooling generates pre-release identifiers that are semver compliant. That means Dependabot does have enough information to bump a pseudo-version like `v1.0.1-<date>-<hash>` to a tagged `v1.0.1`. 
This PR allows the update to continue, and adds the pseudo-version to the list of candidates to avoid downgrades, in the event the user is pinned to a newer version than is currently released.
This will *not* update the dependency to a non-released pseudo-version, only pseudo to released.
Note: I will need to update the Go smoke test.
> Go: update psuedo-versions to released versions

- python/Dockerfile
- python/helpers/build
- python/lib/dependabot/python/python_versions.rb
- python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
Updates default versions to 3.10.10 and 3.11.2. Things moved around a bit since I opened #6375 and #6404 but I think these changes cover it.
> Use latest Python 3.10 and 3.11 as of 2023-02-23

- go_modules/lib/dependabot/go_modules/update_checker.rb
- go_modules/spec/dependabot/go_modules/update_checker_spec.rb
I noticed one of my personal Go repos was still not getting the security update for golang.org/x/net after #6713. 
The issue is that the GitCommit checker is identifying some Go pseudo-versions as Git SHAs (like `v0.0.0-20180826012351-8a410e7b638d`) but others are not Git SHAs (like `v0.0.0-20201021035429-f5854403a974`). There must be a bug in this code identifying dependency sources as git: 
https://github.com/dependabot/dependabot-core/blob/cddd02aa8b8dc44ab0580b139c8ceafb45e97aa2/go_modules/lib/dependabot/go_modules/file_parser.rb#L38-L42
That causes `checker.vulnerable?` to return false here: 
https://github.com/dependabot/dependabot-core/blob/7196bb00a2e52d0d2ed167d1964ddab7e88dc1fe/common/lib/dependabot/update_checkers/base.rb#L137-L138
Which then leads to the "no longer vulnerable" …
> fix Go "no longer vulnerable" due to bad SHA detection

- common/lib/dependabot/file_parsers/base/dependency_set.rb
- common/spec/dependabot/file_parsers/base/dependency_set_spec.rb
- github_actions/lib/dependabot/github_actions/update_checker.rb
- maven/spec/dependabot/maven/file_parser_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb
- nuget/spec/dependabot/nuget/file_parser_spec.rb
> Fix updating GitHub Actions & Dockerfiles with mixed versions

- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
We see a large amount of "unknown errors" in the Go ecosystem. Really these aren't unknown, but resolvability issues. So I've added additional error regexes here which will classify them more accurately.
> Go: handle more resolvability errors

- common/lib/dependabot/file_fetchers/base.rb
- go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
Continuing the effort from #6730 to categorize known errors that we can't fix.
I'm seeing "package \S+ is not in GOROOT" quite a bit which indicates a relative import path that is not present. For instance, the package is named `web` and there's an import `web/package` where the directory `package` doesn't exist. This might be because they have generated code that isn't checked in, which is against Go conventions, so I don't think we need to try to support it: 
> once the file is generated (and tested!) it must be checked into the source code repository to be available to clients
> --https://go.dev/blog/generate
Also fixing a NilClass bug introduced in https://github.com/dependabot/dependabot-core/pull/6172. The original intent was to check for the match in this `unless`, so when an error …
> Go: handle missing import error and submodule cloning failure error

- github_actions/lib/dependabot/github_actions/file_parser.rb
- github_actions/spec/dependabot/github_actions/file_parser_spec.rb
- github_actions/spec/dependabot/github_actions/file_updater_spec.rb
- github_actions/spec/fixtures/workflow_files/workflow.yml
- github_actions/spec/fixtures/workflow_files/workflow_monorepo.yml
The change in Dependency combine logic at #6082 surfaced a bug where if a Github Action is referencing two different branches in the same workflow, Dependabot would create a PR unifying it to a single branch, while is not what the user wants.
The fix is to ignore any `uses:` references which include a reference that should not be updated, like a branch name not named like a version (like `master` or `stable`).
In addition to fixing this bug, this change also allows Dependabot to create PRs for mixed situations like the following, where the version is updated and the others are left alone:
```yaml
uses: dtolnay/rust-toolchain@master
uses: dtolnay/rust-toolchain@stable
uses: dtolnay/rust-toolchain@1.42
```
or the following, where the SHA is updated and the others are left alone:
```yaml …
```
> Don't ever update GitHub Actions unless they are actually pinned 

- updater/lib/dependabot/setup.rb
It looks like this workaround was added around six years ago when Dependabot ran on Heroku and needed to override some changes from its buildpack.
I don't believe we need this anymore and should clean it up as a refers to a long gone runtime environment - that said, I'm not sure removing it is the most ideal outcome.
Having it live in a setup block for the Updater definitely feels wrong as we should either not have this or have it in the initialisation hooks for the `bundler/` gem, similar to how we use `Dependabot::Utils.register_always_clone` to set ecosystem config.
@deivid-rodriguez do you have any thoughts on this?
> Remove a Heroku workaround from early implementation

- npm_and_yarn/helpers/lib/yarn/subdependency-updater.js
- npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
- npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
Previously the logic attempted fresh installs of package@version and copied the generated lockfile contents across to force a dependency realignment.  This was sometimes flawed as "version" could somehow (didn't figure this out) sometimes be a pinned version, resulting in a noop lockfile change for a dependency bump that was definitely possible.
The new logic is much more straightfoward IMO, we take the existing lockfile.  Remove all entries that map to the given package that also resolve to the suspect version and then just run "yarn" again and take the resultant lockfile.
This logic is mirroring my implementation in `uuaw` --> https://github.com/MarshallOfSound/uuaw which aimed to automatically fix `yarn audit` security alerts which dependabot failed to solve automatically.  I figured …
> fix: improve yarn@^1 subdependency update success

- updater/spec/dependabot/updater_spec.rb
While trying to make changes to the updater logic, it's become apparent that our tests have become difficult to work with. This is a first pass at inlining setup so that tests can be reasoned about as individual units.
The approach here is generally:
* Remove `let` statements which are not overridden
* Stub calls to `Dependabot.logger`
* Exract setup of `job`, `service` and `updater` objects into callable methods
* Use :point_up: to bring setup into individual specs
> Inline updater specs

- go_modules/lib/dependabot/go_modules/file_fetcher.rb
Fixes NoMethodError error introduced just now in #6658
```
NoMethodError
undefined method `content' for nil:NilClass
"gomod" => go_mod.content.match(/^go\s(\d+\.\d+)/)&.captures&.first || "unknown"
```
This is being caused by misconfigured dependabot.yml where `go.mod` is not present in the directory. I'm kind of surprised we don't raise an exception sooner since it's listed in `required_files_in?`.
> Go: fix NilClass error when directory doesn't have a go.mod file

- updater/lib/dependabot/service.rb
- updater/lib/dependabot/updater.rb
- updater/spec/dependabot/service_spec.rb
- updater/spec/dependabot/updater_spec.rb
This should make it a little easier to diagnose failures without needing to also consult the Dependabot error UIs. It's also handy for figuring out which dependencies failed when theres a long list of dependencies to update.
Adds two potential summaries at the end of the job:
For errors that aren't specific to a dependency:
```
+--------------------+
|    Errors          |
+--------------------+
| job_repo_not_found |
+--------------------+
```
For errors updating a particular dependency:
```
+-------------------------------------+
|    Dependencies failed to update    |
+---------------------+---------------+
| best_dependency_yay | unknown_error |
+---------------------+---------------+
```
> Include summary of errors at the end of job output

- bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
- composer/spec/dependabot/composer/update_checker_spec.rb
- gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb
- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
Most of our `pending` tests have associated code comments. However, they're only visible when viewing the raw source, not when running `rspec`.
So this makes it visible when running tests why a particular test is pending.
> Annotate `pending` tests with comments

- npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
This should be `pending` rather than commented out.
Long term we can probably [stub in a super short timeout via a custom `.yarnrc` file](https://azureossd.github.io/2022/09/10/fix-yarn-ESOCKETTIMEDOUT-with-.yarnrc-configuration-file/) but this is good enough for the first iteration here.
> Switch commented out test to pending

- composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
This was commented out because it had to wait til `composer` timed out, which defaults to 300 seconds (5 mins).
However, `composer` supports setting a custom timeout using the env var `COMPOSER_PROCESS_TIMEOUT`.
So set a much lower timeout and re-enable the test. When I first re-enabled the test, I discovered a code bug. Furthermore, once that was fixed by https://github.com/dependabot/dependabot-core/pull/6435, I discovered a bug in the test itself, so we should keep this enabled if we have any hope of deriving value from it.
> Mark test `pending` for `composer` `Dependabot::PrivateSourceTimedOut`

- common/lib/dependabot/file_fetchers/base.rb
- common/spec/dependabot/file_fetchers/base_spec.rb
- updater/lib/dependabot/file_fetcher_command.rb
- updater/spec/dependabot/file_fetcher_command_spec.rb
Failures from cloning a repo assume a repo access error by default. This causes confusion when the error is something else. I suspect OutOfDisk is the culprit for an issue I'm looking into so this adds detection for that.
> Attempt to detect OutOfDisk errors when cloning repos

- docker/lib/dependabot/docker/file_updater.rb
- docker/spec/dependabot/docker/file_updater_spec.rb
- docker/spec/fixtures/helm/yaml/mixed-image.yaml
We are able to parse image dependencies like this from a helm file:
```
image: nginx:1.14.2
```
But when we update a helm file we expected it to be formatted as:
```
image:
repository: nginx
tag: 1.14.2
```
This change attempts to perform the update with both formats for helm files.
Is there an official name for these different ways of specifying a docker image? I don't know the specifics here but this fixes an issue that came in through support.
> Support updating docker format image dependencies in a helm values file
