dependabot/dependabot-core

go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb

This being out of date caused a [CI failure](https://github.com/dependabot/dependabot-core/actions/runs/4346810196/jobs/7594010245) in another branch. It'd be great to make this a static target, but I'm not sure what our process is for locking the version down.

Bump latest version to reflect current release

---

python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb

These currently end up in the unknown_error category so this provides easier visibility to the user.

Detect when pip compile hits memory or disk limits

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/updater.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/dependency_change_spec.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/updater_spec.rb

This PR introduces a new [Dependabot::DependencyChange](https://github.com/dependabot/dependabot-core/pull/6792/files#diff-1df7c2253c7a813b8528a05529986fe5d2f7ac95cf2e9d5d6c65db463fc28aba) class which wraps a set of `Dependabot::Dependency` and `Dependabot::DependencyFile` objects which constitute the outcome of a `Dependabot::Updater` operation.
As part of the [prototype](https://github.com/dependabot/dependabot-core/pull/6663/files#diff-1f8c3901647148d6f9fbda3a5c943490beb28c1291f21a3b6713471e0c39902bR42-R62) effort, Rubocop flagged the growing number of parameters being passed down into the API Client - effectively the 'output' class for the Updater - when we started adding in new placeholders for the concept of a "Group Rule".
This problem indicates we have a missing abstraction …

Introduce Dependabot::DependencyChange as a wrapper for updater output plus metadata

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/base_command.rb
updater/lib/dependabot/environment.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/logger/formats.rb
updater/lib/dependabot/setup.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater.rb
updater/spec/dependabot/environment_spec.rb
updater/spec/dependabot/job_spec.rb
updater/spec/dependabot/updater_spec.rb

This branch extracts a couple of tidy ups from some ongoing work to prepare the Dependabot::Updater to receive our [prototype grouped updating strategy](https://github.com/dependabot/dependabot-core/pull/6663).
While splitting the updater up into discrete classes, there were two cross-cutting pain points:
- Having pass _both_ a Job object and the job_id is counter productive and it leaves us reaching back to the `Dependabot::Environment` object as we start to extract code. 
- This is likely going to make compartmentalisation worse as the `Environment` object should never be part of Core but some of the Updater strategies we are extracting _should_ become Core-bound eventually so ecosystems can override them
- Solution: Let's just allow a Job to know its id?
- Writing to the …

Extract log helper methods into a Logger::Formatter, Push the `job_id` into the Job object

---

.github/workflows/smoke.yml
common/lib/dependabot/pull_request_creator/message_builder.rb
updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/dependency_change_spec.rb

The DEFAULT_GITHUB_REDIRECTION_SERVICE has been the default argument for PullRequestCreator, but I think it can also serve the same purpose in PullRequestCreator::MessageBuilder.

Rely on previously-defined constant

---

updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/dependency_change_spec.rb

This fixes a bug introduced in #6792.
The newly introduced `DependencyChange` class made an assumption that any content created as result of a Job which had  `updating_a_pull_request?` should not generate a `pr_message` object as the ApiClient historically did not accept a `pr_message` argument.
In reality, we have this scenario when `updating_a_pull_request?` is true to consider:
https://github.com/dependabot/dependabot-core/blob/a196e04c7f7ef580fdc1da66952c87e53cfb6da3/updater/lib/dependabot/updater.rb#L196-L201
In a scenario where we close the existing PR and create a new one, the `nil` PR message blocks the API accepting the request.

Do not nil out the PR message for jobs updating a PR

---

gradle/lib/dependabot/gradle/file_fetcher.rb
gradle/lib/dependabot/gradle/file_parser.rb
gradle/lib/dependabot/gradle/file_updater.rb
gradle/spec/dependabot/gradle/file_fetcher_spec.rb
gradle/spec/dependabot/gradle/file_parser_spec.rb
gradle/spec/dependabot/gradle/file_updater_spec.rb
gradle/spec/fixtures/github/content_gradle_toml.json
gradle/spec/fixtures/github/libs_versions_toml.json
gradle/spec/fixtures/version_catalog_file/libs.versions.only.libraries.toml
gradle/spec/fixtures/version_catalog_file/libs.versions.only.plugins.toml
gradle/spec/fixtures/version_catalog_file/libs.versions.overlapping.toml
gradle/spec/fixtures/version_catalog_file/libs.versions.toml

Hello from the GitHub [Android mobile team](https://github.com/mobile)!
As part of a client apps hackathon we decided to give it a shot and add [version catalog](https://docs.gradle.org/current/userguide/platforms.html) support for Gradle projects.
This functionality has been requested by some users here: https://github.com/dependabot/dependabot-core/issues/3121, and we are planning to start using version catalog as well as soon as Dependabot supports it :P.
We have added support for version catalogs defined using a `toml` file ([more info](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml)), for libraries and plugins using value versions and referenced versions, so this changes add support for **a** toml file like:
```
[versions]
corektx = …
```

Add version catalog support for Gradle

---

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
python/spec/fixtures/pyproject_files/poetry_exact_requirement.toml

Resolves this error when checking for updates when a specific python version is pinned in pyproject.toml. We want it to match the version that pre-installed with the updater rather than dynamically installing a different patch release.
```
Dependabot::SharedHelpers::HelperSubprocessFailed: The currently activated Python version 3.11.2 is not supported by the project (3.11.1). Trying to find and use a compatible version.
Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
./lib/dependabot/python/update_checker/poetry_version_resolver.rb:349:in `run_poetry_command'
./lib/dependabot/python/update_checker/poetry_version_resolver.rb:167:in `run_poetry_update_command'
```

Adjust poetry/pyproject python version to match installed in version resolver

---

updater/lib/dependabot/job.rb

Fixes a bug introduced in #6810 
The modified code in this PR attempted to retrieve the `credential-metadata` using the wrong key name by confuting the pre- and post-standardisation use of kebab- and snake-case respectively, i.e. `credential_metadata` instead.
This change reverts to the original call order to ensure that the retrieval happens after standardisation to guard against any future changes to key manipulation leaving the credential_metadata clause out of alignment with the rest of the payload.

Fix retrieval of private registry metadata from the Job definition

---

updater/lib/dependabot/job.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/job_spec.rb

Fast-follow on https://github.com/dependabot/dependabot-core/pull/6843
The previous fix only remediated for the wrong key case being used, but by regressing the call order it didn't account for the fact that the `slice` operation no longer includes the `credentials` key.
This is a split-the-difference fix which uses the new call order so the `credentials` are injected to a filtered attribute list that uses a single `PERMITTED_KEYS` list but are pulled from a version of the hash that is pre-filtered **and** standardised.

Fix the call order when pulling through cred metadata

---

updater/lib/dependabot/base_command.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/updater.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/updater_spec.rb

This is another clear-the-way PR for #6663 [[Prototype] Generating grouped update PRs](https://github.com/dependabot/dependabot-core/pull/6663).
Previous PR: https://github.com/dependabot/dependabot-core/pull/6810
The `Dependabot::Updater` class implements quite a lot of private methods to assist error handling. As we start to break the updater out into individual strategy classes which handle discrete operations, many of them need to share these methods.
This PR clears the way to start breaking the logic apart primarily via three changes:
- Stop maintaining a cache of errors inside `Dependabot::Updater`. This isn't used in any significant way, we can just use `Dependabot::Service#errors` as a substitute in the one place we need to check if any errors have happened.
- Prefer to use …

[Updater] Prefer to use `Dependabot::Service` directly and as an application error reporter

---

common/spec/dependabot/pull_request_updater/github_spec.rb

Oktokit began URL escaping the branch name which caused our stubs to miss calls. This fixes the common ci tests.

Escape the branch name for the branch_url

---

common/lib/dependabot/clients/github_with_retries.rb

I noticed significant delay at the start of gathering data for the PR. I tracked this down to Faraday's feature of finding a proxy in the environment. For whatever reason it's very slow for us in our smoke tests, and possibly production. 
To fix it, I've set the proxy explicitly from the environment, if it's set there. If it's not, it will again fall back to the old behavior. So if anyone is relying on that, it should still work.

fix Faraday find_proxy slowness

---

updater/lib/dependabot/api_client.rb

This is the same change as in #6853. @Nishnha noted that there was another `find_proxy` I missed. Turned out that it's probably the same issue, and by avoiding it we save even more time!
On my machine it made the Go test go from 1:35 to :25! 🤯

avoid find_proxy which is slow

---

updater/lib/dependabot/logger/formats.rb
updater/lib/dependabot/setup.rb

To help track down freezes and performance issues it's helpful if every line has a consistent timestamp. This matches the timestamp format that the proxy uses. 
Before:
```
updater | I, [2023-03-17T11:39:57.488735 #911]  INFO -- sentry: ** [Raven] Raven 3.1.2 configured not to capture errors: DSN not set
updater | INFO Starting job processing
```
After:
```
updater | 2023/03/17 11:43:56 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/03/17 11:43:58 INFO Starting job processing
```

add timestamp to logger

---

.github/workflows/ci.yml
updater/Gemfile

One of our tests starting failing out of nowhere and slowed us down a bit. We found this was due to a fairly minor Octokit change in https://github.com/dependabot/dependabot-core/pull/6826. 
To catch this sort of thing sooner, we should be running all CI whenever the updater Gemfile or lock changes. 
I wasn't sure if `updater/Gemfile*` would pick up both, so I opted for `updater/Gemfil*`.

run all CI on Gemfile or Gemfile.lock change

---

docker/Dockerfile
docker/lib/dependabot/docker/metadata_finder.rb
docker/spec/dependabot/docker/metadata_finder_spec.rb

Allows us to include richer metadata about the release when creating Docker update PRs (commits, release notes, repo link, etc) to address https://github.com/dependabot/dependabot-core/issues/2085. To enable support, maintainers of docker images need to add the [`org.opencontainers.image.source`](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) label to their `Dockerfile` with the url of the source repo. Additionally, they need to tag the repo with the same tags as the published docker images. This allows Dependabot to understand which repo & commit is associated each version/tag of a docker image.
This example repo demonstrates the setup: https://github.com/dependabot-fixtures/docker-with-source
There isn't a simple registry API to read …

Link docker image to repo via OCI source annotation

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater_spec.rb

This is another clear-the-way PR for #6663 [[Prototype] Generating grouped update PRs](https://github.com/dependabot/dependabot-core/pull/6663).
Depends on https://github.com/dependabot/dependabot-core/pull/6846
A Dependabot update process has three broad steps:
1. Fetch the files we need from the repository
2. Parse the fetched files into a set of dependency information Dependabot can work with
3. Iterate over the dependency update to make changes to the fetched files which are pushed back to the repo
Currently, step(1) is performed as a single command so we do not need to provide repository credentials to the Update step and it hands files over to step(2) by encoding them into a 'job definition' along with the workload description it used to fetch them.
As we start to break the …

[Updater] Start splitting the Updater by extracting DependencySnapshot as an input class

---

updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/error_handler.rb

Follows up on https://github.com/dependabot/dependabot-core/pull/6847 which must merge first
This is small and somewhat imperfect extract-to-class refactor to move aside some long methods we use for presenting `Dependabot::Errors` via the `Dependabot::Service` and/or logging.
As we split out distinct operator classes, duplicating these methods is really undesirable as they have a lot of specific behaviour that would be hard to keep in alignment.
I think there's a deeper refactor to be had here since methods ultimately derive an "error detail" hash based on the subclass of `Dependabot::Error` being handled, e.g.
```ruby
{
"error-type": "private_source_timed_out",
"error-detail": { source: error.source }
}
```
I think this could just become a method on each `Dependabot::Error` subclass, but …

[Updater] Break out handler methods for Dependabot::Error classes into a small utility class

---

updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/updater/operations_spec.rb

This change is downstream of https://github.com/dependabot/dependabot-core/pull/6865 and https://github.com/dependabot/dependabot-core/pull/6847 which should both merge first
This is another clear-the-way PR for #6663 [[Prototype] Generating grouped update PRs](https://github.com/dependabot/dependabot-core/pull/6663).
In order to introduce Grouped Updates, we need to clean up the distinct business objects involved in a single Dependabot "Operation" in order to avoid hard-to-reason about branching at different points in the code line.
This PR introduces the `Dependabot::Operations` module which acts as a way to isolate each distinct type of Update we do to avoid us switching from a Version- to Security-update strategy within methods.
It then uses this pattern to extract the logic required …

[Updater] Establish the Updater::Operations pattern, Extract UpdateAllVersions as the first strategy class

---

bundler/helpers/v2/monkey_patches/definition_ruby_version_patch.rb

While we're [deliberating on how to proceed with Ruby 3.2.0](https://github.com/dependabot/dependabot-core/pull/6436), we're seeing some updates failing due to requirements on it. So to fix that we can add that version here to get PRs flowing again.

allow Ruby 3.2.0 updates to work

---

Dockerfile.updater-core

This will help Dependabot include relevant change details when it opens PRs against this image. Support was added in https://github.com/dependabot/dependabot-core/pull/6864.
I'm not sure if we also need to add this label to each ecosystem image. I'll followup with that change if this doesn't have the expected result.

Add OCI source annotation to updater core image

---

common/lib/dependabot/source.rb
common/spec/dependabot/source_spec.rb

Accounting for trailing `.git` was causing false negatives for `.github` repositories.
Fixes #6841.

Fix updating reusable workflows in .github repos

---

gradle/lib/dependabot/gradle/file_parser.rb
gradle/spec/fixtures/buildfiles/root_build.gradle.kts

Fixes #6863.
Trully fixing this (as in, actually create correct PRs) was out of scope for the first MVP for Gradle Version Catalogs, and I don't want to continue with the business of parsing Kotlin/Java code in Ruby. The way to go for us is probably to leverage #1164.
So the way I approached this is to just avoid creating an incorrect PR by fixing the underlying bug that caused that.
We do support some bare version replacements in build files, for example,
```
val helmVersion = "1.6.0"
id("org.unbroken-dome.helm") version helmVersion apply false
```
What the code used to do was checking whether the version parsed was all "word characters" or not.
If all word characters, then it's considered a property name, a value for the property is looked up, and if a value cannot be found, then the …

Don't consider references to catalogs in buildfiles

---

python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb

Unfortunately, bumping to the latest version of `pipenv` is currently blocked on us dropping support for Python 3.6:
* https://github.com/dependabot/dependabot-core/pull/6104#issuecomment-1397616478
So for now let's clarify the comment with a TODO... 
This whole bit of code may also get redone if we switch the interface we use:
* https://github.com/dependabot/dependabot-core/issues/6836
But for now let's capture some notes until we can devote more time to this.

Clarify TODO comment

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb

If a repo has multiple .npmrc files, Dependabot only rewrites one of them to remove variables. NPM doesn't seem to have an issue with this, I assume it's just expanding undefined vars to `""`, but Yarn 1 is not ok with that and errors.
To fix this, I've added some code to rewrite all of the .npmrc files and remove the variables. 
Still trying to figure out if there's a way to test this in this project, I have a CLI test that is passing with this change.

fix Yarn 1 erroring on parent npmrc files with undefined vars

---

bundler/helpers/v2/lib/functions/lockfile_updater.rb

Fix a typo that showed up in a job run
```
return dependencies_to_unlock.append(*potentials_deps) if potentials_deps.any?
^^^^^^^^^^^^^^^
Did you mean?  potential_deps
```

Fix typo: potentials -> potential

---

Dockerfile.updater-core
hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/dependabot/hex/update_checker_spec.rb

I noticed we're copying all of common in before doing the `bundle install`. This means for any change in common we're having to wait for bundler to run again when it's not required unless the Gemfile or gemspec changes.
This should result in faster builds!

decrease chance of Docker cache invalidation due to common change

---

updater/lib/dependabot/service.rb

This fixes an issue introduced in https://github.com/dependabot/dependabot-core/pull/6846
We previously passed `job.package_manager` in two places, in [one](https://github.com/dependabot/dependabot-core/pull/6846/files#diff-0ae3ea6b30ef21b78d5b11abdd5a8b478e3df86e9c2d681c88fc4d03f49e170bL94-L98) as a 'tag' and in [another](https://github.com/dependabot/dependabot-core/pull/6846/files#diff-b18ee444afdafa5177657bddd586b0097d8d8f631729850ed2afd5b6eb573e5aL997-L1007) as part of the 'extra' hash.
In #6846, this logic was consolidated but package_manager was only passed in the `extra` hash meaning that Sentry no longer hydrates it as a searchable value. This PR fixes this by correctly passing it as a `tag` for _all_ captured errors, if the Job is available.

Add package manager as a tag in error contexts

---

bin/dry-run.rb

* Use a unified diff format, much easier to read, and everyone is more used to it.
* Include a stats summary of added and deleted lines.

Improve `dry-run.rb` diffs

---

updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater_spec.rb

Follows up on #6906 
Now we've established the fast-fail approach to Dependency parsing in production, this PR makes a small follow-up change to relay the outcome of the parsing to the service as metadata we use to maintain an understanding of the current state of the project to immediately after the parsing takes place.
This will remove the need to perform this call in each operation class, avoiding repetition.

[Updater] Update the service's dependency metadata in one place

---

README.md

Add a section to the Readme documenting the credential proxy.
[rendered](https://github.com/dependabot/dependabot-core/tree/document-credential-proxy#private-registry-credential-management)
This provides three benefits:
1. Users are reassured that GitHub keeps their secrets safe.
2. Security researchers who manage to hack `dependabot-core` aren't surprised when we tell them that doesn't mean they hacked the entire Dependabot Service at GitHub.
3. Clarifies why adding support for private registries to `dependabot-core` isn't enough for those registries to be supported by the Dependabot service that GitHub runs. We still have to plumb those auth schemes into the proxy.
Perhaps down the road we may be able to open source the proxy so others can benefit from the increased security, but that's …

Document the credential proxy

---

README.md

The release guide is only helpful for maintainers, it's visual noise for everyone else. So let's:
1. Create a dedicated section for maintainers following the format from https://github.com/dependabot/fetch-metadata/blob/aea2135c95039f05c64436f1d14638c300e10b2b/README.md#L177-L211
2. Move the release notes there
Later on we may have additional things to add under the maintainers section, for example what commands to run to merge Dependabot PR's that are failing due to needing to run `cd /updater && bundle install`, but let's land this first.

Create dedicated section for maintainers

---

README.md

No need to waste space on cloning instructions:
1. Anyone reading this will almost always be familiar with how `git` works. If not, most of the rest of this won't make sense to them either.
2. Cloning makes sense for development, but not for someone just wanting to run Dependabot... for that we'd rather push them to another tool.
3. The windows error will loudly fail, as opposed to silently failing. When I googled that error, one of the top results was a stackOverflow answer showing exactly this answer.
So let's remove this so we can focus the reader's attention on higher-value topics.

Remove `git clone` instructions from Readme

---

updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/refresh_version_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/updater/operations_spec.rb
updater/spec/dependabot/updater_spec.rb

Follows on from https://github.com/dependabot/dependabot-core/pull/6866, #6884 
This branch peels out the Updater code required to accept a job which is "refreshing" an existing Dependabot PR for a version update using the same approach as before:
- Extract the entire code path required from the Updater
- Remove any code related to non-concerns for this operation type, in this case security-updates primarily
- Wire it into the Updater to be used for a specific job type, verifying current testing passes
We use different terminology for this operation in some places depending on the trigger, but it isn't correct to think of it as a "rebase" despite commands like `@dependabot rebase` existing.
The actual behaviour is one of three outcomes:
- If the project still needs the same dependency at …

[Updater] Extract RefreshVersionPullRequest as an Operation class

---

docker/lib/dependabot/docker/update_checker.rb

~I think this is a regression of #6748.~
EDIT: Just checked, and not a regression of that PR, actually. Unsure for how long we've been this slow.
Logic was going directly through `fetch_latest_version`, which is not memoized.
This make the slow logic (`fetch_` methods) only run once.
Before:
```
$ time bin/dry-run.rb docker dsp-testing/dependabot-core-4419 --cache files
=> reading dependency files from cache manifest: ./dry-run/dsp-testing/dependabot-core-4419/cache-manifest-docker.json
=> updating 1 dependencies: node
=== node (10.9.2-alpine)
=> latest available version is 19.8.1-alpine
=> latest allowed version is 19.8.1-alpine
=> requirements update strategy: 
=> bump node from 10.9.2-alpine to …
```

Restore performance of Docker update checker

---

omnibus/dependabot-omnibus.gemspec

The `omnibus` gem here is composed of all the subgems for each package manager / ecosystem. And those subgems already specify a minimum ruby/rubygems version as inherited from `common`. So specifying it here doesn't actually change the requirement, it just advertises better what's already required.

Inherit required ruby/rubygems version from `common`

---

.github/ISSUE_TEMPLATE/bug-report.yml

We get the occasional issue about Alerts / Dependency Graph, and they're out of scope for both this issue tracker and the team that watches the issue tracker... ie, there's nothing we can do.
So let's point folks in the right direction from the get-go.

Discourage filing issues about Alerts / Dependency Graph

---

.github/ISSUE_TEMPLATE/tech-debt.yml

Tech Debt issues are rarely filed by n00bs, but almost always by folks already familiar with the project.
Because they tend to be more knowledgable, they generally are already aware of duplicates, so this just gets in the way.

Remove checkbox for searching for duplicates

---

docker/lib/dependabot/docker/update_checker.rb

Before:
```
$ time bin/dry-run.rb docker dsp-testing/dependabot-core-4419 --cache files
=> reading dependency files from cache manifest: ./dry-run/dsp-testing/dependabot-core-4419/cache-manifest-docker.json
=> updating 1 dependencies: ubuntu
=== ubuntu (12.04.5)
=> latest available version is 23.04
=> latest allowed version is 23.04
=> requirements update strategy: 
/home/dependabot/dependabot-core/docker/lib/dependabot/docker/file_updater.rb:66:in `updated_dockerfile_content': Expected content to change! (RuntimeError)
from /home/dependabot/dependabot-core/docker/lib/dependabot/docker/file_updater.rb:33:in `block in updated_dependency_files'
from …
```

Properly memoize nil digests from registry API

---

bundler/dependabot-bundler.gemspec
cargo/dependabot-cargo.gemspec
common/dependabot-common.gemspec
composer/dependabot-composer.gemspec
docker/dependabot-docker.gemspec
elm/dependabot-elm.gemspec
git_submodules/dependabot-git_submodules.gemspec
github_actions/dependabot-github_actions.gemspec
go_modules/dependabot-go_modules.gemspec
gradle/dependabot-gradle.gemspec
hex/dependabot-hex.gemspec
maven/dependabot-maven.gemspec
npm_and_yarn/dependabot-npm_and_yarn.gemspec
nuget/dependabot-nuget.gemspec
omnibus/dependabot-omnibus.gemspec
pub/dependabot-pub.gemspec
python/dependabot-python.gemspec
terraform/dependabot-terraform.gemspec

In particular adding the changelog metadata makes Dependabot PR's show the changelog contents when it creates PRs.
For now I pointed them all at the same changelog because we don't maintain separate changelogs/issue trackers for the individual sub-gems. Easy enough to change later if needed.

Add links to issue tracker / changelog to gemspecs

---

common/dependabot-common.gemspec

Use the correct email for open source projects at GitHub.
The previous one is a leftover from before Dependabot was acquired and is no longer monitored.

Use the correct author email

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb

If a Dockerfile is using a version+SHA reference of an image coming from a registry that does not provide digests, we initially think an update is possible, but then fail to update the Dockerfile because we cannot really know which SHA we should update to.
For example, with the following Dockerfile
```Dockerfile
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5@sha256:3f32ebba0cbf3849a48372d4fc3a4ce70816f248d39eb50da7ea5f15c7f9d120
```
We get:
```
$ bin/dry-run.rb docker dsp-testing/dependabot-core-4419 --cache files
warning: parser/current is loading parser/ruby31, which recognizes 3.1.4-compliant syntax, but you are running 3.1.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> reading dependency files from cache manifest: …
```

Avoid some "Files not changed!" errors in Docker

---

docker/lib/dependabot/docker/file_updater.rb
docker/spec/dependabot/docker/file_updater_spec.rb

If we have multiple Dockerfiles with mixed formats and outdated versions, we may end up updating some references incorrectly. For example, with 2 Dockerfiles both with out of date versions (but not the same), and one of them including a SHA.
In that case, the version including a SHA would not get updated, resulting in an invalid version+SHA combinatation.
This PR fixes that.
Before:
```
$ bin/dry-run.rb docker reload/php-fpm --cache files --dep composer
=> reading dependency files from cache manifest: ./dry-run/reload/php-fpm/cache-manifest-docker.json
=> updating 1 dependencies: composer
=== composer (2.3)
=> latest available version is 2.5
=> latest allowed version is 2.5
=> requirements update …
```

Fix updating some references when having multiple Dockerfiles

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb

With the following `Dockerfile`
```Dockerfile
FROM ubuntu:22.04@sha256:817cfe4672284dcbfee885b1a66094fd907630d610cab329114d036716be49ba
```
Before:
```
$ bin/dry-run.rb docker reload/php-fpm --cache files  --dep ubuntu
=> reading dependency files from cache manifest: ./dry-run/reload/php-fpm/cache-manifest-docker.json
=> updating 1 dependencies: ubuntu
=== ubuntu (22.04)
=> latest available version is 22.04
(no update needed as it's already up-to-date)
🌍 Total requests made: '0'
```
After:
```
$ bin/dry-run.rb docker reload/php-fpm --cache files  --dep ubuntu
=> reading dependency files from cache manifest: ./dry-run/reload/php-fpm/cache-manifest-docker.json
=> updating 1 dependencies: ubuntu
=== ubuntu …
```

Allow updating digest only when tag is up to date

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm8/workspace_outdated_deps_not_in_root_package_json/bump-version-for-cron/package.json
npm_and_yarn/spec/fixtures/projects/npm8/workspace_outdated_deps_not_in_root_package_json/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm8/workspace_outdated_deps_not_in_root_package_json/package.json

When updating a dependency not included in the root `package.json` file, and that only requires `package-lock.json` changes, we ended up running `npm install --lockfile-only` (without explicit `package@version` arg), and that would result in no lockfile changes and the above error.
We need to force the update through a `package@version` CLI argument. However, as it was already explained on a comment, in this case this causes a new dependency to be added to the top level `package.json` file, which is not desirable. To workaround that, we save the original `package.json` content, and restore it after the upgrade and re-run `npm install --lockfile-only` again to bring the lockfile in sync.

Fix "no files were updated!" errors in workspaces

---

python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb

This is failing on `main` because `blinker` `1.6` just dropped: https://github.com/pallets-eco/blinker/blob/main/CHANGES.rst#version-16
Ideally we'd update the test to not depend on the version, but mocking may be non-trivial if a native helper is used here.
Besides, `blinker` is updating less than 1x per year, and it's trivial to see what broke in CI and update it.

Update test expectation to match latest `blinker` release

---

cargo/Dockerfile

Bump rust, use the new [CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol) option.

bump Cargo version

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/environment.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb

Before adding two more "Operation" classes for Security Updates, we should ensure that any code that is starting to be carried into every Operation class so far is de-duplicated as much as possible.
Rather than repeat logic to filter the parsed dependencies by either those that are permitted by allow_conditions or those which intersect with the job.dependencies within the Updater, I've just moved this logic unto `Dependabot::Snapshot` and slimmed down the dependencies method(s) in the various classes.

[Updater] Move filtering of parsed dependencies by allow rules or job dependencies

---

script/ci-test-updater

For example,
```
script/ci-test-updater spec/dependabot/integration_spec.rb:396
```

Allow running specific updater specs easily

---

CONTRIBUTING.md
README.md

Over time the Readme has grown organically by adding new sections as needed. Unfortunately, the length and relative lack of order makes it not very approachable for folks new to the project.
So this adds a Table of Contents structured in a way that's more accessible, and then re-orders the content appropriately.
[rendered](https://github.com/dependabot/dependabot-core/blob/re-order-readme-using-intuitive-TOC/README.md)

Re-structure Readme using a TOC

---

common/lib/dependabot/dependency.rb
common/lib/dependabot/pull_request_creator/message_builder.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/integration_spec.rb

Before:
```
$ script/dependabot update docker dsp-testing/dependabot-core-5758
updater | 2023/04/04 13:11:52 INFO Results:
updater | +---------------------------------------------------------------------+
updater | |                 Changes to Dependabot Pull Requests                 |
updater | +---------+-----------------------------------------------------------+
updater | | created | docker/library/ruby ( from 2.7.6-buster to 3.2.2-buster ) |
updater | | created | ubuntu ( from focal to focal )                            |
updater | +---------+-----------------------------------------------------------+
proxy | time="2023-04-04T13:11:52Z" level=info msg="4/28 calls cached (14%)"
```
After:
```
$ script/dependabot update docker dsp-testing/dependabot-core-5758
updater | 2023/04/04 …
```

Generate proper PR summary table for docker digest updates

---

common/lib/dependabot/config/file_fetcher.rb
common/lib/dependabot/errors.rb

We were always instantiating this exception with an empty message. Now we provide the path that was not found by default.

Give a useful message when DependencyFileNotFound is raised

---

bundler/dependabot-bundler.gemspec
cargo/dependabot-cargo.gemspec
common/dependabot-common.gemspec
composer/dependabot-composer.gemspec
docker/dependabot-docker.gemspec
elm/dependabot-elm.gemspec
git_submodules/dependabot-git_submodules.gemspec
github_actions/dependabot-github_actions.gemspec
go_modules/dependabot-go_modules.gemspec
gradle/dependabot-gradle.gemspec
hex/dependabot-hex.gemspec
maven/dependabot-maven.gemspec
npm_and_yarn/dependabot-npm_and_yarn.gemspec
nuget/dependabot-nuget.gemspec
omnibus/dependabot-omnibus.gemspec
pub/dependabot-pub.gemspec
python/dependabot-python.gemspec
terraform/dependabot-terraform.gemspec

One of the things I noticed a long time ago on RubyGems is it's not really clear how all the Dependabot gems fit together... which is mostly because their `description` metadata field all inherit from `common`.
If you're trying to get going with the Dependabot gem, it's unclear which one you actually want.
So this fixes that.

Clarify `summary`/`description` for RubyGems

---

updater/spec/dependabot/updater_spec.rb

Doing this for every test makes it hard to work with these specs because, for example, programming mistakes can be also swallowed by the catch all stub.
I think this can be further refined, but stubbing only when needed seems like an improvement.

Don't swallow all updater spec errors unconditionally

---

updater/lib/dependabot/dependency_change_builder.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/dependency_change_builder_spec.rb
updater/spec/dependabot/updater_spec.rb

We've started the process of isolating the main updater operations into concrete classes by extracting the codelines for:
- Creating fresh updates for all out of date dependencies
- Refreshing an existing PR for a single out of date dependency
Next we plan to do the same for [Security update workflows](https://github.com/dependabot/dependabot-core/pull/6961), but before this we're focusing on removing duplicate code and extracting business objects to encapsulate some of the concerns. ( https://github.com/dependabot/dependabot-core/pull/6991, https://github.com/dependabot/dependabot-core/pull/6989 ).
This pull request completes the work we started a while back where we introduced a `DependencyChange` object which describes the outcome of an operation in terms of the dependencies that have …

[Updater] Introduce a DependencyChangeBuilder class to complete encapsulation of diff generation

---

npm_and_yarn/Dockerfile

I do not know what version we are targeting. Can we upgrade to the latest `3.x` version if CI passes? 
If the intention is to stay within `3.2.x`, I can create a separate PR  as we're also behind in that range

build(deps): bump yarn from 3.2.3 to 3.4.1

---

go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb

A new version of golang.org/x/net was released which broke this test. By ignoring newer versions this test continues to work going forward.

fix flaky Go test by ignoring newly released versions

---

Dockerfile.updater-core
go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb

In #5356 we switched away from a PPA since it wasn't keeping up with new versions of Ruby. Ruby-install was good but building from source is slow, and it seems like we break the cache more often than we care to.
This approach is to copy Ruby et al from the official Ruby Docker image which should stay up-to-date. This allows us to skip the build to save time, and we can stay on our current version of Ubuntu by copying out the binaries. This also saves ~100MB from somewhere, the `bundler` image is now around 640MB for me. 
I had to move the `bundle install` out since it didn't seem to like to be run on a different version of Ubuntu? I'm not sure, but even with less parallelism this is very fast locally. Submitting as Draft to test against CI, check the speed, and get feedback.

improve worst case image build time

---

npm_and_yarn/helpers/build

During image build, this works because `dry-run` is not yet set in configuration. But if you re-run it inside the development container after, for example, changing the version of a native dependencies, it no longer installs anything.
Avoid `dry-run` mode explicitly to prevent this.

Fix reinstalling `npm_and_yarn` native helper dependencies

---

common/lib/dependabot/clients/azure.rb
common/spec/dependabot/clients/azure_spec.rb

Autocomplete functionality added in #4064 is missing a variable to set autoCompleteIgnoreConfigIds. This PR adds it.

Allow passing autoCompleteIgnoreConfigIds value for azure

---

python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb

We've need to update this spec twice so far, and will have to keep doing this every time blinker releases new versions.
I fixed the spec permanently this time by only checking for presence of the dependency.

Fix Python CI

---

.devcontainer/core-dev/devcontainer.json
.vscode/extensions.json

Fixes #7017 by replacing "misgogi-ruby-rubcop" with "LoranKloeze.ruby-rubocop-revived"

Update abandoned misogi ruby-rubocop

---

Dockerfile.updater-core
updater/Gemfile.lock

There's [a change](https://github.com/rubygems/rubygems/pull/6578) in 2.4.11 that may prevent Dependabot from timing out when trying to update big Gemfiles.

Update Bundler to 2.4.11

---

.devcontainer/core-dev/devcontainer.json
.vscode/extensions.json
.vscode/launch.json
omnibus/Gemfile

Addresses Issues 7027 and 7017 ( Fixes #7027 )  updates outdated gem ruby-debug-ide and updates .devcontainer/core-dev and .vscode/launch.json
Follow on PRs will address outdated extension for rubocop

Replace ruby-debug-ide with debug gem

---

README.md

Add a link to the public Dependabot Core board in our docs

Update README.md to include link to the public Dependabot Core board

---

.gitignore

I use [IDEA products ](https://www.jetbrains.com/products/) , and I would appreciate if this is merged as currently I need to ensure that I don't commit it accidentally with each pull request
Creating a separate pull request for this as suggested by this comment: 
https://github.com/dependabot/dependabot-core/pull/7029#discussion_r1163093575
Thanks!

chore(ee): ignore `.idea` folder

---

.github/dependabot.yml
bundler/lib/dependabot/bundler/file_fetcher.rb
bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/file_updater.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/dependabot/bundler/update_checker/file_preparer_spec.rb

This patch would need careful consideration since I guess there was a reason to forbid this in the first place.
But it makes Dependabot generate correct PRs for our development dependencies in /common.
Without this PR:
```
$ bin/dry-run.rb bundler dependabot/dependabot-core --dir /updater --dep rubocop-performance 
=> dumping fetched dependency files: ./dry-run/dependabot/dependabot-core/updater
=> updating 1 dependencies: rubocop-performance
=== rubocop-performance (1.16.0)
🌍 --> GET https://rubygems.org/api/v1/versions/rubocop-performance.json
🌍 <-- 200 https://rubygems.org/api/v1/versions/rubocop-performance.json
=> latest available version is 1.17.1
=> latest allowed version is 1.16.0
=> requirements …
```

Allow updating gemspecs loaded from a Gemfile

---

cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb

Fixes #4915
Per https://rust-lang.github.io/rustup/overrides.html the rust-toolchain file can have a `.toml` extension, but the non-extension version is preferred. So I've added a second lookup for the extensioned file.

cargo: support rust-toolchain with toml extension

---

common/lib/dependabot/errors.rb

Amends 086274e3a4d8f476a1b95a96de2ce9d10515a590, which did not really fix the problem for `Dependabot::DependencyFileNotFound`, and applies the same improvement for `Dependabot::DependencyFileNotParseable`.

Improve some exception error messages

---

cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb

We want to gather info on the optional Cargo overrides file to find out how many people are using them, and what versions are commonly pinned. That will help us make decisions about what versions of the toolchain we should continue to support.

cargo: gather toolchain statistics

---

bundler/lib/dependabot/bundler/file_parser/file_preparer.rb
bundler/lib/dependabot/bundler/file_parser/gemfile_declaration_finder.rb
bundler/lib/dependabot/bundler/file_parser/gemspec_declaration_finder.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/spec/dependabot/bundler/file_updater/lockfile_updater_spec.rb
bundler/spec/fixtures/projects/bundler1/path_gem_with_ruby_requirement/Gemfile
bundler/spec/fixtures/projects/bundler1/path_gem_with_ruby_requirement/Gemfile.lock
bundler/spec/fixtures/projects/bundler1/path_gem_with_ruby_requirement/vendor/couchrb/couchrb.gemspec
bundler/spec/fixtures/projects/bundler2/path_gem_with_ruby_requirement/Gemfile
bundler/spec/fixtures/projects/bundler2/path_gem_with_ruby_requirement/Gemfile.lock
bundler/spec/fixtures/projects/bundler2/path_gem_with_ruby_requirement/vendor/couchrb/couchrb.gemspec

When dealing with libraries, Dependabot sets an extra requirement on Ruby to be the lowest version supported by the gem.
However, it was also incorrectly doing so when dealing with vendored path gems, because all gemspecs were being considered when adding this extra requirement, not just the one in the top level.

Fix incorrect detection of top level gemspecs

---

common/lib/dependabot/dependency_group.rb
common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb
common/spec/dependabot/dependency_group_spec.rb
common/spec/dependabot/pull_request_creator/branch_namer/dependency_group_strategy_spec.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb
common/spec/dependabot/pull_request_creator_spec.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb

We have spiked out using `DependencyGroup` in branch naming but in our internal tests we are overriding the `prefix` value for projects in order to work around potential naming collisions since the prototype cannot yet manage superseding of existing pull requests.
Before we go into the next round of testing, we should make our branch naming for grouped PRs more compatible with existing automation and also avoid problems of the branch name overflowing due to a larger-than-normal number of dependencies being involved.
This PR finishes off our grouped naming strategy so it incorporates the normal prefix, the package manager, directory and target branch along with the actual group name being used.

[Updater] Wire up and flesh out branch naming for Grouped Update PRs

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

This is definitely not perfect, but I think better than what we have.
There's two improvements:
* If given a yarn Berry lockfile, we were still incorrectly instrumenting yarn 1 (unless `packageManager` set in `package.json`).
* If we can't resolve a specific package manager, we'll still run the update job and provide updates. We'll use the npm update checker but we could potentially switch to any other package manager without issues, so I think it's helpful to log separately.

Improve npm package manager instrumentation

---

updater/bin/fetch_files.rb
updater/bin/update_files.rb
updater/lib/dependabot/service.rb

Tags are searchable, extra is not. This improves our ability to figure out what is going wrong with a job ID.

use tags in error reporting

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/file_parser/dotnet_tools_json_parser.rb
nuget/lib/dependabot/nuget/file_updater.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
nuget/spec/dependabot/nuget/file_parser/dotnet_tools_json_parser_spec.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb
nuget/spec/fixtures/dotnet_tools_jsons/dotnet-tools.json
nuget/spec/fixtures/dotnet_tools_jsons/invalid_json.json
nuget/spec/fixtures/github/contents_dotnet_config_directory.json
nuget/spec/fixtures/github/contents_dotnet_dotnet_tools.json
nuget/spec/fixtures/github/contents_dotnet_global.json

Local dotnet tools such as [`dotnet-ef`](https://learn.microsoft.com/en-us/ef/core/cli/dotnet) are distributed [as NuGet packages](https://www.nuget.org/packages/dotnet-ef/). The tools and their versions are stored in `.config/dotnet-tools.json` as decribed in the [docs](https://learn.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use).
This PR adds support for updating them using the existing infrastructure for NuGet. Basically similar to the support for `global.json` but works around directory nesting and multiline regex match for the JSON.
Fixes: #1697

Support for nuget tools in .config/dotnet-tools.json

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/private_artifactory_repository/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm6/private_artifactory_repository/package.json

fix(npm): registry inferring should include the full registry path

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb

Follow up for the following discussion https://github.com/dependabot/dependabot-core/pull/7030#discussion_r1164833616

docs(npm): explain situations where parsing `resolved` can fail

---

updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/spec/dependabot/updater/operations_spec.rb
updater/spec/dependabot/updater_spec.rb

Follows on from https://github.com/dependabot/dependabot-core/pull/6866, https://github.com/dependabot/dependabot-core/pull/6884, https://github.com/dependabot/dependabot-core/pull/6939
This branch peels out the Updater code required to accept a job which is generating a new Dependabot PR for a security update using the typical approach of:
- Extract the entire code path required from the Updater
- Remove any code related to non-concerns for this operation type, in this case version updates and rebases
- Wire it into the Updater to be used for a specific job type, verifying current testing passes
The one significant deviation from the previous PRs is that this does make test changes. In order to pass the existing tests, some setups need to be completed by ensuring there is a value for …

[Updater] Extract UpdateVulnerableVersion as an Operation class

---

updater/spec/dependabot/dependency_group_engine_spec.rb
updater/spec/dependabot/updater_spec.rb

Reproducer:
```
$ script/ci-test-updater './spec/dependabot/dependency_group_engine_spec.rb[1:4:1]' './spec/dependabot/updater_spec.rb[1:2:1]' --seed 24926
```
There was one spec causing side effects that was missing cleanup.
Also I changed cleaning up side effects to be done after the specs that create them, not before.

Fix flaky specs in updater

---

updater/spec/dependabot/dependency_group_engine_spec.rb

We were also leaking the grouped updates experiment.
Failures can be reproduced with:
```
$ script/ci-test-updater './spec/dependabot/dependency_group_engine_spec.rb:129' './spec/dependabot/update_files_command_spec.rb:52' --order=defined
```

Fix more order dependent spec failures

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

The `yarn_berry?` helper receives a `DependencyFile`, not the actual content.

Fix Yarn Berry detection during package manager instrumentation

---

bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/native_helpers.rb

This should give the user a nice message on why Dependabot couldn't solve the dependencies given, and stop showing as "unknown errors" for our reporting.

Bundler: handle SolveFailures as expected errors

---

common/lib/dependabot/clients/github_with_retries.rb

If `dependabot-core` is used in another application which has a separate dependency on Octokit, requests made through `dependabot-core` will rewrite the middleware stack. This is an attempt to prevent that behavior and make the setting of middleware specific to the client being built.

🛑 Stop clobbering Octokit middleware

---

cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb

Per the [docs](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), the toolchain files should be TOML since rustup 1.23. We're seeing a fair amount of projects using the old style, which won't work with what version we're on, so going to turn that unknown error into a DependencyFileNotParseable error.

Cargo: handle TOML parsing errors

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
common/spec/dependabot/pull_request_creator_spec.rb

Currently any PRs we generate for Dependency Groups use existing logic to make a best effort to summarise all the dependencies that have changed.
This is adequate for some cases where only 1-3 dependencies have changed, but in testing we've found groups of ~10 which break the PR layout badly and are generally not terribly friendly to encounter.
This change introduces a new naming strategy specifically for PRs created by Dependency Groups where they use the **name of the group** being updated instead of the Dependencies involved, leaving this for the PR body to communicate, e.g.
> Bump the all-the-things group in myproject/ with 3 updates
This achieves two things:
- It builds awareness when a PR has been created from a group configuration rather than a single dependency upgrade for the …

Pull Request names are Dependency Group aware

---

bin/docker-dev-shell
updater/README.md

Technically every ecosystem results in building a per-ecosystem updater image. But currently running the `updater` unit tests requires the `bundler` ecosystem image.
So this is a convenience to make it so we don't have to rememeber that
and can just run `bin/docker-dev-shell updater`.

Map `updater` ecosystem to `bundler`

---

Dockerfile.updater-core
common/dependabot-common.gemspec
updater/Gemfile.lock

While working on PNPM, I was going crazy because Dependabot could not parse the following YAML file:
https://github.com/ice-lab/icestark/blob/ec2d44244a2b4ebd7af0e0ff0a10f528b33b8a64/pnpm-lock.yaml
However, it would be parsed just fine on my dev machine.
On my dev machine:
```
$ ruby -rpsych -e 'Psych.load_file("tmp/ice-lab/icestark/pnpm-lock.yaml")'
```
On the development container:
```
$ ruby -rpsych -e 'Psych.load_file("tmp/ice-lab/icestark/pnpm-lock.yaml")'
/usr/local/lib/ruby/gems/3.1.0/gems/psych-4.0.4/lib/psych.rb:455:in `parse': (tmp/ice-lab/icestark/pnpm-lock.yaml): did not find expected ',' or '}' while parsing a flow mapping at line 1308 column 17 (Psych::SyntaxError)
from /usr/local/lib/ruby/gems/3.1.0/gems/psych-4.0.4/lib/psych.rb:455:in `parse_stream'
from …
```

Fix parsing some YAMLs due to outdated libyaml

---

updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/spec/dependabot/dependency_change_spec.rb

In order to ensure the PR title and message body are built using the right strategy, we need to pass any group assigned to the `Dependabot::DependencyChange` on to the `Dependabot::PullRequestCreator::MessageBuilder` class.
I've also made a small agreement change to the name of the placeholder group we use if no configuration is supplied to use the same placeholder name we use elsewhere.

[Updater] DependencyChange passes any group to the PR message builder

---

updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/security_update_helpers.rb
updater/spec/dependabot/updater/operations_spec.rb

Follows on from https://github.com/dependabot/dependabot-core/pull/6866, https://github.com/dependabot/dependabot-core/pull/6884, https://github.com/dependabot/dependabot-core/pull/6939, https://github.com/dependabot/dependabot-core/pull/6961
This branch is the last of four class extractions to peel out the distinct scenarios the Updater _actually_ handles today in clear terms.
This branch peels out the Updater code required to accept a job which is refreshing a Dependabot PR for a security update using the typical approach of:
- Extract the entire code path required from the Updater
- Remove any code related to non-concerns for this operation type, in this case version updates and rebases
- Wire it into the Updater to be used for a specific job type, verifying current testing passes
The …

[Updater] Extract RefreshSecurityUpdatePullRequest into an Operation class

---

updater/lib/dependabot/environment.rb
updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/operations.rb
updater/spec/dependabot/updater_spec.rb
updater/spec/spec_helper.rb

Follows on from https://github.com/dependabot/dependabot-core/pull/7128
Now that all well-formed job definitions are routed to an Operation class, the only jobs that can possibly hit the `Updater#legacy_run` path are those where the attributes **do not match real-world configurations**.
This PR makes a change to disable the `Updater#legacy_run` method in our test suite so any existing or new tests which hit the legacy code line will fail.
Having done this, it then addresses two cohorts of failing tests:
- A set of ignore condition tests which are creating new Version PRs but are using `job.dependencies` as a convenience in their test setup to avoid having to account for N dependencies
- This fix for these is to adjust the expectations so they only examine the target dependency without …

[Updater] Ensure we no longer test the legacy code path

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb

Currently when Dependabot encounters an error from Cargo when it can't find a dependency it raises a HelperSubprocessFailed error. 
This recategorizes that case to a DependencyFileNotResolvable error which shows a better error including the dependency that was not found.
I randomly generated the dependency name in the test so no one can register the name and break our tests 😄

Cargo: handle dependencies that are not in the index

---

npm_and_yarn/lib/dependabot/npm_and_yarn/dependency_files_filterer.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/dependency_files_filterer_spec.rb

If a monorepo provides multiple packages, but a single root lockfile, we just need to run the update checker in the root lockfile, since that one should be managing all dependencies.
We were running the update checker once per package, making things painfully slow.
Also, we were running the commands to check for the update inside each folder, and I'm not sure that actually works as expected in presence of a root lockfile.

Don't run update checker unnecessarily on all javascript packages in a monorepo

---

npm_and_yarn/Dockerfile

I think the problem was not that native helpers pull Yarn 1, but that the version was being activated for the root user, not for the dependabot user. I don't think we need it for root.
(Extracted from #7134)

Prepare yarn berry just once

---

cargo/lib/dependabot/cargo/update_checker/version_resolver.rb
cargo/spec/dependabot/cargo/update_checker/version_resolver_spec.rb

This is the same PR as #7122 but against the version resolver. 
It would probably be good in the future to create a native helper that both the version resolver and lockfile updater use since the errors seem like they are the same between the two.

Cargo: handle unsupported toolchain versions (part 2)

---

bundler/dependabot-bundler.gemspec
cargo/dependabot-cargo.gemspec
common/dependabot-common.gemspec
composer/dependabot-composer.gemspec
docker/dependabot-docker.gemspec
elm/dependabot-elm.gemspec
git_submodules/dependabot-git_submodules.gemspec
github_actions/dependabot-github_actions.gemspec
go_modules/dependabot-go_modules.gemspec
gradle/dependabot-gradle.gemspec
hex/dependabot-hex.gemspec
maven/dependabot-maven.gemspec
npm_and_yarn/dependabot-npm_and_yarn.gemspec
nuget/dependabot-nuget.gemspec
omnibus/dependabot-omnibus.gemspec
pub/dependabot-pub.gemspec
python/dependabot-python.gemspec
terraform/dependabot-terraform.gemspec

I noticed we specify a `issue_tracker_uri` in our RubyGems metadata, but it's not showing up on RubyGems: https://rubygems.org/gems/dependabot-omnibus
A little digging showed [this is supposed to be `bug_tracker_uri`](https://guides.rubygems.org/specification-reference/#metadata).
Compare `rails` where it shows up:
1. https://github.com/rails/rails/blob/744b6715a5d07a2ddffceea8283f7b787541bc60/rails.gemspec#L24
2. https://rubygems.org/gems/rails

It's `bug_tracker_uri` not `issue_tracker_uri`

---

CHANGELOG_ARCHIVE_2019_TO_SWITCH_TO_GITHUB_RELEASES.md
bin/bump-version.rb
common/dependabot-common.gemspec

We'd like to publish release more often, and part of that is making the release process more streamlined so that the maintainers don't dread the busywork of cutting a release.
Part of that is automating creating PR's that bump the version... but there's a race condition because we don't keep the changelog routinely updated with every PR... so if the version bump PR is opened, and then another PR is merged, that other PR won't be mentioning in the release notes.
The easiest way to sidestep that is to switch to managing the release notes via GitHub releases and stop using a Changelog text file.
We've had this discussion of "flat file vs git tags / GitHub releases" on a number of open source projects that I help maintain, and the pros/cons typically boil down to GitHub releases are more …

Switch from `Changelog.md` to GitHub releases

---

bin/bump-version.rb

Now that this script no longer generates the changelog, it's so simple that there's no need for `--dry-run`. Any file changes can be reverted using `git restore`.
I thought about leaving it in for development purposes, but anyone working on this can hack what they need by commenting code out.
So might as well simplify it, esp since this will be used within a GitHub action workflow soon, simpler is better.

No need for `--dry-run`

---

npm_and_yarn/Dockerfile

We never heard back from Yarn regarding the [release notes for this version](https://github.com/yarnpkg/berry/issues/5369)
But @deivid-rodriguez [confirmed that we are using `3.5.0` ](https://github.com/dependabot/dependabot-core/pull/7001#issuecomment-1517845943)

build(deps): bump Yarn from 3.4.1 to 3.5.0

---

common/lib/dependabot/dependency_group.rb
updater/lib/dependabot/api_client.rb
updater/spec/dependabot/api_client_spec.rb

Pass the serialized group name to PR creator (and the API client) when creating a PR for grouped updates.
We no longer pass the `grouped-update` key to the PR creator and instead pass in the `dependency-group` name
For now we are transforming the group name to downcase, snake_case, and to a symbol (although the test checks the name after it's been serialized to JSON, so the DependencyChange#id is converted to a string)

Pass the serialized group name when creating a PR for grouped updates

---

.github/workflows/images-latest.yml

This took me a little longer than it should have to understand what was going on, so here's a few cleanups that would have helped me grok things faster:
1. Rename `TAG` to `COMMIT_SHA` because tag is a bit ambiguous because the image is actually getting tagged with multiple things.
2. Organize all the tagging steps together.
3. Move the login step right next to publish... total nit, but typical workflows are build, tag, publish, and login is really part of publishing.
4. Clarify that we're _only_ building the ecosystem images, as `dependabot-updater` is ambiguous since there's both the base core image and the ecosystem images.

Clarify the `images-latest` workflow

---

terraform/Dockerfile

https://github.com/hashicorp/terraform/releases/tag/v1.4.6

build(deps): bump Terraform to 1.4.6

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm8/engines/.npmrc
npm_and_yarn/spec/fixtures/projects/npm8/engines/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm8/engines/package.json

For additional context see https://github.com/dependabot/dependabot-core/issues/4072#issuecomment-1413222679
When `engine-strict` is set to true, Dependabot can error if the currently installed version doesn't match the range set in package.json. 
This gives the error in the UI more substance to help the customer figure out why it happened and solve the problem if they choose. Also helps clean up our error reporting!

NPM: handle EBADENGINE better

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb

Since we have `ignore` settings, this may lead code reader into thinking we actually support skipping lockfiles through `dependabot.yml`. This is just trying to respect a package manager specific setting, so let's rename it to reduce confusion.
Suggested by @jeffwidman at https://github.com/dependabot/dependabot-core/pull/7081#discussion_r1176058626.

Improve naming of a method

---

bin/bump-version.rb

If `bundle lock` failed for some reason, then the exit code wasn't preserved and the message about the gemfile being updated successfully was incorrectly printed.

Catch `bundle lock` failures

---

bin/bump-version.rb

In https://github.com/dependabot/dependabot-core/pull/7208 I added this error checking, but I discovered through further testing that `$?.exitstatus` is always "truthy" in ruby, even for a `0` exit code!
I double-checked this variant, and it works as expected for both the success/failure cases.

Do not catch the `0` exit code

---

.github/workflows/images-latest.yml

`GH_TOKEN` is necessary when using the `gh` CLI.
We use `gh` over in `images-branch.yml` when doing some stuff around forks, but not here in `images-latest.yml`.
I considered leaving it for consistency, and in case we ever add back `gh`. But the consistency arg doesn't make sense since `images-updater-core.yml` doesn't have this. And if we add back `gh`, we'll get an obvious error message about the problem per https://github.com/github/docs/issues/21930#issuecomment-1310122605.

Remove unused `GH_TOKEN` env var

---

updater/lib/dependabot/environment.rb
updater/lib/dependabot/updater.rb
updater/spec/dependabot/updater_spec.rb
updater/spec/spec_helper.rb

We haven't seen any jobs hit this code path in over one week of observation, so let's complete the migration and remove this code.
This PR does not address refactoring the specs into per-operation files since that is off the critical path and we've generally been treating gaps tests as no-harm, no-foul.
It does however remove a test for one "operation" that doesn't actually exist in production: creating a brand new PR for one or more specific Dependencies.
If we need this behaviour in future, it'll be relatively trivial to compose a new Operation class and test to bring it back so let's remove it for clarity for now.
Finally, I've added some notes on the plan to split and migrate the tests as well as a warning to avoid adding new tests to the old interface. I've added an issue to the …

Remove Updater#legacy_run

---

Rakefile
dependabot-core.gemspec

While auditing [our gems](https://rubygems.org/profiles/dependabot), I noticed there was a `dependabot-core` gem that hadn't been updated in years: https://rubygems.org/gems/dependabot-core/versions/0.94.13
This was probably the original gem before it was all split apart into the meta gem `dependabot-omnibus` and the subgems.
This creates confusion because the name matches the `dependabot-core` repo.
At first I planned to delete it, but then I saw the note on Rubygems that deleting a gem frees up the namespace. We would much rather own this namespace to prevent namesquatting, so I've created a placeholder gemspec that has no associated source code.
I wasn't sure if `gem` would allow building/publishing with no source code, so tested, and it all worked:
```shell
$ gem build …
```

Add a placeholder `dependabot-core.gemspec`

---

common/dependabot-common.gemspec
updater/Gemfile.lock

I think we may need some changes to adapt to version 1.15.0, in particular, to https://github.com/deitch/docker_registry2/pull/85.
In tests we stub a HEAD request which 1.15.0 no longer performs, so hopefully we just need to adapt the specs, but the new version means no behavioral changes for us.
For now I'll pin it to get CI green.

Pin docker_registry2 to 1.14.0 to fix CI

---

.github/workflows/gems-bump-version.yml
.github/workflows/gems-release-to-rubygems.yml
README.md
bin/bump-version.rb

This continues the process of streamlining our releases by adding a custom GitHub Action workflow to automate creating version bump PR's.
For now, I intentionally left it as manually triggered to keep the review straightforward and let us try it for a week or two.
Once we're sure we're happy with this, then we plan to add a workflow trigger of a regular cron task to ensure we release frequently... probably on a weekly cadence.
Related:
* https://github.com/dependabot/dependabot-core/issues/7132

Create version bump PRs using a custom action

---

.github/workflows/smoke.yml
updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/dependabot/updater/operations_spec.rb
updater/spec/dependabot/updater_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_with_ungrouped.yaml

As we start to test configured Dependency Groups, we no longer need to rely on the Updater handling empty dependency groups by failing over to a "group everything in one PR" placeholder rule.
The service is now responsible for injecting this in places where it is required, otherwise we should treat an empty `job.dependency_groups` as a sign the feature is not being invoked since this is the target production behaviour.
Removing it now will avoid any debugging confusion as we start to test more widely.
As part of making this change I migrated the test that verifies that the `GroupUpdateAllVersions` class handles mixes of grouped and ungrouped dependencies properly from the "legacy" `updater_spec.rb` into the class-specific test.
This lead on to a further change in …

[Updater] The Updater always expects job.dependency_groups to be defined

---

updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_overlapping_groups.yaml

This is a quick unit test that verifies two things:
- That we correctly parse N `dependency_groups` to perform two group update attempts
- That if two groups overlap, we will PR the same dependencies in both by design

[Updater] Add a test for two overlapping groups

---

.github/workflows/gems-bump-version.yml
updater/.ruby-version

We need to inherit the bundler version used in `updater/Gemfile.lock` when running the `gem-bump-version` GitHub action.
Otherwise when the action runs, `ruby/setup-ruby` will use a default `bundler` version, which will change `BUNDLED WITH` to this default version.
Normally that wouldn't matter, but we also pin the version of `bundler` used in the native helper for the `bundler` ecosystem. And when we run the Updater in production at GitHub, since `BUNLDED WITH` is the last time we run `bundle install`, it'll change the bundler version not only for the `updater` app, but also for the native helper. So we'd be silently getting a different version of `bundler`, but _only_ when running the `updater`, which means local debugging would see the pinned bundler version.
Instead, let's avoid all …

Make `gem-bump-version` inherit `ruby`/`bundler` versions

---

cargo/spec/dependabot/cargo/file_updater/lockfile_updater_spec.rb

The `cargo update` command tested here can fail because of two reasons:
* The version of the dependency we're updating to does not exist (time 99.0.0).
* The version of an unrelated dependency we're locked to does not exist (regex 99.0.0).
This spec is checking for the latter, but `cargo update` may throw either error inconsistently.
Let's force a valid version of time to update to, so that the second error is always raised.
Example of the error: https://github.com/dependabot/dependabot-core/actions/runs/4892537905/jobs/8734412290?pr=7222#step:5:176
```
Failures:
1) Dependabot::Cargo::FileUpdater::LockfileUpdater#updated_lockfile_content when updating the lockfile fails because an existing requirement is no good raises a helpful error
Failure/Error:
expect { …
```

Fix flaky cargo spec

---

bin/dry-run.rb
bundler/lib/dependabot/bundler/update_checker.rb
bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb
bundler/spec/dependabot/bundler/update_checker/requirements_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb
cargo/lib/dependabot/cargo/update_checker.rb
cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb
cargo/spec/dependabot/cargo/update_checker/requirements_updater_spec.rb
cargo/spec/dependabot/cargo/update_checker_spec.rb
common/lib/dependabot/dependency.rb
composer/lib/dependabot/composer/update_checker.rb
composer/lib/dependabot/composer/update_checker/requirements_updater.rb
composer/spec/dependabot/composer/update_checker/requirements_updater_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/requirements_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/requirements_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
python/lib/dependabot/python/update_checker.rb
python/lib/dependabot/python/update_checker/requirements_updater.rb
python/spec/dependabot/python/update_checker/requirements_updater_spec.rb
python/spec/dependabot/python/update_checker_spec.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/job_spec.rb
updater/spec/dependabot/updater_spec.rb

Trying to retry #5581, but in a correct way now.
Fixes #5569.

Fix `lockfile-only` versioning strategy not creating some updates that are expected (v2)

---

updater/lib/dependabot/job.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/job_spec.rb

Currently finding a way to reproduce issues found in Sentry can be challenging, usually the easiest way is to find a public project that we can run our code against. Today this is hard, because we need to manually comb the errors in sentry until we find one that's public.
With this change, that should no longer be an issue.

Add tag to indicate if repo is private in sentry reports

---

updater/lib/dependabot/updater/operations/group_update_all_versions.rb

As described, this is just a small presentation tweak.

[Updater] Explain why we defer groups with existing PRs when all groups are triggered

---

updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb

Noticed while debugging something else, we don't have our usual markers in the logs when we start a rebase job for a group, so let's add them.
I've also split out the `perform` method to avoid a long method warning and push the error handling around update/close calls into its own method.

[Updater] Add missing log lines to job startup

---

Dockerfile.updater-core
updater/Gemfile.lock

We've seen reports of [this error](https://github.com/rubygems/rubygems/issues/6614), and Bundler 2.4.13 should fix it!

Update Bundler to 2.4.13

---

updater/lib/dependabot/job.rb

Noticed in https://github.com/dependabot/dependabot-core/issues/7223, when running a CLI job without credentials can result in a NilClass error due to `credentials_metadata` not existing.
Defaulting the value to `[]` fixes it. 
This isn't something that can happen in production, more of a user-friendly feature for folks who haven't set up a LOCAL_GITHUB_ACCESS_TOKEN.

fix NilClass error on credential-less runs

---

.github/workflows/images-updater-core.yml

When the images were split, this was updated to push to GHCR rather than Dockerhub.
In fact, you can see here the last image was pushed 3 months ago: https://hub.docker.com/r/dependabot/dependabot-core/tags
But this reference to dockerhub wasn't updated.
Note:
This pushes the `dependabot-updater-core` image to GHCR, but not the ecosystem-specific images... that was likely an oversight. Correcting that is outside the scope of this PR though.

Fix outdated reference to DockerHub

---

.github/workflows/gems-release-to-rubygems.yml

Watching for tags works, but introduces the risk that an unexpected tag name that happens to match the regex will trigger a push.
Additionally, a tag on a branch other than `main` could trigger the workflow as well.
By limiting only to actual releases, we ensure that we only push to RubyGems when we actually publish a release.
Related:
* https://github.com/dependabot/dependabot-core/issues/7132

Switch to watching releases rather than tags

---

cargo/Dockerfile

See https://github.com/rust-lang/rust/releases/tag/1.69.0
And https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html

build(deps): bump Rust from 1.68.2 to 1.69.0

---

updater/lib/dependabot/updater/group_update_creation.rb

Fixes https://github.com/dependabot/dependabot-core/issues/7238
This PR attempts to address the root cause of npm transitive dependencies generating `NoChangeErrors` during grouped updates.
Here's the error we're seeing:
```
2023/05/05 11:49:01 INFO Checking if @typescript-eslint/typescript-estree 5.27.1 needs updating
2023/05/05 11:49:02 INFO Latest version is 5.59.2
2023/05/05 11:49:03 INFO Requirements to unlock own
2023/05/05 11:49:03 INFO Requirements update strategy widen_ranges
2023/05/05 11:49:03 INFO Updating @typescript-eslint/typescript-estree from 5.27.1 to 5.59.1
2023/05/05 11:49:03 ERROR Error processing @typescript-eslint/typescript-estree (Dependabot::NpmAndYarn::FileUpdater::GroupedSubDependencyUpToDate)
2023/05/05 11:49:03 ERROR Subdependency is already up-to-date …
```

Reparse dependencies after each batch when performing grouped updates

---

common/lib/dependabot/git_metadata_fetcher.rb

When metadata source configured for a release is not accessible by Dependabot, the `git ls-remote` command to find release tags will hang with a prompt asking for user credentials.
I don't think this is a problem in production, or CI, probably because `git` detects automatically that it's being run in a non interactive environment. However, when running specs manually, it shows a prompt. This can be reproduced for example by running the following from the cargo folder:
```
$ rspec spec/dependabot/cargo/update_checker/version_resolver_spec.rb -e "raises a GitDependenciesNotReachable error"
Run options: include {:full_description=>/raises\ a\ GitDependenciesNotReachable\ error/}
Randomized with seed 30240
Username for 'https://github.com':
```
Dependabot is not supposed to be run …

Don't hang when metadata source is not accessible

---

go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb

The Go updater code has two code paths. The more common one is it uses the cloned repo to do updates, first doing a `git reset`, not using the manifests that were fetched.
The other path only happens when a clone fails and there's no vendoring (and other specific conditions) where it will write out a dummy project that imports all dependencies so that the update can proceed with imperfect information.
The problem is when Grouped Updates comes along, the Go code needs to write the manifests to disk each time since they get wiped out between updates of the dependencies with that `git reset`.
So this PR passes in the dependency_files to the GoModUpdater so it can overwrite what is on disk each time, and make the Grouped Update successful.

Go: fix grouped updates missing updated dependencies in manifests

---

gradle/lib/dependabot/gradle/file_updater.rb
gradle/spec/dependabot/gradle/file_updater_spec.rb
gradle/spec/fixtures/buildfiles/build_same_groupId_different_artifactId.gradle

With the current implementation, any line matching the requirement is upgraded. That leads to undesired side effects as described in the issue
Fixes #7002

fix(gradle): update dependencies only if group and artifact ids are the same

---

.github/workflows/codeql-analysis.yml

CodeQL is complaining that these two files are unparsable Ruby:
```
[2023-04-20 07:34:33] [build-stdout] [2023-04-20 07:34:33] [build-stdout]  WARN /home/runner/work/dependabot-core/dependabot-core/bundler/spec/fixtures/projects/bundler1/invalid_ruby/Gemfile:2: A parse error occurred. Check the syntax of the file. If the file is invalid, correct the error or exclude the file from analysis.
[2023-04-20 07:34:33] [build-stdout] [2023-04-20 07:34:33] [build-stdout]  WARN /home/runner/work/dependabot-core/dependabot-core/bundler/spec/fixtures/projects/bundler2/invalid_ruby/Gemfile:2: A parse error occurred. Check the syntax of the file. If the file is invalid, correct the error or exclude the file from analysis.
```
These two files are test specs and intentionally unparsable, so ignoring …

CodeQL: ignore purposefully invalid ruby files

---

common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb
common/spec/dependabot/pull_request_creator_spec.rb

As described, changes the branch naming from:
> dependabot/ecosystem/group-name/prototype-1683734594
to
> dependabot/ecosystem/group-name-1683734594
We maintain the timestamp to avoid jobs recreating group PRs colliding but drop the word 'prototype' as we've got enough working we're moving towards beta

[Grouped Updates] Remove prototype from branch names

---

.github/workflows/gems-bump-version.yml

I kept having problems while testing https://github.com/dependabot/dependabot-core/pull/7324/ until I realized that because I was doing my testing on a branch, `actions/checkout` was starting from the branch and then opening a PR against `main`, so it included not only the commit generated within this workflow, but also whatever other commits I'd made during my testing.
For this particular workflow, we always want to start from `main` as we're building a PR that should only contain the version bump commit.

Ensure we start from `main` even if workflow run from a branch

---

.github/workflows/gems-bump-version.yml

Adding an App Token to the release workflow so CI jobs run.
This App Token is currently stored as an actions secret. Actions prevents forks from reading secrets, so we'd have to explicitly merge a PR in order to leak the secret. Actions also redacts secrets, so we should be mostly safe from typos.
If we later decide we want to protect it further, we have two options:
1. Migrate it to a deployment secret for increased security. This way _any_ workflow run accessing the secret requires explicit approval from the maintainers. Unfortunately, the workflow will just hang in a "waiting" state, but not easily notify the user that it needs approval. I prototyped the workflow, and it was pretty clunky--we had to trigger the workflow, remember to manually approve it, and only then the PR shows up... …

Add App Token to release workflow so CI jobs run

---

README.md

Pickup a minor format tweak I noticed while working on duplicating the release process over to another repo... this just looks a little better.

Minor format tweak to readme instructions for releasing

---

.github/workflows/gems-bump-version.yml

This adds a workflow trigger that goes off every Thursday. This way we are reminded to release weekly.
If the version bump PR is already open because it hasn't yet been merged from the previous week, then this workflow will bomb out when it tries to push the branch, since the branch name is idempotent.
Fix: https://github.com/dependabot/dependabot-core/issues/7132

Schedule the release PR to arrive weekly

---

.github/workflows/gems-release-to-rubygems.yml

Clarify that we're safe to run on every release.
Also clarify the expected scope of the API key so that if someone rotates it, they remember to limit the scope of it.
Related:
* https://github.com/dependabot/dependabot-core/issues/7132

Minor cleanup on the publish RubyGems action

---

updater/lib/dependabot/dependency_change_builder.rb

Ensures that (a) a dependency whose version has changed but whose requirements have not changed is still included in the generated dependency change instance, and (b) a dependency whose requirements have changed but whose version has not changed is still included in the generated dependency change instance.
Should unblock https://github.com/dependabot/smoke-tests/pull/72

Ensure updated dependencies are correctly included when building dependency change instance

---

common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb
common/spec/dependabot/pull_request_creator/branch_namer/dependency_group_strategy_spec.rb

Grouped update Pull Requests will generally have more dependencies that we can tolerate in the branch name compared to solo dependency PRs, but we rely on deterministic branch names to avoid race conditions where we retry pushing a branch that has already been successfully pushed.
The current behaviour of appending a timestamp is resulting in us opening the odd duplicate when something causes us to backoff and partially retry opening the PR, see:
- https://github.com/github/dependabot-action/pull/949
- https://github.com/github/dependabot-action/pull/950
This fixes the bug by updating the branch naming strategy for groups to use a short ( 10 character ) digest hash of the dependency changes.
This will ensure that if we open a new PR for the same group with different versions or …

[Grouped Updates] Generate deterministic branch names based on content

---

github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/spec/fixtures/workflow_files/workflow.yml

In github_actions, it's valid to use symbol, date and time objects in your workflow yaml files. Up until now, Dependabot was failing parsing on these, as the classes are by default not allowed by `YAML.safe_load`, this changes that to match the behavior in GitHub.

Allow parsing symbols, time and date values in workflow yaml

---

updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb

Fix for https://github.com/dependabot/dependabot-core/pull/7310
When testing #7310 yesterday we realised that any attempt to 'rebase', i.e. call the `update_pull_request` endpoint, from within a scheduled `GroupUpdateAllVersions` job fails as the endpoint expects the job to specify a _single_ target PullRequest to update.
After discussing this, we realised that having rebases happen within the scheduled job is something we can and should defer - rebases should honour the user configuration and only be triggered when the branch goes into conflict, it's not intentional nor well understood that we rebase during a schedule for some PRs right now.
This change course-corrects our approach so that the delegation to the `RefreshGroupUpdatePullRequest` will defer rebases but will replace or …

[Updater] When a Dependency Group is refreshed as part of a scheduled GroupUpdateAllVersions, it defers rebasing

---

common/lib/dependabot/dependency_group.rb
common/spec/dependabot/dependency_group_spec.rb
updater/lib/dependabot/job.rb
updater/spec/dependabot/dependency_group_engine_spec.rb
updater/spec/fixtures/jobs/job_with_dependency_groups.json

This uses an `exclude-patterns` key from the Dependabot update config that behaves the same way as the regular `patterns` key, but will exclude any matching dependencies from a grouped update.
The tests for this are somewhat minimal, so if you think this would require more testing before we deploy please don't hesitate to let me know.

exclude patterns for grouped updates

---

common/lib/dependabot/pull_request_creator/message_builder.rb

Adds a newline for grouped update intros.

Add a newline after the group intro

---

Dockerfile.updater-core

Fixes https://github.com/dependabot/dependabot-core/issues/7438
The official Docker Ruby image tags used to default to Debian Bullseye, but now that there's [a new release of Debian](https://www.debian.org/releases/), the Docker image points to the new release.
This breaks things when we try to build or run Core:
```
> [stage-0 32/33] RUN gem install bundler -v 2.4.13 --no-document &&  rm -rf /var/lib/gems/*/cache/* &&  bundle config set --global build.psych --with-libyaml-source-dir=/home/dependabot/src/libyaml/yaml-0.2.5 &&  bundle config set --local path 'vendor' &&  bundle config set --local frozen 'true' &&  bundle config set --local without 'development' &&  bundle install &&  rm -rf ~/.bundle/cache:
#0 0.188 /usr/local/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' …
```

Use ruby:3.1.4-bullseye

---

github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

Previously we would avoid updating requirements if the commit for the dependency does not match the commit for the updated reference.
The commit for the dependency is guessed by the `GitCommitChecker` using the _first_ source as the dependency source. However, this can be inaccurate when updating dependencies with sources with mixed versions, since they may point to different commits.
I think this is an issue in the `GitCommitChecker` but I also noticed that these checks should not be necessary, we can unconditionally update the source, even if the commits don't match.
Fixes https://github.com/dependabot/dependabot-core/issues/7384.

Fix edge case when updating Actions with mixed versions

---

updater/lib/dependabot/updater/dependency_group_change_batch.rb
updater/lib/dependabot/updater/group_update_creation.rb

This PR moves the management of the overall Dependency list into the `GroupDependencyFileBatch` class and repositions it as a `DependencyGroupChangeBatch`.
This affords us an interface where we just pass in each `DependencyChange` and the right thing happens internally to the `DependencyGroupChangeBatch` for both the files and dependency list without the actual group updater worrying about the details.
I've had a walk through the implications of us updating a Dependency twice in a single group, this has the potential to happen more for transitive dependencies if we do something like:
- `dep_a` and `dep_b` both depend on `dep_x`
- We update `dep_a` which unlocks updating `dep_x` to the highest version currently permitted by `dep_b`
- We update `dep_b` which now unlocks updating `dep_x` to …

[Grouped Updates] Cleaner management of the update dependency list

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/dependabot/updater_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_with_existing_pr.yaml

~~Follows on from https://github.com/dependabot/dependabot-core/pull/7310~~
This extracts `CreateGroupUpdatePullRequest` as a sibling class to `RefreshGroupUpdatePullRequest` and removes all responsibility for actually processing groups into PullRequests from `GroupUpdateAllVersions` so its sole responsibility is co-ordination of which strategy to use for each group.

[Updater] Extract creation of new group Pull Requests into a discrete class

---

updater/lib/dependabot/service.rb
updater/lib/dependabot/updater.rb
updater/lib/dependabot/updater/error_handler.rb
updater/lib/dependabot/updater/errors.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/updater/error_handler_spec.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb

This resolves some `FIXME` statements where we were silently substituting the `DependencyGroup#name` for `Dependency#name` as a 'good enough' workaround for the `handle_dependabot_error` method requiring a dependency to be passed.
This PR splits the `handle_dependabot_error` into two flavours:
- handle_dependency_error - this is effectively the same as the existing `handle_dependabot_error` method
- handle_job_error - this is a separate signature for cases where the context does not include a specific Dependency which can be used in places where the `FIXME` was noted
As part of this I've also split the `log_error` method into `log_dependency_error` and `log_job_error` flavours for the same reason.
For now, I've settled for sending the `dependency_group` as part of the information we sent …

[Updater] Avoid mis-representing a Dependency Group as a Dependency in error handling

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb

Pnpm is now available to everyone so we can remove the experiment flag.

Remove pnpm experiment flag

---

pub/Dockerfile
pub/helpers/pubspec.lock
pub/helpers/pubspec.yaml
pub/spec/dependabot/pub/update_checker_spec.rb

Also upgrades other dependencies of pub/helper
New in this pub-commit:
```
git log --format="%C(auto) %h %s" 554b3c32f71ff96ca03fb8b40c367b1fa564c239...a167
63a93b5050c6a9d917fca5a132cfcb00f1a9 
a16763a9 Validate that dependency names are valid package names (#3940)
4a109f30 Expand constraint for `http` (#3930)
8aee9515 Retry package:http ClientException (#3939)
d7fa780d Add test for publish --skip-validation (#3935)
5a3f21b4 Add strict-cast analysis option (#3919)
fbb6f750 Merge pull request #3934 from sigurdm/cherry_pick_cache_warning
0dc18c02 Merge remote-tracking branch 'origin/master' into cherry_pick_cache_warning
fe6acca8 Warn about presence of legacy cache (#3921)
0c2b0bb8 Handle pubspec_overrides.yaml in `add` and `upgrade --major-versions` (#3920)
078c7fea Handle version not …
```

Roll pub. Use dart 3 for running helpers.

---

Dockerfile.updater-core
README.md

Describe usage of `DEPENDABOT_HOME` environment variable to determine whether Dependabot is running or not.
in favor of https://github.com/dependabot/dependabot-core/issues/7048

Add `DEPENDABOT` environment variable for users

---

common/lib/dependabot/file_parsers/base/dependency_set.rb

While working on #7344 I was experimenting with adding some metadata to dependencies during file parsing that I would then use in subsequent steps. But I noticed that metadata is not being passed around.
I _think_ this is a bug introduced by 3a0f9950396b46421eb5009836f87809d6f88388, but I'm opening this PR and running CI to make sure I'm not missing anything.

Instantiate less dependencies

---

github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/spec/dependabot/github_actions/file_parser_spec.rb
github_actions/spec/fixtures/workflow_files/inconsistent_case.yml

Fixes a small GitHub Actions edge case where we'll get a `Multiple sources!` error instead of proper updates.

Fix actions updates when inconsistent casing is used

---

.github/workflows/codeql-analysis.yml

This reverts commit 8cc1dd7c337b9b451be5cefc7dd6dfc4fa10083d, since [the upstream issue ](https://github.com/github/codeql/issues/13103) is now fixed (I think).

Revert "Pin CodeQL version (#7275)"

---

Dockerfile.updater-core
updater/Gemfile.lock

Closes #7273 through https://github.com/rubygems/rubygems/pull/6694.

Update Bundler to 2.4.14

---

Dockerfile.development
common/spec/spec_helper.rb

This makes tests have less side effects.
For example, if you run tests locally (outside of the development image), you'll end up with your git user set as `dependabot-ci`. That actually leaked into a PR we merged recently:

Configure git with ENV

---

common/spec/dependabot/shared_helpers_spec.rb

In an ensure block, this tries to delete the temporary file it creates, but since we mocked creation, it fails. So mock deletion too.
I don't know why this does not fail normally, but it does fail when running the spec in isolation:
```
$ rspec spec/dependabot/shared_helpers_spec.rb:531
Run options: include {:locations=>{"./spec/dependabot/shared_helpers_spec.rb"=>[531]}}
Randomized with seed 16877
F
Failures:
1) Dependabot::SharedHelpers.with_git_configured when the host has run out of disk space is expected to raise Dependabot::OutOfDisk
Failure/Error: specify { expect { configured_git_config }.to raise_error(Dependabot::OutOfDisk) }
expected Dependabot::OutOfDisk, got #<Errno::ENOENT: No such file or directory @ apply2files - /home/dependabot/.gitconfig> with backtrace:
Finished in …
```

Fix flaky spec

---

common/lib/dependabot/shared_helpers.rb
common/lib/dependabot/workspace.rb
common/lib/dependabot/workspace/base.rb
common/lib/dependabot/workspace/git.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/dependabot/workspace/git_spec.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/support/dummy_pkg_helpers.rb

Merges into https://github.com/dependabot/dependabot-core/pull/7404
We've updated the group update strategy to avoid polluting the manifest files passed into each instance of Dependabot Core objects with changed vendored files, but the problem with this is that we also revert the project-on-disk to the state it was in before the previous update **and only copy the manifest back in**.
This means it is up to the native package manager to re-download the vendor files that changed in the previous step as well as the current step, which over time results in us replacing the same files over and over. Whether this is cached or we end up fully re-downloading binaries can end up being an implementation detail of the tools we shell out to, so we can't really rely on this long-term.
This branch …

[Grouped Updates] Utilise a git-backed workspace for each group so we retain vendor file changes properly

---

.github/workflows/smoke.yml

We've been running these tests nightly, but let's start adding them to CI builds to avoid regressions.
The bundler+vendoring spec might be worth dropping eventually, but since the code involved is still subject to change we'd prefer not to see regressions in the next few months.

Add smoke tests for go, npm and bundler+vendoring

---

terraform/Dockerfile

Release notes 
https://github.com/hashicorp/terraform/releases/tag/v1.5.1
https://github.com/hashicorp/terraform/releases/tag/v1.5.2

build(deps): bump Terraform from 1.5.0 to  1.5.2

---

updater/lib/dependabot/file_fetcher_command.rb

There's no point in recording the versions on GHES / non-cloud instances because we can't access that data for telemetry purposes. So put it behind a feature flag.
This will also make it so later on when we do the rename of `record_package_manager_version` to `record_ecosystem_versions`, there is less to worry about for backwards incompatible changes on GHES.
Before merging this, first need to merge the internal change that sets this feature flag, so that we don't lose visibility on cloud after we merge it.
Related:
* https://github.com/dependabot/dependabot-core/pull/7492
* https://github.com/dependabot/dependabot-core/pull/7517

Only record ecosystem versions when flag set

---

hex/spec/dependabot/hex/update_checker_spec.rb

The previous token was tied to a user account of someone who is no longer on the Dependabot team. When I removed that user from the Hex org, this [test started breaking](https://github.com/dependabot/dependabot-core/actions/runs/5487053978/jobs/9997970150?pr=7525).
So this updates the token to an organization-based token, which is not tied to any user.
This is a read-only token, which has access to _all_ private packages in the https://hex.pm/orgs/dependabot org.
This is a security risk if we don't realize this and accidentally upload a private test package to this organization that we don't want to make public, but there's currently no way to prevent that other than using two separate organizations.
I filed a feature request upstream:
* https://github.com/hexpm/hexpm/issues/1205

Update the `hex.pm/orgs/dependabot` token

---

composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb
hex/spec/dependabot/hex/update_checker_spec.rb

After I rotated the Gemfury/Hex.PM tokens, these unit tests started failing, which made us realize we've been exposing the account tokens in the clear.
Historically this was fine because:
1. These private registries were used solely for test accounts, it didn't matter if they were compromised.
1. Dependabot was a startup manned by a small team, so everyone knew these registries were publicly exposed and shouldn't be re-used for anything private.
However, :two: is no longer true... now that :dependabot: is part of GitHub, the team has grown so there's a risk that someone could upload something that should stay private to these orgs.
Unfortunately, neither Gemfury nor Hex.PM support limiting the scope of a token to particular package(s). So while they're read-only, they still expose …

Stop exposing real account tokens in plaintext

---

bin/dry-run.rb
bundler/lib/dependabot/bundler/file_fetcher.rb
cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb
common/lib/dependabot/file_fetchers/base.rb
go_modules/lib/dependabot/go_modules/file_fetcher.rb
go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
updater/lib/dependabot/api_client.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/service_spec.rb

This flips the `updater` to calling the new `record_ecosystem_versions`
endpoint.
Additionally, this flips the per-ecosystem implementations of
`package_manager_version` to this new `ecosystem_versions` hash.
Note that we expect the shape of the data to be slightly different in
the long term for these metrics... ie, we plan to record a
`min`/`max`/`raw` or something along those lines for the range of
versions supported by the manifest.
However, changing that will be done in separate PR's for easier
review/discussion/audit of those individual ecosystems.
Related:
* https://github.com/dependabot/dependabot-core/pull/7492
* https://github.com/dependabot/dependabot-core/pull/7516

Switch to using the new `record_ecosystem_versions` endpoint.

---

npm_and_yarn/Dockerfile

Changelog: https://github.com/yarnpkg/berry/compare/@yarnpkg/cli/3.5.0...@yarnpkg/cli/3.6.0

buid(deps): bump Yarn from 3.5.0 to 3.6.0

---

updater/lib/dependabot/dependency_snapshot.rb
updater/spec/dependabot/dependency_snapshot_spec.rb

With the changes made in https://github.com/dependabot/dependabot-core/pull/7548 we have a clear touch-point as to when groups are hydrated from the configuration at job startup.
This follows up on that to correct and oversight where the feature flag / experiment for grouped updates didn't stop us attempting to interpret your group config if the feature was disabled.
At this point we're in public beta so this experiment is generally true in production but this reduces the splash radius for anyone using the CLI and ensures that the feature flag is a proper circuit breaker if we need to turn things off temporarily.

[Grouped Updates] Don't instantiate any groups without the feature flag

---

docker/Dockerfile

https://github.com/regclient/regclient/releases/tag/v0.5.0

build(deps): bump REGCTL from 0.4.8 to 0.5.0

---

Dockerfile.development
terraform/lib/dependabot/terraform/file_parser.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb

Fixes #5841 by using a regex to determine if interpolation syntax is used anywhere in a source.

Detect interpolation in terragrunt sources and skip if present

---

terraform/spec/dependabot/terraform/file_parser_spec.rb

Stubs out a registry request that's not captured by a VCR. The test fails when the VCR mode is set to `:none` as part of https://github.com/dependabot/dependabot-core/pull/4822
See https://github.com/dependabot/dependabot-core/actions/runs/4957979462/jobs/8870303817?pr=4822#step:5:223 for the error

Stub registry request that's not captured by a VCR

---

common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

The different sections of the metadata go through the LinkAndMentionSanitizer twice.
Once per sub section and once as the complete message.
In case of source providers that support HTML that is not a problem. The Markdown is converted to HTML and after that left alone.
In case of a source provider that does not support HTML (like bitbucket) there is a problem.
The links in the markdown are converted from github.com to redirect.github.com. And in the second pass the links are converted from redirect.github.com to redirect.redirect.github.com.
This PR contains a fix so only the second pass will convert the links in case the source provider does not support HTML.

Prevent links in PR description that link to redirect.redirect.github.com

---

.devcontainer/core-dev/devcontainer.json
Dockerfile.development

We split the monolith docker image into per-ecosystem images. The `dependabot/dependabot-core` image was replaced by `dependabot/dependabot-updater-core`.
Additionally, we don't publish this new image to Dockerhub, but only to GHCR.
So this corrects the references to it.
This is mostly the great work of @dwc0011 from:
* https://github.com/dependabot/dependabot-core/pull/7458
However, the scope of that PR is starting to get a bit larger, and we'll need to have more conversations about the best way forward. It's unclear if we should even have a default `FROM` value vs always forcing it to be set. But that's a bigger conversation.
So for now I extracted this smaller set of changes out so we can at least stop referencing an old Dockerfile that we no longer update.

Use the new base image

---

bin/docker-dev-shell

I found it handy to have access to these while debugging some `updater` code.

Mount `updater/bin` into the docker dev shell

---

.github/workflows/smoke.yml

This updates the command to match the smoke invocation used in the CLI and proxy.
This should hopefully reduce mistakes creeping in like https://github.com/dependabot/cli/pull/148 where I copy/pasted not realizing there was a slight difference between the two repos.
Related:
* https://github.com/dependabot/cli/pull/150
* https://github.com/dependabot/cli/pull/148

Match the smoke test invocation of CLI/proxy

---

composer/lib/dependabot/composer/helpers.rb
composer/lib/dependabot/composer/native_helpers.rb
composer/spec/dependabot/composer/helpers_spec.rb

The `"v"` prefix isn't part of the version, for example if we report metrics on it. It's only needed for building the path to the helper.
Extracted from:
* https://github.com/dependabot/dependabot-core/pull/7323

Only add `"v"` prefix for the helper path

---

npm_and_yarn/Dockerfile
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb

Upgrades the Node.js version that dependabot uses to the latest active LTS (Long Term Support) version which is 18.x. https://nodejs.org/en
* Dependabot currently uses a `Maintenance LTS` version of Node.js instead of a `Active LTS` version. https://nodejs.dev/en/about/releases/
* We run into the following issue since we have `engine-strict` enabled and want to avoid 
```
Dependabot uses Node.js v16.20.0
and NPM 8.19.4
. Due to the engine-strict setting, the update will not succeed.
```
* https://github.com/dependabot/dependabot-core/issues/4072#issuecomment-1413222679
* https://github.com/dependabot/dependabot-core/pull/7194 
* https://zenn.dev/risu729/articles/dependabot-engine-strict

Upgrade Node.js to active LTS version (18.x)

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/smoke.yml

Sometimes when working on fixing CI you may need to push several times. For these cases, I think it makes sense to automatically cancel previous runs in the same branch.

Cancel previous jobs in the same branch when repushing

---

.github/workflows/smoke.yml

On a passing smoke test workflow, you still get some Red Cross annotations.
They don't make the build fail, but can be distracting.
Trying to not run them when not necessary.

Don't try to diff if there's nothing to diff

---

.github/workflows/smoke.yml

To get out of chicken and egg situations, like when adding a new ecosystem.

Make smoke tests cache optional

---

.github/dependabot.yml

Use wildcard matching to aggregate prod and dev updates into two separate groups

Aggressively group prod and dev dependencies for NPM

---

maven/lib/dependabot/maven.rb
maven/spec/dependabot/maven_spec.rb

Fixes #3845
Depends on https://github.com/dependabot/smoke-tests/pull/59/files
Implemented just like #6526 as suggested

feat(maven): use `groupId` and `artifactId` for the dependency name

---

python/lib/dependabot/python/file_fetcher.rb

While working on adding python version metric to the file fetcher, it was starting to get confusing what the pre-existing `python_version` var referred to... so rename it to be explicit that it refers to the `.python-version` _file_.

Rename `python_version` -> `python_version_file` for clarity

---

Rakefile

It will happen the first time we release a new ecosystem.
I don't see any harm in allowing it?

Allow gem does not exist in RubyGems case

---

python/README.md

We broke the monolithic docker image into per-language images. So point the link at the Python one.
Also update to a PR that bumped python using this new dockerfile so that we have a better example. It's not perfect as it doesn't bump the `pyenv global` var, but it's the best we've got right now. We can replace it with the [`3.12` PR in October](https://peps.python.org/pep-0693/).

Point at the correct `Dockerfile` for python

---

python/lib/dependabot/python/file_fetcher.rb
python/spec/dependabot/python/file_fetcher_spec.rb

We want to know what versions of python are required by our users, so this is an initial stab at collecting some data.
Ideally we capture the minimum version, the maximum version, and the raw data from each manifest file that allowed us to calculate the min/max... this won't be quite so clean/polished, but we need to start somewhere and even a primitive form of this metric will provide enough information for us to understand the user impact of dropping python 3.6.

Instrument Python version metric

---

.github/dependabot.yml

Excluding `detect-indent` for this reason: see https://github.com/dependabot/dependabot-core/pull/5683#issuecomment-1243468605

Update dependabot.yml to capture by package manager

---

cargo/lib/dependabot/cargo/file_fetcher.rb

I would like help for writing a test, I have found `cargo/file_fetcher_spec.rb`, but I don't
understand how it works.
Closes #5864

fix: correctly find workspace.dependencies-declared dependencies and their Cargo.toml

---

common/lib/dependabot/dependency_group.rb
common/spec/dependabot/dependency_group_spec.rb
updater/spec/dependabot/dependency_group_engine_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_by_dependency_type.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_semver_grouping.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_semver_grouping_with_global_ignores.yaml

This merges into #7581 and changes the way this rule is configured:
```yaml
groups:
rails:
patterns:
- "rails*"
update-types: ["minor", "patch"]
```
If `update-types` is not specified, we default to `["major", "minor", "patch"]`, i.e. all versions.

[Grouped Updates] Refactor how SemVer groups are configured

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/dependency_change_spec.rb

To remove ignore conditions on the dependencies on a given pull request user needs to have option to view those conditions. This task is to implement that for the user.  The PR body should look something like below:
**PR Body**
Dependabot Ignore Conditions Applied on the Pull Request
|Dependency Name| Ignore Condition|
|-|-|
business| [< 1.9, >1.8.0]|
business| [< 1.6.0, >1.3.0]|
statesmen| [< 1.2.0, >1.1.0]|
The user will use the ignore condition mentioned in the PR body and will use the upcoming new [unignore command](https://github.com/github/dependabot-updates/issues/4424) to remove those conditions on a specific dependency.
Fixes: https://github.com/github/dependabot-updates/issues/4478
In the PR body, displaying top 20 lasted ignore conditions (if any) sorted by `created_at` or …

Show ignore conditions in a request  body

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb

The exclusion for these two packages was added years ago by Grey, back when Dependabot ran on a completely different service back-end.
Since then, much of our internal infra has been completely rewritten and any failures with deps in prod can invariably be repro'd locally, so it no longer makes sense to carve out these exclusions.
I suspect the underlying issue in `composer` that led to this problem has likely been fixed (at least in `composer 2`) so we won't see this problem.
But if for some reason we do, than we should investigate further to see what the _root_ problem is rather than swallowing it.

Remove manual exclusion of specific packages

---

swift/lib/dependabot/swift/update_checker.rb
swift/lib/dependabot/swift/update_checker/version_resolver.rb
swift/spec/dependabot/swift/update_checker_spec.rb
swift/spec/fixtures/projects/ReactiveCocoaNested/subfolder/Package.resolved
swift/spec/fixtures/projects/ReactiveCocoaNested/subfolder/Package.swift

The update checker temporarily tries to update versions, and then parses to resulting lockfile to figure out what the latest resolvable version is.
To do this, it uses a modified manifest with unlocked depencies.
This modified manifest was not inheriting the `directory` property from the original manifest and that was causing swift to be run from the wrong folder, and thus reparsing of the updated lockfile fail.
To fix that, make sure manifests used by the UpdateChecker inherit the `directory` property from the original manifests.

Fix some swift updates failing when `directory` is configured

---

python/lib/dependabot/python/metadata_finder.rb
python/spec/fixtures/pypi/pypi_response_pendulum.json

Per the [Warehouse PyPI docs](https://warehouse.pypa.io/api-reference/json.html#project):
> The `bugtrack_url` key on this response should be considered deprecated.
>
> It currently always returns `null` and in the future, the `bugtrack_url` key may be removed from this response.

Stop checking deprecated `bugtrack_url`

---

swift/lib/dependabot/swift/native_requirement.rb
swift/spec/dependabot/swift/update_checker_spec.rb
swift/spec/fixtures/projects/ReactiveCocoa/Package.swift

I changed this method name in the last minute, and somehow forgot to update all usages 🤷‍♂️.
This typo would cause errors when updating requirements whenever the previous two conditions were not met (`from:`, or `.upToNextMajor` not used).

Fix typo in method name in Swift update checker

---

Dockerfile.updater-core
updater/Gemfile.lock

New version has a working `bundle lock --update --bundler` command, so we can bump the Bundler version locally without having to actually install any gems.
Supersedes #7497. I'm going directly to 2.4.17, because regressions were found on both 2.4.15 and 2.4.16.

Bump Bundler to 2.4.17

---

python/spec/dependabot/python/update_checker_spec.rb

Since we'll be dropping 3.6/3.7 soon, we want to ensure that users on unsupported python versions get a clearly understandable error and not a random traceback.

Test that unsupported Python versions raise the expected error

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/bitbucket.rb

Add sane limit to PR description limit for Bitbucket cloud

---

python/spec/fixtures/lockfiles/edited.lock
python/spec/fixtures/lockfiles/edited_array.lock
python/spec/fixtures/lockfiles/environment_variable_source.lock
python/spec/fixtures/lockfiles/git_source.lock
python/spec/fixtures/lockfiles/git_source_bad_ref.lock
python/spec/fixtures/lockfiles/git_source_unreachable.lock
python/spec/fixtures/lockfiles/hard_names.lock
python/spec/fixtures/lockfiles/version_hash.lock
python/spec/fixtures/lockfiles/version_not_specified.lock

Our `pipenv` fixtures are a bit outdated... when I tried to delete Python 3.6, they started failing because we've got some code that reads the python version and tries to use that to guess at what version of python to run.
However, when I tried regenerating one of these lockfiles under a newer Python, I was surprised that the entire `host-environment-markers` key disappeared.
After a little digging, I found that this key was removed in 2018, which also explains why only the older fixtures have it and not the more recent fixtures. More historical context:
* https://github.com/pypa/pipenv/issues/753
* https://github.com/pypa/pipenv/commit/ecf78424c1740bae3511c731c032a3768154072c#r28870534
* https://github.com/pypa/pipenv/commit/ecf78424c1740bae3511c731c032a3768154072c#diff-ef852c4ac364f94681 …

Delete deprecated `host-environment-markers` key

---

python/spec/dependabot/python/update_checker/pip_version_resolver_spec.rb
python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
python/spec/dependabot/python/update_checker_spec.rb

While working on the PR to drop support for Python 3.6, I noticed these specs could use some tidying up:
1. `3.7` will soon be dropped, so bumped the "latest" version to `3.11`.
2. We had no explicit test of what happens when an outdated Python version was specified.
Finally, the biggest change is removing the test of "old python version supported by Dependabot but not supported by a newer version of the library". The problem is that the test scenario, while nice to have, is becoming less realistic. 
Overall (and I say this as someone who helps maintain several popular Python open source libraries) the Python ecosystem has been aligning pretty closely to the upstream version support lifecycle. Ie, library maintainers are starting to align when they drop support for old python versions …

Fixup `pip_version_resolver` specs

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/smoke.yml

Apparently new versions on Docker (at least on v23) no longer include Gemfile.lock files inside `bundler/spec/fixtures` in the build image.
Reading our current `.dockerignore`, it seems that the new behaviour prioritizes more explicit rules (not ending with `*`) even if they appear earlier in the file.
I'm not sure if this is expected, or a bug, but we can change the entries to not be ambiguous and simplify them.

Use dockerignore rules that play better with recent docker versions

---

bundler/spec/spec_helper.rb

This helped me while debugging #7713.

Give better error message when fixture project is missing a file

---

python/helpers/requirements.txt

I couldn't figure out why we pinned `wheel` because it's not directly `import`'d until I stumbled across myself asking the same question  a year ago:
* https://github.com/dependabot/dependabot-core/pull/5597
🤣 
So let's document it to save myself from re-asking the question a year from now.

Document why we pin `wheel`

---

common/lib/dependabot/pull_request_creator/gitlab.rb
common/lib/dependabot/pull_request_updater/gitlab.rb
common/spec/dependabot/pull_request_creator/gitlab_spec.rb
common/spec/dependabot/pull_request_updater/gitlab_spec.rb

request_{creator,updater}/gitlab.rb doesn't pass the DependencyFile content_encoding to the GitLab API. This causes vendored files (in our case yarn pnp zip files) to be uploaded as text.

Set file encoding in GitLab commits

---

common/lib/dependabot/file_fetchers/base.rb

Dependabot can properly list GitLab repo contents on a given branch/commit.
This is problematic when you are, for example, testing dependabot config and the requirements files are not present on the main repository branch, but on the changed branch only. In such case, dependabot won't see expected requirements, resulting in `Dependabot::DependencyFileNotFound`.
According to the GitLab API (https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree), you have to use the `ref` argument to list the repository at a given commit/branch.
The GitLab client blindly passes all the arguments to the API itself, including the `ref_name` argument. GitLab ignores extra GET parameters, thus it wasn't erroring out.

Fetching GitLab repo contents correctly uses the ref argument

---

bundler/spec/dependabot/bundler/file_fetcher/child_gemfile_finder_spec.rb
bundler/spec/dependabot/bundler/file_fetcher/gemspec_finder_spec.rb
bundler/spec/dependabot/bundler/file_fetcher/path_gemspec_finder_spec.rb
bundler/spec/dependabot/bundler/file_fetcher/require_relative_finder_spec.rb
bundler/spec/spec_helper.rb

Before:
```
[dependabot-core-dev] ~/dependabot-core/bundler $ rspec -e "with invalid Ruby"
Run options: include {:full_description=>/with\ invalid\ Ruby/}
Randomized with seed 12398
(string):2:20: error: unexpected token tUMINUS
(string):2:     ruby -rubygems -e 'require "jekyll-import";
(string):2:                    ^                           
.(string):2:20: error: unexpected token tUMINUS
(string):2:     ruby -rubygems -e 'require "jekyll-import";
(string):2:                    ^                           
.(string):2:20: error: unexpected token tUMINUS
(string):2:     ruby -rubygems -e 'require "jekyll-import";
(string):2:                    ^                           
.(string):2:20: error: unexpected token tUMINUS
(string):2:     ruby -rubygems -e 'require "jekyll-import"; …
```

Suppress error output when evaluating invalid Ruby during tests

---

bin/dry-run.rb
common/lib/dependabot/dependency_file.rb
common/lib/dependabot/file_fetchers/base.rb
common/lib/dependabot/pull_request_creator/github.rb
common/lib/dependabot/pull_request_updater/github.rb

We have logic to fetch symlinked files through the Github API, but the logic does not work for files inside symlinked folders.
This PR tries to fix that.
This, if it works, would be an alternative to #7352, which would not need to reintroduce the bug fixed by the original PR.
Fixes #7071.

Fix fetching files in symlinked folders

---

bundler/script/ci-test
composer/script/ci-test
go_modules/script/ci-test
hex/script/ci-test
npm_and_yarn/script/ci-test
python/script/ci-test
swift/script/ci-test

That prints the actual RSpec command that gets run under the hood. If the current CI flakies are order dependent, it should allow us to reproduce them.

Enable `--verbose` when running specs

---

.github/dependabot.yml

We run the full CI suite for any PR's against `/updater`, so it can be pretty time consuming.
Let's run the `aws-sdk-*` PR's together to save CI/engineering review cycles.

Group Dependabot `aws-sdk-*` PRs

---

docker/Dockerfile

Release notes https://github.com/regclient/regclient/releases/tag/v0.5.1
> Features:
> 
> Add options to regctl index create for artifactType and subject (https://github.com/regclient/regclient/pull/490)
> Add --latest flag to regctl artifact get and regctl artifact list (https://github.com/regclient/regclient/pull/507)
> Add in memory caching support. (https://github.com/regclient/regclient/pull/510)
> Fixes:
> 
> Fix typo in OCI annotations (https://github.com/regclient/regclient/pull/485)
> Support multiple dashes in repo names. (https://github.com/regclient/regclient/pull/489)
> Fix auth failures, do not trigger a backoff (https://github.com/regclient/regclient/pull/492)
> Update Go dependencies from all subdirectories and used in tests …

build(deps): bump regclient from 0.5.0 to 0.5.1

---

python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb

This method is not called anywhere in our codebase.
`git blame` shows it was added 4 years ago and used at that time, but the python version detection code has been heavily refactored since then so I didn't bother to trace where it's usage got removed.
So let's nuke it.

Delete unused method `error_certainly_bad_python_version?`

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/smoke.yml

Since CI on PRs only runs depending on changed files, I think it's good to have an after-merge full CI for every PR.
Solution taken from https://stackoverflow.com/a/70972844/143243.

Don't cancel full CI runs on main

---

npm_and_yarn/Dockerfile

It seems that the Yarn team stopped publishing release notes for some reason. [My issue](https://github.com/yarnpkg/berry/issues/5369) is still waiting an official response 
In the meantime, we need to trust our tests :/ 
Changes : https://github.com/yarnpkg/berry/compare/@yarnpkg/cli/3.6.0...@yarnpkg/cli/3.6.1

build(deps): bump Yarn to 3.6.1

---

bundler/spec/dependabot/bundler/file_updater_spec.rb

No longer used since https://github.com/dependabot/dependabot-core/pull/7296.

Remove leftover setting that no longer exists

---

updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/dependency_change_spec.rb

fixes https://github.com/dependabot/dependabot-core/issues/7743
We're seeing large updates that have large PR bodies fail to create on GitHub with a 422. I think this is due to [this change](https://github.com/dependabot/dependabot-core/pull/7487) moving the truncation from the `PullRequestCreator.create` to the `MessageBuilder`, and also we started recently using the `MessageBuilder` here in the `DependencyChange` class. It didn't get the new truncation settings passed in.
For now I copy-pasted the PullRequestCreator's new switch case to add in the limit to get PRs flowing again. This code seems like it could use a refactor.

fix PR unable to create with grouped updates

---

python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb

In the versions between what we are currently on in `dependaobt-core` and the latest versions of `pipenv`, they deprecated and then completely removed the `pipenv lock [-d]` command in favor of `pipenv requirements [--dev]` command.
Since our current version of `pipenv` supports the `pipenv requirements` command, let's proactively switch to it now. That will make the future upgrade in https://github.com/dependabot/dependabot-core/pull/7715 easier.
More context:
* https://github.com/pypa/pipenv/pull/5069
* https://github.com/pypa/pipenv/pull/5091
* https://github.com/pypa/pipenv/issues/5198
* https://github.com/pypa/pipenv/pull/5200

Replace deprecated `pipenv lock` with `pipenv requirements`

---

npm_and_yarn/Dockerfile

https://github.com/pnpm/pnpm/releases/tag/v8.6.12
https://github.com/pnpm/pnpm/releases/tag/v8.6.11
https://github.com/pnpm/pnpm/releases/tag/v8.6.10
https://github.com/pnpm/pnpm/releases/tag/v8.6.9
https://github.com/pnpm/pnpm/releases/tag/v8.6.8

build(deps): bump pnpm from 8.6.7 to 8.6.12

---

common/lib/dependabot/metadata_finders/base.rb
composer/lib/dependabot/composer/file_fetcher.rb
elm/lib/dependabot/elm/update_checker.rb
hex/lib/dependabot/hex/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
nuget/lib/dependabot/nuget/file_fetcher.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/file_updater/requirement_file_updater.rb

We seem to be using different techniques to memoize results of methods.
I tried to unify this around:
* Use standard `||=` for methods that should never return nil like `updated_dependency_files`.
* Use a `defined?` guard for methods that may return nil, like the ones for fetching files if they are present.

Unify memoization

---

bundler/lib/dependabot/bundler/file_fetcher.rb
cargo/lib/dependabot/cargo/file_fetcher.rb
common/lib/dependabot/file_fetchers/base.rb
common/spec/dependabot/file_fetchers/base_spec.rb
composer/lib/dependabot/composer/file_fetcher.rb
elm/lib/dependabot/elm/file_fetcher.rb
go_modules/lib/dependabot/go_modules/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
nuget/lib/dependabot/nuget/file_fetcher.rb
pub/lib/dependabot/pub/file_fetcher.rb
python/lib/dependabot/python/file_fetcher.rb
terraform/lib/dependabot/terraform/file_fetcher.rb

The `fetch_file_if_present` method returns `nil` if the file is not present. That means we can't use `||=` for memoizing its result, and we'll end up retrying every time.

Fix incorrect memoizations

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb

If a repo has multiple .npmrc files, Dependabot only rewrites one of them to remove variables. NPM doesn't have an issue but Yarn 1 is not ok and errors out. 
This issue was fixed in the [PR](https://github.com/dependabot/dependabot-core/pull/6883) but one of the edge case was to leading to raise the issue again.
**Edge case:** 
User root dir contained the `.npmrc` file with it's sub-dir (foo/bar/foo1/bar1/yarn.lock). The Dependabot npm job was failing for  path `/foo/bar/foo1/bar1 ` with the below error:
```bash
updater | 2023/07/13 16:04:33 ERROR <job_694149843> Failed to replace env in config: ${ARTIFACTORY_PASSWORD}
updater | 2023/07/13 16:04:33 ERROR <job_694149843> /home/dependabot/common/lib/dependabot/shared_helpers.rb:131:in `run_helper_subprocess'
updater | 2023/07/13 16:04:33 …
```

Fixing Yarn1 erroring with failed to replace env

---

common/lib/dependabot/file_fetchers/base.rb
gradle/lib/dependabot/gradle/file_fetcher.rb
maven/lib/dependabot/maven/file_fetcher.rb
nuget/lib/dependabot/nuget/file_fetcher.rb

The `fetch_file_if_present` method is used for fetching optional files. So it should tolerate "Not found" errors. Currently it does tolerate them, except when they are caused by a missing folder. For example, when looking for `.mvn/extensions.xml` and a `.mvn` directory is not there.
This PR makes it consistently ignore all "Not found" errors.

`fetch_file_if_present` should ignore all "Not Found" errors

---

gradle/lib/dependabot/gradle/file_fetcher.rb

It doesn't get in the middle of real usage, but when running file fetcher specs in isolation, it bites you:
```
[dependabot-core-dev] ~/dependabot-core/gradle $ rspec spec/dependabot/gradle/file_fetcher_spec.rb:345 
Run options: include {:locations=>{"./spec/dependabot/gradle/file_fetcher_spec.rb"=>[345]}}
Randomized with seed 62369
F
Failures:
1) Dependabot::Gradle::FileFetcher with a script plugin fetches the buildfile and the dependencies script
Failure/Error:
FileParser.find_include_names(buildfile(root_dir)).
reject { |path| path.include?("://") }.
reject { |path| !path.include?("/") && path.split(".").count > 2 }.
select { |filename| filename.include?("dependencies") }.
map { |path| path.gsub("$rootDir", ".") }.
map { |path| File.join(root_dir, path) }.
uniq
NameError:
uninitialized …
```

Add missing `require`

---

bundler/helpers/v1/run.rb
bundler/helpers/v2/run.rb

Since https://github.com/dependabot/dependabot-core/pull/4973, we explicitly activate the proper Bundler version of top of the runner, with either `gem "bundler", "~> 1.17"` or `gem "bundler", "~> 2.3"`, depending on whether its the v1 or v2 helper.
That will error out if the proper version can't be activated.
That means we don't really need to check for versions explicitly.
Since I was at it, I also bumped the activation line for v2 to `gem "bundler", "~> 2.4"`, since that's where we are now.

Simplify Bundler native helper runners

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

Previously the ignore conditions weren't showing, because we were assuming symbol keys, when these keys are strings and formatted in kebab-case.

Update ignore condition table

---

python/lib/dependabot/python/file_updater/pipfile_preparer.rb

I had to stare at this code golf for a little bit to realize that it's enforcing that every source URL has one-and-only-one trailing slash.
I started to tweak it a little to make it more readable, but I decided instead that this is business we really shouldn't be in... Dependabot is the tool that runs the package manager, not the package manager itself. 
So if a package manager doesn't like a URL that lacks a trailing slash, it should be the one handling the coercing or raising the error, and then we transparently forward that to the user.
There are some use cases where we need to handle URL normalization for deduping purposes within Dependabot internals, but I poked around a bit and as far as I can tell they don't apply here.
So let's trust the user / package managers to do the right …

Stop coercing Pipfile source URL's to have trailing slashes

---

bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/fixtures/projects/bundler1/private_gem_source/Gemfile
bundler/spec/fixtures/projects/bundler1/private_gem_source/Gemfile.lock
bundler/spec/fixtures/projects/bundler2/private_gem_source/Gemfile

Recent Bundler versions include `bundle config set --global <source> username:password` in the error message, instead of `bundle config <source> username:password`.
But our regexp had not been updated, so the source was getting parsed as `set --global <source>`.

Fix private source authentication error message

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_preparer.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb

I found a fair bit of duplicated logic when updating NPM and Yarn lockfiles that's already implemented in `PackageJsonPreparer`. So I'm refactoring things to reuse it.

Refactor preparing `package.json` files

---

docker/lib/dependabot/docker/tag.rb
docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb
docker/spec/fixtures/docker/registry_tags/bar.json
docker/spec/fixtures/docker/registry_tags/baz.json
docker/spec/fixtures/docker/registry_tags/multiple-intermediate-words.json
docker/spec/fixtures/docker/registry_tags/openjdk.json

This is not sustainable in the long term, since we can't properly support any version schema anybody decides to use.
But it sounds like we did support this one before and unintentionally broke it, so trying to restore it.
In the future, I think we should allow people teach Dependabot what their tags look like.

Restore version schema with <version> and <build_number> with words between them

---

bundler/helpers/v2/lib/functions/lockfile_updater.rb

Just pushing this change to see which specs fail.

Fix missing cache prunes

---

.github/workflows/smoke.yml
bundler/helpers/v2/lib/functions/lockfile_updater.rb

~I will revert #7295 as part of this PR and retry it with fixed smoke tests.~
Fixes a regression introduced by #7295 and makes sure bundler group vendoring smoke tests get run so that they'll catch the same thing going forward.

Make sure Bundler group vendoring smoke tests get actually run, and pass

---

common/lib/dependabot/git_metadata_fetcher.rb

In #7789, CodeQL signaled an issue with this regexp.
I can't think of a way this can be exploited, but we can use a more performant 
regexp that matches the smart protocol
documentation at https://git-scm.com/docs/http-protocol#_smart_server_response.
In particular:
> Clients MUST validate the first five bytes of the response entity
> matches the regex ^[0-9a-f]{4}#. If this test fails, clients MUST NOT
> continue.
and:
> Clients MUST verify the first pkt-line is # service=$servicename.
> Servers MUST set $servicename to be the request parameter value. Servers
> SHOULD include an LF at the end of this line. Clients MUST ignore an LF
> at the end of the line.

Remove CodeQL warning

---

Dockerfile.updater-core

This fixes an issue where if you introduce a RuboCop offense at `bin/dry-run.rb` and run RuboCop inside a development shell, no offenses will be detected.
The explanation of why this happens is a bit complicated.
This is how a dev shell looks like
```
$ bin/docker-dev-shell bundler
[dependabot-core-dev] ~/dependabot-core $ cat .rubocop.yml
---
inherit_from: omnibus/.rubocop.yml
[dependabot-core-dev] ~/dependabot-core $ cat ../.rubocop.yml
---
inherit_from: omnibus/.rubocop.yml
[dependabot-core-dev] ~/dependabot-core $
```
There's a duplicated RuboCop configuration.
This duplication may seem harmless, but results in weird behavior of RuboCop.
In particular, exclusions are not correctly interpreted, because they are resolved using the current directory as a base, not the directory of the …

Don't copy .rubocop.yml file to updater's home folder

---

bin/docker-dev-shell

Run into the following error when running `rubocop` in a dev shell:
```
[dependabot-core-dev] ~/dependabot-core $ rubocop
No such file or directory @ rb_check_realpath_internal - /home/dependabot/dependabot-core/omnibus/script/
/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/gems/rubocop-1.50.2/lib/rubocop/target_finder.rb:109:in `realpath'
/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/gems/rubocop-1.50.2/lib/rubocop/target_finder.rb:109:in `symlink_excluded_or_infinite_loop?'
/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/gems/rubocop-1.50.2/lib/rubocop/target_finder.rb:103:in `block in wanted_dir_patterns'
/home/dependabot/dependabot-core/omnibus/.bundle/ruby/3.1.0/gems/rubocop-1.50.2/lib/rubocop/target_finder.rb:99:in `reject' …
```

Remove mount of folder that does not exist

---

common/bin/git-credential-store-immutable
omnibus/.rubocop.yml
updater/bin/update_files.rb

Let RuboCop inspect files in ecosystem bin folders

---

swift/Dockerfile

By cleaning up install artifacts.
dependabot/dependabot-core-development-swift 3.11GB
ghcr.io/dependabot/dependabot-updater-swift  2.83GB
dependabot/dependabot-core-development-swift 2.6GB
ghcr.io/dependabot/dependabot-updater-swift  2.32GB

Reduce Swift image size

---

Dockerfile.updater-core

We have a single ruby in there and don't use any version manager, so it´s not necessary.
This file is only needed to hint actions using `ruby/setup-ruby` the ruby version they should use.

Don't copy ruby version file into the updater image

---

python/Dockerfile

Deletes the apt lists for the python image.
From test:
```
Finished in 11 minutes 15 seconds (files took 1.18 seconds to load)
1146 examples, 0 failures, 22 pending
Randomized with seed 46973
```
cc dependabot/dependabot-core#946 dependabot/dependabot-core#3896

Add apt lists clean up to python Dockerfile

---

updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb
updater/spec/fixtures/vcr_cassettes/Dependabot_Updater_Operations_GroupUpdateAllVersions/when_the_snapshot_contains_a_git_dependency/creates_individual_PRs_since_git_dependencies_cannot_be_grouped_as_semver.yml

By definitions, git dependencies do not follow semver, as their version number is a hash, so these should never be included in the semver group

Do not attempt to group git dependencies as semver

---

python/helpers/requirements.txt
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb

Depends on:
* https://github.com/dependabot/dependabot-core/pull/7610
We no longer support Python 3.6, so this now always needs to happen.
I also bumped the minimum version of `poetry` up to `1.2` as that's when
the flag was added. It shouldn't matter, as python will default to the
highest version allowed by that version of python, and now that we only
support `3.7` onwards that will be the upper bound.

Remove `3.6` guard when setting `poetry config experimental.system-git-client`

---

python/lib/dependabot/python/language_version_manager.rb

Depends on:
* https://github.com/dependabot/dependabot-core/pull/7610
In the python dockerfile, we pre-install python 3.7-3.11, then `tar` it
to save space.
Now that we're not supporting python <= 3.6, we no longer have any
reason to run `pyenv install`, so we can dop that and simplify our code.

Stop manually installing python

---

python/helpers/requirements.txt

The range existed because newer versions of `poetry` had dropped
`python` `3.6` support.
Now that we've dropped `3.6`, we can go back to pinning to a
specific version for more deterministic builds.
Blocked on:
* #6299

Pin poetry to specific version

---

python/helpers/requirements.txt
python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb

Relevant breaking changes: https://github.com/jazzband/pip-tools/releases/tag/7.0.0
> Backwards Incompatible Changes:
> 
> - Default to --resolver=backtracking (https://github.com/jazzband/pip-tools/pull/1897). 
> - Drop support for Python 3.7 (https://github.com/jazzband/pip-tools/pull/1879).
So this is blocked by:
* #7702

Upgrade `pip-tools` to `7.2.0`

---

python/helpers/requirements.txt

The range was specified because newer versions of `pip` don't support
`python` `3.6`.
So now that we've dropped support for `3.6` here in Dependabot, we can
go back to pinning to a single version.
Blocked on:
* #7702

`pip` no longer requires a range

---

Dockerfile.updater-core

This reverts commit a89b3acef9b2965df6a3006851e8a5fc6a20fa41.
Turns out this is also used by rubocop in order to decide whether to apply cops that depend on specific ruby versions or not. Without this, running RuboCop inside a development shell does not run cleanly.

Revert "Don't copy ruby version file into the updater image (#7802)"

---

Dockerfile.updater-core
bin/docker-dev-shell

Putting it together with the rubocop configuration may illustrate better that these files are used together.
One more follow up to #7835 and previous PRs.
I could also add a comment here, but I'm scared to break this jumbo command 😆.

Mount .ruby-version in the dev image instead of copying it

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

I'm getting a weird test failure at #7819.
I haven't yet figured it out, but during investigation I noticed this method for adding `:all_versions` metadata to dependencies seems more complicated than necessary.

Simplify handling all versions metadata on NPM

---

Dockerfile.development
README.md
bin/docker-dev-shell
bundler/README.md
cargo/README.md
composer/README.md
docker/README.md
elm/README.md
git_submodules/README.md
github_actions/README.md
go_modules/README.md
gradle/README.md
hex/README.md
maven/README.md
npm_and_yarn/README.md
nuget/README.md
pub/README.md
python/README.md
swift/README.md
terraform/README.md
updater/README.md

Right now, if you jump into a development shell, you'll notice this:
```
[dependabot-core-dev] ~/dependabot-core $ ls ../docker/
dependabot-docker.gemspec  Dockerfile  Gemfile  lib  README.md  script  spec
[dependabot-core-dev] ~/dependabot-core $ ls docker/
dependabot-docker.gemspec  Gemfile  lib  script  spec
```
This seems a bit strange.
I think we can use the same structure as in the production updater image for development, simplifying also the Dockerfile and making the image a bit thinner (~ 50Mb).

Simplify development images

---

common/lib/dependabot/clients/gitlab_with_retries.rb
common/lib/dependabot/pull_request_creator/gitlab.rb
common/lib/dependabot/pull_request_updater/gitlab.rb
common/spec/dependabot/pull_request_creator/gitlab_spec.rb
common/spec/dependabot/pull_request_updater/gitlab_spec.rb

This fixes broken commit creation for gitlab that was introduced by: https://github.com/dependabot/dependabot-core/pull/7381
The issue here is that gitlab api only supports 2 encoding values, `base64` and `text`. Current implementation will try to pass `utf-8` as indicated by unit tests which will raise an error like: `Server responded with code 400, message: actions[0][encoding] does not have a valid value, actions[1][encoding] does not have a valid value`.
Gitlab api doc for refernce: https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions

Fix encoding option value for gitlab commit creation

---

Dockerfile.updater-core
hex/Dockerfile
swift/Dockerfile

`22.04` LTS dropped yesterday: https://ubuntu.com/blog/ubuntu-22-04-lts-released
I'm not sure of the GitHub internal infra, there may be security/infra reasons blocking
this upgrade that are not visible to external contributors, but thought I'd at least open
this PR to see what CI thinks.
For the Erlang issue, I had to install Erlang from Ubuntu Universe rather than Erlang Solutions.
Unfortunately that means we will probably lag on Erlang versions in the future.
While this isn't ideal from an Erlang perspective, this unblocks the
`22.04` upgrade, which is a bigger deal for the other ecosystems.
I'm hopeful this is only a temporary state of affairs and someone from
the community steps up to provide a PR switching to installing from
either the Erlang Solutions PPA or the RabbitMQ PPA. …

Bump underlying `ubuntu` to `22.04` LTS

---

python/lib/dependabot/python/update_checker/index_finder.rb
python/spec/dependabot/python/update_checker/index_finder_spec.rb
python/spec/fixtures/pyproject_files/pypi_explicit.toml
python/spec/fixtures/pyproject_files/pypi_explicit_lowercase.toml

Fixes #7431.
Fixes #7724.
When a github user has poetry >= 1.5.0, they will be nagged by a warning to run `poetry source add pypi`, which will add the following section to the users pyproject.toml:
[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
This causes the problem outlined in #7431, that the index_finder will fail due to this section missing a `url`.
This commit works around this issue by explicitly adding a url for the case where the source "name" is equal to "PyPI".

python: Handle explicit PyPI source in pyproject.toml

---

python/Dockerfile

I don't see a reason to double-install these apt packages. If we instead change the base for `python` `3.11` to be `python-core`, then we pick this up for free. It won't be cheaper in wall clock time since the jobs are parallel, but it saves network bandwidth/CPU/IOPS.
More importantly, it reduces the chance of developer mistakes if we accidentally add or remove a package from one place and forget to copy/paste that change.

Don't double-install packages required for building Python.

---

.github/dependabot.yml

Instead of specifying individual dependencies, we can now leverage the dependency-type config option for these, and while we're at it, let's ensure we don't include major updates in these groups, as they tend to be harder to merge and addressing them separately is usually the better option.

Use dependency-type and semver grouping for dev dependencies

---

pub/lib/dependabot/pub/update_checker.rb

Bubble up expected pub security update errors to the user

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb

For some reason, while working on #6590, I found a spec that was failing with a
```
Dependabot::SharedHelpers::HelperSubprocessFailed: Failed to clone https://github.com/no-exist-sorry/monolog to read package information from it
```
instead of the expected Dependabot::GitDependenciesNotReachable error.
It seems composer is raising a slightly different error under some situations, so tweaked the regexp to handle that.

Fix missed error matching on composer

---

updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/security_update_helpers.rb

Currently uploading dependencies through the Gradle Dependency Submission API fills the Dependency Graph with _all_ project dependencies (direct or indirect), even if the indirect ones won't appear on any dependency files.
This changes the updater to record a better error in this case.

Report gradle security update errors when dependency not found in repository

---

python/Dockerfile

1. Reorder the list of package lexicographically
2. Assume the only packages needed for `pyenv` to install `python` are
the ones listed in https://github.com/pyenv/pyenv/wiki#suggested-build-environment
3. Move the remaining packages to a separate section of packages that
are installed in the final image, not the builder image (they're not
needed for building the various python's)
4. Go through the list of packages that are _potentially_ used for user
packages, and search the repo issues/PR's/commit log for any
mentions. Also google to see if any common python libraries require
them. If so, document why.
5. Delete the remaining packages, they're probably not needed.
This should slightly shrink our build times/image size, but there is a
risk that one or more of the removed libraries are …

Split system packages into two sections: required to build python vs required to build users' python packages

---

python/Dockerfile

When dependabot tries to update `gssapi` or `krb5` in a `requirements.txt` file of a Python project, it fails with the following error.
```
updater |   Collecting krb5==0.3.0
updater |     Downloading krb5-0.3.0.tar.gz
updater |        - 1.7 MB 66.7 MB/s 0:00:00
updater |     Installing build dependencies: started
updater |     Installing build dependencies: finished with status 'done'
updater |     Getting requirements to build wheel: started
updater |     Getting requirements to build wheel: finished with status 'error'
updater |     error: subprocess-exited-with-error
updater |     
updater |     × Getting requirements to build wheel did not run successfully.
updater |     │ exit code: 1
updater |     ╰─> [23 lines of output]
updater |         /bin/sh: 1: krb5-config: not found
updater …
```

Install libkrb5-dev package in python Dockerfile

---

terraform/Dockerfile

Release notes https://github.com/hashicorp/terraform/releases/tag/v1.5.6

build(deps): bump terraform from 1.5.5 to 1.5.6

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/library_detector.rb

Addresses the following error that is happening in `main` npm tests : 
> 
> Failure/Error:
> @project_npm_response.body.force_encoding("UTF-8").encode.
> include?(project_description)
> 
>  FrozenError:
>    can't modify frozen String: ""
Example failure : https://github.com/dependabot/dependabot-core/actions/runs/6019388208/job/16329143018?pr=7811

fix: duplicate response body before mutating it

---

python/helpers/build
python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/lib/dependabot/python/file_parser/setup_file_parser.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/lib/dependabot/python/file_updater/requirement_replacer.rb

To reduce ambiguity, by default the compiled output from python 3 results in the commands `python3` / `pip3`. Often wrapper tooling will create additional symlinks of `python`/`pip` pointing at these, but they aren't the out-of-the-box default when compiling Python straight from source.
In our case, `pyenv` _does_ add these symlinks. However, if we move away from using `pyenv install` to another method (:wink:), then life will be simpler if we directly call `python3` / `pip3` because we won't need to create symlinks.

Use `python3`/`pip3` so we don't have to have `python`/`pip` symlinks

---

python/Dockerfile
python/lib/dependabot/python/language_version_manager.rb

Our Python docker builds are slow... a typical CI test run for Python takes ~21 minutes, of which the first ~10 minutes are spent building the image.
This results in slower local development, slow CI test suites, and slow deployments.
The main culprit is `pyenv install` which under the covers downloads the python source and then compiles it locally. Profiling showed that the download was quick, so even though `pyenv` supports `aria2c`, there's not much to be gained there. Unfortunately, a quick look at the `pyenv` issue tracker showed [there's no way to to pass pre-compiled artifacts to `pyenv`](https://github.com/orgs/pyenv/discussions/1872).
For a long time we've bandied about the idea of switching from `pyenv` to downloading pre-compiled Pythons.However, we use `pyenv local` + `pyenv …

Use pre-compiled Python from official Docker image

---

npm_and_yarn/Dockerfile

The latest version of Node 18 installs npm `9.6.7` but we need more information before we can proceed. See https://github.com/npm/cli/issues/6742
In the meantime, I believe that it adds value to upgrade to `9.6.5` as we're behind
Closes https://github.com/dependabot/dependabot-core/pull/7659

build(deps): bump npm from 9.5.1 to 9.6.5

---

python/helpers/build

This removes the pyc files which were added during previous python invocations.
Ensure shared objects are stripped, preserving timestamps.
Before:
```
dependabot@9c1ccba0e418:/usr/local/.pyenv/versions$ du -shc *
51M	3.10.13.tar.gz
185M	3.11.5
51M	3.8.18.tar.gz
49M	3.9.18.tar.gz
335M	total
```
After
```
dependabot@f0f1ba4d48ae:/usr/local/.pyenv/versions$ du -shc *
31M	3.10.13.tar.gz
107M	3.11.5
32M	3.8.18.tar.gz
31M	3.9.18.tar.gz
200M	total
```

Python helper removes bytecode files

---

python/Dockerfile

Now that we've stopped compiling Python from source and instead download/copy a pre-compiled version, there's no need to install these apt packages.
A few may be needed for users to build python deps written in native C, but those shouldn't be listed in this section, they should be added later in the the Dockerfile where we already list other packages needed for that:
https://github.com/dependabot/dependabot-core/blob/51b268a81a983c6547af4d95768218a03bd8e751/python/Dockerfile#L128-L143
Also, it's unclear which of these would be needed, so let's start by removing these, and then as needed can add back the couple that we actually discover are needed.

Stop installing apt packages for compiling Python

---

python/Dockerfile

Previously we'd build all the non-default pythons concurrently with building the default python, and then sequence installing the `apt` packages behind building the default Python.
However, these `apt` packages can take a little while to fetch/install, and they don't require the default Python, so instead parallelize building the default python at the same time as installing the apt packages.
This also makes the flow consistent across all pythons of building in a separate stage and then copying to the final image.

Make building the default python concurrent rather than sequential

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb

Closes: https://github.com/dependabot/dependabot-core/issues/7942
I am getting an error `Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound` for a project that has a ruby version requirement for `3.0.6`. This PR bumps the expected RUBY_VERSIONS to include the latest for [ruby 3.0](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-0-6-released/)
Ran tests locally and passed

Bump RUBY_VERSIONS to include 3.0.6

---

Dockerfile.updater-core
python/Dockerfile
python/lib/dependabot/python/language_version_manager.rb

Replace `gzip` with `zstd` for both speed + size benefits.
I added `zstd` to the base image rather than the python-specific image because:
1. it's only 1,695 KB
2. We'll likely use it in other places down the road, such as unpacking deps for jobs
3. The Python image would have required additional steps like `apt-get update`
4. Originally I was afraid that installing `zstd` would take more time than is saved with the compression speedup--and that time would apply to _all_ images, but looking at the raw CI logs and grep'ing for `zst` shows that it takes < 0.5s to install it.
This results in faster compression + space savings:
```shell
root@ca684869d4af:/usr/local/.pyenv/versions# time tar -acf 3.11.5.tar.gz 3.11.5
real	0m5.564s
user	0m5.458s
sys	0m0.626s …
```

Replace `gzip` with `zstd` for speed + size benefits

---

gradle/lib/dependabot/gradle/version.rb
gradle/spec/dependabot/gradle/version_spec.rb

Fixes https://github.com/dependabot/dependabot-core/issues/3759
This change causes the `+` to always compare higher than any version in the semver position. That means when the dependency specifies `4.+` with no lockfile, it won't attempt to update to version 4.11 because 4.+ already covers that.
The code in `gradle/version.rb` is particularly challenging. If there's a better way to write this let me know.

Gradle: fix comparison of the prefix version range

---

go_modules/Dockerfile

Due to a bug in Go 1.20 (see https://github.com/golang/go/issues/61873), when importing a module without a dot in it, we get:
```
18:13 ❱ GOTOOLCHAIN="go1.20+auto" go get
akvorado: ambiguous import: found package akvorado in multiple modules:
akvorado (/home/bernat/code/free/akvorado)
(/home/bernat/src/gocode/pkg/mod/golang.org/toolchain@v0.0.1-go1.20.linux-amd64/src/akvorado)
```
This issue was fixed in Go 1.20.8 which was just released. By using `go1.20.8` as a toolchain for anything <= 1.20, we still cover the use case introduced in #7884, but we also avoid this bug. `go1.20.8` is a valid toolchain. For Go 1.20, only `go1.20` is a valid version for `go` directive in `go.mod`.

go: fix ambiguous import when using a module without a dot

---

maven/lib/dependabot/maven.rb
maven/lib/dependabot/maven/file_parser.rb
maven/lib/dependabot/maven/file_updater/declaration_finder.rb
maven/lib/dependabot/maven/metadata_finder.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/file_parser_spec.rb
maven/spec/dependabot/maven/file_updater/declaration_finder_spec.rb
maven/spec/dependabot/maven/file_updater_spec.rb
maven/spec/dependabot/maven/metadata_finder_spec.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb

In https://github.com/dependabot/dependabot-core/pull/1924 the classifier was added to take account of the different URL pattern needed to pull the dependency, however it was added to the dependency name and this has caused some issues around `allow` and `ignore`. 
I've put up a repro here: https://github.com/dsp-testing/maven-no-make-pr
Since it is appending the classifier to the end of the dependency name, the allow is preventing the update.
To fix this I moved the classifier into the dependency metadata, which didn't exist when #1924 was created, but now is a perfect place for this data to live!

Maven: fix classifier being part of the dependency name

---

docker/lib/dependabot/docker/version.rb
docker/spec/dependabot/docker/version_spec.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/spec/dependabot/updater/operations/group_update_all_versions_spec.rb

Fixes https://github.com/dependabot/dependabot-core/issues/7938
WIP
`Dependabot::Docker::Version#new` would normally return an instance of a `Gem::Version` with an actual value, but `Docker::Version#initialize` failed to call `#super` and so it returned `Gem::Version.new(nil)` instead.
This PR fixes that issue in the `Dependabot::Docker::Version` class by actually calling `#super` and it also removes the overloaded `#self.correct?(version)` method that was present since the base method should now work correctly.
Finally, in `Updater::GroupUpdateCreation` we make sure to cast the version returned by the latest version finder to an actual `Dependabot::Version` so we can use the `Dependabot::Version#segments` method.

Ensure Docker versions are valid Dependabot::Versions

---

common/lib/dependabot/metadata_finders/base/changelog_finder.rb
common/lib/dependabot/metadata_finders/base/changelog_pruner.rb

See
- https://github.com/dependabot/dependabot-core/security/code-scanning/55
- https://github.com/dependabot/dependabot-core/security/code-scanning/108
https://ruby-doc.org/3.2.2/String.html#method-i-rstrip

Use `rstrip` to trim trailing newlines

---

.git-blame-ignore-revs

This ignores the _large_ style change commit https://github.com/dependabot/dependabot-core/commit/3fc49229761517cf3dc6979018a9a2d84f733ece.
See [Ignore commits in the blame view (Beta)][1] for more information.
[1]: https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/

Add `.git-blame-ignore-revs-file` and ignore style change

---

common/dependabot-common.gemspec
omnibus/Gemfile
updater/Gemfile.lock

Part of #7782 and step 1 of the [adopting Sorbet in an existing codebase][1] guide.
This will be followed with step 2 [initializing sorbet][2]
[1]: https://sorbet.org/docs/adopting#step-1-install-dependencies
[2]: https://sorbet.org/docs/adopting#step-2-initialize-sorbet-in-our-project

Add sorbet dependencies

---

common/Gemfile
common/dependabot-common.gemspec

Sorbet currently doesn't support `aarch64-linux`. Unfortunately, this means that it doesn't work on Docker on macOS, unless you force `--platform=linux/amd64` or `DOCKER_DEFAULT_PLATFORM=linux/amd64`.
This change makes `sorbet` and `tapioca` only install on supported platforms for now. This means that typechecking with `srb tc` will not work on Docker on macOS. However, while it's an optional, non-enforced, part of the project this is an acceptable trade-off.
Thankfully, it looks like official support for `aarch64-linux` is extremely close to being completed. So I anticipate this workaround will be shortlived.
References:
- https://github.com/sorbet/sorbet/issues/4119
- https://github.com/sorbet/sorbet-build-image/pull/8

Make sorbet and tapioca optional

---

.vscode/extensions.json
.vscode/settings.json
sorbet/config

This adds and enables the [Sorbet VSCode extension][1] as outlined in [the Sorbet documetation][2].
This PR also disables Sorbet's [watchman][3] integration. That does limit Sorbet to only type-checking files that are edited in VSCode. But this would require editing the setup scripts and/or Dockerfiles. As Sorbet is still an optional part of the codebase, I think this is an acceptable trade-off for now.
Part of #7782
[1]: https://marketplace.visualstudio.com/items?itemName=sorbet.sorbet-vscode-extension
[2]: https://sorbet.org/docs/vscode
[3]: https://github.com/facebook/watchman

Add Sorbet VSCode extension

---

omnibus/Gemfile

Fixes the freeze on `bundle install` when running `bin/docker-dev-shell common --rebuild ` on ARM. 
Not sure why `install_if` worked in common but doesn't work in omnibus. Plain ole `if` seems ok though!

fix docker-dev-shell on ARM

---

docker/lib/dependabot/docker/version.rb

The `#correct?` method mimics creating a new `Docker::Version` without actually instantiating one. It checks that the semver part of the `Docker::Version` is actually valid semver.
The [previous version](https://github.com/dependabot/dependabot-core/blob/e1967ef907e681817f596a99e5eb741c1de48d8a/docker/lib/dependabot/docker/version.rb#L23) of this method called `#new` and `Docker::Version#new` would call `Gem::Version#new` which would call `#correct?`, and it would get stuck in an infinite loop, so it was removed.
This PR adds in a working version of the method and there are already existing test cases for it like https://github.com/dependabot/dependabot-core/blob/7cf009180799b2c1d58f710d45b521d18853a25a/docker/spec/dependabot/docker/version_spec.rb#L30-L45

Add back the Docker::Version.correct? method

---

common/lib/dependabot/file_fetchers.rb
common/lib/dependabot/file_parsers.rb
common/lib/dependabot/file_updaters.rb
common/lib/dependabot/update_checkers.rb

Add sig to dependency injection containers

---

common/lib/dependabot.rb
common/lib/dependabot/clients/azure.rb
common/lib/dependabot/clients/bitbucket.rb
common/lib/dependabot/clients/bitbucket_with_retries.rb
common/lib/dependabot/clients/codecommit.rb
common/lib/dependabot/clients/github_with_retries.rb
common/lib/dependabot/clients/gitlab_with_retries.rb
common/lib/wildcard_matcher.rb
sorbet/rbi/shims/array.rbi
sorbet/rbi/shims/aws-sdk-codecommit.rbi
sorbet/rbi/shims/aws-sdk-ecr.rbi
sorbet/rbi/shims/hash.rbi
sorbet/rbi/todo.rbi

Mainly adding `typed: true` to clients, but also includes:
- Making `dependabot.rb` and `wildcard_matcher.rb` `typed: strong` mostly as a learning experience to see what is required at that type enforcement level
- Define stubs of `to_json` for `Array` and `Hash`
- Define stubs for `AWS` errors which Sorbet is unable to determine (See [The TODO RBI file][1] for more details)
- Wrap `*_with_retries` clients with `T.unsafe` as they explicitly rely on `method_missing` which Sorbet can't deal with
Related to #7782. Supersedes #8028 (as I created that from the `main` branch of my fork 🤦)
[1]: https://sorbet.org/docs/rbi#the-todo-rbi-file

Add types to clients

---

python/lib/dependabot/python/version.rb

This hopefully fixes #8003 which exhibits the following error:
```
updater | 2023/09/14 09:33:53 ERROR <job_721897648> Error processing pytz (NoMethodError)
updater | 2023/09/14 09:33:53 ERROR <job_721897648> undefined method `split' for #<Dependabot::Python::Version 2023.3.post1>
updater | 
updater |         version, @local_version = version.split("+")
updater |                                          ^^^^^^
```
The error message is indicating that the `split` method is being called on an instance of `Dependabot::Python::Version`, not a string. The `split` method is a string method, so it cannot be called on an object of a different type unless it implements its own "split" method, which this "Version" type doesn't seem to do.
cc @carogalvin 👋 😅 sorry for pinging you here but this seems …

fix: call 'split' on string-type object, not on version-type object

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb

Closes: https://github.com/dependabot/dependabot-core/issues/8040
I am getting an error Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound for a project that has a ruby version requirement for 3.2.2 This PR bumps the expected RUBY_VERSIONS to include the latest for [Ruby 3.1](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-1-4-released/) and [Ruby 3.2.2](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/)
Ran tests locally and passed

Bump RUBY_VERSIONS to include 3.1.4 and 3.2.2

---

.github/workflows/sorbet.yml
.gitignore
script/generate-coverage-report

Two changes:
- Only upload spoom snapshot data on `main` branch
- We don't ultimately care about snapshots taken on PRs until they are merged
- Generate the HTML report when running on `main` branch
- Allows us to easily see progress
[Successful run][1]
[1]: https://github.com/dependabot/dependabot-core/actions/runs/6202656407?pr=8047

Generate and upload spoom coverage report on main

---

go_modules/Dockerfile

From: https://go.dev/doc/devel/release#go1.21.1
> go1.21.1 (released 2023-09-06) includes four security fixes to the cmd/go, crypto/tls, and html/template packages, as well as bug fixes to the compiler, the go command, the linker, the runtime, and the context, crypto/tls, encoding/gob, encoding/xml, go/types, net/http, os, and path/filepath packages. See the [Go 1.21.1 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.1+label%3ACherryPickApproved) on our issue tracker for details.

build(deps): bump go from 1.21.0 to 1.21.1

---

common/dependabot-common.gemspec
omnibus/Gemfile
updater/Gemfile.lock

This changes the version range of `sorbet-runtime` from `~> 0.5` (AKA `>= 0.5, < 0.6`) to `~> 0.5.11026` (AKA `>= 0.5.11026`). This supersedes #8048.
I also added a comment about why `sorbet` and `tapioca` are currently guarded by a conditional. Hopefully we can remove it in the near future.

Update Sorbet from `0.5.11011` to `0.5.11026`

---

common/lib/dependabot/pull_request_creator/github.rb

This was missed in #8013.
Currently it returns `nil` but then raises an UnexpectedError.

raise if the reference already exists

---

sorbet/tapioca/config.yml

The documentation that was generated when this was installed has been causing warnings to be added to PR diffs. These values are defaults, which seem to be just as helpful as the comments which were added.
[Source for defaults](https://github.com/Shopify/tapioca/blob/fa61b834119d4a9dc0643862d4ad4804225b0ab9/README.md?plain=1#L879-L935)
This is meant to address 👇 warnings

💅 Use defaults instead of comments for documentation

---

common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
python/spec/dependabot/python/file_parser/setup_file_parser_spec.rb
updater/lib/dependabot/api_client.rb
updater/lib/dependabot/base_command.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater/error_handler.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater/error_handler_spec.rb
updater/spec/dependabot/updater_spec.rb

Dependabot currently treats `unknown_errors` the same as any other error type.
However, `unknown_errors` are a bit of a special case because they are mostly caused by a HelperSubprocessFailure when Dependabot shells out to native package managers. The helper subprocess failures are harder to debug because they can be specific to a dependency set or some combination of a package manager version and project file features.
In order to better investigate unknown errors, we should send the error details to the backend service so we can look for trends.
This PR makes a few changes to the way unknown errors are logged:
1. unknown errors can only be generated from a few sources:
a. helper subprocess failures
b. file fetcher command errors
c. update files command errors 
2. helper subprocess …

Track unknown errors

---

common/lib/dependabot/shared_helpers.rb

Removing logging of the command during Subprocess failure. This might contain PII info and since this data is displayed during Dependabot job logs (during failure/exception) so removing it.

Removed logging of commands from Subprocess failure

---

common/lib/dependabot/git_commit_checker.rb
github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

Fixes #7971.
For example, on https://github.com/getlogbook/logbook:
± .github/workflows/wheel-builder.yml
~~~
--- /tmp/original20230919-234-sgikwf	2023-09-19 17:36:17.144755893 +0000
+++ /tmp/updated20230919-234-cdm607	2023-09-19 17:36:17.144755893 +0000
@@ -25,7 +25,7 @@
name: Build sdist
runs-on: ubuntu-latest
steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - uses: actions/checkout@v4 # v3.5.3
with:
ref: ${{ github.event.inputs.version || github.ref }}
@@ -50,7 +50,7 @@
os: [ubuntu-20.04, windows-2019, macos-11]
steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - uses: actions/checkout@v4 # v3.5.3
with:
ref: ${{ github.event.inputs.version || github.ref }}
~~~
3 insertions (+), 3 deletions (-) …

Respect style of each action when mixed styles are used

---

Dockerfile.updater-core

This change moves a few items that are less likely to change towards the beginning of the Dockerfile. This should keep a new layer being created for ruby (~55MB) with each new image creation.

Dockerfile - Add infrequently layers earlier

---

common/spec/dependabot/file_fetchers/base_spec.rb

A lot of warnings like this get printed:
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
```

Fix warnings when running tests in common

---

common/lib/dependabot/git_commit_checker.rb
github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb

See https://github.com/rubygems/rubygems/pull/6995 for an example.
Since there is an old action pinned to `actions/checkout@v3.6.0`, that's the version the dependency takes, and the one that tries to be replaced. However, all comments are using `# v4.0.0`, since that's what the other actions are using, so the comment replace fails.
Instead, respect the version each action is pinned to when performing the replace, keeping the spirit of #8068.

Fix some github actions version comments not getting updated

---

npm_and_yarn/Dockerfile
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb

Release notes:
https://github.com/pnpm/pnpm/releases/tag/v8.7.0
https://github.com/pnpm/pnpm/releases/tag/v8.7.1
https://github.com/pnpm/pnpm/releases/tag/v8.7.2
https://github.com/pnpm/pnpm/releases/tag/v8.7.3
https://github.com/pnpm/pnpm/releases/tag/v8.7.4
https://github.com/pnpm/pnpm/releases/tag/v8.7.5
https://github.com/pnpm/pnpm/releases/tag/v8.7.6

build(deps): bump PNpm from 8.6.12 to 8.7.6

---

bundler/script/ci-test
common/dependabot-common.gemspec
composer/script/ci-test
go_modules/script/ci-test
hex/script/ci-test
npm_and_yarn/script/ci-test
python/script/ci-test
swift/script/ci-test

[Turbo Tests](https://github.com/serpapi/turbo_tests) is a parallel_tests drop-in replacement that changes the default output to look exactly the same as plain RSpec.
It makes it easier to inspect failures at the end of the output instead of being interleaved.

Improve running specs

---

updater/spec/support/dummy_pkg_helpers.rb

Same as #8100, but for updater specs.

Remove another git warning during specs

---

updater/lib/dependabot/updater/group_update_creation.rb

Fixes https://github.com/dependabot/dependabot-core/issues/7978
Fixes https://github.com/dependabot/dependabot-core/issues/7961
Before trying to create a Version, we need to check if it's `correct?` to prevent NilClass errors, and other bad things. This handles the Git dependency case as well, since a Git dependency is not semver. 
I didn't add a new test because this existing test [here](https://github.com/dependabot/dependabot-core/commit/31c4c30c0fb391de4fc226fed5fffce22110dac8#diff-864299df6238a996bac5ef9ae9c06478ce8b06362acfa3193aef0896a6d815f0R265-R293) seems to be doing a pretty good job of testing it using a realistic example of a Git dependency. Now, this extends to other ecosystems now where things like `latest` (Docker) are common, but the Updater tests are always in the …

fix semver segments errors due to invalid Versions

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/dependency_snapshot_spec.rb
updater/spec/dependabot/updater/operations_spec.rb

This has been rolled out, the flags have been at 100% for a while now so time to clear 'em out.

Remove grouped updates feature flags

---

updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/fixtures/bundler_vendored/original/Gemfile.lock
updater/spec/fixtures/bundler_vendored/updated/Gemfile.lock

First commit makes updater specs pass on `aarch64-linux`.
Second commit fixes some random dependent test failures introduced by #8104.

Fix some flaky test failures

---

updater/spec/fixtures/bundler_grouped_by_types/updated_development_deps/Gemfile.lock

The new parser 3.2.2.4 release has caused a new test failure.

Catch up test lockfile with parser 3.2.2.4 release

---

cargo/script/ci-test
common/script/ci-test
docker/script/ci-test
elm/script/ci-test
git_submodules/script/ci-test
github_actions/script/ci-test
gradle/script/ci-test
maven/script/ci-test
nuget/script/ci-test
terraform/script/ci-test

When I worked on #6590, I apparently forgot to enable parallel tests for all ecosystems. All of them seem to be running fine in parallel, except for Pub.
For now I'm enabling parallel tests for the others.

Parallelize tests on all ecosystems, except for Pub

---

updater/lib/dependabot/job.rb
updater/spec/dependabot/updater_spec.rb

Fixes #7651
If you try to ignore all versions of a dependency that is otherwise allowed to update, Dependabot will still query the registry to get a list of versions.
This becomes a problem if the dependency source is an un-configured private registry because it will fail the HTTP request and cause an error on the job which is completely avoidable if Dependabot had skipped the check.
This PR adds a check for completely ignored dependencies in `allowed_update?` which will fix the issue for individual PRs and grouped updates. 
Future enhancements to this could include checking if the range provided means no update is possible, like if the dependency is at `1.0.0` and the ignored version range is `> 1.0.0`.

fix completely ignored dependencies querying for updates

---

updater/lib/dependabot/base_command.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater/error_handler.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater/error_handler_spec.rb
updater/spec/dependabot/updater_spec.rb

- This PR adds the new feature flag named `record_update_job_unknown_error`. It has been created to be always enabled when running on our cloud infrastructure but remains inactive for GHES. The reason behind this differentiation is that older versions of GHES do not support the functionality of reporting unknown errors. This change ensures smooth operation across various environments without compromising on functionality where supported.
- This feature flag will be used to skip any `api_client.record_update_job_unknown_error` call to capture the unknown error when running in GHES environment.
- This new feature flag `record_update_job_unknown_error` is already created in Dependabot-api and deployed to production.
- The [PR](https://github.com/github/dependabot-updates/issues/3650#:~:text=E …

Added record update job error api back to capture unknown errors 

---

updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh_similar_pr.yaml

fixes #8149
In #8106 we accounted for existing grouped pull requests dependencies when running a grouped update job to prevent a dependency from appearing in multiple PRs.
This PR adds that same logic to the refresh so when Dependabot rebases or recreates a PR it doesn't duplicate the dependencies.

fix refreshing a grouped PR causes dependency duplication

---

updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/create_group_security_update_pull_request.rb
updater/spec/fixtures/bundler_grouped_by_types/updated_development_deps/Gemfile.lock

This is a grouped security updates prototype.
It detects a group by seeing multiple dependencies are passed into a security update job. Then it creates a grouping on-the-fly to generate a single PR instead of the usual multiple PRs. 
This is a feature in development, so there's no way to exercise it without flags set in the service.

grouped security updates

---

terraform/Dockerfile

Release notes 
https://github.com/hashicorp/terraform/releases/tag/v1.5.7
https://github.com/hashicorp/terraform/releases/tag/v1.6.0
https://github.com/hashicorp/terraform/releases/tag/v1.6.1

build(deps): bump Terraform from 1.5.6 to 1.6.1

---

python/helpers/lib/parser.py
python/spec/dependabot/python/file_parser_spec.rb
python/spec/fixtures/requirements/with_path_dependency.txt

These can't be updated.
If we try to update them, we end up running into errors later. Sample repro:
```
$ bin/dry-run.rb pip "bowtie-json-schema/bowtie" --dir="/." --updater-options=grouped_updates_experimental_rules,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=a8fd4b1828d5a71f8bda669e8dc84daf19caa1c9 --cache=files --dep bowtie-json-schema
```

Ignore file dependencies when parsing requirement files

---

cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb
cargo/lib/dependabot/cargo/update_checker/version_resolver.rb

We're getting the following flaky in cargo:
https://github.com/dependabot/dependabot-core/actions/runs/6493735738/job/17635263354
```
Failures:
1) Dependabot::Cargo::UpdateChecker::VersionResolver latest_resolvable_version when using a toolchain that is too old raises a helpful error
Failure/Error:
expect { subject }
.to raise_error(Dependabot::DependencyFileNotEvaluatable)
expected Dependabot::DependencyFileNotEvaluatable, got #<Dependabot::SharedHelpers::HelperSubprocessFailed: Blocking waiting for file lock on package cache
error: Unable to update registry `crates-io`
Caused by:
usage of sparse registries requires `-Z sparse-registry`> with backtrace:
Finished in 33.38 seconds (files took 1.24 seconds to load)
360 examples, 1 failure
Failed examples:
rspec …
```

Improve detection of unsupported cargo toolchains

---

bin/dry-run.rb
bundler/spec/dependabot/bundler/file_fetcher_spec.rb
common/lib/dependabot/errors.rb
common/lib/dependabot/file_fetchers/base.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
updater/lib/dependabot/file_fetcher_command.rb

If the user is configuring a directory for dependabot that no longer exists, and the ecosystem does not clone full repositories, we'll end up with unknown `Octokit::NotFound` errors when trying to fetch dependency files.
This PR creates a new error that will be displayed to the user so that she can fix her configuration.

Expose a new directory_not_found user error

---

common/lib/dependabot/errors.rb
common/spec/dependabot/errors_spec.rb

If error includes multiple urls with @ in their fragments, we would redact it incorrectly.

Fix false positive auth redaction

---

python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb
python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb

This PR contains a few different bug fixes and refactorings.
I decided to propose them together, because the failing cases I was working with did not get fixed by applying only a subset of the fixes, but they need all of them to start creating sane PRs.
Break up of the different fixes is:
* Fix regex match of pip-compile errors as a way to retry `pip-compile` with `--no-build-isolation`. This error was caused by Pip itself changing the error message, and just catches up with the change. 500455f9a1c91dc937b7c1e38d9cb93ebbc47cb9
* Copy `--no-build-isolation` retry code into the file updater. Normally error detection only needs to happen in the update checker, since we fail early when detecting these errors and we don't need to check again in the file updater. We don't reach that far. …

Fix multiple pip compile errors

---

python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/fixtures/pyproject_files/different_requirements.toml
python/spec/fixtures/pyproject_files/different_requirements_legacy.toml
python/spec/fixtures/pyproject_files/different_requirements_main.toml

If a `pyproject` specifies the same dependency in the development and main groups, that will cause Dependabot to crash.
This PR fixes the problem.
It can be reproduced with
```
bin/dry-run.rb pip "whitphx/streamlit-server-state" --dir="/." --updater-options=grouped_updates_experimental_rules,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=0ccf9bd713ae97042a40705f8f29555bcd8003c8 --cache=files --dep streamline
```

Fix poetry multiple requirement replacement in pyproject.toml

---

sorbet/rbi/gems/.gitattributes

This will collapse diffs in `.rbi` files by default and omit them from the repository language statistics. See [Customizing how changed files appear on GitHub][1] for more details.
This is the `.gitattributes` file that gets generated by the newest version of `tapioca`. `.rbi` files are automatically generated by `tapioca` and should not be manually edited.
[1]: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

Mark `.rbi` as `linguist-generated`

---

github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb
github_actions/spec/fixtures/workflow_files/pinned_sources_version_comments.yml

When YAML strings are quoted, Dependabot fails to update trailing version comments. For example, Dependabot will update the SHA but not the "v2.1.0" comment below:
```yaml
- uses: "actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81" # v2.1.0
```
This PR fixes the bug in the associated regex.
In addition, this PR removes a test case using a short SHA (`"01aecc"`) that is no longer updated (a problem that the test suite doesn't notice) and isn't supported by GitHub Actions anymore.
It also updates a short-SHA-based test case (`"01aecc#v2.1.0"`) to use a full-length SHA so that it is more likely to catch bugs that might be introduced.
Fixes #8125

Fix version comments after quoted strings

---

python/lib/dependabot/python/file_updater/requirement_file_updater.rb

Currently we get a missing method call on `nil`, which is zero useful.
Hopefully this will give a bit more information about the issue.

Get better info on an unknown error

---

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
python/spec/fixtures/pyproject_files/incorrect_poetry_setup.toml

If a user defines an incorrect `pyproject.toml` file for Poetry, for example, because it's missing some required keys like `tool.poetry.name`, well end up crashing because Poetry can't handle with that under the hood.
For example,
```
$ bin/dry-run.rb pip "obervinov/vault-package" --dir="/." --updater-options=grouped_updates_experimental_rules,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=9782e76cbd40d26b64049e4f1389af4a273b62b3 
=> dumping fetched dependency files: ./dry-run/obervinov/vault-package/.
=> updating 4 dependencies: hvac, keyring, python-dateutil, logger
=== hvac (1.1.0)
=> checking for updates 1/4
🌍 --> GET https://pypi.org/simple/hvac/
🌍 <-- 200 https://pypi.org/simple/hvac/
=> …
```

Raise user errors on invalid poetry manifest

---

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb

Otherwise we'll end up with an error, like here:
```
$ bin/dry-run.rb pip "The-Dark-Limit/watchdog-node" --dir="/." --updater-options=grouped_updates_experimental_rules,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=79b38eac0d4ac6e6e737f077fb0988af8edee9d4 --cache=files
```

Avoid trying to parse poetry.lock if pyproject.toml is invalid for Poetry

---

python/helpers/lib/parser.py
python/spec/dependabot/python/file_parser_spec.rb
python/spec/fixtures/requirements/remote_constraints.txt

These are remote dependencies, so we can't update them.
If we parse them, we'll end up crashing somewhere else.

Ignore dependencies from remote constraint files

---

go_modules/Dockerfile

also fixes #8203
It's kind of ironic that we need to keep bumping versions of Go, so I changed the Dockerfile to pull Go from the official Docker image. I think that will cause Dependabot to start bumping the FROM line so we won't have to!
Obviously Go 1.20 at the bottom won't be bumped by this, but once Go 1.22 is released it will stop receiving updates.

Go: pull from the official Docker image so that Dependabot bumps it

---

common/lib/wildcard_matcher.rb
updater/lib/dependabot/updater/group_update_refreshing.rb
updater/lib/dependabot/updater/operations.rb
updater/lib/dependabot/updater/operations/refresh_group_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations_spec.rb

Currently, when rebasing a grouped security update, we will default to creating individual PRs for each dependency, since the updater does not know how to refresh grouped updates.
This adds a basic strategy that reuses the refresh behavior for Version Update groups.

Ensure Grouped Security Updates are rebased correctly

---

python/lib/dependabot/python/requirement_parser.rb
python/spec/dependabot/python/requirement_parser_spec.rb

We currently raise an error when trying to update requirements like this, for example:
```
mypy==v1.5.1
```
Such an error can be reproduced with:
```
bin/dry-run.rb pip "Rahul2044/cve-bin-tool" --dir="/." --updater-options=grouped_updates_experimental_rules,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=abaa7571b4aac36489b59137f0ef827c0f4c7ded --cache=files --dep mypy
```

Support Python requirements with preceding "v"

---

common/lib/dependabot/file_updaters/base.rb
go_modules/lib/dependabot/go_modules/file_updater.rb
maven/lib/dependabot/maven/file_updater.rb
nuget/lib/dependabot/nuget/file_updater.rb

A couple of notable things I'd like to highlight about this PR:
- Reordered the parameters of `initialize` to fix [`Sorbet/KeywordArgumentOrdering`: Optional keyword arguments must be at the end of the parameter list][1]
- It's a little unclear what the types of `credentials` and `options` should be
- I was more confident in `credentials` being `T::Hash[String, String]`
- I was less confident in `options` so it's `T::Hash[String, T.untyped]`
- Methods marked with [`overridable`][2] should likely be marked as `abstract`, but `abstract` methods are required to have no body, and I am not sure if anything is depending on them raising a `NotImplementedError`
- Changes to other files are type system 'escape hatches' as they haven't been properly typed yet and I wanted to keep this PR small
Part …

Add types to `FileUpdaters::Base`

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/integration_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/updater_spec.rb

Interestingly Sorbet was confused that we were delegating to update_dependency_list but also defining it. So I removed the delegation.
Also I had to tell the doubles that they were the thing Sorbet is checking for. This seems to be the correct approach https://stackoverflow.com/questions/56742572/how-to-use-sorbet-type-checking-with-rspec-mocks

add types to service

---

docker/lib/dependabot/docker/update_checker.rb

Clarify docker logs about ignoring a normally expected update candidate

---

python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/fixtures/pyproject_files/same_requirements.toml

If there are multiple dependencies with the same requirement in the same
group in pyproject.toml, sometimes Dependabot could end up incorrectly replacing all of them.
Fixes #8259.
Fixes #8250.

Fix poetry regression

---

bundler/helpers/v2/lib/functions/force_updater.rb
bundler/lib/dependabot/bundler/update_checker/force_updater.rb
bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb
bundler/spec/fixtures/projects/bundler1/top_level_update_with_git_gems/Gemfile
bundler/spec/fixtures/projects/bundler1/top_level_update_with_git_gems/Gemfile.lock
bundler/spec/fixtures/projects/bundler2/top_level_update_with_git_gems/Gemfile
bundler/spec/fixtures/projects/bundler2/top_level_update_with_git_gems/Gemfile.lock

#7621 fixed an issue where some dependencies were not getting requirement updates in the Gemfile in situations where users would usually expect them.
However, the fix was too aggressive and it caused also unrelated dependencies to the update being unlocked under some situations.
This PR implements a hopefully safer approach.
Fixes #8195.

Unlock related Gemfile dependencies, but not everything that changed

---

updater/lib/dependabot/job.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/service_spec.rb

It could be useful to be able to prioritize errors by the number of repos affected.

Pass user info to Sentry

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_preparer.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/package_json_preparer_spec.rb
npm_and_yarn/spec/fixtures/projects/generic/null_deps/package.json

Our dependency parsing class was parsing these just fine, but not other classes.
Fixes errors like 
```
SECURITY_ADVISORIES='[{"dependency-name":"@babel/traverse","patched-versions":[],"unaffected-versions":[],"affected-versions":[">= 8.0.0-alpha.0 < 8.0.0-alpha.4","< 7.23.2"]}]'  bin/dry-run.rb npm_and_yarn "unctionjs/isNil" --dir="/." --dep="@babel/traverse" --security-updates-only --updater-options=grouped_updates_experimental_rules,npm_transitive_dependency_removal,record_ecosystem_versions,record_update_job_unknown_error,unignore_commands --commit=967b0de4a2ccadf63e3e14745bb8a95a2a1e1347
```

Handle null dependencies in package.json

---

bin/bump-version.rb
bin/dry-run.rb

These files are included in the spoom report, but didn't have a type sigil. These were found with `grep --recursive --files-without-match --include "*.rb" "# typed: " .`. Now the only `.rb` files without sigils are bundler spec fixtures.

Explicitly add `# typed: false` for bin files

---

common/lib/dependabot/config/file.rb
common/lib/dependabot/utils.rb
python/lib/dependabot/python.rb

The right key was actually "pip", not "python".
Enabling this was silently a noop. Properly enabling it requires more work, so revert for now.
In addition, I added some changes to make sure this doesn't happen again. I guess these changes could potentially get in the middle for people extending dependabot-core to add custom ecosystems, but I don't think anybody is reliably doing this, and if they are, they can probably add one more patch to workaround this. For now, I'd prioritize our own convenience.

Revert python always clone registration

---

python/lib/dependabot/python.rb
python/lib/dependabot/python/file_updater.rb
python/lib/dependabot/python/file_updater/pipfile_file_updater.rb
python/lib/dependabot/python/update_checker.rb
python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb
python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
python/spec/dependabot/python/file_updater/pipfile_file_updater_spec.rb
python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb
python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb
python/spec/fixtures/projects/pipenv/editable-package/Pipfile
python/spec/fixtures/projects/pipenv/editable-package/Pipfile.lock
python/spec/fixtures/projects/pipenv/editable-package/ballcone/__init__.py
python/spec/fixtures/projects/pipenv/editable-package/pyproject.toml

This PR retries #8266, but:
* With a correct ecosystem key (`pip`, instead of `python`).
* Making sure the cloned repo is passed around, although still used only for Pipenv. We should make sure the clone is also used for Poetry and Pip compile in the future but for now I decided to limit this PR to fix the pipenv issue I was dealing with initially.

Enable always clone for Python (take 2)

---

composer/Dockerfile
composer/helpers/v2/composer.lock
composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb
composer/spec/dependabot/composer/file_updater_spec.rb
updater/spec/fixtures/composer/updated/composer.lock

`plugin-api-version` was changed from "2.3.0" to "2.6.0" in Composer version 2.6.0. https://github.com/composer/composer/commit/16bdfe4dae0d6ef151d71441849e735f3b0a93c8
This pull request fixes tests to allow upgrading Composer to 2.6.0+. I've targeted https://github.com/dependabot/dependabot-core/pull/8159 here, but the base for this can be easily changed to the default branch if that's preferred.

Composer: update expected plugin API version

---

updater/spec/fixtures/bundler_grouped_by_types/updated_development_deps/Gemfile.lock

Once again it broke.
We should have a more resilient test, but I'm procrastinating for now and went with the easy but not permanent fix.

Fix tests broken by racc release

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
npm_and_yarn/spec/fixtures/github/contents_js_pnpm.json
npm_and_yarn/spec/fixtures/github/pnpm_lock_5.3_content.json
npm_and_yarn/spec/fixtures/github/pnpm_lock_5.4_content.json
npm_and_yarn/spec/fixtures/github/pnpm_lock_6.0_content.json

Closes #7500.
I expect this to fix a bunch of errors in our internal board, but of course will also break for repos where it's actually working.
I don't think this needs a deprecation changelog since we have [documented](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) v7 and v8 as the only supported versions from the beginning.
#7298 would make transition easier for users but I think pnpm v6 is old enough so that this PR does not need to block on that feature.

Raise expected errors when unsupported PNPM versions are used

---

python/lib/dependabot/python/pipenv_runner.rb

After #8312, `pipenv upgrade` errors are not being aggregated in Sentry. This commit should fix that.

Properly aggregate `pipenv upgrade` errors in Sentry

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/json_lock.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/yarn_lock.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_preparer.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/registry_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/nonexistent_locked_dependency/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/nonexistent_locked_dependency/pnpm-lock.yaml

Sometimes errors will have the following shape
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@tiptap-pro/extension-mathematics/-/extension-mathematics-2.3.3.tgz: Not Found - 404
```
instead of the one we were capturing
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@dependabot%2Ftotally-fake-dependency-soz: Not Found - 404
This error happened while installing a direct dependency of dependabot_tmp_dir
@dependabot/totally-fake-dependency-soz is not in the npm registry, or you have no permission to fetch it.
```
This PR changes the regex to capture both types of errors.

Catch more 404 PNPM fetch errors and raise them as user errors

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb

If a scoped registry is not configured for a scoped dependency, however a global registry is configured, it should fall back on the configured global registry.
As discussed in https://github.com/dependabot/dependabot-core/issues/8242#issuecomment-1793136986

npm: Fall back on configured global registry for scoped packages

---

composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb

Apparently Actions can now deal with 16G, so our test no longer causes an OutOfMemory error.

Fix broken composer CI

---

common/spec/dependabot/file_fetchers/base_spec.rb
sorbet/config

Apparently #8310 broke some common specs. No idea why CI did not catch that, but can be reproduced with
```
rspec ./spec/dependabot/file_fetchers/base_spec.rb:1646
```
from common.
This PR removes the signature from `run_shell_command` until we can address the real culprit, since that seems to let the specs pass.

Fix common CI

---

bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb

Probably due to sorbet and rspec's `and_call_original` not playing nice with each other.
See for example latest run in main branch's CI: https://github.com/dependabot/dependabot-core/actions/runs/6787005329/job/18448834031.

Fix more test failures

---

.github/dependabot.yml

This will bump the FROM line in the Go ecosystem Dockerfile so we don't have to manually update it. See #8225

add Dependabot config for Docker at /go_modules

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/vulnerability_auditor.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/vulnerability_auditor_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

We needed to gate this feature because older versions of GHES didn't have support for PRs that remove dependencies. All currently supported versions of GHES now support this so we can remove the flag.

Remove feature flag gating dependency removal

---

common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
common/spec/dependabot/pull_request_creator/pr_name_prefixer_spec.rb
common/spec/fixtures/github/commits_conventional_long_messages.json

When figuring out which case to use, we were looking at previous Dependabot commit messages.
However, our regexps were trying to match the whole commit messages, not just the commit title, and that was causing some false positives.

Fix incorrect casing in some Dependabot PR titles

---

go_modules/lib/dependabot/go_modules/file_fetcher.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/updater/dependency_group_change_batch.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_group_security_update_pull_request.rb
updater/spec/dependabot/updater/dependency_group_change_batch_spec.rb
updater/spec/dependabot/updater/operations_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_by_dependency_type.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_overlapping_groups.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_semver_grouping.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_semver_grouping_with_global_ignores.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_all_with_ungrouped.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh_dependencies_changed.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh_similar_pr.yaml
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh_versions_changed.yaml

follow-on to #8309
This makes the Updater run multiple updates across multiple directories, then smashes all the changes together and creates a PR. Confirmed with some of the smoke tests: https://github.com/dependabot/smoke-tests/pull/135

handle updating manifests across multiple directories

---

bundler/spec/dependabot/bundler/update_checker_spec.rb

```
$ SUITE_NAME=bundler1 rspec spec/dependabot/bundler/update_checker_spec.rb:181 
Run options: include {:locations=>{"./spec/dependabot/bundler/update_checker_spec.rb"=>[181]}}
Randomized with seed 2658
F
Failures:
1) Dependabot::Bundler::UpdateChecker#latest_version with a private rubygems source 
Failure/Error: raise Dependabot::PrivateSourceAuthenticationFailure, source
Dependabot::PrivateSourceAuthenticationFailure:
The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): repo.fury.io
Finished in 0.78182 seconds (files took 1.03 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/dependabot/bundler/update_checker_spec.rb:181 # Dependabot::Bundler::UpdateChecker#latest_version …
```

Fix one more `and_call_original`-related flaky spec

---

python/spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb

```
$ rspec spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb:408
Run options: include {:locations=>{"./spec/dependabot/python/update_checker/pip_compile_version_resolver_spec.rb"=>[408]}}
Randomized with seed 64626
F
Failures:
1) Dependabot::Python::UpdateChecker::PipCompileVersionResolver#resolvable? that fails to resolve due to resource limits because it ran out of disk space raises a helpful error
Failure/Error:
expect { subject }
.to raise_error(Dependabot::OutOfDisk)
expected Dependabot::OutOfDisk but nothing was raised
Top 1 slowest examples (3.32 seconds, 100.0% of total time):
Dependabot::Python::UpdateChecker::PipCompileVersionResolver#resolvable? that fails to resolve due to resource limits because it ran out of disk space raises a helpful error
3.32 …
```

Fix more Sorbet + `and_call_original` issues

---

bin/dry-run.rb
npm_and_yarn/helpers/lib/pnpm/lockfile-parser.js
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/npmrc_only_global_registry/.npmrc
npm_and_yarn/spec/fixtures/projects/npm6/npmrc_other_scoped_registry/.npmrc
npm_and_yarn/spec/fixtures/projects/pnpm/tarball_urls/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/tarball_urls/pnpm-lock.yaml

This PR fixes two issues:
* Dependabot can't infer the proper registry for each dependency by looking at registry urls in pnpm-lock.yaml.
This is handy because developers don't need to commit a `.npmrc` file and matches what we already support for NPM and Yarn.
* Dependabot incorrectly tries to infer the proper registry for each dependency by looking at presence in the registry, even when registries & scopes are explicitly configured in `.npmrc`.
This is a good last resort fallback, but it should not be used if registries & scopes have been explicitly configured.
Fixes https://github.com/dependabot/dependabot-core/issues/8242.
Fixes performance issues introduced by https://github.com/dependabot/dependabot-core/pull/8094.
Likely to fix …

Fix PNPM issues with private registries

---

swift/lib/dependabot/swift/update_checker/version_resolver.rb
swift/spec/dependabot/swift/update_checker_spec.rb
swift/spec/fixtures/projects/ReactiveCocoaNoLockfile/Package.swift

I thought we supported this, but there were some issues.
Fixes #8350.

Support updating Package.swift files without a lockfile

---

composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/helpers.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb

Sometimes we're getting failures like these:
```
1) Dependabot::Composer::FileUpdater::LockfileUpdater the updated lockfile when another dependency has an unreachable git source raises a helpful errors
Failure/Error:
expect { updated_lockfile_content }.to raise_error do |error|
expect(error).to be_a Dependabot::GitDependenciesNotReachable
expect(error.dependency_urls)
.to eq(["https://github.com/no-exist-sorry/monolog.git"])
end
expected: ["https://github.com/no-exist-sorry/monolog.git"]
got: [""]
(compared using ==)
```
This PR raises a runtime error when this happens to help finding out the culprit.

Refactor composer error handling and better handle potential errors

---

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/lib/dependabot/python/update_checker/index_finder.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
python/spec/dependabot/python/update_checker/index_finder_spec.rb
python/spec/fixtures/pyproject_files/extra_source_explicit.toml
python/spec/fixtures/pyproject_files/extra_source_explicit_and_package_specify_source.toml
python/spec/fixtures/pyproject_files/package_specify_source.toml

- The issue #7918 is being addressed to incorporate support for Poetry's explicit package source.
- Following this update, the explicit package source will only be utilized if a package explicitly specifies it as the source.
Poetry 1.5.0 introduced the concept of an explicit package source, which can be found here: [Explicit Package Sources](https://python-poetry.org/docs/repositories/#explicit-package-sources).
> If package sources are configured as explicit, these sources are only searched when a package configuration [explicitly indicates](https://python-poetry.org/docs/repositories/#package-source-constraint) that it should be found on this package source.
- An update has been made to the pyproject_files_parser, which previously ignored package source configuration in pyproject.toml …

Respect poetry explicit source

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/images-branch.yml
.github/workflows/images-latest.yml
.github/workflows/images-updater-core.yml
.github/workflows/smoke.yml

We don't yet have any submodules, but we will be adding one with Nuget updater overhaul. In other to deploy those changes, I need to run the branch-images workflow manually, but that will always use the version of workflows in main (or optionally in a branch of our own repo), so I cannot build an image for that PR without introducing this first.

Clone submodules in CI workflows

---

.github/workflows/images-branch.yml

This is a follow up to #8429. When building images manually, we need to manually checkout PRs, so we also need to manually clone submodules.

Clone submodules when building images manually

---

docker/lib/dependabot/docker/tag.rb
docker/spec/dependabot/docker/update_checker_spec.rb

We currently special case `mcr.microsoft.com/windows/servercore`. This is because normally suffixes including non numeric characters signal prereleases, but in the case of these images, they have the `KB-` suffix which actually means cumulative updates over the base version, not prereleases.
This is really not great, and we should figure out a better way to give people what they want rather than adding special cases all over the place.
However, we have been special casing `KB` for a long time, so for now this PR fixes an issue that I found with it. It's the following:
```
$ bin/dry-run.rb docker dotnet/dotnet-docker  --dir /src/aspnet/6.0/nanoserver-1809/amd64/ --cache files
=> reading dependency files from cache manifest: ./dry-run/dotnet/dotnet-docker/src/aspnet/6.0/nanoserver-1809/amd64 …
```

Fix windows servercore Docker updates

---

bundler/helpers/v1/lib/functions.rb
bundler/helpers/v2/lib/functions.rb

While working on #8138, I realized that our Bundler native helpers in production are running with the `frozen` setting set to `true`, because that's what it's set in the updater image as configuration:
https://github.com/dependabot/dependabot-core/blob/7e90f1c86f9da0011397734f28c69637b8c470b8/Dockerfile.updater-core#L118
Our native helper specs don't catch this, because they don't run in the context of the `updater` directory/Gemfile, so the `frozen` setting is not visible, but they do fail when they start running in the context of the `updater` directory/Gemfile. That was surfaced by the changes in #8138.

Bundler native helpers should not run in a frozen context

---

bundler/helpers/v2/spec/functions/dependency_source_spec.rb
bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb

Bundler error message changed in Bundler 2.2.0.

Properly capture and re-raise PublicSourceTimedOut errors in Bundler

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb

In the case of git dependencies, if the version is not tagged correctly the error is not caught as a resolvability error. This adds handling for the error message if a release is not tagged as expected.

yarn:update add a handled error for missing tags

---

nuget/lib/dependabot/nuget/cache_manager.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/update_checker/compatibility_checker.rb
nuget/lib/dependabot/nuget/update_checker/dependency_finder.rb
nuget/lib/dependabot/nuget/update_checker/tfm_comparer.rb
nuget/lib/dependabot/nuget/update_checker/tfm_finder.rb

This change bumps the type strictness for the files added in #8179. That PR was started before Sorbet was added to the codebase, so it's expected that they started as `#typed: false`.
The bump was performed automatically with `bundle exec spoom bump --from=false --to=true nuget`.

Bump `nuget` files type strictness

---

python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb
python/spec/fixtures/pyproject_files/inline_comments.toml

Fix for the following issue:
https://github.com/dependabot/dependabot-core/issues/8366

Capture dependencies groups with inline comments in pyproject files

---

python/lib/dependabot/python/update_checker/index_finder.rb
python/spec/dependabot/python/update_checker/index_finder_spec.rb

- fix #8414
> Package source constraints are strongly suggested for all packages that are expected to be provided only by one specific source to avoid dependency confusion attacks.
https://python-poetry.org/docs/repositories/#package-source-constraint
- Update the `index_finder.rb` script to ensure that if a dependency has a package source configuration in `pyproject.toml`, it won't utilize any other sources as its `:main` source.
- Please note that the behavior may not completely align with Poetry's behavior. 
- For example, if a package points to a source that is not defined in `pyproject.toml`, Poetry will raise an exception, but Dependabot will continue to check the default source. 
- **Should we consider aligning dependabot behavior with Poetry's in this regard?**
- dependabot bot …

fix #8414 follow poetry source constraint

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/registry_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/private_registry_ghpr/.npmrc
npm_and_yarn/spec/fixtures/projects/pnpm/private_registry_ghpr/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/private_registry_ghpr/pnpm-lock.yaml

One case where they happen is when the user configures incorrectly
`https://npm.pkg.github.com/<org>` as the scope, instead of just
`https://npm.pkg.github.com`.
Another case (I did not test this but I suppose), is when the user
specifies a PAT without the proper read_packages scope.

Handle 403 Forbidden errors from PNPM

---

github_actions/lib/dependabot/github_actions/update_checker.rb

After deploying #8441, I saw this new error:
```
Parameter 'ref': Expected type String, got type NilClass
Caller: /home/dependabot/common/lib/dependabot/git_commit_checker.rb:98
Definition: /home/dependabot/common/lib/dependabot/git_metadata_fetcher.rb:71
```
I think this should fix the culprit.

Fix type issues detected in GitHub Actions ecosystem

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

This is a recreation of #7140 but with changes from #7487 and simpler tests.
When truncating the PR descriptions for Azure, the string is converted from UTF-8 to UTF-16, operated on then changed back to UTF-8. The last step fails resulting in a string with an invalid string that cannot be converted to JSON for the request body and the PR cannot be created.
This PR changes from `force_encoding(...)` to `encode(...)` which seems to solve the problem.
The spec I have added fails when using `force_encoding(..)` but works with `encode(...)` as guided by some [Stack Overflow post](https://stackoverflow.com/a/10466273). The issue shows up when converting to JSON using `to_json` so the spec is modified to test exactly that.
This should fix …

Fix encoding changes when truncating PR descriptions

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

fixes #7662
Group PRs that only have 1 dependency are missing the version from -> to line. 
There are examples in this very repo: https://github.com/dependabot/dependabot-core/pull/8459
The reason this happened is in the past, for PRs with one dependency the version update was included in the title. For grouped updates, the group info is included in the title, so the version info needs to be in the body. We just missed one place where we needed to check for a group.

fix grouped update PRs are missing current -> updated version message

---

common/lib/dependabot/git_commit_checker.rb
github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/spec/dependabot/github_actions/file_parser_spec.rb
github_actions/spec/fixtures/workflow_files/inaccessible_source.yml

The functionality that needs accessing the dependency source is not critical, so skip it if the repo is not accessible. The end result of this should be that we still parse the dependency, and it will be properly ignored before checking updates for it. If it's a non ignored dependency, we should be getting another `git_dependencies_not_reachable` error when checking for updates.

Ignore repo access issues while parsing actions dependencies

---

common/lib/dependabot/clients/codecommit.rb
common/spec/dependabot/clients/codecommit_spec.rb

While looking into https://github.com/dependabot/dependabot-core/pull/8460, I grepped for codecommit requires and I wonder whether we were actually using this dependency.
Then I found this error in our error tracker:
```
uninitialized constant Dependabot::Clients::CodeCommit::Aws
Aws::CodeCommit::Client.new
```
Sounds like we are missing a require?

Fix missing codecommit require

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/registry_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/private_tarball_urls/.npmrc
npm_and_yarn/spec/fixtures/projects/pnpm/private_tarball_urls/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/private_tarball_urls/pnpm-lock.yaml

I think this should be the last big category of PNPM errors we were not handling!

Handle 401 Unauthorized errors from PNPM

---

common/lib/dependabot/dependency_file.rb
common/lib/dependabot/workspace/base.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/registry_parser.rb
python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb

This is splitting out the `spoom bump` from #8469 while I figure out why `bundle exec spoom bump --from=true --to=strict` _really_ wants to bump `bundler/helpers/v1/run.rb` when it doesn't meet the requirements to be `strict.`

Bump type strictness

---

.gitattributes

Since #6682 all files in the repository have been normalized to LF. However, when checking out the repository on Windows, and `core.autocrlf` or `core.eol` are unset, line endings are set to CRLF. See [the documentation][^1]:
> If the eol attribute is unspecified for a file, its line endings in the working directory are determined by the `core.autocrlf` or `core.eol` configuration variable (see the definitions of those options in [git-config[1]](https://git-scm.com/docs/git-config)). If `text` is set but neither of those variables is, the default is `eol=crlf` on Windows and `eol=lf` on all other platforms.
We should default to a known good configuration, and not depend on people to have the correct git config to.
[^1]: https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt …

Enforce LF line endings on checkout

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb

Unfortunately I created a test feed and test repo but have not being able to reproduce the issue, so I cannot validate whether this fixes it.
Would fix #7759.

Fix private registry authentication for NPM 8 or higher

---

updater/lib/dependabot/updater/operations/refresh_group_security_update_pull_request.rb

Forgot to add support for this in #8331

add support for refreshing a grouped security update

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser/property_value_finder.rb
nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
nuget/spec/dependabot/nuget/update_checker/dependency_finder_spec.rb
nuget/spec/fixtures/configs/example.com_nuget.config
nuget/spec/fixtures/csproj/directory_build_props_that_pulls_in_from_parent.props
nuget/spec/fixtures/csproj/directory_build_props_with_package_update_variable.props
nuget/spec/fixtures/csproj/directory_build_props_with_property_version.props
nuget/spec/fixtures/csproj/property_version_not_in_file.csproj
nuget/spec/fixtures/nuget_responses/example_index.json
nuget/spec/fixtures/nuspecs/Microsoft.Extensions.DependencyModel_42.42.42_faked.nuspec
nuget/spec/fixtures/nuspecs/Microsoft.NETCore.Platforms_43.43.43_faked.nuspec

Fixes #8470 (2 issues)
1. `api.nuget.org` was always queried, even if not listed in the `NuGet.Config` file; this simply removes that and also adds a test to ensure it's not hit.
2. When searching `Directory.Build.props/.targets`, only the first found file was considered; instead, _all_ files up to the root of the repo need to be searched for the specified properties.

Honor NuGet.config sources and search all build files for properties

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/file_updater.rb
docker/lib/dependabot/docker/tag.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/dependabot/docker/file_updater_spec.rb
docker/spec/fixtures/docker/dockerfiles/underscore
docker/spec/fixtures/helm/yaml/digest.yaml

As part of the work inside Azure DevOps to improve dependabot (see #8179) there were some updates to the Docker updater that needed to be split out into their own PR, specifically:
- Allow docker version prefixes to contain underscores
- Add support for digests when updating helm charts
(cc @brbayes-msft)

port Docker updater improvements from Azure DevOps

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
updater/lib/dependabot/dependency_change_builder.rb
updater/lib/dependabot/updater/operations/create_group_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_group_security_update_pull_request.rb
updater/lib/dependabot/updater/security_update_helpers.rb
updater/spec/dependabot/dependency_change_builder_spec.rb

Fix up the title and PR body for mutli-directory PRs so they split the dependency updates by directory.
So https://github.com/dsp-testing/gsu-7/pull/1 would look like

Teach Dependabot how to present multi-directory PRs

---

common/dependabot-common.gemspec
updater/Gemfile.lock

See https://github.com/flori/json/issues/553
Credit to @JamieMagee for spotting the issue.
`json` should probably be listed in the gemspec anyway since we use it directly.

fix regression in json gem by using an older version

---

.github/workflows/smoke.yml

I'm trying to come up with a way to discover smoke tests dynamically and run them in dependabot-core. While doing that I realized there was a simpler way to do the filters. So I thought I would ship this PR first to clean things up and make sure it worked.
The idea is that if any of the "common" files change we need to run all smoke tests, so there's no reason to list every test out in the filters, just the directories in core that changed. It gets rid of a lot of duplication.

clean up smoke.yml

---

maven/lib/dependabot/maven/metadata_finder.rb

In #8327 the FileFetcher was switched from Base to the Maven one, but the require was missed, so sometimes tests fail due to this if it didn't happen to be required by another file first.

require correct FileFetcher

---

updater/lib/dependabot/updater/group_update_creation.rb

When checking to see if all versions are ignored, grouped security updates need to call `lowest_security_fix_version`, otherwise it will continue and throw AllVersionsIgnored which halts the update.

fix group update creation failure when a dependency is ignored

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
nuget/spec/fixtures/configs/versioned_search.config
nuget/spec/fixtures/nuget_responses/index.json/versioned_SearchQueryService.index.json

From [this comment](https://github.com/dependabot/dependabot-core/pull/8502#issuecomment-1840756122), a NuGet repository's `:search_url` can't be found if it has a version suffix like `/3.0.0`, etc.  This PR checks in priority order for the specific `SearchQueryService` value.

properly resolve nuget search query when the api is versioned

---

.github/smoke-filters.yml
.github/smoke-matrix.json
.github/workflows/smoke.yml

Another step towards dynamic discovery of smoke tests.
In this PR I split the filter and matrix out into separate files. The filter was just for vanity, makes it much easier to read the workflow. Having the matrix suites in a file allows us to run the dorny/paths-filter action first and then filter the matrix.json to only tests that needs to run. 
In other words, going forward when you change a file in `go_modules`, it won't run the `bundler` smoke test only to skip all steps. Instead it won't even run in the first place!

only run suites that have changes

---

python/helpers/requirements.txt

The [PR](https://github.com/pypa/pipenv/pull/6024) that we were cherry-picking has been merged, and also [another one](https://github.com/pypa/pipenv/pull/6021) that will fix more Dependabot errors.
Still no release but we can switch back to the upstream repo.

Use upstream pipenv again

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

~Apparently a `HEAD` request is incorrectly returning 404 sometimes. Downloading the full tgz may be heavy, but I think it won't happen often and correctness should come before speed. We can iterate later if this fixes the problem.~
After testing with OP, it was found that it was the %2F in tarball URLs that was causing this, so this PR was changed to not escape dependency names when building tarball URLs for yanked detection.  
Closes #8544.

Don't escape dependency names in tarball URLs since it doesn't always work

---

.github/smoke-matrix.json
.github/workflows/smoke.yml

When adding a new smoke test, we had to remember to also add it to this list of tests, which inevitably means we forgot.
This change pulls the list of tests from the smoke test so as long as it's on main it will be run!
It relies on convention that the "test" value in smoke-matrix.json matches the test name like so: `smoke-$test-.yaml`.
So I need to rename a few tests after merging this.

dynamically discover smoke tests

---

nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
nuget/spec/fixtures/configs/with_trustedSigners.config

This fixes 2 issues with querying NuGet apis:
1. Allow querying from the `trustedSigners` section of `NuGet.Config`
2. Allow querying v2 APIs to determine dependency eligibility

improvements to querying nuget apis for versions

---

docker/lib/dependabot/docker/file_parser.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/dependabot/docker/update_checker_spec.rb
docker/spec/fixtures/docker/registry_tags/bar_with_v.json

This reverts https://github.com/dependabot/dependabot-core/pull/8165 which caused a regression in updates for docker tags with a 'v' prefix. We missed this because we didn't have test coverage across the FileParser and UpdateChecker for this case. I added a test to help prevent reoccurrence.

Fix docker updates for tags with a v prefix

---

nuget/helpers/lib/NuGetUpdater/NuGetProjects/Directory.Build.props
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.CommandLine/NuGet.CommandLine.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Commands/NuGet.Commands.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Common/NuGet.Common.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Configuration/NuGet.Configuration.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Credentials/NuGet.Credentials.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.DependencyResolver.Core/NuGet.DependencyResolver.Core.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Frameworks/NuGet.Frameworks.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.LibraryModel/NuGet.LibraryModel.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.PackageManagement/NuGet.PackageManagement.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Packaging/NuGet.Packaging.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.ProjectModel/NuGet.ProjectModel.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Protocol/NuGet.Protocol.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Resolver/NuGet.Resolver.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Versioning/NuGet.Versioning.csproj

This corresponds with the latest `nuget.exe` download from https://nuget.org/downloads
I've also copied over several `<NoWarn>` and `<Nullable>` tags from the submodule projects to make the build output cleaner; this has no functional effect.

update NuGet.Client submodule to latest public release, 6.8.0.131

---

docker/lib/dependabot/docker/file_parser.rb

When attempting to append a digest for helm charts, the docker updater is failing because the `.append` method does not exist.  This corrects that behavior to use the proper append syntax.

Fix docker attempting to append digest for helm

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npmrc_builder_spec.rb
npm_and_yarn/spec/fixtures/projects/npm6/private_source_shrinkwrap/npm-shrinkwrap.json
npm_and_yarn/spec/fixtures/projects/npm6/private_source_shrinkwrap/package.json

npm-shrinkwrap.json may be in a repository without a lockfile, so Dependabot needs to look at it to infer a private registry in the npmrc file.

consider shrinkwrap when inferring an npmrc file

---

nuget/helpers/lib/NuGetUpdater/.gitignore
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/SdkPackageUpdaterHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/SdkPackageUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs

This enables the NuGetUpdater to handle "old-style" csproj files where the Version is a child of the PackageReference instead of just attributes.
Recommend reviewing with `&w=1` in the URL to disable whitespace diff.

Handle Version Elements in Update

---

composer/lib/dependabot/composer/file_fetcher.rb
composer/lib/dependabot/composer/file_updater/lockfile_updater.rb
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/file_fetcher_spec.rb
composer/spec/fixtures/github/artifact_directory_listing.json
composer/spec/fixtures/github/composer_json_with_artifact_deps.json
composer/spec/fixtures/github/dependency.json

With Composer it's possible to have artifact repositories which are a local directory of zipped dependencies: https://getcomposer.org/doc/05-repositories.md#artifact
Since Dependabot wasn't fetching these archives, or even the empty directories, Composer was throwing errors saying the file wasn't found:
```
RecursiveDirectoryIterator::__construct(path/to/zipped/packages): failed to open dir: No such file or directory
```
This PR tries downloading the zipped files if they exist. If not a fake `.gitkeep` is added so it will create the directory to appease Composer.

support Composer artifact repositories

---

github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb
github_actions/spec/fixtures/workflow_files/pinned_sources_version_comments.yml

Fixes #8559
If an Action is pinned to a SHA with no tag, then it would fail to find the tag and try to create a Version with `nil` which raises an exception.
So adding a guard clause to fix that and let the update complete. The comment will not be updated since it can't match a tag that doesn't exist.

fix exception when Action is pinned to a SHA with no tags

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/update_checker.rb

Over the past couple of years, we've significantly thinned out the `go` native helper functionality in favor of leveraging `go mod` CLI.
I'm reasonably confident we've removed the ruby calls in these two files to the native helper, so this removes the orphaned/leftover `require` statements.

Remove unused `requires` of deleted `go` native helper functionality

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

Fix version information missing from the commit message when a dependency group only updates one dependency.
Relates to #8217.
For example:
https://github.com/martincostello/project-euler/pull/317/commits/62bf0f9046a782d0233aed41e9fe466aa6751f95
```text
Bump the xunit group with 1 update
Bumps the xunit group with 1 update: [xunit](https://github.com/xunit/xunit).
- [Commits](https://github.com/xunit/xunit/compare/2.6.2...2.6.3)
---
updated-dependencies:
- dependency-name: xunit
dependency-type: direct:production
update-type: version-update:semver-patch
dependency-group: xunit
...
Signed-off-by: dependabot[bot] <support@github.com>
```
https://github.com/martincostello/project-euler/pull/315/commits/741ea1e80fb1bd5c9ab6dbf24001860ccc62efaf
```text
Bump the xunit group with 2 updates
Bumps …
```

Fix missing version in commit message for dependency group with 1 update

---

omnibus/Gemfile

The CI on `main` is randomly breaking because we don't have `sorbet` pinned.
This will make it so we update our types in a more controlled manor when Dependabot bumps the dependency.

pin Sorbet's version so it doesn't randomly break

---

python/lib/dependabot/python/file_fetcher.rb

It's not revealed anywhere what version of Python Dependabot is using.
This is helpful when Python users haven't specified what version of Python to use, and may be experience "update not possible" errors because their dependency doesn't support that version.

help customers debug Python issues like update_not_possible

---

go_modules/lib/dependabot/go_modules/file_updater.rb

While running the `go_modules` tests, I noticed that the `git` warning about an unspecified default branch was being repeatedly thrown in tests.
Originally I assumed it was a bad test fixture setup (similar to @deivid-rodriguez 's fixes in  https://github.com/dependabot/dependabot-core/pull/8100 / https://github.com/dependabot/dependabot-core/pull/8113), but I tracked it down to here which appears to run in production... so it may be filling production logs in addition to CI logs.
Before adding this line:
```
[dependabot-core-dev] ~/go_modules $ rspec ./spec/dependabot/go_modules/file_updater_spec.rb:179
Randomized with seed 30583
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all …
```

Stop printing pointless `git` default branch warning into logs/tests

---

common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb

Re-opening this PR from my own repo since I'm no longer on the :dependabot: team so no longer have write access to the main repo:
* https://github.com/dependabot/dependabot-core/pull/6455
As noted in that PR, https://developercommunity.visualstudio.com/content/problem/608769/add-support-for-in-markdown.html eventually leads to https://developercommunity.visualstudio.com/t/add-support-for-the-html-tag-in-markdown/609415#T-N1190213 specifies that Azure ADO now supports the `<details>` tag in Markdown.
Users also chimed in on https://github.com/dependabot/dependabot-core/pull/6455 to provide proof that it works as expected.
Fix #6453

Azure DevOps now supports HTML in PR descriptions

---

common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb
common/spec/dependabot/pull_request_creator/message_builder/metadata_presenter_spec.rb

Depends on, this should get merged first:
* https://github.com/dependabot/dependabot-core/pull/8628
--
I noticed in https://github.com/dependabot/dependabot-core/pull/6467 that @brrygrdn had added some nice tests for Azure / HTML fragments. He did some refactoring work to change the behavior of what got sanitized that I was a little hesitant to grab without further investigation. However, I'm no longer on the :dependabot: team and my free time open source efforts are currently focused elsewhere so I'm not going to dig into the full refactoring.
However, I did want to cherry-pick over this small set of tests for Azure out of that PR, as it is straightforward.

Add a test for Azure sources

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb
common/spec/dependabot/pull_request_creator/branch_namer/dependency_group_strategy_spec.rb

This PR passes the `includes_security_fixes` param to the BranchNamer so that we use special branch names for multi-directory grouped security updates.
The branch name for these PRs now read:
`dependabot/bundler/group-security-bundler-b8d660191d`
This shouldn't change the branch name for any other type of PR.

Use a hash in the branch name for multi-directory grouped security updates

---

sorbet/rbi/shims/opentelemetry-sdk.rbi
updater/lib/dependabot/base_command.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/opentelemetry.rb
updater/lib/dependabot/update_files_command.rb

This pull request primarily focuses on enhancing the OpenTelemetry integration within the Dependabot system, with changes spanning across multiple files. The main changes include the addition of `shutdown` and `force_flush` methods to the `TracerProvider` class, ensuring the shutdown of the OpenTelemetry exporter in the `run` method, and renaming the spans in `perform_job` methods while also setting the attribute for `JOB_ID`.
Changes to Dependabot's OpenTelemetry usage:
* <a href="diffhunk://#diff-0ae3ea6b30ef21b78d5b11abdd5a8b478e3df86e9c2d681c88fc4d03f49e170bR59-R60">`updater/lib/dependabot/base_command.rb`</a>: Ensured the shutdown of the OpenTelemetry exporter in the `run` method. This ensures that the OpenTelemetry system is properly closed when the run method finishes execution.
* …

Fix up some of the open telemetry issues

---

terraform/Dockerfile

Release notes
https://github.com/hashicorp/terraform/releases/tag/v1.6.2
https://github.com/hashicorp/terraform/releases/tag/v1.6.3
https://github.com/hashicorp/terraform/releases/tag/v1.6.4
https://github.com/hashicorp/terraform/releases/tag/v1.6.5
https://github.com/hashicorp/terraform/releases/tag/v1.6.6

build(deps): bump Terraform to 1.6.6

---

.github/workflows/images-branch.yml

It's difficult to tell if the branch images job was skipped or not, making it hard to pick the SHA out of the output and do a deployment.
This moves the part where it figures out if the PR is approved to a first step, and if it's not approved it skips the entire `push-updater-images` which makes it really obvious.

improve how branch images skips

---

.github/dependabot.yml

Forgot to do this along with https://github.com/dependabot/dependabot-core/pull/8686.

Dependabot should keep Cargo up to date

---

nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb

Previously we would create Azure NuGet package URLs in a "friendly" format like this:
```
https://pkgs.dev.azure.com/dnceng/public/_apis/packaging/feeds/dotnet-public/nuget/packages/Newtonsoft.Json/versions/13.0.1/content?sourceProtocolVersion=nuget&api-version=7.0-preview
```
Azure would then return a `303` with the "real" download URL, something like this:
```
https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/newtonsoft.json/13.0.1/newtonsoft.json.13.0.1.nupkg
```
Given that we've already pulled in the `index.json`, we know exactly what the "real" URL will be, so we simply create that directly, since we know it's a V3 API.
This allows us to simplify the code a bit.
There was an internal PR earlier today …

create azure nuget package urls directly from endpoint types

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/resolvability_errors.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb

fix #8700
As @JamieMagee mentions, without the -e flag unsupported versions of modules breaks updates for the entire run since `go list` errors out.
It might be worth throwing this into the Go smoke test to prevent regressions.

fix unsupported Go modules preventing updates

---

.github/dependabot.yml

All other dependencies from common are already managed by the updater Dependabot configuration.

Only create PRs for dependencies in the sorbet group

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
nuget/spec/fixtures/github/csproj_in_subdirectory/NuGet.Config
nuget/spec/fixtures/github/csproj_in_subdirectory/src/some-project/some-project.csproj

If dependabot is started from a deep directory, a `NuGet.config` file further up the tree (e.g., at the root) wasn't properly found.  This fixes the search behavior to look further up when the file name might not be `NuGet.config`, but `../../NuGet.config`.

properly locate `nuget.config` when it's further up-directory from a project

---

bin/dry-run.rb
npm_and_yarn/Dockerfile
npm_and_yarn/helpers/test/npm6/conflicting-dependency-parser.test.js
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/json_lock.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/native_helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

~We're already using corepack to activate the version of Yarn used by each project through the `packageManager` field in their `package.json` file.~
~However, downloading and activating the project's version on the fly could fail sometimes, for example, in some firewalled environments.~
~This PR takes a more explicit approach of explicitly activating the project's version with `corepack`, but if that fails, proceed with the global version.~
~NOTE: I included a few other refactorings and improvements with the PR.~
This PR has been repurposed. Its original purpose was 👆, however, we have never heard any reports of corepack failing to activate versions, so I don't want to complicate our implementation fixing a non issue.
However, the other corepack improvements I made here seemed nice, so I …

Improve corepack setup

---

nuget/lib/dependabot/nuget/cache_manager.rb
nuget/lib/dependabot/nuget/file_parser/packages_config_parser.rb
nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/update_checker/compatibility_checker.rb
nuget/lib/dependabot/nuget/update_checker/dependency_finder.rb
nuget/lib/dependabot/nuget/update_checker/property_updater.rb
nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/lib/dependabot/nuget/update_checker/requirements_updater.rb
nuget/lib/dependabot/nuget/update_checker/tfm_comparer.rb
nuget/lib/dependabot/nuget/update_checker/tfm_finder.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb

Nuget CI is currently broken.
Issues are order dependent (although seem to be happening consistently), and can be reproduced with:
```
$ rspec './spec/dependabot/nuget/update_checker/version_finder_spec.rb[1:1:15:1:1:1,1:1:17:1:1]' --seed 17384
```
The issue is dependency caching.
This PR fixes the problem by making sure specs always avoid caching, except when the caching itself is being explicitly tested.
In addition to this, this PR also introduces some changes to make it possible to actually reproduce the failure, because running specs in isolation currently fails with another error, namely:
```
$ rspec ./spec/dependabot/nuget/update_checker/version_finder_spec.rb:407
An error occurred while loading ./spec/dependabot/nuget/update_checker/version_finder_spec.rb.
Failure/Error:
class …
```

Fix broken nuget CI

---

nuget/lib/dependabot/nuget/file_parser.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb

Right now if Dependabot is checking a directory which contains only .proj files (but that .proj file may reference a csproj higher up) it will fail with  `No project file or packages.config!`. That's because the regex used in this case is `/\.[a-z]{2}proj$/`, if we make the 2 characters optional we get the .proj file we were expecting.

Test that file_parser reads .proj files

---

docker/lib/dependabot/docker/file_parser.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/fixtures/kubernetes/yaml/unexpected_image.yaml

If the `image` field didn't match our regex we would throw when `.match` returned nil. It's possible we should handle a wider variety of image specs, but when all that fails we need to not throw nil exceptions.

Handle unexpected kub image shapes

---

nuget/helpers/build
nuget/lib/dependabot/nuget/file_updater.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/nuget_config_credential_helpers.rb
nuget/spec/dependabot/nuget/nuget_config_credential_helpers_spec.rb

When dependabot is launched, private NuGet feed credentials might be passed in via the `credentials` object.  These credentials are used to query NuGet, but when the C# command line tool is launched, these credentials are not passed through.  Since the command line tool may start other dotnet or NuGet processes, the proper way to propagate credentials is to patch the user-level `NuGet.Config` file located at `~/.nuget/NuGet/NuGet.Config`.  This patching is handled in a wrapper function that ensures the original config file is restored after calling the command line tool.  In production this file restore shouldn't matter, because a single dependabot run launches a new container then it's discarded, but when running locally it's best to restore this file.
Fixes #8721.

patch user-level `NuGet.Config` before invoking dotnet/nuget tools

---

go_modules/Dockerfile

Go 1.21.6 was released on 2024-01-09, without this Dependabot currently sees the following issue:
```
updater | 2024/01/10 21:30:34 ERROR <job_772665481> go: go.mod requires go >= 1.21.6 (running go 1.21.5; GOTOOLCHAIN=local)
```

Bump golang from 1.21.5-bookworm to 1.21.6-bookworm in /go_modules

---

common/lib/dependabot/dependency_file.rb
common/lib/dependabot/file_fetchers/base.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/updater/dependency_group_change_batch.rb
updater/spec/dependabot/updater/dependency_group_change_batch_spec.rb

In #8405 I was under the impression that `DependencyFile`'s `directory` was the directory of the file, and name was just the basename, but that's not the case. A `DependencyFile`'s `directory` should always be the job (source) directory, and the `name` contains the relative path from the `directory` and also the filename. 
Not sure what problem I was running into before, but removing `job_directory` and filtering on directory alone is passing the smoke tests, so this is confirmed!

directory is the job directory

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb
bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_3/Gemfile
bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_3/Gemfile.lock
bundler/spec/fixtures/projects/bundler1/gemfile_require_ruby_3_3/example.gemspec
bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_3/Gemfile
bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_3/Gemfile.lock
bundler/spec/fixtures/projects/bundler2/gemfile_require_ruby_3_3/example.gemspec

Added Ruby 3.3.0 to `RubyRequirementSetter` version requirements.
Think this will fix the `Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound` error raised in https://github.com/dependabot/dependabot-core/issues/8739

Added Ruby 3.3.0 to RubyRequirementSetter version requirements

---

updater/lib/dependabot/dependency_change_builder.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/spec/dependabot/dependency_change_builder_spec.rb

This is a better approach to https://github.com/dependabot/dependabot-core/pull/8782
Now no matter which Operation runs it will raise an error when there are no updated files.
Also by moving it into the DependencyChangeBuilder, it's testable!

raise a specific exception when the FileUpdater doesn't produce a change

---

.vscode/launch.json

The `omnibus` directory doesn't include `.bundle/bin/rspec` anymore, so I use the `rspec` command from `$PATH` instead. I also changed it to run the current file by default, instead of asking you to input the file path.
I also moved the tests command to the top of the list, so it runs by default when  hitting F5. I think it's more common than debugging `dry-run.rb`.

Fix vscode rdbg launch command

---

common/lib/dependabot/git_commit_checker.rb

Fixes https://github.com/dependabot/dependabot-core/pull/8789#issuecomment-1894211179

Allow `version` to be `String` or `Gem::Version`

---

.github/dependabot.yml

Group Python helper updates

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Dependency.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

The existing code includes all packageReferences the TempProject as `<PackageReference Include`, regardless of how they were found in the original context. If (for a given project) a PackageReference exists only as `<PackageReference Update` MSBuild does not load that reference and it should not appear in the Dependencies list. The way I saw this manifesting was that packages which don't get a `<PackageReference Include` in the csproj were getting manually included due to `PR Update`s, which caused `NU1605` errors (package downgrade). I assume it could have other downstream effects that don't occur to me ATM as well.
My fix is that we start keeping track of if we have only seen `Update` versions of particular `PackageReference` items, and if so we should add them to our temp project only …

Handle Update PackageReferences more correctly

---

common/lib/dependabot/pull_request_creator.rb

This is a follow up to https://github.com/dependabot/dependabot-core/pull/8793
I'm a bit new to sorbet and completely missed that the type is also defined on initializer params.
Also updated `assignees` attribute because in case of GitLab it is array of integers not strings.

Fix reviewers, assignees types in PullReqeustCreator

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ProcessExtensions.cs

There are cases where we are failing to look at the entire result of a ProcessExtensions call because we return our result as soon as `process.Exited` is Invoked. But `process.Exited` does not indicate that all the STDOUT and STDERR events have been handled, only that the process has entered the Exited state. So I took a look at [what they do in dotnet/format](https://github.com/dotnet/format/blob/main/src/Utilities/ProcessRunner.cs) and made some changes. Of particular note here is the call to `WaitForExit` which guarantees that all events currently in-flight returns before returning.
This could express itself in a lot of ways, but what I observed was that not all transitive dependencies of a project were being correctly reported (we shell that work out to MSBuild). I was unable to write …

Handle STDOUT more correctly

---

devcontainers/lib/dependabot/devcontainers/file_fetcher.rb
devcontainers/lib/dependabot/devcontainers/file_parser.rb
devcontainers/lib/dependabot/devcontainers/file_parser/feature_dependency_parser.rb
devcontainers/lib/dependabot/devcontainers/file_updater.rb
devcontainers/lib/dependabot/devcontainers/file_updater/config_updater.rb
devcontainers/lib/dependabot/devcontainers/requirement.rb
devcontainers/lib/dependabot/devcontainers/update_checker.rb
devcontainers/lib/dependabot/devcontainers/utils.rb
devcontainers/lib/dependabot/devcontainers/version.rb
devcontainers/spec/dependabot/devcontainers/file_fetcher_spec.rb
devcontainers/spec/dependabot/devcontainers/file_parser_spec.rb
devcontainers/spec/dependabot/devcontainers/file_updater_spec.rb
devcontainers/spec/dependabot/devcontainers/update_checker_spec.rb
devcontainers/spec/fixtures/projects/config_in_dot_devcontainer_folder/.devcontainer/devcontainer.json
devcontainers/spec/fixtures/projects/config_in_folder/.devcontainer/devcontainer.json
devcontainers/spec/fixtures/projects/config_in_root/.devcontainer.json
devcontainers/spec/fixtures/projects/custom_configs/.devcontainer/bar/devcontainer.json
devcontainers/spec/fixtures/projects/custom_configs/.devcontainer/foo/devcontainer.json
devcontainers/spec/fixtures/projects/deprecated/.devcontainer.json
devcontainers/spec/fixtures/projects/manifest_and_lockfile/.devcontainer-lock.json
devcontainers/spec/fixtures/projects/manifest_and_lockfile/.devcontainer.json
devcontainers/spec/fixtures/projects/multiple_configs/.devcontainer.json
devcontainers/spec/fixtures/projects/multiple_configs/.devcontainer/devcontainer.json
devcontainers/spec/fixtures/projects/multiple_roots/.devcontainer/devcontainer.json
devcontainers/spec/fixtures/projects/multiple_roots/src/go/.devcontainer/devcontainer-lock.json
devcontainers/spec/fixtures/projects/multiple_roots/src/go/.devcontainer/devcontainer.json
devcontainers/spec/fixtures/projects/sha_pinned/.devcontainer.json
devcontainers/spec/fixtures/projects/updated_manifest_outdated_lockfile/.devcontainer-lock.json
devcontainers/spec/fixtures/projects/updated_manifest_outdated_lockfile/.devcontainer.json

This change provides initial support for a [devcontainers](https://containers.dev) ecosystem, leaning heavily on the [`devcontainers/cli`](https://github.com/devcontainers/cli) for ecosystem-specific implementation.
This updater will look in the provided `--directory` for a `devcontainer.json` (or `.devcontainer.json` if `directory === /`) and update all dev container [Features](https://containers.dev/implementors/features/) that are pinned to an out-of-date major version.  The [lockfile](https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-lockfile.md) will also be updated if one is already present in the target directory.
I aim to add future updater granularity/modes in the future.
Requires at least dev container CLI …

Add `devcontainers` ecosystem

---

docker/lib/dependabot/docker/file_fetcher.rb
docker/spec/dependabot/docker/file_fetcher_spec.rb
docker/spec/fixtures/github/contents_helm_repo.json

Our helm charts have `.`'s in the middle of the file name (ie. not denoting a hidden `.file`). Dependabot isn't finding these files due to a bug in the filter regex. This fixes that issue and adds our file name pattern to the spec files.
Closes: https://github.com/dependabot/dependabot-core/issues/7008
- Fix the `docker/lib/dependabot/docker/file_fetcher.rb` yaml regex
- Update the `docker/spec/dependabot/docker/file_fetcher_spec.rb` spec to avoid regressions

Docker fetcher: support filenames with a `.` in the middle of the name

---

common/lib/dependabot/pull_request_creator.rb
common/spec/dependabot/pull_request_creator_spec.rb

I think `BranchNamer` being passed a `target_branch: nil` is a supported use case. Actually, I believe it's the most common use case: Dependabot is targeting the default branch, so the branch name it creates does not include any target branch name.

Allow BranchNamer to be passed a nil branch

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/file_updater.rb

Follow up to this PR: https://github.com/dependabot/dependabot-core/pull/8862
Looks like we use a similar regex to filter out/in the yaml Helm charts when parsing/updating the dependencies. This PR does the following:
- Moves the regexs to instance variables for reuse
- Allows `.` in the file names
- Sets the ending anchor on the regex (this was used in the fetcher but not in the parser/updater)

Docker parser/updater: also support files with a `.` in the name

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb

Expand environment variables in `NuGet.Config` as per [the documentation](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables).
There are several use cases around this, some which will work in the updater, others which will not.  One case where this won't help the updater, but is still interesting is the following:
``` xml
...
<add key="ClearTextPassword" value="%TOKEN_FROM_CI%" />
...
```
In this case the public dependabot updater won't have access to that token/environment variable, but if a user runs dependabot in their own isolated instance, they can inject that variable and it _will_ be replaced.
In the case where an environment variable couldn't be expanded, a warning is issued to help make it obvious to the user why their update may have …

try to perform environment variable expansion in `NuGet.Confing`

---

python/helpers/requirements.txt

Since our fixes are now [out](https://github.com/pypa/pipenv/releases/tag/v2023.11.17)!

Point again to latest pipenv release

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DotNetTools.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/DotNetToolsJsonUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs

Similar to how we weren't using proper discovery logic for global.json files (#8815), this change has us walk the file tree from the workspace folder up to the root looking for the dotnet-tools.json file.

Use proper discovery logic for dotnet-tools.json files.

---

gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb
gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb

Gradle was previously ignoring repositories from the top level buildfile (/build.gradle.kts) which resulted in Dependabot looking for the dependency in the wrong repository.
Some repositories are still not getting picked up correctly, specifically ones that use a custom URI like https://kotlin.bintray.com/kotlin-dev/, although that will need to be addressed separately.
Side note: the bintray repository has been sunset, so we should eventually remove it. Also, the jCenter repository is marked as read-only currently and will likely be sunset in the future.
Trying to use a repository in a top-level buildfile before this PR:
```
updater | 2024/01/24 19:30:28 INFO <job_778363964> Checking if com.gradle:common-custom-user-data-gradle-plugin 1.8.1 needs updating
proxy | 2024/01/24 19:30:28 [024] …
```

[gradle] Parse repositories from the top-level buildfile

---

nuget/lib/dependabot/nuget/nuget_client.rb
nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb
nuget/spec/dependabot/nuget/nuget_client_spec.rb
nuget/spec/dependabot/nuget/update_checker/dependency_finder_spec.rb
nuget/spec/dependabot/nuget/update_checker/nuspec_fetcher_spec.rb

Previously the NuGet updater would directly query every package feed _except_ Azure DevOps for the `.nuspec` contents, but this didn't account for both GitHub and AWS package feeds that return 404 on a `.nuspec`.
The fix is to _only_ directly pull the `.nuspec` file from the feeds that support it, specifically NuGet.org and Azure DevOps; all other feeds we pull the `.nupkg` then manually extract the `.nuspec`.  If/when we find more package feeds that _do_ allow direct pulling of the `.nuspec` files, we can add them to the allow list.
This will fix issues like the following, where the `.nuspec` couldn't be queried which meant we weren't able to parse any meaningful version numbers:
```
proxy | 2024/01/17 22:16:38 [078] GET https://nuget.example.com/some.package/1.2.3/some.package.nuspec …
```

only directly query `.nuspec` files from nuget and azure devops

---

gradle/lib/dependabot/gradle/file_parser/repositories_finder.rb

Add a guard for nil top level buildfiles
Fixes a sentry error:
```
undefined method `content' for nil:NilClass
buildfile.content
^^^^^^^^
```

Add a guard for nil top level buildfiles

---

common/lib/dependabot/pull_request_creator.rb

Should be the last fix regarding types of PullRequestCreator and GitLab implementation.
This updates `milestone` type which in case of GitLab is just a single integer.
I did ran gem built from this branch through my workflow to make sure some other thing isn't missing again and I think it should be it now.

Fix milestone type for PullRequestCreator

---

silent/tests/testdata/su-group-default-multidir.txt
silent/tests/testdata/su-group-default.txt

This better captures the current state of how GSU works in ahead of #8742.

grouped security updates don't require an explicit group

---

updater/lib/dependabot/job.rb
updater/spec/dependabot/job_spec.rb

I noticed the new devcontainers smoke test has a directory that does not start with `/`. https://github.com/dependabot/smoke-tests/blob/5b012ee504a3ec30eb05af415d600aeff5cc00fd/tests/smoke-devcontainers.yaml#L16
It just happened to work but is now breaking as I [implement multi-dir support](https://github.com/dependabot/dependabot-core/pull/8742). 
I think we can be a little more flexible here and just add the `/` and also clean the path. 
In the future I'd like to explore changing the source directory type to a `Pathname` instead of a `String` to encourage comparisons to be for the cleaned path.

clean directory at job start

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

It is very common for conditions in MSBuild to have the property values wrapped in single quotes. This PR updates `MSBuildHelper` to understand how to deal with these.
There were tests around the condition handling, so I added variations of the test data that includes quotes.

Handle MSBuild property conditions that have a property wrapped in single quotes in NuGetUpdater

---

nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/nuget_client.rb
nuget/lib/dependabot/nuget/update_checker/compatibility_checker.rb
nuget/lib/dependabot/nuget/update_checker/dependency_finder.rb
nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/lib/dependabot/nuget/update_checker/tfm_comparer.rb
nuget/lib/dependabot/nuget/update_checker/tfm_finder.rb
nuget/spec/dependabot/nuget/update_checker/compatibility_checker_spec.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
nuget/spec/dependabot/nuget/update_checker/tfm_finder_spec.rb
nuget/spec/fixtures/nuspecs/Microsoft.AppCenter.Crashes_faked.nuspec

When checking a package for TFM compatibility, the `targetFramework` attribute might be missing, so don't try to return the `nil` value.
This includes other changes as separate commits, namely:
1. Make individual classes more easily testable by lifting them directly into the `Nuget` module, and not a subclass of `UpdateChecker`.
2. Make `rubocop` happy.
The second commit is the interesting one.
Fixes #8804.

Don't assume `.nuspec` dependency group has a `targetFramework` attribute.

---

updater/lib/dependabot/job.rb
updater/spec/dependabot/job_spec.rb

fixes #8918
Introduced in https://github.com/dependabot/dependabot-core/pull/8912, when a GSU runs it has a nil directory so we must check for nil here. 
I was confused why the GSU multi-dir test didn't catch this, but it's because of https://github.com/dependabot/cli/pull/256 sending a blank String and thus no NilClass error.

fix nil directory causing NilClass exception

---

nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb
nuget/spec/dependabot/nuget/update_checker/nuspec_fetcher_spec.rb

We've seen some responses that are encoded as UTF-16LE, not UTF-8. As a result we error out when trying to force encoding and remove invalid bytes manually:
```
invalid byte sequence in UTF-8
/home/dependabot/nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb:80:in `gsub'
...
```
I tried forcing the content-encoding by adding a `Accept: text/xml;content-encoding=utf-8` header, but this wasn't respected.
Using [`String#scrub`][1] seems to be the best approach here, as it replaces invalid byte sequences in the chosen encoding with the provided replacement. For our use case, I provided an empty string as the replacement.
[1]: https://docs.ruby-lang.org/en/3.1/String.html#method-i-scrub

Remove invalid UTF-8 characters from nuspec response body

---

common/lib/dependabot/file_fetchers/base.rb
common/spec/dependabot/file_fetchers/base_spec.rb

This change allows for Dependabot to retry transient git errors with an exponential backoff. The errors below are either ones we've seen from telemetry, or possible errors in git source code.
The current backoff strategy is configured to retry 5 times, with sleep times of 3, 6, 12, 24, and 48 seconds.

Retry transient git clone errors

---

script/updater-e2e
silent/lib/dependabot/silent/file_updater.rb
silent/tests/testdata/vu-group-incidental.txt
silent/tests/testdata/vu-incidental.txt

Documenting the behavior of the updater with tests!
When a dependency depends on a specific version of another dependency they will get bumped together, but the interesting part is what Dependabot does next. 
Currently there's a bug with grouped updates using semver grouping, it will create an extra PR, so I've captured that behavior here which should be fixed by https://github.com/dependabot/dependabot-core/pull/8803.

add tests around incidental updates

---

common/lib/dependabot/file_fetchers/base.rb

After https://github.com/dependabot/dependabot-core/pull/8933 I'm noticing some smoke tests are failing to pass and the depednency files are coming back in different order depending on what system is running the test.
I think I tracked it down to `Dir.entries` which doesn't guarantee any order, so by sorting we can have more deterministic tests.
Most likely this will break some smoke tests and I'll have to regenerate them.

fix smoke tests failing because Dir.entries order is not deterministic

---

docker/Dockerfile

https://github.com/regclient/regclient/releases/tag/v0.5.2
https://github.com/regclient/regclient/releases/tag/v0.5.3
https://github.com/regclient/regclient/releases/tag/v0.5.4
https://github.com/regclient/regclient/releases/tag/v0.5.5
https://github.com/regclient/regclient/releases/tag/v0.5.6

bump(deps): bump regclient from 0.5.1 to 0.5.6

---

silent/tests/testdata/su-basic.txt
silent/tests/testdata/su-group-pattern.txt
silent/tests/testdata/su-group-semver.txt
silent/tests/testdata/su-group-type.txt
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/updater/operations_spec.rb

In https://github.com/dependabot/dependabot-core/pull/8742 the `applies_to?` method was too permissive so singular security updates are trying to create in groups.

fix security updates getting into grouped code

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb

An internal repo was failing to query packages because one of the NuGet feeds had a space resulting in the following error:
```
URI::InvalidURIError:
bad URI(is not URI?): "https://www.myget.org/F/exceptionless/api with spaces/v3/index.json"
```
The fix is to simply escape the feed URLs.  The escaping is done right after consolidating all feeds from NuGet.Config files as well as feeds from `dependabot.yml`.

escape nuget feed urls before querying

---

common/lib/dependabot/credential.rb
hex/lib/dependabot/hex/credential_helpers.rb
hex/spec/dependabot/hex/credential_helpers_spec.rb
hex/spec/dependabot/hex/file_updater/lockfile_updater_spec.rb
hex/spec/dependabot/hex/update_checker_spec.rb

Introduced by https://github.com/dependabot/dependabot-core/pull/8967, this is some untested and untyped code which is failing. 
I added the missing functionality required by this code to the Credential class and added a test for good measure.

fix TypeError: no implicit conversion of Credential into Hash

---

updater/lib/dependabot/dependency_group_engine.rb
updater/lib/dependabot/dependency_snapshot.rb

stacked on #8986
I'd like to merge this into that PR and then deploy them both. This was to make it easier to review. 
I can't use `typed: strong` yet because the dependency group passed in is untyped. In a followup refactor I'll try to address that.

type DependencyGroupEngine

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/dependency_group_engine.rb
updater/lib/dependabot/dependency_snapshot.rb
updater/spec/dependabot/dependency_snapshot_spec.rb

I changed a few of the memoized methods into methods that calculate during initialization as the types work out much more easily this way.

add types to DependencySnapshot

---

common/lib/dependabot/pull_request_creator.rb

Before #8729 `target_project_id` was `nil` when it was not provided.
Version ^0.240.0 upward is therefore broken for consumers on Gitlab.
This should be the default behaviour again.

fix(gitlab): pr creator missing default for target_project_id

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb

Since https://github.com/dependabot/cli/pull/268 we're passing Azure Artifacts feeds as `nuget_feed` (correctly) instead of `git_source`. The CLI passes the credentials to the proxy, but the updater only [gets the `host` and `type`][1].
This might conflict with #9004 
[1]: https://github.com/dependabot/cli/blob/35deb52c81b16ce706ec8601b85c589b7d483503/cmd/dependabot/internal/cmd/update.go#L361-L367

Filter out NuGet feeds which don't have URLs

---

nuget/lib/dependabot/nuget/update_checker/compatibility_checker.rb
nuget/spec/dependabot/nuget/update_checker/compatibility_checker_spec.rb

A package's `.nuspec` file can self-identify as a development dependency which normally means it can always be upgraded, but some packages exist that identify as development dependencies but also have regular `targetFramework`-specific dependencies.  The fix is to only allow development dependency upgrades if they're purely a development dependency and don't contain any other dependencies _unless_ the specified target framework is still compatible.
Fixes #9016

only consider a package a development dependency if it doesn't have any other regular dependencies

---

nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb

Private AWS NuGet feeds return `HTTP 307` when requesting the `.nupkg` contents, but the `NupkgFetcher` currently only allows `303` redirects.  The result is that `nil` is returned which causes problems much later on, including another instance of `undefined method 'fetch' for nil:NilClass`.  This PR adds a `307` redirect handler as well as a test that verifies both `303` and `307` redirects.
Fixes #9021

allow folllowing HTTP 307 when resolving `.nupkg` contents

---

silent/tests/testdata/vu-basic-directories.txt
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb

Some of our multi-dir changes leaked into non-grouped updates, the result is job definitions that have `directories: ["/"]`set rather than `directory: "/"`.
In the long run this is what we want anyway, so I've added a really easy fix in the non-grouped operations to handle this case.

fix directories in use for non-grouped updates

---

common/lib/dependabot/metadata_finders/base/changelog_finder.rb

This has a lot of:
- `T.unsafe` because the source platform clients (GitHub, Azure DevOps, etc.) all use `method_missing` to inject credentials or handle retries. Rewriting them is going to be difficult 😖
- `OpenStruct` and `Sawyer::Resource` return types, again because of source platform clients
- `T.untyped` response types because of (you guessed it!) source platform clients

Strict type `Dependabot::MetadataFinders::Base::ChangelogFinder`

---

common/lib/dependabot/dependency_group.rb
silent/tests/testdata/su-group-pattern.txt
silent/tests/testdata/su-group-semver.txt
silent/tests/testdata/su-group-type.txt
updater/lib/dependabot/dependency_group_engine.rb
updater/spec/dependabot/dependency_group_engine_spec.rb

This adds support for property `applies-to` which allows developers to specify that the group configuration should apply to only version updates, or only security updates.
For backward compatibility, if `applies-to` is not set then it applies only to version updates.

support group configs specifically for security updates or version updates

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Fix a typo (`*Dependeny*`) found in `MSBuildHelper` and `SdkPackageUpdater`.

Fix dependency typo

---

README.md
updater/lib/dependabot/setup.rb
updater/lib/dependabot/sorbet/runtime.rb

Previously if Sorbet found runtime typecheck failures, these would result in an exception, halting further job execution.
While we should be informed of those failures, there is no reason why this should end up failing the job for our customers.
This PR configures Sorbet to report the exceptions to Sentry but continue processing.

Report Sorbet issue to sentry without raising

---

common/lib/dependabot/workspace/git.rb
common/spec/dependabot/workspace/git_spec.rb

Previously `Dependabot::Workspace::Git#store_change` would attempt to create a git commit if there were changes to ignored files, which would cause `git commit` to return a non-zero status and fail the job. As of this change, the method returns early if there are no changes (to un-ignored files) to commit.
Fixes: https://github.com/dependabot/dependabot-core/issues/9060

Prevent attempt to create empty commit

---

common/lib/dependabot/shared_helpers.rb
common/lib/dependabot/workspace/git.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/helpers/test/error_bash
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/yarn_lock.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb

These currently end up in the `unknown_error category` so this provides easier visibility to the user.
- Added out of disk error message to the go module updater.
- Added out of disk/memory error message to the yarn file parser.

Surface out of disk/memory error message for easier visibility

---

docker/lib/dependabot/docker/utils/credentials_finder.rb
docker/spec/dependabot/docker/update_checker_spec.rb
docker/spec/dependabot/docker/utils/credentials_finder_spec.rb

The tests didn't catch this since they were still passing in hashes.
Thanks @noorul for https://github.com/dependabot/dependabot-core/pull/9072, I've pulled in your change and fixed up the tests.

fix docker credential type errors

---

README.md

The block of HTML code that displays a picture header at the top of
the README file is indented with 4 spaces after an empty line.
GitHub Markdown sees that as a code block (see [Indented code
blocks](https://github.github.com/gfm/#indented-code-blocks) in the
GitHub Flavored Markdown Spec).
Removing the blank line should fix it as the HTML code won't be seen as
a code block anymore and will instead be unescaped and inserted as [raw HTML](https://github.github.com/gfm/#raw-html).

Fix README image header

---

nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb

The NuGet updater is invoked with already-escaped command line options, so we can simply call it with `allow_unsafe_shell_command: true`, otherwise the arguments are double escaped.
Adding that parameter was the real fix, but I also refactored the code a bit to make testing the command line generation easier.
N.b., the helper function `run_shell_command` only takes a string which it tries to escape and that's where the problem arose; we have to pre-escape our strings to allow for a path with spaces in it, etc., and then tell `run_shell_command` that we've already escaped everything.
Fixes #8633

nuget updater command is already space-enabled; allow unsafe execution

---

.github/workflows/images-branch.yml

Follow up to https://github.com/dependabot/dependabot-core/pull/8885
It looks like sentry is receiving the default `development` value for new releases
I think it's because the "prepare tag" and "prepare tag (fork)" steps are both getting skipped and that's where we add the tag to the GITHUB_ENV.
We are missing the case where the workflow was triggered by a pull request review, so I fixed that here. I'm not sure if we should also include the `workflow_dispatch` event as well since we sometimes use that for maintainer PRs too. It would fail for forks but then they would try the "prepare tag (forks)" step and succeed. Maybe there's another way to tell if a PR is from a fork?

Run the prepare tag step on pull_request_review

---

nuget/lib/dependabot/nuget/metadata_finder.rb

We are seeing sorbet runtime exceptions caused by passing a nil argument to a typed method that expects a string. The change proposed in this PR fixes this by avoiding the method call if the argument is nil.
Fixes #9110

Avoid passing nil url to registry client

---

nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb

When testing NuGet updates against a GitHub package feed, I discovered that there were other types of `30X` redirects that weren't being followed.
This PR follows information found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) about various types of `30X` redirects, specifically, `301`, `302`, `303`, `307`, and `308`.  The redirects not covered are the ones where there's not a specific `Location:` header returned that can be followed, e.g., `300` which can specify multiple redirect options, but according to the documentation is rare, and `304` which means a cached version can be used, but our updater won't have a cached version to use.

add more http redirects

---

nuget/lib/dependabot/nuget/http_response_helpers.rb
nuget/lib/dependabot/nuget/nuget_client.rb
nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb

The NuGet updater uses the `PackageBaseAddress` endpoint to generate URLs to download `.nupkg` packages, but some feed providers don't supply that endpoint.  This is a workaround that allows `PackageBaseAddress` to be missing/`nil` and if it is, it makes a few extra network hops to discover the `.nupkg` download URL.
This PR is also dependent on a separate internal PR that injects authentication to the proper URL endpoints.
Fixes #8887.

find .nupkg URL without PackageBaseAddress

---

updater/lib/dependabot/file_fetcher_command.rb
updater/spec/dependabot/file_fetcher_command_spec.rb

For easier debugging, put the job.json output in the logs immediately during file fetching.

output job.json at the start of a run

---

nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/update_checker/dependency_finder.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb

If a package version property can't be expanded, silly things happen like querying NuGet for `$SomePackageVersion`.  This PR is 2 related fixes rolled into one.
1. Pre-filter package versions by passing them through `Version.parse()`.  If that fails, there's nothing meaningful that can be done, so we can quit early and, more importantly, cleanly.  Package versions that failed to parse are elevated to warnings.
2. Don't assume package versions in `Directory.Packages.props` are a version number; they might be a variable expansion.  Currently this PR just removes the `Version` requirement to allow the raw string to pass through, but I've filed #9151 to track future work.  The raw string pass-through will prevent a bunch of crashes if a variable is used in the property field.
This should fix …

don't fail completely if package version cannot be parsed

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs

If attempting to `nuget.exe update ...` a package when one of the other installed packages has been delisted, the operation will fail with:
```
Unable to find package 'Delisted.Package'. Existing packages must be restored before performing an install or update.
```
This PR detects this issue by checking for exit code != 0 and the message listed above (n.b., the updater image and tool is always built and run with the default locale, so this string does not need to be localized), runs `nuget restore ...`, and then retries the update procedure.  This retry is only done once and if it fails the second time, the update process will fail.
Fixes #9108.

run `nuget restore` if the first update operation failed

---

common/.rubocop.yml

Now that all of `common` is `typed: strict` this RuboCop rule ensures that going forward all files are required to remain `typed: strict`.

Require `typed: strict` for `common`

---

common/lib/dependabot/update_checkers/base.rb

Seeing `Dependabot::Sorbet::Runtime::InformationalError` saying this should be a String which makes sense since it comes in from job.json. Those values all should be Strings I would think.

fix type of requirements_update_strategy

---

updater/lib/dependabot/sorbet/runtime.rb

Sorbet errors are currently sent to Sentry. This change also sends them via OpenTelemetry.

Record Sorbet errors with OpenTelemetry

---

nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb
nuget/spec/dependabot/nuget/update_checker/nupkg_fetcher_spec.rb

Some authenticated NuGet feeds (e.g., AWS CodeArtifact) handle `.nupkg` downloads with a `307` redirect with a signed URL and that redirect (from the response header `Location: <redirected-url>`) must be used _exactly_ for it to work, otherwise it's reported as a signing failure.  The fix is to use the built-in file downloader (`RegistryClient.get`) because it sets `omit_default_port: true` to prevent `:443` from getting appended to the host.
I couldn't find a meaningful way to test this since there's no way to see if the port was manually specified or if it was inferred.  I did, however, run a manual test with an AWS CodeArtifact NuGet feed.

use built-in file downloader to get `.nupkg`

---

npm_and_yarn/Dockerfile

https://nodejs.org/en/blog/announcements/v19-release-announce
https://nodejs.org/en/blog/announcements/v20-release-announce

build(deps): bump node to v20

---

updater/lib/dependabot/updater/operations/update_all_versions.rb

We are seeing sorbet runtime exceptions caused by attempting to instantiate a dependency with nil requirements, when an array of hashes is expected. This is happening during a check that uses a dependency's `previous_requirements`, which may be nil, as the `requirements` when instantiating a new dependency.
https://github.com/dependabot/dependabot-core/blob/795dafedf31666de6e91b078b799fd7f2517478b/updater/lib/dependabot/updater/operations/update_all_versions.rb#L245-L250
This PR fixes this by bailing if `previous_requirements` is nil.
Fixes #9215

Avoid instantiating a dependency with nil requirements

---

common/lib/dependabot/pull_request_creator/message_builder/issue_linker.rb

We are seeing sorbet runtime exceptions when generating issue links during PR creation because a method is returning a nil `source_url` where a string is expected.
The exceptions are coming from `IssueLinker`:
https://github.com/dependabot/dependabot-core/blob/795dafedf31666de6e91b078b799fd7f2517478b/common/lib/dependabot/pull_request_creator/message_builder/issue_linker.rb#L49
`IssueLinker` [expects a non-nil `source_url`](https://github.com/dependabot/dependabot-core/blob/795dafedf31666de6e91b078b799fd7f2517478b/common/lib/dependabot/pull_request_creator/message_builder/issue_linker.rb#L27-L30) in its initializer, so internally it expects `source_url` to be a non-nil string.
`IssueLinker` is [instantiated by `MetadataPresenter`](https://github.com/dependabot/dependabot-core/blob/6357b576 …

Add handling for nil `source_url` in `IssueLinker` when generating PR text

---

nuget/lib/dependabot/nuget/update_checker.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

When checking for updated packages, it's possible that none of the queried sources has that package.  The result is that `UpdateChecker.latest_version` can be `nil` which leads to all sorts of problems.
The fix is to report the currently installed package version as latest if nothing could be found.  This situation was found where a user is running dependabot on their repo with only their own private NuGet feed, specifically so they could always be up-to-date with their internal organization.  During this update process, the dependency `Newtonsoft.Json` version `13.0.3` was found, but since that's a public package, it wasn't found on their private feed.  The result was `undefined method 'fetch' for nil:NilClass`.  That is obviously incorrect, so in the instance where the package could not …

report the current version as latest if nothing can be found

---

nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/spec/dependabot/nuget/file_parser/project_file_parser_spec.rb

When parsing project references, we were assuming all of the elements looked like this:
``` xml
...
<ProjectReference Include="path\to\other.csproj" />
...
```
If that `Include` attribute isn't present, then we'll eventually throw with:
```
undefined method `tr' for nil:NilClass
relative_path = ref_path.tr("\\", "/")
^^^
```
The fix is to simply skip processing that particular `<ProjectReference>` element if it doesn't have the requisite attribute.  Similar behavior is also present elsewhere in `project_file_parser.rb`, so it's a known pattern that we just missed applying here.
Of all of the current `undefined method '_' for nil:NilClass` errors in NuGet, this is the largest class.

don't assume the `Include` attribute is present on a `<ProjectReference>` node

---

nuget/lib/dependabot/nuget/requirement.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb
nuget/spec/fixtures/projects/open_upper_version_range/my.csproj

If a package version range was oddly formed then it could eventually lead to
```
undefined method `end_with?' for nil:NilClass
elsif upper_b.end_with?(")") then "< #{upper_b.sub(/\s*\)/, '')}"
^^^^^^^^^^
```
The fix is to add another `nil` guard around the result of the string split.  This is done elsewhere in this same method, so it's a valid scenario for it to short-circuit with `nil` instead of assuming we got something as a result of the split.
There are no scenarios where we need to add a `nil` check to the `lower_b` variable; it's already guaranteed to have a value from the stack frame above it.

improve robustness of parsing odd-looking version ranges

---

common/lib/dependabot/version.rb
github_actions/lib/dependabot/github_actions/version.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/version.rb
nuget/lib/dependabot/nuget/version.rb
pub/lib/dependabot/pub/version.rb
sorbet/rbi/shims/rubygems.rbi
terraform/lib/dependabot/terraform/version.rb

The upstream types for `Gem::Version.initialize`[^1] and `Gem::Version.new`[^2] are quite complex. They accept `T.any(String, Integer, Float, Gem::Version, NilClass)`.
For our use cases, these are too broad, and we see some issues with `SystemStackError` due to Sorbet's runtime type checking inserted at each level of our class hierarchy i.e. `Ecosystem::Version` -> `Dependabot::Version` -> `Gem::Version`.
Sorbet does have documentation on how to [narrow the types of a child method][1]. The documentation suggests altering the parent class to be generic, and specifying the generic type in child classes. Unfortunately, it's not feasible to alter the root class, `Gem::Version`.
Another approach might be to use one of Sorbet's escape hatches `override(allow_incompatible: true)`[^3]. But this …

Simplify type parameters for `Gem::Version`

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb

We are seeing sorbet runtime exceptions when checking if the corresponding types package for a dependency should be updated due to passing a nil version to [`#backwards_compatible_with?`](https://github.com/dependabot/dependabot-core/blob/0661469a58981018312249c24306fa34bf08d8fa/npm_and_yarn/lib/dependabot/npm_and_yarn/version.rb#L75-L76):
https://github.com/dependabot/dependabot-core/blob/0661469a58981018312249c24306fa34bf08d8fa/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb#L273
This PR addresses this by returning early if the latest types package version is nil.
Fixes #9241

Avoid comparison with nil version

---

nuget/lib/dependabot/nuget/file_updater.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb

We've seen behaviour when we attempt to use NuGet to perform an update, where the remote dependency tree is not complete. For example, imagine we have the following dependency tree:
```mermaid
flowchart LR
MyProject -->|Depends on| A[A 1.0]
A -->|Depends on|B[B 1.0]
```
If package A version 2.0 is published, and it has a dependency on package B version 2.0, but that package isn't yet published to the NuGet feed, the upgrade will fail. NuGet will give the error `WARNING: Install failed. Rolling back...` and remove the existing dependencies on package A version 1.0 and package B version 1.0. This rollback behaviour of NuGet is not configurable.
To try and catch this, I'm comparing the number of lines in the original content versus the updated content. If the updated content has less lines …

Filter out NuGet files where lines were only deleted

---

nuget/lib/dependabot/nuget/update_checker.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

When trying to update a vulnerable package, it's possible that no non-vulnerable compatible package can be found.  In this instance it was leading to another case of this:
```
undefined method `fetch' for nil:NilClass
latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
^^^^^^
```
The fix is to use the safe navigation operator (`&.`) to allow `nil` to propagate all the way up.  This behavior is expected and allowed in this case because further along the modified line is another safe navigation (`&.to_s`) and on the next line is yet another (`&.slice(...`).
The `nil` propagation in this case flows into `requirements_updater.rb` where it's explicitly allowed, both in the [initializer](https://github.com/dependabot/dependabot-core/blob/971d0915d9c42845675c3e8ba3f45a9d9e …

use safe navigation through resolvable version

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

Fix the number of updated directories in a group update.
Previously we were listing the number of directories that Dependabot would try to update instead of the number of directories that were _actually_ updated.
This only affects the PR title and the commit message (since it uses the PR title)

Fix the number of updated directories in a group update

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This should allow other potential updates to flow instead of erroring out the whole process.

when resolving MSBuild properties, don't throw if it can't be resolved

---

nuget/lib/dependabot/nuget/update_checker/compatibility_checker.rb
nuget/spec/dependabot/nuget/update_checker/compatibility_checker_spec.rb

When determining the target frameworks that a package supports, we first check the `.nuspec` file.  If that doesn't list anything then we open the `.nupkg` as a zip file and find all subdirectories under the `lib/` directory.  Some zip compressors create empty entry objects for each directory which could cause the string split to return `nil` eventually resorting in:
```
ArgumentError
comparison of NilClass with String failed
```
The fix is to exlucde these `nil` entries.  This was a large class of failures in the telemetry.

ensure nupkg zip entry contains a tfm before adding to the list

---

nuget/Dockerfile

This should fix #9249 (at least the error about the missing 8.0.101/8.0.201 SDK).

update dotnet sdk

---

bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
common/lib/dependabot/update_checkers/version_filters.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
gradle/lib/dependabot/gradle/update_checker/version_finder.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb

When doing an update, you might get an update_not_possible error with the following logs:
```
updater | Latest version is 1.0.0
updater | Requirements to unlock update_not_possible
updater | Requirements update strategy bump_versions
updater | No update possible for my-dependency 1.0.0
```
One of the reasons this can happen is that all versions were filtered out while trying to update a specific dependency. 
This PR aims to improve the logging for ecosystems to give users a hint of why the update is not possible:
```
updater | Latest version is 1.0.0
updater | Requirements to unlock update_not_possible
updater | Requirements update strategy bump_versions
updater | Filtered out 156 unsupported Python 3.11 versions
updater | Filtered out 12 pre-release versions
updater | Filtered out 256 …
```

improve update-not-possible logging

---

common/lib/dependabot/errors.rb
updater/lib/dependabot/base_command.rb
updater/lib/dependabot/file_fetcher_command.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater/error_handler.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater/error_handler_spec.rb
updater/spec/dependabot/updater_spec.rb

We're using a mix of dashes and underscores, which I find confusing. I've introduced some failures trying to get these right, so I'm making all string keys dasherized.

📏 Standardize Error Keys

---

common/lib/dependabot/file_fetchers/base.rb
common/spec/dependabot/file_fetchers/base_spec.rb
go_modules/lib/dependabot/go_modules/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb

In https://github.com/dependabot/dependabot-core/pull/8933 we made all ecosystems clone rather than fetching single files. 
Similarly this PR enables recurse submodules for all ecosystems to fix some path dependency issues. The only downside would be an increase in out of disk errors but we can onboard to Actions beta now which increases the amount of disk available.
Fixes #8428
Fixes #9198
Fixes #7201
Fixes #9193
Fixes #7916
Supersedes:
- #7078
- #9181
- #8807

always recurse submodules when cloning

---

python/helpers/lib/parser.py
python/helpers/requirements.txt
python/helpers/run.py

I couldn't figure out why the tests were failing for:
* https://github.com/dependabot/dependabot-core/pull/7741 (which was superseded by https://github.com/dependabot/dependabot-core/pull/8627)
until I realized that `pipfile` imports `toml`:
https://github.com/pypa/pipfile/blob/4706d2cbd35e0b47a05a6421fa17f93827bc454f/setup.py#L44
which then gets used over in the unrelated file `parser.py`: https://github.com/dependabot/dependabot-core/blob/89ebc55dac8630574301a10917425f80a56e4763/python/helpers/lib/parser.py#L24
So let's make the import of `toml` explicit so that we aren't relying on the side effects of importing `pipfile`. The `toml` requirement from `pipfile` isn't pinned, so I simply pinned to the latest release.
Python `3.11` added a native `tomllib` library, so once we drop support …

Make `toml` an explicit requirement

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb

When an appropriate NuGet dependency file could not be found, return a more specific error message.  This also explicitly limits project files to the extensions `.csproj`, `.vbproj`, and `.fsproj`.  The earlier mechanism would allow other things like `.sfproj`, but the C# updater tool doesn't allow that, so we're tighter on what we'll accept/scan.

make dependency file not found message more specific

---

nuget/lib/dependabot/nuget/file_parser.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb

This should help when investigating update failures from log files.  Test contains sample output.

report discovered dependencies and requirement metadata

---

.github/workflows/gems-bump-version.yml

Improve security by switching to the official GitHub action for managing app tokens. More [details](https://github.com/tibdex/github-app-token/issues/99#issuecomment-1787602874).
The default scope is limited to only this repo per the [docs](https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories):
> If owner and repositories are empty, access will be scoped to only the current repository.
See also:
* https://github.com/dependabot/fetch-metadata/pull/504

Switch to official GitHub action for managing app tokens

---

go_modules/lib/dependabot/go_modules/file_fetcher.rb
go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/replace_stubber.rb
go_modules/lib/dependabot/go_modules/requirement.rb

This PR adds `strict` Sorbet annotation in some files in `go_modules` and enables Sorbet Runtime.

Cover parts of `go_modules` code with Sorbet

---

nuget/lib/dependabot/nuget/update_checker/property_updater.rb

Fix from #9337 
Seen in production stack traces
```
T.let: Expected type T.nilable(String), got type Dependabot::Nuget::Version with value #<Dependabot::Nuget::Version 14.1.4>
Caller: /home/dependabot/nuget/lib/dependabot/nuget/update_checker/property_updater.rb:38
```

`@target_version` can be `String` or `Dependabot::Nuget::Version`

---

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
python/spec/fixtures/pyproject_files/poetry_non_package_mode.toml

Starting with version 1.8, Poetry has a non-package mode for projects using Poetry not for building and publishing packages but only for dependency management. `name`, `version`, `description` and `authors` fields are optional in non-package mode.

Support Poetry non-package mode

---

silent/tests/testdata/vu-group-update-not-possible.txt
updater/lib/dependabot/updater/group_update_refreshing.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb

When there's a grouped PR and Dependabot rebases it, but all the dependencies are up to date because a developer went and manually bumped them, Dependabot will close the PR with the message:
> Looks like these dependencies are up-to-date now, so this is no longer needed
The problem is at this point in the code we don't necessarily know _**why**_ there are no updated dependencies. It could be that they were all up to date, but also could be they all errored, perhaps all ignored, or some other reason.
In lieu of tracking why each dependency failed to update, this PR switches the Dependabot message in this scenario to:
> Looks like these dependencies are no longer updatable, so this is no longer needed.
This better captures the reason why the PR was closed.

swap language when closing group refresh PR to be less specific

---

updater/lib/dependabot/updater/group_update_creation.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb

We are seeing runtime exceptions due to calling a method on an argument that may be nil. This change properly handles nil arguments.

Prevent `NoMethodError` in group update creation

---

nuget/lib/dependabot/nuget/file_parser.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/fixtures/csproj/basic2.csproj

If a `<TargetFramework>` cannot be parsed from a `.csproj`/`.vbproj`/`.fsproj`, there's no meaningful update that can be performed, so we explicitly check for that.  This also means that we can't pull dependencies directly from `packages.config`, etc. because we still depend on the project file's contents, so the tests were updated to reflect that.  `global.json` and `dotnet-tools.json` are exceptions to requiring a project file and are still handled appropriately.
Update to smoke-tests
=====
This PR depends on a PR dependabot/smoke-tests#197 and they must be taken in parallel.
Temporary commit has been removed.  ~~**N.b.**, this PR has a temporary commit that points to the smoke-tests PR branch to show the smoke-tests passing.  That commit will need to be removed before this is merged.~~

only report dependencies from project files that have a target framework

---

nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb

Updates type signature to accommodate the possibility of a nil `package_version` argument in `NuspecFetcher::fetch_nuspec`.

`package_version` may be nil

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Update.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

When the C# tool is invoked to process updates, the repo's root is set as the working directory.  It's common practice for a repo to contain a `global.json` file that specifies the .NET SDK to use, but when the C# tool is launched, it picks up that `global.json` file and tries to use that SDK version when locating MSBuild and if the SDK version specified in the file doesn't match what's installed in the updater (or it's not upgradable via `"rollForward": "latestMinor"` or similar), then an exception is thrown.  The updater (currently) has SDK 8.0.202, but it's not uncommon for repos in the wild to use 3, 5, 6, or 7; this is what causes the failure.
The desired behavior is that the updater uses the version of MSBuild that's installed in the updater and to accomplish this, the user's …

don't allow `global.json` from repo to affect MSBuild discovery

---

common/lib/dependabot/clients/bitbucket_with_retries.rb
nuget/lib/dependabot/nuget/file_fetcher/import_paths_finder.rb
nuget/lib/dependabot/nuget/file_fetcher/sln_project_paths_finder.rb
nuget/lib/dependabot/nuget/file_parser/dotnet_tools_json_parser.rb
nuget/lib/dependabot/nuget/file_parser/global_json_parser.rb
nuget/lib/dependabot/nuget/file_parser/packages_config_parser.rb
nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb
nuget/lib/dependabot/nuget/file_parser/property_value_finder.rb
nuget/lib/dependabot/nuget/file_updater/property_value_updater.rb
terraform/lib/dependabot/terraform/version.rb
updater/lib/dependabot/dependency_group_engine.rb
updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/setup.rb

`require "sorbet-runtime"` is required to enable runtime checks. Found using the following:
```
grep --files-without-match "require \"sorbet-runtime\"" (grep --files-with-matches "# typed: strict" --include "*.rb" --recursive)
```

Add `require 'sorbet-runtime'` where missing

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/nuget_search_stubs.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb

Update `repository_finder.rb` to filter NuGet sources to those with a matching `packageSourceMapping` entry.  If no mapping is found, no filtering is performed which means the regular method of scanning all sources is preserved.
Fixes #9380

honor `packageSourceMapping` from `NuGet.Config`

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

When loading projects, we use the flag `IgnoreMissingImports` but if a project referencing the Aspire workload is loaded when that workload is not installed will fail because an attempt is made to load a generated project that isn't on disk.  The fix is to simply ensure all files exist.

don't fail loading build files that don't exist

---

silent/tests/testdata/su-group-default-rebase-multidir.txt
silent/tests/testdata/su-group-rebase-default.txt
silent/tests/testdata/su-group-type.txt
silent/tests/testdata/vu-group-all.txt
silent/tests/testdata/vu-group-exclude-patterns.txt
silent/tests/testdata/vu-group-incidental.txt

The grouped-update flag was never hooked up fully, we don't use it. Removing from the input of the tests to avoid confusion.

remove unused boolean from input of tests

---

common/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb
common/spec/dependabot/pull_request_creator/branch_namer/solo_strategy_spec.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb

- fixes https://github.com/dependabot/dependabot-core/issues/8565
In some ecosystems, an update to a dependency will result in a multi-dependency PR. In this case our BranchNamer appends all the dependency names to create the branch names. This is causing an excessively long branch names which are within the limits that GitHub allows but can break on Windows since it has a smaller file path limit.
This PR changes the BranchNamer naming strategy for multi-dependency PRs to generate a short digest. The branch names are going to be, for example `dependabot/nuget/multi-068ffedafd`, which is similar to what we use for grouped updates.
I opted to start the name with `multi` to differentiate from `grouped` branches just to make it easier to debug in the future, feel free to bikeshed 😄

fix really long branch names

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

If a package version is a property that can't be resolved, don't throw because it fails the entire update process.  Instead exclude that dependency.

only report dependencies whose version numbers can be resolved

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

example: https://github.com/dsp-testing/dependabot-gsu-multi-directory-tests/pull/19
The backend directory has >5 dependency updates so it should be a table
The frontend directory only has 3 updates so it should not be a table, and should not be inside of other table
The original code was attempting to add a table inside another table when there were 5 or more updates, regardless of the total number of updates in other directories. This made the /frontend updates appear nested incorrectly.
Solution: The fix separates the logic for handling 5 or more updates distinctly from cases with fewer updates. By ensuring that the condition for creating a table is only met for directories with 5 or more updates, we avoid unintended nesting or formatting issues for directories like /frontend with …

Table doesn't properly end for multi-directory GSU

---

updater/lib/dependabot/updater/group_update_creation.rb

In #8963 I made DependencySnapshot aware of multiple directories, so we can remove this TODO now.
This should speed up all grouped updates a small amount because it was re-parsing the files an extra time for each group.
Now we can simply do `dependency_snapshot.dependencies` which will return what DependencySnapshot parsed at the beginning of the job run.

remove redundant parsing of original files

---

updater/lib/dependabot/updater/group_update_creation.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb

We are seeing runtime exceptions due to comparing the semver components of two versions of a dependency when the components are not of the same type.
I considered two approaches:
1. Coerce the semver components of both versions to integers before comparing
2. Skip the comparison unless the semver components of both versions are of the same type
This is updater code so it's supposed to be ecosystem agnostic. Since each ecosystem brings its own version class (which inherits from `Gem::Version` and whose major/minor/patch components could be a number of different things), I opted to avoid making assumptions about the version instances. Instead, if two instances of an ecosystem's version class have major/minor/patch components of different types, we avoid the comparison altogether.

Prevent comparison of Integer with String in group update creation

---

common/lib/dependabot/dependency.rb

`Dependency#previous_requirements` may be nil, so handle nil case before passing to `T.must`, which may cause a runtime exception.
Closes #9325

Check for nil `Dependency#previous_requirements` before passing to `T.must`

---

updater/lib/dependabot/dependency_group_engine.rb

We need this behavior to stay synced with the behavior in the service.

Add a note about assumptions being made

---

common/lib/dependabot/pull_request_updater/github.rb
common/spec/dependabot/pull_request_updater/github_spec.rb
common/spec/fixtures/github/force_push_restricted_branch.json

When a force push is rejected from a [Repository Rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) the error that's returned is different, handle that case the same as other force push rejections.

Handle force push restrictions from repository rules

---

bundler/lib/dependabot/bundler/cached_lockfile_parser.rb
bundler/lib/dependabot/bundler/file_fetcher.rb
bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb

The bundler ecosystem repeatedly parsed the customer's lockfile during file fetching, file parsing, and file updating.
To speed things up I've introduced a cache which will return the pre-parsed lockfile.

bundler: avoid repeat lockfile parsing with caching

---

common/lib/dependabot/dependency.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

Fixes https://github.com/github/dependabot-updates/issues/5753
Explicitly state if dependency was removed in the dependency updates table for grouped updates

Explicitly state if dependency was removed in the dependency updates table for grouped updates

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

This PR resolves the issue of duplicated entries in the group update PR's summary table by ensuring that only unique dependencies are considered in the message builder. These are then displayed in the PR summary table.
Fixes: https://github.com/dependabot/dependabot-core/issues/7695

Fix Duplicate Dependencies Showing in PR summary table

---

go_modules/Dockerfile
go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb

In #8044 I said:
> Additionally, some customers have aggressive firewalls set on their Actions runners, and so it's not a great idea to have the Go tooling automatically download versions of the Go toolchain.
But I was overlooking that GHES customers don't run on the latest updater. They're often frozen on a slightly older version. So naturally when the next version of Go comes out and they update, Dependabot is broken for them and they have no recourse.
This puts back the auto-download behavior built into Go.

automatically download the latest Go when needed

---

bundler/lib/dependabot/bundler/file_parser.rb

This is a slight performance improvement that will help with grouped updates. 
I noticed in a flamegraph that `gemspec_dependencies` is called multiple times for each call of `parse`, so memoizing the call improves the performance.

bundler: avoid reparsing same gemspec

---

swift/Dockerfile

Hello there!
I have encountered an issue:
```sh
updater | 2024/04/09 06:19:14 ERROR <job_811965137> error: 'repo': package 'repo' is using Swift tools version 5.10.0 but the installed version is 5.9.0
```
I have found a similar one here:
- #8073
It looks like it's time to update the Swift version:
- https://github.com/apple/swift-org-website/blob/main/_data/builds/swift_releases.yml#L1674

Bump Swift version from 5.9 to 5.10

---

bundler/lib/dependabot/bundler/helpers.rb
bundler/spec/dependabot/bundler/helper_spec.rb

We rely on this information for metrics, not application logic. I believe we're receiving poor information and making decisions based on it. I'm updating this to see if we're indeed supporting as many Bundler v1 projects as it seems.

Update how we record Bundler versions

---

common/lib/dependabot/update_checkers/base.rb
common/spec/dependabot/update_checkers/base_spec.rb

We were previously using safe traversal to call `#to_s` on a nilable string, i.e., we were creating empty strings:
https://github.com/dependabot/dependabot-core/blob/a3dba8f6474160b2f4743a4b43385a735d58fcb9/common/lib/dependabot/update_checkers/base.rb#L227
This has been causing runtime exceptions because the `Dependency` initializer explicitly raises if either `version` or `previous_version` is an empty string.
Fixes #9430

Avoid passing empty strings as versions

---

common/lib/dependabot/pull_request_updater/github.rb

As a follow-up to #9439, I noticed a couple more exceptions around branch protection rules, which I've listed here.
I am not sure that adding a new test for each permutation of this error is of a lot of value, but open to feedback on this

Handle more branch protection errors

---

python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb

When the Python native requirement parser is unable to determine a `requirement_type`, we previously would include a `nil` value in the requirements group attribute, which in turn would cause our production check to determine that groups are present and no `default` or `install_requires` group is present, so this must be a dev dependency.
However, when no groups can be determined I think it's safer to assume all dependencies as production dependencies instead, as demonstrated by the test that I've updated, where the dependency in question is specified as such:
```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
[project]
name = "pkgtest"
authors = [{name = "Sample", email = "sample.project@example.org"}]
license = {file = "LICENSE"}
classifiers = …
```

Treat pep-621 deps as prod if no requirement_type is specified

---

common/lib/dependabot/git_commit_checker.rb
common/spec/dependabot/git_commit_checker_spec.rb
github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

If an Action is pinned to v3.5, and a v4 and v4.1.0 are released, Dependabot won't bump the Action.
This is because it tries to match the same precision. So v3.5 is precision 2, v4 is precision 1, v4.1.0 is precision 3.
It makes sense to not allow a v4 -> v4.1.0 bump because in the Action world, v4 and v4.1.0 SHOULD be pointed to the same commit.
However in the case above, v3.5 -> v4 does make sense, but we'd prefer a v4.X if available.
So this code will prefer a matching precision, but if one doesn't exist it will become less precise.

Actions: allow less precise semver updates

---

.github/workflows/smoke.yml

This branch doesn't exist so the smoke tests weren't running.

fix smoke tests not running

---

pub/helpers/build

We suddenly started getting pub image failures.
<details>
<summary>logs</summary>
```
#10 11.17 /opt/dart/pub-cache/git/pub-a42800e5a2f539dd5d86fdc3a6f3beefc971c753/lib/src/command/lish.dart:43:57: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
#10 11.17         return validateAndNormalizeHostedUrl(argResults.option('server'));
#10 11.17                                                         ^
#10 11.17 /opt/dart/pub-cache/git/pub-a42800e5a2f539dd5d86fdc3a6f3beefc971c753/lib/src/command/uploader.dart:26:42: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
#10 11.17   Uri get server => …
```

fix pub build not using lockfile

---

updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/spec/dependabot/update_files_command_spec.rb

The PR creation process requires gathering a significant amount of metadata which is IO heavy. Rather than wait for that to finish, we can pop that in a thread and continue on with the next updates. 
Testing locally against dependabot-core this lead to a 30% reduction in the job runtime, but it's very dependent on if there's a lot of PRs to create.
The major downside of this is that the logs become more difficult to read because the metadata gathering overlaps with the output for the next dependency, so I've put this behind an experiment and we can enable it on customers that are hitting the timeout.

asynchronously create PRs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/SdkPackageUpdaterHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/spec/dependabot/nuget/file_parser_spec.rb

Previously we'd manually parse each build file's XML and extract the `TargetFramework`, etc. properties.  This could lead to thinking a project supported a TFM when it really didn't.  The solution is to use the MSBuild-evaluated value as the project file is loaded.

use MSBuild-evaluated property values for TFM

---

.github/workflows/smoke.yml

In #9487 I missed a reference to a branch that has been deleted.

fix smoke test download failing

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Update.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackagesConfigUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DirsProj.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DotNetTools.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Mixed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs

Previously we had to temporarily displace a `global.json` file to allow MSBuild discovery to work.  This process would fail, however, if the updater tool was launched in a subdirectory and `global.json` was at the root.
The fix is to explicitly search for _all_ copies of `global.json`, starting from the current directory and progressing to the root and temporarily displace them.
Fixes #9249.

handle _all_ instances of `global.json` when initializing MSBuild
