dependabot/dependabot-core

common/lib/dependabot/clients/azure.rb
common/lib/dependabot/clients/codecommit.rb
common/lib/dependabot/metadata_finders/base.rb
common/lib/dependabot/pull_request_creator/bitbucket.rb
common/lib/dependabot/pull_request_creator/codecommit.rb
common/spec/fixtures/projects/simple/Gemfile
elm/lib/dependabot/elm/file_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/sub_dependency_files_filterer.rb

hh170424: Fixing the sorbet type errors.

---

Gemfile.lock
common/dependabot-common.gemspec
updater/Gemfile
updater/Gemfile.lock

This is currently giving Bundler a hard time when trying to create updates for updater. Since we already depended on Stackprof as a development dependency in dependabot-core, I've just upgraded that to be a runtime dependency and all should be good.

Ensure stackprof is only required once

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This came from a failed update seen in a log file.
The packages `SpecFlow` and `SpecFlow.Tools.MsBuild.Generation` are tightly intertwined with the latter having a hard dependency on the former and attempting to update just `SpecFlow` will result in package incoherencies.  The correct behavior would be to also pull the second package forward.
This is a nasty problem because we have to generate all possible update paths (e.g., the updated version of `SpecFlow` crossed with all updated versions of `SpecFlow.Tools.MsBuild.Generation` and any other packages that generated the same warning) and try them all by running through a call to `dotnet restore` to see if it generated any `NU1608` warnings.  A call to the full `restore` command is necessary because the reported package incompatibilities …

update all packages with dependencies on the target package when possible

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs

When updating in a `packages.config` scenario, the `.csproj` doesn't have to list the assembly version.  This modifies the check to allow either `Include="Some.Dependency"` _or_ `Include="Some.Dependency, Version=1.2.3.4, ...."`.

allow packages.config update when project file doesn't list assembly version

---

python/lib/dependabot/python/file_parser/python_requirement_parser.rb
python/spec/dependabot/python/file_parser/python_requirement_parser_spec.rb

Fixes #6650 
Adds functionality to ignore comments in .python-version file, fetches the minimum Python version and unit test it.

add functionality to ignore comments in .python-version file and fetch minimum Python version successfully

---

bundler/lib/dependabot/bundler/metadata_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb

I noticed that we're spending a lot of time making requests to rubygems, fair game, but I also noticed that we're requesting uncompressed JSON blobs, and JSON tends to compress relatively well. I'm seeing a modest performance improvement in local testing on a small-ish repo. Benchmarking network requests is always a little tricky, but I think it's fair to assume this certainly wouldn't hurt performance.
Excon is kind enough to handle the decompression for us.

Request gzip'ed responses from rubygems API

---

maven/lib/dependabot/maven/file_parser/property_value_finder.rb
maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb
maven/spec/fixtures/poms/property_pom_duplicate_tags.xml

Problem:
How to handle the Malformed expression?
Solution provided : 
As per the maven documentation, properties can contain any values. So if it is an expression then we should treat it as an expression and find the value of it, else we need to treat that as regular value.
Property value can accept
1. Expression ${exp}
2. Booleans
3. Version numbers in any format
4. Date Time formats and etc.
Ref : 
https://maven.apache.org/pom.html#Properties
https://maven.apache.org/guides/introduction/introduction-to-the-pom.html

Maven: Handle Malformed expressions or Invalid values present in properties section of the pom.xml file

---

python/lib/dependabot/python/file_updater/setup_file_sanitizer.rb
python/spec/dependabot/python/file_updater/setup_file_sanitizer_spec.rb

Fix #6387
Fetch the actual package name and replace hardcoded "sanitised-package" with the actual package name

Replace hardcoded "sanitized-package" with the actual package name

---

common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb

fixes #9457
This adds the stacktrace to the logs which allowed me to track down one of the other issues in #9457.
In job.json we started sending `updated-at` in the ignore conditions so it could be used for sorting, but here in the code it was used incorrectly as `updated_at`. 
Then later when types were applied, a `T.must` was added which always fails because neither `created_at` nor `created-at` are ever sent in the payload.
It would be best if `job.rb` immediately parsed the `job.json` into types and passed those around instead of hashes. That would help avoid this problem in the future.
From what I can tell, `updated-at` should always be sent, but I was a bit defensive and set the time to the epoch for any that don't have that field set.

fix ignore conditions nil error

---

.github/dependabot.yml

I noticed sorbet is getting into our dev-dependencies group: https://github.com/dependabot/dependabot-core/pull/9582
This is because there are other sorbet related projects like sorbet-runtime, rubocop-sorbet, etc.
So by capturing all of those in the sorbet group, it should be easier to bump together, then our dev-dependencies group is easier to merge.

prevent sorbet from bumping in dev-dependencies

---

nuget/lib/dependabot/nuget/discovery/discovery_json_reader.rb
nuget/lib/dependabot/nuget/file_parser.rb

The newly added `discover` command is only dependent on the `workspace_path` value, so use that as a cache key.
Previously, it was possible for the `discover` command to be run multiple times and in some large repos, that could lead to a timeout.  Also moved the reporting of the results of the `discover` command to just after it actually runs so it's not repeated in the log.

cache results of the discovery tool

---

.github/workflows/images-branch.yml

Local branch of https://github.com/dependabot/dependabot-core/pull/9547
An initial implementation of https://github.com/dependabot/dependabot-core/issues/9546 for branch images
cc/ @JamieMagee

Sign branch images with cosign

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml

Adding ignore helpet test fixtures to both code QL and dependency review jobs.

Ignoring the fixture files in workflow (dependency review and code QL) runs

---

common/lib/dependabot/metadata_finders/base/changelog_finder.rb
common/spec/dependabot/metadata_finders/base/changelog_finder_spec.rb

fixes #9565
The method `changelog_from_suggested_url` is trying to get a listing of the files so it can return them and get the `html_url`, so `tmp_files` should always be an array.
The reason it wasn't is because `suggested_changelog_url` had a [fragment](https://en.wikipedia.org/wiki/URI_fragment) (e.g. `#v2.8.6`) which the `Source.from_url` doesn't handle, so we end up grabbing the file itself rather than the directory listing. 
By stripping the fragment we get the listing which fixes the problem.
This is all a bit strange. It's weird we're using `Source.from_url` when we could use `URI` to parse. Also if we have the URL to the changelog it seems like we could transform the URL into the HTML URL without making a network call.
But for now I'll put this fix in and slowly back away...

fix fragment in suggested_changelog_url causing exceptions

---

nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Packaging/NuGet.Packaging.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Packaging/PackageFolderReader.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackagesConfigUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/SdkPackageUpdaterHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs

Some packages (e.g., `jQuery`) don't contain assemblies, but if they're in a `packages.config` scenario, that can pose 2 issues with updating.
1. We can't determine the local packages directory.
2. The update process will fail unless `restore` has been run first.
To correct the first issue, we fall back to a relative packages path of `../packages` which is by far the most common value used.  Since the given package has no assemblies, this fall back value won't be written back to the `.csproj`; it's just temporary.
To correct the second issue it was just a case of expanding our detection logic of when we need to run `restore` before retrying `update`.
Part of this fix uncovered an issue where NuGet package are sometimes checked for a `content` directory with a case-sensitive search.  The …

allow updating package without assemblies from `packages.config`

---

python/Dockerfile
python/lib/dependabot/python/language_version_manager.rb

Currently when I use dependabot with python 3.12.3 it says:
```py
Dependabot detected the following Python requirement for your project: '^3.12.3'.
Currently, the following Python versions are supported in Dependabot: 3.12.*, 3.11.*, 3.10.*, 3.9.*, 3.8.*.
```
This enables dependabot for python 3.12.3 and 3.11.9

chore(python): target latest python versions 3.12.3, 3.11.9

---

script/_common

This change enabled [Docker content trust][1] which verifies the signatures of container images used by docker. This is only done for the base image, which is built on top of Ubuntu.
The signature can be manually verified as follows:
```bash
$ docker trust inspect --pretty docker.io/library/ubuntu:22.04
Signatures for docker.io/library/ubuntu:22.04
SIGNED TAG   DIGEST                                                             SIGNERS
22.04        6d7b5d3317a71adb5e175640150e44b8b9a9401a7dd394f44840626aff9fa94d   (Repo Admin)
Administrative keys for docker.io/library/ubuntu:22.04
Repository Key:       8273733f491f362bb36710fd8a99f78c3fbaecd8d09333985c76f1064b80760f
Root Key:     1f9bc7ae6335ae41ee03e983c0e31303901be567b4cdb3fc7c7363f0591128ff
```
Why are we using Docker content trust to …

Enable Docker content trust

---

bundler/helpers/v1/monkey_patches/definition_ruby_version_patch.rb

These were omitted in a previous pull request. I'm unsure if Bundler v1 needs them, so I'm defaulting to making sure they're present.
The patch levels were determined by installing Ruby locally.

Specify patch levels for previous Rubies

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Discover.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

* Fixes https://github.com/dependabot/dependabot-core/issues/9612 and https://github.com/dependabot/dependabot-core/issues/9495
`NuGetUpdater.Cli.exe discover` was throwing "An item with teh same key has already been added" in the situation where a centrally-managed Directory.Build.props file would have 2 references for the same package based on a condition such as the repository using central package management.
This is an example that would make the tool throw from my company's centrally-managed [Directory.Build.props file](https://github.com/Particular/RepoStandards/blob/master/src/Directory.Build.props):
```xml
<ItemGroup Condition="'$(ManagePackageVersionsCentrally)' == 'true'">
<GlobalPackageReference Include="Particular.Analyzers" Version="$(ParticularAnalyzersVersion)" /> …
```

Allow NuGet dependencies to exist with duplicate names but different dependency types

---

updater/bin/fetch_files.rb
updater/bin/update_files.rb

We primarily upgraded to Ruby 3.3 so that we could enable YJIT. We did this in order to hopefully mitigate some of the performance issues some of our larger customers have faced.
This change enables YJIT for _some_ update jobs. The reason for the incremental enablement is that we would like to measure the impact that YJIT has before adopting it fully (which we intend to do).

Enable YJIT for even-numbered update jobs

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/9_0_format/pnpm-lock.yaml

Related: https://github.com/dependabot/dependabot-core/issues/9522

Use pnpm@9 for lockfile >= 9.0

---

common/lib/dependabot/metadata_finders/base/changelog_finder.rb
common/lib/dependabot/metadata_finders/base/commits_finder.rb
common/lib/dependabot/metadata_finders/base/release_finder.rb
common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb
silent/lib/dependabot/silent.rb
silent/lib/dependabot/silent/metadata_finder.rb

In #9560 we started revealing the exceptions that were being thrown in the metadata finders.
This caused the "silent" integration test output to be full of exceptions making it difficult to see what was going on in the test.
This implements the minimum amount to prevent exceptions in the logs of the integration tests.

fix exceptions from integration tests due to no metadata finders

---

.rubocop_todo.yml
elm/spec/dependabot/elm/update_checker/requirements_updater_spec.rb
npm_and_yarn/spec/npm_and_yarn_config_spec.rb

https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecdescribeclass

Enable RSpec/DescribeClass

---

.github/workflows/ci.yml

Recommended as part of [GitHub's own GitHub Actions security hardening guide][1] and [the OSSF Scorecards checks][2]
> **Pin actions to a full length commit SHA**
>
> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. When selecting a SHA, you should verify it is from the action's repository and not a repository fork.
[1]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
[2]: https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

Pin actions in CI workflow to commit SHA

---

nuget/helpers/lib/NuGetUpdater/Directory.Packages.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Discover.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Update.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.DotNetToolsJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/MockNuGetPackage.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/NuGetUpdater.Core.Test.csproj
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DirsProj.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DotNetTools.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Mixed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs
nuget/helpers/lib/NuGetUpdater/global.json

Comments have been added inline with the code where the most attention should be paid.
In short, if a unit test is written as it was before, the behavior will remain the same; network access to `api.nuget.org` will be allowed.  _However_, as soon as the `packages` parameter is specified, a test-only `NuGet.Config` is written to the test directory which disallows **all** network access and only allows the packages created in a special directory to be queried.  Since we don't use any custom NuGet API handling, this is perfectly fine as we're letting the "real" NuGet handle its sources however it sees fit (which in this case is all from a local feed.)
The vast majority of this PR was changing things like `Newtonsoft.Json` to `Some.Package` and can be ignored.  In some tests the specific …

restrict C# nuget unit tests to local package feeds

---

cargo/lib/dependabot/cargo/metadata_finder.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
cargo/spec/dependabot/cargo/update_checker/latest_version_finder_spec.rb
cargo/spec/fixtures/private_registry_responses/hello-world.json
cargo/spec/fixtures/private_registry_responses/not_found.json

The Cargo implementation for private registries should support the sparse index file format. In sparse registries, the response consists of multiple JSON objects instead of a single JSON object when checking available versions. This PR addresses and handles that response format.
Fixes: https://github.com/dependabot/dependabot-core/issues/9764

Cargo implementation must support Cargo sparse index file format

---

silent/README.md

[rendered](https://github.com/dependabot/dependabot-core/blob/0401501a7fc2c264eaf6f8b3043eb5b0b2311d52/silent/README.md)
This adds a README to the silent ecosystem directory which explains why it exists, how to read the tests, and how to run them. 
Let me know if I've missed anything.

adding documentation to the silent ecosystem

---

.codespellrc
bundler/spec/dependabot/bundler/file_fetcher/path_gemspec_finder_spec.rb
bundler/spec/dependabot/bundler/file_fetcher/require_relative_finder_spec.rb
bundler/spec/dependabot/bundler/file_fetcher_spec.rb
python/spec/dependabot/python/file_updater/pip_compile_file_updater_spec.rb

This PR is to address the review comments provided in https://github.com/dependabot/dependabot-core/pull/9758

Harry/text improvement, context wording, for ecosystem bundler, review comments of #9758 addressed here.

---

bundler/helpers/v2/monkey_patches/bundler_spec_set_patch.rb
bundler/helpers/v2/monkey_patches/definition_bundler_spec_set_patch.rb
bundler/helpers/v2/run.rb
bundler/helpers/v2/spec/definition_bundler_spec_set_patch_spec.rb
bundler/helpers/v2/spec/native_spec_helper.rb

**Context** : https://github.com/dependabot/dependabot-core/issues/9781
"To solve lazy specification error, we need to update rubygem in Dependabot core with the release having the fix in the below comment. But before we do that, we also need to make few changes into Dependabot core to support the release as Dependabot relies on the @unlock[:gems] value in Bundler::Definition, which is now removed at initialize time
More detailed context: https://github.com/rubygems/rubygems/pull/7659#issuecomment-2114690972
This task will unblock the cargo private registry support for GA"
**Fix applied:**  Applied monkey patch on Bundler::materialize_for_installation

Monkey patch on Bundler::materialize_for_installation for resolve Bundler::LazySpecification issue

---

nuget/lib/dependabot/nuget/update_checker.rb
nuget/lib/dependabot/nuget/update_checker/dependency_finder.rb
nuget/lib/dependabot/nuget/update_checker/property_updater.rb
nuget/lib/dependabot/nuget/update_checker/version_finder.rb
nuget/spec/dependabot/nuget/update_checker/dependency_finder_spec.rb
nuget/spec/dependabot/nuget/update_checker/version_finder_spec.rb

The current handling of `ignored_versions` in a `job.yml` file is incorrect.  Consider an example from the unit tests; a `job.yml` could list that for a certain package, `ignored_versions` should be `< 1.1.1, > 1.1.1` which should be read as "ignore anything below 1.1.1 and ignore anything above 1.1.1" which boils down to "only accept version 1.1.1".  The previous implementation did a slightly different thing of "negate (version is less than 1.1.1 AND version is greater than 1.1.1)" which is impossible; this was a wrong application of our good friend [De Morgan](https://en.wikipedia.org/wiki/De_Morgan%27s_laws).
The proper fix here is to turn that check into "negate (version is less than 1.1.1 OR version is greater than 1.1.1)".  Thankfully the Maven updater does the correct thing so I …

fix nuget ignored package version handling

---

nuget/Dockerfile
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TemporaryDirectory.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/helpers/lib/NuGetUpdater/global.json

The behavior around handling `Directory.Packages.props` has subtly changed in the `*.300` SDK which meant for unit tests, an empty `Directory.Build.props` had to be written and in other cases writing an empty `Directory.Packages.props` wasn't the correct thing to do any more.
More details about the difference with handling `Directory.Packages.props` can be found at NuGet/Home#13453.

update to 8.0.300 SDK

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb

This, alongside #9800, fixes all the remaining type errors in the `npm_and_yarn` ecosystem.
Once both of these are merged I can add
```yml
Sorbet/TrueSigil:
Enabled: true
```
to `.rubocop.yml`.

True type remainder of `npm_and_yarn`

---

cargo/lib/dependabot/cargo/helpers.rb

The Cargo private registry is working with CLI + Core but failing with Dependabot API + Core
The issue arises because the cargo_registry key is missing in one of the entries in the Dependabot API, which results in a nil value when accessed in the core code, leading to the error mentioned earlier. 
Fix:
To fix the issue adding a new cargo private registry key, in the `.dependabot.yml file` as an additional parameter: `cargo_registry: registry name` and changes in this PR uses that key.

Replace cargo registry keyword from the credentials to use new keyword registry

---

npm_and_yarn/.rubocop.yml

With #9800 and #9827, all of the `npm_and_yarn` ecosystem is now `# typed: true` with Sorbet. This change enforces this requirement with RuboCop to prevent regressions in type safety.

Enforce `true` sigil in `npm_and_yarn` ecosystem

---

.github/workflows/sorbet.yml

Our [spoom GitHub Actions workflow][1] is currently printing a warning for this step
```
Warning: This command is deprecated. Please use spoom srb bump instead.
```
This change migrates us from using `spoom bump` to `spoom srb bump`.
[1]: https://github.com/dependabot/dependabot-core/actions/workflows/sorbet.yml

Use non-deprecated `spoom srb bump` command

---

gradle/spec/dependabot/gradle/file_fetcher/settings_file_parser_spec.rb
gradle/spec/dependabot/gradle/file_fetcher_spec.rb
gradle/spec/dependabot/gradle/file_parser/property_value_finder_spec.rb
gradle/spec/dependabot/gradle/file_parser/repositories_finder_spec.rb
gradle/spec/dependabot/gradle/file_parser_spec.rb
gradle/spec/dependabot/gradle/file_updater_spec.rb
gradle/spec/dependabot/gradle/metadata_finder_spec.rb
gradle/spec/dependabot/gradle/requirement_spec.rb
gradle/spec/dependabot/gradle/update_checker/requirements_updater_spec.rb
gradle/spec/dependabot/gradle/update_checker/version_finder_spec.rb
gradle/spec/dependabot/gradle/update_checker_spec.rb
gradle/spec/dependabot/gradle/version_spec.rb

Test Improvements, Context Wording, For the ecosystem: Gradle
Please ensure the context wordings are meaningful and sensible.
Ran Lint and Test against the respective ecosystem.

TICtxtWrd-grdl: Test Improvements, Context Wording, For the ecosystem: Gradle

---

updater/lib/dependabot/service.rb
updater/spec/dependabot/service_spec.rb

The PullRequestCreator refuses to create PRs when either the `previous_version` is absent or the `previous_requirements` reveal there were no changes to a dependency.
That code is here: https://github.com/dependabot/dependabot-core/blob/75b48123458652e6572c1ac6ab0934b63412f371/common/lib/dependabot/pull_request_creator.rb#L224-L231
This results in what looks like successful runs ending with a PR not being created. 
To improve this, we need to move the validation check closer to where the issue is. In this PR, I added behind an experiment the same check right before sending the PR data to the client.
This will give us, and customers, more information about the nature of the problem, since it will tell us which dependency is failing and why. Then we can target which ecosystems need help and …

fail sooner when PR creation data is incomplete

---

github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/spec/dependabot/github_actions/file_updater_spec.rb
github_actions/spec/fixtures/workflow_files/same_name_ending.yml

Prevent the case where one action has the name of another with a prefix followed by a - (hyphen). For instance, julia-actions/cache and actions/cache.
This is done by updating the regex that matches the action names. `\W` used before does not match `-`, so I changed to the explicit `[^a-zA-Z_-]`.
I have also created a test and a fixture to use in the test.
Fix #9885
The new test should capture the use case presented in #9885. I tested it before and after the fix, so it does appear to be testing what I propose.

Prevent github actions with same name ending after hyphen to be updated

---

.github/workflows/sorbet.yml
script/generate-coverage-report

Fix the spoom coverage report generation.
It hasn't been generating a new report since 24th April due to the command we were using being deprecated.
Related to #9876 
The deprecation warning is gone and the report is being generated again.

Migrate to new `spoom srb coverage` command

---

bundler/lib/dependabot/bundler/metadata_finder.rb

True type `Dependabot::Bundler::MetadataFinder`

---

.rubocop_todo.yml
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb

https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecvoidexpect

Enabling RSpec/VoidExpect

---

.rubocop_todo.yml
hex/spec/dependabot/hex/update_checker/version_resolver_spec.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
updater/spec/dependabot/file_fetcher_command_spec.rb

The Rubocop rule to check for MetadataStyle was excluded on several files.  This PR will re-enable that issue.
Please be on alert for multiple lines doing the same thing.
The rubocop rule will be enforced on the entire application.

Enabled Rubocop rule for the MetadataStyle test

---

common/lib/dependabot/dependency.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/service_spec.rb

In https://github.com/dependabot/dependabot-core/pull/9888 I moved the failure out of the service and into the Updater.
In this PR, I prevent the failure by removing the questionable update, and logging to tell us what's happening.
It seems there are various reasons why an update with no previous version will happen, but rather than failing the job or a group, we should log it and continue on.
We should stop seeing the error being reported.

don't fail when a dependency doesn't have a previous version

---

go_modules/lib/dependabot/go_modules/metadata_finder.rb

Sorbet Implementation for go_modules MetaDataFinder ruby file.
Please pay attention to the fixes in the go_modules MetaDataFinder ruby file.
**Checklist**

Strict type `Dependabot::GoModules::MetaDataFinder`

---

.rubocop_todo.yml
pub/spec/dependabot/pub/update_checker_spec.rb
pub/spec/spec_helper.rb
updater/spec/dependabot/service_spec.rb

The RSpec rubocop rule [SharedExamples](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/SharedExamples) had been blocked from running on several fies.  This PR corrects that issue
This PR shoud just change a few names of shared examples in two or three rspec files.  Since these were included in other files, the other files had to be run against it.
The tests will run effectively without any change in performance.

Enabling SharedExamples Rubocop rule

---

composer/helpers/v2/src/UpdateChecker.php
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb

Problem: Depnedabot ignoring the minor patch filter. And creating minor patch update PRs
Solution: Checking latest available version is compatible with given composer.json only then raise PR. 
Some previous test cases are modified, Specially some of the expected raise an error, now it's not as there is no need of updating dependency.
Current Implementation will only do the update if the latest available version in the registry is compatible with composer.json. 
Ran cli in local an ensured no PR generated for minior patch updates.

5800-sev-3-dependabot-not-respecting-ignore-minorpatch-updates: Updating to the latest available in the registry.

---

hex/lib/dependabot/hex/file_updater.rb
hex/lib/dependabot/hex/native_helpers.rb

Sorbet Implementation for Hex FileUpdater and NativeHelpers ruby file.
Please pay attention to the fixes in the Hex FileUpdater and NativeHelpers ruby file.

Strict type `Dependabot::Hex::FileUpdater::NativeHelpers`

---

hex/lib/dependabot/hex/file_updater/mixfile_git_pin_updater.rb

Sorbet Implementation for Hex MixFileGitPinUpdater ruby file.
Please pay attention to the fixes in the Hex MixFileGitPinUpdater ruby file.

Strict type `Dependabot::Hex::MixFileGitPinUpdater`

---

common/lib/dependabot/dependency.rb
common/spec/dependabot/dependency_spec.rb

This is a concept which has been deemed to be missing. The effect of this is that when a pull request exists for a group, without there being knowledge of a directory, individual pull requests are then created. By adding `#directory` to Dependabot::Dependency, we'll be able to prevent this.
We'll need to start setting `#directory` in future changes. By leaving it in its current state, it will be available to the updater (for said future changes), and to consumers of the library.
While this change adds an `attr_accessor`, `#directory` is not being written or read anywhere yet.

Add `#directory` to Dependabot::Dependency

---

.rubocop_todo.yml
common/spec/dependabot/dependency_file_spec.rb
common/spec/dependabot/dependency_group_spec.rb
common/spec/dependabot/experiments_spec.rb
common/spec/dependabot/file_updaters/artifact_updater_spec.rb
common/spec/dependabot/file_updaters/vendor_updater_spec.rb
common/spec/dependabot/workspace/git_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
pub/spec/dependabot/pub/update_checker_spec.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
updater/spec/dependabot/job_spec.rb

The Predicate Matcher rubocop rule is disabled for some files.  This Pull request will re-enable it.
Please review for duplicated code blocks which escaped the autocorrect.  This is a rework of PR #9910 9910, which had more merge conflicts than were fixable.
This rubocop rule will work as desired

Enabling PredicateMatcher Rubocop rule on RSpec.

---

.rubocop_todo.yml
bundler/spec/dependabot/bundler/file_fetcher_spec.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb
common/spec/dependabot/clients/bitbucket_spec.rb
common/spec/dependabot/git_commit_checker_spec.rb
common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb
docker/spec/dependabot/docker/file_parser_spec.rb
elm/spec/dependabot/elm/file_fetcher_spec.rb
go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
gradle/spec/dependabot/gradle/update_checker/multi_dependency_updater_spec.rb
hex/spec/dependabot/hex/file_fetcher_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/metadata_finder_spec.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
python/spec/dependabot/python/file_fetcher_spec.rb

https://www.rubydoc.info/gems/rubocop-rspec/1.10.0/RuboCop/Cop/RSpec/ScatteredSetup
The ScatteredSetup Rubocop rule has been disabled for some tests.  This PR enables the rule for all of the ecosystem
Autocorrect may create some funky syntax.  Please be alert for such changes.
The setup for the tests should be much cleaner.

Enabling ScatteredSetup Rubocop rule

---

hex/lib/dependabot/hex/file_parser.rb

Sorbet Implementation for Hex FileParser ruby file.
Please pay attention to the fixes in the Hex FileParser ruby file.

Strict type `Dependabot::Hex::FileParser`

---

docker/lib/dependabot/docker/requirement.rb
docker/spec/dependabot/docker/requirement_spec.rb

The signature takes a splatted argument, but it's been typed as a String. I'm updating this so that it is compatible with current uses of Docker Requirement in the service 👇 
```plaintext
TypeError:Parameter 'requirements': Expected type String, got type Array with value [">= 2.0.20230809182251.a", "< 2.0.20230809182252"]
Caller: /home/dependabot/.local/share/gem/ruby/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:133
Definition: /home/dependabot/.local/share/gem/ruby/gems/dependabot-docker-0.261.0/lib/dependabot/docker/requirement.rb:31 (Dependabot::Docker::Requirement#initialize)
```
No, but I do see that `Requirement.requirement_string` accepts a `T.nilable(String)` and immediately uses `T.must(requirement_string)`. This does not seem to be intentional, but …

Fix Docker Requirement initializer type

---

bundler/lib/dependabot/bundler/file_fetcher/require_relative_finder.rb

Sorbet Implementation for Bundler RequireRelativeFinder ruby file.
Please pay attention to the fixes in the Bundler RequireRelativeFinder ruby file.

Strict type `Dependabot::Bundler::RequireRelativeFinder`

---

updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/dependency_change_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh.yaml

Currently, when Dependabot attempts to do a multi-directory update, it doesn't consider the directory of the dependencies in existing pull requests. This results in ungrouped pull requests being created for the dependencies which are already in a grouped pull request. By considering the directory of existing dependencies, we can avoid this issue.
I've created a (private) repository which is impacted by the existing behavior. Once this pull request is merged, I'll re-run Dependabot on that repository and confirm that the grouped updates are correctly grouped and single-dependency pull requests are not created.

Include `directory` when serializing dependencies

---

.rubocop_todo.yml
common/spec/dependabot/metadata_finders/base/commits_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/requirement_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/dependency_files_builder_spec.rb

The NamedSubject Rubocop rule was accidentally disabled after work had been completed on it.  This will re-enable that cop for main so that we can avoid the rebasing issues we have come across
This change is merely putting a named subject in for the generic 'subject' designator.
Resetting branches to main will include this rule in the enabled ruleset.

Re-enabled NamedSubject RSpec rule which was accidentlaly overwritten

---

go_modules/lib/dependabot/go_modules/version.rb
go_modules/spec/dependabot/go_modules/version_spec.rb

The `@prerelease` component should include everything after the `-`, not only the initial split. Otherwise, comparing prereleases with multiple `-` does not work.
Fixes #10020.

Fix Go modules prerelease

---

updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/updater/dependency_group_change_batch.rb
updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/spec/dependabot/updater/dependency_group_change_batch_spec.rb

Requires https://github.com/dependabot/dependabot-core/pull/9982
Now that a `Dependabot::Dependency` can have a directory, we should use it to track which dependencies are updated in each `updated_dependency_file` in a `DependencyGroupChangeBatch`. This will allow us to keep track of every dependency update across every file.
A `DependencyGroupChangeBatch` is used to hold and consolidate the `DependencyChanges` when [updating a group](https://github.com/dependabot/dependabot-core/blob/main/updater/lib/dependabot/updater/group_update_creation.rb#L50). For a multi-directory PR, the `DependencyGroupChangeBatch` represents updating a group across every directory. 
Prior to this change, the `DependencyGroupChangeBatch` would overwrite the `updated_dependencies` from the previous directory. …

DependencyGroupChangeBatch tracks updated dependencies per file

---

.rubocop.yml
.rubocop_todo.yml

https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecindexedlet
<h2 id="rspecindexedlet" style="box-sizing: inherit; scrollbar-width: thin; scrollbar-color: rgb(193, 193, 193) transparent; color: rgb(25, 25, 25); font-weight: 400; hyphens: none; line-height: 1.3; margin: 1rem -1rem 0px; border-bottom: 1px solid rgb(225, 225, 225); padding: 0.4rem 1rem 0.1rem; font-family: Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: …

Disabling the RSpec IndexedLet Rubocop rule due to its negligible benefit

---

.rubocop_todo.yml
nuget/spec/dependabot/nuget/update_checker/dependency_finder_spec.rb
pub/spec/dependabot/pub/file_updater_spec.rb
pub/spec/dependabot/pub/infer_sdk_versions_spec.rb
pub/spec/dependabot/pub/update_checker_spec.rb

https://www.rubydoc.info/gems/rubocop-rspec/1.15.0/RuboCop/Cop/RSpec/BeforeAfterAll
What are you trying to accomplish?
The BeforeAfterAll RSpec rule was disabled in some parts of the ecosystme. This PR will enable and fix those scenarios it identifies.
Anything you want to highlight for special attention from reviewers?
Please watch for code duplications or conflicts.
How will you know you've accomplished your goal?
The Rubocop rule will work and the tests will not fai afterwards.
Checklist
I have run the complete test suite to ensure all tests and linters pass.
I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
I have written clear and descriptive commit messages.
I have provided a detailed description of the …

Enabling RSpec/BeforeAfterAll Rubocop rule

---

updater/Gemfile.lock

Warnings due to using old httparty were partially fixed by https://github.com/dependabot/dependabot-core/pull/9770.
However, you still get runtime warnings like the following:
```
updater | /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.
```
because the update was not applied to `updater/` folder.
This PR also updates the dependency in updater/Gemfile.lock.
Follow up to #9770 and #9873.

Upgrade httparty to 0.22.0

---

common/lib/dependabot/errors.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/private_registry_no_config/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/private_registry_no_config/pnpm-lock.yaml

Fixes following sentry issue : 
```
NoMethodError: undefined method `requirements' for nil:NilClass
sources = dependency.requirements
^^^^^^^^^^^^^
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:298:in `registry_source_url'
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:137:in `locked_registry'
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:34:in `registry'
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:130:in `raise_package_access_error'
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb:108:in `block in handle_pnpm_lock_updater_error'
...
(48 additional frame(s) were not displayed)
```
**Preface :**  Dependencies are listed in public as well as …

Added private repo access error catch and missing repo error capture

---

Dockerfile.updater-core

This is a fresh copy of https://github.com/dependabot/dependabot-core/pull/9979, as requested in https://github.com/dependabot/dependabot-core/pull/9979#issuecomment-2187693088.
Even if Bundler is tested against multiple versions of RubyGems, it's best if both are upgraded together.
Also, upgrading RubyGems installs an upgraded copy of Bundler as a default gem, so I believe it's unnecessary to install Bundler explicitly. It should result in a slightly thinner image.
No.
Everything still works smoothly in production after deploying this.

Make it easier to upgrade Bundler & RubyGems in sync (take 2)

---

common/lib/dependabot/shared_helpers.rb
npm_and_yarn/Dockerfile
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private/pnpm-lock.yaml
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private_v8/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private_v8/pnpm-lock.yaml

This is required so that Dependabot works for people using PNPM 9 and not specifying `packageManager` in their `package.json` files.
If `packageManager` is not specified, Dependabot currently uses PNPM 8. When PNPM 8 finds "PNPM 9 lockfiles", it prints a warning like this:
```
 WARN  Ignoring broken lockfile at /home/dependabot/tmp/wJoenn/vue-template: Lockfile /home/dependabot/tmp/wJoenn/vue-template/pnpm-lock.yaml not compatible with current pnpm
```
So it ignores the lockfile and creates a new one from scratch using its own format (lockfileVersion 6), causing the problem reported in https://github.com/dependabot/dependabot-core/issues/9684.
The problem can be reproduced in a dev shell with
```
$ bin/dry-run.rb npm_and_yarn wJoenn/vue-template --commit …
```

Bump default PNPM to 9.4.0

---

composer/helpers/v2/src/UpdateChecker.php
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb

Reverts dependabot/dependabot-core#10018
Based on the comment provided on the https://github.com/dependabot/dependabot-core/pull/10018 I have decided to revert this changes.
Once we resolve all the related issue we will enable this changes again.

Revert "Passing the latest allowable version as package constraints"

---

python/lib/dependabot/python/requirement.rb
python/lib/dependabot/python/update_checker/requirements_updater.rb
python/spec/dependabot/python/requirement_spec.rb
python/spec/dependabot/python/update_checker/requirements_updater_spec.rb

The goal of this PR is to correct the behavior of the versioning strategy in Dependabot for Python dependencies. Specifically, when using the "increase" strategy.
**Why:** The current behavior was widening the range (e.g., from `>=8,<9` to `>=8,<10`), which is not the intended behavior. Instead, it should keep lower bound version as the new latest version and just move forward the upper boundary version (e.g., from `>=8,<9` to `>=9,<10`) as mentioned [Documentation for Versioning Strategies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy)
**Issues this affects or fixes:** 
- Addresses the issue reported in #6631.
- First noticed at #6625 (comment).
The changes involve modifying the …

Update lower boundary in Python pip pyproject when bumping versions #6631

---

nuget/lib/dependabot/nuget/file_updater.rb

Fix Dependabot::Nuget::FileUpdater file content normalization (line-endings) as the current logic replaces CRLF line-endings of source file with LF.
Related to #8642

Fix Dependabot::Nuget::FileUpdater file content normalization

---

common/lib/dependabot/errors.rb
updater/lib/dependabot/service.rb
updater/spec/dependabot/file_fetcher_command_spec.rb
updater/spec/dependabot/service_spec.rb

**Preface:** When there is Security update related exception in NPM and YARN ecosystem, the error response is generic ("No files were updated!") which is not very useful in Sentry analysis. The fix adds a new tag to Sentry to better isolate the issues related with Security Update failures.
**Fix:** Include "security-update" tag with :dependabot: jobs. tag will assert to true if job is of type security update and false if regular update. 
Process to fix https://github.com/github/dependabot-updates/issues/6133 issues related with NPM and Yarn package manager. The change is to isolate security updates from regular updates so that these issues can be analyzed in a separate bucket for fixes.
This fix was followed up after discussion here: …

Including Sentry meta tag for security updates

---

go_modules/.rubocop.yml
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/lib/dependabot/go_modules/metadata_finder.rb
go_modules/lib/dependabot/go_modules/native_helpers.rb
go_modules/lib/dependabot/go_modules/path_converter.rb
go_modules/lib/dependabot/go_modules/resolvability_errors.rb
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
go_modules/lib/dependabot/go_modules/version.rb

Complete strict sorbet typing `go_modules`
Also enabled `Sorbet/StrictSigil` to prevent regressions
Tests pass

Strict type `go_modules`

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This fixes an issue discovered during internal log scanning.  A `NuGet.Config` file with local package sources using Windows-style directory separators aren't handled correctly in the discovery phase when running in a Linux container.  The fix is to normalize to Unix-style directory separators.

allow all directory separators for local package feeds

---

terraform/Dockerfile

https://github.com/hashicorp/terraform/releases/tag/v1.9.0
https://releases.hashicorp.com/terraform/1.9.0/

build(deps): bump terraform from 1.8.0 to 1.9.0

---

gradle/lib/dependabot/gradle/file_updater.rb
gradle/spec/dependabot/gradle/file_updater_spec.rb

Fixes following issue:
`NoMethodError: undefined method 'content' for nil:NilClass`
```
original_content = buildfile.content.dup
^^^^^^^^
gradle/lib/dependabot/gradle/file_updater.rb:116:in `update_version_in_buildfile'
gradle/lib/dependabot/gradle/file_updater.rb:74:in `block in update_buildfiles_for_dependency'
gradle/lib/dependabot/gradle/file_updater.rb:62:in `each'
gradle/lib/dependabot/gradle/file_updater.rb:62:in `update_buildfiles_for_dependency'
gradle/lib/dependabot/gradle/file_updater.rb:28:in `block in updated_dependency_files'
...
(27 additional frame(s) were not displayed)
```
**Preface:** 
When managing a large project with several sub-modules, user can work with different configurations. user can create a single repo with all the submodules as part of single project. In …

Adds exception to handle nil buildfile issue

---

hex/lib/dependabot/hex/file_fetcher.rb

Remove a redundant call to `fetch_file_from_host` in `mixfile`. This was called out in the original review by @landongrindheim, but never addressed[^1]. Thank you @jeffwidman for pointing this out.
N/A
Sorbet checks and tests pass.
[^1]: https://github.com/dependabot/dependabot-core/pull/9990/files#r1648045378

Remove redundant call from `mixfile`

---

common/lib/dependabot/git_commit_checker.rb
common/lib/dependabot/update_checkers/base.rb
github_actions/.rubocop.yml
github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/update_checker_spec.rb

Complete Sorbet strict typing of `github_action` and enable `Sorbet/StrictSigil` RuboCop check.
A couple of minor changes required outside of the `github_actions` directory:
- `Dependabot::UpdateCheckers::Base.lowest_security_fix_version` return type changed from `Dependabot::Version` to `T.nilable(Dependabot::Version)`
- This makes sense, as not all updates will have a security fix version
- Removed `nil` return values from a couple of methods in `Dependabot::GitCommitChecker` by using `filter_map` instead of just `filter`
- `nil` array values aren't used, and it makes types in callers simpler
Also, I fixed what I believe to be an incorrect test mock. A string value was being returned where a `Dependabot::Version` was expected. See #9342 for more information about incorrect types in …

Strict type `github_actions`

---

common/lib/dependabot/update_checkers/base.rb
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb

Fix the "Passed `nil` into T.must" error that occurs when `nil` is passed into a method that expects a non-`nil` value. This is the same issue identified in #10156 
N/A
Tests pass and error stops

Fix "Passed `nil` into T.must" error

---

common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/shared_helpers_spec.rb

This PR aims to enhance the `run_helper_subprocess` method by making the `HelperSubprocessFailed` error class configurable. This change allows callers to specify a custom error class that extends `HelperSubprocessFailed`, enabling better categorization of errors based on the package manager or other context. This will help to categorize error classes between ecosystems, improving error debugging when using tools like console, Sentry, or other monitoring tools.
This update addresses the need for more granular error handling and categorization in subprocess executions, improving error transparency and debugging efficiency across different package managers.
The new functionality introduces an optional `error_class` parameter to the `run_helper_subprocess` method. This parameter defaults to …

Make `HelperSubprocessFailed` error class configurable in run_helper_subprocess

---

composer/helpers/v2/src/UpdateChecker.php
composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb

Reverts dependabot/dependabot-core#10150
as we found the new approach to fix this.
https://github.com/dependabot/dependabot-core/pull/10182/files

Revert "Combining dependabot core version constraint (latest_allowable_version) with existing composer version constraint"

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb
composer/spec/fixtures/projects/php_specified_in_library/composer.json

provided the solution for ignore minor version not respected issue.
Before we look for the anything `=< latest_allowable_version`. (this cause the issue as some ignored version is part of this range). now we were looking for `=< latest_allowable_version` So it will not select any ignored version. 
As name suggest version_resover.rb checks that given latest_available_version is resolves or not
Changes made on ruby level not in php script now
Ran all the unit test against the solution and ensured by debugging logs.

Solution provided for ignore minor version config is not respected.

---

.github/workflows/smoke.yml
python/lib/dependabot/python/requirement.rb
python/lib/dependabot/python/update_checker/requirements_updater.rb
python/spec/dependabot/python/requirement_spec.rb
python/spec/dependabot/python/update_checker/requirements_updater_spec.rb

The goal of this PR is to revert a previous change that modified the behavior of the versioning strategy in Dependabot for Python dependencies. The reverted PR aimed to correct the behavior of the "increase" strategy but has introduced a bug. The versioning strategy needs to be re-planned and re-implemented correctly.
**Why:** The changes in the reverted PR caused unintended behavior that needs to be fixed. We will re-implement the correct versioning strategy after careful planning.
This reversion is necessary because the previous changes have introduced bugs in the versioning strategy. We need to re-evaluate and properly plan the versioning strategy before re-implementing it to avoid similar issues in the future.
The reversion will restore the previous behavior of the versioning …

Revert PR #10060: Fix Versioning Strategy for Python Dependencies

---

go_modules/Dockerfile

My company commits large files using Git LFS which happen to be part of our Go module source tree.
Without `git-lfs` installed, Dependabot's local git installation does not automatically resolve those files, causesing "checksum mismatch" against the committed `go.sum`.
Git LFS support is important when downloading Go modules directly from git repositories. Direct download is more common for private repositories. It is also a valid method to fetch module archives for public repositories, although those are often downloaded from the module-proxy.
While Git LFS may be relevant for other ecosystems, I've been heavily occupied with Go for the past several years. Thus, I'm unable to offer a qualified solution for all ecosystems. Nonetheless, I think this solution is very relevant for companies …

Support Go modules with LFS committed files

---

nuget/lib/dependabot/nuget/metadata_finder.rb
nuget/spec/dependabot/nuget/metadata_finder_spec.rb

PR #10025 moved the NuGet package source repository URL finder to native code, but since that feature is behind an experimental flag, the old version of `metadata_finder.rb` and the corresponding tests had to be temporarily restored.  Otherwise no change has been made.
Manually verified with the customer-reported repo.
Fixes #10178.

ensure ``Dependency::source::source_url`` can be populated from `.nuspec` uRL

---

common/lib/dependabot/errors.rb
npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

We are trying to reduce unknown_errors to change them into defined_errors that will improve support and provide clean error to customer. Followings are implemented to achieve that:
- Enhance the error handling for `npm_and_yarn` module by mapping `unknown_errrors` into defined errors.
- Handling errors through yarn error code. 
- Handling custom errors by using a systematic way to check patterns in error message  
Yarn Error Codes: https://yarnpkg.com/advanced/error-codes
Issue aiming to fix unknown_errors especially related to with missing dependencies and network errors during Yarn helper runs, reducing unknown errors. Also we changed the error structure to make it easy new specified errors for developers. 
Focus on core `common/lib/dependabot/errors.rb` changes since all defined errors …

Improve Yarn Helper Error Handling

---

updater/lib/dependabot/dependency_change.rb
updater/spec/dependabot/dependency_change_spec.rb

I took this change out of https://github.com/dependabot/dependabot-core/pull/10195 to make it easier to review.
This fixes rebases not working in the absence of directories in the existing PR job data, but also keeps the behavior for PRs that do have directories. Rather than considering the state of the experiment, we instead consider whether the directory is in the data we're about to compare. This way the data will work in either state.
Additionally I found that the tests for grouped updates were invalid as they had the wrong shape. The dependency array was wrapped in another redundant array. A proper type with Sorbet enforcement would be helpful here.
By treating the data itself as the feature flag, we can handle older PRs as well as new ones.
There's no way to validate with directory …

fix PR matching code for both directory and no directory cases

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/MockNuGetPackage.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestHttpServer.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/NuGetContext.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs

This feature is behind the `nuget_native_analysis` feature flag.
During a controlled roll out of the feature, a bug was found in the logs.  Misbehaving NuGet package sources could cause uncaught exceptions.  One example was found with Artifactory/JFrog.  This PR catches those exceptions so the analysis can continue.
The bulk of this PR is creating a test-only HTTP server to mimic the necessary `404` responses.

handle 404 from nuget sources

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/ExpectedDiscoveryResults.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestHttpServer.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Mixed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalysisResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/NuGetContext.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/WorkspaceDiscoveryResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ErrorType.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/NativeResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/analysis/dependency_analysis.rb
nuget/lib/dependabot/nuget/native_discovery/native_workspace_discovery.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/nuget_config_credential_helpers.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

With most of the update work being performed in C#, we need a mechanism to surface errors encountered.  This PR adds 2 fields to the output JSON, `ErrorType` and `ErrorDetails`.  Those values are then examined when the output JSON is processed and the relevant error is raised.
The bulk of this PR can be described in two changes:
1. Wrap calls to NuGet APIs and catch `HttpRequestException` with codes `401` or `403` and set the appropriate fields.
1. When we're starting an external process, we instead scrape the output for a known string and turn that into `HttpRequestException` to be caught further up the call stack.
2. Any time the Ruby code processes an output JSON file, check for `ErrorType` and raise, otherwise continue execution as normal.
The design allows future work of detecting …

surface authentication errors from native tool

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/CompatibilityCheckerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs

If a NuGet package doesn't list any dependency groups and has no assemblies in the `lib/` directory, it is assumed to be compatible with everything and according to NuGet and .NET Framework rules its framework is reported as `Any,Version=v0.0`.  This value needs to be special-cased in the compatibility checker; before we were doing straight equality checking, which isn't strictly correct.
This fixes an issue found in the logs during a controlled rollout of recent NuGet changes.

ensure every project is compatible with the `Any,Version=v0.0` framework

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Files/ProjectBuildFile.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

It's valid MSBuild to have leading and trailing whitespace in a package name in a `PackageReference` element so we need to explicitly handle that during reporting and updating.
Examining the logs showed that an attempt was made to fetch a URL like `https://<some-nuget-source>/some.package  /index.json` and this is because there was trailing whitespace in the project file of the form:
``` xml
...
<PackageReference Include="Some.Package   " Version="1.2.3" />
...
```
A normal `dotnet restore` and `dotnet build` call can handle this, so we must, too.  The fix was to call `?.Trim()` at a few key locations.

trim whitespace from package names

---

nuget/lib/dependabot/nuget/native_update_checker/native_update_checker.rb

Examining the logs showed some instances of the NuGet dependency info file failing to parse, but not much more information than that.  This PR logs the file's content to make later debugging easier.  We already report the discovery JSON file as well as the analyze JSON result, so this is in line with our current behavior.

write dependency info JSON to log

---

github_actions/lib/dependabot/github_actions/version.rb
github_actions/spec/dependabot/github_actions/version_spec.rb
terraform/lib/dependabot/terraform/version.rb
terraform/spec/dependabot/terraform/version_spec.rb

Stop github actions and terraform updates erroring for version formats like `v3.3.2` and `1.17.2+backport-1`
Malformed version number errors in terraform and github actions should stop

Fix malformed version number error for terraform and github actions

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/file_fetcher_command.rb

We put glob support behind a feature flag so it could be rolled out and tested. 
The feature is now released, we can remove this code.
Nope, I just got rid of `dependency_files_for_globs` and pulled the implementation up into `dependency_files_for_multi_directories` so the diff looks complicated.
Removing code that is no longer being run, so we shouldn't see any change.

remove glob experiment since glob support is released

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb

The goal is to fix an `ArgumentError` that occurs when the `latest_version` is `nil` in the `original_package_update_available?` method. Instead of performing a comparison when `latest_version` is `nil`, the method will return `false`. This will prevent the error and ensure the function handles the `nil` case gracefully.
By returning `false` when `latest_version` is `nil`, we avoid the `ArgumentError` that occurs due to the comparison with `nil`. This approach ensures that the method functions correctly even when the `latest_version` is not available.
- The error should no longer appear in the logs.
- Running the test suite should pass without errors related to this issue.
- Any additional tests should confirm that the function handles `nil` values for `latest_version` appropriately.

Fix `ArgumentError` in `original_package_update_available?` when `latest_version` is `nil`

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/NuGetContext.cs

Some CI runs fail due to a corrupted temporary NuGet package.  I can't get this to fail locally, but it seems to have a~30% failure rate in CI.  The temp directory is re-used between tests and I'm exploring a theory that one test writes a corrupt package and the next test reads that.  This PR uses a unique directory each time.  I'll be running CI repeatedly to see if I can get it to fail.
I've run the NuGet leg of the CI 10 times with no failures.  I'm good to call this ready.

use unique directory for temp nuget packages

---

.github/workflows/smoke.yml
bundler/helpers/v2/lib/functions/force_updater.rb

I noticed that #9923 seems to have caused an issue where security updates in Bundler subdependencies no longer succeed.
The new issue seems much worse than the original enhancement (a better error message in an edge case).
So I'm trying to fix it.
Closes https://github.com/dependabot/dependabot-core/pull/10251.
I think ideally we'd add support in upstream Bundler for things like `bundle lock --update foo=<version>`, since right now Bundler only has the capability of updating dependencies to their latest version.
But that's a big feature, so for now I used an approach that creates a `Bundler::Definition` from the Gemfile but adds an extra top level dependency to force the update.
Hopefully the new smoke test I added to cover this passes.

Fix security updates in Bundler subdependencies

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ErrorType.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/MissingFileException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb

During a restore of a project with a `packages.config` file, a missing targets/project file will fail the restore.  I saw instances in the logs of this resulting in `unknown_error` but in this case we know exactly what the problem is, so we scan the restore log for a well-known message and surface it appropriately.

report missing nuget files

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/group_update_all_versions.rb
updater/spec/dependabot/dependency_snapshot_spec.rb

This reverts the addition of `add_handled_group_dependencies` in #9938 because it's functionally equivalent to the existing `add_handled_dependencies`.
PR #8963 added support for multi-dir handling of dependencies. The way our update works, and how DependencySnapshot keeps track of the directory can be described with this pseudocode:
```
for each group {
for each directory {
dependency_snapshot.current_directory = directory
do_the_update(dependency_snapshot)
}
}
for each ungrouped_dependency {
for each directory {
dependency_snapshot.current_directory = directory
do_the_update(dependency_snapshot)
}
}
```
So anytime `add_handled_dependencies` is called, it uses the `@current_directory` which was set earlier. It has context of which directory is currently being updated. …

removing more of dependency_has_directory feature flag

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/RequirementTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/Requirement.cs

Requirements passed to an update operation (e.g., as a part of the `ignored_versions` property) can have multiple parts separated by a comma.  These are interpreted as the `AND` combination of each individual requirement.  The NuGet updater doesn't support this, so this PR adds that functionality.
The `Requirement` class was made abstract with two concrete classes inheriting from it; `IndividualRequirement` and `MultiPartRequirement`.
`IndividualRequirement` is exactly the same as the original `Requirement` class, modulo moving some common code into the base class.
`MultiPartRequirement` simply contains multiple `IndividualRequirement`s and when checking for version compatibility, returns the `AND` combination of all parts via the LINQ method `All()`.

support multi-part requirements

---

.github/workflows/ci.yml

I noticed in passing that this is on `1.21`, def time to bump it to `1.22`.

Use `go` `1.22` in CI

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Analyze.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/MockNuGetPackage.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs

When analyzing packages for updates, the current code path only considers projects (e.g., `*.csproj`, etc.)  This PR explicitly analyzes the dependencies of `global.json` and `.config/dotnet-tools.json`.  Since these are top-level items in top-level files, we can directly return the new dependencies array once we've computed the newest available version.
This PR also includes required changes to test code to allow passing in extra metadata when creating mock NuGet packages.

analyze `global.json` and `dotnet-tools.json`

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

The goal of this PR is to centralize and manage yarn error handling logic within the `YarnErrorHandler` class. This change aims to move error handling from the business logic defined in `YarnLockfileUpdater` into `YarnErrorHandler`, making the code more generalized and maintainable.
This approach was chosen to streamline error handling by separating concerns and improving the maintainability of the codebase. It also aligns with the update in dependabot-core (#10177) for more manageable error handling.
- If errors are consistently handled by the `YarnErrorHandler` class instead of being scattered across the `YarnLockfileUpdater`.
- By running tests to ensure that all existing error handling scenarios are correctly managed by the new implementation.
- By confirming that the new error …

Centralize Yarn Error Handling for Yarn Update

---

python/lib/dependabot/python/metadata_finder.rb
python/spec/dependabot/python/metadata_finder_spec.rb
python/spec/fixtures/pypi/pypi_response_project_urls_source.json

Dependabot opened a PR to bump the version of a python module, django-split-settings. However, in the body of the PR, the URL that has been created is wrong. It is a funding URL that has been configured in the package metadata. 
Customer is seeing a URL which is unrelated to the package. The URL is used to go to the package repository directly from the PR. However, with the wrong URL in place, the user is being redirected to the wrong place and getting a 404.
Dependabot will create the PR with the correct link.

Use repository in project urls as a source

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

This PR aims to reduce the number of unknown errors by creating specific, related error messages for the YN0035 error code. The YN0035 error occurs when the remote server fails to provide the requested resource for a package. By capturing and handling this error, we can provide more informative error messages.
This change addresses the need for better error handling in scenarios where packages cannot be retrieved due to server issues, which is crucial for maintaining the reliability and usability of the package management process.
The main focus of this PR is to ensure that the error messages are specific and helpful, significantly aiding in diagnosing issues during package retrieval.
- If an error occurs with YN0035, the error handler will capture it and provide a detailed error message …

Handle Errors Coded with YN0035 Yarn Error Code

---

updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb

Updated Typings to Strict Type for CreateSecurityUpdatePullRequest
I have updated the typings to be strict type for the `CreateSecurityUpdatePullRequest` class. This change aims to improve type safety and reliability of the code by enforcing stricter type checks.
While updating the typings, I made sure to cover all method signatures and type annotations. Please pay special attention to any edge cases that might have been affected by these changes.
By ensuring that all tests pass successfully and no type-related errors are introduced.

Strict type `Dependabot::Updater.Operations::CreateSecurityUpdatePullRequest`

---

silent/tests/testdata/su-basic.txt
silent/tests/testdata/vu-basic.txt
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb

- fixes #10310
In #10195 we added `directory` to the payload, which then came back in the `existing-pull-requests` data, which made these methods stop working because they didn't take `directory` into account.
The fix is to include it in the comparison, but we also need to support the older data as well so that check is done second.
In the future we can DRY this up, but for now it works!
Rebases will start working again.

fixing rebases not finding the existing pull request due to directory

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Adding a transitive dependency is accomplished by invoking the CLI tool `dotnet add project.csproj package Some.Transitive.Dependency --version 1.2.3`, but if that project has custom `msbuild-sdks` listed in `global.json` _and_ that SDK is explicitly imported, then adding the package will fail because the `global.json` file is temporarily sidelined (see #10305) to prevent any issues with a .NET SDK mismatch.
The fix is to optionally retain a bare-bones `global.json` with _only_ the `msbuild-sdks` property to allow package installation to proceed.

retain `msbuild-sdks` property in `global.json` when adding a transitive dependency

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb

**Preface:** Fixes issues related with Dependabot::SharedHelpers::HelperSubprocessFailed 
**Issues and fixes:** Following are the exceptions and intended fixes:
1. Issue related with `socket hang up` . It was observed that a variation of _socket hang up_ exception was returned from native helper which was not handled.
`request to https://nexus.xyz.com/repository/npm-js/ejs failed,reason: socket hang up`
**Fix:** modifies the exception filter to contain the exception
2. Issues related with `ESOCKETTIMEDOUT`. Following response was returned from native helper on socket time out.
`https://npm.pkg.github.com/@group%2ffe-release: ESOCKETTIMEDOUT`
**Fix:** Adds exception filter and raises `PrivateSourceTimedOut` exception.
3. If package.json file is malformed, `premature close` response is …

Fixes Dependabot::SharedHelpers::HelperSubprocessFailed issues

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This PR aims to fix a bug for the `npm_and_yarn` ecosystem. The changes include:
1. Implementing accurate reporting for transitive dependencies by returning `nil` when there are conflicting dependencies and the dependency is not top-level.
2. Ensuring that the correct security fix version is identified for both top-level and transitive dependencies within the `npm_and_yarn` ecosystem.
This change is necessary to ensure that our system correctly handles and reports vulnerable transitive dependencies within the `npm_and_yarn` ecosystem, improving our ability to maintain a clear and accurate dependency relationship.
This change specifically addresses the bug related to conflicting transitive dependencies in the `npm_and_yarn` ecosystem.
- The system accurately identifies and reports the …

Report transitive dependency vulnerability errors for npm, yarn, and pnpm

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/codespell.yml
.github/workflows/smoke.yml
.github/workflows/sorbet.yml

Lately we have been running out of API quota because the CI and smoke tests use tokens for testing.
Since we require branches to be up-to-date before merging, running these things on main is kind of pointless. So we can save quota by not running them again.
I know some of these workflows that I removed the main run from don't use the token, but again I don't see the point in running them on main if the branch was up-to-date.
Is my assumption above correct?
Maybe we'll run out of quota less often.

don't waste quota on main since branch was up-to-date

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/RequirementTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/Requirement.cs

Version requirements, particularly `ignore`, can have wildcards, commonly in the form of `> 2.*, < 3`, e.g., to ignore all v2 versions of a package.  The underlying `NuGetVersion` class doesn't allow wildcards, but since we're only doing this for requirements which always have an operator, we can support them.
The new behavior simply splits the version on the `.` character and replaces any single character wildcard with `0`.  For NuGet the only single character wildcard allowed is `*`, but it's not uncommon for a single letter like `a` or `x` to be used, so I added support for that as well.
Issue found during a manual scan of the logs.

allow for wildcards in version requirements

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs

When analyzing the potential package upgrades, if the given package doesn't exsit on _any_ feed, quit early and report that the current version is up-to-date.
Found during a manual scan of the logs.

report no new version if a given package doesn't exist on any feed

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TemporaryEnvironment.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs

When #9694 was created to force unit tests to not hit the network, there was one case where we didn't yet have the test infrastructure, because one particular test _requires_ network access, but now we have the appropriate test helpers to hit `localhost`.  This PR simply converts this remaining test from using real packages from nuget.org to using test-only packages and a `localhost` NuGet feed.
I've manually confirmed that we hit the same codepath.

convert test to not require the network

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

This PR aims to add error handling for the YN0082 error code in the `YarnErrorHandler`. The YN0082 error occurs when no candidates are found for a specified package version, and it needs to be captured and handled appropriately to improve the error reporting and user experience.
The approach used to handle the YN0082 error is similar to the existing handling of the YN0035 error. It captures the package causing the error and raises a `Dependabot::DependencyNotFound` error with the relevant package information.
- The error handling code for YN0082 should correctly capture and raise the `Dependabot::DependencyNotFound` error.
- The added tests should pass, demonstrating that the new error handling works as expected.
- Running the complete test suite should ensure no other functionality is …

Add Error Handling for YN0082 in YarnErrorHandler

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
npm_and_yarn/spec/fixtures/npm_responses/200_with_invalid_json.json
npm_and_yarn/spec/fixtures/npm_responses/200_with_valid_json.json

**Preface:** Related with `JSON::ParserError` issues.
**Issue:**  Private registry usually returns 200 code in case of successful response. The response contains package information as a JSON object. But it was observed that some private registries return 200 code with an HTML markup (usually for login). :dependabot: throws a `JSON::ParserError` in case of invalid JSON object.
**Fix:** Identify if the response body being returned is valid JSON and raise proper exception in case invalid JSON.
```
+---------------------------------------------------------+
|              Dependencies failed to update              |
+------------------------+--------------------------------+
| jszip                  | dependency_file_not_resolvable | …
```

Fixes JSON::ParserError: unexpected token issue

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
npm_and_yarn/spec/fixtures/npm_responses/lodash.json
npm_and_yarn/spec/fixtures/projects/npm8/top_level_and_transitive/package-lock.json
npm_and_yarn/spec/fixtures/projects/npm8/top_level_and_transitive/package.json

When a security update is run and the project has the vulnerability as both a direct dependency, and indirect dependency of other top-level dependencies, Dependabot only fixes the top-level dependency.
By using the audit's abilities during the `lowest_security_fix_version` check we can return `nil` to force a full unlock.
Also made a slight modification to return audit results more often when doing a security update.
I have a real-world test here: https://github.com/dsp-testing/npm-multiple-top-level-ancestors
The PR created should remove all instances of the vulnerable lodash.

NPM: fix security update for indirect and direct dependencies

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/updater_spec.rb

**Preface:** Fixes issue related with `RuntimeError-No package.json` and `Dependabot::SharedHelpers::HelperSubprocessFailed`
**Fixes:** 
1. Fixes user runtime exception ` RuntimeError::No package.json!` with `DependencyFileNotFound` exception.
2. Allows exception handling for 
a. `Unauthenticated: request did not include an Authorization header.`
b. `ESOCKETTIMEDOUT`
c. `socket hang up`

Fixes RuntimeError-No package.json issue

---

common/lib/dependabot/errors.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_no_access/.npmrc
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_no_access/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_no_access/pnpm-lock.yaml
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_with_server_error/.npmrc
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_with_server_error/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/private_repo_with_server_error/pnpm-lock.yaml

**Preface:** Fixing issues related with `HelperSubprocessFailed` and sanitize error response for `yarn_lock_file_updater`
**Issues:** Resolves following issues:
```
ERR_PNPM_FETCH_401  GET  https://registry.npmjs.org/@typescript-eslint/parser/-/parser-5.62.0.tgz:  - 401
ERR_PNPM_FETCH_403 GET  https://registry.npmjs.org/@typescript-eslint/parser/-/parser-5.62.0.tgz:  - 403
ERR_PNPM_FETCH_500  GET  https://registry.npmjs.org/@typescript-eslint/parser/-/parser-5.62.0.tgz:  - 500
ERR_PNPM_FETCH_502 GET  https://registry.npmjs.org/@typescript-eslint/parser/-/parser-5.62.0.tgz:  - 502
```
**Fix:** Adds exception handling for `ERR_PNPM_FETCH` errors. 
```
+-----------------------------------------------------------------------------------+
|                           Dependencies failed to …
```

Fixes ERR_PNPM_FETCH-HelperSubprocessFailed 

---

updater/lib/dependabot/updater/group_update_creation.rb

This commit addresses type issue that the introduction of type has brought about.
The PR #9929 has introduced a regression in which the type check stops execution. It is apparently unexpected as the final message results in "unknown_error" and the backtrace appended to this message is the only clue to debug with.
However once you take a look inside the root of the error is rather expectable so let's not overwhelm those who might encounter from this time on.
```
2024/08/09 12:24:28 INFO Checking if faraday-httpclient 1.0.1 needs updating
2024/08/09 12:24:28 INFO Latest version is 2.0.1
2024/08/09 12:24:39 INFO Requirements to unlock all
2024/08/09 12:24:39 INFO Requirements update strategy bump_versions
2024/08/09 12:24:39 ERROR Passed `nil` into T.must
2024/08/09 12:24:39 ERROR …
```

Guard against possible nil before the actual nil inevitably stops execution

---

.dockerignore
.github/workflows/smoke.yml
.gitignore
nuget/.dockerignore
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Update.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Sdk.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/DependencyConflictResolver.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/native_helpers.rb

My code is currently behind an environment variable not yet set. Will work with @brettfo to put this behind the experiment flag.
Looking for feedback on implementation, unit tests, variable names, etc. 
DependencyConflictResolver.cs is the main code.
MSBuildHelper.cs and MSBuildHelperTests.cs  were used for tests
UpdateWorkerTests.Sdk.cs was lightly used with testing with Brett
Added temporary commit to make smoke tests pass.
Smoke Test PR: 
https://github.com/dependabot/smoke-tests/pull/219
This is the PR that adds the experiment:
https://github.com/github/dependabot-api/pull/5511

feature-intern-ResolveDependencyConflictsNew to main

---

.github/workflows/ci.yml
.github/workflows/smoke.yml

We have been running into the API rate limit, so this is a way we can lower our usage.
No
Maybe we'll hit the rate limit less.

lower API rate usage by enabling git-powered comparison

---

updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/job.rb
updater/lib/dependabot/pull_request.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/lib/dependabot/updater/security_update_helpers.rb
updater/spec/dependabot/dependency_change_spec.rb
updater/spec/dependabot/pull_request_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb

- See https://github.com/dependabot/dependabot-core/issues/9561
Replaces an Array of Hashes with an actual class! This prevents typos and makes Sorbet more useful. 
One challenge here was we use a mini-version of Dependency. So I didn't want to reuse the Dependency class as the comparison is kind of special, so I made an inner-class Dependency under Pull Request. Is that confusing? Should it have a different name?
This change should have no functional difference, so as long as the type checking and tests are passing, and no new errors popup after deployment we should be good.

type existing prs in the job definition

---

.github/workflows/smoke.yml

Revert the branch used for running smoke tests back to the one used in `dependabot-core` main. This is necessary to ensure consistency and compatibility with the main branch of `dependabot-core`.
The previous change commit: https://github.com/dependabot/dependabot-core/commit/d09bc1efa1b95c321f7a58f5ce6b30b51bf6a0c4
This change reverts the smoke test branch to align with the `dependabot-core` main branch. It is important to review any potential impacts this might have on the existing tests and their outcomes.
- The smoke tests run successfully using the `dependabot-core` main branch.
- Any errors or issues specific to the previous branch setup are resolved.

Revert Smoke Test Branch to Dependabot-Core Main

---

bundler/lib/dependabot/bundler.rb
bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/file_parser/file_preparer.rb
bundler/lib/dependabot/bundler/package_manager.rb
bundler/spec/dependabot/bundler/file_parser_spec.rb
bundler/spec/dependabot/bundler/package_manager_spec.rb
common/lib/dependabot/file_parsers/base.rb
common/lib/dependabot/notices.rb
common/lib/dependabot/package_manager.rb
common/lib/dependabot/pull_request_creator/message_builder.rb
common/spec/dependabot/file_parsers/base_spec.rb
common/spec/dependabot/notices_spec.rb
common/spec/dependabot/package_manager_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
updater/lib/dependabot/dependency_change.rb
updater/lib/dependabot/dependency_change_builder.rb
updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/lib/dependabot/updater/security_update_helpers.rb
updater/spec/dependabot/dependency_change_spec.rb
updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_version_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/update_all_versions_spec.rb
updater/spec/dependabot/updater/pull_request_helpers_spec.rb

The goal of this PR is to enhance the file parser to return the `package_manager` information directly. This change has been implemented for Bundler, and other package managers can have this feature added in the future. This information will be used to check for deprecation warnings specifically for Bundler v1.
This change allows us to better handle deprecation warnings for Bundler v1 by providing a consistent way to access package manager information directly from the file parser.
- The abstract `package_manager` method has been added to the base file parser.
- For Bundler, the `package_manager` method has been implemented and returns the necessary information for deprecation warnings.
- For other package managers, the `package_manager` method is currently not implemented but can be …

Add Bundler v1 Deprecation Warning

---

common/lib/dependabot/notices.rb
common/spec/dependabot/notices_spec.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb

This PR reformats the deprecation and error messages related to Bundler v1 support. The goal is to make the messaging clearer and more grammatically accurate for users when they encounter notices about upgrading or unsupported versions.
This change improves the readability and clarity of the deprecation warnings and error messages for Bundler v1, ensuring that users have a better understanding of the steps they need to take.
The focus was on improving the grammar and structure of the messages. Please review the changes to ensure that the messaging is clear and that no important information was lost in the reformatting.
- The deprecation and error messages are clearer and more grammatically correct.
- Users encountering these messages should have a better understanding of the required …

Reformatted Deprecation and Error Messages for Bundler v1 Support

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

When running NuGet dependency discovery, we should only process project types that are explicitly supported, namely `.csproj`, `.vbproj`, and `.fsproj`.  This is consistent with how it's done elsewhere in this repo, we just missed a spot.
Fixes #10372

only discover dependencies from known project types

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/file_updater.rb
nuget/lib/dependabot/nuget/native_discovery/native_dependency_file_discovery.rb
nuget/lib/dependabot/nuget/native_discovery/native_discovery_json_reader.rb
nuget/lib/dependabot/nuget/native_discovery/native_project_discovery.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/native_update_checker/native_requirements_updater.rb
nuget/lib/dependabot/nuget/native_update_checker/native_update_checker.rb
nuget/lib/dependabot/nuget/update_checker.rb
nuget/lib/dependabot/nuget/update_checker/requirements_updater.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb
nuget/spec/dependabot/nuget/native_update_checker/native_requirements_updater_spec.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

~~### Contains a temporary commit to redirect the smoke test branch.  This commit needs to be reverted prior to merging, but is here to show the updated smoke tests pass.~~
Related smoke test PR: dependabot/smoke-tests#221
The handling of multiple dependencies, including transitive dependencies, wasn't done correctly for NuGet.  An example best illustrates this:
1. `file_parser.rb` returns 3 dependencies:
- `Dependency1, name=Newtonsoft.Json, Version=12, locations={FileA.csproj}`
- `Dependency2, name=Newtonsoft.Json, Version=11, locations={}` // this was a transitive dependency, no location given to conform to expectations in the common code, but in reality, this transitive dependency came from FileB.csproj
- `Dependency3, name=Newtonsoft.Json, Version=13, locations={FileC.csproj}`
2. …

fix handling of NuGet transitive dependencies

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/file_updater.rb
nuget/lib/dependabot/nuget/native_discovery/native_dependency_file_discovery.rb
nuget/lib/dependabot/nuget/native_discovery/native_discovery_json_reader.rb
nuget/lib/dependabot/nuget/native_discovery/native_project_discovery.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/native_update_checker/native_requirements_updater.rb
nuget/lib/dependabot/nuget/native_update_checker/native_update_checker.rb
nuget/lib/dependabot/nuget/update_checker.rb
nuget/lib/dependabot/nuget/update_checker/requirements_updater.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb
nuget/spec/dependabot/nuget/native_update_checker/native_requirements_updater_spec.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

~~## This PR contains a temporary commit to redirect the smoke tests.  That temporary commit needs to be removed before merging.~~
Corresponding smoke-tests PR that should go in at the same time: dependabot/smoke-tests#224
NuGet dependencies only exist via MSBuild and that allows arbitrary directory crawling.  Due to the complexities of that, the previous PR #10449 is being reverted.
Future NuGet work will require rewriting the updater to not use any of the common dependabot code and that means the NuGet updater will be in a "broken" state for the time being and the previous version of "broken" is better than the current.

Revert "rework reporting of dependencies and requirements to better handle transitive dependencies"

---

python/Dockerfile
python/lib/dependabot/python/language_version_manager.rb

Closes https://github.com/dependabot/dependabot-core/issues/10469

chore(python): target latest python 3.12.5 version

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

**Preface:** Fixes issues related with YARN `Dependabot::DependabotError` errors.
**Issues:** Yarn update response errors handling issues
**Fixes:** Adds exception handler for following Yarn codes:
```
YN0001-Libzip
YN0009-Build Failed
YN0041-Invalid authentication
YN0060-Incompatible peer dependency
YN0068-No matching package
YN0086-Peer dependencies incorrectly met
```

Adds handler for YARN :: YN0xx errors

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

**Preface:** Issue related with Dependabot::Updater::SubprocessFailed: Subprocess issues
**Issues:** Unhandled exceptions in YARN package manager response
**Fix:** Adds error handlers for following:
```
Request returned a 403
authentication required
Permission denied
bad_request
500 Internal Server Error
Couldn't find package
```

Error handler for Dependabot::Updater::SubprocessFailed: Subprocess issues

---

bin/docker-dev-shell

When following README steps:
https://github.com/dependabot/dependabot-core/blob/dc7b8d2ad152780e847ab597d40a57f13ab86d4f/README.md?plain=1#L409-L415
Facing issue with running rubocop locally:
```bash
dependabot-core$ bin/docker-dev-shell cargo
> image dependabot/dependabot-core-development-cargo already exists
=> running docker development shell
[dependabot-core-dev] ~ $ cd cargo
[dependabot-core-dev] ~/cargo $ rubocop
Configuration file not found: /home/dependabot/.rubocop_todo.yml
[dependabot-core-dev] ~/cargo $
```
Fix mount to enable local execution of rubocop

Mount `.rubocop_todo.yml` to enable successful rubocop execution

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/opentelemetry.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/lib/dependabot/updater/security_update_helpers.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/update_all_versions_spec.rb
updater/spec/dependabot/updater/pull_request_helpers_spec.rb

This PR introduces a deprecation warning alert for `bundler v1`.
**Why:**
- To provide information regarding deprecation if used ecosystem versions in the alert with users. 
This change ensures the bundler v1 deprecation is sent to api that can be used to displayed on github ui. 
The changes are focused on sending bundler v1 deprecation notice to api. This PR requires changes from https://github.com/dependabot/dependabot-core/pull/10466 PR.  
Note: The sent notice is going to be delegate github UI through api and from there is going to be shown to the user on dependabot insight page. 
- Successfully sending deprecation warnings for Bundler v1 to dependabot-api.
- Verification through tests that the correct deprecation warning shown in alerts on github ui for bundler v1
- Similar to the …

Sending Bundler v1 Deprecation Warning Alert

---

common/lib/dependabot/notices.rb
common/spec/dependabot/pull_request_creator/message_builder_spec.rb
updater/lib/dependabot/notices_helpers.rb

This PR ensures that deprecation warnings for `bundler v1` are properly displayed in both the pull request message and the logs.
There are two key fixes in this PR:
1. **PR Message Warning**: The `bundler v1` deprecation warning is now correctly displayed in the PR message without including the "Bumps rails..." message within the warning block.
Example of the fixed warning:
2. **Logging Warning Consistency**: In the log output, the second deprecation warning message ("Please upgrade to version `v2`.") should properly work under the updater thread. 
After fix:

Fix showing bundler v1 deprecation warnings in PR message and logs

---

cargo/lib/dependabot/cargo/file_fetcher.rb
cargo/spec/dependabot/cargo/file_fetcher_spec.rb
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_detached_crate_fail_1.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_detached_crate_fail_2.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_detached_crate_success.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_detached_workspace_member.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_incorrect_detached_workspace_member.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_incorrect_workspace.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_workspace.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_cargo_manifest_workspace_nested_one_nested_two.json
cargo/spec/fixtures/github/path_dependency_workspace_member/contents_dir_detached_crate_success.json

Given a repository like so:
```
.
├── cli_crate
│   ├── Cargo.toml
└── workspace
├── Cargo.toml
└── nested
└── Cargo.toml
```
Where `workspace` represents a workspace containing only `nested`, and `cli_crate` has a path dependency to `nested`, and `nested` inherits any property from the root (e.g. `edition =  { workspace = true }`).
If we point dependabot to only `cli_crate`, it will error out when running `cargo update` as though it can fetch the path dependency `nested`, it cannot resolve this as it also needs the `workspace` due to this inheritance. Fix Cargo file_fetcher to support this logic of locating the root of a workspace member who is a path dependency, and fetching it.
For negative cases, where the root cannot be located or is incorrect, emit an error message (instead of when …

Support retrieving workspace of path dependencies in cargo

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectResolver.cs

Fix #10549.
See https://github.com/dependabot/dependabot-core/issues/10549#issuecomment-2333227090 for context.
When a .NET Framework project contains an assembly reference that does not have "PublicKeyToken" specified, e.g.
```csproj
<Reference Include="CSharpFunctionalExtensions, Version=2.40.3.0, Culture=neutral, processorArchitecture=MSIL">
<HintPath>..\packages\CSharpFunctionalExtensions.2.40.3\lib\net461\CSharpFunctionalExtensions.dll</HintPath>
</Reference>
```
The update will fail when updating assembly binding redirects in `app.config`/`web.config`, e.g.
```log
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.ArgumentNullException.Throw(String paramName)
at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
at …
```

Fix argument null exception when updating assembly references with no public key token

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/registry_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

Preface: Issues related with Dependabot::Updater::SubprocessFailed
Issues: Unhandled exceptions related Yarn YN0001 error codes, Argument errors and URI errors
Fixes: Captures and adds relevant exception handlers

Fixes Dependabot::Updater::SubprocessFailed issues

---

CONTRIBUTING.md

The most common reason a contributor would need to edit the docs is to bump supported package manager versions. So let's link directly to that.

Add direct link to the docs for package manager versions

---

common/lib/dependabot/errors.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb

**Preface:** Issue related with `Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder::RegistryError`
**Issue:** Due to `RegistryError` exception placement, the error was incorrectly being thrown into `unknown_error` type
**Fix:** Fixes placement of `RegistryError` exception type so that it is raised under correct exception type instead of unknown_error type.
```
+-------------------------------+
| Dependencies failed to update |
+--------------+----------------+
| express      | registry_error |
+--------------+----------------+
```

Fix : RegistryError error handler correction to stop propagation to unknown_errors

---

bundler/lib/dependabot/bundler/helpers.rb

This PR updates the default behavior to use Bundler v2 when the `bundler_v1_unsupported_error` feature flag is enabled and a Gemfile.lock exists. If the Gemfile.lock does not specify the Bundler version, we will now default to Bundler v2 instead of v1 when the flag is active.
This change affects how dependencies are handled when there is no explicit Bundler version in the Gemfile.lock. With the feature flag enabled, the failover will be Bundler v2. This ensures compatibility with newer versions and prevents issues with unsupported Bundler v1.
- Bundler v2 is correctly used as the default when the `bundler_v1_unsupported_error` flag is enabled and the Gemfile.lock exists but lacks version information.
- Dependencies update as expected using Bundler v2 under these conditions.
- The feature …

Change default to Bundler v2 when unsupported feature flag is on and Gemfile.lock exists

---

.github/workflows/sorbet.yml

Run the Sorbet workflow against `main` as it only generates the report against `main`. This was removed in #10352.
cc: @jakecoffman

Run sorbet against `main`

---

.github/workflows/smoke.yml
maven/lib/dependabot/maven/new_version.rb
maven/lib/dependabot/maven/update_checker/requirements_updater.rb
maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/new_version_spec.rb
maven/spec/dependabot/maven/requirement_spec.rb
maven/spec/dependabot/maven/update_checker/requirements_updater_spec.rb
maven/spec/dependabot/maven/version_spec.rb

Reverts dependabot/dependabot-core#10558

Revert "Use new implementation of Maven version standard"

---

common/lib/dependabot/errors.rb
nuget/lib/dependabot/nuget/file_updater.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb

When the NuGet updater cannot perform any update, jobs currently fail with `unknown_error` which comes from here: https://github.com/dependabot/dependabot-core/blob/dddd7b2f60e72bd93e3490f1ab88d413419f3a27/updater/lib/dependabot/dependency_change_builder.rb#L73
This isn't very descriptive and makes it difficult to investigate the `unknown_error` bucket, especially since in this case we know exactly what went wrong.
The fix is to add a new error type that represents this scenario and raise it directly in the NuGet updater.  This has the benefit of making the call stack more usable.
The error type string `update_not_possible` is already well-known.

raise specific error when no update was possible

---

python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb

**Preface:** Issue related with `Dependabot::SharedHelpers::HelperSubprocessFailed` 
**Issues:** 
1. Python version mentioned in .toml file is not compatible with dependency
2. Package version mentioned in .toml file is not found in python package index
3. Error 401 while accessing private package index
**Fix:** 
Adds exception handlers to appropriate error messages and show useful message to user

Python Dependabot::SharedHelpers::HelperSubprocessFailed issues fixes

---

nuget/helpers/lib/NuGetUpdater/Directory.Packages.props

There was a bug in an XML reader used by the NuGet updater that has been fixed in a recent release.  Simply bumping that package.
Specifically, the issue was round-tripping attributes with single quotes.  E.g., this:
``` xml
<Element Attribute='value' />
```
was incorrectly round-tripped as this:
``` xml
<Element Attribute='value" />
```
Notice the closing quote of the attribute was changed from a single to a double quote.

update package to fix bug in XML reader

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Update.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/MockNuGetPackage.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/LockFileUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/NuGetHelper.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ProcessExtensions.cs

With #9678, the nuget updated gained support for package lock files.
However, it fails when the csproj path contains spaces (see https://github.com/dependabot/dependabot-core/pull/9678#issuecomment-2376037446).
This now changes the `ProcessEx` helper to accept a list of args (instead of just a string). This should fix this issue for the lock file update as well as several other places.
My initial thought was to simply escape the strings myself, but `ProcessStartInfo` has a constructor that also takes an argument list, so I opted to use that one and leave the escaping to the system.
Also, I didn't just want to fix the lock file updater, because I found other places where paths (which can possibly contains spaces) weren't correctly escaped. With that API change, it should no longer be an …

Make sure process parameters are correctly quoted

---

nuget/helpers/lib/NuGetUpdater/.editorconfig
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/TestApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/DependencyFileNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PrivateSourceAuthenticationFailure.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/IApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs

This updates the full end-to-end update runner (not yet in production) for NuGet by rearranging the error handling.  The individual tools used by the current Ruby updater remain unchanged, but everything else has been refactored so that one single place of error handling could be added to `RunWorker.cs`.  This involved creating new types to represent `private_source_authentication_error`, `dependency_file_not_found`, and `unknown_error` as a catch-all.
The changes to `AnalyzeWorker.cs`, `DiscoveryWorker.cs`, and `UpdaterWorker.cs` are simply to move the `try`/`catch` blocks to a different function.
Future work will be to add support for more error types.

rearrange NuGet error handling to one location in full runner

---

nuget/lib/dependabot/nuget/update_checker/repository_finder.rb
nuget/spec/dependabot/nuget/update_checker/repository_finder_spec.rb

NuGet feed URLs can appear in `NuGet.Config` files either as URL-escaped or unescaped values.  This PR mimics what NuGet proper does and first tries to parse the URL and if that fails, then the URL is escaped.

only escape repo urls if necessary

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/RequirementTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/Requirement.cs
nuget/lib/dependabot/nuget/requirement.rb
nuget/spec/dependabot/nuget/requirement_spec.rb

Requirement strings were found in the wild with a trailing comma, e.g., `>= 1.40.0, `
A quick check of two other requirement handlers, NPM and Python, both allow for an empty value so the NuGet version is being updated as well.

allow empty version after comma in a requirement

---

npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/version_selector.rb

Related to https://github.com/dependabot/dependabot-core/pull/10510
This feature flag was tested for feasibility and found to be successful in providing runtime version installation for pnpm and yarn package managers
Now the feature flag is tested and can be cleaned up.

Cleans up feature flag for dynamic version selector

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Analyze.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Discover.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ErrorType.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/NativeResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdateNotPossible.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/UpdateNotPossibleException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb

If a required package is missing from all sources in a `packages.config` scenario, report `UpdateNotPossible` instead of `unknown_error`.
An instance of this was seen where a `NuGet.Config` file was using an Azure DevOps feed with a restricted view that didn't have all packages listed.

report specific error when project cannot be restored

---

terraform/lib/dependabot/terraform/file_updater.rb

Strict type `Dependabot::Terraform::FileUpdater`

Strict type `Dependabot::Terraform::FileUpdater`

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

This patch builds on the prior update to set npm 8 as the default and fallback version for lockfile versions 2 and above. It addresses an issue where npm 9 was incorrectly altering the lockfile version to 1 for some projects, ensuring npm 8 consistency and lockfile stability for projects relying on version 3 lockfiles.
Just note that, this PR is continuation fix of following merged PR. 
- https://github.com/dependabot/dependabot-core/pull/10757
- Resolves the issue of lockfile version inconsistency when npm 9 inadvertently changes lockfile version to 1.
- Ensures consistent use of npm 8 as the fallback, improving reliability for projects with lockfile versions above 2.
- The patch limits npm handling by enforcing npm 8 as the fallback for lockfile versions 2+, maintaining expected …

Patch: Enforce npm 8 for Lockfile Version 2+

---

python/lib/dependabot/python/requirement.rb
python/lib/dependabot/python/version.rb
python/spec/dependabot/python/requirement_spec.rb
python/spec/dependabot/python/version_spec.rb

[Link to issue](https://github.com/dependabot/dependabot-core/issues/10611)
Update our python version implementation to be conformant with the python version specification here: https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions
I'm updating the regex for version formats to be the one specified in the python version specification.

Update python version regex and fix version ordering

---

npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

This PR updates test specs to align with the recent changes introduced in the merged PR [Update NPM Default and Fallback Versions to NPM 8](https://github.com/dependabot/dependabot-core/pull/10757). These changes ensure that all specs accurately reflect the new default and fallback npm version of 8.
These updates address test mismatches in registry URL and npm version handling following the update to npm 8 as the fallback version.
This update ensures compatibility with npm 8 as the standard for dependency resolution, while maintaining legacy npm 6 behavior where necessary. The `npm_fallback_version_above_v6` feature flag is enabled or disabled in specs based on the specific scenario being tested.
- **Testing**: All tests should pass with npm 8 as the default and fallback version.
- …

Update Specs for NPM 8 as Default and Fallback Version

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs

When looking in a `.csproj` for a `web.config` file, the XML can take various forms.  Previously only the exact form of `<Content Include="web.config" />` was allowed.
This PR fixes that.  The bug was that we were first considering the `<Content>` element's raw content before considering the `Include` attribute, but we need to look at the attribute first and only if that fails consider the raw content.
Now the tested formats include (values seen in the wild):
``` xml
<Content Include="web.config" />
```
``` xml
<Content Include="web.config">
</Content>
```
``` xml
<Content Include="web.config">
<SubType>Designer</SubType>
</Content>
```

allow for various xml formatting when finding runtime config file

---

nuget/lib/dependabot/nuget/file_updater.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb

When lock file support was added, an allowed file regex was missed.  There is also an internal-only PR that has also been submitted with the same fix.
Fixes #10730.

update allowed files regex

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/ExpectedUpdateOperationResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ErrorType.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb

While adding error handling last week I missed a spot to catch a generic `Exception` and report it up the chain; this fixes that.
Previously, the telemetry would classify a whole variety of failures under the category `Dependabot::SharedHelpers::HelperSubprocessFailed: No dotnet-tools.json file found.` due to the first line in the command's output.  Now we'll get properly grouped failures.
I found in the logs where a NuGet server returned a `500` and that made NuGet fail miserably but made for a great test case.

handle all errors during an update job

---

nuget/Dockerfile

Fixes currently broken `nuget` ecosystem build for `arm64` architecture due to not having a prebuilt powershell `.deb` package. Changes installation method to use pre-built binaries instead of `.deb` package.
Fixes: https://github.com/dependabot/dependabot-core/issues/10689
Currently it's not possible to validate on CI due to not having `arm64` architecture builds. I have ran this locally though on my arm machine and image is building. If CI passes, it at least should show that regressions were not introduced.

Fix nuget ecosystem arm build

---

npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private/pnpm-lock.yaml
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private_v8/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/github_dependency_private_v8/pnpm-lock.yaml

**PR Description**:
This PR addresses an issue in the `pnpm` specs where we were using the `https://github.com/Zelcord/electron-context-menu` dependency as a git dependency, which was previously private. This setup led to errors in tests involving private dependencies. To resolve this, I've created an equivalent dependency in our `dependabot-fixtures` account, named `pnpm_github_dependency_private`, at `https://github.com/dependabot-fixtures/pnpm_github_dependency_private`.
The goal is to replace the private `electron-context-menu` dependency in `pnpm` specs with an equivalent dependency in our `dsp-testing` repository. This change ensures that tests for private dependencies can run without errors.
I opted for creating an equivalent dependency in our controlled `dependabot-fixtures` …

Update pnpm Specs with Public Git Dependency for Private Testing

---

silent/lib/dependabot/silent/file_parser.rb
silent/lib/dependabot/silent/package_manager.rb
silent/tests/testdata/vu-unsupported.txt
updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/dependabot/updater/group_update_creation.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/dependency_snapshot_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb
updater/spec/fixtures/bundler/unsupported/Gemfile
updater/spec/fixtures/bundler/unsupported/Gemfile.lock

When we parse the manifest files, if we come across an unsupported package manager version, we should immediately fail the job.
The idea is the customer will need to upgrade or remove the old manifest to get updates again. This keeps our code simple to maintain rather than trying to work around old outdated versions.
Most of this PR is implementing it in the "silent" ecosystem which is a dummy ecosystem used to test the updater.
This change will cause bundler 1 jobs to start failing with a clear error message.

raise when an unsupported package manager version is present

---

swift/Dockerfile

The Swift Project has recently released Swift 6.0, and I would like Dependabot to continue working with my projects once I have updated them to this language version.
Dependabot will be able to interact with Swift packages using the Swift 6.0 tools.

Update Swift Dockerfile to use Swift 6.0.1

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs

I'm looking at how https://github.com/dependabot/dependabot-core/issues/10260 can be fixed, but the current terminology is a little confusing; It would be good to clear this up.
The change adds documentation to clarify the scenarios where a "packages.config" update and "PackageReference" update could happen. The current terminology, "SdkPackageUpdater", gives the impression that "PackageReference" will only appear in SDK-style project files, which is not correct (see code comments).
No changes to behaviour, purely documentation.
I can easily identify which updater class is applicable to each project file format.

Rename  SdkPackageUpdater => PackageReferenceUpdater, for clarity

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackagesConfigUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

When running an update in a `packages.config` scenario, the path to the packages directory is determined from existing `<HintPath>` elements.  If the path returned looks something like `..\packages` that causes problems on non-Windows machines because the backslash is retained and ultimately the packages are restored to a directory named `..?packages` which is incorrect.
The first fix was to simply normalize this path to the Unix standard which Windows can handle just fine.
The second fix was to expand the cases where we run `nuget.exe restore` _before_ we can update the package; this happens if a package's `.targets` file is directly imported without a guarding `Condition="Exists(path)"` attribute.
This fixes some bugs seen during an internal log audit.

report unix-friendly packages path

---

nuget/helpers/lib/NuGetUpdater/Directory.Common.props

The updaters build and run in a Linux container, but I, and likely other NuGet developers, use Windows.  When investigating issues that only repro in Linux, I'll commonly use a WSL instance and VS Code to do my work, but if I have to switch back and forth between Windows and WSL, it gets painful because I have to regularly clean/rebuild the `artifacts` directory.
By adding the well-known MSBuild value `$(OS)` this makes it easier to switch.  The value itself isn't interesting, but usually evaluates to either `Windows_NT` or `Unix`.  The end result is that there are separate `bin/` and `obj/` directories for each OS so it's possible to run unit tests in both instances in the same codebase at the same time.

split artifacts on OS

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This PR is adding an MSBuild property that will prevent this [.NET SDK target](https://github.com/dotnet/sdk/blob/7ca2f7cf5dcb94cf852a964b2d003bbd4a684836/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets#L36,) to execute in order to continue getting the dependency graph.
Fixes https://github.com/dependabot/dependabot-core/issues/10117
There does not seem to be another way to avoid getting the `NETSDK1147` error.
This PR uses two specifics to get around workloads not being installed:
- It uses `DesignTimeBuild` to skip the workloads validation
- It defines a fake `TargetPlatformVersion` in order for nuget to still consider the platform-specific target frameworks.
Both tests that are added will succeed, as they reference target frameworks that require …

fix(dotnet): Ensure that packages can be updated when referencing .NET workloads

---

common/lib/dependabot/version.rb
common/spec/dependabot/version_spec.rb
maven/lib/dependabot/maven/version.rb
maven/spec/dependabot/maven/version_spec.rb
python/lib/dependabot/python/version.rb
python/spec/dependabot/python/version_spec.rb

I need to be able to get the correct lowest prerelease suffix for a version. I can then use this to build the correct version ignore ranges in dependabot core as well as dependabot API.
Currently, we have this suffix hardcoded in a few areas of the [core codebase](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/requirement.rb#L142) and [api codebase](https://github.com/github/dependabot-api/blob/main/app/actions/find_or_create_ignore_condition/ignore_condition_builder.rb#L29) . Unfortunately, this suffix is ecosystem-specific and that's why this PR adds a method to return the correct suffix in a specific ecosystem.
Once this PR get's merged I can then fix this [issue](https://github.com/dependabot/dependabot-core/issues/10798). There is already a draft …

Add lowest_prerelease_suffix method

---

maven/spec/dependabot/maven/version_spec.rb
python/lib/dependabot/python/requirement.rb
python/lib/dependabot/python/version.rb
python/spec/dependabot/python/version_spec.rb

Remove a feature flag and code that is no longer needed.
The feature flag was added in this [PR](https://github.com/dependabot/dependabot-core/pull/10613) to ensure the new python version changes could be turned off easily if necessary.
It also removes old code from the previous implementation that is no longer relevant e.g the old version regex.

Remove python_new_version feature flag and irrelevant code

---

python/lib/dependabot/python/update_checker/latest_version_finder.rb
python/spec/dependabot/python/update_checker/latest_version_finder_spec.rb

Fix [issue 10813](https://github.com/dependabot/dependabot-core/issues/10813) where a local python version like `20241015.20437.714166+master.fe8974a` is getting the plus sign replaced with a dot and, as a result, failing validation. With the [updated version regex](https://github.com/dependabot/dependabot-core/pull/10613), the plus gets parsed correctly therefore this hack is no longer necessary.
The added test will pass.

Remove replacement of plus with dot in python latest version

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/branch_namer/base.rb

This is related with https://github.com/dependabot/dependabot-core/pull/10519 , As there seems to be an issue with sending and receiving args from api, we are adding additional logs to better collect and validate data exchange between API and core.

Adds telemetry collection logs for existing branches information

---

python/lib/dependabot/python/update_checker.rb
python/lib/dependabot/python/version.rb
python/spec/dependabot/python/version_spec.rb

Issue: https://github.com/dependabot/dependabot-core/issues/10845
Backport [this fix from maven](https://github.com/dependabot/dependabot-core/pull/10664) into python. 
Though, currently, ignore conditions like ["version-update:semver-major", "version-update:semver-minor"] are working exactly like in the previous python version implementation, this is not strictly correct. Based on (the python version specification)[https://packaging.python.org/en/latest/specifications/version-specifiers], dev0 is the suffix with the lowest precedence so that's what we need to use in the ranges. Otherwise, we could end up in a situation where a dependency with version 2.9 and settings that say ignore majors could upgrade to 3.dev0 as 3.dev0 < 3.a.

Add semver ignore-condition range code into python version

---

updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb

The `lead_security_dependency` experiment is downcasing only one half of the dependency name comparison resulting in closed PRs in an ecosystem where the current packages are reported with some upper case characters, e.g., NuGet reporting `System.Text.Json` and that string not matching `system.text.json`.  The result is that the comparison on line 155 is returning `false`: `dep.name.downcase == lead_dep_name` where `lead_dep_name` comes from `security_advisory_dependency`.  The NuGet example then expands to `"system.text.json" == "System.Text.Json" # => false`.
The fix is to restore the call to `.downcase` that is present when the experiment isn't enabled.

do case-insensitive comparison for `lead_security_dependency` experiment

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/BindingRedirectsTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs

Previously when updating a package in a `packages.config` scenario with an `app.config` file, we'd update or add binding redirects for all referenced assemblies.  This was too heavy-handed, particularly when a user's `app.config` file only had a few binding redirects.  We'd then add 20+ which wasn't really what they wanted.
Another approach would be to only update existing binding redirects, but ultimately the dependabot tool is meant to help address security vulnerabilities, which might mean updating a very specific transitive dependency and if a binding redirect wasn't added, this could lead to difficult to diagnose issues at runtime with an assembly mismatch.
So the approach taken here is twofold: (1) update any existing binding redirect, and (2) add new binding redirects, but _only_ …

restrict when we add binding redirects

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Run.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/CloneCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Program.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Clone/CloneWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Clone/TestGitCommandHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/CloneWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/IGitCommandHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/ShellGitCommandHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/DependencyFileNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobRepoNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobSource.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/MarkAsProcessed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PrivateSourceAuthenticationFailure.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdateNotPossible.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/updater/main.ps1

The changes in this PR are only relevant for the long-standing work item of rewriting the NuGet updater in C#.
This PR moves the calls to `git clone ...` from the PowerShell script into C#.  The reason is that we already have much of the architecture available there to process and report errors.
We can now unit test the result of the `git clone ...` commands without actually needing to invoke the tool.
The contents of the PowerShell script were also simplified to call the new tool.
There are still two separate calls into the `NuGetUpdater.Cli` tool because that's how an update job is invoked.  One call with `fetch_files` and another with `update_files`.  This also means that we can easily  test either half in isolation; no need to perform a meaningless clone just to test the updater, and …

add explicit `clone` command for NuGet updater

---

maven/lib/dependabot/maven/update_checker/requirements_updater.rb

We're seeing the following Sorbet errors:
```
Parameter 'source_url': Expected type String, got type NilClass
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:133
Definition: /home/dependabot/maven/lib/dependabot/maven/update_checker/requirements_updater.rb:34 (Dependabot::Maven::UpdateChecker::RequirementsUpdater#initialize)
```

`source_url` in `Maven::UpdaterChecker::RequirementsUpdater` can be `nil`

---

python/lib/dependabot/python/update_checker.rb

`req_string.match(VERSION_REGEX)` returns a `MatchData` object. So when we attempt to construct a `Python::Version` object, it fails. We need to convert it to a string first.

Convert match from `MatchData` to string before creating Python version

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/RunCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestAnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestDiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestUpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/IAnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/IDiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/IUpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs
nuget/spec/dependabot/nuget/native_helpers_spec.rb

This makes testing `RunWorker.cs` much faster; approx 20s to 1s.
It also fixes some path handling on Windows machines; common for development, but not production or CI.

create interfaces for workers to make testing more direct

---

nuget/helpers/lib/NuGetUpdater/NuGetProjects/Directory.Build.props
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.CommandLine/NuGet.CommandLine.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Configuration/NuGet.Configuration.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.LibraryModel/NuGet.LibraryModel.csproj
nuget/helpers/lib/NuGetUpdater/NuGetProjects/NuGet.Packaging/NuGet.Packaging.csproj

We don't control the code in the `NuGet.Client` submodule, but we can turn off the warnings so they don't clutter the build.
There are still build warnings in the code that we _do_ control, but that's for another day.

clean up warnings from NuGet.Client submodule

---

python/helpers/lib/parser.py
python/lib/dependabot/python/file_parser/pyproject_files_parser.rb
python/lib/dependabot/python/update_checker.rb
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
python/spec/dependabot/python/update_checker_spec.rb
python/spec/fixtures/pyproject_files/table_build_system_requires.toml

This adds support for build-system requires  in pyproject.toml files.
related: #8465
Executed dry run scipt that produces this output. have used my git repo with sample pyproject.toml
bin/dry-run.rb pip gopidesupavan/workspace-poc
https://github.com/gopidesupavan/workspace-poc/blob/main/pyproject.toml
```
bin/dry-run.rb:728:in `block in <main>'
bin/dry-run.rb:620:in `each'
bin/dry-run.rb:620:in `<main>'
=> build-system: bump: bump flit-core from 1 to 3.10.1
± pyproject.toml
~~~
--- /tmp/original20241106-114043-w2gv8e     2024-11-06 17:52:24.124167518 +0000
+++ /tmp/updated20241106-114043-q7mclq      2024-11-06 17:52:24.124167518 +0000
@@ -1,5 +1,5 @@
[build-system]
-requires = ["flit_core==1"]
+requires = ["flit_core==3.10.1"]
build-backend = "flit_core.buildapi"
[project]
~~~
2 …
```

Adding support for build-system.requires in pyproject.toml

---

common/lib/dependabot/requirement.rb
updater/lib/dependabot/api_client.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/updater/group_update_refreshing.rb
updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb
updater/lib/dependabot/updater/operations/update_all_versions.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/create_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_version_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/update_all_versions_spec.rb
updater/spec/dependabot/updater_spec.rb

This PR adds functionality, controlled by the `enable_record_ecosystem_meta` feature flag, to send ecosystem metrics from `update_job` results to Dependabot-API. This allows for improved tracking of dependency updates across ecosystems, including versioning details for package managers and languages. Metrics cover raw and processed versions as well as constraints, enabling better visibility into compatibility trends.
This change is part of ongoing efforts to enhance update visibility and track deprecations across ecosystems.
The `ecosystem_data` method structures and extracts version and requirement details. Data includes nested fields, which may need flattening for Datadog compatibility. Reviewers should verify that the metric structure aligns with Dependabot-API requirements.
- …

Send Ecosystem Metrics to Dependabot-API on Update Job Completion

---

npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb

This PR fixes a bug in the `npm_and_yarn/package_manager.rb` file where an empty or undefined package manager name resulted in a `NoMethodError` (`undefined method 'to_sym' for an instance of Hash`). This error, as reported in [Sentry Issue DELTAFORCE-11XD](https://sentry.io/organizations/...), occurred when `package_manager_by_name` was called with an invalid package manager name.
The update ensures that the method handles cases of empty or invalid package manager names gracefully, preventing `to_sym` from being called on unintended data types.
To resolve this issue, the code now checks the validity of the package manager name before calling `to_sym`. Reviewers should focus on the additional validation logic to confirm that it aligns with expected behavior for handling empty or missing …

Fix bug related to empty package manager name in npm_and_yarn package manager

---

nuget/Dockerfile
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/global.json

Update .NET 8 and 9 SDKs to their latest versions - the main motivation to use a stable version of .NET 9.
No.
The build is green.

Update .NET SDKs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs

When checking if a newer package exists, we previously only checked the NuGet endpoint to see if the version is reported.  This doesn't necessarily work with an authenticated Azure DevOps feed because the version could be reported as existing, but actually attempting to download the `.nupkg` could fail because the current authentication isn't allowed to pull in the upstream package.
The fix is to try to actually download the package before we report it as a possible upgrade path.
This issue was found by manually scanning the logs from the `nuget_native_analysis` experiment.

only report a package as existing if the actual `.nupkg` can be downloaded

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This PR ensures that `corepack` is explicitly invoked when running `npm`, `pnpm`, and `yarn` commands. By calling `corepack` directly, we can guarantee that the correct package manager versions (installed via Corepack) are used for each command. This change helps prevent version mismatches and enhances consistency across different environments.
This change resolves inconsistencies in package manager versions used in different environments and addresses potential issues caused by mismatched versions.
The key change here is the addition of `corepack` to the `npm`, `pnpm`, and `yarn` command execution. This ensures that the commands run with the versions installed by Corepack. If there were multiple approaches to achieve this, I selected this one to make the execution explicit and …

Ensure Corepack Usage for npm, pnpm, and yarn Command Execution

---

pub/lib/dependabot/pub/helpers.rb
pub/spec/dependabot/pub/update_checker_spec.rb
pub/spec/fixtures/projects/can_update_with_dart_sdk_deps/pubspec.yaml

I have noticed that under certain conditions, Dependabot fails to create updates with the following logs:
```
updater | 2024/11/15 12:51:41 INFO <job_917330574> Checking if custom_lint 0.6.8 needs updating
updater | 2024/11/15 12:51:41 INFO <job_917330574> Latest version is 0.7.0
updater | 2024/11/15 12:51:41 INFO <job_917330574> Requirements to unlock update_not_possible
updater | 2024/11/15 12:51:41 INFO <job_917330574> Requirements update strategy 
2024/11/15 12:51:41 INFO <job_917330574> No update possible for custom_lint 0.6.8
```
Upon investigation, I found that the following error occurred in dependency_services internal, interrupting the update resolution. (different dependency, but same cause.)
```
Because every version of flutter from sdk depends on collection 1.18.0 and …
```

[pub] Fix update fails when project contains dependency from Dart SDK

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/PathHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs

Make file check in DiscoveryWorker case insensitive. This allows projects referenced from solution files to be found even if the case of the file path is different.
Currently we have issues where a `.sln` file references a project found on disk but we fail to discover it because the casing is different.
Fixes #10957 
The approach taken was to crawl our way through the directories while and looking for matching names on each section while ignoring casing differences.

Make DiscoveryWorker project path check case insensitive

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs

When parsing a `job.json` file, the field `$.job.debug` can appear as `null`.  This handles that.
Issue found during a manual audit of telemetry.

allow `null` when parsing `job.debug` field

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb

This PR addresses issues related to Sorbet typings in the `npm_and_yarn` ecosystem package manager. The goal is to ensure proper type safety and consistency across the codebase, reducing potential runtime errors and improving maintainability.
1. Fixed incorrect Sorbet type annotations for methods in the package manager helpers.
2. Ensured consistent handling of method signatures and parameters for all package manager classes (`NpmPackageManager`, `YarnPackageManager`, `PNPMPackageManager`).
3. Resolved errors caused by type mismatches in `installed_version`, `setup`, and other helper methods.
- Improves the robustness of type-checking in the `npm_and_yarn` ecosystem.
- Aligns method signatures with actual usage patterns in the package manager implementation.
- Review the changes to …

Fix Sorbet Typings for `npm_and_yarn` Ecosystem Package Manager and Helpers

---

go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/language.rb
go_modules/lib/dependabot/go_modules/package_manager.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/language_spec.rb
go_modules/spec/dependabot/go_modules/package_manager_spec.rb

Update the go ecosystem to add support for gathering ecosystem metrics that need to be persisted in datadog via `POST /update_jobs/:id/record_ecosystem_meta`
This is one in a series of PRs to gather ecosystem meta data and persist it in datadog. See earlier PRs for [Bundler](https://github.com/dependabot/dependabot-core/pull/10826) and [NPM](https://github.com/dependabot/dependabot-core/pull/10862)
- I'll be able to see Go ecosystem metrics in datadog

Add support for go ecosystem metrics collection

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs

When considering package updates, we call `.Distinct()` on the `string` version of the target frameworks.  These can differ by case, e.g., `net8.0` vs `NET8.0` which will result in duplicates further on in the analysis process.  These can also differ in form, but not function, e.g., `net48` vs `.NETFramework,Version=v4.8`.  Because of this the call to `.Distinct()` was moved to be after the conversion to a proper framework value.

remove duplicate TFMs when considering updates

---

common/lib/dependabot/pull_request_creator.rb
common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/branch_namer/base.rb
common/lib/dependabot/pull_request_creator/branch_namer/dependency_group_strategy.rb
common/lib/dependabot/pull_request_creator/github.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb
common/spec/dependabot/pull_request_creator/github_spec.rb

Remove the `dedup_branch_names` ff and existing_branches array
They are no longer being used
n/a
No job logs about existing branches

Remove dedup_branch_names ff and existing_branches array

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/npm8/workspace_outdated_deps_not_in_root_package_json/package-lock.json

This PR addresses general issues with npm version detection and provides a robust solution to handle version determination based on the `package-lock.json` file. It updates the `enable_corepack_for_npm_and_yarn` feature by setting the default npm version to 10 when the feature flag is enabled. Previously, the default npm version was set to 8. This update ensures compatibility with the latest npm features while solving broader problems related to npm version detection.
- To address inconsistencies in detecting the installed npm version across different lockfile scenarios.
- To align with the latest npm version (10) for improved functionality and support.
- To provide a seamless user experience by handling various edge cases, including missing or malformed lockfiles.
- The new method …

Set Default `npm` Version to 10 Under enable_corepack_for_npm_and_yarn Feature Flag

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb

Fixing an issue where running **npm 9** or **npm 10** caused a downgrade of the `package-lock.json` lockfile version when subdependencies were updated. The existing npm version check was specific to **npm 8**, leading to incorrect behavior for **npm >= 9**.
This update ensures compatibility for npm versions **8**, **9**, and **10**, treating them equally in the conditional logic for subdependency updates.
Bug Issue: [dependabot-core/#10982](https://github.com/dependabot/dependabot-core/issues/10982)
- The logic has been adjusted to include all **npm versions >= 8**. This required reviewing how the `run_npm8_subdependency_update_command` method is triggered and modifying the conditional checks to account for npm versions **8**, **9**, and **10**.
- Special attention was given to ensure …

Fix: Ensure Compatibility with npm >= 8 to Prevent Lockfile Downgrades

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs

When attempting to perform an update, we currently can't do it if we detect a difference in the peer dependencies.  Eventually this is a situation that should be solvable, but since it's currently not, it's better to gracefully exit the updater instead of throwing an error.
This is currently one of the biggest error traces in the telemetry.

gracefully exit if we can't solve an issue with peer dependencies

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/LinuxOnlyAttribute.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/PathHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathHelper.cs

After a previous change we encountered issues when trying to resolve paths with different casing. The previous implementation assumed only one path would match after doing a case-insensitive search. We later encountered a case where there was more than one match. 
The revised version returns a list of a strings (paths) and then changes the discovery worker to be case-sensitive and loop over the found paths.

Handle paths with multiple case-insenstive matches on disk.

---

common/lib/dependabot/requirement.rb
common/spec/dependabot/requirement_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb

This PR adds the ability to extract and report package manager version constraints for `npm`, `pnpm`, and `yarn` from the `engines` field in the `package.json` manifest file.
By including these constraints, the ecosystem metrics now provide better visibility into the range of supported package manager versions used in projects.
This PR enhances ecosystem metrics tracking for the `npm_and_yarn` ecosystem by introducing package manager version requirement collection and normalization for `npm`, `pnpm`, and `yarn`.
- Review the extraction logic for the `engines` field to ensure it handles constraints properly for `npm`, `pnpm`, and `yarn`.
- Validate that the conversion logic accurately transforms raw versions like `1.3.4` into `=1.3.4`.
- Consider edge cases where the `engines` field may …

Add `npm_and_yarn` package managers' requirements to ecosystem metrics

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/language_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb

This PR adds functionality to detect and include the language name (`Node.js`) and its version for `npm`, `pnpm`, and `yarn` package managers. 
**Why?**
- To accurately identify the runtime environment (`Node.js`) by using `node -v` to fetch the version directly.
- This ensures dependency updates are handled with the correct language version context, improving reliability in JavaScript-based ecosystems.
This change improves Dependabot's ability to work with JavaScript projects by explicitly detecting and documenting Node.js as the runtime language and its version.
---
- The implementation uses the `node -v` command to fetch the Node.js version at runtime. This approach is simple, reliable, and avoids relying on indirect metadata (e.g., `volta` or `engines.node`).
- Test coverage ensures …

Store Language Name, Version, and Requirements for `npm`, `pnpm`, and `yarn`

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Rel : https://github.com/github/dependabot-updates/issues/7169
Root cause of above issue is `yarn add/upgrade <package-name>@version` is failing
Creating a cache folder under .yarn file fixes this issue.
I have ran the cli against [the repo where I recreated the error](https://github.com/dsp-testing/yarn_monorepo_core) and solved it by this update.
I have ran the cli against [the repo where I recreated the error](https://github.com/dsp-testing/yarn_monorepo_core) and solved it by this update.

Running `yarn install` before running the update checkoer

---

python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/package_manager.rb
python/spec/dependabot/python/peotry_package_manager_spec.rb
python/spec/dependabot/python/pip_compile_package_manager_spec.rb
python/spec/dependabot/python/pip_package_manager_spec.rb
python/spec/dependabot/python/pipenv_package_manager_spec.rb
python/spec/dependabot/python/poetry_package_manager_spec.rb

**Fix:** Enables metric collection for `pip-compile` and `pipenv`
Enhancements to package manager detection:
Also enables local python setup for correct detection of `pip-compile`, `poetry` and `pipenv` based of python version

Python metric collection

---

hex/lib/dependabot/hex/file_parser.rb
hex/lib/dependabot/hex/language.rb
hex/lib/dependabot/hex/package_manager.rb
hex/spec/dependabot/hex/file_parser_spec.rb
hex/spec/dependabot/hex/language_spec.rb
hex/spec/dependabot/hex/package_manager_spec.rb

Update the hex / elixir ecosystem to add support for gathering ecosystem metrics.
- I'll be able to see hex / elixir ecosystem metrics in datadog

Add support for hex ecosystem metrics collection

---

gradle/lib/dependabot/gradle/file_parser.rb
gradle/lib/dependabot/gradle/language.rb
gradle/lib/dependabot/gradle/package_manager.rb
gradle/spec/dependabot/gradle/file_parser_spec.rb
gradle/spec/dependabot/gradle/language_spec.rb
gradle/spec/dependabot/gradle/package_manager_spec.rb

Update the Gradle ecosystem to add support for gathering ecosystem metrics.
As agreed at standup, in this PR, I'm returning `jvm_based_languages` as the language name. In addition, NOT-AVAILABLE is being returned for the language and gradle versions as there is no consistent way to extract this data based on the Gradle dependency file alone. In future, we might be able to improve on this but that will have to await the completion of [install Gradle on docker images](https://github.com/github/dependabot-updates/issues/7534).
- I'll be able to see Gradle ecosystem metrics in datadog

Add support for gradle ecosystem metrics collection

---

python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/package_manager.rb
python/lib/dependabot/python/update_checker.rb

We are not able to see `pipenv` package manager in metric collection, experimenting if reordering package manager as per `update checker` resolves this issue. 
Adds more telemetry data to verify python version that is coming up in metric.

Reorders package managers for python ecosystem metric collection

---

common/lib/dependabot/ecosystem.rb
devcontainers/lib/dependabot/devcontainers/file_parser.rb
devcontainers/lib/dependabot/devcontainers/language.rb
devcontainers/lib/dependabot/devcontainers/package_manager.rb
devcontainers/spec/dependabot/devcontainers/file_parser_spec.rb
devcontainers/spec/dependabot/devcontainers/language_spec.rb
devcontainers/spec/dependabot/devcontainers/package_manager_spec.rb

Update the devcontainers ecosystem to add support for gathering ecosystem metrics.
- I'll be able to see devcontainers ecosystem metrics in datadog

Add support for devcontainers ecosystem metrics collection

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestLogger.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/ShellGitCommandHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DotNetToolsJsonDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/GlobalJsonDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/PackagesConfigDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Files/JsonBuildFile.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/FrameworkChecker/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/DotNetToolsJsonUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/GlobalJsonUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/LockFileUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ConsoleLogger.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/DependencyConflictResolver.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ILogger.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/NuGetHelper.cs

Replace `logger.Log(...)` with `logger.Info(...)`, etc. where the formatting matches the messages produced by the Ruby logger call `Dependabot.logger.info(...)`.  This is to ensure consistent log messages, no matter what code produced it.
There were also a few instances of `Console.WriteLine` that were replaced with the appropriate `logger` call.

align C# log messages with Ruby

---

common/lib/dependabot/registry_client.rb
common/spec/dependabot/registry_client_spec.rb

Adding a retry interval to registry client Excon GET requests to better handle transient socket EOF errors affecting Maven and Terraform dependency updates by spacing out retry attempts.
The change spaces out retry attempts by 5 seconds, working with Excon's default of 4 retries for idempotent requests. This should help prevent rapid consecutive failures while still maintaining the existing retry behavior.
* Error rate monitoring shows reduction in EOFError failures
* Failbot metrics confirm retried requests succeed

Adding retries interval to registry client

---

git_submodules/lib/dependabot/git_submodules/file_parser.rb
git_submodules/lib/dependabot/git_submodules/package_manager.rb
git_submodules/spec/dependabot/git_submodules/file_parser_spec.rb
git_submodules/spec/dependabot/git_submodules/package_manager_spec.rb

Update the git-submodules ecosystem to add support for gathering ecosystem metrics.
These metrics don't include language information because language does not seem to be applicable to git-submodules.
- I'll be able to see git-submodules ecosystem metrics in datadog

Add support for git-submodules ecosystem metrics collection

---

nuget/lib/dependabot/nuget/analysis/analysis_json_reader.rb
nuget/lib/dependabot/nuget/native_discovery/native_discovery_json_reader.rb
nuget/lib/dependabot/nuget/native_update_checker/native_update_checker.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb
nuget/spec/dependabot/nuget/file_updater_spec.rb
nuget/spec/dependabot/nuget/update_checker_spec.rb

A recent PR wrote discovery JSON files to `/tmp` but telemetry is reporting that sometimes an expected file is missing.  This appears in the logs as:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/.dependabot/discovery.1.json
```
Ultimately, I don't know exactly what's happening, but here's a guess.
1. An update job consists of [two processes](https://github.com/dependabot/cli/blob/4e7612fe884683ade8c54ad8fd137fc6da92bb84/internal/infra/run.go#L422): `bin/run fetch_files` and `bin/run update_files`.
2. The recent PR (#11026) writes discovery JSON files during the `fetch_files` step to `/tmp/.dependabot/dependabot*`.
3. That same PR then reads those discovery files during the `update_files` step.
According to the logs, all instances of `discovery.1.json` not being found …

store discovery files under $HOME so they're not cleaned up by the OS

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/native_discovery/native_discovery_json_reader.rb
nuget/script/run

Despite a recent PR, it still seems possible for the discovery JSON files to go missing between `fetch_files` and `update_files`.
This PR allows the update job to continue by re-running discovery if necessary, but also logs in several locations what discovery files were produced so we can hopefully figure out where they're going.  Re-running discovery is faster the second time because packages have already been downloaded and only adds 30s or so to the update.
I manually verified the re-run behavior works by manually deleting the discovery JSON files between `fetch_files` and `update_files` and the appropriate errors were reported and discovery was re-run and the update job completed as expected.

allow discovery to re-run if files are missing; log errors

---

go_modules/Dockerfile

As per [this discussion](https://github.com/github/dependabot-updates/issues/5945#issuecomment-2518096628) 
we are removing [this environment variable](https://github.com/dependabot/dependabot-core/blob/main/go_modules/Dockerfile#L31C1-L36C26) as it is misleading the developers and it does not add any values.
Based on [this request](https://github.slack.com/archives/C01BKB7EVQX/p1733357921734009?thread_ts=1733334587.468269&cid=C01BKB7EVQX)
Removing unused and misleading environment variable
As per the [discussion here](https://github.com/git-lfs/git-lfs/issues/2406)

Cleaning up lfs environment variable as it is not being used

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackagesConfigUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ProjectHelper.cs

Found during a manual scan of the logs.
When determining if a `.csproj` has an assembly reference to a package, an incorrect assumption was made that the name of the assembly would match the name of the package, but that's not correct.
The correct behavior is to match the `HintPath` with the package name, because that will always match.  We had an existing regular expression that did the correct matching, so this was lifted higher in the class so it could be re-used.

allow for differing package and assembly names when finding packages path

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TemporaryDirectory.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/CompatabilityChecker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/NuGetContext.cs

NuGet package analysis needs to download the packages to examine the dependencies.  This was previously done with `$TMP` but that could result in duplicate package downloads, using extra network bandwidth as well as disk space.
In the worst case scenario, the initial package would be downloaded to 2 places on disk and the updated package would be downloaded to 3.  E.g., if updating `Newtonsoft.Json` from `11.0.1` to `13.0.1` there would be 1 copy of `Newtonsoft.Json/11.0.1` in `$TMP` and 1 copy in the global package cache.  There would then be 2 copies of `Newtonsoft.Json/13.0.1` in `$TMP` and 1 in the global package cache.  With these changes there is now only 1 copy of `11.0.1` and 1 copy of `13.0.1`, both in the global package cache.  Assuming a similar size between different versions …

download nuget packages to well-known location

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/file_parser.rb
nuget/lib/dependabot/nuget/native_discovery/native_discovery_json_reader.rb
nuget/script/run

Clean up log messages added in #11055.
Originally the log messages were to debug why a file generated during `fetch_files` wasn't present for the subsequent call to `update_files`.  I've since learned that in certain instances, update jobs can run those two commands in separate containers with no shared filesystem.
The fix to re-run discovery if needed is still the correct choice, so this only backs off the logging.
Recent telemetry shows that re-running the discovery has fixed the original issue.

remove unnecessary log messages

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/lib/dependabot/terraform/package_manager.rb
terraform/lib/dependabot/terraform/version.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/dependabot/terraform/package_manager_spec.rb

Update the terraform ecosystem to add support for gathering ecosystem metrics.
These metrics don't include language information because language does not seem to be applicable to git-submodules.
- I'll be able to see terraform ecosystem metrics in datadog

Add support for terraform ecosystem metrics collection

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/RequirementConverter.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Condition.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

This is part of the work to enable the end-to-end NuGet updater purely in C#.
This adds parsing for the job file's `ignore-conditions` property and passes those values through to the analyzer worker.
Since the end-to-end updater is not enabled, the only part of this code that will see production currently is the new parsing of the `Condition` type.  I modelled this after the [relevant type](https://github.com/dependabot/cli/blob/4e7612fe884683ade8c54ad8fd137fc6da92bb84/internal/model/job.go#L92) in the CLI.

parse and honor `ignore-conditions` from job file

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb

This PR implements a fallback mechanism for situations where Corepack fails to install a specified package manager version, typically due to private registry issues. 
The fallback ensures that:
1. The system-installed version of the package manager is detected.
2. Corepack prepares and activates this version for use.
This change improves reliability and ensures seamless dependency management even when registry issues occur.
- The approach prioritizes simplicity by leveraging existing system-installed versions of package managers.
- Is there any potential edge case that might require additional validation (e.g., missing binaries or incompatible versions)?
- Logging has been added to trace both installation and fallback processes—feedback on log clarity is welcome.
- The fallback mechanism …

Add fallback to local package manager when Corepack installation fails

---

docker/lib/dependabot/docker/file_parser.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/fixtures/kubernetes/yaml/with_bom.yaml

If a YAML file was saved with the encoding "UTF-8 with BOM" and parsed, only the first property will be reported, ignoring the rest of the file and ultimately resulting in no images found and nothing updatable.
This PR explicitly detects the byte order mark and reports `DependencyFileNotParseable` with a message so the user can correct it.
Bug was found during internal investigations.

detect byte order mark in YAML and report error

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/PathHelperTests.cs
nuget/script/ci-test
nuget/updater/common.ps1
nuget/updater/main.ps1
nuget/updater/test-data/global-json-discovery-2-values/global.json
nuget/updater/test-data/global-json-discovery-2-values/src/global.json
nuget/updater/test-data/global-json-discovery-none/src/.gitignore
nuget/updater/test-data/global-json-discovery-root-no-file/.gitignore
nuget/updater/test-data/global-json-discovery-root-with-file/global.json
nuget/updater/test.ps1

For the eventual end-to-end C# NuGet updater, a PowerShell script is used to crawl the directories for `global.json` files for SDK installation prior to the job running.  This PR makes that behavior testable and fixes a bug where this logic would previously throw when trying to navigate past the update root directory.

make directory crawling unit-testable

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Run.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Advisory.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/AllowedUpdate.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/CommitOptions.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/DependencyGroup.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/GroupPullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/RequirementsUpdateStrategy.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/VersionConverter.cs

The job deserializer had a bunch of `string`, `object`, etc. for properties that we don't yet use.
This PR adds concrete types for everything in the job file so it'll be usable when necessary.  The shape of the job file was pulled from [the CLI](https://github.com/dependabot/cli/blob/4e7612fe884683ade8c54ad8fd137fc6da92bb84/internal/model/job.go) as well as [this repo](https://github.com/dependabot/dependabot-core/blob/fa9831f094e1a575ace3444769de7e57bee4f5a2/updater/lib/dependabot/job.rb).

add concrete types to job deserializer

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs

When asked if we supported a certain scenario, I couldn't find a test that did exactly this, but it _is_ supported so this just adds a test.
The scenario is the `<PackageReference>` element existing in a non-standard `.targets` file with the `Version` property as a sub-element.

add missing test for scenario

---

composer/lib/dependabot/composer/file_parser.rb

This PR addresses an issue where Dependabot Core attempts to use Composer v1, which has been deleted. The problem occurs because the unsupported error is not being thrown properly. As a result, the system attempts to invoke Composer v1, leading to failures such as:
```
php -d memory_limit=-1 /opt/composer/v1/bin/run
```
**Why:**  
Composer v1 is no longer supported, and Dependabot Core should ensure the unsupported error is thrown correctly to prevent attempts to use it. This fix will enforce the proper handling of unsupported versions and redirect processes as required.
---
- The issue lies in the error-handling logic for Composer v1. The changes ensure that unsupported versions throw appropriate errors to prevent execution.  
- Reviewers may want to double-check areas where the …

Fix Composer v1 Unsupported Error Handling in Dependabot Core

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.DotNetToolsJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.DotNetTools.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/JsonHelper.cs

Fixes #11050. The error was being thrown when trying to parse a JSON file with trailing commas. This PR adds an argument to the parser to allow trailing commas in JSON as well as the corresponding tests in the Updater and the Discovery.

Add argument to parser to allow trailing comma in json.

---

swift/lib/dependabot/swift/file_parser.rb
swift/lib/dependabot/swift/language.rb
swift/lib/dependabot/swift/package_manager.rb
swift/lib/dependabot/swift/version.rb
swift/spec/dependabot/swift/file_parser_spec.rb
swift/spec/dependabot/swift/language_spec.rb
swift/spec/dependabot/swift/package_manager_spec.rb

Update the swift ecosystem to add support for gathering ecosystem metrics.
- I'll be able to see swift ecosystem metrics in datadog

Add support for swift ecosystem metrics collection

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Analyze.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Discover.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/AnalyzeCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/RunCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/lib/dependabot/nuget/update_checker.rb

The `discover` and `update` NuGet tool commands both have a `--job-path` argument so that the current set of experiments can be parsed.
This PR adds the same behavior to the `analyze` command.  We don't yet need the experiments for this command, but we will soon so this is front loading some of the work.

pass job file path to analyze command

---

composer/lib/dependabot/composer/update_checker/latest_version_finder.rb
composer/spec/dependabot/composer/update_checker/latest_version_finder_spec.rb

Ref: https://github.com/github/dependabot-updates/issues/7609
Throwing an appropriate error, when private registry response with 200 status and empty array response.
Used Dependabot::PrivateSourceAuthenticationFailure error message for this failure
Ran the dependabot client and confirmed `The error no implicit conversion of String into Integer` is not there.

Throwing an appropriate error, when private registry response with 200 status and empty array response

---

python/helpers/requirements.txt

PR https://github.com/dependabot/dependabot-core/pull/11079 is failing because of grouping. Not sure grouping is mandatory.

Bump poetry version from 1.8.3 to 1.8.5

---

python/Dockerfile
python/lib/dependabot/python/language_version_manager.rb

This PR bumps the latest Python version to 3.12.7 (the latest stable 3.12.* release - [link](https://www.python.org/doc/versions/)).
Fix https://github.com/dependabot/dependabot-core/issues/10830

chore(python): Target latest Python 3.12 version to 3.12.7

---

.github/dependabot.yml

Composer 1 was removed in:
* https://github.com/dependabot/dependabot-core/pull/10934
But we've still got a Dependabot job looking for PHP dependencies in the V1 folder, which no longer exists.
So delete that job.

Stop checking for Composer 1 dependencies

---

npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/npm_package_manager_spec.rb

Add changes to set NPM v6 as deprecated and unsupported. The deprecation warning and unsupported error are controlled by the following feature flags:
- `npm_v6_deprecation_warning`
- `npm_v6_unsupported_error`
Feature Flags PR: https://github.com/github/dependabot-api/pull/5763
This mirrors the approach used for Bundler v1 and composer 1, allowing us to guide users towards migrating to NPM v9 while providing a controlled rollout.
The deprecation and unsupported checks for NPM v6 are controlled by feature flags. Please focus on verifying that the logic tied to the feature flags works as expected.
We will monitor logs and metrics to ensure:
- NPM v6 users see the deprecation warning when the feature flag is enabled.
- Actions using NPM v6 are blocked when the unsupported error flag is …

Add support for NPM V6 deprecation warning and unsupported error

---

npm_and_yarn/Dockerfile
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

I'm debugging in this area, and want to make sure I'm working off the latest upstream changes.

Bump yarn to 4.5.3

---

terraform/lib/dependabot/terraform/file_parser.rb
terraform/lib/dependabot/terraform/file_selector.rb
terraform/spec/dependabot/terraform/file_parser_spec.rb
terraform/spec/fixtures/projects/child_module_with_no_source/main.tf
terraform/spec/fixtures/projects/child_module_with_no_source/override.tf

When the config file is overridden, the code should process it and find the missing key values from the base file.
Ref : https://developer.hashicorp.com/terraform/language/files/override
Wrote an rspec test to check if the overridden module does not include the source. And ensured that when there is a property present in both then overridden value is present in the dependency set.

If overridden file exists, then process it and find the missing key values from base file.

---

docker/lib/dependabot/docker/file_fetcher.rb
docker/spec/dependabot/docker/file_fetcher_spec.rb
docker/spec/fixtures/github/contents_docker_repo_multiple.json

`Containerfile` is a thing.

---

common/lib/dependabot/command_helpers.rb
common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/command_helpers_spec.rb
common/spec/dependabot/shared_helpers_spec.rb
common/spec/fixtures/commands/error.sh
common/spec/fixtures/commands/error_hang.sh
common/spec/fixtures/commands/no_timeout.sh
common/spec/fixtures/commands/output_hang.sh
common/spec/fixtures/commands/success.sh
common/spec/spec_helper.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
updater/spec/dependabot/dependency_snapshot_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_version_update_pull_request_spec.rb

This PR introduces a timeout mechanism for running helper subprocesses to ensure they do not run indefinitely, enhancing system stability and robustness. The change is gated behind the **feature flag**: `enable_shared_helpers_command_timeout`.
---
- Added the `capture3_with_timeout` method to manage subprocess execution with a configurable timeout.  
- Integrated the timeout mechanism into the `run_helper_subprocess` method by replacing the existing `Open3.capture3` call with `capture3_with_timeout`.  
- Set the default timeout for helper subprocesses to 120 seconds to prevent indefinite blocking.  
**Note**: The timeout applies to **the time between** outputs to `stdout` or `stderr`, **not the overall execution duration of the command**. Each time the command produces output, the timeout …

WIP: Set timeout for helper subprocesses to enhance stability

---

common/lib/dependabot/command_helpers.rb
common/lib/dependabot/shared_helpers.rb

The purpose of this change is to increase the default timeout for helper subprocess commands from 2 minutes to 15 minutes. This adjustment is intended to address cases where the previous timeout was insufficient for certain processes, causing premature failures.
This update aims to ensure that helper subprocess commands have adequate time to complete under normal conditions, reducing the likelihood of timeout-related errors.
- This is a global change to the default timeout value for helper subprocess commands. Reviewers should evaluate whether the new timeout value is appropriate across all use cases.
- If there are scenarios where the longer timeout could cause issues, alternative solutions (e.g., a configurable timeout) might be considered.
- Timeout-related errors for helper subprocess …

Increase default timeout for helper subprocess commands from 2 minutes to 15 minutes

---

common/lib/dependabot/errors.rb
github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/spec/dependabot/github_actions/file_parser_spec.rb
github_actions/spec/fixtures/workflow_files/unresolved_version.yml

Improves error handling by raising a clear `UnresolvableVersionError` error when dependencies lack version constraints, rather than failing with a generic Sorbet error. This helps users understand exactly which dependencies are failing.
Chose to fail fast during parsing rather than proceeding with dependencies that are not semver. This provides clearer feedback and prevents Sorbet from raising confusing type errors later in the update process.
When the parse method correctly identifies dependencies without versions and raises an `UnresolvableVersionError` rather than a Sorbet issue message.

Improve error handling for missing dependency versions for github actions

---

npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb

This PR is a follow up to  [add support for NPM V6 deprecation warning and unsupported error](https://github.com/dependabot/dependabot-core/pull/11112). Basically, I'm trying to show warnings to the user if they are still using NPM v6 which has been deprecated and will soon no longer be supported. In the earlier PR (https://github.com/dependabot/dependabot-core/pull/11112) some setup code was missing so the warnings and errors could not successfully trigger. This PR fixes that.
We will monitor logs and metrics to ensure:
- NPM v6 users see the deprecation warning when the feature flag is enabled.
- Actions using NPM v6 are blocked when the unsupported error flag is enabled.
- Tests have been added to validate the behaviour of both feature flags.
- [ x I have thoroughly tested my code …

Return deprecated version if user requests it so that we can trigger warning or logging

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/DependencyConflictResolver.cs

When trying to update a top level dependency instead of pinning a transitive dependency, don't report the transitive version as a possible solution for the top level package.
This required an update to a test where the minimum version of a dependency doesn't exist.  To get around this, the test was updated to use faked local packages with the correct versions.  Issue #11150 was filed for the future work.

don't use transitive dependency version as top level version

---

nuget/helpers/lib/NuGetUpdater/.editorconfig
nuget/helpers/lib/NuGetUpdater/Directory.Build.props
nuget/script/ci-test

The NuGet updater already enforces code formatting as a CI check, but this ensures the formatting failures are raised as errors in the build and appear in the IDE.  This makes finding and fixing them much easier so a CI cycle isn't wasted.
~~This PR contains a temporary commit that introduces a formatting error to verify the CI fails as expected.  Onec verified this commit will be removed.~~
Temporary commit resulted in the expected build error in CI.

elevate formatting issues to build failure

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs

Looking through the logs I see some failures in the `analyze` command, but that part of the code is only set up to handle `private_source_authentication_failure` so this will explicitly report the exception text.
There will certainly be more fixes coming, but this should put the exception text and call stack in the telemetry.

capture and report analyzer failures

---

python/lib/dependabot/python/language.rb
python/spec/dependabot/python/language_spec.rb

Adds changes to set python 3.8 as deprecated and eventually unsupported. The deprecation warning and unsupported error are controlled by the following feature flags:
- `python_3_8_deprecation_warning`
- `python_3_8_unsupported_error`
Feature Flags PR: https://github.com/github/dependabot-api/pull/5763
This mirrors the approach used for Bundler v1, composer 1 etc allowing us to guide users towards migrating to python 3.13 while providing a controlled rollout.
We will monitor logs and metrics to ensure:
- Python 3.8 users see the deprecation warning when the feature flag is enabled.
- Actions using python 3.8 are blocked when the unsupported error flag is enabled.
- Tests have been added to validate the behaviour of both feature flags.

Add support for python 3.8 deprecation warning and unsupported error

---

python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/package_manager.rb
python/spec/dependabot/python/file_parser_spec.rb

Fixed issue where we were not able to capture pip-compile package manager in metric collection.

Fixes pip-compile file matcher for metric collection

---

common/lib/dependabot/notices.rb
common/spec/dependabot/notices_spec.rb
updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/notices_helpers.rb
updater/spec/dependabot/notices_helpers_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb

We already have a feature to display deprecation notices for package managers. These can be warnings for deprecated package managers or errors for unsupported package managers. We now have a new use case: displaying similar notices but for language deprecations.
This PR generalises the code for package manager notices so that it can be used for language deprecations as well. In most cases this just involves passing in a new optional param `version_manager_type` in method calls and using it to generate the correct notice messages. To minimise the number of changes and to reduce the risk of breaking existing functionality, this param has a default value of `:package_manager.
Code comments, method arguments and variable names have also been updated accordingly so that they make sense for …

Add support for language deprecation notices, warnings and errors

---

common/lib/dependabot/ecosystem.rb
github_actions/lib/dependabot/github_actions.rb
github_actions/lib/dependabot/github_actions/constants.rb
github_actions/lib/dependabot/github_actions/file_fetcher.rb
github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/lib/dependabot/github_actions/file_updater.rb
github_actions/lib/dependabot/github_actions/metadata_finder.rb
github_actions/lib/dependabot/github_actions/package_manager.rb
github_actions/lib/dependabot/github_actions/update_checker.rb
github_actions/spec/dependabot/github_actions/file_parser_spec.rb
github_actions/spec/dependabot/github_actions/package_manager_spec.rb
updater/lib/dependabot/api_client.rb
updater/spec/dependabot/api_client_spec.rb

This PR implements package manager support for GitHub Actions workflows. 
The goal is to enhance ecosystem compatibility and streamline dependency management within GitHub Actions workflows.
- The `github_actions` package manager does not include versioning. Therefore, we are currently adding only the `package_manager` field into the ecosystem structure to maintain consistency across ecosystems.
- The package manager will initialize correctly for GitHub Actions workflows.
- Metrics related to the `github_actions` update process will be available in the metrics collection.

Add Package Manager for GitHub Actions

---

python/lib/dependabot/python/language.rb
python/spec/dependabot/python/language_spec.rb

Fix a bug where we compare a python version in major.minor.patch format against a list of python versions in major.minor format to check whether the version is deprecated. For example, 3.8.20 was coming up as not deprecated because we were comparing it against `[3.8]`. My solution is to only use the major.minor version to check deprecation status.
I'll see a language deprecation warning, in the logs, for a repo with a python version greater than 3.8 but less than 3.9

[BUG FIX] Only use the major.patch version to check deprecation status

---

.github/workflows/images-latest.yml

I noticed on a recent commit to `main` on my personal fork that it's trying/failing to push images to GHCR due to permissions errors: https://github.com/jeffwidman/dependabot-core/actions/runs/12593801189
There's no point in forks doing that--they will never have the proper permissions to publish images to the real GitHub GHCR Dependabot image.
We already prevent forks from trying to publish the base updater image here: https://github.com/dependabot/dependabot-core/blob/53178c5d340c7fcb171d5aec7e640d350f3f837c/.github/workflows/images-updater-core.yml#L14
We just forgot to also do it in this workflow for the final ecosystem images.
So this rectifies that.

Prevent forks from trying (and failing) to push latest images to GHCR

---

.github/workflows/images-branch.yml

I found the original code confusing because it _always_ checks if the PR is approved, even when run on forks. Yet the job still bails if run on a fork, _even if the PR is approved_.
So I pulled the `if` conditional that bypasses forks up into the first job. This works because if the `approval` job gets skipped, then the subsequent job will also be skipped since it `needs: approval` ([docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds)).
So this should hopefully be both more readable within the code, more readable in CI output on PR's, and also more performant. 🥂 
Originally, I wasn't 100% sure this works... perhaps there was a reason why the fork-check conditional needed to be attached to the second job.
However, when I checked …

Skip earlier when run on forks

---

.github/dependabot.yml

We grouped the Python PR's to avoid noise. However, what I've observed in practice is we (and our users) care more about staying up to date on the package managers and not so much if the internal libraries used in our helpers stay up to date.
So by breaking the package managers themselves out as distinct groups, it allows us to quickly move forward on those, without getting blocked if there's a breaking change in a minor helper library.
Here's an example of exactly this problem:
* https://github.com/dependabot/dependabot-core/pull/11107#issue-2735504252

Treat Python Package managers as distinct groups

---

.github/workflows/images-branch.yml

When running this workflow manually (signalled via the `workflow_dispatch` event), we need to ensure that we are operating on commits that have been reviewed/approved. This is a safety measure to prevent:
1. Accidental pushes that might cause bugs.
2. Malicious pushes that might do nefarious things.
I considered implementing this by re-checking for approval at the time we checkout the code, but because the `gh` call to check for approval is a separate call from the checkout, we will always need to do this SHA comparison to avoid a race. So the simplest thing was to memoize the SHA as part of the output from the first job and avoid another `gh` call.
Lastly, this validation relies on `Dismiss stale pull request approvals when new commits are pushed` being set in the repo settings. It's …

Ensure additional commits after approval are rejected

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/package_manager.rb
docker/spec/dependabot/docker/docker_package_manager_spec.rb
docker/spec/dependabot/docker/file_parser_spec.rb

Adds Metric collection for _docker package manager_

Adds metric collection support for Docker 

---

bundler/lib/dependabot/bundler/file_parser.rb
bundler/lib/dependabot/bundler/package_manager.rb
bundler/spec/dependabot/bundler/package_manager_spec.rb
common/spec/dependabot/ecosystem_spec.rb
common/spec/dependabot/notices_spec.rb
common/spec/dependabot/requirement_spec.rb
common/spec/spec_helper.rb
updater/spec/dependabot/notices_helpers_spec.rb

This PR updates the handling of deprecation and unsupported checks for Bundler by ensuring that `detected_version` is consistently used instead of `raw_version`. 
This change improves the accuracy of deprecation notices and resolves edge cases where `raw_version` is either `nil` or different from the `detected_version`. It also refines the notice generation and logging behavior to handle all scenarios correctly.
**Why?**
- To ensure the consistency and correctness of version checks across Dependabot's ecosystem.
- To fix potential issues with mismatched version usage in deprecation and unsupported logic.
- To enhance the reliability and clarity of notices for deprecated and unsupported versions.
---
- The logic in `unsupported?` and related methods was updated to handle cases where …

Update Bundler deprecation unsupported check to use detected version

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.GlobalJson.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/WebApplicationTargetsConditionPatcher.cs

Previously we'd only filter out an imported project if its path was _exactly_ `$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets`, however in looking through the logs I've also seen instances of `$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets` so I've simply expanded the pattern to match on any import with a file name of `Microsoft.WebApplication.targets`.
While working on this I also found that if a test does fail, it's not reported in the log very well, so I've addressed that.  With this additional fix, I found 2 unit tests that had some merge conflict artifacts.  These tests were expected to fail, just not in the way that they were, so they've now been fixed to fail in the expected way again.

expand pattern to filter out `Microsoft.WebApplication.targets`

---

python/lib/dependabot/python/file_parser.rb
python/lib/dependabot/python/language.rb
python/lib/dependabot/python/language_version_manager.rb
python/spec/dependabot/python/language_spec.rb

This PR updates the detection logic for Python 3.8 to ensure that `detected_version` is consistently used across the deprecation and unsupported checks. 
This change addresses scenarios where `raw_version` is either `nil` or diverges from `detected_version`, improving the reliability of version checks and the accuracy of deprecation and unsupported notices for Python.
**Why?**
- To align the detection and handling of Python versions with `detected_version` as the authoritative source.
- To resolve inconsistencies and potential errors when `raw_version` is `nil` or different from `detected_version`.
- To ensure a consistent and reliable experience for Dependabot users managing Python dependencies.
---
- The `unsupported?` and related methods have been updated to prioritize …

Update Python 3.8 Detection Logic to Use Detected Version

---

common/lib/dependabot/file_fetchers/base.rb
common/lib/dependabot/workspace/git.rb
common/spec/dependabot/file_fetchers/base_spec.rb
common/spec/dependabot/workspace/git_spec.rb

The output from this command is used to set the base commit SHA in some scenarios.  For repos like https://github.com/GoogleCloudPlatform/agent-assist-integrations where the default/base branch is named `HEAD`, the output includes a warning.  This ends up causing issues downstream where Dependabot assumes the string `warning: refname 'HEAD' is ambiguous.\n<sha>` only contains a commit SHA.
```
➜  agent-assist-integrations git:(heads/HEAD) cd .git
➜  .git git:(heads/HEAD) git rev-parse HEAD
warning: refname 'HEAD' is ambiguous.
5abcecddb18427d227ee56c9c1a06cbe5f63e70f
```
The warning is output to stderr while the SHA is output to stdout, so a quick fix to bypass this error case is to not capture stderr in the returned command output.
I don't think there's any case for running this command …

Drop warnings from output of `git rev-parse HEAD`

---

composer/Dockerfile

Clean up missed composer v1 artifacts

Remove composer v1 from Dockerfile

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

When reporting missing files from MSBuild, we previously only supported one error message pattern:
```
The imported project "<some-path>" was not found
```
but I've discovered that another pattern can occur:
```
The imported file "<some-path>" does not exist
```
This PR expands that pattern to report a missing file instead of getting classified as `unknown_error`.

expand pattern to report missing files

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/language_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/npm_package_manager_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_helper_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/pnpm_package_manager_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_package_manager_spec.rb

This PR updates the handling of deprecation and unsupported checks for the `npm_and_yarn` ecosystem's package managers: `npm`, `pnpm`, and `yarn`.
The changes include:
- Implementing a unified and comprehensive version detection mechanism for `npm` that prioritizes checking the `packageManager` field, `engines`, and lockfiles in that order to determine the version.
- Refining deprecation and unsupported logic for `npm` to ensure alignment with the ecosystem's requirements.
- Ensuring `pnpm` and `yarn` consistently return `false` for deprecation and unsupported checks, as no such logic applies to them.
**Why?**
- To improve consistency and accuracy in how version detection and deprecation/unsupported checks are performed across package managers.
- To address gaps in version detection by …

Update `npm_and_yarn` deprecation and unsupported checks for `npm`, `pnpm`, and `yarn` package managers

---

common/lib/dependabot/errors.rb
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Analyze.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Discover.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/AnalyzeCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/CloneCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/DiscoverCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/RunCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Clone/CloneWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/ExpectedDiscoveryResults.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/RequirementConverter.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/BadRequirementException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/CloneWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ErrorType.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/NuGetUpdater.Core.csproj
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/BadRequirement.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/DependencyFileNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobRepoNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PrivateSourceAuthenticationFailure.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdateNotPossible.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/lib/dependabot/nuget/native_helpers.rb

The `job.json` file is passed to all update steps which means we need to be able to report all parsing errors as they occur.
Originally this work started because a requirement was specified in the job file that could not be parsed, so part of this PR is to return the well-known error `illformed_requirement`, represented as `BadRequirementError`.
Most of this PR was to make testing possible, but ultimately it comes down to 2 major changes:
1. For the current hybrid Ruby/C# updater, only validate and report job file parsing errors in the `discover` command.  All subsequent commands also parse the job file, but any failure to parse is fatal so we only need to actually report it there; all other instances can assume it's acceptable.
2. For the new end-to-end updater, the `clone` command is …

capture and report job deserialization errors

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/ProjectHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/ProjectHelper.cs

It's possible for a C# project to contain both SDK-style refernces (via `<PackageReference .../>` elements) as well as `packages.config`.  Previously only the `packages.config` style references would be considered if there were no SDK-style references.
This PR allows both to exist and merges the results, including the `AdditionalFiles` property.

merge SDK and packages.config references in discovery

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/CommitOptions.cs

Despite the CLI claiming that the job property [`commit-message-options.include-scope` is a `string` pointer](https://github.com/dependabot/cli/blob/4e7612fe884683ade8c54ad8fd137fc6da92bb84/internal/model/job.go#L133), in reality it's [serialized and used as a `bool`](https://github.com/dependabot/dependabot-core/blob/be5f774e7b9a86976b5d8e88db7aea25641e4bd3/common/lib/dependabot/config/update_config.rb#L105).  This PR just fixes that issue and updates a test to reflect job files seen in the wild.
Issue found by looking through the logs after recent error reporting improvements.

change type of property `job.commit-message-options.include-scope` to `bool`

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Looking through the logs I found an instance where we weren't detecting an unauthorized package feed.

expand pattern to report unauthorized feed

---

python/lib/dependabot/python/file_parser.rb
python/spec/dependabot/python/file_parser_spec.rb
python/spec/fixtures/requirements/malformed_markers.txt

Sentry Issue: https://github.sentry.io/issues/6202418024/?project=1451818&referrer=github_integration
Github Issue: https://github.com/github/dependabot-updates/issues/8056
```
NoMethodError: undefined method `captures' for nil
python/lib/dependabot/python/file_parser.rb:341:in `evaluate_condition'
python/lib/dependabot/python/file_parser.rb:328:in `marker_satisfied?'
python/lib/dependabot/python/file_parser.rb:310:in `blocking_marker?'
python/lib/dependabot/python/file_parser.rb:257:in `block in requirement_dependencies'
python/lib/dependabot/python/file_parser.rb:254:in `each'
...
(26 additional frame(s) were not displayed)
```
For some python requirements.txt files with markers, the marker condition is malformed, causing the `captures` method to be called on a `nil` object.
There is an …

Handle calling captures method on nil

---

updater/lib/dependabot/job.rb

Add a comment to hint why we clean the directories.
This serves as a code hint to anyone working on that section of code that they need to be careful about security implications.
Paths with `../..` are normalized in Core, so the Dependabot Core library cannot access directories outside of the project.
The new code comment is present.

Add a comment to hint why we clean directories

---

composer/Dockerfile
composer/helpers/v1/build
composer/helpers/v1/composer.json
composer/helpers/v1/composer.lock
composer/helpers/v1/src/UpdateChecker.php
composer/helpers/v2/composer.lock
composer/spec/dependabot/composer/file_parser_spec.rb
composer/spec/dependabot/composer/file_updater/lockfile_updater_spec.rb
composer/spec/dependabot/composer/file_updater_spec.rb
composer/spec/dependabot/composer/update_checker_spec.rb
composer/spec/fixtures/projects/autoload/composer.lock
composer/spec/fixtures/projects/subdependency_update_required/composer.json
composer/spec/fixtures/projects/subdependency_update_required/composer.lock
composer/spec/fixtures/projects/v1/pear/composer.lock
composer/spec/fixtures/projects/v1/plugin/composer.json
composer/spec/fixtures/projects/v1/plugin/composer.lock
python/lib/dependabot/python/update_checker/poetry_version_resolver.rb
python/spec/dependabot/python/update_checker/poetry_version_resolver_spec.rb

We are currently on `7.4` which has been EOL'd by upstream in Nov 2022:
* https://www.php.net/eol.php
* https://www.php.net/supported-versions.php
There is no newer version of the `7.x` series, so we have to bump to the `8.x` series.
Fix: https://github.com/dependabot/dependabot-core/issues/6527
Fix: https://github.com/dependabot/dependabot-core/issues/6958

Bump `php` to `8.2`

---

npm_and_yarn/lib/dependabot/npm_and_yarn/bun_package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/language.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/npm_package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/pnpm_package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/yarn_package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/bun_package_manager_spec.rb

As a first step towards adding support for Bun we are adding the `BunPackageManager` class and extracting package managers into their own files.
- This is the first part of merging the changes suggested in https://github.com/dependabot/dependabot-core/pull/11209 in digestible PRs.
- Contributes to #6528 
For wider context you can check https://github.com/dependabot/dependabot-core/pull/11209 or https://github.com/dependabot/dependabot-core/pull/11248
The ultimate plan is to use a new structure for multiple Javascript ecosystems similar to https://github.com/dependabot/dependabot-core/pull/1862.
This PR was put together before the change in approach. It was decided that we proceed with these PR's as-is.
We will then follow-up with a PR migrating to the new structure. This migration PR will …

Add bun package manager

---

common/lib/dependabot/errors.rb
github_actions/lib/dependabot/github_actions/file_parser.rb
github_actions/spec/dependabot/github_actions/file_parser_spec.rb
github_actions/spec/fixtures/workflow_files/unresolved_version.yml

Reverts dependabot/dependabot-core#11144
Temporarily reverting as this causing more issues than it solves.

Revert "Improve error handling for missing dependency versions for github actions"

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb

This change resolves an issue in PNPM dependency parsing where main dependencies with specifiers were not prioritized, leading to errors or unexpected behavior. By prioritizing main dependencies with `specifiers` in the lock file, the parser ensures that the main dependency node is retained, while transitive dependencies are grouped under `all_versions`. This directs the update process to correctly assess the vulnerability status of the main dependency.
The behavior is controlled by the feature flag `enable_fix_for_pnpm_no_change_error`, which ensures the changes are incremental and non-disruptive for other use cases.
This addresses the "no change" error in PNPM dependency processing, which occurred because main dependencies with specifiers were not prioritized, causing the update process …

Fix PNPM Dependency Parsing Error by Prioritizing Main Dependencies

---

updater/config/.npmrc

Whilst working on adding the Bun package manager an issue was surfaced related to a custom cert used for NPM 6.
This PR removes the `calfile` from `.npmrc`.
See https://github.com/dependabot/dependabot-core/pull/11209
NPM 6 is no longer supported.
No functional changes are observed.

Remove `cafile` hack used for NPM 6

---

npm_and_yarn/spec/npm_and_yarn_config_spec.rb

This is a follow-up to https://github.com/dependabot/dependabot-core/pull/11302
It seems that this spec should have failed, but it didn't because CI used a cached docker container.
The spec is now redundant as we have removed the assignment for the NPM 6 `cafile` in `.npmrc`.
We can recreate the issue:
1. On the `main` branch run `bin/docker-dev-shell npm_and_yarn --rebuild`
2. Run the spec in the container `cd npm_and_yarn && rspec ./spec/npm_and_yarn_config_spec.rb`
3. The spec should fail ❌ 
4. Revert the commit fromhttps://github.com/dependabot/dependabot-core/pull/11302, `git revert cf69f2537e5fab87a40acdeaad362d7a84042da6`
6. Run `bin/docker-dev-shell npm_and_yarn --rebuild`
7. Run the spec in the container `cd npm_and_yarn && rspec ./spec/npm_and_yarn_config_spec.rb`
8. The spec …

Remove the check for the NPM 6 `cafile` in `.npmrc`

---

python/lib/dependabot/python/file_updater/requirement_replacer.rb
python/spec/dependabot/python/file_updater/requirement_replacer_spec.rb

adds error handler error while resolving the dependency version updates

Fixes [weekly 1.5k] [pip] missing key authority error issues

---

common/lib/dependabot/errors.rb
silent/tests/testdata/vu-group-semver-error.txt
updater/lib/dependabot/update_files_command.rb
updater/spec/dependabot/update_files_command_spec.rb

Handle a DependencyFileNotParseable error when running the Updater so that this error doesn't get propagated up the chain as an unknown error. It also won't appear in Sentry once it's been handled correctly.
We are already handling the exception on line https://github.com/dependabot/dependabot-core/blob/main/updater/lib/dependabot/update_files_command.rb#L27 and this just reapplies the same logic.
The Sentry issue specified above should cease to appear.

Handle DependencyFileNotParseable error on Updater.run

---

python/helpers/lib/parser.py
python/helpers/requirements.txt
python/spec/dependabot/python/file_parser/pyproject_files_parser_spec.rb
python/spec/fixtures/pyproject_files/pyproject_1_0_0.toml
python/spec/fixtures/pyproject_files/pyproject_1_0_0_nodeps.toml
python/spec/fixtures/pyproject_files/pyproject_1_0_0_optional_deps.toml

This is a fix for issue #10523 (and possibly others). We use [`tomli`](https://github.com/hukkin/tomli) instead of the outdated [`toml`](https://github.com/uiri/toml) package because the former has full TOML `1.0.0` support.
The change is minimal and should not break anything, since the only thing that changes is the TOML parsing function.
https://github.com/dependabot/dependabot-core/blob/127a9586156843c68bfd2e1897365d288e0ffe07/python/helpers/lib/parser.py#L27
The above is replaced by this:
```python
with open(pyproject_path, "rb") as file:
project_toml = tomli.load(file)
```
The requirements and comments are adjusted accordingly.
I suppose it could be a topic of discussion, which third-party TOML parsing library is best to use, while support for older Python version is not dropped. But …

Fix TOML parsing in Python ecosystem (fixes #10523)

---

nuget/updater/common.ps1

The SDK installer wasn't actually verifying that the property `$globalJson.sdk.version` is present.  This would have broken the install step a few lines down.

do null check before attempting to install sdk

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Advisory.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

Also consider a security advisory's explicit safe versions when evaluating package updates.
The lambda version filter was rewritten to make it easier to read and debug because there are several places to set a breakpoint.  The only functional change is the additional explicit check in the `SafeVersions` property at the end.
The run worker was also updated to generate the correct `DependencyInfo` object from the `SecurityAdvisory`s from the job file.
Fixes #11311.

prefer `SafeVersions` property when considering other versions

---

common/lib/dependabot/errors.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/bun_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This change introduces handling for the `NoChangeError` that occurs during transitive dependency updates specifically in the `pnpm` package manager. 
When certain conditions are met, the code raises a new error, `ToolFeatureNotSupported`, indicating that updating transitive dependencies is not supported in `pnpm`. 
This logic is gated behind the `enable_fix_for_pnpm_no_change_error` feature flag to allow for controlled testing and adoption.
This change ensures improved error feedback for unsupported scenarios in `pnpm`, reducing unknown failures.
---
The error is raised **only for `pnpm`** when **all** of the following conditions are true:
1. The `enable_fix_for_pnpm_no_change_error` feature flag is enabled.
2. The project includes a `pnpm-lock.yaml` file.
3. The `dependencies` array is …

Handle `NoChangeError` for Transitive Dependency Updates in `pnpm` Package Manager Behind Feature Flag

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb

This PR fixes the issue where the `pnpm` update command was being executed incorrectly as `pnpm pnpm update...`. The duplicate `pnpm` in the command caused errors and prevented updates from running as expected.
This fix ensures that the correct `pnpm update` command is used, improving the reliability of dependency updates for projects using `pnpm`.
- Fixes the incorrect execution of the `pnpm` update command.
- Resolves errors and unexpected behavior caused by running `pnpm pnpm update`.
---
- This change specifically targets `pnpm` and ensures compatibility with its expected behavior for dependency updates.
- Please confirm that no other areas of the code rely on the incorrect `pnpm pnpm update` pattern.
---
- Verifying that the corrected `pnpm update` command runs successfully without …

Fix `pnpm` Update Command to Address Dependency Update Issues

---

hex/Dockerfile
hex/helpers/lib/run.exs
hex/spec/dependabot/hex/file_parser_spec.rb

This bumps Elixir to 1.17.3
There's only one required change here to switch the IO.read mode.

Bump Hex Elixir to 1.17.3

---

hex/Dockerfile
hex/spec/dependabot/hex/file_parser_spec.rb

This makes Elixir current.
I included the OTP bump because it had no alterations besides version numbers.
This enables the #11295 changes.
Only minor change required for 1.18.1 was re-ordering within the Dependabot::Dependency.requirements inside of a test. Hope that's fine.

Bump Hex OTP to 26, Elixir to 1.18.1

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

Reverts dependabot/dependabot-core#11322
As per the discussion on 17/01/2025 Friday discussion, I am reverting back this changes.
Removing corepack from cli command

Revert "Revert "Removing corepack usage from else clause""

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Fixing the Bug related to [this workflow](https://github.com/dsp-testing/pnpm-monorepo-7659)
Error:
```
updater | 2025/01/20 14:45:53 ERROR <job_950629041> Error during file fetching; aborting: Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`.
updater | 2025/01/20 14:45:53 ERROR <job_950629041> Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`.
updater | 2025/01/20 14:45:53 ERROR <job_950629041> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/psych-5.1.2/lib/psych/visitors/to_ruby.rb:432:in `visit_Psych_Nodes_Alias'
```
Wrote new rspec to test pnpm-workspace-yaml 
`rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb:2024`
nil scenario `rspec …

Enabling alias parsing in pnpm_workspace_yaml

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/fixtures/projects/yarn/workspace_requirements_catalog/package.json

When updating individual repositories within a monorepo using the `directory` configuration, we want to skip the `catalog:` protocol. This change improves the handling of monorepo dependency updates by ensuring Dependabot correctly processes directory-specific updates without being affected by the catalog protocol.
The main change focuses on the protocol handling logic. I chose to skip the catalog protocol specifically for directory updates since these are meant to operate on isolated parts of the repository, and the catalog protocol isn't necessary in this context. This approach ensures clean, targeted updates for individual packages within monorepos.
Users can successfully process updates for specific directories in their monorepo. The "no change" errors previously triggered by catalog …

Skip catalog protocol when using directory configuration in monorepos

---

common/lib/dependabot/errors.rb
devcontainers/spec/dependabot/devcontainers/file_parser_spec.rb
pub/lib/dependabot/pub/helpers.rb
pub/spec/dependabot/pub/update_checker_spec.rb

Replace Dependabot::DependabotError in pub/lib/dependabot/pub/helpers.rb with more meaningful error so that errors that don't need to be in Sentry don't end up there.

Handle Dependabot::DependabotError in pub/lib/dependabot/pub/helpers.rb

---

bin/dry-run.rb
common/lib/dependabot/file_fetchers/base.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

The previous implementation was incorrect. This PR correctly sets the `:enable_beta_ecosystems` experiment state. We are also removing the more specific `:bun_updates` feature as it is now redundant.
This is a follow-up/fix for [Handle enable_beta_ecosystems boolean setting #11334](https://github.com/dependabot/dependabot-core/pull/11334)
```bash
./bin/docker-dev-shell npm_and_yarn --rebuild
./bin/dry-run.rb npm_and_yarn dsp-testing/dependabot-bun-public --enable-beta-ecosystems
```
<details>
<summary>Expected output</summary>
```
=> bump @types/bun from 1.1.16 to 1.1.18
± bun.lock
~~~
--- /tmp/original20250122-2574-6rmd3r       2025-01-22 11:34:43.796832648 +0000
+++ /tmp/updated20250122-2574-1wx5kf        2025-01-22 11:34:43.796832648 +0000
@@ -2,10 +2,9 @@
"lockfileVersion": 0, …
```

Update use of the `enable_beta_ecosystems` experiment

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/helpers_spec.rb

`corepack` [does not](https://github.com/nodejs/corepack/issues/295) support the `bun` package manager. We will use the `fallback_to_local_version` by default for `bun`.
GitHub actions are failing due to the use of `corepack` for `bun`.
This wasn't surfaced by the dry-run as the `package_manager_install` and `package_manager_activate` are not invoked by the `dry-run`.
We should be able to create PRs in https://github.com/dsp-testing/dependabot-bun-public for bun.

Don't use corepack for bun

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/spec/dependabot/bundler/file_updater/ruby_requirement_setter_spec.rb

Adds error handler for Ruby version not found class so that they don't end up being in Sentry.
```
Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound: Dependabot::Bundler::FileUpdater::RubyRequirementSetter::RubyVersionNotFound
bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:65:in `ruby_version'
bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:33:in `rewrite'
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb:262:in `block in lock_ruby_version'
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb:260:in `each'
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb:260:in `lock_ruby_version'
```
...
(50 additional frame(s) were not displayed)

Adds error handler for Ruby version not found class error

---

python/lib/dependabot/python/file_parser/pipfile_files_parser.rb

Added sorbettype check as strict for python/lib/dependabot/python/file_parser/pipfile_files_parser.rb
It should pass all the test cases and post deployment it should not break.

Added sorbettype check as strict

---

python/lib/dependabot/python/file_parser.rb

Fix an incorrect sorbet type in dependabot/python/file_parser.rb that's causing the following error in Sentry:
```
Return value: Expected type T::Boolean, got type NilClass
Caller: /home/dependabot/python/lib/dependabot/python/file_parser.rb:258
Definition: /home/dependabot/python/lib/dependabot/python/file_parser.rb:307 (Dependabot::Python::FileParser#blocking_marker?)
```

Fix sorbet type in dependabot/python/file_parser.rb

---

npm_and_yarn/lib/dependabot/npm_and_yarn/bun_package_manager.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/bun_package_manager_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/package_manager_detector_spec.rb

Package manager detector was defaulting to the [DEFAULT_PACKAGE_MANAGER](https://github.com/dependabot/dependabot-core/blob/535799dd68a47cd686e8205e59f9754e4b4730c3/npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb#L105) of `npm` when we using the `bun` package manager.
We encounter a `tool_version_not_supported ` error in the dependabot workflow [run](https://github.com/dsp-testing/dependabot-bun-public/actions/runs/12927975464/job/36054271621).
We can test with https://github.com/dsp-testing/dependabot-bun-public

Update `PackageManagerDetector` for bun

---

common/lib/dependabot/errors.rb

The NuGet updater can raise a `PrivateSourceAuthentication` error during a fetch operation.  This PR adds that error to the list of known errors in the `fetcher_error_details` function.

report `private_source_authentication_failure` during fetch

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Adds error handlers for major exceptions in the `go_modules` package.

Fixes part of [4.8k weekly] [go_modules] go_modules exceptions

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatedDependencyListTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

This PR only updates the end-to-end NuGet updater which is not yet used in production.
It allows updates to happen on both top-level _and_ transitive dependencies.  The result is a scenario that the hybrid Ruby/C# updater can't handle, but the end-to-end updater can.
The test has a dependency reported from three locations:
1. As a top-level dependency - up to date.
2. As a top-level dependency - needs update.
3. As a transitive dependency - needs pinning.
The hybrid updater can only update scenario 2 and misses the transitive dependency.

run full updater on all dependencies, including transitives

---

hex/helpers/lib/parse_deps.exs
hex/spec/dependabot/hex/file_parser_spec.rb

Mix.Dep.Converger.converge can raise exceptions, which then leak the exception into IO as non-encoded binary.
Basically, since we now encode/decode base64, anything non base64 is going to fail.
I unskipped the skipped test. It was failed in CI due to the `requirements` array being sorted inconsistently, but I ran it ~45 times locally and it passed every time.

Hex: Encode exceptions

---

bundler/lib/dependabot/bundler/file_parser/file_preparer.rb
bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb

Add sorbet type checking to bundler/file_updater/gemspec_sanitizer.rb
Tests on CI should remain green and no new issues should appear in Sentry

Add sorbet type checking to bundler/file_updater/gemspec_sanitizer.rb

---

bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb

Fix the sorbet typing error below:
```
Parameter 'node': Expected type T.nilable(T.any(Parser::AST::Node, String, Symbol)), got type Integer with value 3
Caller: /home/dependabot/bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb:232
Definition: /home/dependabot/bundler/lib/dependabot/bundler/file_updater/gemspec_sanitizer.rb:227 (Dependabot::Bundler::FileUpdater::GemspecSanitizer::Rewriter#replace_json_parses)
```
Instead of typing a node as `T.nilable(T.any(Parser::AST::Node, String, Symbol))`, we'll use the previously defined ParserNode type which is an alias of `T.nilable(T.any(Parser::AST::Node, String, Symbol, String, Integer, Float))`. This will correctly handle parse tokens that are symbols, strings or integers.

Fix sorbet tying error in bundler/file_updater/gemspec_sanitizer.rb

---

npm_and_yarn/Dockerfile
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/bun_lock.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser/lockfile_parser_spec.rb
npm_and_yarn/spec/fixtures/projects/bun/simple_v1/bun.lock
npm_and_yarn/spec/fixtures/projects/bun/simple_v1/package.json

`bun.lock` files generated by `bun@1.2` will have a `lockfileVersion` value `1`.
Part of https://github.com/dependabot/dependabot-core/issues/6528
Support for `lockfileVersion = 1` was requested [here](https://github.com/dependabot/dependabot-core/issues/6528#issuecomment-2612360621) and [here](https://github.com/dependabot/dependabot-core/issues/6528#issuecomment-2612470807).
We will be able to generate dependabot PRs when the `lockfileVersion` value is `1`.

Allow lockfileVersion not equal to zero

---

npm_and_yarn/lib/dependabot/npm_and_yarn.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/yarn_error_handler_spec.rb

Adds error handler for YN0086 error type

Fixes [weekly 1.2k] [npm_and_yarn] YN00xx errors 

---

maven/lib/dependabot/maven/update_checker/version_finder.rb
maven/spec/dependabot/maven/update_checker/version_finder_spec.rb

Adds more suitable error handler for **_Excon_** type registry failure errors.

Fixes [weekly 5k] [maven] Excon error ending up as unknown errors

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb

Allows overwriting the read and open timeout values for interactions with the docker registry using two separate environment variables
I do not have any issue in the tracker, but I noticed this need while using `dependabot-core` with slow private registries
Initially, I considered using the existing environment variables defined here : 
https://github.com/dependabot/dependabot-core/blob/c95a0fcfe208bc516441aa0b15e17401ac08a1b6/common/lib/dependabot/clients/github_with_retries.rb#L13-L14
But I noticed that the default values there are different and I figured that separate environment properties may be better

feat: add option to overwrite Docker read and open timeout values

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdateAllowedTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

The new C# end-to-end updater will need to be able to determine if an update is appropriate to run.  This was accomplished by re-implementing (in a way that makes sense specifically for NuGet) the `job.allowed_update?` function.  The existing Ruby unit tests were copied where appropriate.
This code is not currently on a code path that is getting executed, but will be once we enable the new updater.
The only real change to `RunWorker.cs` was adding the new function `IsUpdateAllowed()`; the large diff is because a redundant `if` block was removed.  I recommend ignoring whitespace when reviewing that file.

both job and dependency are considered for update eligibility

---

python/lib/dependabot/python/file_updater/pipfile_preparer.rb

Fixed sorbet types as strict for Python Module

Fixed sorbet types as strict for Python Module

---

common/lib/dependabot/errors.rb
devcontainers/spec/dependabot/devcontainers/file_parser_spec.rb
updater/lib/dependabot/api_client.rb
updater/spec/dependabot/api_client_spec.rb

Handle the error below:
```
Dependabot::ApiError
{"errors":[{"status":400,"title":"Bad Request","detail":"The request contains invalid or unauthorized changes"}]}
dependabot-updater/lib/dependabot/api_client.rb in block in create_pull_request at line 44
```
so that it no longer appears in Sentry.
The above response is returned from dependabot-api `UpdateJobs::CreatePullRequest.handle_invalid_dependency_files ` when the dependency files are invalid. There's not much we can do to prevent this API error but we need to handle it correctly so that it doesn't appear in Sentry as an `Unknown Error`.
The above error won't appear in Sentry anymore.

Raise DependencyFileUnsupported error when API returns matching 400 error

---

bundler/lib/dependabot/bundler/file_updater/gemspec_dependency_name_finder.rb

Fix the Sentry error below:
```
Parameter 'node': Expected type T.nilable(T.any(Parser::AST::Node, String, Symbol)), got type Integer with value 2
Caller: bundler/lib/dependabot/bundler/file_updater/gemspec_dependency_name_finder.rb:46
Definition: bundler/lib/dependabot/bundler/file_updater/gemspec_dependency_name_finder.rb:41 (Dependabot::Bundler::FileUpdater::GemspecDependencyNameFinder#find_dependency_name_node)
```
There shouldn't be any Sentry errors related to the `GemspecDependencyNameFinder` class.

Fix erroring sorbet types in gemspec_dependency_name_finder.rb

---

updater/lib/dependabot/dependency_snapshot.rb
updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb
updater/spec/dependabot/dependency_snapshot_spec.rb
updater/spec/dependabot/updater/operations/refresh_group_update_pull_request_spec.rb
updater/spec/fixtures/bundler_multiple_groups/original/Gemfile
updater/spec/fixtures/bundler_multiple_groups/original/Gemfile.lock
updater/spec/fixtures/bundler_multiple_groups/updated/Gemfile
updater/spec/fixtures/bundler_multiple_groups/updated/Gemfile.lock
updater/spec/fixtures/job_definitions/bundler/version_updates/group_update_refresh_multiple_groups_unchaged.yaml
updater/spec/fixtures/rubygems-versions-a.json

Prevent [this issue](https://github.com/dependabot/dependabot-core/issues/11372), which, in summary:
- When a dependency is in 1 PR, but according to dependabot, it could be in multiple PRs (not in practice because 1 group specifies major and 1 is minor), it incorrectly closes the PR and that dependency won't return to any PR without manual intervention
I added an optional param to `mark_group_handled` called `excluding_dependencies`, which should work as advertised, and will avoid the exclusion if the dependency is in an existing PR. Also, this should maintain current behavior of closing a PR when a dep exists in more than 1 PR.
I only used this optional param in [RefreshGroupUpdatePullRequest](https://github.com/judocode/dependabot-core/blob/03138322048d002e9b285b1a3660490a1f6e2646/updat …

Do not close a PR when it supersedes other groups

---

common/lib/dependabot/errors.rb
docker/lib/dependabot/docker/update_checker.rb

Adds error handlers for bad response while accessing private registries

Fixes [weekly 1.3k] [docker] RestClient::ServerBrokeConnection and related errors

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Examined some logs for `unknown_error` and found some more regex patters to report a better error.

expand patterns for unpossible updates

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs

Experiment names in `job.json` can be either snake case or kebab case.  Previously only snake case was supported, but this PR supports the alternate, too.
Inspiration taken from [here](https://github.com/dependabot/dependabot-core/blob/fa20d494ab21ac1ace2ab1b4be01b3a251e544b1/updater/lib/dependabot/job.rb#L127).

allow alternate experiment names

---

npm_and_yarn/lib/dependabot/npm_and_yarn/constraint_helper.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/constraint_helper_spec.rb

This PR improves version constraint handling by adding explicit support for `latest`. While we previously handled the wildcard (`*`), `latest` was not recognized separately. This update ensures `latest` correctly resolves to the newest available version.
- Adds explicit handling for the `latest` constraint.  
- Ensures `latest` resolves to the newest available version.  
- Improves consistency in version resolution logic.
- This change introduces `LATEST_REGEX` to distinguish `latest` from other constraints.  
- Please verify that the behavior aligns with expected package manager resolution.
- Tests confirm `latest` resolves correctly to the newest available version.  
- No regressions in existing wildcard (`*`) or constraint handling.  
---

Add Support for `latest` Constraint in Version Detection

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/fixtures/projects/pnpm/catalog_monorepo/apps/auth-proxy/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/catalog_monorepo/package.json
npm_and_yarn/spec/fixtures/projects/pnpm/catalog_monorepo/pnpm-lock.yaml
npm_and_yarn/spec/fixtures/projects/pnpm/catalog_monorepo/pnpm-workspace.yaml
npm_and_yarn/spec/fixtures/projects/pnpm/catalog_prettier/pnpm-lock.yaml

Fix a bug where PNPM workspace catalogs were being removed from lockfiles during dependency updates. This happened because where were not referencing the `pnpm-workspace.yaml` file when running updates to the lockfiles.
- Simplified how workspace content is passed to lockfile updater
- Removed unnecessary `is_catalog` flag
- Directly pass `@updated_pnpm_workspace_content` to maintain catalog entries
- PNPM lockfiles update catalog entries after updates

fixing pnpm catalogs being removed from lockfile during update

---

common/lib/dependabot/errors.rb
python/lib/dependabot/python/file_updater/poetry_file_updater.rb
python/spec/dependabot/python/file_updater/poetry_file_updater_spec.rb

Fix the Sentry error below:
**RuntimeError**: python/lib/dependabot/python/file_updater/poetry_file_updater.rb in updated_pyproject_content
Content did not change!
I have added a new error type: DependencyFileContentNotChanged to the errors.rb file. This will replace the current runtime error that is polluting Sentry. I'll be adding this error on the API repo as well.
This error won't appear in Sentry anymore.

Handle `Content did not change!` in poetry_file_updater.rb 

---

npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb

The `fetch_files` phase was failing due to a Corepack installation issue with `pnpm`. The error stemmed from an inability to verify the package manager's signature when installing `pnpm@9.15.5`. This caused the entire process to fail.  
This PR addresses the issue by activating the local package manager as a fallback when Corepack installation fails. This ensures that Dependabot can proceed with file fetching even if Corepack encounters verification issues.
---
- The fallback mechanism was chosen to prevent hard failures during `pnpm` installation and instead allow Dependabot to use an already available version.  
- If there are concerns about security implications, we can discuss alternative solutions, such as stricter validation checks before activating the fallback.  
---
- Dependabot …

Fix Corepack install failure by activating local package manager fallback

---

javascript/lib/dependabot/javascript.rb

When splitting up PRs for the introduction of the bun ecosystem we missed a required file in the first [PR](https://github.com/dependabot/dependabot-core/pull/11445).
Resolves #11483 
The dry run script should no longer raise an error when it encounters the line `require "dependabot/javascript"` in `bin/dry-run.rb:114`.
```bash
[dependabot-core-dev] ~ $ ./bin/dry-run.rb 
usage: ruby bin/dry-run.rb [OPTIONS] PACKAGE_MANAGER REPO
--provider PROVIDER          SCM provider e.g. github, azure, bitbucket
--dir DIRECTORY              Dependency file directory
--branch BRANCH              Repo branch
--dep DEPENDENCIES           Comma separated list of dependencies to update
--cache STEPS                Cache e.g. files, dependencies
--write                      Write the update to the cache …
```

Add required javascript file to fix dry run script

---

terraform/lib/dependabot/terraform/registry_client.rb

Strict type `Dependabot::Terraform::RegistryClient`

Strict type `Dependabot::Terraform::RegistryClient`

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/composer_error_handler_spec.rb

Adds error handlers for various composer errors including _private source authentication failures_, i_nvalid requirements_ in manifest files, and _bad response_ errors.

Fixes [weekly 1.5k] [composer] Helper-Subprocess-Errors

---

sorbet/config

Update the Sorbet ignore list with the new ecosystems created since the last Sorbet config update.
These files are omitted from the Sorbet reports.

Update sorbet ignore list with new ecosystems

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb

Fix the following type of Sentry error:
```
go: governor imports
governor/app/bootstrap imports
governor/app/providers/pub_sub imports
governor/rpc/governor/v1: package governor/rpc/governor/v1 is not in std (/home/dependabot/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/governor/rpc/governor/v1)
```
This is a user error that occurs when a package is not being referenced correctly. We can't resolve it on our end so we just need to raise the appropriate error so that it stops appearing in Sentry as an unknown error.
There shouldn't be any new occurrences of this issue in Sentry once this fix has been deployed.

Handle import error when a package is referenced incorrectly

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/TargetFrameworkReporter.targets
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Dependabot runs in a Linux container so a TFM like `net8.0-windows` needs some special handling.
The core of the fix was adding `<EnableWindowsTargeting>true</EnableWindowsTargeting>` when doing direct TFM detection and the rest is a big cleanup and simplification as well as more testing.
Fixes #11506

improve TFM discovery when targeting Windows

---

hex/Dockerfile

ESL's version of erlang didn't include arm packages, and also is slightly behind in versions compared to RabbitMQ's erlang version.

Switch Hex erlang package provider

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/TestApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/ClosePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PullRequestExistsForLatestVersion.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/SecurityUpdateNotNeeded.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdatePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/IApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/script/run

In preparation of future work, this adds some PR management message types to the end-to-end NuGet updater.  No functional change.

add pr management message types to NuGet updater

---

bin/dry-run.rb
javascript/lib/dependabot/bun.rb
javascript/lib/dependabot/bun/file_parser/bun_lock.rb
javascript/lib/dependabot/bun/update_checker.rb
javascript/lib/dependabot/bun/update_checker/conflicting_dependency_resolver.rb
javascript/lib/dependabot/bun/update_checker/latest_version_finder.rb
javascript/lib/dependabot/bun/update_checker/library_detector.rb
javascript/lib/dependabot/bun/update_checker/requirements_updater.rb
javascript/lib/dependabot/bun/update_checker/subdependency_version_resolver.rb
javascript/lib/dependabot/bun/update_checker/version_resolver.rb
javascript/lib/dependabot/bun/update_checker/vulnerability_auditor.rb
javascript/lib/dependabot/javascript/file_fetcher.rb
javascript/lib/dependabot/javascript/native_helpers.rb
javascript/lib/dependabot/javascript/package_name.rb
javascript/lib/dependabot/javascript/update_checker/dependency_files_builder.rb
javascript/lib/dependabot/javascript/update_checker/registry_finder.rb

The final step in enabling the bun ecosystem is to register the bun package manager.
Follows https://github.com/dependabot/dependabot-core/pull/11445, https://github.com/dependabot/dependabot-core/pull/11446, https://github.com/dependabot/dependabot-core/pull/11508, and https://github.com/dependabot/dependabot-core/pull/11521
This approach is quite coarse and will be revisited. To facilitate the expedient release of the bun ecosystem we have moved required files directly under the `Dependabot::Bun` namespace. Later when more other `javascript` ecosystems move we can properly organise the shared code.
We can test with `dry-run`:
`./bin/dry-run.rb bun dsp-testing/dependabot-bun-public  --updater-options=enable_bun_ecosystem --enable-beta-ecosystems`
<details>
<summary>Click to expand …

Register the bun package manager

---

composer/lib/dependabot/composer/file_parser.rb
composer/spec/dependabot/composer/file_parser_spec.rb
composer/spec/fixtures/projects/local_package_as_dep/composer.json
composer/spec/fixtures/projects/local_package_as_dep/composer.lock

Excludes local and non-updatable packages from the dependency list when updating Composer dependencies.

adds experiment to exclude local and non updatable packages

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatedDependencyListTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/PathComparer.cs

Update is for the non-yet-running end-to-end updater.
Instead of performing updates by project then by dependency, invert that to update by dependency then by project.  This is more in line with the current updater and makes the future work of generating a PR description easier.
This includes sorting the reported dependencies where before it was discover order.  This will make all future reporting more deterministic.

group update operations by dependency name

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

A private package source might not contain the `Microsoft.Windows.App.Ref` package so only set `EnbleWindowsTargeting` when the TFM explicitly contains the string `-windows`.

don't unnecessarily require windows app ref package

---

cargo/Dockerfile
go_modules/Dockerfile
python/Dockerfile

Fixing the FromAsCasing warning that I found in the python docker build.

FromAsCasing error fixes.

---

bun/spec/dependabot/bun/file_updater_spec.rb
javascript/spec/dependabot/javascript/bun/file_updater_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/bun_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This change removes the `enable_fix_for_pnpm_no_change_error` feature flag from **dependabot-core** and **dependabot-api**, making the logic always behave as if the flag were enabled. This simplifies the code and ensures the fix is always applied.
The feature flag is no longer needed as the fix is stable, and removing it helps streamline the codebase.
- The removal of the feature flag is straightforward, but please review to ensure no unintended dependencies remain.
- All conditional checks for this flag have been removed or modified to assume it is always `true`.
- All related tests should pass without issues.
- The expected behavior (previously gated by the feature flag) should now be the default behavior.
- Code should be simpler and easier to maintain without feature flag …

[Feature Flag] - Remove `enable_fix_for_pnpm_no_change_error` Feature Flag

---

go_modules/helpers/importresolver/main.go
go_modules/helpers/importresolver/main_test.go

Per https://github.com/golang/go/issues/42026, the [io/ioutil](https://pkg.go.dev/io/ioutil) package has been deprecated since go1.16. Replace them with the standard invocation of os.MkdirTemp https://pkg.go.dev/os#MkdirTemp.
a trivial change in the native helper - Go importresolver
in [importresolver/main.go:L32-L34](https://github.com/dependabot/dependabot-core/pull/11541/files#diff-ee661abcf6e1525d05ec5fbc6813717b564cd4688395b852ed11c489b5b3e332R32-R34), added the removal of the local file on function exit (to prevent "pollution" of the local filesystem) since `TestVCSRemoteForImport` returns only the `repo.Remote()` "portion" of `repo` and the local directory is not used.
added a unit test `go_modules/helpers/importresolver/main_test.go` to test the function `VCSRemoteForImport` (to …

go_modules: replace deprecated ioutil library

---

elm/lib/dependabot/elm/version.rb

Improve the sorbet typing in elm/version.rb  from true to strict.
All CI checks should continue to pass as before.

Make elm/version.rb sorbet typing strict

---

python/Dockerfile

Python dependency jinja2 is required Cargo Rust installation for pip-compile
Failing command in dependabot core
```
command: {} pyenv exec pip-compile -v --build-isolation --allow-unsafe --output-file\=requirements-dev.txt -P jinja2 requirements-dev.in {}
```
With Error:
```
2025-01-02T10:49:26.7645509Z     Preparing metadata (pyproject.toml): started
2025-01-02T10:49:26.7645917Z     Preparing metadata (pyproject.toml): finished with status 'error'
2025-01-02T10:49:26.7646405Z     error: subprocess-exited-with-error
2025-01-02T10:49:26.7646767Z     
2025-01-02T10:49:26.7647336Z     × Preparing metadata (pyproject.toml) did not run successfully.
2025-01-02T10:49:26.7647858Z     │ exit code: 1
2025-01-02T10:49:26.7648473Z     ╰─> [6 lines of output]
2025-01-02T10:49:26.7648789Z …
```

Adding Cargo Rust to the Python Environment

---

python/lib/dependabot/python/language.rb
python/spec/dependabot/python/language_spec.rb

In order to support the smooth deprecation of python 3.8 we added two feature flags: `python_3_8_deprecation_warning ` and `python_3_8_unsupported_error`. As we stopped supporting python 3.8 on 5th February 2025, these feature flags are no longer required and this PR removes them to make the code easier to maintain.
After this PR is merged, the feature flags `python_3_8_deprecation_warning ` and `python_3_8_unsupported_error` will be removed from the codebase and tests should continue to pass.

Remove python 3.8 deprecation / unsupported FFs and cleanup tests

---

common/lib/dependabot/errors.rb
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyNotFoundException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/DependencyNotFound.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/native_helpers.rb

Include more error message patterns for missing packages.
The `dependency_not_found` error can happen during NuGet fetch so a corresponding entry was added to `fetcher_error_details` to match the entry in `updater_error_details` in `errors.rb`.

expand error patterns for missing packages

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/FrameworkChecker/CompatibilityCheckerFacts.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/FrameworkChecker/SupportedFrameworks.cs

I want to add .NET 9 to the list of supported frameworks, and thus to the "compatibility matrix", so that updates of packages targeting older versions of the framework are allowed.
Package update are currently rejected with the following message when not directly targeting NET 9:
```
The package <package-name>.<package-version> is not compatible. Incompatible project frameworks: net9.0
```
Fixes: https://github.com/dependabot/dependabot-core/issues/11516
.NET 9 projects receive updates for packages that target older (pre 9) framework versions.

Add .NET 9 as a supported framework

---

.github/workflows/images-latest.yml
bun/lib/dependabot/bun.rb

When running the Bun updater, it is matching to the "bundler" image as the Bun image has not been registered correctly.
Part of https://github.com/github/dependabot-updates/issues/7990
We should start to see the Bun image being pushed to the registry and used.

Add Bun image strategy to push the Bun updater image

---

docker_compose/lib/dependabot/docker_compose/file_parser.rb
docker_compose/lib/dependabot/docker_compose/file_updater.rb
docker_compose/lib/dependabot/shared/shared_file_updater.rb
docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb
docker_compose/spec/dependabot/docker_compose/file_updater_spec.rb
docker_compose/spec/fixtures/docker_compose/composefiles/inline_dockerfile

* Adding support for `dockerfile_inline` as request as suggested by @krokyze https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2671830088
* Fixing issue with YAMLs with aliases @gegoune
https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2671630312
* We will be able to update `dockerfile_inline` images
* YAML files with aliases will be able to be parsed

Adding support for dockerfile_inline

---

nuget/Dockerfile
nuget/updater/common.ps1
nuget/updater/install-targeting-packs.ps1
nuget/updater/test-data/targeting-packs/packs/Existing.Targeting.Pack.Ref/7.8.9/.gitignore
nuget/updater/test-data/targeting-packs/sdk/1.2.3/Microsoft.NETCoreSdk.BundledVersions.props
nuget/updater/test-data/targeting-packs/sdk/4.5.6/Microsoft.NETCoreSdk.BundledVersions.props
nuget/updater/test.ps1

The NuGet updater Docker image currently installs the .NET 8 and 9 SDKs, but an intereseting scenario was encountered.
Consider a repo with:
- a project targeting `net7.0`
- a `NuGet.Config` file that explicitly calls the `<clear />` directive **AND** where the remaining NuGet package feeds don't contain any `Microsoft.NETCore.App.Ref` packages
- **NO** `global.json` file forcing the installation of a 7.0 SDK
If dependency discovery is run on that project it will fail because the current 9.0.x SDK will require the `Microsoft.NETCore.App.Ref` targeting pack version `7.0.20` but since that package isn't on the remaining private feeds, the operation will fail.
This PR scans the currently installed SDKs and downloads and extracts all required targeting packs.
The result is the following lines …

install all .NET targeting packs specified by the installed SDKs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

If a required project, props, or targets file is missing **_or if the casing doesn't match and MSBuild on Linux can't resolve it_**, report the specific file.
Previously a missing file would cause an error in discovery and nothing would be returned and the empty dependency file set turned into a `dependency_file_not_found` reporting that no `.csproj` files were found.
That's not entirely correct so now that specific file is captured and reported.  The end result for the user is the same, but this will make log classification easier.

report specific missing file during discovery

---

docker_compose/lib/dependabot/docker_compose/file_parser.rb
docker_compose/lib/dependabot/docker_compose/file_updater.rb
docker_compose/lib/dependabot/docker_compose/tag.rb
docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb
docker_compose/spec/dependabot/docker_compose/file_updater_spec.rb

Fixing how Dependabot handles Docker image digest updates in Docker Compose by:
1. Modifying the regex pattern to properly parse sha256: prefixed digests
2. Storing only the digest hash (without sha256: prefix) in the dependency's source hash
3. Reusing Dependabot's existing Docker version updater logic for Docker Compose updates
4. Updated the digest parser in the `Tag` class to use the `FileParser` constant
Thanks to @gegoune https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2672326569 and @DigitallyRefined https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2673761870 for raising this issue
Removed custom update_digest_and_tag implementation to reuse the base Docker version updater
The changes will be verified when:
1. Digest updates preserve the …

Remove sha256 from the source's digest

---

docker_compose/lib/dependabot/docker_compose/file_parser.rb
docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb

Add support for environment variable handling in Docker Compose file parsing. Currently, when Docker Compose files contain environment variables in version/tag specifications (e.g., image: ${DOCKER_IMAGE}), the parser attempts to process these as concrete versions, leading to incorrect dependency tracking.
This change ensures that dependencies with environment variable tags are skipped during parsing, while still properly handling dependencies with concrete version tags. This is important because we cannot meaningfully track or update dependencies where the version is determined at runtime through environment variables.
Thanks to @gmile https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2674192037 for reporting this issue
Adding a simple environment variable check in …

Skip docker compose images with env param

---

docker_compose/lib/dependabot/docker_compose/file_updater.rb
docker_compose/spec/dependabot/docker_compose/file_updater_spec.rb
docker_compose/spec/fixtures/docker_compose/composefiles/tag_quoted

Images with quotes are not being updated and resulting in a `no change` error. This PR adds support for images wrapped in quotes.
Thanks to @Bert-R https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2676048313 and @Aaron-Ritter https://github.com/dependabot/dependabot-core/issues/390#issuecomment-2678101243 for reporting this issue
Dependabot will now be able to update images wrapped in quotes

Support images wrapped in quotes

---

nuget/lib/dependabot/nuget/file_fetcher.rb
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/file_fetcher_spec.rb
nuget/updater/common.ps1
nuget/updater/main.ps1
nuget/updater/normalize-file-names.ps1

NuGet only allows [three options](https://github.com/NuGet/NuGet.Client/blob/68db83a99814547864e09170f6c3179b33933a27/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L24-L37) for the config file naming:
- `nuget.config`
- `NuGet.config`
- `NuGet.Config`
If a code base is primarily developed on a case-insensitive file system like Windows, a config file named `Nuget.config` is fine, but dependabot runs in a Linux container with a case-sensitive file system and in that instance the config file won't be picked up by the NuGet tooling resulting in the default package feed of `api.nuget.org`.
This PR addresses that by running a script to rename the files prior to any operation being performed.
Fixes #11525.

ensure proper casing for `NuGet.Config` prior to any operations being performed

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs

Issue found when scanning internal logs.
If a feed is specified with an internal-only URL, checking that feed for possible updates will obviously fail.  We don't want to fail the entire update process, though, because it's entirely possible for a repo to list both public and internal feeds and to only want dependabot to run for public packages.
The fix is to broaden the scope of the `try` block so that if fetching the service index fails, we simply continue onto the next source.

don't continue checking a non-existant feed for a package

---

docker/lib/dependabot/docker/update_checker.rb

Increasing timeouts for fetching tags from 5 seconds to 60 seconds
Images with a lot of tags will be fetched successfully

Increase timeout for getting tags from 5 seconds to 60 seconds

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatedDependencyListTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

This includes non-project files, e.g., `global.json` and `dotnet-tools.json` in the call to `create_pull_request`.  Most of the work was explicitly adding these two files to the list of files to check.

include non-project files in pull request

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This is a less common error, but something that appeared during a manual audit of the logs.  This will turn the missing SDK message into a `dependency_not_found` error.

add error for missing sdk

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb

Currently, the [implementation](https://github.com/dependabot/dependabot-core/blob/main/go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb#L199C8-L211C12) only logs an error message when go mod tidy fails, making it unclear if it runs successfully. This PR ensures proper logging to confirm its execution.
N/A
I ran the Dependabot CLI locally and confirmed that I receive a success message (`go mod tidy succeeded`) before every PR creation(`Submitting github.com/spf13/cobra pull request for creation`). 
Example output:
```
updater | 2025/02/28 11:25:09 INFO `go mod tidy` succeeded
updater | 2025/02/28 11:25:09 INFO Started process PID: 2077 with command: {} git status --untracked-files all --porcelain v1 /home/dependabot/dependabot-updater/repo/vendor {}
updater | 2025/02/28 …
```

Adding a success log to the `go mod tidy` command to ensure it runs before creating a version bump PR.

---

nuget/lib/dependabot/nuget/nuget_config_credential_helpers.rb
nuget/spec/dependabot/nuget/nuget_config_credential_helpers_spec.rb
updater/lib/dependabot/file_fetcher_command.rb

This PR is for a very specific scenario, namely:
1. A repo with NuGet packages
2. That depends on a custom password- or token-authenticated feed
3. And no `NuGet.Config` file exists in the repo
The NuGet updater relies heavily on native NuGet tooling and the native NuGet tooling looks in parent directories for a `NuGet.Config` file and also in the user-level location of `~/.nuget/NuGet/NuGet.Config`.
In this case a custom package feed needs to be added to the user-level `NuGet.Config` file so that all of the tooling knows it's available.  The proxy service is then responsible for all authentication.
Update jobs are split into two phases, `fetch_files` and `update_files`.  Each job phase is given different information regarding feed credentials as specified in the job file.
The …

use `$.job.credentials-metadata` if `$.credentials` isn't given

---

python/lib/dependabot/python/metadata_finder.rb

Sorbet Type as strict for the metadata_finder

Added sorbet type strict for the metadata_finder

---

Rakefile

The v2 API added endpoints specific for a specific version of a gem: https://guides.rubygems.org/rubygems-org-api-v2/
Benefits:
1. Less data gets returned over the wire.
Compare:
* https://rubygems.org/api/v1/versions/dependabot-omnibus.json 
* https://rubygems.org/api/v2/rubygems/dependabot-omnibus/versions/0.299.1.json
3. Less brittle since we no longer parse the `response.body`
4. Faster since we only check `response.code`
I verified that sending a non-existent version returns a `404`: https://rubygems.org/api/v2/rubygems/dependabot-omnibus/versions/0.7.1.json

Simplify the "version already exists" check by using RubyGems v2 API

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/SdkProjectDiscoveryTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.targets

Dependency discovery is a two step process:
1. Discover a project's TFMs.
2. For each TFM, discover dependencies.
Several MSBuild properties are set to enable this to work properly for OS-specific situations, but if a value for `$(TargetPlatformVersion)` is not set, there are two separate values that need to be used as a default.  For scenario (1) a default value of `0.0` is required, but for scenario (2) a default value of `1.0` is required.  This PR allows each stage of dependency discovery to set the appropriate value.
Fixes #11719.

use different values for `$(TargetPlatformVersion)` for TFM and dependency discovery

---

.github/workflows/gems-bump-version.yml

I was about to add `bundler-cache: true` when I realized that we don't actually `bundle install` anything. So the cache is not only superfluous, it's probably slower.
Since I spent a little bit of time digging into this and it's easy to miss if someone is in a hurry, I thought best to document for the next person.
Hopefully this way if someone changes to `bundle install` a gem, they'll realize this should get flipped on.

Document why `bundler-cache: true` isn't needed

---

cargo/Dockerfile

Downgrading the Rust base image from `rust:1.85.0-bookworm` to `rust:1.84.0-bookworm` to fix missing dependencies in the Cargo ecosystem.  
The `rust:1.85.0-bookworm` Docker image is missing required layers, leading to issues where `cargo` is not found in the container environment. This has been confirmed by reverting locally and testing `cargo` commands successfully.  
Issue Link: [dependabot-core/issues/11737](https://github.com/dependabot/dependabot-core/issues/11737)  
Sentry Issue: [DELTAFORCE-12XK](https://github.sentry.io/issues/6352804694/?referrer=github_integration)  
- This downgrade is a temporary fix to restore functionality.  
- Further investigation may be needed to determine why `rust:1.85.0-bookworm` is missing essential dependencies.  
- If a better long-term solution is …

Downgrade Rust Docker image from 1.85.0-bookworm to 1.84.0-bookworm to restore missing dependencies

---

python/lib/dependabot/python/package/package_details_fetcher.rb
python/lib/dependabot/python/update_checker.rb
python/lib/dependabot/python/update_checker/pip_version_resolver.rb
python/spec/dependabot/python/update_checker_spec.rb
python/spec/fixtures/pypi/pypi_response_luigi.json

This PR fixes an issue where cooldown options were not being correctly passed into the latest version finder. This ensures that the version resolution process properly respects cooldown settings, preventing unnecessary updates from being suggested too soon.  
- The fix ensures that cooldown settings are correctly included in the version-finding logic.  
- Let me know if there are edge cases I might have missed.  
- Verified that cooldown settings are correctly applied when resolving versions.  
- Tests cover the expected cooldown behavior to prevent early dependency updates.

Fix passing cooldown options into Python Latest Version Finder

---

cargo/Dockerfile

Reverts dependabot/dependabot-core#11738
This PR reverts our previous downgrade from Rust 1.85.0-bookworm to 1.84.0-bookworm. The Docker image has been [republished](https://hub.docker.com/layers/library/rust/1.85.0-bookworm/images/sha256-56248c7a926f4202b184d07269ba61295b21955b745e4b2b18dc869aec128575) with fixes for the issues we encountered earlier.
The cargo unit tests are now passing successfully with the 1.85.0 image. Note that some cargo e2e tests are still experiencing issues, but these appear to be unrelated to the Docker image version.
This PR can be merged if all unit cargo tests continue to pass in CI.
closes: https://github.com/dependabot/dependabot-core/issues/11745

Revert "Downgrade Rust Docker image from 1.85.0-bookworm to 1.84.0-bookworm to restore missing dependencies"

---

docker/lib/dependabot/docker/version.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/fixtures/helm/yaml/multi-image-with-bad-version.yaml

The docker updater version class has slightly different code between the `initialize` method and the `correct?` method.  This PR aligns the two by removing the fallback to `parsed_version` and explicitly checking a return value before proceeding.
Fixes #11739.

align version checking code with the parse method

---

bin/dry-run.rb
common/lib/dependabot/package/package_latest_version_finder.rb
common/lib/dependabot/package/release_cooldown_options.rb
common/spec/dependabot/package/package_latest_version_finder_spec.rb
common/spec/dependabot/package/release_cooldown_options_spec.rb
python/spec/dependabot/python/update_checker_spec.rb
updater/lib/dependabot/job.rb
updater/spec/dependabot/job_spec.rb

This PR improves test coverage by adding and updating specs for `Job`, ensuring that cooldown functionality is properly tested. Additionally, it fixes an issue where the dry-run mode was not passing cooldown settings through environment variables.  
These changes help ensure that cooldown settings are correctly parsed, applied, and tested across different update scenarios.  
- Updated spec coverage for `Job`, focusing on cooldown attributes and parsing.  
- Fixed the dry-run functionality to correctly pass cooldown settings via environment variables.  
- Ensured that cooldown behavior is consistent when applied in different cases.  
- Running the full test suite should confirm that cooldown settings are handled correctly in both normal and dry-run modes.  
- The dry-run execution should …

Add/Update Specs for Job & Fix Dry-Run to Pass Cooldown Through Env Variables

---

.github/workflows/ci.yml
silent/tests/go.mod

This way it's one less place we have to keep things in-sync.
I realize the version in `go.mod` is intended as a minimum bound and not a hardcoded version, for example, the underlying file is already using a slightly different version:
https://github.com/dependabot/dependabot-core/blob/d0b3517a63291220cbdb7b04f1f6859474fcd375/silent/tests/go.mod
But practically speaking my experience is this way is simpler to reason about.

Make `setup-go` inherit `go` version from the `go.mod` file

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestMessageTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/TestApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatePermittedAndMessageTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/ClosePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/CreatePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/GroupPullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/MessageBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PullRequestDependency.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdatePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/IApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestConverter.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

This PR adds the final bits of PR handling messages and will report things like `update_pull_request`, `pull_request_exists_for_latest_version`, `security_update_not_needed`, etc.
The bulk of the tests were copied from the existing Ruby implementation and slightly tweaked to better represent the NuGet ecosystem.
This also required more strongly typed values for existing pull requests.  In the JSON they're represented as an array of array of dependencies and that's what the old model represented, but now they're more strongly typed.  Consider the following example that better shows the structure:
``` jsonc
{
"job": {
// ...
"existing-pull-requests": [
// pull request 1
[
{
"dependency-name": "Some.Dependency",
"dependency-version": "1.2.3"
}
],
// pull request 2
[
{
"dependency-name": …
```

report pr status messages as appropriate

---

nuget/Dockerfile

The NuGet updater installs SDKs as specified in a repo's `global.json` files then wherever possible, uses that version of the SDK for various update operations.  Older versions of the .NET SDK (e.g., 3.1.xxx) require libssl 1.1, but that's not available on the current updater image nor on the install sources so it needs to be manually installed.
Found during a manual internal log audit.

install libssl 1.1 to support older .NET SDKs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/CommitOptions.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/CommitOptions_IncludeScopeConverter.cs

To help with https://github.com/dependabot/cli/pull/408 this PR allows the following values for the `include-scope` property:
- `true` bool
- `false`
- `"true"` stringified bool
- `"false"`
- `null` null - false
The old values are still supported to allow for older CLI versions to still work.

allow multiple forms for `$.job.commit-message-options.include-scope` property

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestMessageTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

Adds simple PR title generation of the shape:
```
Update Some.Package to 1.2.3
```
In a more complicated scenario where multiple versions were updated for multiple packages the text will look like:
```
Update Package.A to 1.0.0, 2.0.0; Package.B to 3.0.0, 4.0.0
```
The same text is used for all three generated fields: PR title, body, and commit message.
The other tests were modified to always report static text for these fields so that changes to the new text generation won't cause a bunch of other tests to fail and require a lot of churn.

add simple title, commit message, and body text generation

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/DiscoverCommand.cs
nuget/updater/main.ps1

If the C# NuGet updater fails to deserialize the `job.json` file, the error handler goes into a method that attempts to turn the exception into a dependabot-specific type.  One of the exception types listed, however, is from an MSBuild binary which means that MSBuild needs to have been resolved first.
This PR builds on the findings of @rhyskoedijk and forces MSBuild to have been loaded before the first time the job file is parsed.  This behavior is really complicated to unit-test because by definition, all unit test runs have _already_ loaded MSBuild.  Subsequent calls to the updater don't need MSBuild pre-loaded in this way because if we get that far we already know the file is formatted correctly.
This also contains a fix to the end-to-end updater (code not live) to not attempt any …

properly report failure to deserialize job file

---

python/lib/dependabot/python/package/package_details_fetcher.rb

This PR fixes an issue where `fetch_from_json_registry` in `PackageDetailsFetcher` could return `nil`, leading to a **Sorbet type validation error**:  
```
Dependabot::Sorbet::Runtime::InformationalError: Parameter 'releases_json': Expected type T::Hash[String, T::Array[T::Hash[String, T.untyped]]], got type NilClass
```
This error occurs when the registry response is unexpectedly empty or missing the `releases` key. The fix ensures that `fetch_from_json_registry` handles this case gracefully by providing a default empty hash (`{}`) if the response is `nil`.  
Fixes:
- https://github.com/dependabot/dependabot-core/issues/11788
---
- The fix ensures that even if `fetch_from_json_registry` returns `nil`, the method does not break due to unexpected `NilClass` values.  
- Alternative …

Fix `NilClass` error in `format_version_releases` for Python package details fetcher  

---

nuget/updater/common.ps1

A common practice is for a repo to have a `global.json` that looks like this:
``` json
{
"sdk": {
"version": "8.0.0",
"rollForward": "latestMinor"
}
}
```
where the SDK version listed isn't actually a proper SDK version like `8.0.100`.  The `global.json` can be used at runtime, however, so we should still try to install what we can.
To accomplish this we see if the SDK version consists of three parts and if the last part is `0` then we can do an alternate installation mechanism where we treat the first two version parts (e.g., `8.0`) as an installation channel.  We then pass this with a separate switch to the installer script which will install the latest from that channel (e.g., `8.0.404` or whatever is current).
Fixes #11752.
With this change the log looks like this:
```
updater | …
```

install .NET SDK from channel if necessary

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestHttpServer.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

If all of the following are true:
- The repo doesn't have a `NuGet.Config` file (or it does but doesn't specify the `<clear />` directive)
- The repo is using Central Package Management (i.e., `Directory.Packages.props`)
- The project sets `$(TreatWarningsAsErrors)` to `true`
- The `dependabot.yml` file lists custom NuGet feeds
...then dependency discovery can fail because the updater generates a `NuGet.Config` file before the updater is run that contains all of the feeds listed in `dependabot.yml` as well as `api.nuget.org` and if there are multiple remote feeds used with CPM, a warning `NU1507` is generated indicating that no `packageSourceMapping` elements were specified in `NuGet.Config`.  `$(TreatWarningsAsErrors)` then kicks in and prevents dependency discovery from happening. …

explicitly override `TreatWarningsAsErrors` to `false` during discovery

---

nuget/Dockerfile

Windows exposes two environment variables, `%TEMP%` and `%TMP%` and those are commonly used in `.targets` files, but since those variables don't exist in the docker image, those steps can fail.
This PR simply creates a directory `/tmp/dependabot` and sets both environment variables to that location.  I've manually verified that those locations are writable by the `dependabot` user.
Fixes #11595.

ensure `$TEMP` and `$TMP` environment variables exist

---

terraform/Dockerfile
terraform/spec/dependabot/terraform/file_parser_spec.rb

Making Dependabot work with Terraform 1.11.x.
https://github.com/hashicorp/terraform/releases/tag/v1.11.0
https://releases.hashicorp.com/terraform/1.11.0/
The build output will show if the image will build successfully.

build(deps): bump terraform from 1.10.5 to 1.11.0

---

nuget/Dockerfile

A follow up to #11741, this PR installs libssl 1.0 to support .NET SDK 2.1.

install libssl 1.0 to support .NET SDK 2.1

---

bin/docker-dev-shell

Reverts dependabot/dependabot-core#11683
As @robaiken has raised an issue with this config.
```
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.Q3NRTvcke4/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.Q3NRTvcke4/Listeners: operation not supported```
```
@dmitris Need your thoughts on this pls
FYI @abdulapopoola

Revert "mount the SSH_AUTH_SOCK socket for ssh-agent"

---

npm_and_yarn/Dockerfile

Release notes: [4.6.0](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.6.0)
What's Changed
> 
>     fix(pnp): support require(esm) by @merceyz in https://github.com/yarnpkg/berry/pull/6639
>     feat: add yarnpkg/core sub exports by @ChALkeR in https://github.com/yarnpkg/berry/pull/6614
>     add a config option to disallow the cache clean command by @elbywan in https://github.com/yarnpkg/berry/pull/6610
>     Small typo in yarn workspaces foreach: include -> exclude by @miorel in https://github.com/yarnpkg/berry/pull/6561

Bump Yarn to 4.7.0

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.targets
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

There are two types of project files: SDK-style projects, and legacy projects.
When determining dependencies, we essentially call `dotnet restore` on the project.
- If it was an SDK-style project, we'll get a list of dependencies.
- If it was a legacy project, we'll see the error `error MSB4057: The target "GenerateBuildDependencyFile" does not exist in the project.` If that error text is found, we know it's a legacy project and we just return an empty array because the newer SDK can't do anything with that.
There's a secret third type of project file: it looks like a legacy project, but it contains `<PackageReference>` elements.  The dotnet CLI can't resolve these packages and we have to do something special.  (Side note, this feature does work in Visual Studio, but we don't have that …

add manual dependency resolution for VS-only PackageReference legacy projects

---

hex/helpers/lib/run.exs

On error, Base.decode64 returns :error, not {:error, _}. Let's change the case pattern to avoid this error:
** (CaseClauseError) no case clause matching: :error
/opt/hex/lib/run.exs:22: DependencyHelper.try_decode/1
/opt/hex/lib/run.exs:8: DependencyHelper.main/0
/opt/hex/lib/run.exs:157: (file)
I noticed the error above, and I'm hoping that fixing this brings us closer to seeing the actual error messages for Hex update failures.
This improves on #11661 , aiming to fix #11569 .
N/A
To be honest, I'm not sure. I don't have a good test case for this - it's just something I noticed in the logs, and I don't know why base64 decoding failed in the first place.

Hex: handle base64 decoding error

---

terraform/Dockerfile

Making Dependabot work with Terraform 1.11.2.
https://github.com/hashicorp/terraform/releases/tag/v1.11.2
https://releases.hashicorp.com/terraform/1.11.2/
The build output will show if the image will build successfully.

build(deps): bump terraform from 1.11.0 to 1.11.2

---

docker/lib/dependabot/docker/file_parser.rb
docker/spec/fixtures/helm/yaml/multi-image-with-bad-version.yaml

The docker tag parser matched against a regular expression but didn't verify that the match worked before trying to pull out the values.
An internal investigation found a helm chart with an empty tag that caused the parser to fail.

ensure regex matched before pulling out values

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/AnalyzeWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/FrameworkChecker/FrameworkCompatibilityServiceFacts.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscovery.targets
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/FrameworkChecker/FrameworkCompatibilityService.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/FrameworkChecker/SupportedFrameworks.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

If no `$(TargetPlatformVersion)` is specified for a `-windows` TFM, manually set the default of `7.0`.
The MSBuild interactions here are complicated and the dependency discovery entry point targets we're using have bypassed target platform resolution so we have to do some manual intervention.  We may end up needing custom values for other OS-specific TFMs, but that work will be trivial.
The test case that was missed before is a project target framework of `net9.0-windows` _AND_ a dependency framework requirement of `*-windows7.0`.
Fixes #11719.

Enforce proper minimum Windows version for OS-specific TFM

---

nuget/lib/dependabot/nuget/file_parser.rb
nuget/spec/dependabot/nuget/file_parser_spec.rb

When the NuGet updater determines if it was able to resolve any files, it only considered reportable dependencies and pulled file information out of that.  That scenario missed a situation where the project evaluation was successful, but there was nothing that could be used as the basis of an update.
This PR fixes that.
The function `DiscoveryJsonReader.run_discovery_in_directory` was called twice and I'd have had to add a third, so it was lifted to a common function to reduce duplication.

consider a successfully evaluated project with no dependencies to be valid

---

uv/lib/dependabot/uv/file_updater/lock_file_updater.rb

Following discussions on the dependabot [issue](https://github.com/astral-sh/uv/issues/2512) on the `uv` repo we are removing the code that updates the required python version in the `pyproject.toml` file for `uv` projects.
Part of https://github.com/dependabot/dependabot-core/issues/10478
Relates to https://github.com/astral-sh/uv/issues/2512#issuecomment-2736991441
This behaviour was carried over from the `python` ecosystem implementation, but is not necessary for `uv`.
`./bin/dry-run.rb uv dsp-testing/dependabot-uv` completes successfully with the expected changes.

Don't update the required python version in pyproject.toml for uv projects

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/DependencyDiscoveryTargetingPacks.props
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/NuGetUpdater.Core.csproj

When attempting dependency discovery for legacy C# projects, it's common to see a warning `The reference assemblies for .NETFramework.Version=v4.7.2 were not found.`  This isn't necessary or relevant for dependency discovery and can be safely ignored.  It's being explicitly removed because it's a red herring and makes it difficult to discover any real failures.  No functional change, but it makes the logs easier to understand.
Due to the order of imports, etc., we need to update the `$(NoWarn)` property earlier in the build process so we need a separate file to do the work.

suppress red herring warning from legacy project dependency discovery

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs

The NuGet updater needs to manually sideline special targets files imports that only come with a full install of Visual Studio.  Previously these files were sidelined as each project was inspected, but if there was a `<ProjectReference>` element and that project _also_ had one of these files, we'd still fail.
The fix is to apply the special transform to all relevant projects files before running any discovery.  Two existing unit tests were updated to contain the relevant project reference.
When reviewing `DiscoveryWorker.cs` I recommend turning off whitespace because indentation was changed, but the functional change is relatively small.

sideline all special targets files before discovery

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Directly updating a dependency with a wildcard version number isn't something dependabot supports, but we _can_ update another dependency even if a wildcard is present.
The fix is to only use an absolute version range if there's no wildcard present when determining the transitive dependency set.

allow updating dependency when another dependency has a wildcard

---

nuget/updater/main.ps1

If an update job is started from the CLI with the `--local` option, a local directory is copied into the updater container and initialized as a git repository.  This PR allows the end-to-end updater to skip the clone step if this is the case.  This mimics the behavior used by the [common code](https://github.com/dependabot/dependabot-core/blob/b2b563118078b2bd16b18081a09f29957007020c/common/lib/dependabot/file_fetchers/base.rb#L786).

skip clone operation if git repo already exists

---

common/lib/dependabot/package/package_details.rb
common/spec/dependabot/package/package_details_spec.rb

Make the `dist_tags` attribute publicly accessible in `PackageDetails`.  
Although the `dist_tags` parameter has been initialized in the constructor, it was previously missing an `attr_reader`, making it unreachable externally.
This change enables consumers of `PackageDetails` to access distribution tags (e.g., `latest`, `beta`), which are useful for version resolution logic, especially in ecosystems like NPM and Yarn.
This is a minimal and targeted change — no logic is altered, only a missing attribute reader is added.  
This ensures consistency with the initialized state of the object and avoids silent confusion when attempting to read `dist_tags`.
- Consumers of `PackageDetails` will now be able to call `.dist_tags` without encountering a `NoMethodError`.
- Existing test suites should …

Add missing `dist_tags` attribute reader to PackageDetails

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackageReferenceUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateOperationBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Mixed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackagesConfig.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/BindingRedirectManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/LockFileUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationResult.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

This PR tracks all update operations performed and reports the results in the log.
There are several parts to this PR:
1. All update operations are classified as `DirectUpdate`, `PinnedUpdate`, or `ParentUpdate`.
1. `DirectUpdate` is where a package version was changed, e.g., from `1.0.0` to `1.0.1`.
2. `PinnedUpdate` is where a transitive dependency had to be pinned to a specific version.  From the user's perspective it appears that we added a new dependency.
3. `ParentUpdate` is where a transitive dependency could be updated by updating another top-level dependency.
2. Where we directly edit files on disk, we return the kind of update performed.
3. When the dependency solver is invoked, it would be too messy to track all updates so instead the function …

track and report all update operations performed

---

npm_and_yarn/lib/dependabot/npm_and_yarn/package/registry_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This PR introduces Sorbet type annotations to three core classes in the `npm_and_yarn` ecosystem:
- `UpdateChecker`
- `LatestVersionFinder`
- `RegistryFinder`
- `VersionResolver`
**What:**  
The goal is to improve static type safety and developer tooling support for these critical components of the npm/yarn update logic. Types have been added to method signatures, internal state, and helper methods where appropriate.
**Why:**  
Adding Sorbet types to these classes increases confidence when making future changes, helps catch bugs earlier, and makes the code easier to navigate for contributors unfamiliar with the implicit contracts in these classes.
- The code now passes `srb tc` with no type errors on the updated files.
- The classes still pass all tests, ensuring functional equivalence.
- …

Add Sorbet type annotations to UpdateChecker, LatestVersionFinder, and VersionResolver for `npm_and_yarn`

---

.github/workflows/images-branch.yml
.github/workflows/images-latest.yml
.github/workflows/images-updater-core.yml

This is mostly cosmetic, but technically it's slightly more secure as it explicitly logs out at the end of the workflow run.

Use the official Docker Login action

---

uv/lib/dependabot/uv/update_checker.rb

To allow Dependabot to correctly resolve **top-level dependencies** in `uv`-based Python projects that do **not have explicit requirements**.
Previously, if a dependency had no `requirements`, it was assumed to be a sub-dependency, and an error was raised if no lockfile (like Pipenv, Poetry, or pip-compile) was found.  
However, `uv.lock` is now supported and can define top-level dependencies even without individual requirement declarations.
This change ensures that if `uv.lock` is present in `dependency_files`, the resolver will correctly treat the dependency as top-level.
There were two possible places to address this logic:
- Inside `resolver_type` logic
- Or in `subdependency_resolver`, which is cleaner and more centralized for fallback
I chose to handle it within …

fix(uv): handle top-level dependencies without requirements

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PrivateSourceBadResponse.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs
nuget/lib/dependabot/nuget/native_helpers.rb
nuget/spec/dependabot/nuget/native_helpers_spec.rb

Currently in the nuget updater if a feed starts to return 429s and we are unable to restore packages it gets reported as a `dependency_file_not_found error` 
This PR changes these to get reported as `private_source_bad_response`.

change rate limiting error in nuget updater

---

docker/lib/dependabot/shared/shared_file_parser.rb
docker/spec/dependabot/docker/file_parser_spec.rb

Update digest handling to include sha256 prefix in source digest and add the digest to the version response if present.
Tags and digests are both part of a "version" for container images. If a digest is present, it takes precedence for specifying the image contents regardless of the tag present.
So, for scenarios where both the tag and digest are both present, then `version` should be in the form of `tag@sha256:digest`
The current approach only returns the tag for `version` even if a digest is present. Only returning the digest (without `sha256:`) if no tag was present.
Updated specs to check for it.

Update docker version to include digest if applicable

---

docker/lib/dependabot/docker/update_checker.rb
docker/spec/dependabot/docker/update_checker_spec.rb

Removing feature flag `docker_tag_component_comparison` from the codebase
**closes: https://github.com/dependabot/dependabot-core/issues/8648**
n/a
Dependabot will use image component comparison to select images to update to

Removing `docker_tag_component_comparison` feature flag

---

common/lib/dependabot/package/package_latest_version_finder.rb
common/lib/dependabot/package/package_release.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/package/package_details_fetcher.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/package_latest_version_finder_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/version_resolver_spec.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker_spec.rb

This PR ensures that the cooldown logic is properly applied in the npm_and_yarn ecosystem's Latest Version Finder by passing the cooldown parameter from the abstract UpdateChecker. Additionally, the npm_and_yarn Latest Version Finder is refactored to extend the generic Package Latest Version Finder, aligning with other ecosystems and improving consistency.
The changes are part of the task to standardize the `npm_and_yarn` client, generic latest version finder, and cooldown filtering for Dependabot. This update address the issue https://github.com/dependabot/dependabot-core/issues/3651 where the goal is to improve version filtering by applying cooldown settings and aligning with the broader implementation across ecosystems.
This PR is a continuation of the following PR:
- …

Introduce PackageLatestVersionFinder for `npm_and_yarn` behind feature flag Part-2

---

bin/docker-dev-shell
script/dependabot

I was trying to run `script/dependabot` within a Codespace when I got the following error:
@jeffwidman ➜ /workspaces/dependabot-core (main ✗) $ script/dependabot update maven dsp-testing/test-dependabot-updates-9127 --debug
cli | 2025/04/01 21:56:02 Inserting $LOCAL_GITHUB_ACCESS_TOKEN into credentials
cli | 2025/04/01 21:56:03 image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest is already up to date
cli | 2025/04/01 21:56:03 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:113d9623e8852177b0027bd1c313bd1c1637058e4079fda9328b735cb4eabbf7
cli | 2025/04/01 21:56:03 image ghcr.io/dependabot/dependabot-updater-maven is already up to date
cli | 2025/04/01 21:56:03 using image …

Ensure `.core-bash_history` file exists when debugging with Dependabot CLI

---

npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/update_checker/package_latest_version_finder_spec.rb

This change applies cooldown logic for release tags in the `npm_and_yarn` ecosystem. It ensures that the cooldown behavior is respected when determining the latest version based on release tags. The goal is to improve the update checker's handling of release versions and integrate cooldown filtering, aligning the behavior with other ecosystems that already use this feature.
- The focus is on applying cooldown behavior for release tags in the `npm_and_yarn` ecosystem.
- The code changes include modifications to the `LatestVersionFinder` and related methods to support cooldown tags.
- The feature flag for cooldown control has been integrated into the version selection process.
- Once merged, the cooldown behavior for release tags will be successfully applied, allowing the update checker to …

Apply Cooldown for Release Tags in `npm_and_yarn` Ecosystem

---

updater/lib/dependabot/updater/security_update_helpers.rb

As explained in https://github.com/dependabot/dependabot-core/issues/11948, we shouldn't be coercing this to an empty string if it's nil. 
Among other things, a later log line checks if it's nil and so an empty string results in a confusing error message.
It looks like this bug originally crept in here:
* https://github.com/dependabot/dependabot-core/pull/9929#discussion_r2023849120
Fix: https://github.com/dependabot/dependabot-core/issues/11948
Related:
* https://github.com/dependabot/dependabot-core/pull/11950

Don't coerce `nil` to `""` if no non-vulnerable version found

---

updater/lib/dependabot/updater/security_update_helpers.rb

As explained in https://github.com/dependabot/dependabot-core/issues/11948, we need to handle when this is an empty string, or we get a confusing error message.
Fix: https://github.com/dependabot/dependabot-core/issues/11948
Related:
* https://github.com/dependabot/dependabot-core/pull/11949

Handle when the version is an empty string

---

common/lib/dependabot/package/package_latest_version_finder.rb

This change removes an incorrect import of Bundler from the `common` module, which was causing issues in the `PackageLatestVersionFinder` class. The import was mistakenly included, leading to errors, and its removal resolves these issues.
The main change is the removal of the unnecessary Bundler import in the `common` module. This should be verified to ensure no unintended side effects occur due to the removal.
The issue causing errors related to the `PackageLatestVersionFinder` should be resolved. After removing the import, the functionality should return to normal without any issues arising from the incorrect import.

Remove Incorrect Bundler Import in Common to Fix PackageLatestVersionFinder Issue

---

bundler/lib/dependabot/bundler/update_checker.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb

This PR handles cooldown options received as the `update_cooldown` attribute of the `UpdateChecker` initializer which expects an `Dependabot::Package::ReleaseCooldownOptions` instance.
This method has already been implemented in this way for the `npm_and_yarn`, `uv`, and `python` ecosystems.
After this PR is merged we can perform a full test of cooldown for `bundler`.

Handle cooldown options for bundler

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Similar to #11919 503's are returning `dependency_file_not_found`. The ruby changes were already added in the previous PR so this iteration just builds on top of that adding another case where we throw `PrivateSourceBadResponse`

Add another NuGet bad response case

---

helm/lib/dependabot/helm/file_parser.rb
helm/spec/dependabot/helm/file_parser_spec.rb
helm/spec/fixtures/helm/v3/chart_permitted_classes.yaml
helm/spec/fixtures/helm/v3/values_permitted_classes.yaml

Adding `Date`, `Time`, and `Symbol` to the permitted classes for YAML parsing in the helm ecosystem. This is needed because `YAML.safe_load` tries to parse dates from values.yaml files, resulting in "Tried to load unspecified class: Date" errors when attempting to run on private dependabot runners.
This affects dependabot's ability to properly parse and update Helm charts.
Related comment: @kuhnroyal https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-2775085909
The change is straightforward - adding three permitted class types to the existing YAML.safe_load
The dependabot runners will successfully parse Helm YAML files containing date values without throwing "Tried to load unspecified class" errors. Tests involving Helm chart updates will pass, and the ecosystem will …

Adding date, time and symbol to permitted classes for helm yaml parsing

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackageReferenceUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Files/ProjectBuildFile.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs

This fixes a very specific bug.
Generally file updates are tracked in memory, but in some cases we use an external tool to update files on disk.  If we do one of these on-disk updates followed by an in-memory update, the on-disk update will be overwritten/discarded.  This PR fixes that behavior by explicitly refreshing the in-memory copy.
A scenario where this would occur and the result is the following:
1. The dependency solver decides a transitive pin is required...
2. ...AND another package needs to be updated
The end result is that step 1 will be lost when the result of step 2 is written back to disk.  The user would see this as a package getting updated and their CI failing because the original pinned dependency was still on the old version.
This is such a specific issue that I've …

ensure pinned transitive dependency isn't overwritten by subsequent updates to the same file

---

go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb

Reverts dependabot/dependabot-core#11815
As per the discussion with @jakecoffman I am reverting this.

Revert "Update go mod version before running `go mod tidy -e`"

---

docker/lib/dependabot/shared/shared_file_parser.rb
docker/spec/dependabot/docker/file_parser_spec.rb

Reverts dependabot/dependabot-core#11938
Fixes #11971
We're also seeing the in https://github.com/github/dependabot-action so I was able to test locally and confirmed reverting it fixes the issue.

Revert "Update docker version to include digest if applicable"

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs

Simple formatting fix.  When reporting updated files, an empty string doesn't suffice.

fix spacing between reported updated files

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestMessageTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

During an update process we gather a list of all operations performed and this is now used to generate the PR body text.
PR body will now look something like this:
```
Performed the following updates:
- Updated Package.A to 1.0.0 in /src/client/library.csproj
- Updated Package.B to 2.0.0 in /Directory.Build.props
```

use update operation collection to generate PR body text

---

.github/ci-filters.yml
.github/workflows/ci.yml
bin/dry-run.rb
bin/spec/dry-run_spec.rb
bin/spec/spec_helper.rb

This PR adds comprehensive specs for the `bin/dry-run.rb` script and integrates them into the CI pipeline. The goal is to ensure that the `dry-run` functionality is thoroughly tested and validated as part of the development process. 
The decision to place the tests in a dedicated `bin/spec` directory was made to keep the tests close to the implementation while ensuring clarity and maintainability. This approach balances the need for logical organization with CI compatibility.
<details>
<summary>
Full decision
</summary>
**Pros:**
- Maintains a clear location that logically corresponds to the script's location
- Follows the established pattern of having `spec` directories for tests
- Cleanly separates these tests from ecosystem-specific tests
- Makes it obvious where to find tests for …

Add Dry Run Specs and CI Integration

---

.github/workflows/gems-release-to-rubygems.yml

Switch to using Trusted Publishing for publishing the Dependabot gems to RubyGems. This is much more secure than using a hardcoded API key.
Before putting up this PR, I configured RubyGems to treat this workflow as a trusted publisher for _all_ of the gems published by this workflow.
Context:
* https://blog.rubygems.org/2023/12/14/trusted-publishing.html
* https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
Related: 
* https://github.com/dependabot/dependabot-core/issues/9786
While this should fix ☝️, I'm not marking it that way as I want to follow all the verification steps listed in https://github.com/dependabot/dependabot-core/issues/9786#issuecomment-2781096230 to confirm it worked before closing it.

Use Trusted Publishing for RubyGems rather than hardcoded API key

---

helm/lib/dependabot/helm/update_checker.rb
helm/spec/dependabot/helm/update_checker_spec.rb

Replacing the typo `helm_repository` with `helm_registry` in the `helm` ecosystem
thanks to @thalescosta for spotting this
Dependabot will get the correct credentials for the `helm_registry` type

Fixing typo `helm_repository` to `helm_registry`

---

helm/lib/dependabot/helm/update_checker.rb
helm/spec/dependabot/helm/update_checker_spec.rb

Fix Helm `index.yaml` fetcher to convert oci repository urls to https when fetching chart indexes. 
The updater can't find chart versions in oci repositories that fallback to searching the registries `index.yaml`. Helm repositories contain `index.yaml` files that list all available charts and versions.
Oci urls are properly converted before making http requests, ensuring users with oci-based Helm repositories can successfully find updates for their dependencies.

Convert oci to https when fetching index.yaml files

---

composer/lib/dependabot/composer/update_checker/version_resolver.rb
composer/spec/dependabot/composer/update_checker/version_resolver_spec.rb
composer/spec/fixtures/projects/unreachable_private_registry/composer.json

`https://composer.dependabot.com` no longer has a DNS record now that Dependabot was acquired by GitHub. And we can't just stub the URL because the call is happening within the `composer` subprocess, not in our ruby process.
This helpful StackOverflow pointed out that example.com is owned by IANA so should be safe, and port 81 is never expected to respond: https://stackoverflow.com/questions/100841/artificially-create-a-connection-timeout-error
Alternatively, we could use a non-routable IP but that may return different errors depending on the topology of the LAN where it's running.
This is a continuation of https://github.com/dependabot/dependabot-core/pull/6776, as a borked Codespace weirdly pushed a massive commit and force-closed that PR and won't let me re-open it. 😢

Use a URL that won't respond

---

helm/lib/dependabot/helm/update_checker.rb
helm/spec/dependabot/helm/update_checker_spec.rb

Adding validation to check if docker images can be updated before reporting new versions in the helm update checker. Previously, it would report updates even for immutable tags like "latest" which can't actually be updated.
Using the :none option with `can_update?` ensures we're only checking if the Docker image can be updated with its current constraints, consistent with how `latest_resolvable_version_with_no_unlock works` in the base update checker.
Dependabot only attempt to create bump prs when the docker images can be updated

Check docker image in helm can be updated

---

helm/lib/dependabot/helm/update_checker.rb
helm/spec/dependabot/helm/update_checker_spec.rb

Raise and log an error if the helm registry response is a string. Some responses from the Helm registry are strings, which should be returned as YAML after it was parse.
We will log an error if the response from the Helm registry is a string, and the response will be returned as YAML after it was parsed

Raise and log an error if helm registry response is a string

---

python/spec/dependabot/python/version_spec.rb

This adds a test case for an invalid version with dots.
We expect the test to pass, but today it fails with:
```
eval error: Malformed version number string 1.8.0-failed.release.attempt
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:214:in `initialize'
/home/dependabot/dependabot-core/python/lib/dependabot/python/version.rb:43:in `initialize'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
(rdbg)//home/dependabot/dependabot-core/common/lib/dependabot/metadata_finders/base/commits_finder.rb:1:in `tag_matches_version?'
```
The relevant [version pattern regex](https://github.com/dependabot/dependabot-core/blob/6d1c083a7e1d244096b024f255cea5eb9c232358/python/lib/dependabot/python/version.rb#L18-L …

Handle invalid version with dots

---

bun/lib/dependabot/bun/file_fetcher.rb
bun/spec/dependabot/bun/file_fetcher_spec.rb

This change removes the `enable_beta_ecosystems` feature flag check from the Bun ecosystem. The feature flag is no longer needed, and this update ensures that the Bun ecosystem operates without being dependent on this flag, simplifying the code and improving maintainability.
Please ensure that removing this feature flag does not affect any other functionality related to the Bun ecosystem. Since the flag is not in active use anymore, the goal is to eliminate redundant checks while ensuring the Bun ecosystem continues to function as expected without the flag.
- Ensure that the Bun ecosystem functions as expected without any issues after the feature flag check is removed.
- All tests should pass, and there should be no errors related to the feature flag removal or the Bun ecosystem.

Remove feature flag `enable_beta_ecosystems` check from bun ecosystem

---

maven/lib/dependabot/maven/update_checker.rb
maven/lib/dependabot/maven/update_checker/version_finder.rb

This PR fixes the Sorbet typings for the Maven ecosystem in the `UpdateChecker` and `LatestVersionFinder`. These changes ensure that the correct types are used, improving the clarity and correctness of type checking in the Maven-related code paths.
- **Why**: To ensure accurate type checking and to make sure that the types align with the expected behavior in the Maven ecosystem, preventing any type mismatches during runtime.
The change involves adding and refining Sorbet typings for the `UpdateChecker` and `LatestVersionFinder` classes, particularly for the Maven ecosystem. There was a need for more precise type definitions to better align with the functionality of these classes.
I chose this approach because it allows for strong typing and ensures the classes handle Maven-related updates …

Fix Sorbet Typings for Maven Ecosystem in Update Checker and Latest Version Finder

---

.github/workflows/gems-release-to-rubygems.yml
Rakefile

This adds sigstore attestations for our published gems.
We do not need to provide an OIDC token to the sigstore client because by default it will request the token from the GitHub Actions environment: https://github.com/sigstore/sigstore-ruby/blob/9ac72d3c27edcd791c8c831316447f0ab7dfb407/cli/lib/sigstore/cli/id_token.rb#L45-L68
The code inspiration for this change came from:
* https://github.com/84codes/rubocop-eighty-four-codes/pull/16
* https://github.com/rubygems/release-gem/pull/11
You can see an example attestation here: https://rubygems.org/gems/sigstore/versions/0.2.1
Related:
* https://github.com/dependabot/dependabot-core/issues/12009

Add sigstore attestations for our published gems

---

.github/workflows/gems-release-to-rubygems.yml

Rather than inheriting the version of RubyGems bundled with Ruby, let's explicitly match the version of RubyGems specified in `Dockerfile.update-core`:
* This matches the rest of our prod/CI systems... so it feels a bit safer.
* It's more flexible because it lets us decouple the RubyGems version from the Ruby version.
I think this is a good idea overall, but the specific need for this arose because the `--attestations` flag was only recently added to the `gem push` command. So we need this for my recently merged Sigstore attestations PR:
* https://github.com/dependabot/dependabot-core/pull/12025
Luckily, @deivid-rodriguez already put in the effort to update the RubyGems version, so we just need to wire that up into this workflow as well:
* …

Publish gems using the version of RubyGems specified in `Dockerfile.updater-core`

---

Rakefile

Gem publishing was taking a surprisingly long time.
Turns out this is because the `rakefile` task has a 2-second sleep between every publish. I suspect this was originally implemented due to rate limits or network flakiness, years ago when we only had a couple of gems.
However, the world has changed:
* RubyGems now implements separate rate limits for Gem push calls, and they're pretty generous: https://guides.rubygems.org/rubygems-org-rate-limits/
* We publish ~20 gems now, so sleeping for 2s adds up.
So let's only sleep on errors.
The smart fix is to switch to only looping/sleeping on transient errors like `429`'s. But this isn't critical code for us and we rarely hit errors, so the current retry implementation is good enough.

Only sleep on errors

---

swift/Dockerfile

It looks like swift has changed how the keys are returned and now has a redirect as well as returning compressed output rather than plain txt file. You can easily test this by running command locally:
```console
curl --connect-timeout 15 --retry 5 https://www.swift.org/keys/all-keys.asc | gpg --import -
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 12193  100 12193    0     0  17438      0 --:--:-- --:--:-- --:--:-- 17418
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```
This change should fix this step and thus fix swift updater image building. I suspect it is still working in CI because it is fetching those steps from cache and not actually rebuilding them.

Fix swift updater image build

---

bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb
bundler/lib/dependabot/bundler/update_checker.rb
bundler/lib/dependabot/bundler/update_checker/file_preparer.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder/dependency_source.rb
bundler/lib/dependabot/bundler/update_checker/requirements_updater.rb
bundler/lib/dependabot/bundler/update_checker/version_resolver.rb
bundler/spec/dependabot/bundler/file_updater/gemspec_sanitizer_spec.rb
bundler/spec/dependabot/bundler/update_checker/force_updater_spec.rb
bundler/spec/dependabot/bundler/update_checker/latest_version_finder_spec.rb
bundler/spec/dependabot/bundler/update_checker/version_resolver_spec.rb
bundler/spec/dependabot/bundler/update_checker_spec.rb

This change refactors the versioning logic within Bundler by updating the version handling to use `Bundler::Version` instead of `Gem::Version`. The goal is to standardize the versioning system used in Bundler and ensure compatibility with the latest versioning practices. This update will help improve the maintainability and consistency of version comparisons and handling across the Bundler codebase.
- Review the code for any instances where `Gem::Version` is used and ensure it's replaced with `Bundler::Version`.
- Ensure that no regressions or unexpected behavior are introduced as a result of this change, particularly in version comparison logic.
- Make sure that all existing functionality works correctly with the updated versioning system.
- The full test suite passes with no regressions …

Refactor: Update Bundler Versioning to Use Bundler::Version Instead of Gem::Version

---

common/lib/dependabot/package/package_latest_version_finder.rb

This change refactors the `PackageLatestVersionFinder` by updating the returned version types to use `Dependabot::Version` instead of previous types like `Gem::Version`. The goal is to make the filtering and handling of versions more consistent by ensuring the correct, more specific `Dependabot::Version` type is used, particularly for version filtering logic across all package ecosystems. This update improves maintainability and consistency across the codebase, aligning version handling with other parts of Dependabot.
- Review the updates to the version handling logic in `PackageLatestVersionFinder`, especially the transition from `Gem::Version` to `Dependabot::Version`.
- Ensure that no unexpected behavior arises from this change in version typing and that all existing functionality …

Sorbet: Update Returned Version Types for Generic PackageLatestVersionFinder 

---

swift/Dockerfile
swift/spec/dependabot/swift/file_parser_spec.rb

I'm seeing the following error on dependabot jobs where Swift version tools are 6.1. 
`updater | 2025/04/14 10:07:31 ERROR <job_997942662> error: 'repo': package 'repo' is using Swift tools version 6.1.0 but the installed version is 6.0.1`
This fixes that by bumping the version of Swift to 6.1.

Bump Swift version from 6.0 to 6.1

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/NuGetUpdater.Cli.csproj

If an SDK-style project references a .NET Framework version via, e.g., `<TargetFramework>net472</TargetFramework>` _AND_ if the build is done on Windows machines _AND_ if a custom NuGet feed is used that doesn't have the `Microsoft.NETFramework.ReferenceAssemblies.*` packages, dependency discovery can fail.
The solution is to force these packages to be pre-downloaded and installed in the updater image package cache so they don't need to be restored.

prepopulate updater image with framework targeting packs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

WPF project restore can create temporary projects with names like `*_abc123_wpftmp.csproj` that are deleted after MSBuild exists.  When analyzing project restore for dependencies, explicitly remove these temporary project files because they're not necessary for our purposes and can break later update steps.

don't return evaluation for temporary projects

---

bun/lib/dependabot/bun/update_checker/latest_version_finder.rb
bundler/lib/dependabot/bundler/update_checker/latest_version_finder.rb
cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb
common/lib/dependabot/package/package_latest_version_finder.rb
common/lib/dependabot/package/package_release.rb
common/spec/dependabot/package/package_latest_version_finder_spec.rb
common/spec/spec_helper.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb

This change refactors the filtering logic for releases in `PackageLatestVersionFinder` to ensure consistent filtering across different version types. The goal is to apply the same filtering methodology to all releases, making the version filtering more robust and aligned with expected behavior across all ecosystems. This improves the maintainability and flexibility of version filtering.
- Review the changes to the filtering logic for releases and ensure that all filtering now behaves consistently across different release types.
- Check that this update doesn't introduce any regressions or breaking changes in how versions are filtered.
- Verify that the logic for filtering releases works as expected, and the updates don't cause any unexpected behaviors.
- The full test suite passes without …

Refactor: Consistent Filtering of Releases in PackageLatestVersionFinder

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/SpecialFilePatcherTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SpecialImportsConditionPatcher.cs

A `<PackageReference>` element can optionally specify a `GeneratePathProperty="true"` attribute which will result in the creation of a special MSBuild property with the prefix `Pkg` that points to the location where the package was restored and unpacked.  E.g., for a package named `Some.Package` a property named `PkgSome_Package` will be created with a value `/home/user/.nuget/packages/some.package/1.0.0`.
If one of these properties is used to explicitly import a `.props` or `.targets` file, this can cause dependency discovery to fail.
The fix is to expand our pattern of `<Import Project="..." />` values to ignore to also search for the substring `$(Pkg`.

don't import from special `Pkg*` properties

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestDiscoveryWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/BOMHandlingTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/BOMHandling.cs

Explicitly detect byte-order-marks on dependency files and ensure the updated file is the same.
The end-to-end updater was missing an explicit `ContentEncoding` of `base64` so most of this PR is fixing that so that when a BOM _is_ detected, we can set `utf-8` or `base64` as appropriate.
Fixes #12077

maintain BOM status for dependency files

---

docker/lib/dependabot/docker/file_parser.rb
docker/lib/dependabot/docker/update_checker.rb
docker/lib/dependabot/shared/shared_file_parser.rb
docker/lib/dependabot/shared/shared_file_updater.rb
docker/spec/dependabot/docker/common/shared_examples_for_docker_update_checkers.rb
docker/spec/dependabot/docker/file_parser_spec.rb
docker/spec/dependabot/docker/file_updater_spec.rb
docker/spec/dependabot/docker/update_checker_spec.rb

Fixes the issue from #11971, that was due to my PR #11938, and was reverted in #11976
The main issue was that `sha256:` was hardcoded in a lot of places around the docker codebase. By adding `sha256:` to the digest everywhere (which will help with #11943) it broke a lot of these checks.
Specs are updated, and tested with the cli against the dependabot-action repo
`dependabot update docker github/dependabot-action --directory /docker --dep dependabot/dependabot-updater-bun`

Update docker version to include digest if applicable - Fixed

---

docker/lib/dependabot/shared/shared_file_updater.rb

This change fixes a bug in handling Docker Compose image references that include both sha256 digests and normal digests. The issue was that image references with a `sha256:<digest>` or `<digest>` were not being replaced correctly. This PR ensures that both types of digest formats are properly updated in the content.
- The approach for replacing `@sha256:<old_digest>` and `@<old_digest>` with `@sha256:<new_digest>` and `@<new_digest>` ensures that both forms are covered.
- It also updates the image tag replacement to avoid leaving any old tags.
- All existing tests that use Docker Compose image references with either `sha256` or simple digest formats should now pass.
- Any references to `@sha256:<digest>` or `@<digest>` in the YAML files should be correctly replaced by the new digest.
- No …

Fix Docker Compose Digest Handling for sha256 and Normal Digests

---

docker_compose/spec/dependabot/docker_compose/file_parser_spec.rb
docker_compose/spec/dependabot/docker_compose/file_updater_spec.rb

This PR addresses an issue in Docker Compose specs where digests in image references were not correctly prefixed with `sha256:`. Specifically, when a digest is included in Docker Compose image references, it should be in the format `sha256:<digest>`, but this was not being enforced. The change ensures that any digest included in Docker Compose image references will be correctly prefixed with `sha256:`.
- The main focus of this change is on fixing Docker Compose image references where the digest did not include the `sha256:` prefix.
- Please pay special attention to the handling of image digests in the test cases to ensure that this fix is applied consistently.
- All Docker Compose spec tests should pass, and the image digest should now always be prefixed with `sha256:`.
- You can verify …

Fix Docker Compose Specs Related to Requirements Digest with Sha256

---

common/spec/spec_helper.rb

Prevent all the `Coverage report generated for test-process-...` messages from being spammed to `stdout` when running `bundle exec rspec`.
See the upstream issue https://github.com/simplecov-ruby/simplecov/issues/992

Prevent `simplecov` from spamming `stdout`

---

maven/lib/dependabot/maven/package/package_details_fetcher.rb
maven/spec/dependabot/maven/package/package_details_fetcher_spec.rb

This PR fixes an issue in the Maven ecosystem where Dependabot fails to propose updates when the version string contains dashes (`-`). This issue was introduced in `0.309.0`, and the incorrect URL generation for versions containing dashes prevents the updates from being proposed.
- **Issue Addressed**: The issue is caused by https://github.com/dependabot/dependabot-core/pull/12022 where dependency files url is constructed wrong. 
- **Affected Package Ecosystem**: Maven
- **Issue URL**: https://github.com/dependabot/dependabot-core/issues/12096
- The change ensures that version strings containing dashes (`-`) are properly handled when generating URLs for fetching dependency metadata.
- This fix includes updating the dependency files url version string by using `version` to string instead …

Fix Version Update Behavior for Versions with Dashes in Maven Ecosystem

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Run.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestHttpServer.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs

From an internal experiment we found that the API call to `mark_as_processed` at the end of a job should use the HTTP method `PATCH` but was using `POST`.  This PR fixes that.  Most of the change was so this could be directly tested.

`mark_as_processed` api endpoint should use the `PATCH` verb

---

bun/.rubocop.yml
bundler/.rubocop.yml
cargo/.rubocop.yml
composer/.rubocop.yml
gradle/.rubocop.yml
hex/.rubocop.yml
npm_and_yarn/.rubocop.yml
python/.rubocop.yml
silent/.rubocop.yml
updater/.rubocop.yml
uv/.rubocop.yml

The change I previously made in #11885 made Sorbet strict mode opt-out at the ecosystem level. This change tightens that up a little bit, by making it opt-out at the file level. This means that newly added files, anywhere in the repository **must** be Sorbet strict typed.
The intention is that files will be removed from the `Exclude` list as they are strict-typed.
N/A
Rubocop passes

Make Sorbet `strict` mode opt-out at the file-level

---

hex/helpers/lib/parse_deps.exs
hex/spec/dependabot/hex/file_parser_spec.rb

Remove `"master"` branch hardcoding from Hex dependency parsing.
This is broken out from #7131, continuing to address #6202.
The solution here was removing the branch hardcoding from the related test expected values as well. I think `nil` should work there; having both `:ref` and `:branch` set for a git dependency doesn't seem quite right anyway.
Passing tests.

Remove `"master"` branch hardcoding for Hex

---

common/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb
common/spec/dependabot/pull_request_creator/branch_namer/solo_strategy_spec.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb
docker/spec/dependabot/docker/update_checker_spec.rb

The main change from my previous PR (#11977) was to add the digest to the version if the digest changed.
Previously, the version would be only the tag, even if the digest changed and the tag didn't. The version would only include the digest if no tag was present.
The solo-strategy for branch naming had a special case for docker where it checked if the versions were equal (which after my change, they never would be, because either the tag, digest, or both would be different) so this PR fixes that, and also shortens the branch name to just the first 6 characters of the digest vs the whole 64 characters
Example new branch names:
- for an update on `ubuntu` with only a digest change: `dependabot/docker/ubuntu-sha256-183054`
- for an update on `ubuntu` where the tag `17.10` doesn't change, but …

Refactor branch naming strategy for docker dependencies with digests.

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/MockNuGetPackage.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.PackageReference.cs

Two well-known packages, `FSharp.Core` and `Microsoft.Windows.SDK.NET.Ref` are required by the SDK, but possibly with updated version numbers.
This PR scans the installed SDK to mock those packages with whatever is necessary.  This is to prevent continual updates to these tests.  No functional change.

mock well-known SDK packages

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MessageReportTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateOperationBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/ClosePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/CreatePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UpdatePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs

The NuGet end-to-end updater outputs a short report of the operations performed and the log gets a similar treatment.  That output isn't quite proper markdown because list items are indented.
This PR fixes the formatting of those messages to make them proper markdown.

make messages proper markdown

---

nuget/script/run

The NuGet updater script entry point queries the `job.json` file for a native updater flag, but that flag can have two different naming conventions, `nuget_native_updater` vs `nuget-native-updater`.
The previous version did a simple find/replace from `-` to `_` which isn't strictly correct.
This new version uses the built-in `jq` DSL to transform the key names.
No functional change, just future-proofing.
Manually verified locally.

improve native updater experiment flag

---

nuget/updater/common.ps1

A repo's `global.json` file should list an SDK version to install like `8.0.100` but some repos found in the wild list a runtime version like `8.0.0` and we manually handle that case by detecting the third part of `.0` and doing a regular channel installation of `8.0`.
I've now found other repos that only list a channel value like `8.0` so this PR explicitly checks for a two-part version number and the line immediately below it rebuilds the exact same version and does a channel install just like before.
Fixes #12161

allow SDK installation from a two-part version

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

The output of various MSBuild and NuGet operations is scanned to generate appropriate error messages and in once instance we're told that while a package exists on the feed, a specific version isn't present.
This PR updates that error message to include this version information to make investigations easier.

report missing package version when possible

---

terraform/Dockerfile

Making Dependabot work with Terraform 1.11.4.
https://github.com/hashicorp/terraform/releases/tag/v1.11.4
https://releases.hashicorp.com/terraform/1.11.4/
The build output will show if the image will build successfully.

build(deps): bump terraform from 1.11.2 to 1.11.4

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs

PRs that updated lots of dependencies were hard to read so this PR:
1. Simplifies the PR title.
2. Uses a markdown-like list for the commit message.
The tests have good examples of the new behavior.

make long title and commit messages easier to read

---

uv/Dockerfile
uv/helpers/requirements.txt
uv/spec/dependabot/uv/file_parser_spec.rb

Fixes #12127
Hopefully this is as straightforward as it seems in lieu of the ability for Dependabot to support multiple versions of uv.

Upgrade uv to the latest 0.7.1

---

npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/metadata_finder_spec.rb

Escape spaces in NPM dependency URLs so they can be properly queried.
NPM uses the value of the `resolved` property in `package-lock.json` as a dependency's URL.  When this URL is queried to generate a PR description, if this URL contains spaces (not uncommon in Azure DevOps NPM feeds) then the query fails eventually resulting in an empty PR body.
This PR escapes the spaces in the source URL so the URL parse and query is successful.  Similar behavior was observed a few lines down where slashes in a package name are individually escaped.
Manually verified against an internal repo with spaces in the `resolved` property.
Fixes #12172

escape dependency url spaces with `%20` before querying

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

A NuGet update run can either throw exceptions, or politely return an error, depending on exactly what and where it occured.
This PR elevates the returned errors and interrupts the update process.  We already handled thrown errors.
Tests now cover all scenarios.

ensure all errors can be surfaced

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Clone/CloneWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/HttpApiHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/TestApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/IApiHandler.cs

A manual audit of some logs shows that for an unknown error, the common Ruby code hits 3 API endpoints: `record_update_job_error`, `record_update_job_unknown_error`, and `increment_metric`.
This PR updates the native C# updater to do the same.
During this I realized that the design of `IApiHandler` was too complicated so it's been simplified to a single method `SendAsync()` and everything else is an extension method.  This makes unit testing more consistent.

call separate endpoints for unknown errors

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MessageReportTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs

When reporting an `unknown_error` the `error-backtrace` field is expected to be a Ruby callstack.
To prevent errors in the service, the .NET stack trace is now appended to the message and an empty string is used for the Ruby callstack.

move .NET callstack to the message field

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

A manual review of internal logs showed another pattern that NuGet can return when a package isn't found.

add pattern for missing package

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/VersionFinderTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/BadResponseException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs

Found during a manual log audit.
When querying a NuGet feed for updated packages, invalid JSON will cause an unknown error.  This catches that error and transforms it into a well-known error.

surface json parse errors from nuget

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/HttpApiHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TestHttpServer.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/HttpApiHandler.cs

The NuGet native updater submits messages directly to the dependabot server, but in the case of a malformed request the error logs would only report `400 (Bad Request)` or similar.  Some server error messages have a string body that contains additional information.
This PR reads that content and throws an exception with this additional information to make investigations easier.

report content from server error messages in exception

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli.Test/EntryPointTests.Run.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.Project.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/SdkProjectDiscoveryTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

When doing direct dependency discovery with MSBuild, a separate dependency was reported for each target framework, e.g.,:
- `Some.Dependency`/`1.0.0` for `net8.0`
- `Some.Dependency`/`1.0.0` for `net9.0`
That bloats the discovery and results in duplicated work and can even lead to an exception seen in the logs.
The fix is to combine all dependencies that differ only by their target framework.  The result is this:
- `Some.Dependency`/`1.0.0` for `net8.0;net9.0`

combine dependency tfms

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs

When checking for possible updates, an attempt is made to match it with an existing pull request, but this assumption is flawed because it assumes the `UpdatedDependencies` property won't be empty.  When checking for updates to MSBuild SDKs this value _is_ allowed to be empty.
This PR removes a problematic call to `.First()` and replaces it with a call to `.FirstOrDefault()` followed by the appropriate `null` check.

don't crash when checking for updated dependencies for SDKs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MessageReportTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/UnknownError.cs

When an exception is turned into an `unknown_error` for reporting, oftentimes the exception will have the `InnerException` property set with additional information, but that's not currently exposed.
This PR switches to using the `ToString()` method directly on the exception because it includes the message, call stack, and all inner exceptions' messages and callstacks making investigations easier.

include all stack information for unknown errors

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackageReferenceUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackageReferenceUpdater.cs

Similar to #11966, if an out-of-process tool updates `Directory.Packages.props` on disk, ensure subsequent updates don't overwrite the first.
In this case the external process emits a message that's very easy to find and parse to determine if that file was edited.

ensure out-of-proc changes to CPM are recorded

---

.github/workflows/smoke.yml
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/SdkProjectDiscoveryTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

NuGet dependencies are discovered by examining an MSBuild binary log.  Previously we only looked in collections like `RuntimeCopyLocalItems`, etc., but those groups were only populated if a package had runtime assets to contribute like a `.dll`.
If a package didn't contain any runtime assets, e.g., it only provided `.props`/`.targets` _or_ it was a roll-up package meant to pull in others, it wouldn't get reported in the dependency list.
The fix entails tracking the item group `PackageDependencies` which is populated with all NuGet packages used during restore, whether they contain runtime assets or not.  Any package name in that group that we don't have a version for is a package that didn't have runtime assets.  We can then match that package name with the contents of the generated …

report transitive packages with no assembly assets

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

We may need to parse a target framework from a `project.assets.json` file and in certain instances there will be a runtime identifier suffix after a slash which causes the function `NuGetFramework.Parse()` to throw.
The fix is to split on the slash and only parse the first part.  If there was no slash, a single string is returned, so that doesn't have to be special cased.
This fixes an issue found during a manual log audit following yesterday's deploy of #12219.

only parse TFM, not RID from assets JSON

---

hex/Dockerfile
python/Dockerfile
updater/bin/run

We should avoid letting ecosystem logic get into the updater project as it should be agnostic.
Also helps debug things at the container level if it doesn't require any Ruby invocations to set environment variables. I like using Dependabot CLI's `--debug` flag to enter intro an interactive session to debug Proxy issues. However if we're tucking the environment variables into the Ruby it's harder to debug without invoking those scripts.
But I think my first point stands on its own. 
This should be a no-op.

move env vars to ecosystem locations

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/JobErrorBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs

The NuGet libraries will oftentimes repeat a failed HTTP call and eventually throw a `FatalProtocolException` with an inner exception with more specific detail.
This PR delves into the `InnerException` property and if it can generate a better error from that, it will use it, otherwise the entire outer exception is used to include as much data as possible.
A manual scan of logs showed that a `FatalProtocolException` could be wrapping an issue where the server was really returning `403` which should have been mapped to `private_source_authentication_failure` and this now fixes that.
The same log scanning exercise showed instances of private NuGet feeds returning a `5xx` error code, sometimes wrapped in NuGet's `FatalProtocolException`, sometimes bare.  This turns all of those exceptions …

improve exception=>error mapping

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/HttpApiHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/IApiHandler.cs

Implement retry logic around all API calls, mirroring what happens in the common Ruby code [here](https://github.com/dependabot/dependabot-core/blob/845d4f27f03f7bd62e12891ca9651f93768e7c35/updater/lib/dependabot/api_client.rb#L52-L59).

add retry logic to API calls

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/JobErrorBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs

Seen during a manual log review.
Querying a NuGet feed can throw a `FatalProtocolException` with an inner `HttpRequestException` with no status code, but another internal `HttpIOException` indicating the server hung up on us.
Fortunately this pattern is very easy to match.

expand pattern for bad feed responses

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

If NuGet can't parse a `packages.config` file we're explicitly told that as well as why.
This PR expands our error pattern matcher to pull out this information so we can report `dependency_file_not_parseable`.
Found during a manual scan of the logs.

expand pattern for unparseable files

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Found during a manual log scan.
This adds another error message pattern that was missed before.

add missing pattern for unauthenticated feed

---

terraform/Dockerfile

Making Dependabot work with Terraform 1.12.0.
https://github.com/hashicorp/terraform/releases/tag/v1.12.0
https://releases.hashicorp.com/terraform/1.12.0/
The build output will show if the image will build successfully.

build(deps): bump terraform from 1.11.4 to 1.12.0

---

uv/lib/dependabot/uv/file_updater/lock_file_updater.rb
uv/spec/dependabot/uv/file_updater/lock_file_updater_spec.rb

Addresses: https://github.com/dependabot/dependabot-core/issues/11889
Private registries specified by user config are included as indexes/default-indexes in the `uv lock` command allowing dependencies to be resolved from sources other than the default public registry
Accomplished by
* Generating lock command options based on python-index credentials provivded
* Passing lock command options to pre-existing `uv lock` execution.
It appears the uv code can already determine the latest version of a dependency hosted on a private registry, it just doesn't pass the relevant indexes during `uv lock` (per example in linked issue)
Implementation is essentially based off of [uv/file_updater/compile_file_updater.rb](https://github.com/dependabot/dependabot-core/blob/main/uv/lib/dependabot/uv/file_upda …

Use private registries when updating uv lockfile dependencies

---

.rubocop.yml
bun/lib/dependabot/bun/update_checker.rb
common/dependabot-common.gemspec
common/lib/dependabot/utils.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb
nuget/lib/dependabot/nuget/cache_manager.rb
nuget/lib/dependabot/nuget/file_fetcher.rb

This is part of several PRs to split the Ruby 3.4 upgrade in https://github.com/dependabot/dependabot-core/pull/11681 out into lower-risk PRs.
This bumps the targeted Ruby version in Rubocop to 3.3 which called unnecessary requires of "set" as it's loaded automatically as of Ruby 3.2

Bump Rubocop target Ruby version from 3.1 to 3.3

---

common/lib/dependabot/clients/bitbucket.rb

In Ruby 3.4 `URI::DEFAULT_PARSER` changed from `RFC2396` to `RFC3986`[^1]. This change makes our use of `RFC2396` explicit instead of implicit.
This migration was partially completed in #12170. This change just finishes the migration.
This is a part of the Ruby 3.4 upgrade #11681
We should migrate from RFC2396 to RFC3986 at some point in the future. This work is tracked in #12327
[^1]: https://github.com/ruby/uri/pull/107

Explicitly use `RFC2396` instead of `DEFAULT_PARSER`

---

common/lib/dependabot/pull_request_creator/branch_namer.rb
common/lib/dependabot/pull_request_creator/branch_namer/multi_ecosystem_strategy.rb
common/spec/dependabot/pull_request_creator/branch_namer/multi_ecosystem_strategy_spec.rb
common/spec/dependabot/pull_request_creator/branch_namer_spec.rb

Currently we are using dependency groups for branch naming, but we need to use the multi-ecosystem name directly for branch naming in multi-ecosystem updates. This change updates the branch naming strategy to use the `multi_ecosystem_name` parameter to generate consistent branch names for updates spanning multiple package managers.
The branch names now follow the pattern `dependabot/{multi_ecosystem_name}-{hash}` and maintain deterministic generation regardless of dependency order.
Branch names use the multi-ecosystem name directly instead of dependency group references when running multi-ecosystem updates

Create branch naming strategy for multi-ecosystem updates

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateOperationBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateWorkerTests.Mixed.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs

Make PR title and commit messages more closely match those from other ecosystems where possible.
For the high level stuff, you should really only need to look at `PullRequestTextTests.cs`.
One thing of note: to generate the proper messages we need to know the old package version that we weren't previously tracking.  To make this easier, the generation of `DirectUpdate`, `PinnedUpdate`, and `ParentUpdate` messages always defaults to `null` for the newly added `OldVersion` property.  Then after the update was performed, the old dependency version is pulled out of the original project dependency discovery.  This way we only need to perform this mapping once.
The exact titles and commit messages couldn't be reasonably copied, especially when directory names are involved because an update …

improve pr title and commit message generation

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs

PR #12343 missed a scenario where the PR prefix is separated from the rest of the title.  Thanks to @samtrion for finding this so quickly after yesterday's merge.  Implementation inspired by `pr_name_prefixer.rb` line 106.

ensure padding after prefix

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb

Currently we are stripping out `pnpm-workspace.yaml` when are creating workspace bump pull requests,
**Attempt to fix:** https://github.com/dependabot/dependabot-core/issues/11953
n/a 
Pull requests that update pnpm workspace yaml files will now be included in the bump pull request

`pnpm-workspace.yaml` should not be considered a support file

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/UpdateOperationBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs

Issue found during a manual scan of the logs.
The list of updates performed is matched against the initially reported dependencies so the exact update can be tracked.  If in the process of updating a package a new transitive dependency came along, there won't be a previous version of the dependency.
The fix is to change a call to `.Single()` to `.SingleOrDefault()` and add some null-safe navigation.

don't assume a previous dependency could be found

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdateHandlers/RefreshVersionUpdatePullRequestHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/ClosePullRequest.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshGroupUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshVersionUpdatePullRequestHandler.cs

Reviewing some internal logs, the service will sometimes return a `400` when trying to call `close_pull_request` or `update_pull_request`.  Examining the service code reports that the body of those requests is expected to contain the same set of dependency names that started the job, not just reporting the offending dependencies.
To make this easier to use going forward, the numerous calls to `close_pull_request` were replaced with a helper that takes the actual job so the dependency names can be correctly constructed.
The calls to `update_pull_request` are more complicated and were patched in-place.

always report the same dependency set when closing or updating

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdateHandlers/GroupUpdateAllVersionsHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/GroupUpdateAllVersionsHandler.cs

The `group_update_all_versions` handler should skip processing an update group where an existing group PR already exists to avoid duplicate PRs.

don't create duplicate PRs

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs

The PR title is created from all package version updates that occurred, but if the same update was performed in multiple locations, we can collapse the versions so that instead of getting this:
```
Bump Some.Package to 1.2.3, 1.2.3
```
We get a single:
```
Bump Some.Package to 1.2.3
```

don't repeat the same version number in pr title

---

python/lib/dependabot/python/package/package_details_fetcher.rb
uv/lib/dependabot/uv/package/package_details_fetcher.rb

**Related Issue:** 
- https://github.com/dependabot/dependabot-core/issues/11902
Fix a bug where Dependabot fails to detect the correct latest version of a pip package when a final release (e.g. `0.45.0`) follows one or more pre-releases (e.g. `0.45.0a1`, `0.45.0rc1`).
In https://github.com/dependabot/dependabot-core/pull/11630, we introduced a `uniq` check for versions, which unintentionally caused final releases to be filtered out when preceded by pre-releases.
This PR reverts that change by removing the `uniq` check, restoring the previous behavior where pre-releases and final releases are treated as distinct entries.
---
The regression was introduced in https://github.com/dependabot/dependabot-core/pull/11630 as part of the cooldown implementation. The added `uniq` version filtering …

Fix pip latest version detection when final releases follow prereleases

---

dotnet_sdk/lib/dependabot/dotnet_sdk/package/package_details_fetcher.rb
dotnet_sdk/lib/dependabot/dotnet_sdk/update_checker.rb
dotnet_sdk/lib/dependabot/dotnet_sdk/update_checker/latest_version_finder.rb
dotnet_sdk/spec/dependabot/dotnet_sdk/package/package_details_fetcher_spec.rb
dotnet_sdk/spec/dependabot/dotnet_sdk/update_checker/latest_version_finder_spec.rb

Add support for security advisories to the `dotnet-sdk` ecosystem.
Currently, if `security-advisories` are passed as a Dependabot job they are ignored, and the dotnet SDK is updated to the latest version, regardless of what the advisories say.
This change migrated `LatestVersionFinder` to use the `Dependabot::Package::PackageLatestVersionFinder` abstract class, and moves much of the API logic to `PackageDetailsFetcher`. This is the standard pattern in much of the rest of Dependabot.
I've also added a relevant smoke test in https://github.com/dependabot/smoke-tests/pull/296

Add support for `security-advisories` to `dotnet-sdk`

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/FrameworkChecker/FrameworkCompatibilityServiceFacts.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/FrameworkChecker/FrameworkCompatibilityService.cs

Before target frameworks like `netstandard2.0` existed, cross-platform and TFM compatibility was accomplished via portable class libraries (PCL).
Package compatibility checks previously returned false if `IsPCL` was `true`, but this PR fixes that by iterating through all PCL profiles in NuGet, determining if a "regular" TFM is compatible with it, then checking each other TFM for compatibility with _that_.  If found, the final framework is marked as being compatible with the PCL.
The reason for the double-lookup is because the NuGet source only defines compatible TFM ranges for the portable profiles.  E.g., PCL Profile 111 `portable-net45+win8+wpa81` reports as supporting the range of `netstandard1.0` through `netstandard1.1`, but a project targeting `netstandard2.0` can absolutely …

add portable profiles to framework compatibility checks

---

common/lib/dependabot/command_helpers.rb
common/lib/dependabot/shared_helpers.rb
common/spec/dependabot/command_helpers_spec.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb

Fix a bug where Dependabot gets stuck during `npm install` when `ERESOLVE` peer dependency conflicts occur. In affected cases, the process remains active without producing output, causing jobs to hang for extended periods or indefinitely.
This change introduces support for early termination by observing command output using the `OutputObserver` interface. When a known ERESOLVE pattern is detected (e.g., invalid peer dependency resolution loops), we gracefully stop the process and propagate the failure early.
This affects:
- dependabot-core command execution logic (`CommandHelpers.capture3_with_timeout`)
- npm command wrapper to utilize output observation and early exit
Fixes:
- https://github.com/github/dependabot-updates/issues/9872
- githubcustomers/Morgan-Stanley#699
We now use an …

Fix: Terminate NPM processes early on peer dependency conflicts using OutputObserver

---

maven/lib/dependabot/maven/file_updater.rb
maven/spec/dependabot/maven/file_updater_spec.rb
maven/spec/fixtures/poms/transitive_dependency_pom_dep_management_exist.xml
maven/spec/fixtures/poms/transitive_dependency_pom_version_not_defined_no_namespace.xml
maven/spec/fixtures/poms/transitive_dependency_pom_version_not_defined_with_tabs.xml

This PR updates the XML parser that is used to add new elements to the `pom.xml` file. Previous approach was using Nokogiri formatter that removed blank lines and makes some unrelated changes to directly adding dependency entries. REXML provides more flexibility in modifying the XML structure and allows to manually format added elements.
New logic also includes manual indentation work. `file_updater` attempts to determine indentation size by looking at children of `<project>` element and construct indentation relatively for all children that are being created. This produces changes that include much less unrelated changes to the file.
Unit tests are updated to also validate that indentation is correct and test cases are exist for 2 space indentation, 4 space indentation, and tabs.
PRs for …

Update XML parser to manually format newly added elements.

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/RunCommand.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatedDependencyListTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/TemporaryDirectory.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ModifiedFilesTracker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/CreateSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/GroupUpdateAllVersionsHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/IUpdateHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshGroupUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshVersionUpdatePullRequestHandler.cs
nuget/updater/main.ps1

Mature .NET repos with NuGet packages are often built only on Windows with a case-insensitive filesystem.  This can cause issues with the NuGet updater because it does much of its work by calling the external tool `dotnet` and `MSBuild`.  Since we can't intercept their filesystem access, this can cause a problem if a `.csproj` contains the line `<Import Project="build/versions.props" />` but the file in the repo and on disk is named `build/Versions.props` (note the upper-case `V`).
The fix is to allow the updater access to two paths: `$DEPENDABOT_REPO_CONTENTS_PATH` as before and a new `$DEPENDABOT_CASE_INSENSITIVE_REPO_CONTENTS_PATH` which is a layer over the same storage, but with a case-insensitive filter on top.  (More on that later.)
Most of the changes in this PR are plumbing …

enable case-insensitive file operations

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandler.cs

The NuGet updater was doing a less-than check for vulnerable dependencies by name vs. total dependencies by name, but that doesn't account for the possibility that a scan could return a certain dependency for two projects, one where it's actually up to date and another where it's vulnerable and needs to be processed.
The fix is to do a zero check instead of less-than before closing an existing pull request and declaring it up-do-date.
Issue found from manual log scan.

only close with `up_to_date` if there are no operations to perform

---

common/lib/dependabot/source.rb
common/spec/dependabot/source_spec.rb

Add support for **OnPrem** Azure DevOps repository URLs (currently only Hosted Azure DevOps urls are supported: `https://dev.azure.com`)
Enhance `organization` and `project` methods in `source.rb` to correctly extract organization and project names.
Add tests in `source_spec.rb` to validate behavior for On-Prem Azure DevOps configurations.
See also: #12364
current implementation, executed with this source configuration (using dependabot cli)
```yaml
"source": {
"provider": "azure",
"repo": "tfs/CollectionName/ProjectName/_git/RepositoryName",
"directory": "/",
"hostname": "azure-onprem-url.domain.org",
"api-endpoint": "https://azure-onprem-url.domain.org:/tfs/"
},
```
results in a bad repository url:
```
##updater | INFO <job_update_0_nuget_all> Submitting CsvHelper pull request for …
```

Add support for `OnPrem` Azure DevOps in `Dependabot.Source`

---

updater/Gemfile.lock

This resolves build failures with GCC 15. Related to #12508 and #12545
Before this change, running `bundle install` resulted in the following build failure
<details>
<summary>Details</summary>
```
current directory: /home/jamie/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/google-protobuf-4.28.2/ext/google/protobuf_c
/home/jamie/.local/share/mise/installs/ruby/3.4.4/bin/ruby extconf.rb
creating Makefile
current directory: /home/jamie/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/google-protobuf-4.28.2/ext/google/protobuf_c
make DESTDIR\= sitearchdir\=./.gem.20250705-2604-o0ps3o sitelibdir\=./.gem.20250705-2604-o0ps3o clean
current directory: /home/jamie/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/google-protobuf-4.28.2/ext/google/protobu …
```

Bump `google-protobuf` from `4.28.2` to `4.31.1` to fix GCC 15 incompatibility

---

Gemfile.lock

This PR adds the missing checksum for the `commonmarker` gem's `arm64-darwin` platform variant in the main Gemfile.lock. The checksum was missing from the CHECKSUMS section while being present for other platforms like `x86_64-linux`.
This ensures consistency across all platform variants of the gem and maintains the integrity verification that Bundler provides through checksums.
The `commonmarker` gem is already an established dependency specified in `common/dependabot-common.gemspec` as `commonmarker (~> 2.3`. This change only adds the missing checksum for the Apple Silicon Mac platform variant - no functional changes to dependencies.
The checksum was likely missing because the Gemfile.lock was last updated on a different platform, and running `bundle install` on an Apple Silicon Mac …

Add missing checksum for commonmarker arm64-darwin platform

---

bin/bump-version.rb

Fixes LoadError: `cannot load such file -- sorbet-runtime`, by reverting changes to `bin/bump-version.rb` in #12490
A sorbet typing [PR](https://github.com/dependabot/dependabot-core/pull/12490) has introduced an error when running `bin/bump-version.rb`:
```
Run NEW_VERSION=$(bin/bump-version.rb patch)
NEW_VERSION=$(bin/bump-version.rb patch)
echo "New version is: $NEW_VERSION"
echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
shell: /usr/bin/bash -e {0}
<internal:/opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': cannot load such file -- sorbet-runtime (LoadError)
from <internal:/opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
from bin/bump-version.rb:5:in '<main>' …
```

Fix gems-bump-version workflow by removing sorbet-runtime

---

python/lib/dependabot/python/package/package_details_fetcher.rb
python/lib/dependabot/python/update_checker/latest_version_finder.rb
python/spec/dependabot/python/package/package_details_fetcher_spec.rb
python/spec/dependabot/python/update_checker_spec.rb
uv/lib/dependabot/uv/package/package_details_fetcher.rb
uv/lib/dependabot/uv/update_checker/latest_version_finder.rb
uv/spec/dependabot/uv/package/package_details_fetcher_spec.rb
uv/spec/dependabot/uv/update_checker_spec.rb

This PR removes the deprecated cooldown feature flag usage across the Python ecosystems: "python" and "uv".
The feature flag was originally used to control behavior related to dependency resolution cooldowns. Now that the cooldown logic is permanently enabled and stable across all Python package managers (pip, poetry, pipenv, pip-tools, uv), the flag and associated conditional logic are no longer needed.
This cleanup helps simplify the codebase, reduce configuration complexity, and eliminate dead code specific to Python package management.
The Python ecosystems had consistent patterns for how the flag was used. In each case, I ensured the removal preserved the current behavior (i.e., as if the flag were always enabled).
Key changes:
- `python` ecosystem: Removed …

Remove deprecated cooldown feature flag for Python ecosystems: python, uv

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/CreateSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/GroupUpdateAllVersionsHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshGroupUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshVersionUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdateOperationBase.cs

Don't emit file names in a generated PR body.  It's unnecessary at that point because the user can simply look at the changed files to get the same information, but it _is_ still output to the log to make investigations easier.

cleanup nuget pr body text

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/RunWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/FileWriters/FileWriterWorkerTests_MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/FileWriters/FileWriterWorker.cs

From a manual scan of the telemetry from the recent `nuget_use_new_file_updater` experiment.
When calculating file paths to watch for possible edits, use the initial project's starting directory, since that's where the workspace discovery object came from.  Previously each individual project directory was used, which is incorrect because workspace discovery is all relative to the first directory scanned.

use initial project directory when computing updated file paths from project discovery

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/FileWriters/XmlFileWriterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/FileWriters/XmlFileWriter.cs

Part of the ongoing `nuget_use_new_file_updater` experiment work.
Explicitly restrict the allowed project extension to `.csproj`, `.vbproj`, and `.fsproj` and the allowed additional files to be the same plus `.props` and `.targets`.
Found during a manual scan of the telemetry.

ensure project is supported file

---

.github/workflows/smoke.yml

PR #12638 had to temporarily redirect the smoke test branch but that work is now done so the branch can be restored to `main`.
Composer failure is addressed in dependabot/smoke-tests#311
Swift failure is tracked in #12647

reset smoke test branch to main

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/HttpApiHandlerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MessageReportTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/PrivateSourceTimedOutException.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/PrivateSourceTimedOut.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Report a timeout exception instead of letting it get turned into an `unknown_error`.
From a manual scan of the telemetry.

check output for timeouts

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/JobErrorBaseTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Utilities/MSBuildHelperTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/JobErrorBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs

Sometimes a NuGet feed will return a corrupt `.nupkg`.  This PR catches the relevant exception and turns it into a `private_source_bad_response` instead of surfacing it as `unknown_error`.
Example stack trace:
```
System.IO.InvalidDataException: Central Directory corrupt.
---> System.IO.IOException: Invalid argument : '/home/dependabot/.nuget/packages/fluentassertions/8.5.0/fluentassertions.8.5.0.nupkg'
at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
--- End of inner exception stack trace ---
at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
at …
```

classify additional error shapes

---

bun/lib/dependabot/bun/update_checker/latest_version_finder.rb
npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb

Fix cooldown filtering for distribution tag versions (like `latest`, `next`, `beta`) in npm/yarn and bun ecosystems. Currently, when cooldown periods are configured, distribution tag versions bypass cooldown filtering and can update to versions that should be blocked.
Added a `cooldown` parameter to `version_from_dist_tags` method and apply cooldown filtering when `cooldown: true` is passed. This ensures distribution tag versions respect the same cooldown rules as regular releases.
- Distribution tag versions will be filtered by cooldown settings when enabled
- Dependencies with cooldown configurations won't update to versions within the cooldown period, even if tagged as `latest`
- Cooldown functionality works consistently across npm/yarn and bun ecosystems

Fix cooldown filtering for latest distribution tags in npm/yarn and bun

---

omnibus/dependabot-omnibus.gemspec

This change resolves dependency version conflicts that occur when trying to update `dependabot-omnibus` from 0.321.2 to 0.322.1. The issue stems from `dependabot-vcpkg` and `dependabot-rust_toolchain` being manually published at version 0.321.2 (which depend on `dependabot-common = 0.321.2`) while the new omnibus version depends on `dependabot-common = 0.322.1`.
The conflict prevents users from updating to the latest omnibus version with this error:
```
Because every version of dependabot-vcpkg depends on dependabot-common = 0.321.2 and dependabot-omnibus >= 0.322.1 depends on dependabot-common = 0.322.1, every version of dependabot-vcpkg is incompatible with dependabot-omnibus >= 0.322.1.
```
This affects users trying to upgrade their dependabot-omnibus dependency in projects like …

fix: Comment out vcpkg and rust_toolchain deps in omnibus to resolve version conflicts

---

Rakefile

Reverts dependabot/dependabot-core#12656 because the problem related to https://github.com/rubygems/rubygems/issues/8836 is resolved.

Revert "Disable ecosystems from rakefile to fix gem release"

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Analyze/VersionFinderTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/ApiModel/CooldownTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/ApiModel/JobTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/MiscellaneousTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/SerializationTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/AnalyzeWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/DependencyInfo.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Analyze/VersionFinder.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Cooldown.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/ApiModel/Job.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/CreateSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/GroupUpdateAllVersionsHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshGroupUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshSecurityUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/UpdateHandlers/RefreshVersionUpdatePullRequestHandler.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/DependencyConflictResolver.cs

This PR implements the package update cooldown feature for NuGet and is behind the new experiment flag `enable_cooldown_for_nuget`.  Separate internal PR will be submitted adding that flag.
The new `cooldown` property was added to the job file and is parsed based on the [common ruby parser](https://github.com/dependabot/dependabot-core/blob/39105f4b8bc2f09066730ae52590245be2d45afb/updater/lib/dependabot/job.rb#L476).
The `AnalyzeWorker` class checks all available package versions and returns the appropriate set, so the high-level work is done there by checking the package metadata for a publish date and passing the appropriate info to the `Cooldown.IsVersionUpdateAllowed` method.  The function `RunWorker.GetDependencyInfo` will include the cooldown object if appropriate and that …

implement package update cooldown feature for nuget

---

helm/lib/dependabot/helm/update_checker.rb

Removed Feature Flag and Added check for the user if not willing to opt cooldown in scan. This restriction will allow user to escape cooldown and dependabot scan will also not be scanning code related to cooldown.
This will help to reduce scan time if user does not want to scan using cooldown option.

Removed Feature Flag and Added check for the user if not willing to opt cooldown in scan.

---

helm/lib/dependabot/helm/helpers.rb
helm/lib/dependabot/helm/update_checker.rb
helm/spec/dependabot/helm/update_checker_spec.rb

Core currently handles private registry authentication directly, but it doesn't have proper access to credentials and violates our architecture where authentication should happen at the proxy layer. This change aligns Helm/ORAS with other package managers and enables proper proxy-based authentication.
Fixes authentication failures with private Helm registries and prepares for implementing basic auth in the proxy.
I am completely removing all places where helm login/oras login were called, there will be a follow up pr replacing this implementation 
All `helm login` and `oras login` CLI calls removed

Removing helm and oras login command

---

updater/lib/dependabot/api_client.rb
updater/lib/dependabot/service.rb
updater/lib/dependabot/update_files_command.rb
updater/lib/github_api/dependency_submission.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/dependabot/service_spec.rb
updater/spec/dependabot/update_files_command_spec.rb
updater/spec/fixtures/bundler_sinatra_app/original/Gemfile
updater/spec/fixtures/bundler_sinatra_app/original/Gemfile.lock
updater/spec/github_api/dependency_submission_spec.rb

This pull request introduces an experiment to emit the dependency data available in an Dependabot Update job to the repository as a payload for the [Dependency Submission API](https://docs.github.com/en/rest/dependency-graph/dependency-submission).
The payload is proxied via the Dependabot backend to the GitHub API using the existing job token Authentication pattern rather than submitted directly.
This experiment is being used to gather examples of the data available to Dependabot jobs for some internal testing right now, we do not plan to make this available as a feature in the short-term so the implementation has been limited to the updater component rather than `dependabot-core` for more general purpose use.
The client API will raise on errors, however the backend implementation is …

[Experiment] Transform the dependency list into a dependency submission payload 

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Clone/CloneWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Clone/CloneWorker.cs

Adds a scenario that we already had for Azure DevOps.
Since ADO and GitHub on-prem use similar repo schemes, the switch expression was simply expanded.

allow custom hostname for github repos

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/FileWriters/XmlFileWriterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/FileWriters/XmlFileWriter.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/XmlExtensions.cs

This PR fixes an error found during a manual scan of the error logs.
When it's necessary to add an `<ItemGroup>` element to a project, don't cast the root object to `IXmlElementSyntax`.  Instead use the `RootSyntax` property which has everything we need.
This also required an update to make the newlines configurable in an existing helper function.

fix incorrect cast when adding child xml element

---

common/lib/dependabot/file_fetchers/base.rb
updater/lib/dependabot/file_fetcher_command.rb

We have a community [PR](https://github.com/dependabot/dependabot-core/pull/12532) to pass sorbet related spec we need to add Sorbet type strict for this file in updater.
It should pass all test cases.

Fixed sorbet type strict error.

---

updater/lib/dependabot/update_files_command.rb
updater/spec/dependabot/update_files_command_spec.rb

**This fixes an experiment-only bug**
When testing this experimental feature, I realised there was a slip up in the in unit tests and the method signature used in the `update_files_command.rb` was that of the `api_client` and not the `service` shim that sits in between the two.
```
updater | 2025/08/05 14:43:17 ERROR <job_1069005148> wrong number of arguments (given 1, expected 0)
2025/08/05 14:43:17 ERROR <job_1069005148> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/signature.rb:204:in 'T::Private::Methods::Signature#each_args_value_type'
updater | 2025/08/05 14:43:17 ERROR <job_1069005148> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:227:in …
```

[Experiment] Fix incorrect method signature when calling the Dependency Submission via Dependabot service

---

updater/lib/dependabot/update_files_command.rb

This branch promotes the payload logging to `info` temporarily as the backend service is designed to be unobtrusive so it's easier for us to see the payload in job logs when we see a snapshot being rejected while we're iterating.
N/A - this is just making it a little easier for us to work transparently
I can see the generated payload in my test job logs.

[Experiment] Log the submission payload at info level for now

---

nuget/Dockerfile

Add environment variable to disable Nerdbank.GitVersioning
This is a workaround until something like #4660 is implemented.

enable updates for repos that consume the Nerdbank.GitVersioning package

---

nuget/updater/main.ps1

I used the wrong operator to perform a logical AND operation.  I should have used `-and` because in PowerShell the `&&` operator is used to chain commands not predicates.

use proper logical and operator

---

bundler/lib/dependabot/bundler/file_parser.rb
common/lib/dependabot/dependency_file.rb
common/spec/dependabot/dependency_file_spec.rb
updater/lib/github_api/dependency_submission.rb
updater/spec/github_api/dependency_submission_spec.rb

The Dependabot updater needs to know about quite a lot of files to do its job, often needing information from lockfiles about dependencies in order to affect changes in manifests.
When it comes to graphing the dependencies used by a project, we generally only need to examine lockfiles for the relevant information as they will know things manifest do not provide like:
- the exact versions used
- any transitive dependencies that are pulled in by direct dependencies
- the relationships between dependencies as its ancestors decedents
If we look at the snapshots being generated for a Ruby project by Dependency Graph's existing source-based parser for the Sinatra example in our tests, we see 28 dependencies, all of which are attributed to the Gemfile.lock:
If we take the submission payload …

[Experiment] Introduce DependencyFile#priority to control graph generation

---

go_modules/Dockerfile
go_modules/lib/dependabot/go_modules/resolvability_errors.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb

Bumps Go to 1.25 which allows us to revert the change in #12230 where we manually download a CL to avoid undesirable toolchain changes.
Feel free to read the reason why this was added over in #12230. 
Tests continue to pass.

bump to Go 1.25

---

.github/issue-labeler.yml

- fixes #12669
Anytime anyone used `go` in their post, it would get labelled with the Go ecosystem label. So every Cargo issue was also a Go issue since `go` is in `cargo`. 
We probably need a better system for customers to select the ecosystem but this is an improvement for now.

prevent mislabeling Go issues

---

npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb
npm_and_yarn/spec/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater_spec.rb

Fixing the npm error on the gem release PR
PR: https://github.com/dependabot/dependabot-core/pull/12900
Failing CI: https://github.com/dependabot/dependabot-core/actions/runs/17136748425/job/48614480727?pr=12900
Related PR updates: https://github.com/dependabot/dependabot-core/commit/35e0d994d28b0370f6a3edfa3a64f5f5cb19a358#diff-3bef8da3dc328cdacd3164c9818a8d9dd8a0969def3d06e5230cd3aa64f32f18R427
Ran rspec in local ensured no errors

NPM error found on release PR is fixed here

---

updater/lib/dependabot/pull_request.rb
updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb
updater/spec/dependabot/pull_request_spec.rb
updater/spec/dependabot/updater/operations/refresh_security_update_pull_request_spec.rb

#12821 contained a fix which allows the npm updater to update a package to multiple versions within a security update, as this is sometimes the best and only way to resolve a security vulnerability. Unfortunately, refreshing a PR that updates a single package to multiple versions is not handled properly and this PR has a fix.
The core issue is that the code to refresh a security update PR did not properly deduplicate the list of modified dependencies when comparing it to the dependencies associated with the job. This causes the updater to close the PR instead of updating it. Here's an example: https://github.com/jasonpaulos/test-dependency-repo/actions/runs/17105333309/job/48512654569
Additionally, I found that the equality code for PullRequest objects was not correct, especially when a …

Fix issues with multi-version dependency changes when refreshing security update PRs

---

.github/workflows/smoke.yml
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/PullRequestTextTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/PullRequestTextGenerator.cs

When generating a PR title, the old version number is mentioned if only a single version update was performed.  If the same update was performed in multiple directories, however, this didn't happen.
The fix is to get the distinct set of old and new version numbers and only _then_ see if it's appropriate to mention the old version number.
Swift smoke test failure due to #12647.

include old version number whenever possible

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/FileWriters/XmlFileWriterTests.cs

Updating a wildcard to a specific patched version is a supported scenario, but we didn't have a test for it.

add missing test case

---

updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb
updater/spec/dependabot/updater/operations/create_group_update_pull_request_spec.rb

This PR integrates `GroupDependencySelector` with `CreateGroupUpdatePullRequest` to fix the "superset problem" where group PRs were including dependencies outside the group's scope. The integration adds filtering after compilation to ensure group PRs only contain dependencies that belong to the group.
The filtering is implemented in the `dependency_change` method and gated behind the `:group_membership_enforcement` feature flag for backward compatibility. I tested the integration by mocking `compile_all_dependency_changes_for` to verify the correct workflow level.
All 5 new tests pass, confirming that filtering works when enabled and is bypassed when disabled. Existing functionality remains intact (68/68 operation tests pass), so group PRs will now correctly include only dependencies that …

Add `GroupDependencySelector` integration to `CreateGroupUpdatePullRequest`

---

go_modules/lib/dependabot/go_modules/file_fetcher.rb
go_modules/lib/dependabot/go_modules/file_parser.rb
go_modules/lib/dependabot/go_modules/file_updater.rb
go_modules/lib/dependabot/go_modules/file_updater/go_mod_updater.rb
go_modules/lib/dependabot/go_modules/package/package_details_fetcher.rb
go_modules/lib/dependabot/go_modules/resolvability_errors.rb
go_modules/lib/dependabot/go_modules/update_checker.rb
go_modules/lib/dependabot/go_modules/update_checker/latest_version_finder.rb
go_modules/spec/dependabot/go_modules/file_fetcher_spec.rb
go_modules/spec/dependabot/go_modules/file_parser_spec.rb
go_modules/spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb
go_modules/spec/dependabot/go_modules/file_updater_spec.rb
go_modules/spec/dependabot/go_modules/package/package_details_fetcher_spec.rb
go_modules/spec/dependabot/go_modules/update_checker/latest_version_finder_spec.rb
go_modules/spec/dependabot/go_modules/update_checker_spec.rb

In order for customers to leverage go proxy servers and/or to configure environment variables used by go to determine how to resolve dependencies, we'll now do two things:
- If a `go.env` file is present at the root of the repository, we'll pull it in and tell the Go toolchain to use it.
- If a credential for a goproxy_server is passed in, and no `go.env` exists, we export the URLs from the credentials as `GOPROXY`, allowing the toolchain to use it. By default we also append `direct` so that direct access to dependencies is still possible.
This should give customers all the flexibility they need to configure how go mod accesses dependencies for their projects, with nice defaults.
The approach I've taken here is to export these values at the file fetching step, from here on the toolchain …

Add support for goproxy_server and go.env files

---

Rakefile

This is a follow-on to:
* https://github.com/dependabot/dependabot-core/pull/12984
A few tweaks:
* If we get to this point, the `bump-version` has already completed successfully and bumped the version in the Gemfile. So nothing more needs to happen there and once the PR was merged, the branch should have auto-deleted.
* So the only thing that needs to happen is to re-run the `gems-release-to-rubygems.yml` workflow again. However, because the bug appears to be in GitHub Actions, re-running the job within that actions UI didn't fix it... we needed to trigger a completely new copy of the runner/action. 
* And the only way to do that is to have a new GitHub release. So we need to delete the previously created git tag, and publish a new GitHub release using the same version.

Clarify error message

---

updater/lib/github_api/dependency_submission.rb
updater/spec/dependabot/api_client_spec.rb
updater/spec/github_api/dependency_submission_spec.rb

Having a timestamp always changing makes smoke tests harder, we'd have to implement an ignore of that field. Easier to remove it and add it back in the server.

removing timestamp which makes it harder to smoke test

---

rust_toolchain/lib/dependabot/rust_toolchain/update_checker/latest_version_finder.rb
rust_toolchain/spec/dependabot/rust_toolchain/update_checker/latest_version_finder_spec.rb

When comparing dated Rust toolchain releases, we need to ensure that the release stability matches i.e. `nightly-2025-01-01` should only ever be compared against `nightly-*` releases, not `stable-*` or `beta-*`.
Closes #12950

Match release stability for dated Rust toolchain releases

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Files/ProjectBuildFileTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/FileWriters/FileWriterWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Update/PackagesConfigUpdaterTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Files/ProjectBuildFile.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs

When attempting an update with `packages.config`, it was possible that the old `<Import Project="..." />` elements wouldn't get cleaned up eventually resulting in a failing PR.
E.g., the diff might look like this (note that the first import directive is still present, but at PR time that file won't exist because it wasn't restored because it's not in `packages.config`)...
``` diff
<Import Project="..\packages\Some.Package.1.0.0\build\Some.Package.targets" />
+<Import Project="..\packages\Some.Package.2.0.0\build\Some.Package.targets" />
```
...but it was expected to look like this...
``` diff
-<Import Project="..\packages\Some.Package.1.0.0\build\Some.Package.targets" />
+<Import Project="..\packages\Some.Package.2.0.0\build\Some.Package.targets" />
```
Normally NuGet interprets a call to …

always restore packages.config before attempting update

---

bin/dry-run.rb

This PR removes the `exclude path` parameter from `bin/dry-run.rb` because the dry run does not exercise the code path for exclude paths, and passing it causes an `ArgumentError: unknown keyword: :exclude_paths`. This keeps the script focused and prevents confusion or errors. 
closes: https://github.com/dependabot/dependabot-core/issues/12889
This change prevents runtime errors and clarifies that exclude path logic is not supported in dry runs.
Run `bin/dry-run.rb` without the exclude path parameter and confirm there are no `ArgumentError` exceptions. All expected files are processed.

Removing `exclude_paths` from dry-run

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/DiscoveryWorker.cs

This is an attempt to track down a transient bug that I haven't been able to reproduce locally.
The `Microsoft.Azure.Functions.Worker.Sdk` package creates a file under temp named `WorkerExtensions.csproj` that sometimes exists after dependency discovery is complete and is reported in the discovery object.
Later steps of the process then try to track the contents of that file but it has by then been deleted.
To avoid adding a bunch of `if (!File.Exists(...))` checks, this instead excludes any project from discovery that doesn't live under the repo root because no matter what those files may contain, there is nothing we could do for them.

only report discovery for projects in the repo

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
nuget/Dockerfile
nuget/helpers/lib/NuGetUpdater/global.json

This simplifes the devcontainer setup for .NET and adds comments to all locations where SDK versions are specified so everything remains in sync.

update devcontainer to correct sdk version

---

python/lib/dependabot/python/metadata_finder.rb
python/spec/dependabot/python/metadata_finder_spec.rb

`200 https://jfrogghdemo.jfrog.io/artifactory/api/pypi/dependabot-pip/pypi/structlog/json` => PackageDetailsFetcher
`404 https://jfrogghdemo.jfrog.io/artifactory/api/pypi/dependabot-pip/simple/structlog/json` => MetadataFinder
Convert `/simple/` endpoints to `/pypi/` for JSON API access in `MetadataFinder`.
This ensures consistency with `PackageDetailsFetcher` and fixes 404 errors
when accessing private registries like `JFrog Artifactory`.
The issue occurred because MetadataFinder was directly appending /json
to`/simple/` endpoints, while JSON APIs require `/pypi/` endpoints.
Changes:
- Update `possible_listing_urls` method to convert `/simple/` to `/pypi/`
- Add comprehensive test coverage for the URL conversion
- Ensure non-simple endpoints remain unchanged
Fixes metadata retrieval for …

Fix Python MetadataFinder URL construction for private registries

---

updater/lib/dependabot/update_graph_command.rb
updater/spec/dependabot/update_graph_command_spec.rb

This PR resolves a TODO in the `UpdateGraphCommand` to ensure we use a distinct label for unknown errors from this command:
https://github.com/dependabot/dependabot-core/blob/9a3bc9da41f690a8d752fcf8b5c88c7d2269efdb/updater/lib/dependabot/update_graph_command.rb#L17-L24
This PR depends on a backend change before it can ship.
This is primarily validated by tests, but if we get unexpected errors as we work we should start seeing them instrumented correctly.

Use a unique label for unknown graphing errors

---

updater/lib/dependabot/dependency_group_engine.rb
updater/lib/dependabot/updater/group_dependency_selector.rb
updater/lib/dependabot/updater/pattern_specificity_calculator.rb
updater/spec/dependabot/dependency_group_engine_spec.rb
updater/spec/dependabot/dependency_snapshot_spec.rb

This PR introduces pattern scoring to the group engine. The goal is to enhance how dependency groups are evaluated and prioritized by assigning scores to patterns, allowing for more nuanced and flexible grouping logic.
By adding a scoring mechanism, we can:
- Better control which dependencies are grouped together, based on their pattern specificity.
- Resolve conflicts where multiple patterns could apply to a dependency by preferring the highest-scoring (most specific) pattern.
- Lay the groundwork for future enhancements that may require more granular group selection and matching.
This change does not alter the default grouping behavior, but it makes the underlying logic more extensible and predictable.
- Lays the foundation for addressing issues where grouping logic was too coarse or …

Add pattern scoring to group engine

---

updater/lib/github_api/dependency_submission.rb
updater/spec/github_api/dependency_submission_spec.rb

Our `job.correlator` value in Dependency Submission payloads is currently very simple and just states that the submission is from Dependabot for a given ecosystem.
In order to support monorepos where there may be more than one snapshot for each ecosystem, and jobs where multiple directories may be graphed at once, we need to make this unique on the manifest.
I've updated the correlation to do this in a fairly straightforward way, let's just append the manifest path to the value.
We store this value as part of the snapshot so there isn't a strict character length, but I didn't want to leave us handling unbounded strings so I've put in a bytesize check that replaces any path longer than 32 bytes with a SHA256 so we have a stable upper boundary that still remains unique on path.
We start …

Dependency Graphing: Update job.correlator to use the relevant manifest path

---

updater/lib/dependabot/pull_request.rb
updater/spec/dependabot/updater_spec.rb

the job definition from API was sending pr_number ,but it gets transformed into pr-number [here ](https://github.com/dependabot/dependabot-core/blob/5dedf3910282d03f486bb393dd1f225eabc2100a/updater/lib/dependabot/job.rb#L141), but core still expects pr_number [here ](https://github.com/dependabot/dependabot-core/blob/5dedf3910282d03f486bb393dd1f225eabc2100a/updater/lib/dependabot/pull_request.rb#L70)which is wrong
so i fixed that mismatch.
succesfull testing in API

added hyphen to fix mismatch

---

bundler/lib/dependabot/bundler/package/package_details_fetcher.rb
bundler/spec/dependabot/bundler/package/package_details_fetcher_spec.rb

Bundler grouping failed initially because the latest version couldn't be resolved.
Example logs:
```
updater | 2025/09/22 12:54:21 INFO <job_1105772381> Finished job processing
updater | 2025/09/22 12:54:21 INFO Results:
+------------------------------------------+
|   Changes to Dependabot Pull Requests    |
+---------+--------------------------------+
| created | json ( from 2.10.2 to 2.12.2 ) |
| created | json ( from 2.11.0 to 2.12.2 ) |
+---------+--------------------------------+
Cleaned up container 34b53fbba59c1a6662aa5b95f6ad98a4f290d27c6c85a7bdebcc0d18620a6100
```
The latest version was not identified:
```
proxy | 2025/09/22 12:54:14 [024] GET [https://rubygems.pkg.github.com:443/dsp-testing/versions](https://rubygems.pkg.github.com/dsp-testing/versions)
proxy | 2025/09/22 …
```

Add GitHub Package Registry support for Bundler ecosystem.

---

nuget/updater/main.ps1

Don't use string interpolation to pass dynamic arguments to the updater because certain PowerShell special characters can cause issues like `$`, etc.  Instead directly pass the string array to `Start-Process`.

pass arguments directly instead of double-interpolating them

---

go_modules/lib/dependabot/go_modules/file_parser.rb

We're seeing the following issue in some repositories
```
Passed `nil` into T.must
file_parser.rb:70:in 'Dependabot::GoModules::FileParser#go_version
```
The issue is that the `go` directive in `go.mod` files was optional before Go 1.21[^1]. So some projects which rely on vendor dependencies that have not been updated since then will not have the `go` directive.
> The go directive sets the minimum version of Go required to use this module. Before Go 1.21, the directive was advisory only; now it is a mandatory requirement: Go toolchains refuse to use modules declaring newer Go versions.
This change makes it optional in Dependabot as well.
[^1]: https://go.dev/doc/modules/gomod-ref#go

Allow for missing go directive in `go.mod`

---

updater/lib/dependabot/updater/pattern_specificity_calculator.rb
updater/spec/dependabot/updater/pattern_specificity_calculator_spec.rb

Add early return optimization to skip pattern matching when dependency groups have no patterns defined (e.g., groups with only `"update-types" => ["patch"]` rules).
Fixes: https://github.com/dependabot/dependabot-core/issues/13154
Returns false immediately when `rules["patterns"]` is empty, avoiding expensive pattern specificity calculations for rule-based groups.
We will no longer to check patterns when no patterns are present

Skip the pattern Specificity calculator if there is no pattern set

---

nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTestBase.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Discover/DiscoveryWorkerTests.cs
nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Discover/SdkProjectDiscovery.cs

The SDK can add packages to a project restore graph and when it does the extra metadata `IsImplicitlyDefined="true"` is set.  Those packages should still appear in the dependency graph because security jobs might need to update them, but they _shouldn't_ appear as top-level items (even though they technically are) because regular version update jobs shouldn't update them.
The fix is to not report the package as top-level if the `IsImplicitlyDefined` metadata is set and instead report them as transitive dependencies (because they ultimately come through `Microsoft.NET.Sdk`).

mark implicit packages as transitive

---

python/lib/dependabot/python/language_version_manager.rb
python/spec/dependabot/python/file_fetcher_spec.rb

When no explicit Python version is specified in manifest files, Dependabot incorrectly defaults to Python 3.9.23 instead of the latest supported version (3.13.5). This prevents updates to packages like Django 5.2.7 that require Python 3.10+.
Related issue: https://github.com/dependabot/dependabot-core/issues/12256
The `python_version_matching_imputed_requirements` method is incorrectly inferring Python 3.9 (the lowest available version) compatibility from existing dependencies, preventing the fallback to `Language::PRE_INSTALLED_HIGHEST_VERSION`.
With Rspec
With Cli run
```
updater | 2025/10/02 15:34:48 INFO Checking if django 5.2.6 needs updating
updater | 2025/10/02 15:34:48 INFO Fetching release information from json registry at https://pypi.org/pypi/ for django
proxy | 2025/10/02 …
```

Fix Python version defaulting to 3.9 (lowest available) instead of latest when no explicit version specified

---

updater/lib/dependabot/update_graph_processor.rb
updater/spec/dependabot/update_graph_processor_spec.rb

As a hacky workaround, we've been 'guessing' the default branch when a `job.source.branch` is nil by straight up injecting a static string value of `main`.
This won't survive first contact with real-world conditions, so let's do what the PR builder and other components do when this is nil, ask the VCS service.
The updater is fairly hardwired unto GitHub and Update Graph jobs doubly so at present, so I haven't made an effort to instantiate all possible VCS clients based on the `job.source.provider`.
For now, if the provider is anything other than GitHub we will continue to 'guess' that `main` is the default branch rather than  hard fail so CLI users can still pull out data, but we will warn that the default branch is a guess for now.
Since the emitted payload is intended for the Dependency …

[Update Graph] If the `job.source.branch` is nil, this means we need to ask for the default branch
